import type { Article, Specialty } from "@/lib/types";
import { TYPE_META, SPECIALTY_META, formatDate } from "@/lib/meta";
import type { LlmInterestProfile } from "@/lib/llm-interest-profile";

export interface DecoratedArticle extends Article {
  typeLabel: string;
  typeTagClass: string;
  specialtyLabel: string;
  dateLabel: string;
  saved: boolean;
  /** True when published after the reader's previous home-feed visit. Always false
   *  outside the home feed (default param) — the badge only makes sense there. */
  isNew: boolean;
  /** True when this reader has already opened the article (see lib/reading.ts
   *  recordArticleRead, called from the article detail page on every view). Defaults to
   *  false for callers that don't pass readIds — same opt-in shape as sinceVisit/isNew. */
  isRead: boolean;
}

export function decorateArticle(
  a: Article,
  savedIds: string[],
  sinceVisit: Date | null = null,
  readIds: string[] = []
): DecoratedArticle {
  const tm = TYPE_META[a.type];
  return {
    ...a,
    typeLabel: tm.label,
    typeTagClass: "tag " + tm.tag,
    specialtyLabel: SPECIALTY_META[a.specialty],
    dateLabel: formatDate(a.date),
    saved: savedIds.includes(a.id),
    isNew: sinceVisit != null && new Date(a.date).getTime() > sinceVisit.getTime(),
    isRead: readIds.includes(a.id),
  };
}

// Explicit signals — what the reader directly told the app, via Profile's specialty field
// or the onboarding/Profile topic chips. Kept as flat bonuses (same values the original
// binary model used) so a brand-new account with zero reading history still gets a
// sensibly ordered feed on day one, before there's any behavior to build an affinity from.
const SPECIALTY_MATCH_WEIGHT = 2;
const FOLLOWED_TOPIC_WEIGHT = 1;

// Implicit signals — what the reader's actual behavior shows, inferred fresh on every
// ranking rather than cached, since it's cheap arithmetic over rows already fetched for the
// page (see app/(app)/home/page.tsx). A save is a deliberate "I want this later" action, so
// it counts for more than a read, which can be a bounce.
const READ_BASE_WEIGHT = 1.5;
const SAVE_BASE_WEIGHT = 2.5;

// Even a 0%-scrolled read still counts for something — opening an article at all is itself
// a small positive signal — but a completed read counts up to 4x more than a bounce.
const MIN_COMPLETION_FACTOR = 0.25;

// Implicit affinity fades rather than accumulating forever, so a reader's *current*
// interests can still shift the feed even after months of history in a different area —
// roughly half-strength every 3 weeks.
const RECENCY_HALF_LIFE_DAYS = 21;
const DAY_MS = 24 * 60 * 60 * 1000;

// The LLM-inferred profile (see lib/llm-interest-profile.ts) is read straight off a small
// number of named topics rather than hundreds of individual articles the way behavioral
// affinity is, so each one is weighted to land a bit above a single followed-topic toggle —
// it's a synthesized read on *why* someone's reading what they're reading, not just a tally.
const LLM_TOPIC_WEIGHT = 1.75;

function recencyWeight(date: Date, now: number): number {
  const ageDays = Math.max(0, (now - date.getTime()) / DAY_MS);
  return Math.pow(0.5, ageDays / RECENCY_HALF_LIFE_DAYS);
}

export interface RankFeedInput {
  articles: Article[];
  specialty: Specialty;
  followedTopics: string[];
  /** The reader's ReadArticle rows — omit entirely for a caller with no behavioral history
   *  available (falls back to the explicit-signal-only ranking). */
  readRows?: { articleId: string; scrollProgress: number; updatedAt: Date }[];
  savedRows?: { articleId: string; createdAt: Date }[];
  /** Cached async-generated signal (see lib/llm-interest-profile.ts) — null/undefined for
   *  a reader who doesn't have one yet, or whose profile is stale and hasn't been
   *  regenerated by the daily cron. Ranking is fully functional without it; this only ever
   *  sharpens it further once one exists. */
  llmProfile?: LlmInterestProfile | null;
}

/**
 * Personalized ranking. Two layers stack on top of each other:
 *  1. Explicit signals (declared specialty, followed topics) — always available, even for
 *     a reader with no history at all.
 *  2. Implicit affinity, built fresh from ReadArticle/SavedArticle history (what this
 *     reader actually reads and saves, weighted by how much of it they read and how
 *     recently) plus, once one's been generated, the LLM-inferred interest profile.
 * Ties (including the common "no signal at all matched" case) fall back to recency, same
 * as the original model.
 */
export function rankFeed(input: RankFeedInput): Article[] {
  const { articles, specialty, followedTopics, readRows = [], savedRows = [], llmProfile } = input;

  // Case-insensitive throughout: hand-authored seed article tags ("CE credit") and the
  // canonical, classify()-derived topic labels shown in Profile ("Ce Credit") don't always
  // agree on capitalization, and a match should still count even when they don't.
  const followedLower = new Set(followedTopics.map((t) => t.toLowerCase()));

  const now = Date.now();
  const articleById = new Map(articles.map((a) => [a.id, a]));
  const affinity = new Map<string, number>();
  const bump = (key: string, amount: number) => affinity.set(key, (affinity.get(key) ?? 0) + amount);
  const bumpArticleTopics = (article: Article, weight: number) => {
    bump(SPECIALTY_META[article.specialty].toLowerCase(), weight);
    for (const tag of article.tags) bump(tag.toLowerCase(), weight);
  };

  for (const row of readRows) {
    const article = articleById.get(row.articleId);
    if (!article) continue;
    const completion = MIN_COMPLETION_FACTOR + (1 - MIN_COMPLETION_FACTOR) * Math.max(0, Math.min(1, row.scrollProgress));
    bumpArticleTopics(article, READ_BASE_WEIGHT * completion * recencyWeight(row.updatedAt, now));
  }
  for (const row of savedRows) {
    const article = articleById.get(row.articleId);
    if (!article) continue;
    bumpArticleTopics(article, SAVE_BASE_WEIGHT * recencyWeight(row.createdAt, now));
  }
  if (llmProfile) {
    for (const topic of llmProfile.topics) bump(topic.label.toLowerCase(), topic.weight * LLM_TOPIC_WEIGHT);
  }

  const score = (a: Article) => {
    let s = a.specialty === specialty ? SPECIALTY_MATCH_WEIGHT : 0;
    if (a.tags.some((t) => followedLower.has(t.toLowerCase()))) s += FOLLOWED_TOPIC_WEIGHT;
    s += affinity.get(SPECIALTY_META[a.specialty].toLowerCase()) ?? 0;
    for (const tag of a.tags) s += affinity.get(tag.toLowerCase()) ?? 0;
    return s;
  };

  return [...articles].sort((a, b) => {
    const diff = score(b) - score(a);
    if (diff !== 0) return diff;
    return new Date(b.date).getTime() - new Date(a.date).getTime();
  });
}
