/**
 * Rehab Sequence's static case bank (see app/games/rehab-sequence/page.tsx,
 * app/actions/rehab-sequence.ts) — each case is a patient scenario with 8 interventions
 * listed in their correct clinical order, plus a one-sentence rationale for each step's
 * position. The reader sees the 8 interventions shuffled and re-orders them.
 */

export type RehabSequenceCategory =
  | "Musculoskeletal"
  | "Neurological"
  | "Cardiopulmonary"
  | "Pediatrics"
  | "Geriatrics"
  | "Sports"
  | "Wellness";

export type RehabSequenceDifficulty = "beginner" | "intermediate" | "advanced";

export interface RehabSequenceCaseEntry {
  id: number;
  title: string;
  category: RehabSequenceCategory;
  difficulty: RehabSequenceDifficulty;
  context: string;
  /** Exactly 8 strings, in correct clinical order from first to last. */
  interventions: string[];
  /** Exactly 8 strings, one per intervention at the same index. */
  rationale: string[];
}

export const rehabSequenceCases: RehabSequenceCaseEntry[] = [
  {
    id: 1,
    title: "Post-op ACL Reconstruction — Day 1 to Return to Sport",
    category: "Sports",
    difficulty: "intermediate",
    context:
      "22-year-old female soccer player, 8 hours post ACL reconstruction with patellar tendon graft. No complications. Goal is return to competitive sport.",
    interventions: [
      "Edema management — ice, elevation, compression",
      "Quad sets and ankle pumps in bed",
      "Straight leg raises and heel slides",
      "Weight bearing as tolerated — gait training with crutches",
      "Closed chain strengthening — leg press and step-ups",
      "Neuromuscular and proprioceptive training — single leg balance",
      "Running progression — straight line then cutting",
      "Sport-specific drills and return to sport testing — hop tests and LSI above 90%",
    ],
    rationale: [
      "Control acute inflammation and hemarthrosis before initiating active movement",
      "Activate quadriceps and prevent DVT through gentle muscle contraction without joint stress",
      "Restore ROM and maintain quad activation as swelling decreases — still non-weight bearing",
      "Begin loading the graft through controlled weight bearing once quad control is sufficient",
      "Progressively load the graft through functional closed chain patterns when full weight bearing achieved",
      "Restore dynamic joint stability through neuromuscular training before introducing higher speed activities",
      "Reintroduce running loads gradually — straight line before cutting to allow graft maturation",
      "Objective functional testing confirms readiness for full return to sport",
    ],
  },
  {
    id: 2,
    title: "Acute Stroke Rehabilitation — Inpatient to Community",
    category: "Neurological",
    difficulty: "intermediate",
    context:
      "68-year-old male, 3 days post left MCA ischemic stroke. Right hemiparesis, expressive aphasia. Previously independent with all ADLs.",
    interventions: [
      "Bed positioning and PROM to prevent contracture",
      "Bed mobility — rolling and supine to sit",
      "Sitting balance and trunk control at edge of bed",
      "Transfer training — bed to chair",
      "Standing balance and weight shifting",
      "Gait training with appropriate assistive device",
      "Task-specific upper extremity training — constraint-induced movement therapy",
      "Community mobility and stair training for home discharge",
    ],
    rationale: [
      "Prevent secondary complications including contracture and pressure injury during flaccid phase",
      "Establish basic mobility and transfers before standing — fundamental to independence",
      "Core stability and sitting balance required before safe standing",
      "Transfers precede gait — needed for basic independence and safe mobility",
      "Standing balance established before introducing the additional challenge of ambulation",
      "Ambulation builds on established standing balance — progress with appropriate device",
      "Upper extremity task-specific training can begin when patient is medically stable — high repetition drives neuroplasticity",
      "Discharge readiness requires functional community and home mobility skills",
    ],
  },
  {
    id: 3,
    title: "Total Knee Arthroplasty — Day of Surgery to Discharge",
    category: "Musculoskeletal",
    difficulty: "beginner",
    context: "70-year-old male, same day as right TKA. No complications. Goal is discharge to home with outpatient PT.",
    interventions: [
      "Quad sets and ankle pumps in bed",
      "Dangle at edge of bed — assess orthostatic tolerance",
      "Stand with bilateral support — assess weight bearing tolerance",
      "Transfer bed to chair with walker",
      "Ambulate in room with walker — full weight bearing",
      "Ambulate in hallway — increase distance",
      "Negotiate one step with railing",
      "Home exercise program education and discharge",
    ],
    rationale: [
      "Initiate quad activation and DVT prevention immediately post-op before standing",
      "Assess cardiovascular response to position change before full weight bearing",
      "Confirm ability to stand and tolerate weight before advancing to ambulation",
      "Basic transfer skill needed for independence before corridor ambulation",
      "Short distance ambulation in controlled environment before longer distances",
      "Progressive distance builds endurance and confidence for home environment demands",
      "Stair negotiation required if home has steps — must demonstrate before discharge",
      "Patient and caregiver education ensures safe and continued recovery at home",
    ],
  },
  {
    id: 4,
    title: "COPD Pulmonary Rehabilitation — Outpatient Program",
    category: "Cardiopulmonary",
    difficulty: "intermediate",
    context:
      "63-year-old female with GOLD Stage II COPD. Dyspnea with minimal exertion. Referred to 12-week outpatient pulmonary rehab program.",
    interventions: [
      "Baseline assessment — 6MWT, spirometry, Borg dyspnea scale",
      "Breathing retraining — pursed lip and diaphragmatic breathing",
      "Energy conservation techniques and activity pacing",
      "Low intensity walking program — 10 minutes continuous",
      "Progressive aerobic training — cycle ergometer and treadmill",
      "Upper and lower extremity resistance training",
      "Home exercise program establishment",
      "Discharge assessment and long-term maintenance plan",
    ],
    rationale: [
      "Establish baseline function before prescribing exercise intensity",
      "Foundational breathing strategies reduce dyspnea and improve efficiency before exercise begins",
      "Energy conservation reduces unnecessary oxygen demand — prerequisite to safe exercise",
      "Begin aerobic training at low intensity to build tolerance safely",
      "Progressive aerobic training is the primary intervention — increase intensity as tolerance improves",
      "Resistance training added after aerobic base established — improves muscle strength and reduces ventilatory demand",
      "Independent home program established before discharge to maintain gains",
      "Objective reassessment quantifies improvement and guides long-term plan",
    ],
  },
  {
    id: 5,
    title: "Shoulder Rotator Cuff Repair — Post-Surgical Rehab",
    category: "Musculoskeletal",
    difficulty: "intermediate",
    context:
      "48-year-old male, 2 days post-op full thickness supraspinatus repair. In sling. Surgeon protocol — no active shoulder movement for 6 weeks.",
    interventions: [
      "Passive ROM — pendulum exercises only — no active elevation",
      "Elbow, wrist, and hand active ROM out of sling",
      "Scapular retraction exercises — sling on",
      "Active-assisted ROM with pulleys at 6 weeks post-op",
      "Active ROM and early rotator cuff activation — isometrics",
      "Progressive rotator cuff strengthening — resistance bands",
      "Functional strengthening — overhead activities with load",
      "Return to full activity and sport-specific training",
    ],
    rationale: [
      "Maintain ROM during immobilization phase without stressing the repair — passive only per protocol",
      "Prevent distal joint stiffness while keeping shoulder protected",
      "Scapular stability can be addressed safely during immobilization phase",
      "Active-assisted motion begins when repair has adequate initial healing — 6 week milestone",
      "Active ROM and isometrics begin when tissue can tolerate muscle contraction without compromise",
      "Progressive loading through the healing graft after ROM and basic activation established",
      "Functional overhead loading in final phase prepares for real-world demands",
      "Return to sport only after full ROM, strength symmetry, and sport-specific function confirmed",
    ],
  },
  {
    id: 6,
    title: "Lumbar Disc Herniation — Acute to Return to Work",
    category: "Musculoskeletal",
    difficulty: "beginner",
    context:
      "38-year-old male physical education teacher with L4-L5 disc herniation. Positive SLR, left leg radiculopathy. No bowel or bladder symptoms. Goal is return to work.",
    interventions: [
      "Education — pain science, posture, activity modification",
      "Directional preference assessment — McKenzie evaluation",
      "Centralization exercises — repeated extension in prone",
      "Neural mobilization — sciatic nerve flossing",
      "Core stabilization — abdominal bracing and dead bug",
      "Functional movement training — hip hinge and squat pattern",
      "Progressive loading — return to physical activity",
      "Work hardening and return to teaching duties",
    ],
    rationale: [
      "Pain science education reduces fear-avoidance and sets realistic expectations before exercise",
      "Identify direction of preference before prescribing exercise — critical for McKenzie approach",
      "Centralization exercises in direction of preference reduce radiculopathy first",
      "Neural mobilization addresses nerve sensitivity once acute radiculopathy begins to centralize",
      "Core stabilization builds spinal support after pain is controlled",
      "Functional movement patterns prepare for work demands — teaching requires bending and lifting",
      "Progressive loading restores tolerance before return to full activity",
      "Work-specific training and gradual return to teaching duties ensure successful outcome",
    ],
  },
  {
    id: 7,
    title: "Parkinson Disease — Outpatient PT Program",
    category: "Neurological",
    difficulty: "advanced",
    context:
      "72-year-old male with Parkinson disease, Hoehn and Yahr Stage 3. Main complaints are freezing of gait, reduced balance, and difficulty with transfers.",
    interventions: [
      "Baseline assessment — UPDRS, Berg Balance Scale, TUG, 10MWT",
      "LSVT BIG training — high amplitude movement exercises",
      "Cueing strategies — visual floor markers and auditory metronome",
      "Transfer training — sit to stand technique and chair modification",
      "Balance training — static and dynamic in multiple positions",
      "Gait training — stride length, arm swing, cadence with metronome",
      "Dual-task training — walking while counting or carrying objects",
      "Home exercise program and caregiver education",
    ],
    rationale: [
      "Establish baseline to track progress and identify priority impairments",
      "LSVT BIG addresses amplitude — foundational before functional movement training",
      "Cueing strategies address freezing directly — critical safety issue",
      "Transfer training addresses fall risk in highest risk situation — sitting to standing",
      "Balance training builds postural stability needed for safe gait",
      "Gait training targets the specific parameters most impaired — stride and arm swing",
      "Dual-task training is most functional and most challenging — introduced after component skills improved",
      "Independent maintenance and caregiver support ensure long-term safety",
    ],
  },
  {
    id: 8,
    title: "Pediatric Developmental Delay — Early Intervention",
    category: "Pediatrics",
    difficulty: "intermediate",
    context:
      "18-month-old male not yet walking. Rolling and sitting achieved. No other diagnosis. Family very engaged. Early intervention program.",
    interventions: [
      "Parent and caregiver education — handling and facilitation techniques",
      "Floor mobility — transitions from sit to quadruped",
      "Quadruped weight bearing and rocking for upper extremity stability",
      "Kneeling and half-kneeling activities",
      "Supported standing at furniture — cruising",
      "Assisted walking with hands-held support",
      "Independent standing — momentary then sustained",
      "Independent ambulation — first steps to functional walking",
    ],
    rationale: [
      "Caregiver education is the most powerful early intervention tool — they provide daily repetition",
      "Establish floor transitions before upright activities — developmental sequence",
      "Upper extremity weight bearing builds strength and stability needed for later transitions",
      "Kneeling is the developmental bridge between floor and standing",
      "Furniture cruising builds standing tolerance and lateral weight shift",
      "Assisted walking develops reciprocal gait pattern before independent steps",
      "Brief independent standing precedes walking — balance must be established",
      "Independent ambulation is the goal — approached through the full developmental sequence",
    ],
  },
  {
    id: 9,
    title: "Cardiac Rehab Phase I — Post Myocardial Infarction",
    category: "Cardiopulmonary",
    difficulty: "beginner",
    context:
      "58-year-old male, day 2 post inferior MI. Hemodynamically stable. On telemetry. Goal is safe discharge to home and Phase II cardiac rehab referral.",
    interventions: [
      "Education — MI, risk factors, activity precautions, warning signs",
      "Ankle pumps and bed exercises — 1-2 METs",
      "Dangle at bedside — monitor HR, BP, symptoms",
      "Stand at bedside — monitor vital sign response",
      "Walk in room — 50 feet with monitoring",
      "Walk in hallway — 100-200 feet with rest breaks",
      "Stair training — one flight if home has stairs",
      "Discharge education — home activity guidelines and Phase II referral",
    ],
    rationale: [
      "Education first — patient must understand their condition and warning signs before exercising",
      "Gentle activation prevents deconditioning and DVT at lowest MET level",
      "Cardiovascular response to position change assessed before ambulation",
      "Standing tolerance confirmed before ambulation — progressive cardiovascular challenge",
      "Short ambulation with close monitoring before longer distances",
      "Progressive distance builds functional capacity for home discharge",
      "Stair negotiation required for home discharge if home has stairs",
      "Discharge planning and Phase II referral ensure continuity of cardiac rehabilitation",
    ],
  },
  {
    id: 10,
    title: "Hip Fracture — ORIF — Inpatient to Home",
    category: "Geriatrics",
    difficulty: "intermediate",
    context:
      "82-year-old female, post-op day 1 after ORIF right hip fracture. Weight bearing as tolerated per surgeon. Mild dementia. Lives alone.",
    interventions: [
      "Bed positioning — prevent hip dislocation postures",
      "Bed mobility — rolling to unaffected side",
      "Transfer — supine to sit over side of bed",
      "Transfer — sit to stand with walker",
      "Ambulate in room — WBAT with walker",
      "Ambulate in hallway — progressive distance",
      "Functional tasks — toilet transfer and shower chair",
      "Home safety assessment and discharge planning with family",
    ],
    rationale: [
      "Prevent dislocation and skin breakdown during acute phase — positioning is first priority",
      "Bed mobility is the foundation of all subsequent transfers",
      "Sit to supine transition needed before standing",
      "Sit to stand is highest fall risk transfer — establish with maximum assist before progressing",
      "Short distance ambulation in controlled environment first",
      "Progressive distance builds tolerance for home environment demands",
      "Functional task training in bathroom is essential for safe independent living",
      "Safe discharge requires home assessment and family or caregiver involvement given dementia and solo living",
    ],
  },
  {
    id: 11,
    title: "Spinal Cord Injury C6 Complete — Acute to Discharge",
    category: "Neurological",
    difficulty: "advanced",
    context:
      "24-year-old male, complete C6 ASIA A tetraplegia after a diving accident, now medically stable on the acute rehab unit. Goal is maximum independence with wheelchair mobility and transfers using available wrist extension.",
    interventions: [
      "Respiratory training — assisted cough and deep breathing",
      "Bed positioning and passive ROM to prevent contracture",
      "Bed mobility training using momentum and available wrist extension",
      "Sitting balance — long sitting and short sitting tolerance",
      "Wheelchair fitting and propulsion training",
      "Transfer training — sliding board transfers",
      "Tenodesis grasp training for ADL tasks",
      "Community wheelchair skills and home accessibility planning",
    ],
    rationale: [
      "Respiratory function is compromised at this level — protect it before anything else",
      "Prevent contracture in denervated muscle groups before mobility training can build on it",
      "Bed mobility is the entry skill for every transfer that follows, using the one active muscle group available",
      "Trunk control must be established before wheelchair sitting and transfers are safe",
      "A properly fitted chair and propulsion technique are needed before transfer training progresses further",
      "Transfers build directly on sitting balance and wheelchair positioning already achieved",
      "Tenodesis grasp is the functional hand substitute — trained once transfers and positioning are reliable",
      "Independence in the community requires both skills and an accessible environment confirmed before discharge",
    ],
  },
  {
    id: 12,
    title: "Total Hip Arthroplasty Posterior Approach — Day of Surgery to Outpatient",
    category: "Musculoskeletal",
    difficulty: "beginner",
    context:
      "67-year-old female, same day post posterior approach total hip arthroplasty. Standard hip precautions in place. Goal is discharge to home with outpatient follow-up.",
    interventions: [
      "Education on hip precautions — no flexion past 90, no adduction, no internal rotation",
      "Ankle pumps and gluteal sets in bed",
      "Log-roll transfer technique and edge-of-bed sitting",
      "Stand with walker — assess weight bearing tolerance",
      "Ambulate in room with walker maintaining precautions",
      "Ambulate in hallway — increase distance",
      "Practice precaution-safe sit to stand from a raised chair",
      "Discharge education and precaution-safe home exercise program",
    ],
    rationale: [
      "Precautions must be understood before any movement is attempted to protect the new joint",
      "Gentle activation prevents DVT and maintains circulation without violating precautions",
      "A precaution-safe transfer technique is required before the patient can sit up at all",
      "Standing tolerance is confirmed before committing to ambulation",
      "Ambulation in a controlled setting reinforces precaution-safe movement patterns",
      "Progressive distance builds endurance needed for a home discharge",
      "A raised-chair sit to stand pattern must be rehearsed before it is needed unsupervised at home",
      "Discharge requires the patient to demonstrate precaution-safe movement independently",
    ],
  },
  {
    id: 13,
    title: "Pediatric Cerebral Palsy Spastic Diplegia — School-Based PT Program",
    category: "Pediatrics",
    difficulty: "intermediate",
    context:
      "7-year-old with spastic diplegic cerebral palsy, GMFCS Level II, ambulates with bilateral ankle-foot orthoses. School-based PT is targeting classroom and playground participation.",
    interventions: [
      "Review of current orthotics and seating for classroom positioning",
      "Lower extremity stretching to manage spasticity and maintain range",
      "Core and hip strengthening in supported positions",
      "Sit-to-stand and floor-to-stand transitions for classroom transfers",
      "Gait training on level surfaces with orthoses",
      "Stair and ramp negotiation for school building access",
      "Playground mobility — uneven terrain and equipment access",
      "Integration into PE class activities with peer participation goals",
    ],
    rationale: [
      "Positioning and equipment must be optimized first since they affect everything the child does all day",
      "Managing spasticity and range is a prerequisite for any strengthening work to be effective",
      "Proximal strength is the base that transfer and gait training will draw on",
      "Independent transfers are needed for basic classroom participation before gait training is prioritized",
      "Level-surface gait is trained before the added challenge of stairs and ramps",
      "Building-access mobility is addressed once level-surface gait is reliable",
      "Uneven playground terrain is a harder mobility demand, tackled after building mobility is secure",
      "Full participation in PE is the functional goal that all prior skills are now applied toward",
    ],
  },
  {
    id: 14,
    title: "COPD Acute Exacerbation — ICU to Discharge",
    category: "Cardiopulmonary",
    difficulty: "advanced",
    context:
      "71-year-old male admitted to the ICU with a COPD exacerbation requiring BiPAP, now improving and transferred to a medical floor. Significantly deconditioned from the admission.",
    interventions: [
      "Positioning and secretion clearance techniques in bed",
      "Active-assisted range of motion in bed",
      "Sitting at edge of bed with breathing control",
      "Standing with assistance and monitored oxygen saturation",
      "Ambulation with assistive device and supplemental oxygen as needed",
      "Increasing ambulation distance with paced breathing",
      "Basic strength training for upper and lower extremities",
      "Discharge planning with home oxygen and pulmonary rehab referral",
    ],
    rationale: [
      "Secretion clearance and positioning address the acute respiratory issue before any exertion is introduced",
      "Gentle range of motion begins mobilization without taxing limited respiratory reserve",
      "Sitting with breathing control is the first upright challenge, still closely monitored",
      "Standing is introduced only once sitting is tolerated with stable oxygenation",
      "Ambulation follows standing tolerance, with oxygen support if needed for safety",
      "Distance is progressed gradually as paced breathing techniques become more effective",
      "Strength training is added once basic mobility is established and tolerated",
      "Discharge planning finalizes ongoing respiratory support and long-term rehabilitation before leaving the hospital",
    ],
  },
  {
    id: 15,
    title: "Chronic Low Back Pain — Outpatient Program",
    category: "Musculoskeletal",
    difficulty: "intermediate",
    context:
      "45-year-old office worker with 2 years of non-specific chronic low back pain, high fear-avoidance, and reduced activity tolerance. Goal is return to full function and exercise.",
    interventions: [
      "Pain science education and graded exposure explanation",
      "Gentle mobility exercises within comfortable range",
      "Low-load motor control exercises — abdominal bracing",
      "Graded exposure to feared movements — bending and lifting",
      "Progressive strengthening — hip hinge and squat under load",
      "Aerobic conditioning — walking or cycling program",
      "Functional task simulation — work and household tasks",
      "Independent maintenance program and relapse prevention plan",
    ],
    rationale: [
      "Reducing fear-avoidance beliefs is the necessary first step before any loaded exercise is introduced",
      "Gentle mobility rebuilds confidence in movement without provoking symptoms",
      "Basic motor control is trained before the more challenging feared movements are attempted",
      "Graded exposure directly targets the fear-avoidance identified at the start",
      "Progressive strengthening builds real tissue capacity once feared movements are tolerated",
      "Aerobic conditioning is layered in once loaded movement is tolerated without flare-up",
      "Functional simulation ties strength and conditioning gains back to the patient's real daily demands",
      "A self-management plan is the last step, ensuring gains are sustained independently",
    ],
  },
  {
    id: 16,
    title: "Ankle Sprain Grade II — Acute to Return to Sport",
    category: "Sports",
    difficulty: "beginner",
    context:
      "19-year-old collegiate volleyball player with a Grade II lateral ankle sprain sustained landing from a jump 2 days ago. Goal is safe return to competitive play.",
    interventions: [
      "PRICE protocol — protection, rest, ice, compression, elevation",
      "Pain-free range of motion exercises",
      "Weight bearing as tolerated with progressive gait normalization",
      "Proprioceptive training — single leg balance progressions",
      "Strengthening — resisted inversion, eversion, and calf raises",
      "Agility drills — lateral shuffles and cutting",
      "Sport-specific plyometrics — jump landing mechanics",
      "Return to sport testing and taping or bracing plan",
    ],
    rationale: [
      "Controlling acute inflammation is the priority in the first 48 to 72 hours",
      "Restoring pain-free motion is needed before weight bearing is progressed",
      "Normal gait mechanics must be restored before more demanding proprioceptive work begins",
      "Proprioception is a well-documented gap after ankle sprain and must be addressed before agility work",
      "Targeted strengthening supports the ligament and prepares the ankle for higher-demand training",
      "Agility drills test the ankle under sport-relevant multidirectional loads",
      "Plyometric landing mechanics specifically address the jump-landing mechanism of injury",
      "Objective testing and a support plan confirm readiness before returning to full competitive play",
    ],
  },
  {
    id: 17,
    title: "Concussion — Acute to Return to Sport",
    category: "Sports",
    difficulty: "beginner",
    context:
      "17-year-old high school soccer player with a diagnosed concussion after heading a ball collision 3 days ago. Symptoms have started to improve with relative rest.",
    interventions: [
      "Relative rest and symptom monitoring for 24 to 48 hours",
      "Light aerobic activity — walking or stationary bike below symptom threshold",
      "Sport-specific exercise — running drills without head impact risk",
      "Non-contact training drills involving more movement",
      "Full contact practice in controlled setting once cleared by physician",
      "Symptom and cognitive re-assessment at each stage progression",
      "Vestibular and balance training if deficits identified",
      "Medical clearance and full return to competitive play",
    ],
    rationale: [
      "Brief rest limits symptom aggravation immediately after injury before any activity is reintroduced",
      "Light aerobic activity is the first controlled test of exertion tolerance without symptom flare-up",
      "Sport-specific movement is added once basic aerobic exertion is tolerated symptom-free",
      "Non-contact drills add complexity and coordination demand before any collision risk is introduced",
      "Full contact is only reintroduced once every prior non-contact stage has been passed safely",
      "Each stage is gated on the athlete remaining symptom-free, not simply on time elapsed",
      "Any lingering vestibular or balance deficit is addressed directly if a stage progression reveals one",
      "Formal medical clearance confirms safety before returning to unrestricted competitive play",
    ],
  },
  {
    id: 18,
    title: "Frozen Shoulder — Acute Pain Phase to Full ROM",
    category: "Musculoskeletal",
    difficulty: "intermediate",
    context:
      "54-year-old female with 3 months of progressive right shoulder stiffness and pain, now in the acute freezing phase with significant loss of external rotation. No trauma history.",
    interventions: [
      "Pain management education and activity modification",
      "Gentle pendulum and passive range of motion within pain tolerance",
      "Joint mobilization — grade I and II for pain modulation",
      "Active-assisted range of motion as pain allows",
      "Joint mobilization — grade III and IV to address stiffness",
      "Active range of motion and light strengthening",
      "Functional strengthening — reaching and overhead tasks",
      "Return to full activity with maintenance stretching program",
    ],
    rationale: [
      "In the acute freezing phase, controlling pain and avoiding aggravation is the priority before any aggressive technique",
      "Passive motion within pain tolerance maintains what range is available without provoking the irritable joint",
      "Low-grade mobilization further modulates pain in the still-irritable acute phase",
      "Active-assisted motion is introduced once pain has settled enough to tolerate more active effort",
      "Higher-grade mobilization to address capsular stiffness is appropriate once the joint is less irritable",
      "Active motion and light strengthening rebuild capacity once range has meaningfully improved",
      "Functional strengthening applies the regained range to real overhead and reaching tasks",
      "A maintenance program preserves gains once functional range and strength are restored",
    ],
  },
  {
    id: 19,
    title: "Breast Cancer Survivorship — Lymphedema and Upper Extremity Rehab",
    category: "Wellness",
    difficulty: "intermediate",
    context:
      "55-year-old female, 6 weeks post mastectomy with axillary lymph node dissection, now developing early signs of upper extremity lymphedema and shoulder stiffness.",
    interventions: [
      "Skin care and infection precaution education",
      "Gentle shoulder range of motion within surgical precautions",
      "Manual lymphatic drainage techniques",
      "Compression garment fitting and bandaging education",
      "Progressive shoulder strengthening within tolerance",
      "Aerobic exercise to support lymphatic flow",
      "Functional retraining — reaching, dressing, and carrying tasks",
      "Long-term self-management education for lymphedema and activity",
    ],
    rationale: [
      "Infection precaution education is essential first since the affected limb has increased infection risk",
      "Range of motion is restored gently within surgical healing precautions before more active techniques begin",
      "Manual lymphatic drainage directly addresses the emerging lymphedema before it progresses further",
      "Compression fitting extends the benefit of lymphatic drainage between treatment sessions",
      "Strengthening is introduced once swelling is better controlled so it doesn't provoke a flare",
      "Aerobic exercise supports lymphatic flow once the limb tolerates more general exertion",
      "Functional tasks apply the regained motion and strength to real daily demands",
      "A self-management plan ensures the patient can control lymphedema risk independently long-term",
    ],
  },
  {
    id: 20,
    title: "Balance and Fall Prevention — Geriatric Outpatient",
    category: "Geriatrics",
    difficulty: "beginner",
    context:
      "76-year-old female with two falls in the past six months, no injury, referred to outpatient PT for fall risk reduction. Lives alone and wants to remain independent.",
    interventions: [
      "Fall risk assessment — Berg Balance Scale and TUG",
      "Home safety and hazard review",
      "Static balance training — standing on varied surfaces",
      "Dynamic balance training — weight shifting and stepping",
      "Lower extremity strengthening — sit to stand and calf raises",
      "Gait training with attention to speed and obstacle negotiation",
      "Dual-task training — walking while performing a cognitive task",
      "Community exercise program referral and follow-up plan",
    ],
    rationale: [
      "A baseline assessment identifies specific fall risk factors before treatment is planned",
      "Environmental hazards are addressed early since they can cause a fall regardless of PT progress",
      "Static balance is the foundation skill trained before more dynamic challenges",
      "Dynamic balance adds the weight-shifting demand present in real walking",
      "Strength directly supports safe transfers and gait, trained alongside balance progressions",
      "Gait training applies balance and strength gains to functional obstacle-rich walking",
      "Dual-task training reflects real-world walking, which rarely happens without added cognitive demand",
      "A community program and follow-up sustain gains after formal outpatient PT ends",
    ],
  },
  {
    id: 21,
    title: "Wrist Fracture Distal Radius — Post Cast Removal to Full Function",
    category: "Musculoskeletal",
    difficulty: "beginner",
    context:
      "50-year-old female, 6 weeks post distal radius fracture, cast just removed. Significant wrist stiffness and mild grip weakness noted at initial evaluation.",
    interventions: [
      "Edema management and scar mobilization if surgical",
      "Gentle active range of motion — wrist flexion, extension, and forearm rotation",
      "Passive range of motion and joint mobilization for stiffness",
      "Grip and forearm strengthening — putty and light resistance",
      "Progressive wrist strengthening — resisted flexion and extension",
      "Functional task training — jar opening, typing, lifting light objects",
      "Higher-load strengthening for work or sport demands",
      "Return to full unrestricted activity",
    ],
    rationale: [
      "Swelling and any surgical scar are addressed immediately since they limit all subsequent motion work",
      "Gentle active motion is the safest first step to begin restoring range after immobilization",
      "Passive mobilization targets the residual stiffness that active motion alone hasn't resolved",
      "Grip strengthening begins early since grip is functionally important and tolerates light load well",
      "Wrist-specific strengthening follows once basic grip and motion are established",
      "Functional tasks apply the regained strength and motion to daily activities",
      "Higher-load strengthening prepares the wrist for more demanding work or sport tasks",
      "Full unrestricted activity is cleared once strength and function meet the demands required",
    ],
  },
  {
    id: 22,
    title: "Rotator Cuff Tendinopathy — Conservative Outpatient Management",
    category: "Musculoskeletal",
    difficulty: "beginner",
    context:
      "44-year-old male painter with 2 months of gradual-onset shoulder pain with overhead activity, no trauma. MRI shows tendinopathy without full thickness tear.",
    interventions: [
      "Activity modification and pain education",
      "Scapular stabilization exercises",
      "Rotator cuff isometrics for pain modulation",
      "Pain-free active range of motion exercises",
      "Progressive rotator cuff strengthening — resistance bands",
      "Eccentric strengthening for tendon loading",
      "Functional strengthening — overhead reaching with load",
      "Return to full work and recreational activity",
    ],
    rationale: [
      "Reducing aggravating overhead load is the first step to calm the irritated tendon",
      "Scapular control is trained early since poor scapular mechanics often drive cuff overload",
      "Isometrics are well tolerated even by an irritable tendon and help modulate pain",
      "Active motion is progressed once isometric loading is tolerated without symptom flare",
      "Band-resisted strengthening builds tendon capacity once basic active motion is pain-free",
      "Eccentric loading specifically targets tendinopathy once concentric strengthening is tolerated",
      "Functional overhead strengthening applies gains to the painter's actual job demands",
      "Full return to work and recreation is cleared once strength meets those overhead demands",
    ],
  },
  {
    id: 23,
    title: "Patellofemoral Pain Syndrome — Adolescent Athlete",
    category: "Sports",
    difficulty: "beginner",
    context:
      "15-year-old female cross country runner with 6 weeks of anterior knee pain worsened by running and stairs. No swelling or instability on exam.",
    interventions: [
      "Activity modification — reduce aggravating running volume",
      "Pain-free quadriceps and hip strengthening — isometric start",
      "Hip abductor and external rotator strengthening",
      "Quadriceps strengthening progression — closed chain exercises",
      "Running gait analysis and cadence modification",
      "Return to running program — walk-run progression",
      "Sport-specific drills — cutting and hill running",
      "Full return to cross country training and competition",
    ],
    rationale: [
      "Reducing aggravating load is the first step to calm symptoms before strengthening begins",
      "Isometric strengthening is well tolerated even with an irritable joint and builds a strength base",
      "Hip weakness is a well-documented contributor to patellofemoral pain and is addressed early",
      "Closed chain quad strengthening progresses load once isometrics and hip strength are established",
      "Gait and cadence changes address a modifiable running mechanic contributing to joint stress",
      "A graded walk-run progression reintroduces running volume without overloading the healing tissue",
      "Sport-specific drills add the cutting and incline demands of cross country before full return",
      "Full return to training and competition is cleared once all prior stages are tolerated symptom-free",
    ],
  },
  {
    id: 24,
    title: "Plantar Fasciitis — Acute to Full Return to Running",
    category: "Sports",
    difficulty: "beginner",
    context:
      "33-year-old recreational runner with 4 weeks of gradual-onset heel pain, worst with first steps in the morning. Training volume increased significantly one month ago.",
    interventions: [
      "Activity modification — reduce running volume and impact",
      "Calf and plantar fascia stretching",
      "Foot intrinsic muscle strengthening",
      "Manual therapy and self-myofascial release",
      "Progressive loading — eccentric calf raises",
      "Footwear and training load review",
      "Return to running program — gradual mileage progression",
      "Full return to prior training volume",
    ],
    rationale: [
      "Reducing impact load is the first step to allow the irritated fascia to settle",
      "Stretching addresses the tightness commonly associated with plantar fascia overload",
      "Intrinsic foot strengthening builds the support the fascia needs, once acute irritation is reduced",
      "Manual therapy further addresses tissue restriction once tolerated alongside active work",
      "Eccentric loading specifically targets tissue capacity once symptoms are better controlled",
      "Reviewing footwear and the training error that likely caused the overload prevents recurrence",
      "Mileage is reintroduced gradually rather than resuming the training spike that caused the problem",
      "Full training volume resumes only once the graded return has been tolerated without symptom return",
    ],
  },
  {
    id: 25,
    title: "Cervical Radiculopathy — Conservative Outpatient Management",
    category: "Musculoskeletal",
    difficulty: "intermediate",
    context:
      "49-year-old male with 3 weeks of neck pain radiating into the right arm with associated numbness. MRI confirms C6-C7 foraminal narrowing. No red flags present.",
    interventions: [
      "Education on posture and activity modification",
      "Cervical retraction exercises and directional preference assessment",
      "Nerve gliding — median and radial nerve mobilization",
      "Cervical and scapular stabilization exercises",
      "Progressive cervical and upper extremity strengthening",
      "Postural endurance training for prolonged positions",
      "Functional task retraining — desk work and lifting",
      "Return to full work and recreational activity",
    ],
    rationale: [
      "Posture and activity education reduces ongoing nerve root irritation before exercise begins",
      "Directional preference exercises are used first since they can rapidly centralize radicular symptoms",
      "Nerve gliding is introduced once symptoms begin to centralize, addressing nerve mobility directly",
      "Stabilization exercises build a foundation of control once acute nerve irritation is settling",
      "Strengthening is progressed once the spine and nerve tolerate stabilization work without flare-up",
      "Postural endurance addresses the sustained positions that provoked symptoms in daily life",
      "Functional retraining applies gains to the specific desk and lifting demands of the patient's routine",
      "Full return to activity is cleared once function is restored without residual radicular symptoms",
    ],
  },
  {
    id: 26,
    title: "Post Partum Pelvic Floor — Return to Running Program",
    category: "Wellness",
    difficulty: "intermediate",
    context:
      "32-year-old female, 8 weeks postpartum after a vaginal delivery, cleared by her OB for exercise. Reports mild stress urinary incontinence and wants to return to running.",
    interventions: [
      "Pelvic floor and diastasis recti assessment",
      "Diaphragmatic breathing and pelvic floor activation training",
      "Core and pelvic floor coordination exercises",
      "Low-impact strength training — squats and bridges",
      "Impact tolerance testing — jumping and hopping",
      "Walk-jog interval progression",
      "Running-specific strength and gait assessment",
      "Full return to running program",
    ],
    rationale: [
      "A baseline assessment of pelvic floor function and any diastasis guides safe progression",
      "Basic activation and breathing coordination is retrained before any loaded exercise is added",
      "Coordinating the core and pelvic floor together is required before impact activities are safe",
      "Low-impact strength training builds capacity without the higher pelvic floor demand of impact",
      "Impact tolerance is tested in a controlled way before running itself is reintroduced",
      "A graded walk-jog interval progression reintroduces running load without overwhelming healing tissue",
      "Running-specific strength and gait are addressed once basic running tolerance is confirmed",
      "Full running is resumed only once impact tolerance and continence are confirmed symptom-free",
    ],
  },
  {
    id: 27,
    title: "Pediatric Torticollis — Evaluation to Discharge",
    category: "Pediatrics",
    difficulty: "beginner",
    context:
      "8-week-old infant referred for congenital muscular torticollis with a head tilt to the right and reduced left cervical rotation. Mild plagiocephaly noted.",
    interventions: [
      "Full evaluation — range of motion measurement and plagiocephaly screening",
      "Parent education on positioning and handling",
      "Passive stretching of the shortened sternocleidomastoid",
      "Active movement encouragement toward the restricted side",
      "Strengthening of the weaker contralateral neck muscles",
      "Environmental modifications — crib and feeding positioning",
      "Reassessment of range of motion and symmetry",
      "Discharge with home program once symmetry is achieved",
    ],
    rationale: [
      "A thorough evaluation establishes the baseline restriction and any associated skull flattening",
      "Parents provide the majority of daily handling, so their education is prioritized early",
      "Passive stretching directly addresses the shortened muscle causing the head tilt",
      "Active movement is encouraged once passive range improves, building the infant's own control",
      "The weaker side is strengthened to restore muscular balance, not just the tight side's length",
      "Positioning changes during daily routines reinforce therapy gains throughout the day",
      "Reassessment confirms whether symmetry goals are being met before considering discharge",
      "Discharge occurs once symmetry is achieved and the family can maintain gains independently",
    ],
  },
  {
    id: 28,
    title: "Multiple Sclerosis Relapse — Inpatient to Community",
    category: "Neurological",
    difficulty: "advanced",
    context:
      "36-year-old female with relapsing-remitting MS experiencing an acute relapse causing lower extremity weakness and gait instability, admitted for inpatient rehab.",
    interventions: [
      "Fatigue and energy conservation education",
      "Bed mobility and transfer training",
      "Sitting and standing balance training",
      "Lower extremity strengthening within fatigue tolerance",
      "Gait training with appropriate assistive device",
      "Endurance training with rest breaks to manage fatigue",
      "Community mobility and stair training",
      "Home exercise program and outpatient follow-up planning",
    ],
    rationale: [
      "Fatigue is a central feature of MS relapse and must be managed before any exertion-based training",
      "Basic mobility and transfers are restored first, respecting fatigue limits established above",
      "Balance training addresses the instability driving fall risk, building on established transfers",
      "Strengthening is dosed carefully within fatigue tolerance rather than pushed to exhaustion",
      "Gait training applies strength and balance gains with support appropriate to current weakness",
      "Endurance is built gradually with planned rest, respecting the same fatigue principle throughout",
      "Community and stair mobility are addressed once basic gait and endurance are established",
      "A sustainable home program and outpatient plan carry gains forward after this relapse resolves",
    ],
  },
  {
    id: 29,
    title: "ICU Acquired Weakness — Early Mobility Program",
    category: "Cardiopulmonary",
    difficulty: "advanced",
    context:
      "60-year-old male, 10 days in the ICU following sepsis, now hemodynamically stable but with significant generalized weakness limiting basic mobility.",
    interventions: [
      "Bedside assessment of strength, sedation level, and hemodynamic stability",
      "Passive and active-assisted range of motion in bed",
      "Bed mobility training — rolling and scooting",
      "Sitting at edge of bed with trunk control training",
      "Sit to stand training with maximum assist as needed",
      "Standing tolerance and weight bearing progression",
      "Ambulation with assistive device and close monitoring",
      "Progressive mobility and strength training toward pre-ICU function",
    ],
    rationale: [
      "Confirming stability and current strength level is required before any mobilization is attempted safely",
      "Gentle range of motion is the safest starting point given profound generalized weakness",
      "Bed mobility is trained next as the foundation for all higher-level mobility",
      "Sitting balance and trunk control are established before standing is attempted",
      "Sit to stand is practiced with full support given the severity of weakness at this stage",
      "Standing tolerance is built gradually once the transfer itself is safely achieved",
      "Ambulation is introduced once standing is tolerated, with monitoring given ongoing medical fragility",
      "Continued progressive training moves the patient from basic mobility back toward prior function",
    ],
  },
  {
    id: 30,
    title: "Lateral Epicondylitis — Conservative Management",
    category: "Musculoskeletal",
    difficulty: "beginner",
    context:
      "41-year-old carpenter with 6 weeks of lateral elbow pain aggravated by gripping tools. Diagnosed with lateral epicondylitis, no prior treatment attempted.",
    interventions: [
      "Activity modification and load reduction education",
      "Pain-free wrist and forearm range of motion",
      "Isometric wrist extensor strengthening for pain modulation",
      "Manual therapy and soft tissue mobilization",
      "Progressive eccentric wrist extensor strengthening",
      "Grip strengthening and forearm endurance training",
      "Functional task simulation — gripping and tool use",
      "Return to full work duties",
    ],
    rationale: [
      "Reducing aggravating gripping load is the first step to allow the tendon to settle",
      "Gentle range of motion maintains mobility without stressing the irritated tendon",
      "Isometric loading is well tolerated even by an irritable tendon and helps modulate pain",
      "Manual therapy addresses soft tissue restriction once isometric loading is tolerated",
      "Eccentric loading specifically targets tendon capacity once basic isometric strength is established",
      "Grip and forearm endurance are built once the tendon tolerates progressive eccentric loading",
      "Functional simulation applies strength gains to the carpenter's actual tool-use demands",
      "Full work duties resume once functional tasks are tolerated without symptom recurrence",
    ],
  },
  {
    id: 31,
    title: "Knee Osteoarthritis — Conservative Outpatient Management",
    category: "Geriatrics",
    difficulty: "beginner",
    context:
      "69-year-old female with bilateral knee osteoarthritis, worse on the right, causing pain with walking and stairs. Not yet a surgical candidate per her orthopedist.",
    interventions: [
      "Education on activity modification and joint protection",
      "Pain-free range of motion exercises",
      "Quadriceps and hip strengthening — isometric and low load",
      "Low-impact aerobic exercise — stationary bike or pool",
      "Progressive strengthening — closed chain exercises",
      "Balance and proprioceptive training",
      "Functional task training — stairs and sit to stand",
      "Long-term self-management and exercise maintenance plan",
    ],
    rationale: [
      "Understanding joint protection principles helps the patient avoid unnecessary aggravation from the start",
      "Restoring comfortable range of motion is addressed before adding any strengthening load",
      "Low-load strengthening builds a foundation of quad and hip support for the joint",
      "Low-impact aerobic exercise improves overall conditioning without excessive joint loading",
      "Closed chain strengthening progresses load once the joint tolerates low-load work well",
      "Balance training reduces fall risk that can accompany knee instability and pain",
      "Functional training applies strength and balance gains to the specific tasks that were limited",
      "A long-term plan sustains gains since osteoarthritis management is ongoing, not a fixed endpoint",
    ],
  },
  {
    id: 32,
    title: "Shoulder Instability — Post First-Time Dislocation Conservative Management",
    category: "Sports",
    difficulty: "intermediate",
    context:
      "21-year-old male recreational basketball player, 1 week after a first-time anterior shoulder dislocation, reduced in the emergency department. Electing conservative management.",
    interventions: [
      "Sling immobilization and pain management education",
      "Pendulum and passive range of motion within protected range",
      "Active-assisted range of motion avoiding provocative positions",
      "Rotator cuff and scapular stabilization strengthening",
      "Progressive strengthening avoiding abduction-external rotation combined end range",
      "Proprioceptive and neuromuscular control training",
      "Sport-specific strengthening and controlled return to overhead activity",
      "Return to sport with continued stability maintenance program",
    ],
    rationale: [
      "A brief period of protected immobilization allows initial capsular healing before motion is progressed",
      "Passive motion within a protected range is the safest way to begin restoring mobility",
      "Active-assisted motion is added while still avoiding the position most likely to re-provoke instability",
      "Dynamic stabilizers are strengthened early since they compensate for the injured static restraints",
      "Strengthening is progressed carefully around the specific vulnerable position rather than into it",
      "Neuromuscular control training addresses the proprioceptive deficit that follows a dislocation",
      "Sport-specific strengthening reintroduces overhead demand only once stability control is established",
      "Return to sport is paired with an ongoing program since recurrence risk remains after a first dislocation",
    ],
  },
  {
    id: 33,
    title: "Patellar Tendinopathy — Jumping Athlete",
    category: "Sports",
    difficulty: "intermediate",
    context:
      "24-year-old male volleyball player with 8 weeks of anterior knee pain at the patellar tendon, worse with jumping and landing. Training load has been high all season.",
    interventions: [
      "Load management — reduce jumping volume in training",
      "Isometric quadriceps loading for pain modulation",
      "Pain-monitored isotonic strengthening — leg extension and squats",
      "Progressive heavy slow resistance training",
      "Energy storage and release exercises — controlled landing drills",
      "Plyometric progression — low to high intensity jumps",
      "Sport-specific jump and landing retraining",
      "Full return to volleyball training and competition",
    ],
    rationale: [
      "Reducing the aggravating jump load is the necessary first step for an overloaded tendon",
      "Isometric loading provides pain relief and is tolerated even by an irritable tendon",
      "Isotonic strengthening is added once isometric loading is well tolerated without symptom flare",
      "Heavy slow resistance training builds the tendon capacity needed for jumping sports",
      "Controlled landing drills reintroduce energy storage and release demand in a lower-risk way",
      "Plyometrics are progressed gradually since they replicate the jumping mechanism that caused overload",
      "Sport-specific landing retraining addresses landing mechanics directly tied to the injury",
      "Full return to competition is cleared once jump and landing tolerance is confirmed symptom-free",
    ],
  },
  {
    id: 34,
    title: "Hamstring Strain Grade II — Acute to Return to Sprint",
    category: "Sports",
    difficulty: "intermediate",
    context:
      "26-year-old male sprinter with a Grade II hamstring strain sustained during a race 3 days ago. MRI confirms a moderate strain at the myotendinous junction.",
    interventions: [
      "Protection and relative rest — avoid stretching or loading the tear",
      "Pain-free range of motion and gentle isometrics",
      "Progressive isotonic strengthening — bridges and light Nordic curls",
      "Eccentric strengthening progression — Nordic hamstring exercise",
      "Running progression — jogging to striding",
      "Sprint mechanics drills at submaximal effort",
      "Progressive sprint training toward maximal velocity",
      "Return to competition with continued eccentric maintenance program",
    ],
    rationale: [
      "Protecting the healing tissue from further strain is the priority in the first few days",
      "Gentle motion and isometrics are introduced once acute pain allows without stressing the healing tear",
      "Isotonic strengthening builds tissue capacity once basic pain-free contraction is tolerated",
      "Eccentric strengthening specifically addresses the mechanism most associated with reinjury",
      "A gradual running progression reintroduces speed without jumping straight to full sprinting",
      "Submaximal sprint drills refine mechanics before maximal effort is attempted",
      "Maximal velocity sprinting is the highest hamstring demand and is reintroduced last",
      "An ongoing eccentric program continues after return to competition given high reinjury risk",
    ],
  },
  {
    id: 35,
    title: "Spondylolisthesis — Adolescent Conservative Management",
    category: "Musculoskeletal",
    difficulty: "advanced",
    context:
      "14-year-old female gymnast with a Grade I L5-S1 spondylolisthesis causing low back pain worse with extension. Electing conservative management with activity modification.",
    interventions: [
      "Activity modification — avoid extension and high-impact loading",
      "Core stabilization in neutral spine — abdominal bracing",
      "Hamstring and hip flexor flexibility work",
      "Pain-free lumbopelvic control exercises",
      "Progressive core and gluteal strengthening",
      "Functional movement retraining avoiding excessive lumbar extension",
      "Gradual return to sport-specific movement with modified technique",
      "Full return to gymnastics with an ongoing core maintenance program",
    ],
    rationale: [
      "Removing the extension-based loading that aggravates the slip is the essential first step",
      "Core bracing in a neutral spine is trained first to reduce shear stress at the defect",
      "Flexibility work addresses common contributors to compensatory lumbar extension",
      "Lumbopelvic control exercises are progressed once basic bracing is mastered and pain-free",
      "Strengthening builds the muscular support needed to protect the spine long-term",
      "Functional retraining ensures daily and sport movement patterns avoid the aggravating extension",
      "Sport-specific movement is reintroduced gradually with technique modified to protect the spine",
      "Full return to gymnastics is paired with ongoing core work given the structural nature of the diagnosis",
    ],
  },
  {
    id: 36,
    title: "Dementia and Fall Risk — Geriatric Care Facility Program",
    category: "Geriatrics",
    difficulty: "advanced",
    context:
      "84-year-old male with moderate dementia residing in a skilled nursing facility, with three falls in the past month. Limited ability to follow multi-step verbal instructions.",
    interventions: [
      "Fall risk and cognitive-communication assessment",
      "Environmental and staff safety education",
      "Simple one-step verbal and demonstration-based cueing for exercise",
      "Seated strengthening exercises using imitation-based instruction",
      "Standing balance activities with hands-on guarding",
      "Functional transfer practice — bed, chair, and toilet",
      "Supervised gait training with consistent routine and cues",
      "Caregiver training for ongoing safe mobility support",
    ],
    rationale: [
      "Understanding both fall risk factors and how the patient best receives instruction shapes every step that follows",
      "Environmental changes and staff awareness reduce risk immediately, independent of the patient's own progress",
      "Instruction must be simplified to match cognitive ability before any exercise can be taught successfully",
      "Seated strengthening is the safest starting point and uses the imitation-based cueing just established",
      "Standing balance is introduced with hands-on guarding given both fall history and cognitive limitations",
      "Functional transfers are practiced directly since they are tied to his actual daily fall risk moments",
      "Gait training uses a consistent routine, since dementia patients respond better to repeated, familiar cues",
      "Caregiver training ensures the same safe strategies are used consistently outside of therapy sessions",
    ],
  },
  {
    id: 37,
    title: "Post-Concussion Vestibular Rehab — Return to School Protocol",
    category: "Neurological",
    difficulty: "advanced",
    context:
      "16-year-old female with persistent dizziness and visual motion sensitivity 4 weeks after a concussion, significantly limiting her ability to attend school.",
    interventions: [
      "Vestibular and oculomotor assessment",
      "Habituation exercises for symptom-provoking head movements",
      "Gaze stabilization exercises — VOR x1 training",
      "Static and dynamic balance training",
      "Visual motion desensitization — busy visual environments",
      "Graded return to school activities — short periods with breaks",
      "Increasing academic and screen-time tolerance",
      "Full return to school and extracurricular activities",
    ],
    rationale: [
      "A specific vestibular and oculomotor assessment identifies which systems are driving her symptoms",
      "Habituation targets the specific movements identified as provoking, in a controlled and graded way",
      "Gaze stabilization is added once basic habituation is tolerated, targeting the vestibulo-ocular reflex directly",
      "Balance training builds on improving vestibular function to address broader postural control",
      "Visual motion desensitization addresses the busy-environment sensitivity limiting school attendance",
      "A graded return to school in short tolerated periods prevents the all-or-nothing relapse of full days too soon",
      "Academic and screen time are increased incrementally as tolerance is demonstrated at each step",
      "Full return to school and activities is cleared once all prior graded steps are tolerated symptom-free",
    ],
  },
  {
    id: 38,
    title: "Hip Labral Tear Conservative Management — Pre-Surgical Optimization",
    category: "Sports",
    difficulty: "advanced",
    context:
      "29-year-old female dancer with an MRI-confirmed anterosuperior labral tear, pursuing a trial of conservative management and pre-surgical strengthening before deciding on surgery.",
    interventions: [
      "Activity modification — reduce provocative hip flexion and pivoting",
      "Core and lumbopelvic stabilization exercises",
      "Pain-free hip strengthening — isometric start",
      "Hip external rotator and gluteal strengthening",
      "Progressive closed chain hip strengthening",
      "Movement pattern retraining — squat and pivot mechanics",
      "Sport-specific strengthening within pain-free range",
      "Functional dance-specific retraining and decision point for surgical referral",
    ],
    rationale: [
      "Reducing the specific movements that provoke labral symptoms is the first step to calm the joint",
      "Core and pelvic stability reduce compensatory hip stress and are safe even with an irritable joint",
      "Isometric hip strengthening builds a base of muscular support without high joint shear",
      "The external rotators and glutes are specifically targeted since they support femoral head stability",
      "Closed chain strengthening progresses load once isolated hip strengthening is well tolerated",
      "Movement retraining addresses the pivoting and deep flexion mechanics common to dance-related labral stress",
      "Sport-specific strengthening is only added within a pain-free range given the structural pathology",
      "Dance-specific function is reassessed at this final stage to guide the surgical versus continued conservative decision",
    ],
  },
  {
    id: 39,
    title: "Achilles Tendon Rupture — Post-Surgical Rehabilitation",
    category: "Sports",
    difficulty: "advanced",
    context:
      "34-year-old recreational basketball player, 1 week post surgical repair of a complete Achilles tendon rupture. In a protective boot, non-weight bearing per surgeon protocol.",
    interventions: [
      "Non-weight bearing period with boot immobilization",
      "Ankle pumps within protocol-allowed range only",
      "Progressive weight bearing in boot per surgeon timeline",
      "Active range of motion out of boot once cleared",
      "Gentle calf strengthening — isometric and light resistance",
      "Progressive strengthening — double to single leg heel raises",
      "Balance and proprioceptive retraining",
      "Return to running and jumping progression toward sport",
    ],
    rationale: [
      "Protecting the surgical repair from load is the priority in the earliest healing phase",
      "Even early ankle motion must stay strictly within the protocol to avoid overstressing the repair",
      "Weight bearing is reintroduced only on the surgeon's timeline, since the repaired tendon dictates the pace",
      "Motion out of the boot is added once tissue healing allows unprotected active movement",
      "Gentle strengthening begins cautiously given how recently the tendon was fully ruptured and repaired",
      "Strengthening is progressed from double to single leg only once basic calf strength is restored",
      "Balance training addresses the proprioceptive deficit that follows both injury and prolonged immobilization",
      "Running and jumping are reintroduced last, as the highest tensile demands the healed tendon will face",
    ],
  },
  {
    id: 40,
    title: "Wellness — General Deconditioning — Sedentary Adult Return to Exercise",
    category: "Wellness",
    difficulty: "beginner",
    context:
      "47-year-old male, largely sedentary for several years, referred for general deconditioning after a routine physical noted low cardiovascular fitness and muscle weakness.",
    interventions: [
      "Baseline fitness assessment and medical clearance review",
      "Education on safe exercise progression and warning signs",
      "Low-intensity walking program — short duration",
      "Basic bodyweight strengthening — sit to stand, wall push-ups",
      "Progressive aerobic duration and intensity increases",
      "Progressive resistance training with light equipment",
      "Functional and recreational activity integration",
      "Independent exercise program and long-term maintenance plan",
    ],
    rationale: [
      "A baseline assessment and medical clearance ensure the exercise program starts at a safe level",
      "Education on safe progression prevents the common error of doing too much too soon after years of inactivity",
      "Low-intensity walking is the gentlest entry point for someone significantly deconditioned",
      "Simple bodyweight strengthening builds basic capacity without needing equipment or high skill",
      "Aerobic duration and intensity are increased gradually once the initial low-intensity phase is tolerated",
      "Resistance training with light equipment is added once basic bodyweight strength is established",
      "Functional and recreational activities reconnect the exercise program to enjoyable, sustainable habits",
      "An independent, long-term plan ensures the fitness gains continue beyond the supervised program",
    ],
  },
];
