// Generated by scripts/fetch-retraction-watch.mjs from
// https://gitlab.com/crossref/retraction-watch-data at commit 893860dd47c7c08efe7b179a08c4fcde8fe9d9f7.
// A real, point-in-time snapshot — not fetched live (see the script for why).
// Re-run the script to refresh.
import type { Article } from "@/lib/types";

export const RETRACTION_WATCH_ARTICLES: Article[] = [
  {
    "id": "rw-65196",
    "type": "research",
    "specialty": "ortho",
    "title": "Acceptance and commitment therapy for the treatment of depression in persons with physical disability: a randomized controlled trial",
    "source": "Clinical Rehabilitation",
    "sourceUrl": "https://doi.org/10.1177/02692155251345412",
    "date": "2025-06-05",
    "readMins": 3,
    "summary": "Retraction issued on 2025-06-05 by Clinical Rehabilitation: Concerns/Issues about Data; Investigation by Journal/Publisher; Investigation by Third Party. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Concerns/Issues about Data; Investigation by Journal/Publisher; Investigation by Third Party"
  },
  {
    "id": "rw-69756",
    "type": "research",
    "specialty": "ortho",
    "title": "Comparison of muscle activities during bench press at different angles in beginners",
    "source": "Journal of Physical Therapy Science",
    "sourceUrl": "https://doi.org/10.1589/jpts.37.48r1",
    "date": "2025-04-01",
    "readMins": 3,
    "summary": "Retraction issued on 2025-04-01 by Journal of Physical Therapy Science. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Flagged by Retraction Watch, see notice for details."
  },
  {
    "id": "rw-55795",
    "type": "research",
    "specialty": "ortho",
    "title": "Task-oriented exercises and early full weight-bearing contribute to improving disability after total hip replacement: a randomized controlled trial",
    "source": "Clinical Rehabilitation",
    "sourceUrl": "https://retractionwatch.com/2022/11/09/pain-researchers-lose-three-papers-after-cochrane-group-questioned-data/",
    "date": "2024-08-15",
    "readMins": 3,
    "summary": "Retraction issued on 2024-08-15 by Clinical Rehabilitation: Concerns/Issues about Data; Investigation by Journal/Publisher; Investigation by Third Party. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Concerns/Issues about Data; Investigation by Journal/Publisher; Investigation by Third Party"
  },
  {
    "id": "rw-55864",
    "type": "research",
    "specialty": "ortho",
    "title": "How balance task-specific training contributes to improving physical function in older subjects undergoing rehabilitation following hip fracture: a randomized controlled trial",
    "source": "Clinical Rehabilitation",
    "sourceUrl": "https://doi.org/10.1177/02692155241265796",
    "date": "2024-08-15",
    "readMins": 3,
    "summary": "Retraction issued on 2024-08-15 by Clinical Rehabilitation: Concerns/Issues about Data; Investigation by Journal/Publisher; Investigation by Third Party. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Concerns/Issues about Data; Investigation by Journal/Publisher; Investigation by Third Party"
  },
  {
    "id": "rw-55909",
    "type": "research",
    "specialty": "neuro",
    "title": "'Regent Suit' training improves recovery of motor and daily living activities in subjects with subacute stroke: a randomized controlled trial",
    "source": "Clinical Rehabilitation",
    "sourceUrl": "https://retractionwatch.com/2022/11/09/pain-researchers-lose-three-papers-after-cochrane-group-questioned-data/",
    "date": "2024-08-15",
    "readMins": 3,
    "summary": "Retraction issued on 2024-08-15 by Clinical Rehabilitation: Concerns/Issues about Data; Investigation by Journal/Publisher; Investigation by Third Party. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Concerns/Issues about Data; Investigation by Journal/Publisher; Investigation by Third Party"
  },
  {
    "id": "rw-55907",
    "type": "research",
    "specialty": "ortho",
    "title": "How balance task-specific training contributes to improving physical function in older subjects undergoing rehabilitation following hip fracture: a randomized controlled trial",
    "source": "Clinical Rehabilitation",
    "sourceUrl": "https://retractionwatch.com/2022/11/09/pain-researchers-lose-three-papers-after-cochrane-group-questioned-data/",
    "date": "2023-07-27",
    "readMins": 3,
    "summary": "Expression of concern issued on 2023-07-27 by Clinical Rehabilitation: Concerns/Issues about Data; Investigation by Journal/Publisher; Updated to Retraction. See the retraction notice for full details.",
    "tags": [
      "Expression of concern"
    ],
    "reviewStatus": "Expression of concern",
    "underReview": "Concerns/Issues about Data; Investigation by Journal/Publisher; Updated to Retraction"
  },
  {
    "id": "rw-55908",
    "type": "research",
    "specialty": "ortho",
    "title": "Task-oriented exercises and early full weight-bearing contribute to improving disability after total hip replacement: a randomized controlled trial",
    "source": "Clinical Rehabilitation",
    "sourceUrl": "https://retractionwatch.com/2022/11/09/pain-researchers-lose-three-papers-after-cochrane-group-questioned-data/",
    "date": "2023-07-27",
    "readMins": 3,
    "summary": "Expression of concern issued on 2023-07-27 by Clinical Rehabilitation: Concerns/Issues about Data; Investigation by Journal/Publisher; Updated to Retraction. See the retraction notice for full details.",
    "tags": [
      "Expression of concern"
    ],
    "reviewStatus": "Expression of concern",
    "underReview": "Concerns/Issues about Data; Investigation by Journal/Publisher; Updated to Retraction"
  },
  {
    "id": "rw-55910",
    "type": "research",
    "specialty": "neuro",
    "title": "'Regent Suit' training improves recovery of motor and daily living activities in subjects with subacute stroke: a randomized controlled trial",
    "source": "Clinical Rehabilitation",
    "sourceUrl": "https://retractionwatch.com/2022/11/09/pain-researchers-lose-three-papers-after-cochrane-group-questioned-data/",
    "date": "2023-07-27",
    "readMins": 3,
    "summary": "Expression of concern issued on 2023-07-27 by Clinical Rehabilitation: Concerns/Issues about Data; Investigation by Journal/Publisher; Updated to Retraction. See the retraction notice for full details.",
    "tags": [
      "Expression of concern"
    ],
    "reviewStatus": "Expression of concern",
    "underReview": "Concerns/Issues about Data; Investigation by Journal/Publisher; Updated to Retraction"
  },
  {
    "id": "rw-40008",
    "type": "research",
    "specialty": "ortho",
    "title": "Multidisciplinary program based on early management of psychological factors reduces disability of patients with subacute low back pain: one-year results of a randomized controlled study",
    "source": "European Journal of Physical and Rehabilitation Medicine",
    "sourceUrl": "https://retractionwatch.com/2022/11/09/pain-researchers-lose-three-papers-after-cochrane-group-questioned-data/",
    "date": "2022-10-24",
    "readMins": 3,
    "summary": "Retraction issued on 2022-10-24 by European Journal of Physical and Rehabilitation Medicine: Error in Data. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Error in Data"
  },
  {
    "id": "rw-39040",
    "type": "research",
    "specialty": "ortho",
    "title": "Multimodal exercises integrated with cognitive-behavioural therapy improve disability of patients with failed back surgery syndrome: a randomized controlled trial with one-year follow-up",
    "source": "Disability and Rehabilitation",
    "sourceUrl": "https://retractionwatch.com/2022/11/09/pain-researchers-lose-three-papers-after-cochrane-group-questioned-data/",
    "date": "2022-09-13",
    "readMins": 3,
    "summary": "Retraction issued on 2022-09-13 by Disability and Rehabilitation: Concerns/Issues about Data; Unreliable Data. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Concerns/Issues about Data; Unreliable Data"
  },
  {
    "id": "rw-38885",
    "type": "research",
    "specialty": "ortho",
    "title": "Group-based multimodal exercises integrated with cognitive-behavioural therapy improve disability, pain and quality of life of subjects with chronic neck pain: a randomized controlled trial with one-year follow-up",
    "source": "Clinical Rehabilitation",
    "sourceUrl": "https://retractionwatch.com/2022/11/09/pain-researchers-lose-three-papers-after-cochrane-group-questioned-data/",
    "date": "2022-09-07",
    "readMins": 3,
    "summary": "Retraction issued on 2022-09-07 by Clinical Rehabilitation: Concerns/Issues about Data; Concerns/Issues about Results and/or Conclusions; Unreliable Results and/or Conclusions. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Concerns/Issues about Data; Concerns/Issues about Results and/or Conclusions; Unreliable Results and/or Conclusions"
  },
  {
    "id": "rw-24392",
    "type": "research",
    "specialty": "ortho",
    "title": "Beneficial Effect of Etidronate on Bone Loss After Cessation of Exercise in Postmenopausal Osteoporotic Women",
    "source": "American Journal of Physical Medicine & Rehabilitation",
    "sourceUrl": "http://retractionwatch.com/?s=%22jun+iwamoto%22",
    "date": "2021-02-01",
    "readMins": 3,
    "summary": "Retraction issued on 2021-02-01 by American Journal of Physical Medicine & Rehabilitation: Concerns/Issues about Data; Concerns/Issues about Results and/or Conclusions; Duplication of Text. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Concerns/Issues about Data; Concerns/Issues about Results and/or Conclusions; Duplication of Text"
  },
  {
    "id": "rw-28897",
    "type": "research",
    "specialty": "ortho",
    "title": "The blood flow restriction training effect in knee osteoarthritis people: A systematic review and meta-analysis",
    "source": "Clinical Rehabilitation",
    "sourceUrl": "https://doi.org/10.1177/0269215521990590",
    "date": "2021-01-20",
    "readMins": 3,
    "summary": "Retraction issued on 2021-01-20 by Clinical Rehabilitation: Error in Analyses; Error in Data; Error in Text. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Error in Analyses; Error in Data; Error in Text"
  },
  {
    "id": "rw-24265",
    "type": "research",
    "specialty": "ortho",
    "title": "Call for applications for the Journal of Physiotherapy Editorial Fellowship",
    "source": "Journal of Physiotherapy",
    "sourceUrl": "https://doi.org/10.1016/j.jphys.2020.08.003",
    "date": "2020-09-15",
    "readMins": 3,
    "summary": "Reinstatement issued on 2020-09-15 by Journal of Physiotherapy: Retract and Replace; Temporary Removal; Removed. See the retraction notice for full details.",
    "tags": [
      "Reinstatement"
    ],
    "reviewStatus": "Reinstatement",
    "underReview": "Retract and Replace; Temporary Removal; Removed"
  },
  {
    "id": "rw-37992",
    "type": "research",
    "specialty": "ortho",
    "title": "Instrument assisted soft tissue mobilization decreases pain intensity and fatigue perception after long-distance ironman triathlon",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.021",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-37993",
    "type": "research",
    "specialty": "ortho",
    "title": "The association of ankle dorsiflexion range of motion and dynamic knee valgus: A systematic review with meta-analysis",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.020",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-37994",
    "type": "research",
    "specialty": "ortho",
    "title": "Influence of bikefit in lower limb biomechanics in road cyclists",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.030",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38219",
    "type": "research",
    "specialty": "sports",
    "title": "Comparison of isokinetic ankle force and plyometric tests in professional handball athletes",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.018",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38220",
    "type": "research",
    "specialty": "ortho",
    "title": "There are differences between cryotherapy techniques applied to the ankle in skin superficial temperature, agility, and equilibrium: Analysis between ice pack, immersion in cold water, and game ready",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.010",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38221",
    "type": "research",
    "specialty": "sports",
    "title": "Clinimetric properties of the forward step-down test qualitative assessment in athletes",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.029",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38222",
    "type": "research",
    "specialty": "ortho",
    "title": "Posterior shoulder tightness, joint position sense, and shoulder strength in subjects with and without glenohumeral internal rotation deficit",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.007",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38223",
    "type": "research",
    "specialty": "ortho",
    "title": "Influence of patellofemoral pain syndrome in functional perfomance of young women",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.019",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38224",
    "type": "research",
    "specialty": "ortho",
    "title": "Comparison of musculoskeletal resources among individuals with different performances in a single leg squat task",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.006",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38225",
    "type": "research",
    "specialty": "ortho",
    "title": "Cold water immersion effects on doms, muscle recruitment, dynamic postural control and sleep quality in soccer players: A randomized and blinded study",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.017",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of/in Article; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of/in Article; Removed"
  },
  {
    "id": "rw-38246",
    "type": "research",
    "specialty": "ortho",
    "title": "Static stretching program decrease the eccentric peak torque without changing the functional perfomance in healthy adults: A Randomized controlled trial",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.012",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38247",
    "type": "research",
    "specialty": "ortho",
    "title": "Evaluation of stiffness in the HIP’S lateral rotator muscles of professional soccer players",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.024",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38248",
    "type": "research",
    "specialty": "ortho",
    "title": "Transcultural adaptation and measurement properties of the Brazilian version of the victorian institute of sport assessment-achilles (VISA-A) questionnaire",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.028",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38249",
    "type": "research",
    "specialty": "ortho",
    "title": "Effect of adhesive elastic tape on excessive pronation of young women",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.026",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38250",
    "type": "research",
    "specialty": "ortho",
    "title": "Nonlinear association of the predictive factors for dynamic knee valgus during the forward step-down test in young athletes",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.014",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38251",
    "type": "research",
    "specialty": "sports",
    "title": "Neuromuscular electrical stimulation during blood flow restriction promotes altered muscle electrical activity and improves balance in high-performance basketball athletes. Blind randomized clinical trial",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.016",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38252",
    "type": "research",
    "specialty": "ortho",
    "title": "The number of repetitions does not influence the forward step-down test performance",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.015",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38263",
    "type": "research",
    "specialty": "sports",
    "title": "Correlation of the torque peak of the isokinetic dynamometer with the peak of ground reaction force in the drop vertical jump in professional futsal players",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.013",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38264",
    "type": "research",
    "specialty": "ortho",
    "title": "Joint Contributions for Force Dissipation During Landings in Athletes with Patellar Tendinopathy",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.011",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38265",
    "type": "research",
    "specialty": "sports",
    "title": "Factors associated to musculoskeletal injuries in street runners",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.009",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38266",
    "type": "research",
    "specialty": "sports",
    "title": "Is there any association between the deficits found in the isokinetic evaluation with the functional performance of professional soccer players?",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.008",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38286",
    "type": "research",
    "specialty": "ortho",
    "title": "Cross-cultural adaptation and validation of the tendon grading system and classification system for the effect of pain on athletic performance in achilles tendinopathy in Brazilian Portuguese-speaking population",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.022",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38287",
    "type": "research",
    "specialty": "ortho",
    "title": "Proprioceptive training for functional instability of the ankle",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.027",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38288",
    "type": "research",
    "specialty": "ortho",
    "title": "Correlation between dynamic valgus and gluteus medius resistance in professional soccer players",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.025",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-38289",
    "type": "research",
    "specialty": "sports",
    "title": "Correlation between a contact plataform and a mobile app in vertical jumping height evaluation",
    "source": "Physical Therapy in Sport",
    "sourceUrl": "https://doi.org/10.1016/j.ptsp.2020.04.023",
    "date": "2020-09-06",
    "readMins": 3,
    "summary": "Retraction issued on 2020-09-06 by Physical Therapy in Sport: Duplication of Content through Error by Journal/Publisher; Removed. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Removed"
  },
  {
    "id": "rw-21662",
    "type": "research",
    "specialty": "neuro",
    "title": "Vitamin K deficiency and osteopenia in disuse-affected limbs of vitamin D-deficient elderly stroke patients",
    "source": "American Journal of Physical Medicine & Rehabilitation",
    "sourceUrl": "https://doi.org/10.1097/PHM.0000000000001348",
    "date": "2019-11-15",
    "readMins": 3,
    "summary": "Retraction issued on 2019-11-15 by American Journal of Physical Medicine & Rehabilitation: Ethical Violations by Author; Investigation by Company/Institution; Misconduct - Official Investigation(s) and/or Finding(s). See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Ethical Violations by Author; Investigation by Company/Institution; Misconduct - Official Investigation(s) and/or Finding(s)"
  },
  {
    "id": "rw-21663",
    "type": "research",
    "specialty": "neuro",
    "title": "Serum beta2-microglobulin reflects increased bone resorption in immobilized stroke patients",
    "source": "American Journal of Physical Medicine & Rehabilitation",
    "sourceUrl": "https://doi.org/10.1097/PHM.0000000000001348",
    "date": "2019-11-15",
    "readMins": 3,
    "summary": "Retraction issued on 2019-11-15 by American Journal of Physical Medicine & Rehabilitation: Ethical Violations by Author; Investigation by Company/Institution; Misconduct - Official Investigation(s) and/or Finding(s). See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Ethical Violations by Author; Investigation by Company/Institution; Misconduct - Official Investigation(s) and/or Finding(s)"
  },
  {
    "id": "rw-21607",
    "type": "research",
    "specialty": "ortho",
    "title": "Rehabilitation Is a Global Health Priority",
    "source": "Archives of Physical Medicine and Rehabilitation",
    "sourceUrl": "https://doi.org/10.1016/j.apmr.2019.08.468",
    "date": "2019-11-06",
    "readMins": 3,
    "summary": "Reinstatement issued on 2019-11-06 by Archives of Physical Medicine and Rehabilitation: Retract and Replace; Temporary Removal. See the retraction notice for full details.",
    "tags": [
      "Reinstatement"
    ],
    "reviewStatus": "Reinstatement",
    "underReview": "Retract and Replace; Temporary Removal"
  },
  {
    "id": "rw-21187",
    "type": "research",
    "specialty": "neuro",
    "title": "Vitamin K deficiency and osteopenia in disuse-affected limbs of vitamin D-deficient elderly stroke patients",
    "source": "American Journal of Physical Medicine & Rehabilitation",
    "sourceUrl": "https://doi.org/10.1097/PHM.0000000000001297",
    "date": "2019-09-04",
    "readMins": 3,
    "summary": "Expression of concern issued on 2019-09-04 by American Journal of Physical Medicine & Rehabilitation: Concerns/Issues about Data; Updated to Retraction. See the retraction notice for full details.",
    "tags": [
      "Expression of concern"
    ],
    "reviewStatus": "Expression of concern",
    "underReview": "Concerns/Issues about Data; Updated to Retraction"
  },
  {
    "id": "rw-21188",
    "type": "research",
    "specialty": "neuro",
    "title": "Serum beta2-microglobulin reflects increased bone resorption in immobilized stroke patients",
    "source": "American Journal of Physical Medicine & Rehabilitation",
    "sourceUrl": "https://doi.org/10.1097/PHM.0000000000001297",
    "date": "2019-09-04",
    "readMins": 3,
    "summary": "Expression of concern issued on 2019-09-04 by American Journal of Physical Medicine & Rehabilitation: Concerns/Issues about Data; Updated to Retraction. See the retraction notice for full details.",
    "tags": [
      "Expression of concern"
    ],
    "reviewStatus": "Expression of concern",
    "underReview": "Concerns/Issues about Data; Updated to Retraction"
  },
  {
    "id": "rw-30181",
    "type": "research",
    "specialty": "ortho",
    "title": "The contingency of the therapeutic effectiveness with the peculiarities of the non-pharmacological treatment of the patients presenting with chronic cholecystitis",
    "source": "Issues of Health Care, Physiotherapy and Therapeutic Physical Education(Вопросы Курортологии, Физиотерапии И Лечебной Физической Культуры)",
    "sourceUrl": "https://doi.org/10.17116/kurort2016436-41",
    "date": "2019-07-21",
    "readMins": 3,
    "summary": "Retraction issued on 2019-07-21 by Issues of Health Care, Physiotherapy and Therapeutic Physical Education(Вопросы Курортологии, Физиотерапии И Лечебной Физической Культуры): Plagiarism of/in Article. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Plagiarism of/in Article"
  },
  {
    "id": "rw-20431",
    "type": "research",
    "specialty": "ortho",
    "title": "Knowledge, experience and training needs of health and social care professionals in assistive technology, ADAPT project",
    "source": "Physiotherapy",
    "sourceUrl": "https://doi.org/10.1016/j.physio.2019.05.001",
    "date": "2019-05-07",
    "readMins": 3,
    "summary": "Retraction issued on 2019-05-07 by Physiotherapy: Not Presented at Conference. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Not Presented at Conference"
  },
  {
    "id": "rw-20166",
    "type": "research",
    "specialty": "ortho",
    "title": "Vitamin K Deficiency and Osteopenia in Vitamin D-Deficient Elderly Women With Parkinson's Disease",
    "source": "Archives of Physical Medicine and Rehabilitation",
    "sourceUrl": "http://retractionwatch.com/?s=yoshihiro+sato",
    "date": "2019-03-19",
    "readMins": 3,
    "summary": "Retraction issued on 2019-03-19 by Archives of Physical Medicine and Rehabilitation: Concerns/Issues about Authorship/Affiliation; Concerns/Issues about Data; Duplication of Data. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Concerns/Issues about Authorship/Affiliation; Concerns/Issues about Data; Duplication of Data"
  },
  {
    "id": "rw-20057",
    "type": "research",
    "specialty": "pediatric",
    "title": "Wearables for Pediatric Rehabilitation: How to Optimally Design and Utilize Products to Meet the Needs of Users",
    "source": "Physical Therapy",
    "sourceUrl": "http://retractionwatch.com/2019/03/11/journal-temporarily-withdraws-eight-papers-after-publisher-mistake/",
    "date": "2019-02-27",
    "readMins": 3,
    "summary": "Reinstatement issued on 2019-02-27 by Physical Therapy: Error by Journal/Publisher; Retract and Replace; Temporary Removal. See the retraction notice for full details.",
    "tags": [
      "Reinstatement"
    ],
    "reviewStatus": "Reinstatement",
    "underReview": "Error by Journal/Publisher; Retract and Replace; Temporary Removal"
  },
  {
    "id": "rw-20058",
    "type": "research",
    "specialty": "ortho",
    "title": "Embodied Cognition in Practice: Exploring Effects of a Motor-Based Problem Solving Intervention",
    "source": "Physical Therapy",
    "sourceUrl": "http://retractionwatch.com/2019/03/11/journal-temporarily-withdraws-eight-papers-after-publisher-mistake/",
    "date": "2019-02-27",
    "readMins": 3,
    "summary": "Reinstatement issued on 2019-02-27 by Physical Therapy: Error by Journal/Publisher; Retract and Replace; Temporary Removal. See the retraction notice for full details.",
    "tags": [
      "Reinstatement"
    ],
    "reviewStatus": "Reinstatement",
    "underReview": "Error by Journal/Publisher; Retract and Replace; Temporary Removal"
  },
  {
    "id": "rw-20059",
    "type": "research",
    "specialty": "ortho",
    "title": "Development Through the Lens of a Perception-Action-Cognition Connection: Recognizing the Need for a Paradigm Shift in Clinical Reasoning",
    "source": "Physical Therapy",
    "sourceUrl": "http://retractionwatch.com/2019/03/11/journal-temporarily-withdraws-eight-papers-after-publisher-mistake/",
    "date": "2019-02-27",
    "readMins": 3,
    "summary": "Reinstatement issued on 2019-02-27 by Physical Therapy: Error by Journal/Publisher; Retract and Replace; Temporary Removal. See the retraction notice for full details.",
    "tags": [
      "Reinstatement"
    ],
    "reviewStatus": "Reinstatement",
    "underReview": "Error by Journal/Publisher; Retract and Replace; Temporary Removal"
  },
  {
    "id": "rw-20060",
    "type": "research",
    "specialty": "pediatric",
    "title": "Assessment of Parent-Child Interaction Is Important With Infants in Rehabilitation and Can Use High-Tech or Low-Tech Methods",
    "source": "Physical Therapy",
    "sourceUrl": "http://retractionwatch.com/2019/03/11/journal-temporarily-withdraws-eight-papers-after-publisher-mistake/",
    "date": "2019-02-26",
    "readMins": 3,
    "summary": "Reinstatement issued on 2019-02-26 by Physical Therapy: Error by Journal/Publisher; Retract and Replace; Temporary Removal. See the retraction notice for full details.",
    "tags": [
      "Reinstatement"
    ],
    "reviewStatus": "Reinstatement",
    "underReview": "Error by Journal/Publisher; Retract and Replace; Temporary Removal"
  },
  {
    "id": "rw-20061",
    "type": "research",
    "specialty": "neuro",
    "title": "Safety and feasibility of transcranial magnetic stimulation as an exploratory assessment of corticospinal connectivity in infants after perinatal brain injury: an observational study",
    "source": "Physical Therapy",
    "sourceUrl": "http://retractionwatch.com/2019/03/11/journal-temporarily-withdraws-eight-papers-after-publisher-mistake/",
    "date": "2019-02-26",
    "readMins": 3,
    "summary": "Reinstatement issued on 2019-02-26 by Physical Therapy: Error by Journal/Publisher; Retract and Replace; Temporary Removal. See the retraction notice for full details.",
    "tags": [
      "Reinstatement"
    ],
    "reviewStatus": "Reinstatement",
    "underReview": "Error by Journal/Publisher; Retract and Replace; Temporary Removal"
  },
  {
    "id": "rw-20062",
    "type": "research",
    "specialty": "pediatric",
    "title": "An Eye-Tracking Method for Directly Assessing Children's Visual-Motor Integration",
    "source": "Physical Therapy",
    "sourceUrl": "http://retractionwatch.com/2019/03/11/journal-temporarily-withdraws-eight-papers-after-publisher-mistake/",
    "date": "2019-02-26",
    "readMins": 3,
    "summary": "Reinstatement issued on 2019-02-26 by Physical Therapy: Error by Journal/Publisher; Retract and Replace; Temporary Removal. See the retraction notice for full details.",
    "tags": [
      "Reinstatement"
    ],
    "reviewStatus": "Reinstatement",
    "underReview": "Error by Journal/Publisher; Retract and Replace; Temporary Removal"
  },
  {
    "id": "rw-20063",
    "type": "research",
    "specialty": "pediatric",
    "title": "Validating accelerometry as a measure of arm movement for children with hemiplegic cerebral palsy",
    "source": "Physical Therapy",
    "sourceUrl": "http://retractionwatch.com/2019/03/11/journal-temporarily-withdraws-eight-papers-after-publisher-mistake/",
    "date": "2019-02-26",
    "readMins": 3,
    "summary": "Reinstatement issued on 2019-02-26 by Physical Therapy: Error by Journal/Publisher; Retract and Replace; Temporary Removal. See the retraction notice for full details.",
    "tags": [
      "Reinstatement"
    ],
    "reviewStatus": "Reinstatement",
    "underReview": "Error by Journal/Publisher; Retract and Replace; Temporary Removal"
  },
  {
    "id": "rw-20064",
    "type": "research",
    "specialty": "ortho",
    "title": "The interdependence of motor and social skill development: Influence on participation",
    "source": "Physical Therapy",
    "sourceUrl": "http://retractionwatch.com/2019/03/11/journal-temporarily-withdraws-eight-papers-after-publisher-mistake/",
    "date": "2019-02-25",
    "readMins": 3,
    "summary": "Reinstatement issued on 2019-02-25 by Physical Therapy: Error by Journal/Publisher; Retract and Replace; Temporary Removal. See the retraction notice for full details.",
    "tags": [
      "Reinstatement"
    ],
    "reviewStatus": "Reinstatement",
    "underReview": "Error by Journal/Publisher; Retract and Replace; Temporary Removal"
  },
  {
    "id": "rw-20164",
    "type": "research",
    "specialty": "neuro",
    "title": "Abnormal Bone and Calcium Metabolism in Patients After Stroke",
    "source": "Archives of Physical Medicine and Rehabilitation",
    "sourceUrl": "http://retractionwatch.com/?s=yoshihiro+sato",
    "date": "2019-02-19",
    "readMins": 3,
    "summary": "Retraction issued on 2019-02-19 by Archives of Physical Medicine and Rehabilitation: Cites Retracted Work; Investigation by Company/Institution; Misconduct - Official Investigation(s) and/or Finding(s). See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Cites Retracted Work; Investigation by Company/Institution; Misconduct - Official Investigation(s) and/or Finding(s)"
  },
  {
    "id": "rw-20167",
    "type": "research",
    "specialty": "ortho",
    "title": "Vitamin K Deficiency and Osteopenia in Elderly Women With Alzheimer's Disease",
    "source": "Archives of Physical Medicine and Rehabilitation",
    "sourceUrl": "http://retractionwatch.com/?s=yoshihiro+sato",
    "date": "2019-02-19",
    "readMins": 3,
    "summary": "Retraction issued on 2019-02-19 by Archives of Physical Medicine and Rehabilitation: Concerns/Issues about Authorship/Affiliation; Concerns/Issues about Data; Investigation by Company/Institution. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Concerns/Issues about Authorship/Affiliation; Concerns/Issues about Data; Investigation by Company/Institution"
  },
  {
    "id": "rw-19125",
    "type": "research",
    "specialty": "ortho",
    "title": "Negative myoglobin staining in hemiplegic muscle of acute stroke patients predicts functional recovery",
    "source": "American Journal of Physical Medicine & Rehabilitation",
    "sourceUrl": "http://retractionwatch.com/?s=jun+iwamoto",
    "date": "2018-08-30",
    "readMins": 3,
    "summary": "Retraction issued on 2018-08-30 by American Journal of Physical Medicine & Rehabilitation: Concerns/Issues about Authorship/Affiliation; Falsification/Fabrication of Data; Investigation by Company/Institution. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Concerns/Issues about Authorship/Affiliation; Falsification/Fabrication of Data; Investigation by Company/Institution"
  },
  {
    "id": "rw-16992",
    "type": "research",
    "specialty": "ortho",
    "title": "The effect of postural control intervention for congenital muscular torticollis: a randomized controlled trial",
    "source": "Clinical Rehabilitation",
    "sourceUrl": "https://doi.org/10.1177/0269215517752416",
    "date": "2018-01-24",
    "readMins": 3,
    "summary": "Retraction issued on 2018-01-24 by Clinical Rehabilitation: Plagiarism of/in Article. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Plagiarism of/in Article"
  },
  {
    "id": "rw-16919",
    "type": "research",
    "specialty": "neuro",
    "title": "Effect of ipriflavone on bone in elderly hemiplegic stroke patients with hypovitaminosis D",
    "source": "American Journal of Physical Medicine & Rehabilitation",
    "sourceUrl": "http://retractionwatch.com/?s=yoshihiro+sato",
    "date": "2018-01-18",
    "readMins": 3,
    "summary": "Retraction issued on 2018-01-18 by American Journal of Physical Medicine & Rehabilitation: Concerns/Issues about Data; Concerns/Issues about Results and/or Conclusions; Investigation by Company/Institution. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Concerns/Issues about Data; Concerns/Issues about Results and/or Conclusions; Investigation by Company/Institution"
  },
  {
    "id": "rw-16920",
    "type": "research",
    "specialty": "ortho",
    "title": "Beneficial Effect of Etidronate Therapy in Immobilized Hip Fracture Patients",
    "source": "American Journal of Physical Medicine & Rehabilitation",
    "sourceUrl": "http://retractionwatch.com/?s=yoshihiro+sato",
    "date": "2018-01-18",
    "readMins": 3,
    "summary": "Retraction issued on 2018-01-18 by American Journal of Physical Medicine & Rehabilitation: Concerns/Issues about Authorship/Affiliation; Falsification/Fabrication of Data; Investigation by Company/Institution. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Concerns/Issues about Authorship/Affiliation; Falsification/Fabrication of Data; Investigation by Company/Institution"
  },
  {
    "id": "rw-14415",
    "type": "research",
    "specialty": "neuro",
    "title": "Intra-rater and inter-rater reliability of the portable gait rhythmogram in post-stroke patients",
    "source": "Journal of Physical Therapy Science",
    "sourceUrl": "https://doi.org/10.1589/jpts.29.874r1",
    "date": "2017-10-21",
    "readMins": 3,
    "summary": "Retraction issued on 2017-10-21 by Journal of Physical Therapy Science. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Flagged by Retraction Watch, see notice for details."
  },
  {
    "id": "rw-11293",
    "type": "research",
    "specialty": "ortho",
    "title": "Electrical Stimulation for Hemiplegic Shoulder Function: A Systematic Review and Meta-Analysis of 15 Randomized Controlled Trials",
    "source": "Archives of Physical Medicine and Rehabilitation",
    "sourceUrl": "https://doi.org/10.1016/j.apmr.2017.07.001",
    "date": "2017-09-01",
    "readMins": 3,
    "summary": "Retraction issued on 2017-09-01 by Archives of Physical Medicine and Rehabilitation: Plagiarism of/in Article. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Plagiarism of/in Article"
  },
  {
    "id": "rw-11838",
    "type": "research",
    "specialty": "neuro",
    "title": "Effect of ipriflavone on bone in elderly hemiplegic stroke patients with hypovitaminosis D",
    "source": "American Journal of Physical Medicine & Rehabilitation",
    "sourceUrl": "http://retractionwatch.com/?s=yoshihiro+sato",
    "date": "2017-09-01",
    "readMins": 3,
    "summary": "Expression of concern issued on 2017-09-01 by American Journal of Physical Medicine & Rehabilitation: Concerns/Issues about Data; Concerns/Issues about Results and/or Conclusions; Investigation by Company/Institution. See the retraction notice for full details.",
    "tags": [
      "Expression of concern"
    ],
    "reviewStatus": "Expression of concern",
    "underReview": "Concerns/Issues about Data; Concerns/Issues about Results and/or Conclusions; Investigation by Company/Institution"
  },
  {
    "id": "rw-11839",
    "type": "research",
    "specialty": "ortho",
    "title": "Beneficial Effect of Etidronate Therapy in Immobilized Hip Fracture Patients",
    "source": "American Journal of Physical Medicine & Rehabilitation",
    "sourceUrl": "http://retractionwatch.com/?s=yoshihiro+sato",
    "date": "2017-09-01",
    "readMins": 3,
    "summary": "Expression of concern issued on 2017-09-01 by American Journal of Physical Medicine & Rehabilitation: Concerns/Issues about Data; Concerns/Issues about Results and/or Conclusions; Investigation by Company/Institution. See the retraction notice for full details.",
    "tags": [
      "Expression of concern"
    ],
    "reviewStatus": "Expression of concern",
    "underReview": "Concerns/Issues about Data; Concerns/Issues about Results and/or Conclusions; Investigation by Company/Institution"
  },
  {
    "id": "rw-7872",
    "type": "research",
    "specialty": "pediatric",
    "title": "Early Use of Power Wheelchair for Children with Duchenne Muscular Dystrophy: A Narrative Review",
    "source": "Disability and Rehabilitation",
    "sourceUrl": "https://doi.org/10.1080/09638288.2016.1194902",
    "date": "2017-07-01",
    "readMins": 3,
    "summary": "Retraction issued on 2017-07-01 by Disability and Rehabilitation. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Flagged by Retraction Watch, see notice for details."
  },
  {
    "id": "rw-7954",
    "type": "research",
    "specialty": "ortho",
    "title": "Effects of Long Duration Low Intensity Ultrasound for Active Trapezius Trigger Points: A Randomized Clinical Trial",
    "source": "The Journal of Sport Rehabilitation",
    "sourceUrl": "https://doi.org/10.1123/jsr.2017-0118",
    "date": "2017-03-01",
    "readMins": 3,
    "summary": "Retraction issued on 2017-03-01 by The Journal of Sport Rehabilitation: Error in Data. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Error in Data"
  },
  {
    "id": "rw-8504",
    "type": "research",
    "specialty": "ortho",
    "title": "Huntington's Disease: Characteristics of Fallers",
    "source": "Physiotherapy Research International: The Journal for Researchers and Clinicians in Physical Therapy",
    "sourceUrl": "https://doi.org/10.1002/pri.1685",
    "date": "2017-01-12",
    "readMins": 3,
    "summary": "Retraction issued on 2017-01-12 by Physiotherapy Research International: The Journal for Researchers and Clinicians in Physical Therapy: Error in Methods. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Error in Methods"
  },
  {
    "id": "rw-11246",
    "type": "research",
    "specialty": "neuro",
    "title": "The role of compensatory movements patterns in spontaneous recovery after stroke",
    "source": "Journal of Physical Therapy Science",
    "sourceUrl": "http://retractionwatch.com/2017/03/06/author-says-lied-approval-animal-research/",
    "date": "2016-12-29",
    "readMins": 3,
    "summary": "Retraction issued on 2016-12-29 by Journal of Physical Therapy Science: Ethical Violations by Author; Lack of IRB/IACUC Approval and/or Compliance. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Ethical Violations by Author; Lack of IRB/IACUC Approval and/or Compliance"
  },
  {
    "id": "rw-11532",
    "type": "research",
    "specialty": "pediatric",
    "title": "Establishing Reference Values for Infant Head Shape Using a Modified Version of Plagiocephalometry",
    "source": "Physical Therapy",
    "sourceUrl": "http://retractionwatch.com/2016/09/21/amid-controversial-sarepta-approval-decision-fda-head-calls-for-key-study-retraction/",
    "date": "2016-08-01",
    "readMins": 3,
    "summary": "Retraction issued on 2016-08-01 by Physical Therapy: Error in Methods; Unreliable Data; Unreliable Results and/or Conclusions. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Error in Methods; Unreliable Data; Unreliable Results and/or Conclusions"
  },
  {
    "id": "rw-9574",
    "type": "research",
    "specialty": "ortho",
    "title": "Is exercise therapy effective in the older people? A systematic review",
    "source": "Physiotherapy",
    "sourceUrl": "https://doi.org/10.1016/j.physio.2016.02.003",
    "date": "2016-04-30",
    "readMins": 3,
    "summary": "Retraction issued on 2016-04-30 by Physiotherapy: False/Forged Authorship; Lack of Approval from Author. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "False/Forged Authorship; Lack of Approval from Author"
  },
  {
    "id": "rw-8383",
    "type": "research",
    "specialty": "ortho",
    "title": "Rehabilitation strategies for wrist sensorimotor control impairment: From theory to practice",
    "source": "Journal of Hand Therapy",
    "sourceUrl": "https://doi.org/10.1016/j.jht.2015.12.003",
    "date": "2016-04-01",
    "readMins": 3,
    "summary": "Retraction issued on 2016-04-01 by Journal of Hand Therapy: Retract and Replace. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Retract and Replace"
  },
  {
    "id": "rw-4203",
    "type": "research",
    "specialty": "ortho",
    "title": "Effect of exercise at light loads with manipulative resistance on infraspinatus, trapezius (upper fiber) and deltoid (middle fiber) muscle activities in shoulder joint elevation",
    "source": "Journal of Physical Therapy Science",
    "sourceUrl": "https://doi.org/10.1589/jpts.27.627r1",
    "date": "2015-10-30",
    "readMins": 3,
    "summary": "Retraction issued on 2015-10-30 by Journal of Physical Therapy Science: Duplication of/in Article. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of/in Article"
  },
  {
    "id": "rw-3362",
    "type": "research",
    "specialty": "ortho",
    "title": "The Value of Adding Transcutaneous Neuromuscular Electrical Stimulation (VitalStim) to Traditional Therapy for Post-stroke Dysphagia: A Randomized Controlled Trial",
    "source": "European Journal of Physical and Rehabilitation Medicine",
    "sourceUrl": "https://doi.org/unavailable",
    "date": "2015-04-01",
    "readMins": 3,
    "summary": "Retraction issued on 2015-04-01 by European Journal of Physical and Rehabilitation Medicine: Concerns/Issues about Authorship/Affiliation; Copyright Claims; Duplication of Text. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Concerns/Issues about Authorship/Affiliation; Copyright Claims; Duplication of Text"
  },
  {
    "id": "rw-2999",
    "type": "research",
    "specialty": "neuro",
    "title": "Effect of Computer-based Cognitive Rehabilitation (CBCR) for People with Stroke: A Systematic Review and Meta-analysis",
    "source": "NeuroRehabilitation",
    "sourceUrl": "https://doi.org/10.3233/NRE-151288",
    "date": "2015-01-01",
    "readMins": 3,
    "summary": "Retraction issued on 2015-01-01 by NeuroRehabilitation: Error in Data; Error in Methods; Unreliable Data. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Error in Data; Error in Methods; Unreliable Data"
  },
  {
    "id": "rw-4398",
    "type": "research",
    "specialty": "ortho",
    "title": "Developing Self-sustainable Hearing Centers in the Developing World--Case Study of EARs Inc Project in Dominican Republic",
    "source": "Disability and Rehabilitation. Assistive technology",
    "sourceUrl": "https://doi.org/10.3109/17483107.2014.962290",
    "date": "2014-09-15",
    "readMins": 3,
    "summary": "Retraction issued on 2014-09-15 by Disability and Rehabilitation. Assistive technology: Duplication of Content through Error by Journal/Publisher; Euphemisms for Duplication. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher; Euphemisms for Duplication"
  },
  {
    "id": "rw-2997",
    "type": "research",
    "specialty": "neuro",
    "title": "Effects of High-Frequency Repetitive Transcranial Magnetic Stimulation on Motor and Gait Improvement in Incomplete Spinal Cord Injury Patients",
    "source": "Neurorehabilitation and Neural Repair",
    "sourceUrl": "https://doi.org/10.1177/1545968314536858",
    "date": "2014-05-22",
    "readMins": 3,
    "summary": "Retraction issued on 2014-05-22 by Neurorehabilitation and Neural Repair: Euphemisms for Plagiarism; Plagiarism of Text. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Euphemisms for Plagiarism; Plagiarism of Text"
  },
  {
    "id": "rw-22771",
    "type": "research",
    "specialty": "neuro",
    "title": "A Review of Abdominal Muscle Stimulation for Patients with Spinal Cord Injury",
    "source": "Journal of Physical Therapy Science",
    "sourceUrl": "https://doi.org/10.1589/jpts.23.697",
    "date": "2011-11-25",
    "readMins": 3,
    "summary": "Retraction issued on 2011-11-25 by Journal of Physical Therapy Science: Plagiarism of/in Article. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Plagiarism of/in Article"
  },
  {
    "id": "rw-17915",
    "type": "research",
    "specialty": "ortho",
    "title": "A regressed phase analysis for coupled joint systems",
    "source": "Gait & Posture",
    "sourceUrl": "https://doi.org/10.1016/j.gaitpost.2010.09.011",
    "date": "2010-10-25",
    "readMins": 3,
    "summary": "Retraction issued on 2010-10-25 by Gait & Posture: Concerns/Issues about Data; Copyright Claims. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Concerns/Issues about Data; Copyright Claims"
  },
  {
    "id": "rw-4396",
    "type": "research",
    "specialty": "ortho",
    "title": "Who Gets the Disability Grant in South Africa? An Analysis of the Characteristics of Recipients in Urban and Rural Areas",
    "source": "Disability and Rehabilitation. Assistive technology",
    "sourceUrl": "https://doi.org/10.1080/17483100903126066",
    "date": "2009-09-09",
    "readMins": 3,
    "summary": "Retraction issued on 2009-09-09 by Disability and Rehabilitation. Assistive technology: Error by Journal/Publisher. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Error by Journal/Publisher"
  },
  {
    "id": "rw-4399",
    "type": "research",
    "specialty": "ortho",
    "title": "Value and Application of the ICF in Rehabilitation Medicine",
    "source": "Disability and Rehabilitation",
    "sourceUrl": "https://doi.org/10.1080/09638280902834364",
    "date": "2009-07-07",
    "readMins": 3,
    "summary": "Retraction issued on 2009-07-07 by Disability and Rehabilitation: Duplication of Content through Error by Journal/Publisher. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Duplication of Content through Error by Journal/Publisher"
  },
  {
    "id": "rw-4851",
    "type": "research",
    "specialty": "ortho",
    "title": "Gait analysis and energy consumption of below-knee amputees wearing three different prosthetic feet",
    "source": "Gait & Posture",
    "sourceUrl": "https://doi.org/10.1016/j.gaitpost.2003.08.007",
    "date": "2003-12-01",
    "readMins": 3,
    "summary": "Retraction issued on 2003-12-01 by Gait & Posture: Plagiarism of/in Article. See the retraction notice for full details.",
    "tags": [
      "Retraction"
    ],
    "reviewStatus": "Retraction",
    "underReview": "Plagiarism of/in Article"
  }
];
