// Generated by scripts/fetch-topic-photos.mjs from Wikimedia Commons.
// A hand-curated, real, freely-licensed photo pool — not fetched live (see the script for
// why). Re-run the script to refresh URLs/licenses for the same title list.
export interface BundledTopicPhoto {
  url: string;
  width: number;
  height: number;
  tags: string[];
  credit: string;
  sourceUrl: string;
}

export const BUNDLED_TOPIC_PHOTOS: BundledTopicPhoto[] = [
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Physical_Therapy_Session_Aboard_the_USS_George_Washington_DVIDS387343.jpg/1280px-Physical_Therapy_Session_Aboard_the_USS_George_Washington_DVIDS387343.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 838,
    "tags": [
      "general",
      "gait"
    ],
    "credit": "Photo by: Petty Officer 2nd Class William Pittman, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Physical_Therapy_Session_Aboard_the_USS_George_Washington_DVIDS387343.jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Child_receiving_physical_therapy_treatment_for_back_pain_in_a_comfortable_clinic_setting_during_the_day.jpg/1280px-Child_receiving_physical_therapy_treatment_for_back_pain_in_a_comfortable_clinic_setting_during_the_day.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 852,
    "tags": [
      "pediatric",
      "back pain",
      "low back"
    ],
    "credit": "Shixart1985, CC BY 2.0, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Child_receiving_physical_therapy_treatment_for_back_pain_in_a_comfortable_clinic_setting_during_the_day.jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/US_Navy_090508-F-7885G-021_Staff_Sgt._Hugo_Reiner%2C_a_physical_therapy_craftsman_aboard_the_Military_Sealift_Command_hospital_ship_USNS_Comfort_%28T-AH_20%29%2C_makes_a_wrist_brace_for_Teresa_De_la_Pena_during_a_Continuing_Promise_200.jpg/1280px-thumbnail.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 1925,
    "tags": [
      "wrist",
      "geriatric"
    ],
    "credit": "U.S. Air Force photo by Airman 1st Class Danielle Grannan, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:US_Navy_090508-F-7885G-021_Staff_Sgt._Hugo_Reiner,_a_physical_therapy_craftsman_aboard_the_Military_Sealift_Command_hospital_ship_USNS_Comfort_(T-AH_20),_makes_a_wrist_brace_for_Teresa_De_la_Pena_during_a_Continuing_Promise_200.jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Kinesio_taping.jpg/1280px-Kinesio_taping.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 966,
    "tags": [
      "ankle",
      "sports injury",
      "general"
    ],
    "credit": "U.S. Air Force photo by Airman 1st Class Alystria Maurer, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kinesio_taping.jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Flickr_-_The_U.S._Army_-_Patient_at_Walter_Reed_test_next-generation_prosthesis.jpg/1280px-Flickr_-_The_U.S._Army_-_Patient_at_Walter_Reed_test_next-generation_prosthesis.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 1348,
    "tags": [
      "gait",
      "post-surgical"
    ],
    "credit": "The U.S. Army, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Flickr_-_The_U.S._Army_-_Patient_at_Walter_Reed_test_next-generation_prosthesis.jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Physical_therapy_clinic_receives_new_equipment_130103-F-ES880-430.jpg/1280px-Physical_therapy_clinic_receives_new_equipment_130103-F-ES880-430.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 1032,
    "tags": [
      "equipment",
      "gait"
    ],
    "credit": "Staff Sgt. Stephenie Wade, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Physical_therapy_clinic_receives_new_equipment_130103-F-ES880-430.jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/On_the_frontlines_against_COVID-_Physical_Therapy_Assistant_%286559676%29.jpg/1280px-On_the_frontlines_against_COVID-_Physical_Therapy_Assistant_%286559676%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 853,
    "tags": [
      "general"
    ],
    "credit": "U.S. Army RHCE by Russell Toof, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:On_the_frontlines_against_COVID-_Physical_Therapy_Assistant_(6559676).jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Pacific_Partnership_2024-1-_Physical_Therapy_at_BNH_%288187681%29.jpg/1280px-Pacific_Partnership_2024-1-_Physical_Therapy_at_BNH_%288187681%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 914,
    "tags": [
      "general",
      "knee"
    ],
    "credit": "U.S. Navy photo by Seaman Apprentice Gavin Arnoldhendershot, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pacific_Partnership_2024-1-_Physical_Therapy_at_BNH_(8187681).jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/US_Navy_070509-N-4772B-008_Robert_J._Jadgchew%2C_Naval_Special_Warfare_Group_One_athletic_trainer%2C_adjusts_the_underwater_treadmill_for_a_patient.jpg/1280px-US_Navy_070509-N-4772B-008_Robert_J._Jadgchew%2C_Naval_Special_Warfare_Group_One_athletic_trainer%2C_adjusts_the_underwater_treadmill_for_a_patient.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 856,
    "tags": [
      "equipment",
      "gait",
      "sports"
    ],
    "credit": "U.S. Navy photo by Mass Communication Specialist 2nd Class Brian P. Biller, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:US_Navy_070509-N-4772B-008_Robert_J._Jadgchew,_Naval_Special_Warfare_Group_One_athletic_trainer,_adjusts_the_underwater_treadmill_for_a_patient.jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/01/Personal_trainer_monitoring_a_client%27s_movement_during_a_fitball_exercise.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
    "width": 1280,
    "height": 852,
    "tags": [
      "equipment",
      "sports",
      "balance"
    ],
    "credit": "www.localfitness.com.au, CC BY-SA 3.0, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Personal_trainer_monitoring_a_client%27s_movement_during_a_fitball_exercise.JPG"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Meaning_beyond_movement-_JTF-Bravo_physical_therapist_provides_hope_to_Honduran_communities_%289352736%29.jpg/1280px-Meaning_beyond_movement-_JTF-Bravo_physical_therapist_provides_hope_to_Honduran_communities_%289352736%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 852,
    "tags": [
      "gait",
      "geriatric"
    ],
    "credit": "U.S. Air Force photo by Staff Sgt. Sadie Colbert, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Meaning_beyond_movement-_JTF-Bravo_physical_therapist_provides_hope_to_Honduran_communities_(9352736).jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Strength_in_numbers-_group_physical_therapy_%287652217%29.jpg/1280px-Strength_in_numbers-_group_physical_therapy_%287652217%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 854,
    "tags": [
      "equipment",
      "general"
    ],
    "credit": "U.S. Air Force photo by Airman Tabatha Chapman, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Strength_in_numbers-_group_physical_therapy_(7652217).jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Dr._Jesus_Olmo_Isokinetic_ACL_Injury.jpg/1280px-Dr._Jesus_Olmo_Isokinetic_ACL_Injury.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 853,
    "tags": [
      "acl",
      "knee",
      "sports injury"
    ],
    "credit": "Riccardo Pisi, CC BY-SA 4.0, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dr._Jesus_Olmo_Isokinetic_ACL_Injury.jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Balance_training_board_2.jpg/1280px-Balance_training_board_2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 1707,
    "tags": [
      "balance",
      "vestibular",
      "equipment"
    ],
    "credit": "Ashashyou, CC BY-SA 3.0, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Balance_training_board_2.jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Yoga_Class_-_Nisana_Foundation_-_Chamrail_-_Howrah_2013-08-24_1989.JPG/1280px-Yoga_Class_-_Nisana_Foundation_-_Chamrail_-_Howrah_2013-08-24_1989.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 851,
    "tags": [
      "pediatric",
      "balance"
    ],
    "credit": "Biswarup Ganguly, CC BY 3.0, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Yoga_Class_-_Nisana_Foundation_-_Chamrail_-_Howrah_2013-08-24_1989.JPG"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Team_U_S_competes_in_wheelchair_basketball_during_2025_Invictus_Games_%288863262%29.jpg/1280px-Team_U_S_competes_in_wheelchair_basketball_during_2025_Invictus_Games_%288863262%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 853,
    "tags": [
      "sports",
      "sports injury",
      "post-surgical"
    ],
    "credit": "U.S. Army photo by Michel Sauret, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Team_U_S_competes_in_wheelchair_basketball_during_2025_Invictus_Games_(8863262).jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/US_Navy_071015-N-5086M-002_U.S._Army_Spc._Saul_Martinez_trains_with_the_medicine_ball_while_standing_on_a_balancing_tool_and_using_the_hands-free_harness_walking_gait-training_device_during_a_therapy_session.jpg/1280px-thumbnail.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 1912,
    "tags": [
      "equipment",
      "balance",
      "gait",
      "post-surgical"
    ],
    "credit": "U.S. Navy photo by Mass Communication Specialist 2nd Class Greg Mitchell, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:US_Navy_071015-N-5086M-002_U.S._Army_Spc._Saul_Martinez_trains_with_the_medicine_ball_while_standing_on_a_balancing_tool_and_using_the_hands-free_harness_walking_gait-training_device_during_a_therapy_session.jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/US_Navy_071015-N-5086M-202_Retired_Marine_Corps_Cpl._Timothy_Jeffers_walks_on_his_prosthetic_legs_while_using_the_hands-free_harness_walking_gait_training_device_during_a_therapy_session_in_the_new_Comprehensive_Combat_and_Com.jpg/1280px-thumbnail.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 1920,
    "tags": [
      "equipment",
      "gait",
      "post-surgical"
    ],
    "credit": "U.S. Navy photo by Mass Communication Specialist 2nd Class Greg Mitchell, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:US_Navy_071015-N-5086M-202_Retired_Marine_Corps_Cpl._Timothy_Jeffers_walks_on_his_prosthetic_legs_while_using_the_hands-free_harness_walking_gait_training_device_during_a_therapy_session_in_the_new_Comprehensive_Combat_and_Com.jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Gait_Analysis_Clinic_helps_improve_running%2C_prevent_injuries_130108-F-GE255-011.jpg/1280px-Gait_Analysis_Clinic_helps_improve_running%2C_prevent_injuries_130108-F-GE255-011.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 848,
    "tags": [
      "gait",
      "sports"
    ],
    "credit": "Staff Sgt. Anthony Hyatt, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gait_Analysis_Clinic_helps_improve_running,_prevent_injuries_130108-F-GE255-011.jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Strength_in_numbers-_group_physical_therapy_%287652210%29.jpg/1280px-Strength_in_numbers-_group_physical_therapy_%287652210%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 854,
    "tags": [
      "equipment",
      "balance"
    ],
    "credit": "U.S. Air Force photo by Airman Tabatha Chapman, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Strength_in_numbers-_group_physical_therapy_(7652210).jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/US_Navy_091003-N-8960W-011_Gunner%27s_Mate_2nd_Class_Patrick_Cornwell_undergoes_an_exam_by_Lt._Cristi_Zohlen_to_document_his_shoulder_pain_in_the_physical_therapy_clinic_aboard_the_aircraft_carrier_USS_Nimitz_%28CVN_68%29.jpg/1280px-thumbnail.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 851,
    "tags": [
      "shoulder",
      "rotator cuff"
    ],
    "credit": "U.S. Navy photo by Mass Communication Specialist Seaman Apprentice Robert Winn, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:US_Navy_091003-N-8960W-011_Gunner%27s_Mate_2nd_Class_Patrick_Cornwell_undergoes_an_exam_by_Lt._Cristi_Zohlen_to_document_his_shoulder_pain_in_the_physical_therapy_clinic_aboard_the_aircraft_carrier_USS_Nimitz_(CVN_68).jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Canadian_Army_Capt._Natalie_Royer%2C_top%2C_helps_relieve_a_pinched_nerve_in_the_neck_of_U.S._Navy_Cmdr._Ingrid_Byles_during_a_physical_therapy_treatment_aboard_Military_Sealift_Command_hospital_ship_USNS_Mercy_120602-O-ZZ999-001.jpg/1280px-thumbnail.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 1969,
    "tags": [
      "neck",
      "spine"
    ],
    "credit": "Kristopher Radder, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Canadian_Army_Capt._Natalie_Royer,_top,_helps_relieve_a_pinched_nerve_in_the_neck_of_U.S._Navy_Cmdr._Ingrid_Byles_during_a_physical_therapy_treatment_aboard_Military_Sealift_Command_hospital_ship_USNS_Mercy_120602-O-ZZ999-001.jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Physical_therapists_make_every_visit_count_130309-A-RB400-024.jpg/1280px-Physical_therapists_make_every_visit_count_130309-A-RB400-024.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 1792,
    "tags": [
      "general"
    ],
    "credit": "Staff Sgt. Michael Carrigan, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Physical_therapists_make_every_visit_count_130309-A-RB400-024.jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Physical_therapy_taking_away_soldiers%E2%80%99_pain_111008-A-IX584-002.jpg/1280px-Physical_therapy_taking_away_soldiers%E2%80%99_pain_111008-A-IX584-002.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 1952,
    "tags": [
      "back pain",
      "spine",
      "general"
    ],
    "credit": "Spc. Anthony Zane, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Physical_therapy_taking_away_soldiers%E2%80%99_pain_111008-A-IX584-002.jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/US_Navy_090702-N-1783P-003_Hospital_Corpsman_1st_Class_Guy_Duke%2C_left%2C_and_Electronics_Technician_3rd_Class_Joshua_Benedict_demonstrate_how_the_Physical_therapy_Department_at_Naval_Health_Clinic%2C_Charleston_use_the_Wii_Fit%27s_yoga.jpg/1280px-thumbnail.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 850,
    "tags": [
      "balance",
      "equipment",
      "vestibular"
    ],
    "credit": "U.S. Navy photo by Machinist's Mate 3rd Class Juan Pinalez, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:US_Navy_090702-N-1783P-003_Hospital_Corpsman_1st_Class_Guy_Duke,_left,_and_Electronics_Technician_3rd_Class_Joshua_Benedict_demonstrate_how_the_Physical_therapy_Department_at_Naval_Health_Clinic,_Charleston_use_the_Wii_Fit%27s_yoga.jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/355th_MDOS_130626-F-WZ808-005.jpg/1280px-355th_MDOS_130626-F-WZ808-005.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 2061,
    "tags": [
      "equipment",
      "knee"
    ],
    "credit": "Airman 1st Class Christine Halan, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:355th_MDOS_130626-F-WZ808-005.jpg"
  },
  {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/LRMC_staff_targets_to_improve_relationships%2C_patient_care_with_Ukrainian_counterparts_%285931161%29.jpg/1280px-LRMC_staff_targets_to_improve_relationships%2C_patient_care_with_Ukrainian_counterparts_%285931161%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 914,
    "tags": [
      "knee",
      "post-surgical"
    ],
    "credit": "Marcy Sanchez, Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:LRMC_staff_targets_to_improve_relationships,_patient_care_with_Ukrainian_counterparts_(5931161).jpg"
  }
];
