// Generated by scripts/fetch-topic-photos.mjs from Wikimedia Commons.
// A hand-curated, real, freely-licensed photo pool — not fetched live (see the script for
// why). Re-run the script to refresh URLs/licenses for the same title list.
export interface BundledTopicPhoto {
  url: string;
  width: number;
  height: number;
  tags: string[];
  credit: string;
  sourceUrl: string;
}

export const BUNDLED_TOPIC_PHOTOS: BundledTopicPhoto[] = [
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/56/Physical_Therapy_Session_Aboard_the_USS_George_Washington_DVIDS387343.jpg/1280px-Physical_Therapy_Session_Aboard_the_USS_George_Washington_DVIDS387343.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 838,
    "tags": [
      "general",
      "gait"
    ],
    "credit": "Photo by: Petty Officer 2nd Class William Pittman — Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Physical_Therapy_Session_Aboard_the_USS_George_Washington_DVIDS387343.jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/01/Child_receiving_physical_therapy_treatment_for_back_pain_in_a_comfortable_clinic_setting_during_the_day.jpg/1280px-Child_receiving_physical_therapy_treatment_for_back_pain_in_a_comfortable_clinic_setting_during_the_day.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 852,
    "tags": [
      "pediatric",
      "back pain",
      "low back",
      "spine"
    ],
    "credit": "Shixart1985 — CC BY 2.0, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Child_receiving_physical_therapy_treatment_for_back_pain_in_a_comfortable_clinic_setting_during_the_day.jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d2/Kinesio_taping.jpg/1280px-Kinesio_taping.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 966,
    "tags": [
      "ankle",
      "sports injury",
      "general"
    ],
    "credit": "U.S. Air Force photo by Airman 1st Class Alystria Maurer — Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kinesio_taping.jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a3/Physical_therapy_clinic_receives_new_equipment_130103-F-ES880-430.jpg/1280px-Physical_therapy_clinic_receives_new_equipment_130103-F-ES880-430.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 1032,
    "tags": [
      "equipment",
      "gait"
    ],
    "credit": "Staff Sgt. Stephenie Wade — Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Physical_therapy_clinic_receives_new_equipment_130103-F-ES880-430.jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/On_the_frontlines_against_COVID-_Physical_Therapy_Assistant_%286559676%29.jpg/1280px-On_the_frontlines_against_COVID-_Physical_Therapy_Assistant_%286559676%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 853,
    "tags": [
      "general"
    ],
    "credit": "U.S. Army RHCE by Russell Toof — Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:On_the_frontlines_against_COVID-_Physical_Therapy_Assistant_(6559676).jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/05/Pacific_Partnership_2024-1-_Physical_Therapy_at_BNH_%288187681%29.jpg/1280px-Pacific_Partnership_2024-1-_Physical_Therapy_at_BNH_%288187681%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 914,
    "tags": [
      "general",
      "knee"
    ],
    "credit": "U.S. Navy photo by Seaman Apprentice Gavin Arnoldhendershot — Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pacific_Partnership_2024-1-_Physical_Therapy_at_BNH_(8187681).jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/Meaning_beyond_movement-_JTF-Bravo_physical_therapist_provides_hope_to_Honduran_communities_%289352736%29.jpg/1280px-Meaning_beyond_movement-_JTF-Bravo_physical_therapist_provides_hope_to_Honduran_communities_%289352736%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 852,
    "tags": [
      "gait",
      "geriatric"
    ],
    "credit": "U.S. Air Force photo by Staff Sgt. Sadie Colbert — Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Meaning_beyond_movement-_JTF-Bravo_physical_therapist_provides_hope_to_Honduran_communities_(9352736).jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b8/Strength_in_numbers-_group_physical_therapy_%287652217%29.jpg/1280px-Strength_in_numbers-_group_physical_therapy_%287652217%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 854,
    "tags": [
      "equipment",
      "general"
    ],
    "credit": "U.S. Air Force photo by Airman Tabatha Chapman — Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Strength_in_numbers-_group_physical_therapy_(7652217).jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d3/Dr._Jesus_Olmo_Isokinetic_ACL_Injury.jpg/1280px-Dr._Jesus_Olmo_Isokinetic_ACL_Injury.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 853,
    "tags": [
      "acl",
      "knee",
      "sports injury"
    ],
    "credit": "Riccardo Pisi — CC BY-SA 4.0, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dr._Jesus_Olmo_Isokinetic_ACL_Injury.jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1f/Yoga_Class_-_Nisana_Foundation_-_Chamrail_-_Howrah_2013-08-24_1989.JPG/1280px-Yoga_Class_-_Nisana_Foundation_-_Chamrail_-_Howrah_2013-08-24_1989.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 851,
    "tags": [
      "pediatric",
      "balance"
    ],
    "credit": "Biswarup Ganguly — CC BY 3.0, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Yoga_Class_-_Nisana_Foundation_-_Chamrail_-_Howrah_2013-08-24_1989.JPG"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/53/Team_U_S_competes_in_wheelchair_basketball_during_2025_Invictus_Games_%288863262%29.jpg/1280px-Team_U_S_competes_in_wheelchair_basketball_during_2025_Invictus_Games_%288863262%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 853,
    "tags": [
      "sports",
      "sports injury",
      "post-surgical"
    ],
    "credit": "U.S. Army photo by Michel Sauret — Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Team_U_S_competes_in_wheelchair_basketball_during_2025_Invictus_Games_(8863262).jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/22/Gait_Analysis_Clinic_helps_improve_running%2C_prevent_injuries_130108-F-GE255-011.jpg/1280px-Gait_Analysis_Clinic_helps_improve_running%2C_prevent_injuries_130108-F-GE255-011.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 848,
    "tags": [
      "gait",
      "sports"
    ],
    "credit": "Staff Sgt. Anthony Hyatt — Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gait_Analysis_Clinic_helps_improve_running,_prevent_injuries_130108-F-GE255-011.jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9f/Strength_in_numbers-_group_physical_therapy_%287652210%29.jpg/1280px-Strength_in_numbers-_group_physical_therapy_%287652210%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 854,
    "tags": [
      "equipment",
      "balance"
    ],
    "credit": "U.S. Air Force photo by Airman Tabatha Chapman — Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Strength_in_numbers-_group_physical_therapy_(7652210).jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5a/US_Navy_091003-N-8960W-011_Gunner%27s_Mate_2nd_Class_Patrick_Cornwell_undergoes_an_exam_by_Lt._Cristi_Zohlen_to_document_his_shoulder_pain_in_the_physical_therapy_clinic_aboard_the_aircraft_carrier_USS_Nimitz_%28CVN_68%29.jpg/1280px-thumbnail.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 851,
    "tags": [
      "shoulder",
      "rotator cuff"
    ],
    "credit": "U.S. Navy photo by Mass Communication Specialist Seaman Apprentice Robert Winn — Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:US_Navy_091003-N-8960W-011_Gunner%27s_Mate_2nd_Class_Patrick_Cornwell_undergoes_an_exam_by_Lt._Cristi_Zohlen_to_document_his_shoulder_pain_in_the_physical_therapy_clinic_aboard_the_aircraft_carrier_USS_Nimitz_(CVN_68).jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/43/US_Navy_090702-N-1783P-003_Hospital_Corpsman_1st_Class_Guy_Duke%2C_left%2C_and_Electronics_Technician_3rd_Class_Joshua_Benedict_demonstrate_how_the_Physical_therapy_Department_at_Naval_Health_Clinic%2C_Charleston_use_the_Wii_Fit%27s_yoga.jpg/1280px-thumbnail.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 850,
    "tags": [
      "balance",
      "equipment",
      "vestibular"
    ],
    "credit": "U.S. Navy photo by Machinist's Mate 3rd Class Juan Pinalez — Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:US_Navy_090702-N-1783P-003_Hospital_Corpsman_1st_Class_Guy_Duke,_left,_and_Electronics_Technician_3rd_Class_Joshua_Benedict_demonstrate_how_the_Physical_therapy_Department_at_Naval_Health_Clinic,_Charleston_use_the_Wii_Fit%27s_yoga.jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a0/LRMC_staff_targets_to_improve_relationships%2C_patient_care_with_Ukrainian_counterparts_%285931161%29.jpg/1280px-LRMC_staff_targets_to_improve_relationships%2C_patient_care_with_Ukrainian_counterparts_%285931161%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 914,
    "tags": [
      "knee",
      "post-surgical"
    ],
    "credit": "Marcy Sanchez — Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:LRMC_staff_targets_to_improve_relationships,_patient_care_with_Ukrainian_counterparts_(5931161).jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/49/Physical_Therapy_Teaching_Lab_at_CU_Anschutz_%28October_2025%29.jpg/1280px-Physical_Therapy_Teaching_Lab_at_CU_Anschutz_%28October_2025%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 960,
    "tags": [
      "equipment",
      "general"
    ],
    "credit": "Mikepascoe — CC0, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Physical_Therapy_Teaching_Lab_at_CU_Anschutz_(October_2025).jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/db/MEDIMAX_Physiotherapy_Clinic_Tel_Aviv.jpg/1280px-MEDIMAX_Physiotherapy_Clinic_Tel_Aviv.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 853,
    "tags": [
      "equipment",
      "sports"
    ],
    "credit": "Hilahalumit — CC BY-SA 4.0, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:MEDIMAX_Physiotherapy_Clinic_Tel_Aviv.jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9d/Leg_treatment_in_physiatry_closeup._Physiotherapist_working_examining_treating.jpg/1280px-Leg_treatment_in_physiatry_closeup._Physiotherapist_working_examining_treating.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 854,
    "tags": [
      "knee",
      "post-surgical",
      "equipment"
    ],
    "credit": "Shixart1985 — CC BY 2.0, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Leg_treatment_in_physiatry_closeup._Physiotherapist_working_examining_treating.jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e9/Dunamis_Therapy_and_Fitness.jpg/1280px-Dunamis_Therapy_and_Fitness.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 933,
    "tags": [
      "equipment",
      "sports",
      "general"
    ],
    "credit": "Greatmats — CC BY-SA 4.0, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dunamis_Therapy_and_Fitness.jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/25/AWH_Pediatric_Physical_Therapy.JPG/1280px-AWH_Pediatric_Physical_Therapy.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 857,
    "tags": [
      "pediatric",
      "balance",
      "general"
    ],
    "credit": "Dr. P. K. Abdul Kader — CC BY-SA 4.0, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:AWH_Pediatric_Physical_Therapy.JPG"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6d/Occupational_Therapist_Melanie_Glapa_works_with_student_George_Hage_to_shape_the_hand_splint_for_hand_therapy_patient_%E2%80%98Pemoli%E2%80%99_at_the_physiotherapy_ward_at_the_National_Referral_Hospital%2C_Honiara._%2810711530113%29.jpg/1280px-thumbnail.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 857,
    "tags": [
      "wrist",
      "post-surgical"
    ],
    "credit": "Department of Foreign Affairs and Trade — CC BY 2.0, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Occupational_Therapist_Melanie_Glapa_works_with_student_George_Hage_to_shape_the_hand_splint_for_hand_therapy_patient_%E2%80%98Pemoli%E2%80%99_at_the_physiotherapy_ward_at_the_National_Referral_Hospital,_Honiara._(10711530113).jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ad/Spangdahlem_physical_therapy_rehabilitates_Airmen_after_injury_%287270858%29.jpg/1280px-Spangdahlem_physical_therapy_rehabilitates_Airmen_after_injury_%287270858%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 854,
    "tags": [
      "balance",
      "equipment",
      "gait"
    ],
    "credit": "U.S. Air Force photo by Staff Sgt. Chanceler Nardone — Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Spangdahlem_physical_therapy_rehabilitates_Airmen_after_injury_(7270858).jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/09/Spangdahlem_physical_therapy_rehabilitates_Airmen_after_injury_%287270860%29.jpg/1280px-Spangdahlem_physical_therapy_rehabilitates_Airmen_after_injury_%287270860%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 854,
    "tags": [
      "shoulder",
      "rotator cuff",
      "equipment"
    ],
    "credit": "U.S. Air Force photo by Staff Sgt. Chanceler Nardone — Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Spangdahlem_physical_therapy_rehabilitates_Airmen_after_injury_(7270860).jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9f/Spangdahlem_physical_therapy_rehabilitates_Airmen_after_injury_%287270864%29.jpg/1280px-Spangdahlem_physical_therapy_rehabilitates_Airmen_after_injury_%287270864%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 854,
    "tags": [
      "shoulder",
      "neck",
      "general"
    ],
    "credit": "U.S. Air Force photo by Staff Sgt. Chanceler Nardone — Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Spangdahlem_physical_therapy_rehabilitates_Airmen_after_injury_(7270864).jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7f/Pacific_Partnership_2024-1-_Physical_Therapy_Clinic_%288103289%29.jpg/1280px-Pacific_Partnership_2024-1-_Physical_Therapy_Clinic_%288103289%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 867,
    "tags": [
      "geriatric",
      "general"
    ],
    "credit": "U.S. Navy photo by Petty Officer 2nd Class Celia Martin — Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pacific_Partnership_2024-1-_Physical_Therapy_Clinic_(8103289).jpg"
  },
  {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/35/US_Navy_110613-N-YM336-079_Lynn_Boulanger%2C_an_occupational_therapy_assistant_and_certified_hand_therapist%2C_uses_mirror_therapy_to_help_address_phan.jpg/1280px-US_Navy_110613-N-YM336-079_Lynn_Boulanger%2C_an_occupational_therapy_assistant_and_certified_hand_therapist%2C_uses_mirror_therapy_to_help_address_phan.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "width": 1280,
    "height": 914,
    "tags": [
      "post-surgical",
      "gait"
    ],
    "credit": "U.S. Navy photo by Mass Communication Specialist Seaman Joseph A. Boomhower — Public domain, via Wikimedia Commons",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:US_Navy_110613-N-YM336-079_Lynn_Boulanger,_an_occupational_therapy_assistant_and_certified_hand_therapist,_uses_mirror_therapy_to_help_address_phan.jpg"
  }
];
