import type { Metadata } from "next";
import { LegalPageLayout } from "@/components/LegalPageLayout";

// Was falling back to the root layout's generic metadata (see app/layout.tsx) — see
// /founding-funders' own metadata export for why every publicly indexable route
// (sitemap.ts/robots.ts list all five) gets one instead.
export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Limbic's Terms of Service: the rules and agreements that govern use of the Limbic platform.",
};

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service" updated="August 31, 2026">
      <h2 className="legal-section-title">1. Acceptance of Terms</h2>
      <p className="legal-body">
        By accessing or using Limbic you agree to be bound by these Terms of Service. If you do not agree to these
        terms do not use the platform.
      </p>

      <h2 className="legal-section-title">2. What Limbic Is</h2>
      <p className="legal-body">
        Limbic is an information and community platform designed for physical therapy professionals, students, and
        the general public. Limbic curates publicly available research, clinical guidelines, and health and
        wellness content for educational purposes only.
      </p>

      <h2 className="legal-section-title">3. Not Medical Advice</h2>
      <p className="legal-body">
        Nothing on Limbic, including content generated by Limbic Agent, articles, guidelines, research summaries,
        community posts, outcome measure calculators, Force Lab comparisons, decision-support tools, or any other
        feature, constitutes medical advice, diagnosis, or treatment. These tools are provided for informational
        and clinical decision-support purposes only and do not replace a licensed clinician&rsquo;s own judgment.
        Always consult a licensed healthcare provider for medical decisions. Limbic is not a substitute for
        professional medical judgment.
      </p>

      <h2 className="legal-section-title">4. Clinician Responsibilities and Patient Data</h2>
      <p className="legal-body">
        Some LimbicPRO features let you record information about your own patients or clients — see the Privacy
        Policy for what this can include. If you are a licensed clinician using these features you represent and
        warrant that you have the right and, where required, the patient&rsquo;s or client&rsquo;s consent to enter
        and store that information, and that you will comply with HIPAA, your state&rsquo;s health information
        laws, your employer&rsquo;s policies, and every other legal or professional obligation that applies to you.
        Limbic is not a covered entity or business associate under HIPAA and does not offer a signed Business
        Associate Agreement. You are solely responsible for what you enter into these tools and for your own
        compliance obligations; Limbic disclaims any liability arising from your use of these features to record,
        store, or share information about a patient or client.
      </p>

      <h2 className="legal-section-title">5. Founding Funders</h2>
      <p className="legal-body">
        A Founding Funder membership is a lifetime subscription to Limbic. It is not an investment, equity stake, or
        ownership interest of any kind in Limbic, its research curation, its intellectual property, or any
        affiliated entity. Founding Funders receive lifetime access to LimbicPRO features and founding member
        recognition. They do not acquire any financial interest, ownership rights, or claims to Limbic content,
        data, or future revenue. All payments are final and non-refundable.
      </p>

      <h2 className="legal-section-title">6. User Content</h2>
      <p className="legal-body">
        You retain ownership of content you post on Limbic including Nexus posts, clips, and comments. By posting
        content you grant Limbic a non-exclusive license to display that content on the platform. You are solely
        responsible for content you post. You agree not to post content that is false, harmful, harassing, or
        violates any applicable law.
      </p>
      <p className="legal-body">
        This includes copyright. Do not post material you do not own or do not have permission to use. Limbic
        removes material that is the subject of a valid infringement notice and{" "}
        <strong>terminates the accounts of repeat infringers in appropriate circumstances</strong>. How notices
        are handled, how to dispute a removal, and how the repeat-infringer policy works are set out in our{" "}
        <a href="/dmca">Copyright &amp; DMCA Policy</a>.
      </p>

      <h2 className="legal-section-title">7. Third Party Integrations</h2>
      <p className="legal-body">
        Limbic lets you optionally connect third party accounts and services, including Google, Strava, and Fitbit.
        Connecting one of these is subject to that provider&rsquo;s own terms and privacy policy, and to whatever
        access permissions that provider grants you. Limbic does not control, and is not responsible for the
        availability, accuracy, or content of, any third party service.
      </p>

      <h2 className="legal-section-title">8. Platform Liability and Copyright Claims</h2>
      <p className="legal-body">
        Limbic is a platform that hosts user generated content. Consistent with Section 230 of the Communications
        Decency Act, Limbic is not responsible for content posted by users. Limbic reserves the right to remove
        content that violates these terms.
      </p>
      <p className="legal-body">
        Section 230 does not apply to intellectual property claims. Claims of copyright infringement are handled
        under our <a href="/dmca">Copyright &amp; DMCA Policy</a>, which sets out how to send a notice of alleged
        infringement, how to file a counter-notification, how to reach our designated copyright agent, and our
        policy of terminating the accounts of repeat infringers.
      </p>

      <h2 className="legal-section-title">9. Subscriptions and Payments</h2>
      <p className="legal-body">
        Subscription fees are charged on a monthly or annual basis depending on your selected plan. You may cancel
        your subscription at any time. Cancellation takes effect at the end of your current billing period. Limbic
        does not offer refunds for partial billing periods. Founding Funder payments are one time and
        non-refundable.
      </p>

      <h2 className="legal-section-title">10. Intellectual Property</h2>
      <p className="legal-body">
        All Limbic owned content, branding, design, software, and features, including but not limited to Limbic
        Agent, Limbic Boards, Limbic Threads, The Movement Lab, and Limbic Vitals, are the exclusive intellectual
        property of Limbic. You may not copy, reproduce, distribute, or create derivative works from any Limbic
        owned content without explicit written permission.
      </p>

      <h2 className="legal-section-title">11. Account Termination</h2>
      <p className="legal-body">
        Limbic reserves the right to suspend or terminate any account that violates these terms, engages in harmful
        behavior, or misrepresents professional credentials. Founding Funder lifetime memberships may be terminated
        for violations of these terms without refund.
      </p>

      <h2 className="legal-section-title">12. Disclaimers</h2>
      <p className="legal-body">
        Limbic is provided as is and as available, without warranties of any kind, express or implied. Limbic does
        not guarantee the accuracy, completeness, or timeliness of any content, calculation, or output on the
        platform, including AI-generated content and clinical decision-support tools. Research and clinical
        guidelines are sourced from publicly available databases and are presented for informational purposes only.
      </p>

      <h2 className="legal-section-title">13. Limitation of Liability</h2>
      <p className="legal-body">
        To the fullest extent permitted by law, Limbic shall not be liable for any indirect, incidental, special,
        consequential, or punitive damages arising from your use of the platform. To the fullest extent permitted
        by law, Limbic&rsquo;s total liability to you for any claim arising out of or relating to these terms or
        your use of Limbic will not exceed the greater of one hundred dollars ($100) or the amount you paid Limbic
        in the twelve (12) months before the claim arose.
      </p>

      <h2 className="legal-section-title">14. Indemnification</h2>
      <p className="legal-body">
        You agree to indemnify and hold Limbic harmless from any claim, loss, liability, or expense (including
        reasonable attorneys&rsquo; fees) arising out of your use of the platform, your content, your violation of
        these terms, or your violation of any law or the rights of a third party — including any claim arising from
        information you enter about a patient or client under Section 4.
      </p>

      <h2 className="legal-section-title">15. Dispute Resolution</h2>
      <p className="legal-body">
        Before filing a claim against Limbic, you agree to first contact us at the address below and attempt to
        resolve the dispute informally. Any dispute that cannot be resolved informally shall be resolved through
        binding arbitration on an individual basis, and not as a class, collective, or representative action,
        except that either party may bring an individual claim in small claims court. This section does not apply
        to claims that either party may bring in court to seek injunctive or other equitable relief.
      </p>

      <h2 className="legal-section-title">16. Governing Law</h2>
      <p className="legal-body">
        These terms are governed by the laws of the State of California. Any disputes not subject to arbitration
        under Section 15 shall be resolved in the courts of Orange County, California.
      </p>

      <h2 className="legal-section-title">17. Changes to Terms</h2>
      <p className="legal-body">
        Limbic reserves the right to update these terms at any time. Continued use of the platform after changes
        constitutes acceptance of the updated terms.
      </p>

      <h2 className="legal-section-title">18. Contact</h2>
      <p className="legal-body">For questions about these terms contact: limbic.center</p>
      <p className="legal-body">Newport Beach, California</p>
    </LegalPageLayout>
  );
}
