import type { Metadata } from "next";
import { LegalPageLayout } from "@/components/LegalPageLayout";

// Was falling back to the root layout's generic metadata (see app/layout.tsx) — see
// /founding-funders' own metadata export for why every publicly indexable route
// (sitemap.ts/robots.ts list all five) gets one instead.
export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Limbic's Terms of Service: the rules and agreements that govern use of the Limbic platform.",
};

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service" updated="August 14, 2026">
      <h2 className="legal-section-title">1. Acceptance of Terms</h2>
      <p className="legal-body">
        By accessing or using Limbic you agree to be bound by these Terms of Service. If you do not agree to these
        terms do not use the platform.
      </p>

      <h2 className="legal-section-title">2. What Limbic Is</h2>
      <p className="legal-body">
        Limbic is an information and community platform designed for physical therapy professionals, students, and
        the general public. Limbic curates publicly available research, clinical guidelines, and health and
        wellness content for educational purposes only.
      </p>

      <h2 className="legal-section-title">3. Not Medical Advice</h2>
      <p className="legal-body">
        Nothing on Limbic, including content generated by Limbic Agent, articles, guidelines, research summaries,
        or community posts, constitutes medical advice, diagnosis, or treatment. Limbic Agent is a clinical
        decision support tool for informational purposes only. Always consult a licensed healthcare provider for
        medical decisions. Limbic is not a substitute for professional medical judgment.
      </p>

      <h2 className="legal-section-title">4. Founding Funders</h2>
      <p className="legal-body">
        A Founding Funder membership is a lifetime subscription to Limbic. It is not an investment, equity stake, or
        ownership interest of any kind in Limbic, its research curation, its intellectual property, or any
        affiliated entity. Founding Funders receive lifetime access to LimbicPRO features and founding member
        recognition. They do not acquire any financial interest, ownership rights, or claims to Limbic content,
        data, or future revenue. All payments are final and non-refundable.
      </p>

      <h2 className="legal-section-title">5. User Content</h2>
      <p className="legal-body">
        You retain ownership of content you post on Limbic including Nexus posts, clips, and comments. By posting
        content you grant Limbic a non-exclusive license to display that content on the platform. You are solely
        responsible for content you post. You agree not to post content that is false, harmful, harassing, or
        violates any applicable law.
      </p>

      <h2 className="legal-section-title">6. Platform Liability</h2>
      <p className="legal-body">
        Limbic is a platform that hosts user generated content. Consistent with Section 230 of the Communications
        Decency Act, Limbic is not responsible for content posted by users. Limbic reserves the right to remove
        content that violates these terms.
      </p>

      <h2 className="legal-section-title">7. Subscriptions and Payments</h2>
      <p className="legal-body">
        Subscription fees are charged on a monthly or annual basis depending on your selected plan. You may cancel
        your subscription at any time. Cancellation takes effect at the end of your current billing period. Limbic
        does not offer refunds for partial billing periods. Founding Funder payments are one time and
        non-refundable.
      </p>

      <h2 className="legal-section-title">8. Intellectual Property</h2>
      <p className="legal-body">
        All Limbic owned content, branding, design, software, and features, including but not limited to Limbic
        Agent, Limbic Boards, Limbic Threads, The Movement Lab, and Limbic Vitals, are the exclusive intellectual
        property of Limbic. You may not copy, reproduce, distribute, or create derivative works from any Limbic
        owned content without explicit written permission.
      </p>

      <h2 className="legal-section-title">9. Account Termination</h2>
      <p className="legal-body">
        Limbic reserves the right to suspend or terminate any account that violates these terms, engages in harmful
        behavior, or misrepresents professional credentials. Founding Funder lifetime memberships may be terminated
        for violations of these terms without refund.
      </p>

      <h2 className="legal-section-title">10. Disclaimers</h2>
      <p className="legal-body">
        Limbic is provided as is without warranties of any kind. Limbic does not guarantee the accuracy,
        completeness, or timeliness of any content on the platform. Research and clinical guidelines are sourced
        from publicly available databases and are presented for informational purposes only.
      </p>

      <h2 className="legal-section-title">11. Limitation of Liability</h2>
      <p className="legal-body">
        To the fullest extent permitted by law, Limbic shall not be liable for any indirect, incidental, special, or
        consequential damages arising from your use of the platform.
      </p>

      <h2 className="legal-section-title">12. Governing Law</h2>
      <p className="legal-body">
        These terms are governed by the laws of the State of California. Any disputes shall be resolved in the
        courts of Orange County, California.
      </p>

      <h2 className="legal-section-title">13. Changes to Terms</h2>
      <p className="legal-body">
        Limbic reserves the right to update these terms at any time. Continued use of the platform after changes
        constitutes acceptance of the updated terms.
      </p>

      <h2 className="legal-section-title">14. Contact</h2>
      <p className="legal-body">For questions about these terms contact: limbic.center</p>
      <p className="legal-body">Newport Beach, California</p>
    </LegalPageLayout>
  );
}
