"use client";

import { useState, useTransition } from "react";
import { generatePreVisitBriefAction, type PatientDetail } from "@/app/actions/clinician-dashboard";
import { NetworkIcon } from "@/components/icons";

function isToday(d: Date): boolean {
  const now = new Date();
  return d.getFullYear() === now.getFullYear() && d.getMonth() === now.getMonth() && d.getDate() === now.getDate();
}

/** The clinician-facing pre-visit brief (see lib/pre-visit-brief.ts generateClinicalBrief)
 *  — distinct from the patient-facing summary reviewed inside the "Prepare for Patient"
 *  modal (PreparePatientModal.tsx), which is never shown here. Looks for a brief already
 *  generated today in `patient.preBriefs` before showing the generate button, so reopening
 *  a patient later the same day doesn't call the model again for nothing. */
export function PreVisitBriefSection({ patient }: { patient: PatientDetail }) {
  const [pending, startTransition] = useTransition();
  const [localBrief, setLocalBrief] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const savedToday = patient.preBriefs.find((b) => !b.patientFacing && isToday(new Date(b.generatedAt)));
  const brief = localBrief ?? savedToday?.brief ?? null;

  const handleGenerate = () => {
    setError(null);
    startTransition(async () => {
      const result = await generatePreVisitBriefAction(patient.id);
      if (!result.ok) {
        setError(result.error);
        return;
      }
      setLocalBrief(result.brief);
    });
  };

  return (
    <div className="clindash-section">
      <div className="clindash-section-header">
        <div className="card-kicker" style={{ margin: 0 }}>
          Pre-Visit Brief
        </div>
        {brief && (
          <button type="button" className="btn btn-ghost" style={{ fontSize: 12 }} onClick={handleGenerate} disabled={pending}>
            {pending ? "Regenerating…" : "Regenerate"}
          </button>
        )}
      </div>

      {error && <p style={{ fontSize: 12, color: "var(--color-danger)", margin: "0 0 8px" }}>{error}</p>}

      {brief ? (
        <>
          <div className="clindash-brief-box">{brief}</div>
          <p className="clindash-disclaimer">
            Generated by Limbic Agent as a starting point for clinical reasoning — not a diagnosis and not medical
            advice. Review before relying on it in patient care.
          </p>
        </>
      ) : (
        <button type="button" className="btn btn-primary" onClick={handleGenerate} disabled={pending}>
          <NetworkIcon size={14} />
          {pending ? "Generating…" : "Generate Pre-Visit Brief"}
        </button>
      )}
    </div>
  );
}
