-- CreateTable
CREATE TABLE "ConnexionSafetyAssessment" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "administeredById" TEXT NOT NULL,
    "visitRequestId" TEXT,
    "clientName" TEXT NOT NULL,
    "clientAddress" TEXT,
    "assessmentDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "itemScores" TEXT NOT NULL,
    "environmentalScore" INTEGER NOT NULL,
    "mobilityScore" INTEGER NOT NULL,
    "fallRiskScore" INTEGER NOT NULL,
    "totalScore" INTEGER NOT NULL,
    "riskLevel" TEXT NOT NULL,
    "criticalFindings" TEXT NOT NULL DEFAULT '[]',
    "criticalFindingsOther" TEXT,
    "equipment" TEXT NOT NULL DEFAULT '[]',
    "caregiverSkills" TEXT NOT NULL DEFAULT '{}',
    "priorityActionsUrgent" TEXT,
    "priorityActionsSoon" TEXT,
    "priorityActionsMonitor" TEXT,
    "biggestRisk" TEXT,
    "mostImportantChange" TEXT,
    "equipmentRecommendedNote" TEXT,
    "caregiverTrainingNote" TEXT,
    "followUp" TEXT,
    "followUpOther" TEXT,
    "ptRecommendation" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "ConnexionSafetyAssessment_administeredById_fkey" FOREIGN KEY ("administeredById") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "ConnexionSafetyAssessment_visitRequestId_fkey" FOREIGN KEY ("visitRequestId") REFERENCES "ConnexionVisitRequest" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
