# -*- coding: utf-8 -*-
"""Axial: abdominal wall, back, breathing, pelvic floor, neck."""
from common import M, T, C, X

TRUNK = dict(
    id="trunk", nav="Trunk", title="Trunk — abdominal wall, quadratus lumborum and the back",
    lede="""Trunk strength is graded by lever length, not by the examiner's hand: the arm position
      changes how much of the body the muscles have to lift. The abdominal wall is four muscles in
      three layers whose fibres cross at angles, and the back is a superficial column (erector
      spinae) over a deep one (transversospinalis). All the back muscles proper are on the
      posterior rami — the ones on the back that are not (trapezius, latissimus, rhomboids,
      serratus posterior) moved there from the limb or the ribs.""",
    groups=[
    ("Anterolateral abdominal wall", [
     M("Rectus abdominis", "abwall",
       "Pubic symphysis and pubic crest.",
       "Xiphoid process and costal cartilages 5–7.",
       "Thoraco-abdominal nn. (anterior rami T7–T11) and subcostal n. (T12).",
       "Flexes the trunk (lumbar spine); compresses the abdominal contents; posteriorly tilts the pelvis.",
       T("supine, hips and knees flexed or legs straight.",
         "none for the curl-up; do not hold the feet down.",
         "patient curls the trunk until the inferior angles of the scapulae clear the table. Grade by arm position: hands behind the head (5), arms crossed on the chest (4), arms reaching forward (3).",
         "patient can lift the head but not clear the scapulae; or the rib cage depresses on attempted curl."),
       "<b>Hip flexors take over once the scapulae clear</b> — past that point it is a sit-up, and holding the feet down lets iliopsoas lift the whole trunk. Lifting only the head is neck flexion. Momentum from swinging the arms shortens the lever."),
     M("External oblique", "abwall",
       "External surfaces of ribs 5–12.",
       "Linea alba, pubic tubercle, anterior half of the iliac crest.",
       "Thoraco-abdominal nn. (T7–T11) and subcostal n. (T12).",
       "Flexes and laterally flexes the trunk; rotates the trunk to the <i>opposite</i> side; compresses the abdomen.",
       T("supine, hips and knees flexed.", "none.",
         "patient curls up and rotates, bringing one shoulder toward the opposite hip. Rotating to the left tests the right external oblique and the left internal oblique. Grade by arm position, as for rectus abdominis.",
         "sitting, patient rotates the trunk without resistance, or cannot clear the scapula on the rotating side."),
       "<b>Pectoralis major pulls the arm across</b> and the shoulder follows without the thorax rotating. Shoulder protraction fakes the reach."),
     M("Internal oblique", "abwall",
       "Thoracolumbar fascia, anterior two-thirds of the iliac crest, connective tissue deep to the lateral inguinal ligament.",
       "Inferior borders of ribs 10–12, linea alba, pecten pubis via the conjoint tendon.",
       "Thoraco-abdominal nn. (T7–T11), subcostal n. (T12), first lumbar n. (L1).",
       "Flexes and laterally flexes the trunk; rotates the trunk to the <i>same</i> side; compresses the abdomen.",
       "<b>Tested with the opposite external oblique</b> in the rotating curl-up. " + C(),
       "Same as external oblique."),
     M("Transversus abdominis", "abwall",
       "Internal surfaces of costal cartilages 7–12, thoracolumbar fascia, iliac crest, connective tissue deep to the lateral inguinal ligament.",
       "Linea alba with the internal oblique aponeurosis; pubic crest and pecten pubis via the conjoint tendon.",
       "Thoraco-abdominal nn. (T7–T11), subcostal n. (T12), first lumbar n. (L1).",
       "Compresses and supports the abdominal contents; tensions the thoracolumbar fascia.",
       "<b>No graded manual test.</b> Patient draws the lower abdomen in without moving the spine or pelvis; palpate the tension just medial and inferior to the ASIS. The prone pressure-biofeedback version, with a cuff under the abdomen, is a clinical convention. " + C(),
       "<b>Breath-holding and posterior pelvic tilt</b> pull the abdomen in without transversus; so does rectus abdominis, which flattens rather than draws in."),
     M("Pyramidalis", "abwall",
       "Body of the pubis, in front of rectus abdominis.",
       "Linea alba.",
       "Subcostal n. (T12).",
       "Tenses the linea alba.",
       "<b>No clinical test.</b> Absent in some people. " + C(),
       "Nothing to fake."),
    ]),
    ("Posterior abdominal wall", [
     M("Quadratus lumborum", "ql",
       "Iliolumbar ligament and the internal lip of the iliac crest.",
       "Medial half of the inferior border of rib 12; tips of the lumbar transverse processes.",
       "Anterior rami of T12 and L1–L4.",
       "Laterally flexes the trunk; hikes the pelvis; fixes rib 12 during inspiration; extends the lumbar spine bilaterally.",
       T("prone or supine, legs straight, holding the table edge.",
         "none — you pull on the leg.",
         "patient hikes the pelvis toward the rib cage on the tested side; resist by pulling the leg caudally at the ankle.",
         "the same, with gentle traction only."),
       "<b>Lateral abdominals and latissimus</b> side-bend the trunk; the pelvis should move toward the ribs, not the ribs toward the pelvis. Hip abduction on the opposite side shifts the pelvis."),
    ]),
    ("Back — erector spinae (superficial column)", [
     M("Iliocostalis (lumborum, thoracis, cervicis)", "back",
       "Common tendon from the posterior iliac crest, posterior sacrum, sacroiliac ligaments, lower lumbar spinous processes.",
       "Angles of the lower ribs; transverse processes of the lower cervical vertebrae.",
       "Posterior rami of the spinal nerves.",
       "Bilaterally extends the vertebral column and controls flexion; unilaterally flexes it laterally.",
       T("prone, a pillow under the abdomen if needed, hands behind the head (harder) or at the sides (easier).",
         "the legs above the ankles, or the pelvis for a thoracic bias.",
         "patient lifts the chest off the table until the umbilicus clears; hold. Grade by arm position and whether full range is held. The Biering-Sørensen hold (trunk unsupported over the table edge) times the same muscles for endurance; its norms vary widely between samples. " + X(),
         "patient cannot lift the chest but contraction is visible or palpable."),
       "<b>Gluteus maximus and the hamstrings</b> extend the hip and lift the trunk through the pelvis if the legs are not stabilized. Lifting only the head is cervical extension."),
     M("Longissimus (thoracis, cervicis, capitis)", "back",
       "Common erector tendon; transverse processes of the upper thoracic and lower cervical vertebrae.",
       "Transverse processes of the thoracic and cervical vertebrae, ribs between tubercle and angle, mastoid process (capitis).",
       "Posterior rami of the spinal nerves.",
       "Extends and laterally flexes the vertebral column; capitis extends the head and turns the face to the same side.",
       "<b>Tested with the erector spinae</b> (see iliocostalis). " + C(),
       "Same as iliocostalis."),
     M("Spinalis (thoracis, cervicis, capitis)", "back",
       "Thoracis: spinous processes of T11–L2. Cervicis, when present: ligamentum nuchae and the spinous process of C7.",
       "Thoracis: spinous processes of the upper thoracic vertebrae. Cervicis: axis and C3–C4. Capitis is usually a few semispinalis fibres on the spinous processes of C7 and T1, not the skull.",
       "Posterior rami of the spinal nerves.",
       "Extends the vertebral column.",
       "<b>Tested with the erector spinae</b> (see iliocostalis). " + C(),
       "Same as iliocostalis."),
    ]),
    ("Back — transversospinalis and small segmental muscles (deep)", [
     M("Semispinalis (thoracis, cervicis, capitis)", "back",
       "Transverse processes of C4–T10.",
       "Spinous processes 4–6 segments above; capitis to the occipital bone between the nuchal lines.",
       "Posterior rami of the spinal nerves.",
       "Extends the head and the thoracic and cervical spine; rotates them to the opposite side.",
       "<b>Tested with trunk and neck extension.</b> Semispinalis capitis is the bulk of the posterior neck either side of the midline. " + C(),
       "Same as the erector spinae and the neck extensors."),
     M("Multifidus", "back",
       "Posterior sacrum, posterior superior iliac spine, mammillary processes of the lumbar vertebrae, transverse processes of the thoracic vertebrae, articular processes of C4–C7.",
       "Spinous processes 2–4 segments above.",
       "Posterior rami of the spinal nerves.",
       "Stabilizes the vertebrae segment by segment during movement; extends and rotates.",
       "<b>No graded manual test.</b> Palpate the swelling of the muscle just lateral to the lumbar spinous processes as the patient gently swells it, or during a small contralateral arm lift in prone. Ultrasound is the research method. " + C(),
       "<b>The erector spinae</b> produce the same palpable tension with any trunk extension — the contraction should come without the spine moving."),
     M("Rotatores", "back",
       "Transverse processes of the vertebrae.",
       "Laminae or spinous processes 1–2 segments above.",
       "Posterior rami of the spinal nerves.",
       "Stabilize the vertebrae; assist extension and rotation; proprioception.",
       "<b>No clinical test.</b> " + C(),
       "Nothing to fake."),
     M("Interspinales and intertransversarii", "back",
       "Spinous processes (interspinales) or transverse processes (intertransversarii) of one vertebra.",
       "The corresponding process of the vertebra above.",
       "Posterior rami; intertransversarii also anterior rami.",
       "Extend (interspinales) and laterally flex (intertransversarii) the vertebral column segmentally.",
       "<b>No clinical test.</b> " + C(),
       "Nothing to fake."),
    ]),
    ("Back — superficial intermediate layer", [
     M("Serratus posterior superior", "thoraxm",
       "Ligamentum nuchae and the spinous processes of C7–T3.",
       "Superior borders of ribs 2–4 (or 2–5).",
       "Intercostal nn. 2–5.",
       "Traditionally described as elevating the ribs; now thought to be mainly proprioceptive. " + X(),
       "<b>No clinical test.</b> " + C(),
       "Nothing to fake."),
     M("Serratus posterior inferior", "thoraxm",
       "Spinous processes of T11–L2.",
       "Inferior borders of ribs 8–12 (or 9–12).",
       "Anterior rami of T9–T12.",
       "Traditionally described as depressing the ribs; now thought to be mainly proprioceptive. " + X(),
       "<b>No clinical test.</b> " + C(),
       "Nothing to fake."),
     M("Levatores costarum", "thoraxm",
       "Tips of the transverse processes of C7–T11.",
       "The rib below, between its tubercle and angle.",
       "Posterior rami of C8–T11.",
       "Elevate the ribs; assist lateral flexion of the vertebral column.",
       "<b>No clinical test.</b> " + C(),
       "Nothing to fake."),
    ]),
    ],
)

BREATH = dict(
    id="breathing", nav="Breathing &amp; pelvic floor", title="Breathing muscles and the pelvic floor",
    lede="""The diaphragm does quiet inspiration by itself; everything else here is recruited when
      breathing gets harder or when the abdomen has to hold pressure. The pelvic floor closes the
      bottom of the same pressurized canister. None of these is graded against the examiner's
      hand — they are observed, measured, or, for the pelvic floor, palpated internally by a
      clinician trained and consented to do it.""",
    groups=[
    ("Breathing", [
     M("Diaphragm", "diaphragm",
       "Sternal part: back of the xiphoid process. Costal part: inner surfaces of the lower six costal cartilages and ribs. Lumbar part: L1–L3 bodies via the crura, and the medial and lateral arcuate ligaments.",
       "Central tendon.",
       "Phrenic nn. (C3, C4, C5) — the whole motor supply.",
       "The main muscle of inspiration: descends and flattens, increasing the vertical dimension of the thorax and pushing the abdominal wall out.",
       "<b>Observe, then measure.</b> Supine, the epigastrium should rise with each quiet breath while the upper chest stays still. A hand on the upper abdomen during a sniff gives a crude resistance. Vital capacity and maximal inspiratory pressure are the numbers; paradoxical inward movement of the abdomen on inspiration in supine is the sign of bilateral weakness. " + C(),
       "<b>Accessory muscles lift the chest</b> — scalenes, SCM and upper trapezius raise the thorax while the abdomen draws in, and a quick glance reads that as a deep breath."),
     M("External intercostals", "intercostal",
       "Inferior border of the rib above.",
       "Superior border of the rib below; fibres run down and forward.",
       "Intercostal nn. (T1–T11).",
       "Elevate the ribs in forced inspiration; stiffen the intercostal spaces.",
       "<b>Observe and measure chest expansion:</b> tape around the chest at a fixed level (the 4th intercostal space or the xiphoid), full expiration to full inspiration, left and right sides compared by hand placement. Normal values depend on the level and the population measured. " + X(),
       "<b>Upper-chest lift by the accessory muscles</b> inflates the reading at the upper level while the lower ribs barely move."),
     M("Internal and innermost intercostals, subcostales, transversus thoracis", "intercostal",
       "Internal: inferior border of the rib above (fibres down and back). Innermost and subcostales: internal surfaces of the ribs. Transversus thoracis: back of the lower sternum.",
       "Internal and innermost: superior border of the rib below. Subcostales: 2–3 ribs below. Transversus thoracis: internal surfaces of costal cartilages 2–6.",
       "Intercostal nn. (T1–T11).",
       "Depress the ribs in forced expiration (the interosseous internal intercostals); stiffen the chest wall.",
       "<b>Observe forced expiration and cough.</b> Cough strength is the functional test of the expiratory muscles, which are mostly the abdominals. " + C(),
       "A weak cough may be abdominal, glottic or inspiratory — a cough needs a big breath in first."),
    ]),
    ("Pelvic floor (pelvic diaphragm)", [
     M("Levator ani (pubococcygeus, puborectalis, iliococcygeus)", "levani",
       "Body of the pubis, tendinous arch of the obturator fascia, ischial spine.",
       "Perineal body, coccyx, anococcygeal ligament, walls of the prostate or vagina, rectum and anal canal.",
       "Nerve to levator ani (branches of S4), inferior anal (rectal) n. from the pudendal n. (S2–S4), coccygeal plexus.",
       "Supports the pelvic organs; resists rises in abdominal pressure; puborectalis kinks the anorectal junction forward, which is part of faecal continence.",
       "<b>Internal palpation</b> (vaginal or rectal), by a clinician trained and consented to do it, graded on the Modified Oxford Scale 0–5: 0 none, 1 flicker, 2 weak, 3 moderate with lift, 4 good with lift against resistance, 5 strong. Externally: observe the perineum lift inward on 'squeeze and lift'. " + C(),
       "<b>Gluteal squeeze, hip adduction, breath-holding and bearing down</b> all look like effort; bearing down moves the perineum outward — the opposite of a contraction."),
     M("Coccygeus (ischiococcygeus)", "pelvicfloor",
       "Ischial spine.",
       "Inferior end of the sacrum and the coccyx.",
       "Branches of the anterior rami of S3–S4.",
       "Supports the pelvic organs; flexes the coccyx.",
       "<b>Tested with levator ani.</b> " + C(),
       "Same as levator ani."),
     M("External anal sphincter", "analtri",
       "Skin and fascia around the anus; coccyx via the anococcygeal ligament.",
       "Perineal body.",
       "Inferior anal (rectal) n. from the pudendal n. (S2–S4).",
       "Closes the anal canal voluntarily.",
       "<b>Voluntary anal contraction</b> on digital examination is part of the international spinal cord injury examination, where its presence makes an injury motor incomplete. The anal wink (S2–S4) is the reflex form. " + C(),
       "<b>Gluteal squeeze</b> and an anal wink reflex both close the anus without voluntary sphincter control."),
     M("Perineal muscles (bulbospongiosus, ischiocavernosus, transverse perinei, external urethral sphincter)", "deepperineal",
       "Perineal body, ischial rami and tuberosities.",
       "Perineal body, corpora, urethra, perineal membrane.",
       "Pudendal n., perineal branches (S2–S4). The external urethral sphincter also receives direct somatic branches of the sacral plexus that run on levator ani.",
       "Support the perineal body; compress the urethra (voluntary urinary continence); maintain erection.",
       "<b>Reflex and history:</b> the bulbocavernosus reflex tests the S2–S4 arc. Voluntary control is judged with the pelvic floor. " + C(),
       "Nothing separately graded."),
    ]),
    ],
)

NECK = dict(
    id="neck", nav="Neck", title="Neck — flexors, extensors, the hyoid muscles and platysma",
    lede="""Two neck flexor systems: superficial (SCM and scalenes), which lift the head by pushing
      the chin forward, and deep (longus colli and capitis), which nod the chin down and hold the
      cervical curve. A strong head lift says nothing about the deep flexors — that is the reason
      the craniocervical flexion test exists. The hyoid muscles act on the jaw and the larynx
      rather than the neck, and are tested in swallowing.""",
    groups=[
    ("Anterolateral", [
     M("Sternocleidomastoid", "scm",
       "Sternal head: upper edge of the manubrium. Clavicular head: medial quarter of the clavicle.",
       "Lateral surface of the mastoid process and the anterior part of the superior nuchal line.",
       "Spinal accessory n. (CN XI), motor; C2–C3 carry proprioception.",
       "Unilaterally: laterally flexes the neck and rotates the face to the <i>opposite</i> side and up. Bilaterally: extends the head when the cervical spine is free to move, and flexes the neck when the spine is held rigid; accessory inspiration.",
       T("supine, head rotated away from the tested side.", "the thorax.",
         "patient lifts the head off the table; resist at the temporal region obliquely down and back.",
         "sidelying with the head supported, rotate the head; or supine, rotate without lifting."),
       "<b>Platysma</b> grimaces and tenses the neck skin. Chin poking forward as the head lifts is SCM working without the deep flexors — a finding about the deep flexors, not SCM."),
     M("Anterior scalene", "scalene",
       "Anterior tubercles of the transverse processes of C3–C6.",
       "Scalene tubercle of rib 1.",
       "Anterior rami of C4–C6.",
       "Laterally flexes and flexes the neck; elevates rib 1 in forced inspiration.",
       T("supine.", "the thorax.",
         "patient lifts the head in anterolateral flexion without rotating; resist at the temporal region obliquely down.",
         "sidelying with the head supported, laterally flex."),
       "<b>SCM</b> joins in and adds rotation — keep the face forward."),
     M("Middle scalene", "scalene",
       "Posterior tubercles of the transverse processes of C2–C7.",
       "Superior surface of rib 1, behind the groove for the subclavian artery.",
       "Anterior rami of C3–C8.",
       "Laterally flexes the neck; elevates rib 1 in forced inspiration.",
       "<b>Tested with the anterior scalene</b> in lateral flexion. " + C(),
       "Same as anterior scalene."),
     M("Posterior scalene", "scalene",
       "Posterior tubercles of the transverse processes of the last 3 or 4 cervical vertebrae.",
       "Anterior surface of rib 2.",
       "Anterior rami of C6–C8.",
       "Laterally flexes the neck; elevates rib 2 in forced inspiration.",
       "<b>Tested with the other scalenes.</b> " + C(),
       "Same as anterior scalene."),
    ]),
    ("Deep anterior (prevertebral)", [
     M("Longus colli", "prevert",
       "Bodies of C5–T3; transverse processes of C3–C5.",
       "Anterior tubercle of the atlas; bodies of C2–C4; transverse processes of C5–C6.",
       "Anterior rami of C2–C6.",
       "Flexes the neck and holds the cervical lordosis from collapsing into extension.",
       "<b>Craniocervical flexion test:</b> supine, a pressure cuff under the upper neck at 20 mmHg; the patient nods the chin in gently to hold 22, 24, 26, 28 then 30 mmHg in turn, 10 s each, without the superficial flexors taking over. Deep neck flexor endurance (chin tucked, head held just off the table, timed) is the endurance form; its norms vary by sample. " + C(),
       "<b>SCM and the scalenes</b> lift instead of nodding — the chin pokes forward, the head leaves the pillow, or the SCM stands out. Holding the breath raises the cuff pressure."),
     M("Longus capitis", "prevert",
       "Anterior tubercles of the transverse processes of C3–C6.",
       "Basilar part of the occipital bone.",
       "Anterior rami of C1–C3.",
       "Flexes the head on the neck (nodding).",
       "<b>Tested with longus colli</b> in the craniocervical flexion test. " + C(),
       "Same as longus colli."),
     M("Rectus capitis anterior and lateralis", "prevert",
       "Anterior: lateral mass of the atlas. Lateralis: transverse process of the atlas.",
       "Anterior: base of the skull in front of the occipital condyle. Lateralis: jugular process of the occipital bone.",
       "Branches from the loop between C1 and C2.",
       "Anterior flexes the head; lateralis laterally flexes it and steadies it.",
       "<b>No isolated test.</b> " + C(),
       "Nothing to fake."),
    ]),
    ("Posterior", [
     M("Splenius capitis", "postcerv",
       "Lower half of the ligamentum nuchae; spinous processes of C7–T3/T4.",
       "Lateral superior nuchal line and the mastoid process.",
       "Posterior rami of the middle cervical nerves.",
       "Unilaterally: laterally flexes and rotates the head to the <i>same</i> side. Bilaterally: extends the head and neck.",
       T("prone, head over the table edge or on the forehead.", "the upper thoracic spine.",
         "patient extends the head and neck, lifting the face; resist at the occiput. Turning the face toward the tested side and extending biases splenius; resist posterolaterally.",
         "sidelying with the head supported, extend."),
       "<b>Thoracic extension lifts the head</b> without the neck moving — stabilize the upper back."),
     M("Splenius cervicis", "postcerv",
       "Spinous processes of T3–T6.",
       "Transverse processes of C1–C3 (or C4).",
       "Posterior rami of the lower cervical nerves.",
       "Unilaterally rotates and laterally flexes the neck to the same side; bilaterally extends it.",
       "<b>Tested with splenius capitis</b> in neck extension. " + C(),
       "Same as splenius capitis."),
     M("Suboccipital group (rectus capitis posterior major and minor, obliquus capitis superior and inferior)", "subocc",
       "Major and obliquus inferior: spinous process of C2. Minor: posterior tubercle of the atlas. Obliquus superior: transverse process of the atlas.",
       "Major: lateral inferior nuchal line. Minor: medial inferior nuchal line. Obliquus superior: occipital bone between the nuchal lines. Obliquus inferior: transverse process of the atlas.",
       "Suboccipital n. (posterior ramus of C1).",
       "Extend the head (the recti and obliquus superior); rotate the head to the same side (rectus major, and obliquus inferior turning the atlas on the axis); fine proprioceptive control of head position.",
       T("prone, head over the table edge.", "the neck at C2 with one hand.",
         "patient tips the head back (capital extension, 'look up with the eyes and chin' without the neck bending); resist at the occiput."),
       "<b>The long neck extensors</b> extend the whole neck — the movement should be a nod at the top of the neck only."),
    ]),
    ("Platysma and the hyoid muscles", [
     M("Platysma", "platysma",
       "Fascia over pectoralis major and deltoid in the upper chest; the fibres cross the clavicle.",
       "Base of the mandible, skin of the cheek and lower lip, angle of the mouth.",
       "Cervical branch of the facial n. (CN VII).",
       "Tenses the skin of the neck (grimace); depresses the mandible and the corners of the mouth.",
       "<b>Observe:</b> patient clenches the teeth and draws the corners of the mouth down hard — vertical ridges stand out in the neck skin. Graded by observation only. " + C(),
       "Depressor anguli oris pulls the mouth down without the neck ridges."),
     M("Digastric", "digastric",
       "Anterior belly: digastric fossa of the mandible. Posterior belly: mastoid notch of the temporal bone.",
       "Intermediate tendon, held to the body and greater horn of the hyoid by a fibrous sling.",
       "Anterior belly: nerve to mylohyoid (CN V3). Posterior belly: facial n. (CN VII).",
       "Depresses the mandible against resistance; elevates and steadies the hyoid in swallowing and speech.",
       "<b>Resisted opening:</b> resist under the chin as the patient opens the mouth; palpate under the jaw. Swallowing is the functional test for the whole suprahyoid group. " + C(),
       "<b>Lateral pterygoid and gravity</b> open the jaw; resisted opening loads the suprahyoids and lateral pterygoids together."),
     M("Mylohyoid", "suprahyoid",
       "Mylohyoid line of the mandible.",
       "Mylohyoid raphe and the body of the hyoid.",
       "Nerve to mylohyoid (CN V3).",
       "Elevates the hyoid, the floor of the mouth and the tongue in swallowing and speech; depresses the mandible.",
       "<b>Tested with the suprahyoids</b> (see digastric). " + C(),
       "Same as digastric."),
     M("Geniohyoid", "suprahyoid",
       "Inferior mental spine of the mandible.",
       "Body of the hyoid.",
       "C1 fibres running with the hypoglossal n.",
       "Pulls the hyoid up and forward, widening the pharynx; depresses the mandible.",
       "<b>Tested with the suprahyoids</b> (see digastric). " + C(),
       "Same as digastric."),
     M("Stylohyoid", "suprahyoid",
       "Styloid process of the temporal bone.",
       "Body of the hyoid.",
       "Stylohyoid branch of the facial n. (CN VII).",
       "Elevates and retracts the hyoid, lengthening the floor of the mouth.",
       "<b>Tested with the suprahyoids</b> (see digastric). " + C(),
       "Same as digastric."),
     M("Infrahyoids (sternohyoid, omohyoid, sternothyroid, thyrohyoid)", "sternohyoid",
       "Sternohyoid: manubrium and medial clavicle. Omohyoid: superior border of the scapula near the suprascapular notch. Sternothyroid: back of the manubrium. Thyrohyoid: oblique line of the thyroid cartilage.",
       "Sternohyoid and omohyoid: body of the hyoid. Sternothyroid: oblique line of the thyroid cartilage. Thyrohyoid: body and greater horn of the hyoid.",
       "Ansa cervicalis (C1–C3); thyrohyoid by C1 fibres running with the hypoglossal n.",
       "Depress the hyoid and larynx after swallowing; steady the hyoid; thyrohyoid raises the larynx when the hyoid is fixed.",
       "<b>No graded test.</b> Palpate the thyroid cartilage rise with a dry swallow and fall back after it. " + C(),
       "Nothing separately graded."),
    ]),
    ],
)

SECTIONS = [TRUNK, BREATH, NECK]
