# -*- coding: utf-8 -*-
"""Head: mastication, facial expression, eye, tongue, palate, pharynx, larynx, middle ear."""
from common import M, C, X

def O(cmd, look):
    """A cranial-nerve style test: the command, then what normal looks like."""
    return "<b>Command:</b> %s <b>Normal:</b> %s %s" % (cmd, look, C())

HEAD = dict(
    id="head", nav="Head", title="Head — chewing, the face, the eye, and the throat",
    lede="""Almost nothing above the neck is graded 0–5 against resistance. The face is graded by
      what it can do — normal, weak, trace, absent — and the throat and eye by whether a movement
      happens and which way it deviates. The deviation is the finding, and each nerve has its own
      rule: the jaw and the tongue deviate <i>toward</i> the weak side, the uvula <i>away</i> from
      it. Every muscle of facial expression is on CN VII; every muscle of mastication is on
      CN V3.""",
    groups=[
    ("Mastication (CN V3)", [
     M("Masseter", "masseter",
       "Inferior border and medial surface of the zygomatic arch.",
       "Angle and lateral surface of the ramus of the mandible.",
       "Masseteric n. of the mandibular division of the trigeminal (CN V3).",
       "Elevates (closes) and protrudes the mandible; deep fibres retrude it.",
       O("clench the teeth.", "palpate both masseters over the ramus — they bulge equally. Resisted closing: push down on the chin as the patient bites up."),
       "<b>Temporalis</b> also closes the jaw; palpate both muscles and compare sides, not force."),
     M("Temporalis", "temporal",
       "Floor of the temporal fossa and the deep temporal fascia.",
       "Tip and medial surface of the coronoid process; anterior border of the ramus.",
       "Deep temporal nn. (CN V3).",
       "Elevates the mandible; posterior fibres retrude it.",
       O("clench the teeth.", "palpate above the zygomatic arch — both sides bulge equally."),
       "<b>Masseter</b> closes the jaw with a weak temporalis — palpate, do not judge by bite."),
     M("Medial pterygoid", "medpt",
       "Deep head: medial surface of the lateral pterygoid plate and the pyramidal process of the palatine bone. Superficial head: tuberosity of the maxilla.",
       "Medial surface of the ramus of the mandible, below the mandibular foramen.",
       "Nerve to medial pterygoid (CN V3).",
       "Elevates and protrudes the mandible; alternating sides produce the grinding (side-to-side) movement.",
       "<b>Not palpable externally.</b> Tested in resisted closing and side-to-side movement with the other closers. " + C(),
       "Masseter and temporalis carry the closing force."),
     M("Lateral pterygoid", "latpt",
       "Superior head: infratemporal surface of the greater wing of the sphenoid. Inferior head: lateral surface of the lateral pterygoid plate.",
       "Pterygoid fovea on the neck of the condyle; the TMJ articular disc and capsule.",
       "Nerve to lateral pterygoid (CN V3).",
       "Both sides: protrude the mandible and help open the mouth. One side: moves the jaw to the <i>opposite</i> side.",
       O("open the mouth slowly; then move the jaw side to side against your hand.", "the jaw opens in the midline. <b>The jaw deviates toward the weak side</b> on opening, because the intact lateral pterygoid pushes its condyle forward unopposed."),
       "<b>Suprahyoids and gravity</b> open the mouth without the pterygoids; a TMJ disc problem also deviates the jaw, with a click and without CN V3 signs."),
    ]),
    ("Facial expression (CN VII)", [
     M("Occipitofrontalis (frontal belly)", "facial",
       "Epicranial aponeurosis.",
       "Skin and subcutaneous tissue of the eyebrows and forehead.",
       "Temporal branch of the facial n. (CN VII); occipital belly by the posterior auricular branch.",
       "Raises the eyebrows and wrinkles the forehead.",
       O("raise your eyebrows.", "symmetrical forehead lines. <b>An upper motor neuron lesion spares the forehead</b> (it has bilateral cortical input); a lower motor neuron (Bell's) palsy does not."),
       "<b>Looking up</b> raises the brows a little without a real contraction."),
     M("Orbicularis oculi", "oculi",
       "Medial orbital margin, medial palpebral ligament, lacrimal bone.",
       "Skin around the orbital margin; superior and inferior tarsal plates.",
       "Temporal and zygomatic branches of the facial n. (CN VII).",
       "Closes the eyelids — the palpebral part gently (blinking), the orbital part tightly (squeezing).",
       O("close your eyes tight and don't let me open them.", "you cannot part the lids; lashes buried equally. With weakness the lashes show on the weak side, and on attempted closure the eye rolls up (Bell's phenomenon)."),
       "<b>Levator palpebrae relaxing</b> drops the lid without orbicularis — gentle closure is not the test; tight closure against your fingers is."),
     M("Corrugator supercilii and procerus", "facial",
       "Corrugator: medial end of the superciliary arch. Procerus: fascia over the nasal bone.",
       "Corrugator: skin above the middle of the eyebrow. Procerus: skin of the lower forehead between the brows.",
       "Temporal branch of the facial n. (CN VII) (procerus: temporal or buccal branch; texts differ).",
       "Draw the eyebrows together and down (frowning); wrinkle the skin over the nose.",
       O("frown.", "vertical lines between the brows (corrugator) and horizontal lines over the bridge of the nose (procerus), both sides."),
       "Squinting uses orbicularis oculi and looks similar."),
     M("Nasalis", "facial",
       "Maxilla, over the canine and incisor teeth.",
       "Nasal cartilages and the aponeurosis over the bridge of the nose.",
       "Buccal branch of the facial n. (CN VII).",
       "Flares (alar part) and compresses (transverse part) the nostrils.",
       O("flare your nostrils.", "both nostrils widen equally."),
       "A deep breath in through the nose flares the nostrils passively."),
     M("Orbicularis oris", "facial",
       "Medial maxilla and mandible; deep surface of the skin around the mouth; angle of the mouth.",
       "Mucous membrane of the lips.",
       "Buccal and marginal mandibular branches of the facial n. (CN VII).",
       "Closes and purses the lips.",
       O("puff out your cheeks and hold; then whistle.", "air does not escape when you press on each cheek. Weakness leaks air on the weak side."),
       "<b>Buccinator</b> holds the cheek taut too; the leak point at the lip corner is orbicularis oris."),
     M("Buccinator", "facial",
       "Mandible and alveolar processes of the maxilla and mandible (at the molars); pterygomandibular raphe.",
       "Angle of the mouth (modiolus), blending with orbicularis oris.",
       "Buccal branch of the facial n. (CN VII). (The buccal nerve of CN V3 is sensory only.)",
       "Presses the cheek against the molars, keeping food between the teeth; resists distension when blowing.",
       O("blow the cheeks out, then suck them in.", "cheeks hold taut; no food pocketing in the cheek after eating (a functional sign of weakness)."),
       "Orbicularis oris seals the lips; a cheek that balloons with the lips sealed is buccinator."),
     M("Zygomaticus major and minor, risorius, levator anguli oris", "facial",
       "Zygomatic bone (zygomaticus); parotid fascia and skin (risorius); canine fossa of the maxilla (levator anguli oris).",
       "Angle of the mouth (modiolus); zygomaticus minor to the upper lip.",
       "Zygomatic and buccal branches of the facial n. (CN VII).",
       "Draw the angle of the mouth up and out — the smile.",
       O("show me your teeth; smile.", "the mouth corners rise symmetrically. The flattened nasolabial fold on the weak side is visible at rest."),
       "A voluntary smile and an emotional smile use different cortical pathways; an asymmetry that appears only in one of them is a central finding, not a muscle one."),
     M("Levator labii superioris (and alaeque nasi)", "facial",
       "Infraorbital margin of the maxilla; frontal process of the maxilla (alaeque nasi).",
       "Skin of the upper lip; ala of the nose (alaeque nasi).",
       "Zygomatic and buccal branches of the facial n. (CN VII).",
       "Raises the upper lip; dilates the nostril (alaeque nasi).",
       O("sneer — raise your upper lip.", "the upper lip rises and the nostril widens on both sides."),
       "Zygomaticus minor raises the lip too."),
     M("Depressor anguli oris, depressor labii inferioris, mentalis", "facial",
       "Anterolateral base of the mandible (depressors); incisive fossa of the mandible (mentalis).",
       "Angle of the mouth; skin of the lower lip; skin of the chin (mentalis).",
       "Marginal mandibular branch of the facial n. (CN VII).",
       "Pull the corner of the mouth and the lower lip down; mentalis raises and protrudes the lower lip and wrinkles the chin (pouting).",
       O("pull the corners of your mouth down; then pout.", "symmetrical lip depression; the chin dimples with the pout."),
       "Platysma pulls the mouth down with the neck skin ridging."),
    ]),
    ("Eye — extraocular muscles and eyelid (CN III, IV, VI)", [
     M("Lateral rectus", "eom",
       "Common tendinous ring (lateral part).",
       "Sclera, lateral side, in front of the equator.",
       "Abducens n. (CN VI).",
       "Abducts the eye.",
       O("follow my finger out to the side.", "the eye reaches the lateral canthus. CN VI palsy: cannot abduct; horizontal double vision worse looking toward the weak side."),
       "The mnemonic <b>LR6 SO4, the rest 3</b> is the whole nerve map of this group."),
     M("Medial rectus", "eom",
       "Common tendinous ring.",
       "Sclera, medial side, in front of the equator.",
       "Oculomotor n. (CN III).",
       "Adducts the eye.",
       O("follow my finger in toward your nose.", "the eye reaches the medial canthus; both eyes converge on a near target."),
       "Convergence and conjugate gaze use different pathways — an eye that adducts in convergence but not in side gaze is an internuclear lesion, not a muscle one."),
     M("Superior rectus", "eom",
       "Common tendinous ring.",
       "Sclera, superior side, in front of the equator.",
       "Oculomotor n. (CN III).",
       "Elevates the eye, and adducts and intorts it.",
       O("look out to the side, then up.", "the eye rises. Tested looking outward because superior rectus is the pure elevator of the abducted eye."),
       "Inferior oblique elevates the adducted eye — test in abduction to separate them."),
     M("Inferior rectus", "eom",
       "Common tendinous ring.",
       "Sclera, inferior side, in front of the equator.",
       "Oculomotor n. (CN III).",
       "Depresses the eye, and adducts and extorts it.",
       O("look out to the side, then down.", "the eye falls. Tested looking outward because inferior rectus is the pure depressor of the abducted eye."),
       "Superior oblique depresses the adducted eye."),
     M("Superior oblique", "eom",
       "Body of the sphenoid, above and medial to the optic canal; the tendon runs through the trochlea.",
       "Sclera, posterosuperior lateral quadrant, deep to superior rectus.",
       "Trochlear n. (CN IV).",
       "Depresses the eye (most in adduction), intorts it, and abducts it.",
       O("look in toward your nose, then down.", "the eye falls. CN IV palsy: vertical double vision worst looking down and in — reading and going downstairs — with a head tilt away from the affected side."),
       "Inferior rectus depresses the eye in other positions — test in adduction."),
     M("Inferior oblique", "eom",
       "Anterior floor of the orbit (maxilla), lateral to the nasolacrimal canal.",
       "Sclera, posterolateral, deep to lateral rectus.",
       "Oculomotor n. (CN III).",
       "Elevates the eye (most in adduction), extorts it, and abducts it.",
       O("look in toward your nose, then up.", "the eye rises."),
       "Superior rectus elevates in other positions — test in adduction."),
     M("Levator palpebrae superioris", "lps",
       "Lesser wing of the sphenoid, above and in front of the optic canal.",
       "Superior tarsal plate and the skin of the upper eyelid.",
       "Oculomotor n. (CN III); its smooth-muscle part (superior tarsal muscle) is sympathetic.",
       "Raises the upper eyelid.",
       O("look up.", "the lid clears the upper iris. Complete ptosis with a down-and-out eye and a large pupil is CN III; mild ptosis with a small pupil is sympathetic (Horner's)."),
       "<b>Frontalis</b> lifts the brow and the lid with it — hold the brow down to test the levator alone."),
    ]),
    ("Tongue (CN XII, except palatoglossus)", [
     M("Genioglossus", "genioglossus",
       "Superior mental spine of the mandible.",
       "Dorsum of the tongue and the body of the hyoid.",
       "Hypoglossal n. (CN XII).",
       "Protrudes the tongue and depresses its centre.",
       O("stick your tongue straight out; push it into each cheek against my finger.", "the tongue protrudes in the midline. <b>It deviates toward the weak side</b> — the intact genioglossus pushes it across. Wasting and fasciculation mean a lower motor neuron lesion."),
       "Facial weakness distorts the mouth and makes a midline tongue look deviated — judge against the nose and chin, not the lips."),
     M("Hyoglossus, styloglossus and the intrinsic tongue muscles", "tongue",
       "Hyoglossus: body and greater horn of the hyoid. Styloglossus: styloid process. Intrinsic: within the tongue.",
       "Side and underside of the tongue.",
       "Hypoglossal n. (CN XII).",
       "Hyoglossus depresses and retracts; styloglossus retracts and curls the sides up; the intrinsics change shape (lengthen, shorten, curl, flatten).",
       O("pull your tongue back; curl it; move it quickly side to side.", "full, quick, symmetrical movement."),
       "Nothing separately graded."),
     M("Palatoglossus", "tongue",
       "Palatine aponeurosis of the soft palate.",
       "Side of the tongue.",
       "Vagus n. (CN X) through the pharyngeal plexus — the one tongue muscle not on CN XII.",
       "Raises the back of the tongue and narrows the opening from mouth to throat.",
       "<b>Tested with the soft palate</b>. " + C(),
       "Same as the palate."),
    ]),
    ("Soft palate, pharynx and larynx (CN IX, X; one on V3)", [
     M("Levator veli palatini, musculus uvulae, palatopharyngeus", "pharynx",
       "Temporal bone and the auditory tube cartilage (levator); posterior nasal spine (uvulae); hard palate and palatine aponeurosis (palatopharyngeus).",
       "Palatine aponeurosis; the uvula; the lateral wall of the pharynx.",
       "Vagus n. (CN X) through the pharyngeal plexus.",
       "Raise the soft palate to close off the nasopharynx in swallowing and speech; shorten the uvula; raise the pharynx.",
       O("open your mouth and say 'ah'.", "the palate rises symmetrically and the uvula stays midline. <b>The uvula deviates away from the weak side</b> — pulled toward the intact one. Nasal speech and fluid through the nose are the functional signs."),
       "A uvula that is simply asymmetric at rest is common; the finding is movement on phonation."),
     M("Tensor veli palatini", "tvp",
       "Scaphoid fossa of the sphenoid, spine of the sphenoid, cartilage of the auditory tube.",
       "Palatine aponeurosis (the tendon hooks round the pterygoid hamulus).",
       "Nerve to medial pterygoid (CN V3) — the one palate muscle not on CN X.",
       "Tenses the soft palate; opens the auditory tube in swallowing and yawning.",
       "<b>No separate bedside test.</b> Ear fullness that does not clear on swallowing is its functional sign. " + C(),
       "Nothing separately graded."),
     M("Pharyngeal constrictors (superior, middle, inferior) and salpingopharyngeus", "pharynx",
       "Pterygomandibular raphe and nearby bone (superior); hyoid (middle); thyroid and cricoid cartilages (inferior); auditory tube (salpingopharyngeus).",
       "Pharyngeal raphe and pharyngeal wall.",
       "Vagus n. (CN X) through the pharyngeal plexus.",
       "Constrict the pharynx in sequence to push the bolus down; the lowest fibres (cricopharyngeus) act as the upper oesophageal sphincter.",
       O("swallow; gag reflex if indicated.", "a single efficient swallow with no cough or wet voice after. The gag reflex tests CN IX (sensory) and CN X (motor)."),
       "<b>A present gag does not mean a safe swallow</b>, and an absent one is common in healthy people — the swallow is the test."),
     M("Stylopharyngeus", "pharynx",
       "Styloid process of the temporal bone.",
       "Posterior border of the thyroid cartilage and the pharyngeal wall.",
       "Glossopharyngeal n. (CN IX) — the only muscle it supplies.",
       "Elevates the pharynx and larynx and widens the pharynx in swallowing.",
       "<b>Tested with swallowing.</b> " + C(),
       "Nothing separately graded."),
     M("Intrinsic laryngeal muscles (cricothyroid, posterior and lateral cricoarytenoid, arytenoids, thyroarytenoid)", "larynx",
       "Cricoid, thyroid and arytenoid cartilages.",
       "Arytenoid and thyroid cartilages; vocal ligament.",
       "Vagus n. (CN X): cricothyroid by the external branch of the superior laryngeal n.; all the others by the recurrent laryngeal n.",
       "Open (posterior cricoarytenoid — the only abductor), close (lateral cricoarytenoid, arytenoids) and tension (cricothyroid, thyroarytenoid) the vocal folds.",
       O("say 'eee', glide the pitch from low to high, and cough.", "a clear voice with a full pitch range and a sharp cough. A breathy, weak voice and weak cough suggest recurrent laryngeal palsy; loss of the high range suggests the superior laryngeal nerve. Laryngoscopy is the definitive test."),
       "A hoarse voice is far more often laryngeal irritation than nerve palsy."),
    ]),
    ("Middle ear", [
     M("Stapedius and tensor tympani", "middleear",
       "Stapedius: pyramidal eminence of the posterior middle ear wall. Tensor tympani: cartilage of the auditory tube and the adjacent sphenoid.",
       "Stapedius: neck of the stapes. Tensor tympani: handle of the malleus.",
       "Stapedius: facial n. (CN VII). Tensor tympani: nerve to medial pterygoid (CN V3).",
       "Damp the vibration of the ossicles in response to loud sound.",
       "<b>History and audiometry:</b> hyperacusis — ordinary sounds uncomfortably loud on one side — in a facial palsy means the lesion is proximal to the nerve to stapedius. The acoustic reflex is measured by audiometry. " + C(),
       "Nothing separately graded."),
    ]),
    ],
)

SECTIONS = [HEAD]
