# -*- coding: utf-8 -*-
"""Lower limb: hip, thigh, leg, foot."""
from common import M, T, C, X

HIP = dict(
    id="hip", nav="Hip", title="Hip — flexors, gluteals, and the deep lateral rotators",
    lede="""Iliopsoas flexes, the gluteals extend and abduct, and six small muscles behind the hip
      rotate it laterally and hold the femoral head in the acetabulum. Most hip tests fail the
      same way: the pelvis and lumbar spine move instead of the femur. Stabilize the pelvis, and
      watch it — a hip test graded while the pelvis tilts is a trunk test.""",
    groups=[
    ("Hip flexors", [
     M("Iliopsoas — iliacus", "iliopsoas",
       "Iliac crest, iliac fossa, ala of the sacrum, anterior sacroiliac ligaments.",
       "Tendon of psoas major, lesser trochanter, and the femur just below it.",
       "Femoral n. (L2, L3).",
       "Flexes the hip; with psoas, the main hip flexor. The hip flexors are the ISNCSCI key muscle for L2.",
       T("sitting at the edge of the table, knees flexed over the edge, hands on the table.",
         "the pelvis — the patient's hands and your hand on the ipsilateral iliac crest.",
         "patient lifts the thigh off the table; resist at the distal anterior thigh toward extension.",
         "sidelying on the tested side, top leg supported, flex the hip with the knee bent."),
       "<b>Leaning back</b> — trunk extension tips the thigh up without hip flexion. <b>Sartorius</b> flexes with lateral rotation and abduction; <b>TFL</b> flexes with medial rotation and abduction. The thigh should rise straight."),
     M("Iliopsoas — psoas major", "psoas",
       "Sides of T12–L4 and the discs between them, and the transverse processes of L1–L4. Many dissection texts also include L5. " + X(),
       "Lesser trochanter of the femur.",
       "Anterior rami of L1–L4, with small branches from the femoral n.",
       "Flexes the hip; flexes the trunk on the thigh; laterally flexes the lumbar spine.",
       "<b>Tested with iliacus as iliopsoas.</b> Kendall's supine variant biases psoas: hip flexed, slightly abducted and laterally rotated, resisted toward extension and slight abduction at the anteromedial leg. " + C(),
       "Same as iliacus."),
     M("Psoas minor", "psoas",
       "Sides of the bodies of T12–L1 and the disc between them.",
       "Pectineal line and iliopectineal eminence.",
       "Anterior ramus of L1.",
       "Weakly flexes the lumbar spine and tilts the pelvis posteriorly.",
       "<b>No clinical test.</b> Absent in a large proportion of people. " + C(),
       "Nothing to fake."),
     M("Sartorius", "sartorius",
       "Anterior superior iliac spine and the notch just below it.",
       "Superior part of the medial surface of the tibia (pes anserinus).",
       "Femoral n. (L2, L3).",
       "Flexes, abducts and laterally rotates the hip; flexes the knee and medially rotates the tibia — the heel-to-opposite-shin position.",
       T("sitting, knees flexed over the edge.",
         "none needed beyond the resisting hands.",
         "patient slides the heel up the opposite shin (hip flexion, abduction, lateral rotation, knee flexion); resist with one hand at the lateral distal thigh (into adduction and extension) and the other at the medial ankle (into knee extension and hip medial rotation).",
         "supine, slide the heel up the opposite shin along the table."),
       "<b>Iliopsoas and rectus femoris</b> flex the hip straight without the rotation — the combined pattern is what makes it sartorius."),
    ]),
    ("Gluteals and tensor fasciae latae", [
     M("Gluteus maximus", "gmax",
       "Ilium posterior to the posterior gluteal line, dorsal sacrum and coccyx, sacrotuberous ligament.",
       "Most fibres into the iliotibial tract (to the lateral condyle of the tibia); deep distal fibres to the gluteal tuberosity.",
       "Inferior gluteal n. (L5, S1, S2).",
       "Extends the hip, most powerfully from flexion (rising from sitting, climbing); laterally rotates; steadies the thigh.",
       T("prone, knee flexed 90° — the flexed knee leaves the hamstrings too short to contribute.",
         "the pelvis over the posterior iliac crest.",
         "patient lifts the thigh off the table; resist at the distal posterior thigh toward flexion.",
         "sidelying on the tested side, extend the hip with the knee flexed."),
       "<b>Lumbar extension lifts the thigh by tilting the pelvis</b> — watch the pelvis, not the leg. With the knee straight the hamstrings extend the hip; abduction or lateral rotation recruits the posterior gluteus medius."),
     M("Gluteus medius", "gmed",
       "External surface of the ilium between the anterior and posterior gluteal lines.",
       "Lateral surface of the greater trochanter.",
       "Superior gluteal n. (L4, L5, S1).",
       "Abducts the hip and medially rotates it (anterior fibres); holds the pelvis level in single-leg stance.",
       T("sidelying on the untested side, bottom knee flexed for balance, test hip slightly extended and in neutral rotation, knee extended.",
         "the pelvis at the iliac crest, preventing it from rolling back.",
         "patient lifts the leg; resist at the distal lateral thigh just above the knee, down and slightly forward.",
         "supine, abduct the leg along the table."),
       "<b>TFL takes over when the hip drifts into flexion and medial rotation</b>. <b>Quadratus lumborum hikes the pelvis</b>, raising the leg without abduction. Rolling back lets the hip flexors abduct in lateral rotation. Trendelenburg sign is the weight-bearing form: the pelvis drops on the unsupported side."),
     M("Gluteus minimus", "gmin",
       "External surface of the ilium between the anterior and inferior gluteal lines.",
       "Anterior surface of the greater trochanter.",
       "Superior gluteal n. (L4, L5, S1).",
       "Abducts and medially rotates the hip; holds the pelvis level in single-leg stance.",
       "<b>Tested with gluteus medius.</b> Medial rotation is resisted in sitting (see the medial rotators under the deep six). " + C(),
       "Same as gluteus medius."),
     M("Tensor fasciae latae", "tfl",
       "Anterior superior iliac spine and the anterior iliac crest.",
       "Iliotibial tract, to the lateral condyle of the tibia (Gerdy's tubercle).",
       "Superior gluteal n. (L4, L5, S1).",
       "Abducts, medially rotates and flexes the hip; tenses the iliotibial tract, helping hold the knee extended.",
       T("supine, hip abducted, flexed and medially rotated, knee extended.",
         "the pelvis.",
         "resist at the anterolateral distal leg toward extension and adduction."),
       "<b>Rectus femoris and iliopsoas</b> produce more flexion than abduction; <b>gluteus medius</b> produces abduction without flexion."),
    ]),
    ("Deep lateral rotators (the deep six) — tested together", [
     M("Piriformis", "piriformis",
       "Anterior surface of the sacrum (S2–S4), margin of the greater sciatic notch, sacrotuberous ligament.",
       "Superior border of the greater trochanter.",
       "Nerve to piriformis, from the anterior rami of S1, S2.",
       "Laterally rotates the extended hip, abducts the flexed hip; holds the femoral head in the acetabulum.",
       T("sitting, knees flexed over the edge.",
         "the distal thigh on the table.",
         "patient rotates so the foot moves inward (hip lateral rotation); resist at the medial ankle outward with a counterforce at the lateral knee. Prone variant: knee flexed 90°.",
         "supine, roll the extended leg outward."),
       "<b>Knee extension and hip abduction</b> swing the foot inward without rotating the femur; lifting the pelvis or leaning shifts weight. The deep six share this test — it grades them as a group."),
     M("Superior gemellus", "gemelli",
       "Ischial spine.",
       "With the obturator internus tendon, medial surface of the greater trochanter.",
       "Nerve to obturator internus (L5, S1, S2).",
       "Laterally rotates the extended hip; steadies the femoral head.",
       "<b>Tested with the deep six</b> (see piriformis). " + C(),
       "Same as piriformis."),
     M("Obturator internus", "obturator",
       "Pelvic surface of the obturator membrane and the surrounding bone.",
       "Medial surface of the greater trochanter.",
       "Nerve to obturator internus (L5, S1, S2).",
       "Laterally rotates the extended hip; abducts the flexed hip; steadies the femoral head.",
       "<b>Tested with the deep six</b> (see piriformis). " + C(),
       "Same as piriformis."),
     M("Inferior gemellus", "gemelli",
       "Ischial tuberosity.",
       "With the obturator internus tendon, medial surface of the greater trochanter.",
       "Nerve to quadratus femoris (L4, L5, S1).",
       "Laterally rotates the extended hip; steadies the femoral head.",
       "<b>Tested with the deep six</b> (see piriformis). " + C(),
       "Same as piriformis."),
     M("Quadratus femoris", "gemelli",
       "Lateral border of the ischial tuberosity.",
       "Quadrate tubercle on the intertrochanteric crest.",
       "Nerve to quadratus femoris (L4, L5, S1).",
       "Laterally rotates the hip; steadies the femoral head.",
       "<b>Tested with the deep six</b> (see piriformis). " + C(),
       "Same as piriformis."),
     M("Obturator externus", "obturator",
       "Margins of the obturator foramen and the external surface of the obturator membrane.",
       "Trochanteric fossa of the femur.",
       "Obturator n. (L3, L4).",
       "Laterally rotates the hip; steadies the femoral head.",
       "<b>Tested with the deep six</b> (see piriformis). The one deep rotator on the obturator nerve. " + C(),
       "Same as piriformis."),
     M("Hip medial rotators (test)", "gmin",
       "Gluteus minimus, anterior gluteus medius and TFL — see their rows.",
       "See their rows.",
       "Superior gluteal n. (L4, L5, S1).",
       "Medially rotate the hip.",
       T("sitting, knees flexed over the edge.", "the distal thigh.",
         "patient rotates so the foot moves outward (hip medial rotation); resist at the lateral ankle inward with a counterforce at the medial knee."),
       "<b>Hip adduction and knee extension</b> swing the foot outward; the pelvis lifts on the tested side."),
    ]),
    ],
)

THIGH = dict(
    id="thigh", nav="Thigh", title="Thigh — quadriceps, hamstrings and adductors",
    lede="""Three compartments, three nerves: anterior on the femoral, medial on the obturator,
      posterior on the sciatic. The exceptions are the ones examiners ask about — pectineus
      (femoral, sometimes obturator too), the hamstring part of adductor magnus (tibial), and the
      short head of biceps femoris (common fibular). The two-joint muscles are the testing
      problem: rectus femoris and the hamstrings each act at the hip and the knee, and joint
      position is how you make them work or keep them out.""",
    groups=[
    ("Quadriceps (anterior compartment)", [
     M("Rectus femoris", "rf",
       "Anterior inferior iliac spine and the ilium just above the acetabulum.",
       "Base of the patella, and through the patellar ligament to the tibial tuberosity.",
       "Femoral n. (L2, L3, L4).",
       "Extends the knee; flexes the hip. The knee extensors are the ISNCSCI key muscle for L3.",
       T("sitting, knees flexed over the edge, a pad under the distal thigh, hands on the table.",
         "the distal thigh, without pressing on the quadriceps.",
         "patient extends the knee to just short of full extension; resist at the distal anterior leg toward flexion.",
         "sidelying on the tested side, top leg supported, extend the knee."),
       "<b>Locking the knee</b> holds with bone — test short of full extension. Leaning back puts rectus femoris on stretch and adds hip flexion; hip medial rotation lets gravity help in sidelying."),
     M("Vastus lateralis", "vl",
       "Greater trochanter and the lateral lip of the linea aspera.",
       "Patella via the quadriceps tendon, lateral patellar retinaculum, tibial tuberosity via the patellar ligament.",
       "Femoral n. (L2, L3, L4).",
       "Extends the knee.",
       "<b>Tested with the quadriceps</b> (see rectus femoris). " + C(),
       "Same as rectus femoris."),
     M("Vastus medialis", "antthigh",
       "Intertrochanteric line and the medial lip of the linea aspera.",
       "Patella via the quadriceps tendon, medial patellar retinaculum, tibial tuberosity via the patellar ligament.",
       "Femoral n. (L2, L3, L4).",
       "Extends the knee; its distal oblique fibres pull the patella medially.",
       "<b>Tested with the quadriceps</b> (see rectus femoris). Whether its oblique fibres can be selectively trained or tested is argued in the literature. " + X(),
       "Same as rectus femoris."),
     M("Vastus intermedius", "antthigh",
       "Anterior and lateral surfaces of the femoral shaft.",
       "Patella via the quadriceps tendon, tibial tuberosity via the patellar ligament.",
       "Femoral n. (L2, L3, L4).",
       "Extends the knee.",
       "<b>Tested with the quadriceps</b> (see rectus femoris). " + C(),
       "Same as rectus femoris."),
     M("Articularis genus", "antthigh",
       "Anterior distal femur.",
       "Synovial membrane of the suprapatellar bursa.",
       "Femoral n. (L3, L4).",
       "Pulls the suprapatellar bursa up during knee extension so it is not pinched.",
       "<b>No clinical test.</b> " + C(),
       "Nothing to fake."),
    ]),
    ("Hamstrings (posterior compartment)", [
     M("Semitendinosus", "semiten",
       "Ischial tuberosity.",
       "Superior part of the medial surface of the tibia (pes anserinus).",
       "Tibial division of the sciatic n. (L5, S1, S2).",
       "Extends the hip; flexes the knee and medially rotates the flexed knee.",
       T("prone, knee flexed about 45°, leg medially rotated (toes in).",
         "the thigh on the table.",
         "patient flexes the knee; resist at the posterior distal leg toward extension.",
         "sidelying on the tested side, flex the knee along the table."),
       "<b>Hip flexion</b> — the buttock rises as the knee bends, which lets the pelvis help. <b>Gastrocnemius</b> flexes the knee if the ankle plantarflexes; <b>sartorius and gracilis</b> flex with hip rotation."),
     M("Semimembranosus", "postthigh",
       "Ischial tuberosity.",
       "Posterior medial condyle of the tibia; a reflected slip forms the oblique popliteal ligament.",
       "Tibial division of the sciatic n. (L5, S1, S2).",
       "Extends the hip; flexes the knee and medially rotates the flexed knee.",
       "<b>Tested with semitendinosus</b> as the medial hamstrings. " + C(),
       "Same as semitendinosus."),
     M("Biceps femoris — long head", "hamstring",
       "Ischial tuberosity.",
       "Lateral side of the head of the fibula.",
       "Tibial division of the sciatic n. (L5, S1, S2).",
       "Extends the hip; flexes the knee and laterally rotates the flexed knee.",
       T("prone, knee flexed about 45°, leg laterally rotated (toes out).",
         "the thigh on the table.",
         "patient flexes the knee; resist at the posterior distal leg toward extension.",
         "sidelying, flex the knee along the table."),
       "<b>Hip flexion and gastrocnemius</b>, as for the medial hamstrings. Hip lateral rotation turns the leg without the knee rotating."),
     M("Biceps femoris — short head", "hamstring",
       "Linea aspera and the lateral supracondylar line of the femur.",
       "Lateral side of the head of the fibula.",
       "Common fibular division of the sciatic n. (L5, S1, S2).",
       "Flexes the knee and laterally rotates the flexed knee; does not cross the hip.",
       "<b>Tested with the long head</b> as the lateral hamstring. The only hamstring on the fibular division — the one that survives a tibial-division injury. " + C(),
       "Same as the long head."),
    ]),
    ("Adductors (medial compartment)", [
     M("Adductor longus", "medthigh",
       "Body of the pubis just below the pubic crest.",
       "Middle third of the linea aspera.",
       "Obturator n., anterior branch (L2, L3, L4).",
       "Adducts the hip; assists flexion.",
       T("sidelying on the tested side, top leg held by you in about 25° of abduction.",
         "the top leg you are holding.",
         "patient lifts the bottom leg up to the top one; resist at the distal medial thigh downward.",
         "supine, adduct the leg along the table from an abducted start."),
       "<b>Rolling forward</b> lets the hip flexors lift the leg; <b>rolling back</b> lets the hamstrings. Lateral pelvic tilt raises the leg without adduction."),
     M("Adductor brevis", "medthigh",
       "Body and inferior ramus of the pubis.",
       "Pectineal line and the proximal linea aspera.",
       "Obturator n. (L2, L3, L4).",
       "Adducts the hip; assists flexion.",
       "<b>Tested with the adductor group</b> (see adductor longus). " + C(),
       "Same as adductor longus."),
     M("Adductor magnus", "addmag",
       "Adductor part: inferior pubic ramus and ischial ramus. Hamstring part: ischial tuberosity.",
       "Adductor part: gluteal tuberosity, linea aspera, medial supracondylar line. Hamstring part: adductor tubercle of the femur.",
       "Adductor part: obturator n. (L2, L3, L4). Hamstring part: tibial division of the sciatic n. (L4).",
       "Adducts the hip; the adductor part flexes, the hamstring part extends.",
       "<b>Tested with the adductor group</b> (see adductor longus). " + C(),
       "Same as adductor longus. Its dual nerve supply is why an obturator lesion does not abolish adduction."),
     M("Pectineus", "medthigh",
       "Superior ramus of the pubis (pecten pubis).",
       "Pectineal line of the femur, just below the lesser trochanter.",
       "Femoral n. (L2, L3); in some people also a branch of the obturator n. " + X(),
       "Adducts and flexes the hip.",
       "<b>Tested with the adductor group</b>, or with the hip flexors. " + C(),
       "Same as adductor longus."),
     M("Gracilis", "gracilis",
       "Body and inferior ramus of the pubis.",
       "Superior part of the medial surface of the tibia (pes anserinus).",
       "Obturator n. (L2, L3).",
       "Adducts the hip; flexes the knee and medially rotates the flexed knee.",
       "<b>Tested with the adductor group</b> with the knee extended. " + C(),
       "Same as adductor longus."),
    ]),
    ],
)

LEG = dict(
    id="leg", nav="Leg &amp; ankle", title="Leg — the anterior, lateral and posterior compartments",
    lede="""Anterior compartment (deep fibular nerve): dorsiflexors and long toe extensors.
      Lateral compartment (superficial fibular nerve): evertors. Posterior compartment (tibial
      nerve): plantarflexors, the invertor tibialis posterior, and the long toe flexors. The
      ankle is where manual resistance is least trustworthy — the plantarflexors are too strong
      for an examiner's arm, which is why they are tested standing.""",
    groups=[
    ("Anterior compartment", [
     M("Tibialis anterior", "ta",
       "Lateral condyle and superior half of the lateral tibia, interosseous membrane.",
       "Medial and inferior surfaces of the medial cuneiform and the base of the 1st metatarsal.",
       "Deep fibular n. (L4, L5).",
       "Dorsiflexes and inverts the foot. The ankle dorsiflexors are the ISNCSCI key muscle for L4.",
       T("sitting, knee flexed over the edge, heel resting on your thigh.",
         "the distal leg.",
         "patient dorsiflexes and inverts with the toes relaxed; resist at the dorsomedial forefoot toward plantarflexion and eversion.",
         "sidelying, dorsiflex along the table."),
       "<b>The long toe extensors dorsiflex the ankle</b> — if the toes extend first, EHL and EDL are doing it. Knee flexion in sitting with the foot on the floor is not a test."),
     M("Extensor hallucis longus", "antcomp",
       "Middle part of the anterior fibula and the interosseous membrane.",
       "Dorsal base of the distal phalanx of the great toe.",
       "Deep fibular n. (L5, S1).",
       "Extends the great toe; dorsiflexes the ankle. The long toe extensors are the ISNCSCI key muscle for L5.",
       T("sitting or supine, ankle neutral.", "the metatarsals.",
         "patient extends the great toe; resist at the dorsum of the distal phalanx (IP) and the proximal phalanx (MTP)."),
       "<b>Extensor hallucis brevis</b> extends the MTP only — the IP straightening is EHL. Ankle plantarflexion tightens EHL and extends the toe passively (tenodesis)."),
     M("Extensor digitorum longus", "antcomp",
       "Lateral condyle of the tibia, superior three-quarters of the anterior fibula, interosseous membrane.",
       "Middle and distal phalanges of the lateral four toes.",
       "Deep fibular n. (L5, S1).",
       "Extends toes 2–5; dorsiflexes the ankle.",
       T("sitting or supine, ankle neutral.", "the metatarsals.",
         "patient extends toes 2–5; resist at the dorsum of the proximal phalanges."),
       "<b>Extensor digitorum brevis</b> extends the MTP joints of toes 2–4 — palpate its belly in front of the lateral malleolus to tell them apart."),
     M("Fibularis tertius", "antcomp",
       "Inferior third of the anterior fibula and the interosseous membrane.",
       "Dorsum of the base of the 5th metatarsal.",
       "Deep fibular n. (L5, S1).",
       "Dorsiflexes and everts the foot.",
       T("sitting, ankle neutral.", "the distal leg.",
         "patient dorsiflexes and everts; resist at the dorsolateral forefoot toward plantarflexion and inversion."),
       "<b>Extensor digitorum longus</b> dorsiflexes and everts too; toes extending first means EDL. Absent in some people."),
    ]),
    ("Lateral compartment", [
     M("Fibularis (peroneus) longus", "fl",
       "Head and superior two-thirds of the lateral fibula.",
       "Plantar base of the 1st metatarsal and the medial cuneiform (the tendon crosses under the foot).",
       "Superficial fibular n. (L5, S1, S2).",
       "Everts the foot and weakly plantarflexes; plantarflexes the 1st ray; supports the transverse arch.",
       T("sidelying on the untested side, or sitting.", "the distal leg.",
         "patient everts with slight plantarflexion; resist at the lateral border of the foot toward inversion. Pressing up under the 1st metatarsal head biases longus.",
         "supine, evert along the table."),
       "<b>Extensor digitorum longus and fibularis tertius</b> evert in dorsiflexion — eversion with the toes extending is not fibularis. Hip medial rotation rolls the foot outward."),
     M("Fibularis (peroneus) brevis", "fb",
       "Inferior two-thirds of the lateral fibula.",
       "Dorsal surface of the tuberosity on the lateral base of the 5th metatarsal.",
       "Superficial fibular n. (L5, S1, S2).",
       "Everts the foot and weakly plantarflexes.",
       "<b>Tested with fibularis longus.</b> " + C(),
       "Same as fibularis longus."),
    ]),
    ("Posterior compartment — superficial", [
     M("Gastrocnemius", "calf",
       "Lateral head: lateral surface of the lateral femoral condyle. Medial head: posterior nonarticular aspect of the medial femoral condyle.",
       "Posterior calcaneus via the calcaneal (Achilles) tendon.",
       "Tibial n. (S1, S2).",
       "Plantarflexes the ankle with the knee extended; flexes the knee. The ankle plantarflexors are the ISNCSCI key muscle for S1.",
       T("standing on the test leg, knee extended, fingertips on a wall for balance only.",
         "none — body weight is the resistance.",
         "patient rises onto the ball of the foot through full range, repeatedly. Hislop's convention: 25 full single-leg heel raises is grade 5; normative studies disagree on the count. " + X(),
         "prone or sidelying, plantarflex through range without weight."),
       "<b>Manual resistance over-grades</b> — an examiner's arm cannot break even a weakened plantarflexor, so a hand-resisted 'grade 5' is not a finding. Leaning forward, bouncing the knee, and partial range inflate the count."),
     M("Soleus", "calf",
       "Posterior head and upper quarter of the fibula, soleal line and medial border of the tibia.",
       "Posterior calcaneus via the calcaneal tendon.",
       "Tibial n. (S1, S2).",
       "Plantarflexes the ankle regardless of knee position; steadies the leg over the foot in standing.",
       T("standing on the test leg with the knee slightly flexed — flexion slackens gastrocnemius.",
         "none — body weight is the resistance.",
         "patient rises onto the ball of the foot through full range, keeping the knee bent.",
         "prone with the knee flexed 90°, plantarflex."),
       "<b>Knee straightening during the raise</b> hands the work back to gastrocnemius. Tibialis posterior, the fibulares and the toe flexors plantarflex too — watch for inversion, eversion or toe clawing."),
     M("Plantaris", "calf",
       "Inferior end of the lateral supracondylar line of the femur and the oblique popliteal ligament.",
       "Posterior calcaneus, with or beside the calcaneal tendon.",
       "Tibial n. (S1, S2).",
       "Weakly assists gastrocnemius.",
       "<b>No clinical test.</b> Absent in some people. " + C(),
       "Nothing to fake."),
    ]),
    ("Posterior compartment — deep", [
     M("Popliteus", "popliteus",
       "Lateral femoral condyle and the lateral meniscus.",
       "Posterior tibia above the soleal line.",
       "Tibial n. (L4, L5, S1).",
       "Unlocks the extended knee — laterally rotates the femur on the fixed tibia, or medially rotates the tibia on the free femur; weakly flexes the knee.",
       T("sitting, knee flexed 90°.", "the distal thigh.",
         "patient rotates the tibia so the toes turn inward; resist at the distal leg toward lateral rotation."),
       "<b>Medial hamstrings</b> medially rotate the tibia; foot inversion looks like tibial rotation — watch the tibial tuberosity, not the toes."),
     M("Tibialis posterior", "tp",
       "Interosseous membrane, posterior tibia below the soleal line, posterior fibula.",
       "Tuberosity of the navicular, the cuneiforms, cuboid, and bases of the 2nd–4th metatarsals.",
       "Tibial n. (L4, L5).",
       "Inverts and plantarflexes the foot; supports the medial longitudinal arch.",
       T("sidelying on the tested side, or sitting, ankle slightly plantarflexed, toes relaxed.",
         "the distal leg.",
         "patient inverts; resist at the medial border of the forefoot toward eversion and dorsiflexion.",
         "supine, invert along the table."),
       "<b>The long toe flexors invert</b> — toes curling means FHL and FDL. <b>Tibialis anterior</b> inverts in dorsiflexion. Single-leg heel raise with the heel failing to swing into inversion is the weight-bearing sign."),
     M("Flexor digitorum longus", "postcomp",
       "Posterior tibia below the soleal line, with an aponeurosis to the fibula.",
       "Bases of the distal phalanges of the lateral four toes.",
       "Tibial n. — S2–S3 in some anatomy texts, L5–S2 in most rehabilitation texts. " + X(),
       "Flexes toes 2–5; plantarflexes; supports the longitudinal arch.",
       T("sitting or supine, ankle neutral.", "the middle phalanges.",
         "patient curls the tips of toes 2–5; resist at the plantar surface of the distal phalanges."),
       "<b>Ankle dorsiflexion flexes the toes passively</b> (tenodesis). Flexor digitorum brevis flexes the PIP only — DIP flexion is FDL."),
     M("Flexor hallucis longus", "postcomp",
       "Inferior two-thirds of the posterior fibula and the interosseous membrane.",
       "Base of the distal phalanx of the great toe.",
       "Tibial n. — S2–S3 in some anatomy texts, L5–S2 in most rehabilitation texts. " + X(),
       "Flexes the great toe; plantarflexes; supports the medial arch; the final push of toe-off.",
       T("sitting or supine, ankle neutral.", "the proximal phalanx of the great toe.",
         "patient flexes the IP joint; resist at the plantar distal phalanx."),
       "<b>Tenodesis from ankle dorsiflexion</b>, and flexor hallucis brevis at the MTP — IP flexion is FHL."),
    ]),
    ],
)

FOOT = dict(
    id="foot", nav="Foot", title="Intrinsic foot muscles — two on the dorsum, four plantar layers",
    lede="""The dorsum has two muscles on the deep fibular nerve; the sole has four layers on the
      medial and lateral plantar nerves, which divide the foot the way median and ulnar divide the
      hand. Most plantar intrinsics cannot be graded against resistance — many people cannot move
      the toes individually at all — so the test is often observation and palpation, and a row
      says so rather than inventing a grade. Root levels for the plantar intrinsics differ by one
      or two segments between standard texts; read them as approximate.""",
    groups=[
    ("Dorsum", [
     M("Extensor digitorum brevis", "footm",
       "Superolateral calcaneus and the inferior extensor retinaculum.",
       "Long extensor tendons of toes 2–4.",
       "Deep fibular n. (L5, S1).",
       "Extends toes 2–4 at the MTP and IP joints.",
       T("sitting or supine, ankle neutral.", "the metatarsals.",
         "patient extends the toes; resist at the dorsum of the proximal phalanges. Palpate the belly just in front of the lateral malleolus."),
       "<b>Extensor digitorum longus</b> extends the same toes; the palpable belly on the dorsum is the evidence EDB is working, and its wasting is an early deep fibular or L5 sign."),
     M("Extensor hallucis brevis", "footm",
       "Superolateral calcaneus and the inferior extensor retinaculum.",
       "Dorsal base of the proximal phalanx of the great toe.",
       "Deep fibular n. (L5, S1).",
       "Extends the MTP joint of the great toe.",
       T("sitting or supine, ankle neutral.", "the 1st metatarsal.",
         "patient extends the great toe MTP with the IP relaxed; resist at the dorsum of the proximal phalanx."),
       "<b>EHL</b> — an IP that straightens as well means the long extensor."),
    ]),
    ("Plantar layer 1", [
     M("Abductor hallucis", "footm",
       "Medial tubercle of the calcaneal tuberosity, flexor retinaculum, plantar aponeurosis.",
       "Medial base of the proximal phalanx of the great toe.",
       "Medial plantar n. (S1–S3; texts differ). " + X(),
       "Abducts and flexes the great toe MTP; supports the medial arch.",
       "<b>Observe and palpate:</b> patient spreads the great toe away from the second; palpate the belly along the medial foot. Many people cannot do this voluntarily. " + C(),
       "<b>Great toe flexion</b> by FHB and FHL looks like movement; lack of voluntary control is common and not a finding on its own."),
     M("Flexor digitorum brevis", "footm",
       "Medial tubercle of the calcaneal tuberosity and the plantar aponeurosis.",
       "Both sides of the middle phalanges of toes 2–5.",
       "Medial plantar n. (S1–S3; texts differ). " + X(),
       "Flexes the PIP joints of toes 2–5.",
       T("sitting or supine, ankle neutral.", "the proximal phalanges.",
         "patient flexes the toes at the PIP joints; resist at the plantar middle phalanges."),
       "<b>FDL</b> — DIP flexion means the long flexor is doing it."),
     M("Abductor digiti minimi (foot)", "footm",
       "Medial and lateral tubercles of the calcaneal tuberosity, plantar aponeurosis.",
       "Lateral base of the proximal phalanx of the 5th toe, often with a slip to the tuberosity of the 5th metatarsal.",
       "Lateral plantar n. (S1–S3; texts differ). " + X(),
       "Abducts and flexes the 5th toe.",
       "<b>Observe and palpate</b> along the lateral border of the sole. " + C(),
       "Rarely voluntary in isolation; absence of movement is not a finding on its own."),
    ]),
    ("Plantar layer 2", [
     M("Quadratus plantae", "footm",
       "Medial surface and lateral margin of the plantar calcaneus.",
       "Posterolateral margin of the FDL tendon.",
       "Lateral plantar n. (S1–S3; texts differ). " + X(),
       "Straightens the oblique pull of FDL along the axis of the foot; assists toe flexion.",
       "<b>No isolated test.</b> " + C(),
       "Nothing to fake."),
     M("Lumbricals (foot), 1–4", "footm",
       "Tendons of flexor digitorum longus.",
       "Medial sides of the extensor expansions of toes 2–5.",
       "1st: medial plantar n. 2nd–4th: lateral plantar n. (S1–S3; texts differ). " + X(),
       "Flex the MTP joints and extend the IP joints of toes 2–5.",
       T("sitting or supine, ankle neutral.", "the metatarsals.",
         "patient flexes the MTP joints while keeping the toes straight; resist at the plantar proximal phalanges."),
       "<b>FDL and FDB curl the toes</b> — IP flexion means the long and short flexors, not the lumbricals. Weak lumbricals with strong long flexors produce claw toes."),
    ]),
    ("Plantar layer 3", [
     M("Flexor hallucis brevis", "footm",
       "Plantar surfaces of the cuboid and lateral cuneiform.",
       "Both sides of the base of the proximal phalanx of the great toe, through the two sesamoids.",
       "Medial plantar n. (S1–S3; texts differ). " + X(),
       "Flexes the MTP joint of the great toe.",
       T("sitting or supine, ankle neutral.", "the 1st metatarsal.",
         "patient flexes the great toe MTP with the IP straight; resist at the plantar proximal phalanx."),
       "<b>FHL</b> — IP flexion means the long flexor."),
     M("Adductor hallucis", "footm",
       "Oblique head: bases of the 2nd–4th metatarsals. Transverse head: plantar ligaments of the MTP joints.",
       "Lateral base of the proximal phalanx of the great toe (via the lateral sesamoid).",
       "Deep branch of the lateral plantar n. (S2, S3). " + X(),
       "Adducts the great toe; supports the transverse arch.",
       "<b>Observe only</b> — few people can adduct the great toe voluntarily. " + C(),
       "Nothing reliable to grade."),
     M("Flexor digiti minimi brevis (foot)", "footm",
       "Base of the 5th metatarsal.",
       "Base of the proximal phalanx of the 5th toe.",
       "Superficial branch of the lateral plantar n. (S2, S3). " + X(),
       "Flexes the MTP joint of the 5th toe.",
       "<b>Tested with the toe flexors</b> — flex the 5th MTP with the IP straight. " + C(),
       "Long and short toe flexors."),
    ]),
    ("Plantar layer 4", [
     M("Plantar interossei (foot), 1–3", "footm",
       "Bases and medial sides of the 3rd–5th metatarsals.",
       "Medial sides of the bases of the proximal phalanges of toes 3–5.",
       "Lateral plantar n. (S2, S3). " + X(),
       "Adduct toes 3–5 toward the axis through the 2nd toe (PAD); flex the MTP joints.",
       "<b>Observe only:</b> patient squeezes the toes together. " + C(),
       "Toe flexion brings the toes together."),
     M("Dorsal interossei (foot), 1–4", "footm",
       "Adjacent sides of the 1st–5th metatarsals.",
       "1st: medial side of the proximal phalanx of the 2nd toe. 2nd–4th: lateral sides of toes 2–4.",
       "Lateral plantar n. (S2, S3). " + X(),
       "Abduct toes 2–4 from the axis through the 2nd toe (DAB); flex the MTP joints.",
       "<b>Observe only:</b> patient spreads the toes. " + C(),
       "Toe extension spreads the toes without the interossei."),
    ]),
    ],
)

SECTIONS = [HIP, THIGH, LEG, FOOT]
