# -*- coding: utf-8 -*-
"""The muscles that are talked about together, and why.

Three tables: named groups and force couples; every joint movement with its prime movers,
assistants and antagonists; and every motor nerve with what its loss looks like. Rows are
(name, col2, col3, last) — the last column is the finding, as in every guide.
"""
from common import C, X

GROUPS = dict(
    id="together", nav="Together", title="Muscles that work together — named groups and force couples",
    note="the relationship is the answer",
    lede="""A muscle is rarely asked about alone. Examiners and clinicians talk in groups — the
      rotator cuff, the pes anserinus, the deep six — because the group shares an attachment, a
      nerve, a compartment, or a job, and that shared thing is what the question is really about.
      A <b>force couple</b> is two or more muscles pulling in different directions that together
      produce one rotation; lose one member and the rotation fails in a characteristic way, which
      is why the last column here is what the failure looks like.""",
    cols=("Members", "What ties them together", "What it looks like when it fails"),
    blocks=[
    ("Shoulder girdle and shoulder", [
     ("Scapular upward rotation force couple",
      "Upper trapezius, lower trapezius, serratus anterior.",
      "Three lines of pull on the scapula — upper trapezius up and in at the acromion, lower trapezius down and in at the root of the spine, serratus anterior forward and out at the inferior angle — add up to one rotation that turns the glenoid upward as the arm rises. See the figure above.",
      "<b>Arm elevation stops short or the scapula wings.</b> Serratus loss: the medial border and inferior angle lift off the ribs (medial winging), worst pushing against a wall. Trapezius loss: the shoulder droops and the scapula slides laterally with the inferior angle rotated out (lateral winging), worst in abduction."),
     ("Scapular downward rotators",
      "Levator scapulae, rhomboid major and minor, pectoralis minor.",
      "The opposite rotation: glenoid turned down, inferior angle toward the spine. They lower the raised arm under control and hold the scapula when the arm pulls down or back.",
      "<b>Dominance, not weakness, is the usual finding</b>: a resting scapula downwardly rotated, with the inferior angle closer to the spine than the superior angle. " + C()),
     ("Scapular retractors",
      "Middle trapezius, rhomboids, (lower trapezius).",
      "Draw the scapula toward the spine. Trapezius retracts with upward rotation, rhomboids with downward rotation — the rotation is how you tell them apart.",
      "<b>A protracted resting scapula</b> and a posterior deltoid that lifts the arm in prone without the medial border moving in."),
     ("Rotator cuff (SITS)",
      "Supraspinatus, infraspinatus, teres minor, subscapularis.",
      "Four tendons blending into the capsule around the humeral head: three onto the greater tubercle (superior, middle, inferior facets, in the order S-I-T), one onto the lesser tubercle. Together they compress the head into the shallow glenoid.",
      "<b>The head rides up.</b> With the cuff unable to hold it down, deltoid's pull translates the head superiorly instead of rotating it: a shrug to lift the arm, painful arc, and a drop-arm when the arm cannot be lowered slowly from 90°."),
     ("Deltoid–rotator cuff force couple",
      "Deltoid (upward shear) with infraspinatus, teres minor and subscapularis (downward and compressive pull).",
      "Deltoid alone would pull the humerus up into the acromion. The lower cuff tendons pull the head down and in at the same time, so the sum is rotation about a fixed centre.",
      "<b>Superior migration of the head</b> on elevation, shrug substitution, and impingement-like pain — the mechanism behind large cuff tears."),
     ("Lady between two majors",
      "Latissimus dorsi (floor), pectoralis major (lateral lip), teres major (medial lip) of the intertubercular sulcus.",
      "All three insert around the bicipital groove and all three adduct and medially rotate the humerus. Latissimus lies between the two 'majors'.",
      "<b>Weak adduction and medial rotation</b> needs all three to go — they cover for each other, which is why an isolated nerve lesion (thoracodorsal, pectoral, lower subscapular) shows only a partial loss."),
     ("Anterior and posterior axillary folds",
      "Pectoralis major (anterior fold); latissimus dorsi and teres major (posterior fold).",
      "The two walls of the armpit you can grip. They are the palpable landmarks for these muscles and the borders of the axilla.",
      "<b>A flat or absent fold</b> — pectoralis major absence (Poland syndrome) or latissimus wasting — is visible before it is tested."),
    ]),
    ("Elbow, forearm and hand", [
     ("Elbow flexor trio",
      "Biceps brachii, brachialis, brachioradialis.",
      "All flex the elbow; forearm rotation picks which does most. Supinated favours biceps, mid-position favours brachioradialis, and brachialis works in all three.",
      "<b>Nerve localization</b>: biceps and brachialis on the musculocutaneous, brachioradialis on the radial. Weak flexion supinated with brachioradialis intact is musculocutaneous; the reverse is radial."),
     ("Forearm rotators",
      "Supinators: supinator, biceps. Pronators: pronator teres, pronator quadratus.",
      "Opposing pairs acting on the radius. Biceps adds power to supination with the elbow flexed; pronator quadratus is the one that works regardless of elbow position.",
      "<b>Supination strength drops with the elbow extended</b> in a biceps rupture (the supinator is left alone); both pronators are on the median nerve, so a median lesion above the elbow leaves only brachioradialis, which can bring a supinated forearm back to neutral and no further."),
     ("Common flexor origin (medial epicondyle)",
      "Pronator teres, flexor carpi radialis, palmaris longus, flexor carpi ulnaris, flexor digitorum superficialis.",
      "Share one tendon origin on the medial epicondyle.",
      "<b>Medial epicondyle pain on resisted wrist flexion and pronation</b> — the pattern of medial epicondylalgia. " + C()),
     ("Common extensor origin (lateral epicondyle)",
      "Extensor carpi radialis brevis, extensor digitorum, extensor digiti minimi, extensor carpi ulnaris (and supinator, anconeus nearby).",
      "Share one tendon origin on the lateral epicondyle; ECRB's part is deepest.",
      "<b>Lateral epicondyle pain on resisted wrist or middle finger extension, and on gripping</b> — the pattern of lateral epicondylalgia. " + C()),
     ("Grip synergy — finger flexors with wrist extensors",
      "FDS and FDP (grip) with ECRB, ECRL and ECU (wrist hold).",
      "The finger flexors also flex the wrist; the wrist extensors must contract to stop them, holding the wrist in slight extension where the flexors are at a strong length.",
      "<b>Grip is weak and painful when the wrist extensors are</b> — and a flexed wrist makes any grip weaker, which is why wrist position changes a grip dynamometer reading."),
     ("Tenodesis",
      "Long finger flexors and extensors, with active wrist extension.",
      "Extending the wrist stretches the finger flexors, which curls the fingers; flexing the wrist opens them. No finger muscle has to contract.",
      "<b>The functional grip of C6 tetraplegia</b>: active wrist extension closes the hand. The same mechanism fakes finger flexion on a manual muscle test — keep the wrist still."),
     ("Anatomical snuffbox",
      "Abductor pollicis longus and extensor pollicis brevis (radial border); extensor pollicis longus (ulnar border).",
      "The hollow between their tendons when the thumb extends; the scaphoid is its floor and the radial artery crosses it.",
      "<b>Snuffbox tenderness after a fall</b> is the scaphoid screen; pain on the APL and EPB tendons with ulnar deviation of the fist over the thumb is the first dorsal compartment (Finkelstein). " + C()),
     ("Thenar eminence",
      "Abductor pollicis brevis, flexor pollicis brevis, opponens pollicis (with adductor pollicis deep to them).",
      "The three on the recurrent branch of the median nerve — the 'OAF' of LOAF. Adductor pollicis is on the ulnar nerve, which is why thumb function splits between two nerves.",
      "<b>Thenar wasting and weak palmar abduction</b> = median at the wrist. <b>Froment's sign</b> (IP flexion to pinch) = ulnar loss of adductor pollicis."),
     ("Hypothenar eminence",
      "Abductor digiti minimi, flexor digiti minimi brevis, opponens digiti minimi (palmaris brevis in the skin).",
      "All on the deep (and palmaris brevis the superficial) branch of the ulnar nerve.",
      "<b>Hypothenar wasting</b> = ulnar at or above the wrist; a lesion in the deep branch alone spares hypothenar sensation."),
     ("Intrinsic-plus: lumbricals and interossei",
      "Lumbricals 1–4, dorsal interossei 1–4, palmar interossei 1–3.",
      "Flex the MCP joints while extending the IP joints — the opposite of what the long flexors and extensor digitorum do at those joints. PAD and DAB about the middle finger.",
      "<b>The claw hand</b>: MCP hyperextended and IPs flexed. Worse in the ring and little fingers with an ulnar lesion at the wrist, because FDP to those fingers is intact and pulls harder (the ulnar paradox)."),
    ]),
    ("Hip, knee, ankle and foot", [
     ("Hip flexors",
      "Iliopsoas (prime), rectus femoris, sartorius, tensor fasciae latae, pectineus, adductor longus and brevis.",
      "Iliopsoas is the only one that flexes the hip past 90° effectively; the others help from lower angles and add rotation or adduction.",
      "<b>Weak hip flexion in sitting</b> is iliopsoas; if the thigh rolls out it is sartorius substituting, rolled in it is TFL."),
     ("Hip abductors and pelvic stability",
      "Gluteus medius, gluteus minimus, TFL (and the upper fibres of gluteus maximus).",
      "In single-leg stance they hold the pelvis level against body weight trying to drop the opposite side — a lever problem, not a strength-to-move problem.",
      "<b>Trendelenburg sign</b> (pelvis drops on the unsupported side) or a <b>compensated Trendelenburg gait</b> (trunk leans over the weak hip to shorten the lever). Superior gluteal nerve."),
     ("Deep six lateral rotators",
      "Piriformis, superior gemellus, obturator internus, inferior gemellus, quadratus femoris, obturator externus.",
      "Run horizontally behind the hip from pelvis to greater trochanter, top to bottom in that order. Rotate the hip laterally and hold the femoral head in the socket like a posterior cuff.",
      "<b>Tested only as a group.</b> The sciatic nerve usually passes below piriformis — the relationship behind piriformis syndrome, whose diagnostic tests are argued about. " + X()),
     ("Gluteus maximus and hamstrings (hip extension)",
      "Gluteus maximus, semitendinosus, semimembranosus, biceps femoris long head, hamstring part of adductor magnus.",
      "Share hip extension. The hamstrings dominate in walking; gluteus maximus is recruited for climbing, rising and running.",
      "<b>Gluteus maximus lurch</b> — trunk thrown backward at heel strike to keep the hip extended — when gluteus maximus is weak. Hamstring cramping in a hip-extension test means the knee was left straight."),
     ("Quadriceps",
      "Rectus femoris, vastus lateralis, vastus medialis, vastus intermedius.",
      "Four heads, one tendon to the patella and on to the tibial tuberosity; one nerve (femoral). Only rectus femoris crosses the hip.",
      "<b>Knee buckling in stance and difficulty with stairs and sit-to-stand.</b> An extensor lag — full passive extension but not active — is the classic sign after knee surgery."),
     ("Hamstrings",
      "Semitendinosus, semimembranosus, biceps femoris (long and short heads).",
      "Three muscles from the ischial tuberosity crossing hip and knee. Medial pair rotate the flexed knee in, biceps rotates it out. Short head of biceps is the odd one — one joint, fibular division.",
      "<b>Strain at the proximal musculotendinous junction</b> in sprinting; weakness on the fibular side only (short head) is a common fibular division lesion."),
     ("Pes anserinus (Say Grace before Tea)",
      "Sartorius, gracilis, semitendinosus.",
      "Three tendons inserting together on the proximal medial tibia, from three compartments with three nerves (femoral, obturator, tibial). All flex the knee and rotate the flexed knee medially.",
      "<b>Pain and tenderness just below the medial joint line</b> — pes anserine bursitis and tendinopathy. They also resist valgus dynamically."),
     ("Hip adductors",
      "Adductor longus, brevis and magnus, pectineus, gracilis (obturator externus as a rotator).",
      "The medial compartment, mostly on the obturator nerve. Adductor magnus has a second nerve (tibial) for its hamstring part.",
      "<b>Groin pain on resisted adduction</b> (squeeze test); obturator nerve loss leaves some adduction through adductor magnus and pectineus."),
     ("Triceps surae",
      "Gastrocnemius (two heads) and soleus (and plantaris).",
      "Share the calcaneal tendon. Gastrocnemius crosses the knee and works best with it straight; soleus does not and works regardless.",
      "<b>Cannot rise on the toes of one leg</b> (tibial nerve, S1, or calcaneal tendon rupture — Thompson test: squeezing the calf does not plantarflex the foot). " + C()),
     ("Stirrup of the foot",
      "Tibialis anterior (medial) and fibularis longus (lateral, crossing under the foot).",
      "Both insert on the medial cuneiform and the base of the 1st metatarsal, from opposite sides, forming a sling under the midfoot. One inverts, one everts; together they steady the arch.",
      "<b>A flattened transverse arch</b> and loss of 1st-ray stability; fibularis longus weakness shows as a first metatarsal that will not plantarflex."),
     ("Tarsal tunnel (Tom, Dick And Very Nervous Harry)",
      "Tibialis posterior, flexor digitorum longus, (posterior tibial artery, vein, tibial nerve), flexor hallucis longus.",
      "Pass behind the medial malleolus under the flexor retinaculum in that order, front to back.",
      "<b>Burning in the sole with a positive Tinel's</b> over the tunnel — tibial nerve compression; tibialis posterior tendon failure is the adult acquired flatfoot."),
     ("Anterior compartment — foot drop",
      "Tibialis anterior, extensor hallucis longus, extensor digitorum longus, fibularis tertius.",
      "One compartment, one nerve (deep fibular), one job: lift the foot in swing and lower it after heel strike.",
      "<b>Foot slap after heel strike and a steppage gait</b> (high knee to clear the toes). With eversion also weak, the lesion is the common fibular nerve; with eversion spared, the deep fibular branch or L4–L5."),
     ("Lateral compartment — evertors",
      "Fibularis longus and brevis.",
      "Superficial fibular nerve; both pass behind the lateral malleolus.",
      "<b>Weak eversion and recurrent inversion sprains</b>; loss with an intact anterior compartment localizes to the superficial fibular branch."),
    ]),
    ("Trunk, neck, jaw and breathing", [
     ("Abdominal wall",
      "Rectus abdominis, external oblique, internal oblique, transversus abdominis.",
      "Three flat layers with fibres at different angles — external oblique down and in (hands in pockets), internal oblique up and in, transversus horizontal — wrapped around a vertical rectus. All on T7–L1.",
      "<b>Beevor's sign</b>: the umbilicus moves upward on a curl-up when the lower abdominals are weak (a lesion around T10). " + C()),
     ("Oblique pair for trunk rotation",
      "External oblique on one side with internal oblique on the other.",
      "Rotating to the left uses the right external and the left internal oblique — their fibres line up across the midline as one diagonal.",
      "<b>Weak rotation to one side</b> points to the external oblique of the opposite side and the internal oblique of the same side."),
     ("Pelvic tilt force couples",
      "Anterior tilt: hip flexors with lumbar extensors. Posterior tilt: abdominals with gluteus maximus and hamstrings.",
      "Each pair pulls the pelvis in the same rotational direction from opposite ends.",
      "<b>Standing lumbar lordosis</b> reflects the balance between the two couples; weakness or shortness on one side is a common explanation that the evidence does not settle. " + X()),
     ("Erector spinae (I Love Spaghetti)",
      "Iliocostalis (lateral), longissimus (middle), spinalis (medial).",
      "Three parallel columns from a common tendon, lateral to medial in that order. They extend the spine and pay out under control as it flexes.",
      "<b>Absent flexion-relaxation</b> — erector spinae still firing at the end of forward bending — is a common finding in people with low back pain. " + C()),
     ("Transversospinalis",
      "Semispinalis, multifidus, rotatores.",
      "Run from transverse processes up and in to spinous processes, spanning fewer segments the deeper they are (semispinalis 4–6, multifidus 2–4, rotatores 1–2).",
      "<b>Multifidus wasting at the level of symptoms</b> is described after low back pain, on imaging rather than on a bedside test. " + C()),
     ("Superficial versus deep neck flexors",
      "SCM and scalenes (superficial); longus colli, longus capitis, rectus capitis anterior (deep).",
      "The superficial muscles lift the head and poke the chin forward; the deep muscles nod the chin and hold the cervical curve. A strong head lift can hide weak deep flexors.",
      "<b>The chin pokes out and the SCM stands proud</b> on the craniocervical flexion test when the deep flexors are weak."),
     ("Scalenes and the thoracic outlet",
      "Anterior, middle and posterior scalene with rib 1.",
      "The brachial plexus and subclavian artery pass between anterior and middle scalene; the subclavian vein passes in front of anterior scalene.",
      "<b>Arm symptoms provoked by positions that narrow the gap</b> — thoracic outlet syndrome, whose provocative tests have poor specificity. " + X()),
     ("Suboccipital triangle",
      "Rectus capitis posterior major, obliquus capitis superior, obliquus capitis inferior.",
      "Form the triangle that holds the vertebral artery and the suboccipital nerve; all on C1's posterior ramus.",
      "<b>Upper cervical headache</b> is attributed to these muscles and joints; the attribution rests mostly on clinical pattern. " + C()),
     ("Jaw closers and openers",
      "Closers: masseter, temporalis, medial pterygoid. Openers: lateral pterygoid, suprahyoids (digastric, mylohyoid, geniohyoid), gravity.",
      "All the muscles of mastication are on CN V3. Three close the mouth; the lateral pterygoid is the only one that opens it, pulling the condyle forward onto the eminence.",
      "<b>Jaw deviation toward the weak side</b> on opening (CN V3 lesion); limited opening with the jaw deviating toward a painful side is more often the TMJ."),
     ("Hyoid elevators and depressors",
      "Suprahyoids (digastric, stylohyoid, mylohyoid, geniohyoid) above; infrahyoids (sternohyoid, omohyoid, sternothyroid, thyrohyoid) below.",
      "Hold the hyoid between them like guy ropes; the suprahyoids pull the hyoid and larynx up and forward to open the oesophagus in swallowing, the infrahyoids bring them back.",
      "<b>Reduced laryngeal elevation</b> on a dry swallow, and cough or wet voice after it, flags a swallowing problem for formal assessment."),
     ("Muscles of breathing",
      "Quiet inspiration: diaphragm (with external intercostals). Forced inspiration adds SCM, scalenes, upper trapezius, pectoralis minor. Forced expiration: abdominals and internal intercostals; quiet expiration is passive recoil.",
      "The diaphragm alone does quiet breathing; the others are recruited as demand rises.",
      "<b>Accessory muscle use at rest</b> — neck muscles standing out with each breath — means the diaphragm is failing or the load is high. Paradoxical abdominal movement supine is bilateral diaphragm weakness."),
     ("Abdominal canister",
      "Diaphragm (top), pelvic floor (bottom), transversus abdominis (front and sides), multifidus (back).",
      "Together they pressurize and stiffen the trunk before and during limb movement.",
      "<b>Treating these as one functional unit</b> is widespread in rehabilitation; how much the timing of their activation matters for back pain is argued in the literature. " + X()),
    ]),
    ],
)

MOVES = dict(
    id="movements", nav="Movements", title="Every movement — prime movers, assistants and antagonists",
    note="read across, then cover the last column",
    lede="""The same muscles, organised by the movement you test rather than the muscle you name.
      <b>Prime movers</b> do most of the work; <b>assistants</b> help or take over when the prime
      mover is weak (which is exactly why they are the usual substitution); the <b>antagonist</b>
      does the opposite movement and has to relax, and its shortness is what limits range. The
      last column is the root that carries the movement and what you see when it fails.""",
    cols=("Prime movers", "Assist / substitute", "Antagonists", "Root and the failure"),
    blocks=[
    ("Scapula", [
     ("Elevation", "Upper trapezius, levator scapulae.", "Rhomboids.", "Lower trapezius, pectoralis minor, latissimus (depression).", "C3–C4 and CN XI. <b>Shoulder droops and a weak shrug.</b>"),
     ("Depression", "Lower trapezius, pectoralis minor.", "Latissimus dorsi, subclavius.", "Upper trapezius, levator scapulae.", "CN XI, C8–T1. <b>Cannot push up from a chair on straight arms.</b>"),
     ("Protraction", "Serratus anterior.", "Pectoralis minor, pectoralis major.", "Trapezius, rhomboids.", "C5–C7 (long thoracic). <b>Medial winging on a wall push.</b>"),
     ("Retraction", "Middle trapezius, rhomboids.", "Upper and lower trapezius, latissimus.", "Serratus anterior, pectoralis minor.", "CN XI, C4–C5. <b>Protracted resting scapula.</b>"),
     ("Upward rotation", "Upper and lower trapezius, serratus anterior (force couple).", "—", "Levator scapulae, rhomboids, pectoralis minor.", "CN XI, C5–C7. <b>Arm stops short of full elevation; winging.</b>"),
     ("Downward rotation", "Levator scapulae, rhomboids, pectoralis minor.", "Latissimus dorsi.", "Upper and lower trapezius, serratus anterior.", "C4–C5, C8–T1. <b>Uncontrolled lowering of the raised arm.</b>"),
    ]),
    ("Shoulder (glenohumeral)", [
     ("Flexion", "Anterior deltoid, coracobrachialis.", "Pectoralis major (clavicular), biceps.", "Latissimus, teres major, posterior deltoid, triceps long head.", "C5–C6. <b>Shrug and trunk lean to lift the arm.</b>"),
     ("Extension", "Latissimus dorsi, teres major, posterior deltoid.", "Triceps long head, pectoralis major (sternocostal, from flexion).", "Anterior deltoid, coracobrachialis, pectoralis major (clavicular).", "C5–C8. <b>Scapular retraction instead of arm movement.</b>"),
     ("Abduction", "Middle deltoid, supraspinatus.", "Anterior and posterior deltoid, biceps long head (in lateral rotation).", "Pectoralis major, latissimus, teres major.", "C5–C6. <b>Hike or lateral rotation to get the arm up.</b>"),
     ("Adduction", "Pectoralis major, latissimus dorsi, teres major.", "Coracobrachialis, triceps long head.", "Deltoid, supraspinatus.", "C6–C8. <b>Rarely weak in isolation — three muscles on three nerves.</b>"),
     ("Medial rotation", "Subscapularis, pectoralis major, latissimus, teres major.", "Anterior deltoid.", "Infraspinatus, teres minor, posterior deltoid.", "C5–C8. <b>Positive lift-off or belly press with a subscapularis tear.</b>"),
     ("Lateral rotation", "Infraspinatus, teres minor.", "Posterior deltoid.", "Subscapularis, pectoralis major, latissimus, teres major.", "C5–C6. <b>External rotation lag sign: the arm drifts back in when released.</b>"),
     ("Horizontal abduction", "Posterior deltoid.", "Infraspinatus, teres minor.", "Pectoralis major, anterior deltoid.", "C5–C6. <b>Scapular retraction substitutes.</b>"),
     ("Horizontal adduction", "Pectoralis major.", "Anterior deltoid, coracobrachialis.", "Posterior deltoid.", "C5–T1. <b>Trunk rotation substitutes.</b>"),
    ]),
    ("Elbow and forearm", [
     ("Elbow flexion", "Biceps, brachialis, brachioradialis.", "Pronator teres, wrist flexors.", "Triceps, anconeus.", "C5–C6 (ISNCSCI C5 key muscle). <b>Wrist flexion to curl the arm.</b>"),
     ("Elbow extension", "Triceps.", "Anconeus.", "Biceps, brachialis, brachioradialis.", "C7 (ISNCSCI C7 key muscle). <b>Locking or gravity-assisted extension.</b>"),
     ("Supination", "Supinator, biceps.", "Brachioradialis (from pronation to neutral).", "Pronator teres, pronator quadratus.", "C5–C6. <b>Shoulder lateral rotation rolls the forearm.</b>"),
     ("Pronation", "Pronator teres, pronator quadratus.", "Brachioradialis (from supination to neutral), flexor carpi radialis.", "Supinator, biceps.", "C6–C8 (median). <b>Shoulder abduction and medial rotation roll the forearm.</b>"),
    ]),
    ("Wrist and hand", [
     ("Wrist extension", "ECRL, ECRB, ECU.", "Extensor digitorum, extensor indicis, EDM.", "FCR, FCU, palmaris longus.", "C6–C7 (ISNCSCI C6 key muscle). <b>Wrist drop (radial n.).</b>"),
     ("Wrist flexion", "FCR, FCU.", "Palmaris longus, FDS, FDP, FPL.", "ECRL, ECRB, ECU.", "C7–C8. <b>Finger flexors curl first.</b>"),
     ("Radial deviation", "FCR, ECRL, ECRB.", "APL, EPB.", "FCU, ECU.", "C6–C7. <b>Thumb muscles substitute.</b>"),
     ("Ulnar deviation", "FCU, ECU.", "—", "FCR, ECRL, ECRB.", "C7–C8. <b>Radial deviation on wrist extension = ECU weak, ECRL intact (posterior interosseous n.).</b>"),
     ("Finger MCP flexion", "Lumbricals, interossei.", "FDS, FDP, flexor digiti minimi.", "Extensor digitorum.", "C8–T1. <b>Claw when intrinsics are lost.</b>"),
     ("Finger PIP flexion", "FDS.", "FDP.", "Extensor digitorum, lumbricals, interossei.", "C7–T1. <b>FDP substitution — the DIP flexes too.</b>"),
     ("Finger DIP flexion", "FDP.", "—", "Extensor digitorum, lumbricals, interossei.", "C8–T1 (ISNCSCI C8 key muscle: middle finger). <b>Cannot make the OK sign (anterior interosseous n.).</b>"),
     ("Finger MCP extension", "Extensor digitorum, extensor indicis, EDM.", "—", "FDS, FDP, lumbricals, interossei.", "C7–C8. <b>Finger drop with wrist extension spared (posterior interosseous n.).</b>"),
     ("Finger abduction", "Dorsal interossei, abductor digiti minimi.", "Extensor digitorum (in extension).", "Palmar interossei.", "C8–T1 (ISNCSCI T1 key muscle: little finger abduction). <b>Wartenberg's sign.</b>"),
     ("Finger adduction", "Palmar interossei.", "Long flexors (fingers converge in flexion).", "Dorsal interossei.", "C8–T1. <b>Cannot hold a card between straight fingers.</b>"),
     ("Thumb flexion", "FPL (IP), FPB (MCP).", "Opponens pollicis.", "EPL, EPB.", "C7–T1. <b>Tenodesis from wrist extension.</b>"),
     ("Thumb extension", "EPL (IP), EPB (MCP), APL (CMC).", "Thenar intrinsics via the extensor expansion (IP only).", "FPL, FPB.", "C7–C8. <b>Cannot lift the thumb off a flat table (EPL rupture).</b>"),
     ("Thumb palmar abduction", "APB, APL.", "Opponens pollicis.", "Adductor pollicis.", "C8–T1. <b>Thenar wasting (median at wrist).</b>"),
     ("Thumb adduction", "Adductor pollicis.", "EPL, FPL (Froment).", "APB, APL.", "C8–T1. <b>Froment's sign (ulnar n.).</b>"),
     ("Opposition", "Opponens pollicis.", "APB, FPB, opponens digiti minimi.", "EPL, APL.", "C8–T1. <b>Pinch tip to tip with the nail facing sideways.</b>"),
    ]),
    ("Hip", [
     ("Flexion", "Iliopsoas.", "Rectus femoris, sartorius, TFL, pectineus, adductor longus and brevis.", "Gluteus maximus, hamstrings, adductor magnus (hamstring part).", "L1–L3 (ISNCSCI L2 key muscle). <b>Leaning back; thigh rolls out (sartorius) or in (TFL).</b>"),
     ("Extension", "Gluteus maximus, hamstrings.", "Adductor magnus (hamstring part), posterior gluteus medius.", "Iliopsoas, rectus femoris, TFL, sartorius.", "L5–S2. <b>Lumbar extension lifts the leg; gluteus maximus lurch in gait.</b>"),
     ("Abduction", "Gluteus medius, gluteus minimus.", "TFL, upper gluteus maximus, sartorius, piriformis (in flexion).", "Adductors, gracilis, pectineus.", "L4–S1. <b>Trendelenburg sign; hip hiking by quadratus lumborum.</b>"),
     ("Adduction", "Adductor longus, brevis, magnus.", "Pectineus, gracilis.", "Gluteus medius, minimus, TFL.", "L2–L4. <b>Rolling forward or back to use flexors or extensors.</b>"),
     ("Medial rotation", "Gluteus minimus, anterior gluteus medius, TFL.", "Semitendinosus, semimembranosus, adductors (position-dependent).", "Deep six, gluteus maximus, sartorius.", "L4–S1. <b>Adduction swings the foot out.</b>"),
     ("Lateral rotation", "Deep six (piriformis, gemelli, obturator internus and externus, quadratus femoris), gluteus maximus.", "Sartorius, biceps femoris long head, posterior gluteus medius.", "Gluteus minimus, anterior gluteus medius, TFL.", "L4–S2. <b>Knee extension swings the foot in.</b>"),
    ]),
    ("Knee", [
     ("Extension", "Quadriceps.", "TFL (via the iliotibial tract, near full extension).", "Hamstrings, gracilis, sartorius, gastrocnemius, popliteus.", "L2–L4 (ISNCSCI L3 key muscle). <b>Knee buckling; extensor lag.</b>"),
     ("Flexion", "Hamstrings.", "Gastrocnemius, gracilis, sartorius, popliteus.", "Quadriceps.", "L5–S2. <b>Hip flexion (buttock rises) in prone.</b>"),
     ("Medial rotation of the tibia (knee flexed)", "Popliteus, semitendinosus, semimembranosus.", "Gracilis, sartorius.", "Biceps femoris.", "L4–S1. <b>Foot inversion fakes it.</b>"),
     ("Lateral rotation of the tibia (knee flexed)", "Biceps femoris.", "—", "Popliteus, medial hamstrings.", "L5–S2. <b>Hip lateral rotation fakes it.</b>"),
    ]),
    ("Ankle and foot", [
     ("Dorsiflexion", "Tibialis anterior.", "EHL, EDL, fibularis tertius.", "Gastrocnemius, soleus, tibialis posterior, fibularis longus and brevis, FHL, FDL.", "L4–L5 (ISNCSCI L4 key muscle). <b>Foot drop; steppage gait.</b>"),
     ("Plantarflexion", "Gastrocnemius, soleus.", "Tibialis posterior, fibularis longus and brevis, FHL, FDL, plantaris.", "Tibialis anterior, EHL, EDL, fibularis tertius.", "S1–S2 (ISNCSCI S1 key muscle). <b>Cannot heel-raise on one leg.</b>"),
     ("Inversion", "Tibialis posterior, tibialis anterior.", "FHL, FDL.", "Fibularis longus, brevis, tertius.", "L4–L5. <b>Toe clawing substitutes.</b>"),
     ("Eversion", "Fibularis longus, fibularis brevis.", "Fibularis tertius, EDL.", "Tibialis posterior, tibialis anterior.", "L5–S1. <b>Toe extensors evert in dorsiflexion.</b>"),
     ("Great toe extension", "EHL.", "EHB (MTP only).", "FHL, FHB.", "L5 (ISNCSCI L5 key muscle). <b>The classic L5 sign.</b>"),
     ("Toe extension (2–5)", "EDL, EDB.", "Lumbricals (IP).", "FDL, FDB.", "L5–S1. <b>EDB wasting on the dorsum.</b>"),
     ("Great toe flexion", "FHL (IP), FHB (MTP).", "—", "EHL, EHB.", "S1–S2. <b>Tenodesis from ankle dorsiflexion.</b>"),
     ("Toe flexion (2–5)", "FDL (DIP), FDB (PIP).", "Quadratus plantae, lumbricals and interossei (MTP).", "EDL, EDB.", "S1–S3. <b>Claw toes when intrinsics are weak.</b>"),
    ]),
    ("Trunk and neck", [
     ("Trunk flexion", "Rectus abdominis.", "External and internal obliques, (iliopsoas once the scapulae clear).", "Erector spinae, quadratus lumborum.", "T7–T12. <b>Beevor's sign.</b>"),
     ("Trunk extension", "Erector spinae, multifidus.", "Quadratus lumborum, semispinalis; gluteus maximus and hamstrings via the pelvis.", "Rectus abdominis, obliques.", "Posterior rami. <b>Hip extension lifts the trunk if legs are free.</b>"),
     ("Trunk rotation", "External oblique (opposite side), internal oblique (same side).", "Multifidus, rotatores, semispinalis.", "The opposite oblique pair.", "T7–L1. <b>Arm reaching across without thoracic rotation.</b>"),
     ("Trunk lateral flexion", "Quadratus lumborum, obliques.", "Erector spinae, rectus abdominis, psoas.", "The same muscles of the other side.", "T7–L4. <b>Hip hike versus side-bend.</b>"),
     ("Neck flexion (capital, nodding)", "Longus capitis, rectus capitis anterior.", "Longus colli, suprahyoids.", "Suboccipitals, semispinalis capitis.", "C1–C3. <b>Chin pokes instead of nodding.</b>"),
     ("Neck flexion (cervical)", "SCM, longus colli, anterior scalene.", "Middle scalene, infrahyoids.", "Splenius, semispinalis, upper trapezius, erector spinae.", "C2–C6, CN XI. <b>Head lag in supine lift.</b>"),
     ("Neck extension", "Splenius capitis and cervicis, semispinalis, erector spinae (cervical).", "Upper trapezius, levator scapulae, suboccipitals.", "SCM, longus colli and capitis, scalenes.", "Posterior rami, CN XI. <b>Thoracic extension substitutes.</b>"),
     ("Neck rotation", "SCM (to the opposite side), splenius (to the same side).", "Obliquus capitis inferior (C1 on C2), semispinalis, upper trapezius.", "The same muscles of the other side.", "CN XI, posterior rami. <b>Trunk rotation substitutes.</b>"),
     ("Neck lateral flexion", "Scalenes, SCM.", "Splenius, upper trapezius, levator scapulae, rectus capitis lateralis.", "The same muscles of the other side.", "C3–C8, CN XI. <b>Shoulder elevation brings the ear to the shoulder.</b>"),
    ]),
    ("Jaw and breathing", [
     ("Jaw elevation (closing)", "Masseter, temporalis, medial pterygoid.", "—", "Lateral pterygoid, suprahyoids.", "CN V3. <b>Asymmetric bulk on clenching.</b>"),
     ("Jaw depression (opening)", "Lateral pterygoid, suprahyoids.", "Gravity, platysma.", "Masseter, temporalis, medial pterygoid.", "CN V3, CN VII, C1. <b>Deviation toward the weak side.</b>"),
     ("Protrusion", "Lateral pterygoid, medial pterygoid.", "Masseter (superficial).", "Temporalis (posterior fibres), deep masseter, digastric.", "CN V3."),
     ("Retrusion", "Temporalis (posterior fibres).", "Deep masseter, digastric, geniohyoid.", "Lateral and medial pterygoids.", "CN V3."),
     ("Lateral excursion", "Lateral pterygoid (opposite side), medial pterygoid (opposite side), temporalis (same side).", "Masseter.", "The same muscles in reverse.", "CN V3."),
     ("Quiet inspiration", "Diaphragm.", "External intercostals.", "(Passive recoil.)", "C3–C5. <b>Paradoxical abdomen supine.</b>"),
     ("Forced inspiration", "Diaphragm, external intercostals.", "SCM, scalenes, upper trapezius, pectoralis minor, serratus anterior.", "Abdominals, internal intercostals.", "C3–C8, T1–T11. <b>Accessory muscle use at rest.</b>"),
     ("Forced expiration and cough", "Rectus abdominis, obliques, transversus abdominis.", "Internal intercostals, latissimus.", "Diaphragm.", "T7–L1. <b>Weak cough in spinal cord injury above T6.</b>"),
    ]),
    ],
)

NERVES = dict(
    id="nerves", nav="Nerves", title="Every motor nerve — what it supplies and what its loss looks like",
    lede="""The nerve column of the muscle tables, turned inside out. The finding is the picture a
      lesion of that nerve produces — the pattern you recognise across the room before you test a
      single muscle — and the muscles listed are the ones that produce it. Root levels are the
      common textbook ranges; they vary by a segment between texts and between people.""",
    cols=("Roots", "Muscles", "What its loss looks like"),
    blocks=[
    ("Cervical and brachial plexus", [
     ("Spinal accessory (CN XI)", "Cranial; C3–C4 proprioception.", "Sternocleidomastoid, trapezius.", "<b>Shoulder droops, weak shrug, lateral winging</b>, and weak head turning away from the lesion. The commonest cause is surgery in the posterior triangle."),
     ("Phrenic", "C3, C4, C5.", "Diaphragm.", "<b>Paradoxical abdominal movement supine</b>; one side is often asymptomatic, both sides cause breathlessness lying flat."),
     ("Dorsal scapular", "C4, C5.", "Rhomboids, levator scapulae.", "<b>Mild medial border prominence</b> and weak retraction; usually subtle."),
     ("Long thoracic", "C5, C6, C7.", "Serratus anterior.", "<b>Medial winging</b> — the medial border and inferior angle lift off the ribs on a wall push."),
     ("Suprascapular", "C5, C6.", "Supraspinatus, infraspinatus.", "<b>Wasting above and below the spine of the scapula</b> with weak abduction and lateral rotation; a lesion at the spinoglenoid notch wastes infraspinatus alone."),
     ("Nerve to subclavius", "C5, C6.", "Subclavius.", "No clinical picture."),
     ("Lateral pectoral", "C5, C6, C7.", "Pectoralis major (clavicular head, part of sternocostal).", "<b>Flattening of the upper chest</b> and weak adduction from flexion."),
     ("Medial pectoral", "C8, T1.", "Pectoralis minor, pectoralis major (sternocostal).", "<b>Weak adduction from above</b>; lower pectoral bulk lost."),
     ("Upper and lower subscapular", "C5, C6, C7.", "Subscapularis (both); teres major (lower).", "<b>Weak medial rotation</b>; rarely isolated."),
     ("Thoracodorsal", "C6, C7, C8.", "Latissimus dorsi.", "<b>Weak extension–adduction</b> and loss of the posterior axillary fold; cannot depress the shoulder to push up."),
     ("Axillary", "C5, C6.", "Deltoid, teres minor.", "<b>Flattened shoulder contour and weak abduction beyond the first few degrees</b>, with numbness over the lateral upper arm (regimental badge area). Shoulder dislocation and surgical neck fracture."),
     ("Musculocutaneous", "C5, C6, C7.", "Coracobrachialis, biceps, brachialis.", "<b>Weak elbow flexion and supination</b>, absent biceps reflex, numb lateral forearm; brachioradialis keeps some flexion."),
     ("Radial (above the elbow)", "C5–T1.", "Triceps, anconeus, brachioradialis, ECRL; then the posterior interosseous group.", "<b>Wrist drop</b> with finger drop and weak brachioradialis; triceps spared when the nerve is injured in the spiral groove (branches arise above it)."),
     ("Posterior interosseous", "C7, C8.", "Supinator, ECRB (usually), ECU, extensor digitorum, EDM, extensor indicis, APL, EPB, EPL.", "<b>Finger and thumb drop without wrist drop</b>; the wrist extends with radial deviation because ECRL is spared and ECU is not. No sensory loss."),
     ("Median (above the elbow)", "C6–T1.", "Pronator teres, FCR, palmaris longus, FDS; then the anterior interosseous group and the thenar muscles.", "<b>Hand of benediction</b> on trying to make a fist: index and middle fingers stay straight. Pronation lost."),
     ("Anterior interosseous", "C7, C8, T1.", "FPL, FDP to index and middle, pronator quadratus.", "<b>Cannot make an OK sign</b> — the thumb IP and index DIP collapse into a pinch of the pads. No sensory loss."),
     ("Median (at the wrist) — recurrent branch", "C8, T1.", "APB, opponens pollicis, FPB (superficial head); lumbricals 1–2 from the digital branches.", "<b>Thenar wasting, weak palmar abduction and opposition</b>, numbness of the lateral three and a half digits — carpal tunnel syndrome."),
     ("Ulnar", "C7, C8, T1.", "FCU, FDP to ring and little; at the wrist the hypothenar muscles, palmaris brevis, interossei, lumbricals 3–4, adductor pollicis, FPB (deep head).", "<b>Claw of the ring and little fingers</b>, Froment's and Wartenberg's signs, first web wasting. A lesion at the elbow claws <i>less</i> than one at the wrist (ulnar paradox)."),
    ]),
    ("Lumbar and sacral plexus", [
     ("Femoral", "L2, L3, L4.", "Iliacus, sartorius, pectineus, quadriceps, articularis genus.", "<b>Knee buckling, weak knee extension and hip flexion</b>, absent patellar reflex, numb anteromedial thigh and medial leg."),
     ("Obturator", "L2, L3, L4.", "Adductor longus, brevis, magnus (adductor part), gracilis, obturator externus, (pectineus).", "<b>Weak adduction and a circumducted swing</b>; numb patch on the medial thigh."),
     ("Superior gluteal", "L4, L5, S1.", "Gluteus medius, gluteus minimus, TFL.", "<b>Trendelenburg sign and gait.</b>"),
     ("Inferior gluteal", "L5, S1, S2.", "Gluteus maximus.", "<b>Difficulty rising from a chair and climbing stairs</b>; backward trunk lurch in stance."),
     ("Nerves to the lateral rotators", "L4–S2.", "Piriformis (S1, S2), obturator internus and superior gemellus (L5–S2), quadratus femoris and inferior gemellus (L4–S1).", "No distinct clinical picture."),
     ("Sciatic — tibial division", "L4–S3.", "Semitendinosus, semimembranosus, biceps femoris long head, adductor magnus (hamstring part); continues as the tibial nerve.", "<b>Weak knee flexion</b> with the tibial nerve deficits below."),
     ("Sciatic — common fibular division", "L4–S2.", "Biceps femoris short head; continues as the common fibular nerve.", "<b>Foot drop</b> with weakness of the short head of biceps — the sign that the lesion is above the knee, not at the fibular head."),
     ("Tibial", "L4–S3.", "Gastrocnemius, soleus, plantaris, popliteus, tibialis posterior, FDL, FHL; then the plantar nerves.", "<b>Cannot rise on the toes</b>, weak inversion and toe flexion, absent ankle reflex, numb sole."),
     ("Common fibular", "L4–S2.", "Divides into the deep and superficial fibular nerves.", "<b>Foot drop with weak eversion</b> and a numb dorsum of the foot; inversion is spared (tibialis posterior) — which separates it from an L5 root lesion, where inversion is weak too."),
     ("Deep fibular", "L4, L5, S1.", "Tibialis anterior, EHL, EDL, fibularis tertius, EDB, EHB.", "<b>Foot drop with eversion spared</b>; numb first web space."),
     ("Superficial fibular", "L5, S1, S2.", "Fibularis longus, fibularis brevis.", "<b>Weak eversion</b>; numb dorsum of the foot except the first web."),
     ("Medial plantar", "S1–S3 (texts differ).", "Abductor hallucis, FDB, FHB, lumbrical 1.", "<b>Burning in the medial sole</b>; motor loss rarely noticed."),
     ("Lateral plantar", "S1–S3 (texts differ).", "Quadratus plantae, abductor digiti minimi, FDM brevis, adductor hallucis, interossei, lumbricals 2–4.", "<b>Clawing of the lesser toes</b> over time."),
     ("Pudendal", "S2, S3, S4.", "External anal sphincter, external urethral sphincter, perineal muscles, part of levator ani.", "<b>Faecal and urinary incontinence and perineal numbness</b> — with saddle anaesthesia, a cauda equina red flag."),
    ]),
    ("Trunk and cranial", [
     ("Posterior rami of the spinal nerves", "Every segment.", "Erector spinae, transversospinalis, interspinales, splenius, suboccipitals (C1).", "<b>Segmental and hard to see</b> — the back muscles overlap many levels."),
     ("Thoraco-abdominal, subcostal, first lumbar (iliohypogastric, ilioinguinal)", "T7–L1.", "Rectus abdominis, obliques, transversus abdominis, pyramidalis.", "<b>Beevor's sign</b>; a segmental bulge of the abdominal wall after a thoracic nerve injury."),
     ("Intercostal", "T1–T11.", "Intercostals, subcostales, transversus thoracis, serratus posterior superior.", "<b>Paradoxical intercostal indrawing</b> in high spinal cord injury."),
     ("Ansa cervicalis", "C1, C2, C3.", "Sternohyoid, omohyoid, sternothyroid (thyrohyoid and geniohyoid by C1 with CN XII).", "No distinct bedside picture."),
     ("Oculomotor (CN III)", "Midbrain.", "Superior, inferior and medial rectus, inferior oblique, levator palpebrae superioris.", "<b>Eye down and out, ptosis</b>, and a dilated pupil when compression reaches the parasympathetic fibres."),
     ("Trochlear (CN IV)", "Midbrain.", "Superior oblique.", "<b>Vertical double vision looking down and in</b>, head tilted away from the lesion."),
     ("Trigeminal, mandibular division (CN V3)", "Pons.", "Masseter, temporalis, pterygoids, mylohyoid, anterior digastric, tensor veli palatini, tensor tympani.", "<b>Jaw deviates toward the weak side</b> on opening; wasting of the temple and cheek."),
     ("Abducens (CN VI)", "Pons.", "Lateral rectus.", "<b>Cannot abduct the eye</b>; horizontal double vision. A false localizing sign of raised intracranial pressure."),
     ("Facial (CN VII)", "Pons.", "Muscles of facial expression, platysma, stapedius, stylohyoid, posterior digastric.", "<b>Lower motor neuron: the whole side of the face, forehead included.</b> Upper motor neuron: the lower face only. Hyperacusis if the lesion is proximal to the nerve to stapedius."),
     ("Glossopharyngeal (CN IX)", "Medulla.", "Stylopharyngeus.", "<b>Reduced gag sensation</b> on one side; motor loss is hard to see."),
     ("Vagus (CN X)", "Medulla.", "Palate (except tensor), pharyngeal constrictors, palatoglossus, larynx.", "<b>Uvula deviates away from the weak side</b>, nasal speech, hoarse voice, weak cough, dysphagia."),
     ("Hypoglossal (CN XII)", "Medulla.", "Genioglossus, hyoglossus, styloglossus, intrinsic tongue muscles.", "<b>Tongue deviates toward the weak side</b>, with wasting and fasciculation on that side in a lower motor neuron lesion."),
    ]),
    ],
)

SECTIONS = [GROUPS, MOVES, NERVES]
