# -*- coding: utf-8 -*-
"""Upper limb: shoulder girdle, glenohumeral joint, elbow and forearm, wrist and hand."""
from common import M, T, C, X

SCAPULA = dict(
    id="scapula", nav="Scapula", title="Shoulder girdle — the muscles that place the scapula",
    lede="""Every arm movement starts here: these muscles position and hold the scapula so the
      glenohumeral muscles have a stable base to pull from. Trapezius is tested as three muscles
      because its three fibre groups pull in three directions and fail separately. The test
      position is the finding's context: watch the scapula, not the hand, because nearly every
      substitution in this region moves the arm correctly while the scapula does something else.""",
    groups=[
    ("Posterior — trapezius, levator scapulae, rhomboids", [
     M("Upper trapezius", "trapezius",
       "External occipital protuberance, medial third of the superior nuchal line, ligamentum nuchae, spinous process of C7.",
       "Posterior border of the lateral third of the clavicle and the acromion.",
       "Spinal accessory n. (CN XI), motor; C3–C4 carry proprioception.",
       "Elevates the scapula and upwardly rotates it with lower trapezius and serratus anterior; extends and laterally flexes the neck to the same side, rotates the face to the opposite side.",
       T("sitting, arms at the sides.", "none needed — test both sides together.",
         "patient shrugs both shoulders toward the ears; resist straight down on top of both shoulders.",
         "same, with a smaller range, or sitting with arms supported."),
       "<b>Levator scapulae and rhomboids also shrug</b> — they elevate with the inferior angle swinging <i>medially</i> (downward rotation), where upper trapezius swings it laterally. Neck side-bending toward the shoulder shortens the distance without elevating the scapula."),
     M("Middle trapezius", "trapezius",
       "Spinous processes and supraspinous ligament of T1–T5.",
       "Medial margin of the acromion and superior lip of the spine of the scapula.",
       "Spinal accessory n. (CN XI).",
       "Retracts (adducts) the scapula.",
       T("prone, shoulder abducted 90° and laterally rotated (thumb up), elbow extended.",
         "the opposite thorax.",
         "patient lifts the arm toward the ceiling, drawing the scapula toward the spine; resist downward at the distal arm or over the lateral scapula.",
         "sitting, arm supported on a table at 90°, retract across the surface."),
       "<b>Posterior deltoid lifts the arm while the scapula stays put</b> — the arm rises, the medial border does not move toward the spine. Rhomboids retract with downward rotation (inferior angle swings in); trunk rotation fakes range."),
     M("Lower trapezius", "trapezius",
       "Spinous processes of T6–T12.",
       "Tubercle at the medial end (root) of the spine of the scapula.",
       "Spinal accessory n. (CN XI).",
       "Depresses the scapula and upwardly rotates it; assists retraction.",
       T("prone, arm overhead at about 145° of abduction in line with the lower fibres, thumb up.",
         "the opposite thorax.",
         "patient lifts the arm from the table; resist downward at the distal arm. If shoulder range or deltoid weakness prevents the arm position, resist at the lateral scapula instead.",
         "same position, observe and palpate depression and retraction of the scapula without the arm lifted."),
       "<b>The arm lifts with the scapula elevating</b> — upper trapezius or levator doing the work. Lumbar extension raises the whole trunk and looks like range."),
     M("Levator scapulae", "levscap",
       "Posterior tubercles of the transverse processes of C1–C4.",
       "Medial border of the scapula from the superior angle to the root of the spine.",
       "Dorsal scapular n. (C5) and cervical nerves C3–C4.",
       "Elevates the scapula and tilts the glenoid inferiorly (downward rotation); laterally flexes the neck.",
       "<b>No isolated manual test.</b> It works in the shrug with upper trapezius; tell them apart by the inferior angle, which swings medially when levator dominates. Palpate deep to upper trapezius just above the superior angle. " + C(),
       "<b>Upper trapezius hides it completely</b> in the shrug. A shrug that drops the glenoid and brings the inferior angle toward the spine is levator- and rhomboid-dominant."),
     M("Rhomboid major", "rhomboid",
       "Spinous processes of T2–T5.",
       "Medial border of the scapula from the root of the spine to the inferior angle.",
       "Dorsal scapular n. (C4, C5).",
       "Retracts and downwardly rotates the scapula; fixes it to the thoracic wall.",
       T("prone, hand resting on the low back (shoulder adducted, extended and internally rotated, elbow flexed).",
         "the opposite thorax.",
         "patient lifts the hand off the back, keeping the arm in place; resist at the distal arm in the direction of scapular abduction and upward rotation (out and down).",
         "sitting, hand behind the back; observe the medial border move toward the spine."),
       "<b>Posterior deltoid and teres major lift the hand</b> without the scapula moving. Middle trapezius retracts without downward rotation, so watch the inferior angle. Anterior tilt from pectoralis minor lifts the hand by tipping the scapula."),
     M("Rhomboid minor", "rhomboid",
       "Ligamentum nuchae and spinous processes of C7–T1.",
       "Medial border of the scapula at the root of the spine.",
       "Dorsal scapular n. (C4, C5).",
       "Retracts and downwardly rotates the scapula; fixes it to the thoracic wall.",
       "<b>Tested with rhomboid major</b> — same position, same resistance. " + C(),
       "Same as rhomboid major."),
    ]),
    ("Anterior — serratus anterior, pectoralis minor, subclavius", [
     M("Serratus anterior", "serratus",
       "External surfaces of the lateral parts of ribs 1–8 (often 9).",
       "Anterior (costal) surface of the medial border of the scapula, most heavily at the inferior angle.",
       "Long thoracic n. (C5, C6, C7).",
       "Protracts the scapula and holds it against the thoracic wall; upwardly rotates it (inferior angle forward and lateral).",
       T("sitting, shoulder flexed to about 130°, elbow extended.",
         "the thorax, with a hand ready at the inferior angle.",
         "resist downward at the distal arm while palpating the inferior angle; the scapula should hold its upwardly rotated position against the chest wall. Supine alternative: shoulder flexed 90°, patient punches toward the ceiling; resist straight down through the fist.",
         "sitting, arm supported on a table at 90°, slide the arm forward; observe protraction."),
       "<b>Winging is the finding</b> — the medial border and inferior angle lift off the chest wall. Pectoralis major pushes the arm forward across the body (horizontal adduction) instead of protracting the scapula; elbow flexion in the supine punch lets triceps and pectoralis do the work."),
     M("Pectoralis minor", "pectoral",
       "Ribs 3–5 near their costal cartilages.",
       "Medial border and superior surface of the coracoid process.",
       "Medial pectoral n. (C8, T1).",
       "Draws the scapula forward and down against the thorax (depression, anterior tilt, downward rotation); raises ribs 3–5 in forced inspiration when the scapula is fixed.",
       T("supine, arm at the side.", "the opposite side of the thorax.",
         "patient lifts the front of the shoulder up off the table without pushing through the hand; resist at the anterior shoulder back toward the table.",
         "same, gravity-minimized is not practical — observe and palpate below the coracoid."),
       "<b>Pushing through the hand or elbow</b> recruits triceps and latissimus to lift the shoulder. Shoulder elevation (shrugging) substitutes for anterior tilt."),
     M("Subclavius", "thoraxm",
       "Junction of rib 1 and its costal cartilage.",
       "Inferior surface of the middle third of the clavicle.",
       "Nerve to subclavius (C5, C6).",
       "Anchors and depresses the clavicle.",
       "<b>No clinical test.</b> It cannot be isolated or palpated through pectoralis major. " + C(),
       "Nothing to fake — there is no test to fake."),
    ]),
    ],
)

SHOULDER = dict(
    id="shoulder", nav="Shoulder", title="Glenohumeral — the deltoid, the cuff, and the three big adductors",
    lede="""Deltoid moves the arm; the rotator cuff keeps the humeral head on the glenoid while it
      does. The three large adductor–internal rotators (latissimus, teres major, pectoralis major)
      share a job and a groove on the humerus. Deltoid is tested as three muscles, as trapezius
      is, because its three parts have three different lines of pull.""",
    groups=[
    ("Deltoid", [
     M("Anterior deltoid", "deltoid",
       "Anterior border and superior surface of the lateral third of the clavicle.",
       "Deltoid tuberosity of the humerus.",
       "Axillary n. (C5, C6).",
       "Flexes and medially rotates the arm.",
       T("sitting, shoulder flexed to 90°, elbow extended or slightly flexed, palm down.",
         "the shoulder girdle, over the scapula.",
         "hold at 90°; resist downward at the distal humerus.",
         "sidelying on the untested side, arm supported, flex the shoulder."),
       "<b>Shrugging or leaning back</b> — upper trapezius and trunk extension lift the arm. Lateral rotation lets biceps long head flex the shoulder; horizontal abduction toward the side turns it into middle deltoid."),
     M("Middle deltoid", "deltoid",
       "Lateral margin and superior surface of the acromion.",
       "Deltoid tuberosity of the humerus.",
       "Axillary n. (C5, C6).",
       "Abducts the arm beyond the first ~15°, which supraspinatus initiates.",
       T("sitting, shoulder abducted to 90°, elbow slightly flexed, palm down.",
         "over the superior scapula.",
         "hold at 90°; resist downward at the distal humerus.",
         "supine, abduct the arm along the table."),
       "<b>Upper trapezius hikes the shoulder and a lateral trunk lean tips the arm up.</b> Lateral rotation turns abduction into flexion by biceps long head and anterior deltoid — keep the palm down."),
     M("Posterior deltoid", "deltoid",
       "Inferior lip of the spine of the scapula.",
       "Deltoid tuberosity of the humerus.",
       "Axillary n. (C5, C6).",
       "Extends and laterally rotates the arm; horizontally abducts.",
       T("prone, shoulder abducted 90° with the arm over the table edge, elbow flexed 90° hanging.",
         "over the scapula.",
         "patient lifts the elbow toward the ceiling (horizontal abduction); resist downward at the distal humerus.",
         "sitting, arm supported at 90° on a table, slide it backward."),
       "<b>Rhomboids and middle trapezius retract the scapula</b>, carrying the arm back with no glenohumeral motion. Long head of triceps helps if the elbow is extended."),
    ]),
    ("Rotator cuff — supraspinatus, infraspinatus, teres minor, subscapularis", [
     M("Supraspinatus", "supra",
       "Supraspinous fossa of the scapula.",
       "Superior facet of the greater tubercle of the humerus.",
       "Suprascapular n. (C5, C6).",
       "Initiates abduction and works with deltoid through the range; compresses the humeral head into the glenoid.",
       T("sitting or standing, arm elevated to 90° in the scapular plane (about 30° forward of the frontal plane), elbow extended, thumb down (empty can) or thumb up at 45° lateral rotation (full can).",
         "over the superior scapula.",
         "hold; resist downward at the distal forearm or arm."),
       "<b>Pain inhibition reads as weakness</b> — a painful, weak result does not separate a tear from a painful tendon. Upper trapezius hikes the shoulder; deltoid is loaded in the same position, so the test biases supraspinatus rather than isolating it."),
     M("Infraspinatus", "infra",
       "Infraspinous fossa of the scapula.",
       "Middle facet of the greater tubercle of the humerus.",
       "Suprascapular n. (C5, C6).",
       "Laterally rotates the arm; holds the humeral head in the glenoid.",
       T("prone, shoulder abducted 90° with the arm on the table, elbow flexed 90° over the edge, forearm hanging.",
         "the distal humerus on the table.",
         "patient rotates the forearm up toward the ceiling (lateral rotation); resist at the distal forearm toward medial rotation. Sitting alternative: arm at the side, elbow at 90°, resist rotation outward.",
         "prone with the whole limb hanging over the edge, rotate the arm outward."),
       "<b>Elbow extension and supination swing the forearm</b> through the arc without rotating the humerus. Scapular retraction and trunk rotation fake range in sitting."),
     M("Teres minor", "cuff",
       "Middle part of the lateral border of the scapula.",
       "Inferior facet of the greater tubercle of the humerus.",
       "Axillary n. (C5, C6).",
       "Laterally rotates the arm; holds the humeral head in the glenoid.",
       "<b>Tested with infraspinatus.</b> Lateral rotation resisted with the arm abducted 90° in the scapular plane (hornblower position) biases teres minor. " + C(),
       "Same as infraspinatus."),
     M("Subscapularis", "subscap",
       "Subscapular fossa (costal surface of the scapula).",
       "Lesser tubercle of the humerus.",
       "Upper and lower subscapular nn. (C5, C6, C7).",
       "Medially rotates the arm; holds the humeral head in the glenoid.",
       T("prone, shoulder abducted 90°, elbow flexed 90° over the table edge.",
         "the distal humerus on the table.",
         "patient moves the palm up and back toward the ceiling (medial rotation); resist at the distal forearm toward lateral rotation. Lift-off: hand behind the back at waist level, lift it away from the back. Belly press: press the palm into the abdomen with the elbow held forward.",
         "prone with the limb hanging, rotate the arm inward."),
       "<b>Pectoralis major, latissimus and teres major all rotate medially</b> — the standard test cannot isolate subscapularis; lift-off and belly press bias it. Elbow extension or scapular anterior tilt lifts the hand in the lift-off without rotation."),
    ]),
    ("Adductor–medial rotators — latissimus dorsi, teres major, pectoralis major, coracobrachialis", [
     M("Latissimus dorsi", "lat",
       "Spinous processes of T7–T12, thoracolumbar fascia, iliac crest, inferior 3–4 ribs.",
       "Floor of the intertubercular sulcus of the humerus.",
       "Thoracodorsal n. (C6, C7, C8).",
       "Extends, adducts and medially rotates the humerus; raises the body toward the arms in climbing; depresses the shoulder girdle.",
       T("prone, arm at the side, medially rotated (palm up).",
         "the pelvis on the same side.",
         "patient lifts the arm toward the ceiling (extension with adduction); resist at the distal forearm toward flexion and abduction. Functional alternative: sitting, hands on the table, press down to lift the buttocks (shoulder girdle depression).",
         "sidelying, extend the arm along the table."),
       "<b>Posterior deltoid and teres major extend the arm</b> too; the depression press-up needs triceps unless the elbows are kept straight and locked. Trunk side-bending lifts the arm through the pelvis."),
     M("Teres major", "tmajor",
       "Posterior surface of the inferior angle of the scapula.",
       "Medial lip of the intertubercular sulcus (crest of the lesser tubercle).",
       "Lower subscapular n. (C5, C6, C7).",
       "Adducts, extends and medially rotates the arm.",
       T("prone, hand resting on the posterior iliac crest (shoulder extended, adducted, medially rotated, elbow flexed).",
         "the opposite thorax.",
         "patient lifts the elbow toward the ceiling; resist at the distal arm toward abduction and flexion."),
       "<b>Rhomboids lift the elbow by retracting the scapula</b> — the arm rises without glenohumeral extension. Latissimus contributes in the same position."),
     M("Pectoralis major — clavicular head", "pecmajor",
       "Anterior surface of the medial half of the clavicle.",
       "Lateral lip of the intertubercular sulcus of the humerus.",
       "Lateral pectoral n. (C5, C6, C7).",
       "Adducts and medially rotates the arm; flexes the arm from extension; horizontally adducts.",
       T("supine, shoulder flexed to 90° (or abducted 90° with elbow flexed), slight medial rotation.",
         "the opposite shoulder.",
         "patient moves the arm up and across toward the opposite shoulder; resist at the distal arm toward horizontal abduction.",
         "sitting, arm supported at 90° on a table, slide across the body."),
       "<b>Trunk rotation and shoulder protraction</b> carry the arm across. Anterior deltoid helps in the flexed start; a clavicular test that fails while the sternocostal one passes localizes to the lateral pectoral nerve."),
     M("Pectoralis major — sternocostal head", "pecmajor",
       "Anterior sternum, costal cartilages 1–6, aponeurosis of external oblique.",
       "Lateral lip of the intertubercular sulcus of the humerus.",
       "Lateral and medial pectoral nn. (C7, C8, T1).",
       "Adducts and medially rotates the arm; extends the arm from flexion.",
       T("supine, shoulder flexed to about 120° and slightly abducted.",
         "the opposite iliac crest.",
         "patient pulls the arm down and across toward the opposite hip; resist at the distal arm upward and outward.",
         "sitting, arm supported on a table, slide it down and across."),
       "<b>Latissimus pulls the arm down</b> without the across component. Trunk flexion and rotation fake the arc."),
     M("Coracobrachialis", "armm",
       "Tip of the coracoid process.",
       "Medial surface of the middle third of the humerus.",
       "Musculocutaneous n. (C5, C6, C7).",
       "Flexes and adducts the arm; helps hold the humeral head in the glenoid.",
       T("sitting, shoulder laterally rotated and flexed, elbow fully flexed, forearm supinated — full elbow flexion leaves biceps too short to contribute.",
         "the shoulder girdle.",
         "resist at the anteromedial distal arm toward extension and slight abduction."),
       "<b>Biceps takes over if the elbow is allowed to extend</b>, and anterior deltoid always contributes to flexion. This test biases coracobrachialis; it does not isolate it."),
    ]),
    ],
)

ELBOW = dict(
    id="elbow", nav="Elbow", title="Elbow and forearm — flexors, extensors and the forearm rotators",
    lede="""Three elbow flexors, and forearm position decides which one is doing the most:
      biceps with the forearm supinated, brachialis in every position, brachioradialis in
      mid-position. That is the whole test design — change the forearm, change the muscle. The
      rotators work the same way: biceps is the strongest supinator with the elbow at 90°, and
      elbow position is how the tests shift load between the pronators.""",
    groups=[
    ("Elbow flexors", [
     M("Biceps brachii", "biceps",
       "Short head: tip of the coracoid process. Long head: supraglenoid tubercle of the scapula.",
       "Radial tuberosity, and the fascia of the forearm via the bicipital aponeurosis.",
       "Musculocutaneous n. (C5, C6).",
       "Supinates the forearm; flexes the elbow, most strongly with the forearm supinated; weakly flexes the shoulder.",
       T("sitting, arm at the side, forearm supinated.",
         "the distal humerus from the front.",
         "patient flexes the elbow; resist at the distal forearm toward extension. The elbow flexors are the ISNCSCI key muscle for C5, graded supine.",
         "sitting with the shoulder abducted 90° and the arm on a table, flex the elbow along the surface."),
       "<b>Wrist flexors flex the elbow</b> if the fingers and wrist curl as the elbow bends. Shoulder extension or a trunk lean backward swings the forearm up; forearm pronation shifts the work to brachialis and brachioradialis."),
     M("Brachialis", "brachialis",
       "Distal half of the anterior humerus.",
       "Coronoid process and tuberosity of the ulna.",
       "Musculocutaneous n. (C5, C6); a lateral part often also from the radial n.",
       "Flexes the elbow in every forearm position — the elbow flexor that works regardless of rotation.",
       T("sitting, arm at the side, forearm pronated.",
         "the distal humerus.",
         "patient flexes the elbow; resist at the distal forearm toward extension."),
       "<b>Brachioradialis contributes in pronation too</b>, so this test biases brachialis rather than isolating it. Wrist flexor substitution as for biceps."),
     M("Brachioradialis", "brachiorad",
       "Proximal two-thirds of the lateral supracondylar ridge of the humerus.",
       "Lateral surface of the distal radius, just proximal to the styloid process.",
       "Radial n. (C5, C6, C7).",
       "Flexes the elbow, most strongly with the forearm in mid-position; brings the forearm toward mid-position from either extreme.",
       T("sitting, forearm in mid-position (thumb up).",
         "the distal humerus.",
         "patient flexes the elbow; resist at the distal radius toward extension. The belly stands out along the lateral forearm — look for it.",
         "sitting, arm supported, forearm in mid-position, flex along the table."),
       "<b>Biceps and brachialis flex the elbow in mid-position too</b>; the visible, palpable belly is the evidence brachioradialis is working. It is the one elbow flexor on the radial nerve, so it separates a radial from a musculocutaneous lesion."),
    ]),
    ("Elbow extensors", [
     M("Triceps brachii", "triceps",
       "Long head: infraglenoid tubercle. Lateral head: posterior humerus above the radial groove. Medial head: posterior humerus below the radial groove.",
       "Proximal olecranon, and the fascia of the forearm.",
       "Radial n. (C6, C7, C8).",
       "Extends the elbow; long head also extends and adducts the shoulder and steadies the humeral head.",
       T("prone, shoulder abducted 90° with the arm on the table, forearm hanging over the edge. Supine alternative: shoulder flexed 90°, elbow flexed.",
         "the distal humerus.",
         "patient extends the elbow to just short of full extension; resist at the distal forearm toward flexion. The elbow extensors are the ISNCSCI key muscle for C7.",
         "sitting, shoulder abducted 90° with the arm on a table, extend the elbow along the surface."),
       "<b>Locking the elbow in full extension</b> holds against resistance with bone, not muscle — test short of lock. Shoulder lateral rotation lets gravity drop the forearm into extension; horizontal abduction flings it."),
     M("Anconeus", "forearm",
       "Lateral epicondyle of the humerus.",
       "Lateral olecranon and the superior posterior ulna.",
       "Radial n. (C7, C8, T1).",
       "Assists triceps in extending the elbow; stabilizes the elbow.",
       "<b>Tested with triceps.</b> No isolated test; palpable just distal and lateral to the olecranon during resisted extension. " + C(),
       "Triceps does nearly all the work, so anconeus cannot be graded separately."),
    ]),
    ("Forearm rotators", [
     M("Supinator", "forearm",
       "Lateral epicondyle, radial collateral and anular ligaments, supinator fossa and crest of the ulna.",
       "Lateral, posterior and anterior surfaces of the proximal third of the radius.",
       "Deep branch of the radial n. / posterior interosseous n. — roots C5–C6 in most rehabilitation texts, C7–C8 in some anatomy texts. " + X(),
       "Supinates the forearm.",
       T("sitting, arm at the side, elbow flexed 90°, forearm pronated.",
         "the distal humerus against the side.",
         "patient turns the palm up; resist by gripping the distal radius and ulna (not the hand) toward pronation. Testing with the elbow extended reduces biceps' share, which is greatest at 90°.",
         "sitting, shoulder flexed with the forearm vertical, supinate."),
       "<b>Shoulder lateral rotation and adduction</b> roll the forearm over without supinating it. Gripping the hand lets wrist and finger muscles turn it."),
     M("Pronator teres", "forearm",
       "Humeral head: medial epicondyle. Ulnar head: coronoid process.",
       "Middle of the lateral surface of the radius (pronator tuberosity).",
       "Median n. (C6, C7).",
       "Pronates the forearm; assists elbow flexion.",
       T("sitting, arm at the side, elbow flexed 90°, forearm supinated.",
         "the distal humerus against the side.",
         "patient turns the palm down; resist at the distal radius and ulna toward supination.",
         "sitting, shoulder flexed with the forearm vertical, pronate."),
       "<b>Shoulder abduction and medial rotation</b> roll the forearm over. Wrist flexion recruits flexor carpi radialis."),
     M("Pronator quadratus", "forearm",
       "Distal quarter of the anterior ulna.",
       "Distal quarter of the anterior radius.",
       "Anterior interosseous n. (median) (C8, T1).",
       "Pronates the forearm; binds the distal radius and ulna.",
       T("sitting, elbow fully flexed, forearm supinated — full elbow flexion slackens pronator teres.",
         "the distal humerus.",
         "patient pronates; resist at the distal forearm toward supination."),
       "<b>Pronator teres still contributes</b> — the elbow-flexed position biases, it does not isolate. Shoulder abduction rolls the forearm over."),
    ]),
    ],
)

WRIST = dict(
    id="forearm", nav="Wrist &amp; fingers", title="Wrist and extrinsic finger muscles",
    lede="""The flexors come off the medial epicondyle, the extensors off the lateral epicondyle,
      and the long finger and thumb muscles cross the wrist on their way to the digits. That last
      fact is the source of most errors here: a wrist test with the fingers working is partly a
      finger test, and a finger test with the wrist moving is partly tenodesis. Keep the joint you
      are not testing still.""",
    groups=[
    ("Wrist flexors — medial epicondyle", [
     M("Flexor carpi radialis", "forearm",
       "Medial epicondyle of the humerus (common flexor origin).",
       "Base of the 2nd metacarpal (and often the 3rd).",
       "Median n. (C6, C7).",
       "Flexes and radially deviates the wrist.",
       T("sitting, forearm supinated and supported on a table, fingers relaxed.",
         "the forearm.",
         "patient flexes the wrist toward the radial side; resist at the base of the 2nd metacarpal toward extension and ulnar deviation.",
         "forearm in mid-position on its ulnar border, flex the wrist along the table."),
       "<b>Finger flexors flex the wrist</b> — if the fingers curl first, FDS and FDP are doing it. Abductor pollicis longus assists radial deviation."),
     M("Palmaris longus", "forearm",
       "Medial epicondyle of the humerus.",
       "Distal flexor retinaculum and the palmar aponeurosis.",
       "Median n. (C7, C8).",
       "Flexes the wrist; tenses the palmar aponeurosis.",
       "<b>Presence test, not a graded test:</b> oppose thumb to little finger and flex the wrist — the tendon stands out at the centre of the wrist. Absent unilaterally or bilaterally in a proportion of people that varies widely between populations. " + C(),
       "Flexor carpi radialis sits just radial to it and is mistaken for it; the palmaris tendon is the more central and more superficial of the two."),
     M("Flexor carpi ulnaris", "fcu",
       "Humeral head: medial epicondyle. Ulnar head: olecranon and posterior border of the ulna.",
       "Pisiform, hook of hamate, base of the 5th metacarpal.",
       "Ulnar n. (C7, C8).",
       "Flexes and ulnarly deviates the wrist.",
       T("sitting, forearm supinated and supported, fingers relaxed.",
         "the forearm.",
         "patient flexes the wrist toward the ulnar side; resist at the hypothenar border toward extension and radial deviation.",
         "forearm in mid-position, flex along the table."),
       "<b>Finger flexors</b> again — watch for the fingers flexing first. It is the wrist flexor on the ulnar nerve: weak ulnar-side wrist flexion with normal FCR points proximal to the elbow's ulnar branches."),
    ]),
    ("Long finger and thumb flexors", [
     M("Flexor digitorum superficialis", "fds",
       "Humero-ulnar head: medial epicondyle, ulnar collateral ligament, coronoid process. Radial head: superior half of the anterior radius.",
       "Sides of the middle phalanges of the medial four digits.",
       "Median n. (C7, C8, T1).",
       "Flexes the PIP joints of digits 2–5; assists MCP and wrist flexion.",
       T("forearm supinated, wrist neutral.",
         "hold every other finger in full extension — this blocks FDP, which shares a common belly — and stabilize the proximal phalanx of the tested finger.",
         "patient flexes the PIP joint; resist at the palmar middle phalanx. The DIP should stay floppy."),
       "<b>FDP flexes the PIP too</b> unless the other fingers are held straight — a DIP that flexes means FDP is working. The little finger's FDS often cannot be isolated at all. Wrist extension produces passive finger flexion (tenodesis)."),
     M("Flexor digitorum profundus", "fdp",
       "Proximal three-quarters of the medial and anterior ulna and the interosseous membrane.",
       "Bases of the distal phalanges of digits 2–5.",
       "Digits 2–3: anterior interosseous n. (median). Digits 4–5: ulnar n. Both C8, T1.",
       "Flexes the DIP joints of digits 2–5; assists flexion of every joint it crosses. The finger flexors (middle finger distal phalanx) are the ISNCSCI key muscle for C8.",
       T("forearm supinated, wrist neutral.",
         "the middle phalanx, with the PIP held in extension.",
         "patient flexes the DIP; resist at the palmar distal phalanx."),
       "<b>Tenodesis</b> — wrist extension pulls the fingers into flexion without any contraction. Rebound from forced extension looks like active flexion. Split innervation is the finding: DIP 2–3 weak with 4–5 strong is anterior interosseous or median; the reverse is ulnar."),
     M("Flexor pollicis longus", "fpl",
       "Anterior surface of the radius and the adjacent interosseous membrane.",
       "Base of the distal phalanx of the thumb.",
       "Anterior interosseous n. (median) (C7, C8).",
       "Flexes the IP joint of the thumb; assists MCP and CMC flexion.",
       T("forearm supinated, wrist neutral.",
         "the proximal phalanx of the thumb in extension.",
         "patient flexes the IP joint; resist at the palmar distal phalanx."),
       "<b>Wrist extension flexes the thumb passively</b> (tenodesis). Relaxation after active extension lets the IP drop into flexion and look like a contraction."),
    ]),
    ("Wrist extensors — lateral epicondyle and supracondylar ridge", [
     M("Extensor carpi radialis longus", "wristext",
       "Lateral supracondylar ridge of the humerus.",
       "Dorsal base of the 2nd metacarpal.",
       "Radial n. (C6, C7).",
       "Extends and radially deviates the wrist. The wrist extensors are the ISNCSCI key muscle for C6.",
       T("sitting, forearm pronated and supported, fingers relaxed.",
         "the forearm.",
         "patient extends the wrist toward the radial side; resist at the dorsum of the 2nd–3rd metacarpals toward flexion and ulnar deviation.",
         "forearm in mid-position, extend along the table."),
       "<b>Finger extensors extend the wrist</b> — if the fingers straighten first, extensor digitorum is doing it; keep them relaxed. It is the one radial wrist extensor above the posterior interosseous branch, so wrist extension that deviates radially with weak ECU localizes to the posterior interosseous n."),
     M("Extensor carpi radialis brevis", "ecrb",
       "Lateral epicondyle of the humerus (common extensor origin).",
       "Dorsal base of the 3rd metacarpal.",
       "Deep branch of the radial n. (C7, C8).",
       "Extends and radially deviates the wrist; the main wrist stabilizer during grip.",
       "<b>Tested with ECRL.</b> By convention the test is repeated with the elbow fully flexed, which slackens ECRL and biases ECRB. " + C(),
       "Same as ECRL. Grip is painful and weak when ECRB's origin is irritable — it is the wrist extensor that holds the wrist still while the fingers flex."),
     M("Extensor carpi ulnaris", "ecu",
       "Lateral epicondyle and posterior border of the ulna.",
       "Dorsal base of the 5th metacarpal.",
       "Posterior interosseous n. (C7, C8).",
       "Extends and ulnarly deviates the wrist.",
       T("sitting, forearm pronated and supported, fingers relaxed.",
         "the forearm.",
         "patient extends the wrist toward the ulnar side; resist at the dorsum of the 5th metacarpal toward flexion and radial deviation.",
         "forearm in mid-position, extend along the table."),
       "<b>Extensor digitorum and digiti minimi</b> extend the wrist if the fingers straighten first."),
    ]),
    ("Long finger and thumb extensors", [
     M("Extensor digitorum", "wristext",
       "Lateral epicondyle of the humerus.",
       "Extensor expansions of digits 2–5.",
       "Posterior interosseous n. (C7, C8).",
       "Extends the MCP joints of digits 2–5, and the IP joints through the expansion; assists wrist extension.",
       T("forearm pronated, wrist neutral, IP joints relaxed.",
         "the wrist and metacarpals.",
         "patient extends the MCP joints; resist on the dorsum of the proximal phalanges toward flexion.",
         "forearm in mid-position, extend the fingers along the table."),
       "<b>Wrist flexion extends the fingers passively</b> (tenodesis). Lumbricals and interossei extend the IP joints — watch the MCP joint, which only extensor digitorum (with indicis and digiti minimi) can extend."),
     M("Extensor indicis", "forearm",
       "Posterior surface of the distal ulna and interosseous membrane.",
       "Extensor expansion of the index finger.",
       "Posterior interosseous n. (C7, C8).",
       "Extends the index finger independently; assists wrist extension.",
       T("forearm pronated, other fingers flexed into a fist.", "the wrist and metacarpals.",
         "patient extends the index MCP; resist at the dorsum of the proximal phalanx."),
       "<b>Extensor digitorum</b> extends the index too; holding the other fingers flexed limits it but does not remove it."),
     M("Extensor digiti minimi", "forearm",
       "Lateral epicondyle of the humerus.",
       "Extensor expansion of the little finger.",
       "Posterior interosseous n. (C7, C8).",
       "Extends the little finger.",
       T("forearm pronated, other fingers flexed.", "the wrist and metacarpals.",
         "patient extends the little finger MCP; resist at the dorsum of the proximal phalanx."),
       "<b>Extensor digitorum's slip to the little finger</b> is often small or absent, so this muscle may be the only extensor there."),
     M("Abductor pollicis longus", "snuffbox",
       "Posterior surfaces of the proximal halves of the ulna, radius and interosseous membrane.",
       "Lateral base of the 1st metacarpal.",
       "Posterior interosseous n. (C7, C8).",
       "Abducts the thumb and extends it at the CMC joint; assists radial deviation of the wrist.",
       T("forearm in mid-position, wrist neutral.", "the wrist.",
         "patient moves the 1st metacarpal away from the palm, forward and outward; resist at the lateral distal 1st metacarpal toward adduction.",
         "same, on the table."),
       "<b>Abductor pollicis brevis</b> abducts at the MCP and proximal phalanx rather than the metacarpal — resist on the metacarpal, not the phalanx. Radial wrist deviation fakes range."),
     M("Extensor pollicis brevis", "snuffbox",
       "Posterior surface of the distal radius and the interosseous membrane.",
       "Dorsal base of the proximal phalanx of the thumb.",
       "Posterior interosseous n. (C7, C8).",
       "Extends the MCP joint of the thumb; assists CMC extension.",
       T("forearm in mid-position, wrist neutral.", "the 1st metacarpal.",
         "patient extends the MCP with the IP relaxed; resist at the dorsal proximal phalanx."),
       "<b>Extensor pollicis longus</b> extends the MCP too — an IP that straightens as well means EPL is doing it."),
     M("Extensor pollicis longus", "epl",
       "Posterior surface of the middle third of the ulna and the interosseous membrane.",
       "Dorsal base of the distal phalanx of the thumb.",
       "Posterior interosseous n. (C7, C8).",
       "Extends the IP joint of the thumb, and the MCP and CMC; retropulsion (lifts the thumb off the table with the palm flat).",
       T("forearm pronated with the palm flat, wrist neutral.", "the proximal phalanx.",
         "patient extends the IP joint; resist on the dorsum of the distal phalanx. Retropulsion: lift the thumb off the table."),
       "<b>The thenar intrinsics extend the IP weakly</b> through their insertion into the extensor expansion, so a little IP extension survives an EPL rupture. Relaxing flexor pollicis longus lets the IP rebound into extension."),
    ]),
    ],
)

HAND = dict(
    id="hand", nav="Hand", title="Intrinsic hand muscles — thenar, hypothenar, lumbricals, interossei",
    lede="""Almost every intrinsic muscle is on the ulnar nerve's deep branch; the exceptions —
      the thenar trio and the lateral two lumbricals — are the median nerve's (the mnemonic is
      LOAF: lumbricals 1–2, opponens, abductor, flexor brevis). That split is the whole
      diagnostic value of this section. Interossei act about an axis through the middle finger:
      dorsal abduct, palmar adduct.""",
    groups=[
    ("Thenar and thumb", [
     M("Abductor pollicis brevis", "thenar",
       "Flexor retinaculum and the tubercles of the scaphoid and trapezium.",
       "Lateral base of the proximal phalanx of the thumb.",
       "Recurrent branch of the median n. (C8, T1).",
       "Abducts the thumb perpendicular to the palm (palmar abduction); helps opposition.",
       T("forearm supinated, hand flat.", "the metacarpals and wrist.",
         "patient lifts the thumb straight up from the palm; resist at the lateral proximal phalanx toward adduction."),
       "<b>Abductor pollicis longus</b> moves the thumb radially rather than forward, and radially deviates the wrist. Thenar wasting over APB is the visible sign of median compression at the wrist."),
     M("Flexor pollicis brevis", "thenar",
       "Superficial head: flexor retinaculum and trapezium. Deep head: trapezoid and capitate.",
       "Lateral base of the proximal phalanx of the thumb.",
       "Superficial head: recurrent branch of the median n. Deep head: deep branch of the ulnar n. Both C8, T1; the split varies between people. " + X(),
       "Flexes the MCP joint of the thumb.",
       T("forearm supinated.", "the 1st metacarpal.",
         "patient flexes the MCP with the IP kept straight; resist at the palmar proximal phalanx."),
       "<b>Flexor pollicis longus</b> flexes the MCP too — an IP that bends means FPL is doing it."),
     M("Opponens pollicis", "thenar",
       "Flexor retinaculum and the tubercle of the trapezium.",
       "Entire lateral border of the 1st metacarpal.",
       "Recurrent branch of the median n. (C8, T1).",
       "Opposes the thumb — flexes and medially rotates the 1st metacarpal at the CMC joint.",
       T("forearm supinated.", "the 5th metacarpal.",
         "patient brings the pad of the thumb to the pad of the little finger; resist at the distal 1st metacarpal, derotating it outward."),
       "<b>Flexor pollicis brevis and longus bring the tip to the little finger without rotating</b> — the thumbnail should face away from the palm (parallel to it) in true opposition, not stay sideways."),
     M("Adductor pollicis", "addpol",
       "Oblique head: bases of the 2nd–3rd metacarpals and capitate. Transverse head: anterior shaft of the 3rd metacarpal.",
       "Medial base of the proximal phalanx of the thumb.",
       "Deep branch of the ulnar n. (C8, T1).",
       "Adducts the thumb; brings it toward the palm in key grip.",
       T("forearm pronated.", "the metacarpals.",
         "patient holds a sheet of paper between the thumb and the side of the index finger with the thumb straight; pull the paper out."),
       "<b>Froment's sign</b> is the substitution itself: flexor pollicis longus (median) flexes the IP to grip the paper when adductor pollicis (ulnar) is weak. EPL also adducts, with extension."),
    ]),
    ("Hypothenar", [
     M("Abductor digiti minimi (hand)", "handm",
       "Pisiform.",
       "Medial base of the proximal phalanx of the little finger.",
       "Deep branch of the ulnar n. (C8, T1).",
       "Abducts the little finger; the small finger abductors are the ISNCSCI key muscle for T1.",
       T("forearm pronated, hand flat.", "the metacarpals.",
         "patient spreads the little finger away from the ring finger; resist at the ulnar side of the proximal phalanx."),
       "<b>Extensor digiti minimi</b> abducts as it extends — keep the finger flat. Wartenberg's sign (little finger resting abducted) is interossei weakness with EDM unopposed."),
     M("Flexor digiti minimi brevis (hand)", "handm",
       "Hook of hamate and the flexor retinaculum.",
       "Medial base of the proximal phalanx of the little finger.",
       "Deep branch of the ulnar n. (C8, T1).",
       "Flexes the MCP joint of the little finger.",
       T("forearm supinated.", "the 5th metacarpal.",
         "patient flexes the MCP with the IP joints straight; resist at the palmar proximal phalanx."),
       "<b>The long finger flexors</b> flex the MCP too; bent IP joints mean FDS and FDP are working."),
     M("Opponens digiti minimi", "handm",
       "Hook of hamate and the flexor retinaculum.",
       "Medial border of the 5th metacarpal.",
       "Deep branch of the ulnar n. (C8, T1).",
       "Draws the 5th metacarpal forward and rotates it toward the thumb, cupping the palm.",
       T("forearm supinated.", "the 1st metacarpal.",
         "patient brings the little finger toward the thumb across the palm; resist at the palmar distal 5th metacarpal."),
       "<b>Flexor digiti minimi and the long flexors</b> flex the finger without rotating the metacarpal."),
     M("Palmaris brevis", "handm",
       "Palmar aponeurosis and flexor retinaculum.",
       "Skin of the medial palm.",
       "Superficial branch of the ulnar n. (C8, T1).",
       "Wrinkles the skin over the hypothenar eminence and deepens the hollow of the palm.",
       "<b>Observe only:</b> the hypothenar skin wrinkles during strong little finger abduction. Not graded. " + C(),
       "Nothing to fake — it is observed, not graded."),
    ]),
    ("Lumbricals and interossei", [
     M("Lumbricals (hand), 1–4", "lumbrical",
       "Tendons of flexor digitorum profundus: 1st and 2nd from the lateral two tendons, 3rd and 4th from the adjacent sides of the medial three.",
       "Lateral sides of the extensor expansions of digits 2–5.",
       "1st and 2nd: median n. 3rd and 4th: deep branch of the ulnar n. All C8, T1.",
       "Flex the MCP joints and extend the IP joints of digits 2–5.",
       T("forearm supinated, fingers extended.", "the metacarpals.",
         "patient flexes the MCP joints while keeping the IP joints straight (the table-top position); resist at the palmar proximal phalanges."),
       "<b>FDS and FDP curl the fingers</b> — flexion at the IP joints means the long flexors are doing it. Loss produces the claw: MCP hyperextended by extensor digitorum, IP joints flexed by the long flexors."),
     M("Dorsal interossei (hand), 1–4", "interossei",
       "Adjacent sides of two metacarpals each (bipennate).",
       "Bases of the proximal phalanges and extensor expansions of digits 2–4.",
       "Deep branch of the ulnar n. (C8, T1).",
       "Abduct digits 2–4 away from the axis through the middle finger (DAB); flex the MCP and extend the IP joints.",
       T("forearm pronated, hand flat, MCP joints in neutral.", "the metacarpals.",
         "patient spreads the fingers; resist each finger at the side of its proximal phalanx — the index on its radial side (1st dorsal interosseous), the middle finger on both sides."),
       "<b>Extensor digitorum spreads the fingers as it extends them</b> — keep the MCP joints flat, not hyperextended. First dorsal interosseous wasting shows in the web space."),
     M("Palmar interossei (hand), 1–3", "interossei",
       "Palmar surfaces of the 2nd, 4th and 5th metacarpals (unipennate).",
       "Extensor expansions and bases of the proximal phalanges of digits 2, 4 and 5.",
       "Deep branch of the ulnar n. (C8, T1).",
       "Adduct digits 2, 4 and 5 toward the middle finger (PAD); flex the MCP and extend the IP joints.",
       T("forearm pronated, fingers abducted.", "the metacarpals.",
         "patient squeezes the fingers together; pull each finger away from the middle finger, or pull a card from between two fingers."),
       "<b>Finger flexion brings the fingers together</b> without the interossei — keep the fingers straight."),
    ]),
    ],
)

SECTIONS = [SCAPULA, SHOULDER, ELBOW, WRIST, HAND]
