# -*- coding: utf-8 -*-
SIDE = r'''
  <div class="tbl-wrap"><table class="rt">
    <colgroup><col style="width:18%"><col style="width:27%"><col style="width:27%"><col style="width:28%"></colgroup>
    <thead><tr><th>Communication disorder</th><th>What's impaired</th><th>Key features</th><th>Consistency</th></tr></thead>
    <tbody>
      <tr><td class="name">Aphasia</td><td>Language: using and understanding it (reading, writing, listening, speaking)</td><td>Fluent (empty speech, neologisms, poor insight) or non-fluent (telegraphic, effortful, aware)</td><td>Paraphasias and anomia across modalities</td></tr>
      <tr><td class="name">Apraxia of speech</td><td>Motor planning/programming of speech</td><td>Groping, high awareness and frustration; repetition helps; better when automatic</td><td>Inconsistent errors</td></tr>
      <tr><td class="name">Dysarthria</td><td>Motor execution: weakness, tone, incoordination</td><td>Slurred; affects respiration, phonation, articulation, prosody, resonance</td><td>Predictable, consistent errors</td></tr>
    </tbody></table></div>
  <p class="intro" style="margin-top:8px">{{u_slp}}</p>

  <div class="tbl-wrap" style="margin-top:18px"><table class="rt">
    <colgroup><col style="width:18%"><col style="width:41%"><col style="width:41%"></colgroup>
    <thead><tr><th>Hemiplegic UE</th><th>Hypotonia / flaccidity</th><th>Hypertonia / spasticity</th></tr></thead>
    <tbody>
      <tr><td class="name">Focus</td><td>Increase muscle activity; prevent contractures and learned non-use</td><td>Minimize hypertonicity; isolated movement out of pattern; balance muscle groups</td></tr>
      <tr><td class="name">Techniques</td><td>Positioning and handling, ROM with scapulohumeral rhythm, weight bearing with facilitation, strengthening (less-involved → bilateral → involved)</td><td>Deep pressure, rhythmic rotation, sustained stretch, warmth, weight bearing, education/HEP, strengthening out of pattern</td></tr>
      <tr><td class="name">Weight bearing is for…</td><td>Joint sense, recruitment, stability, brain–UE connection</td><td>Decreasing tone, mobility, isolating joint motion</td></tr>
      <tr><td class="name">Complementary</td><td>Approximation, VC, tactile cues, NMES</td><td>Pharmacology, splinting, orthotics, taping, positioning</td></tr>
    </tbody></table></div>
  <p class="intro" style="margin-top:8px">{{u_ue2}}</p>

  <div class="tbl-wrap" style="margin-top:18px"><table class="rt">
    <colgroup><col style="width:18%"><col style="width:27%"><col style="width:27%"><col style="width:28%"></colgroup>
    <thead><tr><th>Population</th><th>Strength</th><th>Aerobic</th><th>Key twist</th></tr></thead>
    <tbody>
      <tr><td class="name">Stroke</td><td>Resistive UE and LE; high intensity 60–80% max</td><td>HIIT 2–5 d/wk × 2–4 wk, 25–30 min, 85–95% HRR</td><td>Monitor for hypotensive responses on the stepper</td></tr>
      <tr><td class="name">Parkinson disease</td><td>Moderate, ≥ 2–3×/wk</td><td>Moderate-high, &gt; 60% HR max</td><td>Large amplitude, rotation, reciprocal; follow aerobic with gait/dual task</td></tr>
      <tr><td class="name">Multiple sclerosis</td><td>Moderate, ≥ 2×/wk</td><td>Beneficial without exacerbations; interval bouts</td><td>Shorten bouts, plan rest, let symptoms guide progression</td></tr>
    </tbody></table></div>
  <p class="intro" style="margin-top:8px">{{crozier18,u_ther}}</p>

  <div class="tbl-wrap" style="margin-top:18px"><table class="rt">
    <colgroup><col style="width:18%"><col style="width:27%"><col style="width:27%"><col style="width:28%"></colgroup>
    <thead><tr><th>Tool</th><th>What it measures</th><th>Scoring</th><th>Watch for</th></tr></thead>
    <tbody>
      <tr><td class="name">Modified Ashworth</td><td>Tone and spasticity</td><td>0, 1, 1+, 2, 3, 4</td><td>Document the muscle group</td></tr>
      <tr><td class="name">UMCT</td><td>Upright LE control (swing and stance)</td><td>Weak / Moderate / Strong (+ E, UT)</td><td>One graded trial per segment</td></tr>
      <tr><td class="name">Fugl-Meyer</td><td>Patterned vs selective movement post-stroke</td><td>UE MDC 3.2 total</td><td>Based on Brunnstrom stages</td></tr>
      <tr><td class="name">MoCA</td><td>Screen for MCI (7 domains)</td><td>&lt; 26 positive; +1 if &lt; 12 y education</td><td>A screen, not a diagnosis</td></tr>
      <tr><td class="name">PSFS</td><td>Patient-chosen functional goals</td><td>Stroke MCID 1.58; MS MCID 2.5</td><td>MDC and MCID differ by condition</td></tr>
    </tbody></table></div>
  <p class="intro" style="margin-top:8px">{{bohan87,hislop95,see13,krish17,evensen23,manago23}}</p>
'''
SIDE_N = 4

CONF = [
 ('Spasticity vs rigidity', '<b>Spasticity:</b> velocity-dependent, catch/clasp-knife, pyramidal', '<b>Rigidity:</b> constant through range, lead pipe/cogwheel, basal ganglia', 'Move faster: if resistance rises, it\'s spasticity.'),
 ('MAS 1 vs 1+', '<b>1:</b> catch and release, or minimal resistance at end range', '<b>1+:</b> catch, then minimal resistance through the rest (&lt; half) of ROM', 'Does the resistance continue after the catch? Then 1+.'),
 ('Ideational vs ideomotor apraxia', '<b>Ideational:</b> can\'t sequence a multi-step task or know how to use a tool', '<b>Ideomotor:</b> can\'t perform on verbal command', 'Ideomotor patients may do it <b>spontaneously</b> later.'),
 ('Apraxia of speech vs dysarthria', '<b>Apraxia:</b> planning; inconsistent; groping', '<b>Dysarthria:</b> execution; slurred; consistent', 'Consistency of errors.'),
 ('Fluent vs non-fluent aphasia', '<b>Fluent:</b> effortless, empty, poor insight', '<b>Non-fluent:</b> effortful, telegraphic, aware', 'Is the speaker frustrated and aware? Non-fluent.'),
 ('Phonemic vs semantic paraphasia', '<b>Phonemic:</b> sound swap ("wishdasher")', '<b>Semantic:</b> word swap ("table" for "bed")', 'Sounds vs meaning.'),
 ('Review of systems vs systems review', '<b>ROS:</b> asked in the history, by body system', '<b>Systems review:</b> brief exam of CV/pulm, integ, MSK, neuromuscular, communication, movement', 'Talking vs examining.'),
 ('PIP vs N-PIP', '<b>PIP:</b> reported by the patient', '<b>N-PIP:</b> identified by the therapist, team or family', 'Who raised it?'),
 ('MDC vs MCID', '<b>MDC:</b> smallest true change beyond error', '<b>MCID:</b> smallest meaningful change', 'Real vs worthwhile.'),
 ('Weber vs Rinne', '<b>Weber:</b> fork on the vertex; lateralization', '<b>Rinne:</b> mastoid then beside the ear; AC vs BC', 'Rinne tests conductive loss; bone louder = conductive loss.'),
 ('CN XII vs cortical lesion', '<b>CN XII:</b> tongue deviates toward the lesion', '<b>Cortex/corticobulbar:</b> tongue deviates away', 'Toward = nerve; away = brain.'),
 ('Rhythmic stabilization vs dynamic reversals', '<b>Rhythmic stabilization:</b> alternating isometrics, no motion', '<b>Dynamic reversals:</b> alternating concentric, with motion', 'Motion allowed? Dynamic reversals (add a hold for stability).'),
 ('Cyclic vs EMG-triggered NMES', '<b>Cyclic:</b> preset on/off, no active effort needed', '<b>EMG-triggered:</b> patient must reach a threshold to trigger it', 'Who starts the contraction?'),
 ('McConnell vs Kinesio taping', '<b>McConnell:</b> posture and alignment reminder', '<b>Kinesio:</b> more dynamic alignment', 'Neither holds the joint in place.'),
 ('Hypotonic vs hypertonic weight bearing', '<b>Hypotonic:</b> joint sense, recruitment, stability', '<b>Hypertonic:</b> reduce tone, mobility, isolate out of pattern', 'Same activity, opposite purpose.'),
 ('UMCT flexion vs extension tests', '<b>Flexion (1–3):</b> swing limb; 3 reps in 10 s', '<b>Extension (4–6):</b> stance limb', 'Knee extension and ankle PF add E (excessive) and UT grades.'),
]

THREADS = [
 ('Cueing tells you about fractionation', 'In movement analysis, regress with verbal → tactile → physical cues (Topic 2). If the person still can\'t change the pattern, they\'re likely synergistically bound (Topic 4), which means MMT isn\'t appropriate and the UMCT or Fugl-Meyer is the better tool.'),
 ('One exam, three kinds of screening language', 'MoCA gives a positive or negative <i>screen</i> (Topic 3). CN screens are documented by listing the nerves tested (Topic 3). Tone is documented by muscle group (Topic 4). The documentation topic (9E) collects these in one place.'),
 ('Hypotheses drive every test choice', 'The reasoning cycle (1D) forms hypotheses at initial observation and in the history. Movement analysis (2E) refines them. That is why test selection and outcome-measure selection (1H) both narrow step by step.'),
 ('SLP and PT share the cranial nerve territory', 'CN IX/X screening includes voice, palate and swallowing, and says to defer to speech therapy when in doubt (3I). The dysphagia warning signs (5I) and SLP referral triggers (5J) are what you act on when that screen is abnormal. Dysarthria shows up in both the cerebellar exam (4F) and motor speech (5F).'),
 ('PNF techniques reappear inside functional training', 'Replication teaches rolling from the end position (7C). Combination of isotonics shapes bridging and sit to stand (7E, 7H). Rhythmic stabilization adds stability to the bridge hold (7E). Learn the table in 6F once and reuse it.'),
 ('Strengthening wins in both tone problems', 'For hypotonia, strengthening follows less-involved → bilateral → involved (8G). For spasticity, resistance training improves function without increasing spasticity (8H). Aerobic and HIIT evidence (6B) points the same way: intensity is a tool, not a risk to avoid.'),
 ('The hand protects the shoulder', 'Early hand work drives proximal demand and reduces shoulder complications (8A). Slings add little (8E), FES targets supraspinatus and posterior deltoid for subluxation (8D), and weight bearing plus hand-opening principles keep the hand in the task (8F, 8I).'),
 ('Movement continuum everywhere', 'The five phases from 2G (initial conditions → termination) are the same grid used for rolling, supine to sit, sit to stand and seated scooting (7B–7I). Use it to structure the O section of a SOAP note (9A).'),
]

NUMS = [
 ('&lt; 8', 'GCS score in coma'),
 ('1.94 / 1.58', 'PSFS MDC / MCID in stroke'),
 ('2.1 / 2.5', 'PSFS MDC / MCID in MS'),
 ('6', 'ANPT core tasks for movement analysis'),
 ('5', 'Movement continuum phases'),
 ('&lt; 26', 'MoCA cut-off for a positive MCI screen'),
 ('51% / 96% · LR 13.5', 'MoCA sensitivity / specificity'),
 ('1.7', 'MoCA clinically meaningful change (points)'),
 ('+1 · /22', 'MoCA: &lt; 12 y education · MoCA Blind total'),
 ('60 · 75 · 60 · 100°', 'Visual field: superior · inferior · nasal · temporal'),
 ('24" → 4"', 'Intact convergence range'),
 ('≤ 40°', 'Spacing between saccade targets'),
 ('≥ 3 lines', 'DVA acuity drop = VOR impairment'),
 ('30° · 2 Hz', 'DVA head flexion · oscillation rate'),
 ('5–10°', 'Head impulse test rotation'),
 ('&gt; 3 beats', 'End-range nystagmus that is positive'),
 ('3.2 / 1.7 / 1.7', 'FMA UE MDC: total / proximal / hand-wrist'),
 ('30° · 60° · 10 s', 'UMCT hip/knee flexion grade cut-offs'),
 ('96% / 90%', 'UMCT reliability: flexion / extension'),
 ('&gt; 80%', 'Accuracy for intact (or impaired) sensation'),
 ('128 Hz', 'Tuning fork for vibration sense'),
 ('256 / 512 Hz', 'Tuning forks for Weber and Rinne'),
 ('~60%', 'Post-stroke cognitive impairment, first year'),
 ('7 ± 2', 'Items held in short-term memory'),
 ('20–40%', 'Acute stroke survivors with aphasia'),
 ('~65% · ~50%', 'Dysphagia: acute stroke · with silent aspiration'),
 ('60–80%', 'High-intensity strength or HR max after stroke'),
 ('85–95% HRR', 'HIIT intensity after stroke'),
 ('25–30 min', 'HIIT session length'),
 ('3–4', 'Max repeated stretches per PNF pattern'),
 ('3×', 'Rolling time post-stroke vs controls'),
 ('40% · &gt; 70%', 'Shoulder pain · UE dysfunction after stroke'),
 ('10–50 Hz · 2.5/2.5 s', 'FES for subluxation: frequency · on/off'),
 ('4.9 mm', 'Subluxation reduction with FES'),
 ('90° · 140°', 'Shoulder ROM limits without / with facilitated rhythm'),
 ('15 s · 1 min', 'Box and Block practice · test time'),
]

CASES = [
 ('1', 'The left side of the plate', 'A 74-year-old woman one month after a stroke keeps catching her left shoulder on door frames and leaves the food on the left side of her plate. She doesn\'t notice either. At intake she can\'t recall her discharge date, and her son fills in most of her history.',
  ['Which two impairments do you suspect?', 'How would you test them?'],
  ['<b>Left visual neglect</b>: doesn\'t attend to the left (bumps door frames, leaves food on the left of the plate). Screen with <b>line bisection</b> and <b>star cancellation</b>; also test confrontation <b>visual fields</b> to rule out a field cut.', '<b>Cognitive impairment</b> (memory): poor recall of events. Screen with the <b>MoCA</b> and document as a positive or negative screen, not a diagnosis.', 'Interview tip: sit in her line of vision, empower her first, then ask permission to involve her son.'],
  ['Neglect', 'MoCA'], '{{u_exam,ting11,krish17,u_subj}}'),
 ('3', 'Drowsy on day 2', 'On day 2 after a large stroke, the patient opens his eyes only after you call loudly and gently shake his shoulder. He answers slowly and needs repeated stimulation to keep responding.',
  ['What level of consciousness is this?', 'How does it shape your exam?'],
  ['<b>Obtunded</b>: arousable but difficult, needs repeated stimulation, slowed responses. (Lethargic patients can be roused with stimulation and show awareness, but fall back asleep easily.)', 'Choose exam activities suited to that level: short, simple, repeated arousal; defer tests that need sustained attention such as the MoCA. <span class="mine">inference</span>'],
  ['Levels of consciousness'], '{{tindall90,fell18}}'),
 ('3', 'A tongue that drifts', 'On CN XII testing, your patient\'s tongue deviates to the right on protrusion. There are fasciculations on the right side of the tongue.',
  ['Where is the lesion more likely?', 'How do you document it?'],
  ['With a CN XII (peripheral) lesion the tongue deviates <b>toward</b> the lesion; with a cortical or corticobulbar lesion it deviates <b>away</b>. Deviation to the right fits a <b>right CN XII</b> lesion. Fasciculations are one of the involuntary movements you are asked to look for.', 'Document: tongue deviates R on protrusion; fasciculations present; strength normal, weak or absent by side; note any dysarthria.'],
  ['CN XII'], '{{u_cn}}'),
 ('3', 'Dizzy after a virus', 'A 45-year-old reports dizziness. On the head impulse test, when you quickly turn her head to the left, her eyes drift with the head and then make a corrective saccade back to your nose. Her static acuity is 20/20; with 2 Hz head oscillation she reads 20/50.',
  ['Interpret the HIT.', 'Interpret the DVA.'],
  ['Corrective saccade after a <b>left</b> head turn → likely <b>left</b> peripheral vestibular loss: document "+L head impulse test".', '20/20 → 20/50 is a drop of more than 3 lines → <b>VOR impairment</b>. Document static and dynamic acuity, position, and plane (yaw).'],
  ['HIT', 'DVA'], '{{u_cn}}'),
 ('4', 'Catch at the elbow', 'Moving the patient\'s left elbow quickly into extension, you feel a catch followed by mild resistance through the rest of the range, less than half of it. Slowly, the arm moves freely.',
  ['Spasticity or rigidity?', 'MAS grade and documentation?'],
  ['Velocity-dependent catch → <b>spasticity</b>.', 'Catch followed by minimal resistance through less than half the range → <b>MAS 1+</b>.', 'Document by muscle group: "MAS 1+ L elbow flexors". Test the less-affected side first for a baseline.'],
  ['MAS'], '{{bohan87,u_exam}}'),
 ('4', 'Strong hip, weak ankle', 'On the UMCT, your patient flexes the hip past 60° three times in 8 seconds, flexes the knee to 45° three times in 9 seconds, and can\'t dorsiflex to a right angle. In single-limb stance with the knees at 30°, the knee keeps collapsing.',
  ['Grade each part you have data for.', 'Which gait phases are affected?'],
  ['Hip flexion <b>Strong</b> (&gt; 60° ×3 in 10 s); knee flexion <b>Moderate</b> (30–60° ×3 in 10 s); ankle DF <b>Weak</b> (no Moderate grade exists for DF); knee extension <b>Weak</b> (continues to collapse).', 'Flexion tests reflect the <b>swing</b> limb; extension tests reflect <b>stance</b>. Expect limited foot clearance in swing and poor knee control in stance. <span class="mine">inference</span>'],
  ['UMCT'], '{{hislop95}}'),
 ('5', 'Words that come out wrong', 'A 68-year-old after a left stroke talks easily and at length, but you can\'t follow the meaning. He calls his wife "my table" and uses made-up words. He doesn\'t seem to notice his errors.',
  ['Fluent or non-fluent?', 'Name two error types and two communication strategies.'],
  ['<b>Fluent aphasia</b>: effortless, long sentences, empty content, decreased insight.', 'Errors: <b>semantic paraphasia</b> ("table" for wife) and <b>neologisms</b> (made-up words).', 'Strategies: short, simple, direct language; verify understanding ("I heard you say ___, is that right?"); use gestures, writing or pictures; don\'t pretend to understand.'],
  ['Aphasia'], '{{u_slp}}'),
 ('5', 'The wet voice at lunch', 'During a session over lunch, your patient with PD coughs after sips of water, and his voice sounds wet afterward. His wife says he had pneumonia twice this year.',
  ['What are you concerned about?', 'What do you do?'],
  ['<b>Dysphagia with aspiration</b>: coughing, wet voice after swallowing and recurrent pulmonary infections are warning signs. About half of people with dysphagia aspirate silently, so the absence of coughing wouldn\'t reassure you either.', '<b>Refer to SLP</b> (known PD, signs of aspiration). Instrumental testing (MBSS or FEES) is their call. Note risk factors such as oral care dependence and limited ambulation.'],
  ['Dysphagia', 'Referral'], '{{u_slp,panebi20}}'),
 ('6', 'HIIT after stroke', 'A 62-year-old 8 months after stroke walks safely on a treadmill with a harness. You want to start high-intensity interval training.',
  ['Give a dose using FITT.', 'What do you monitor?'],
  ['<b>F:</b> 2–5 days/week for 2–4 weeks. <b>I:</b> fastest safe walking speed or 85–95% HRR. <b>T:</b> 25–30 min sessions; bursts such as 30 s with 30–60 s recovery, up to 3 min on/4 min off. <b>T:</b> treadmill if safe.', 'Monitor intensity and vital signs; if you use a recumbent stepper, watch for hypotensive responses.'],
  ['HIIT'], '{{crozier18}}'),
 ('6', 'Tired by set two', 'A patient with MS says she stopped exercising because she\'s exhausted by the second set and her legs feel worse in the heat.',
  ['How do you adjust the program?'],
  ['Keep the challenge and change the dose: <b>shorten bouts</b> (fewer reps or less time, same task), <b>plan rest</b> before fatigue overwhelms performance and use it to return to the task, and <b>let symptoms guide progression</b>.', 'Combine moderate strength training (≥ 2×/week) with aerobic work; aerobic exercise is beneficial without causing exacerbations. Account for heat sensitivity and recovery time.'],
  ['MS dosing'], '{{u_ther,halab17,tallner12}}'),
 ('7', 'Rolling to the weak side', 'A 72-year-old woman, 4 months after a right stroke, rolls to the left independently but needs min assist and a verbal cue to bring her left arm across when rolling right. Her left arm moves in a flexion synergy when she reaches.',
  ['Why is rolling right harder?', 'Give two facilitation ideas.'],
  ['Rolling right means the involved <b>left</b> UE and LE must lead across midline; post-stroke, rolling toward the non-affected side tends to rely on pulling with the non-paretic arm while the paretic side follows passively.', 'Ideas: "where the eyes, head and neck go, the trunk will follow"; PNF D1 flexion ("follow your hand with your eyes… squeeze, turn and pull up and across"); LE D1 flexion ("toes up, heel up and across"); replication from the end position; reverse chop with manual contacts on the pelvis.'],
  ['Rolling', 'PNF'], '{{zukow25,hooge09,u_roll,u_ue2}}'),
 ('7', 'Dropping into the chair', 'The same patient stands with contact guard, pushing up with her right arm and leg. When she sits down, she drops into the chair with poor control.',
  ['Which phase and contraction type is the problem?', 'Pick a PNF technique to train it.'],
  ['Stand to sit requires <b>controlled eccentric</b> forces throughout, especially through the momentum-transfer phase until the buttocks land.', '<b>Combination of isotonics</b> (concentric, hold, eccentric without relaxation) or part-task practice of the lowering phase. Also consider forced use or error augmentation to load the left LE.'],
  ['Stand to sit'], '{{u_sts,u_ther}}'),
 ('8', 'Four days post-stroke, flaccid arm', 'A 61-year-old man is 4 days after a right stroke. His left UE is hypotonic with no active movement, and you can palpate an inferior shoulder subluxation. In sitting, the left arm hangs at his side and he props on his right hand.',
  ['List three priorities for the left UE.', 'Would you use a sling? FES?'],
  ['Priorities: <b>positioning and handling</b> to protect the shoulder (supported arm in bed and chair); <b>early mobility</b> and weight bearing through the left UE with facilitation; start work on the <b>hand</b> to drive proximal demand and prevent learned non-use.', 'Slings: evidence is insufficient and they are likely not beneficial. FES over supraspinatus and posterior deltoid (10–50 Hz, 2.5 s on/off, 3–5 days/week ≥ 4 weeks) can reduce subluxation (~4.9 mm on average).'],
  ['Hypotonia', 'Subluxation'], '{{u_ue1,u_ue2,ada05,lavi22,vafadar15}}'),
 ('8', 'Should we strengthen a spastic arm?', 'A family member worries that strengthening exercises will make their father\'s spastic arm "tighter".',
  ['What does the evidence say?', 'What is the goal of treatment?'],
  ['Resistance training improves strength, gait speed, function and quality of life <b>without exacerbating spasticity</b>, and may benefit spasticity itself. Weakness affects function more than spasticity does.', 'Goals are <b>functional and patient-centered</b>, never "decrease spasticity". Strengthen out of pattern where possible; use inhibition techniques (deep tendon pressure, rhythmic rotation, sustained stretch) as temporary preparation.'],
  ['Hypertonia'], '{{pak08,chacon24,ross07,u_ue2}}'),
 ('9', 'Writing the O and A', 'Today you did forced-use weight shifting onto the left LE in standing (5 min, min A), then sit-to-stand × 10 with VC for foot placement 3/5 reps.',
  ['Write one O line and one A line.'],
  ['<span class="mine">example</span> O: "Neuromuscular re-ed: forced-use weight shift to L LE in standing at counter × 5 min, min A at pelvis, to improve paretic-limb weight acceptance for gait and transfers. STS × 10 from 18\" mat, VC for L foot placement 3/5 reps, CGA."', '<span class="mine">example</span> A: "Pt demonstrates improved L LE weight acceptance with reduced reliance on R UE push-off, reducing fall risk during transfers; continues to require VC for foot placement. Would benefit from continued skilled PT."'],
  ['SOAP'], '{{u_soap}}'),
]

# Q: (topic, question, options, answer_index, explanation)
Q = [
 (1,"Which ANPT resource is the Evaluation Database to Guide Effectiveness?",["CPG","EDGE documents","JNPT","HOAC-II"],1,"EDGE = Evaluation Database to Guide Effectiveness; documents exist for PD, MS, TBI, SCI, stroke and vestibular disorders."),
 (1,"Which is person-first language?",["The stroke patient","A person with Parkinson disease","A TBI","The spastic arm"],1,"Person-first language is standard in journals and government documents, though some communities (e.g., Deaf) prefer not to use it."),
 (1,"In a neuro (vs ortho) exam, motor control is typically examined with:",["MMT and myotomes","Patterned vs selective movement and the UMCT","Dermatomes","Special tests"],1,"Ortho defaults to MMT/myotomes; neuro assesses patterned vs selective movement and upright motor control."),
 (1,"When does a clinician first form hypotheses in the streamlined framework?",["Only after all tests","During initial observation and the history","At discharge","After reassessment only"],1,"Hypotheses are formed early and guide data collection and test selection."),
 (1,"A daughter reports her father is forgetting his meds; he doesn't mention it. This is a:",["PIP","N-PIP","AP","Diagnosis"],1,"Non-patient-identified problems are raised by the therapist, team or family."),
 (1,"Anticipated problems require:",["Remediation","Prevention and education","Referral only","No action"],1,"Future problems → prevention; existing problems → remediation."),
 (1,"Which belongs to the systems review (exam), not the review of systems?",["Asking about GI symptoms","Screening communication, affect, cognition and learning style","Asking about weight loss","Asking about endocrine disease"],1,"Systems review: CV/pulm, integ, MSK, neuromuscular, communication/affect/cognition/language/learning style, movement."),
 (1,"Thinking out loud while you perform a transfer is reflection:",["On action","In action","After action","External only"],1,"In action = during the event; on action = after (e.g., a journal)."),
 (1,"Remaining accountable while a PTA provides part of the care is called:",["Consult","Refer","Manage","Co-manage"],2,"Manage = remain accountable when the plan involves assistive personnel."),
 (1,"The smallest change considered worthwhile or important is the:",["MDC","MCID","SEM","ICC"],1,"MDC = smallest change beyond error; MCID = smallest meaningful change."),
 (1,"Outcome measures used to track change and treatment effectiveness serve which purpose?",["Discriminative","Predictive","Evaluative","Diagnostic"],2,"Evaluate = track change, determine effectiveness."),
 (2,"During the subjective exam, the PT should be positioned:",["Standing over the patient","In the patient's line of vision at the same level","Behind the patient","Beside the caregiver"],1,"Patient supported (back, feet, arms), head neutral; PT in line of vision at the same level."),
 (2,"When family is present, you should:",["Address the family first","Empower the patient first, then ask permission to involve family","Ask the patient to leave","Only address family if the patient has aphasia"],1,"Empower the patient first, then ask permission to involve family/caregivers."),
 (2,"PSFS MCID in stroke is:",["1.58 points","1.94 points","2.1 points","2.5 points"],0,"Stroke: MDC 1.94, MCID 1.58. MS: MDC 2.1, MCID 2.5."),
 (2,"For a chronic neuro condition, a useful PLOF question is:",["What was your function at birth?","What was your function 6 months or 1 year ago, or before the most recent change?","What is your pain level?","Do you have insurance?"],1,"Anchor PLOF in time for chronic conditions."),
 (2,"Walking in a busy clinic is which Gentile category?",["Stationary individual, stationary environment","Moving individual, stationary environment","Stationary individual, moving environment","Moving individual, moving environment"],3,"Moving person in a moving environment."),
 (2,"Coming from sitting in an armchair to standing, walking, turning and sitting at a table is a:",["Discrete task","Continuous task","Serial task","Closed task"],2,"Serial = discrete movements performed sequentially."),
 (2,"Which is the correct order of movement continuum phases?",["Preparation, initial conditions, initiation, execution, termination","Initial conditions, preparation, initiation, execution, termination","Initiation, preparation, execution, termination, initial conditions","Initial conditions, initiation, preparation, execution, termination"],1,"Initial conditions → preparation → initiation → execution → termination."),
 (2,"'Understanding of instructions and timing of response to commands' belongs to which phase?",["Initial conditions","Preparation","Execution","Termination"],1,"Preparation is the internal process of understanding and selecting a response."),
 (2,"The recommended order for regressing a task is:",["Physical assist, tactile cue, verbal cue","Verbal cue, tactile cue, physical assist","Tactile cue, verbal cue, physical assist","Verbal cue, physical assist, tactile cue"],1,"Verbal → tactile → physical assistance (noting how, how much, where)."),
 (2,"Which is NOT one of the 6 ANPT core tasks?",["Sit to stand","Step up/down","Rolling","Reach, grasp and manipulate"],2,"Core tasks: sitting, sit to stand, standing, walking with a turn, step up/down, reach/grasp/manipulate."),
 (2,"'Ability to orient the body in relation to gravity' defines:",["Alignment","Stability","Verticality","Symmetry"],2,"Verticality is measured relative to a plumb line."),
 (2,"A patient who can't change their movement pattern with cues or instruction is most likely:",["Malingering","Synergistically bound","Apraxic","Normal"],1,"Unable to fractionate → synergistically bound."),
 (3,"A patient arousable only with repeated loud voice and gentle shaking, with slowed responses, is:",["Lethargic","Obtunded","Stuporous","Alert"],1,"Obtunded (minimally conscious state). Lethargic patients are easier to rouse and show awareness."),
 (3,"Coma corresponds to a GCS of:",["< 8","< 12","< 15","≤ 3 only"],0,"Coma: unarousable even with noxious stimuli; reflex motor responses; GCS < 8."),
 (3,"Difficulty finding a peeler in a cluttered drawer suggests a deficit in:",["Visual closure","Figure-ground","Depth perception","Neglect"],1,"Figure-ground: locating objects on a busy background."),
 (3,"Which tests screen for visual neglect?",["Snellen and Rinne","Line bisection and star cancellation","Weber and gaze holding","Box and Block"],1,"Line bisection and star cancellation (Ting 2011)."),
 (3,"A patient can't use scissors when asked but later uses them spontaneously. This is:",["Ideational apraxia","Ideomotor apraxia","Agnosia","Aphasia"],1,"Ideomotor apraxia: can't produce the movement to verbal command."),
 (3,"The MoCA cut-off for a positive MCI screen is:",["< 22","< 24","< 26","< 28"],2,"< 26: sensitivity 51%, specificity 96%, LR 13.5."),
 (3,"A MoCA of 22 should be documented as:",["Patient has mild cognitive impairment","Positive screen for mild cognitive impairment","Patient has dementia","Normal cognition"],1,"The MoCA screens; it doesn't diagnose."),
 (3,"A patient with 10 years of education scores 25 on the MoCA. The adjusted score is:",["24","25","26","27"],2,"Add 1 point for < 12 years of education."),
 (3,"In the swinging flashlight test for CN II, you observe:",["The ipsilateral pupil","The contralateral pupil","Eyelid elevation","Nystagmus"],1,"CN II: contralateral pupil should constrict. CN III: ipsilateral pupil."),
 (3,"Normal temporal visual field extends to about:",["60°","75°","90°","100°"],3,"Superior 60°, inferior 75°, nasal 60°, temporal 100°."),
 (3,"Convergence is considered intact if the patient can focus:",["Up to 10 inches","Up to 4 inches","Up to 1 inch","Only at 2 feet"],1,"Intact to 4\"; impaired if blurry or double > 4\" from the nose."),
 (3,"Which muscle is tested by asking the patient to wrinkle the forehead?",["Zygomaticus","Frontalis","Platysma","Masseter"],1,"CN VII: frontalis (eyebrows), zygomaticus (smile), orbicularis oris (purse), orbicularis oculi (close eyes), platysma."),
 (3,"On Weber testing, sound lateralizes to the left. This may mean:",["Left sensorineural loss","Left conductive loss or right sensorineural loss","Right conductive loss","Normal hearing"],1,"Lateralization = ipsilateral conductive or contralateral sensorineural loss."),
 (3,"A positive Rinne (abnormal) means:",["Air conduction louder than bone","Bone conduction louder or longer than air","Sound heard at midline","No sound heard"],1,"Bone > air = conductive hearing loss on the side tested."),
 (3,"Which DVA result indicates VOR impairment?",["1-line drop","2-line drop","3 or more line drop","No change"],2,"≥ 3-line drop in acuity during 2 Hz head oscillation."),
 (3,"Head turned quickly to the right; the eyes make a corrective saccade to the left. Document:",["+L HIT","+R HIT","Negative HIT","Central lesion"],1,"Weakness is on the side of the head turn: +R head impulse test."),
 (3,"Lack of upward gaze on gaze-holding testing is a:",["Peripheral sign","Central sign","Normal finding","Sign of CN VI palsy"],1,"Lack of upward gaze is a central sign."),
 (3,"The tongue deviates to the left on protrusion with a lesion of the:",["Left cortex","Left CN XII","Right CN XII","Right trigeminal nerve"],1,"Deviates toward a CN XII lesion; away from a cortical/corticobulbar lesion."),
 (3,"A right optic tract lesion produces:",["Blindness of the right eye","Right nasal hemianopia","Left homonymous hemianopia","Loss of both temporal fields"],2,"Right optic tract (or right occipital lobe) → left homonymous hemianopia."),
 (4,"Velocity-dependent resistance with a 'clasp-knife' feel is:",["Rigidity","Spasticity","Hypotonia","Paratonia"],1,"Spasticity: velocity/amplitude-dependent; pyramidal tract damage."),
 (4,"'Lead pipe' resistance equal in agonist and antagonist suggests dysfunction of the:",["Corticospinal tract","Basal ganglia/extrapyramidal pathways","Peripheral nerve","Cerebellum only"],1,"Rigidity: extrapyramidal, most commonly basal ganglia."),
 (4,"Which documentation of tone is correct?",["Hypertonicity in L elbow flexion","Hypertonicity in L elbow flexors","Spastic L arm","Tone 2+ elbow"],1,"State the muscle group, not the motion."),
 (4,"MAS 2 is:",["Catch and release at end range","More marked increase through most of ROM, but the part moves easily","Passive movement difficult","Rigid"],1,"3 = passive movement difficult; 4 = rigid."),
 (4,"To test for spasticity, you should:",["Move slowly from the lengthened range","Move quickly from the end of the shortened range","Test the more-affected side first","Only test in standing"],1,"Spasticity: start at the shortened range, elongate quickly; test the less-affected side first."),
 (4,"The strongest component of the UE flexion synergy is:",["Shoulder abduction","Elbow flexion","Forearm supination","Scapular elevation"],1,"Bolded in the synergy table: elbow flexion."),
 (4,"The UE extension synergy includes:",["Shoulder abduction/ER, supination","Shoulder adduction/IR, elbow extension, pronation","Scapular retraction","Wrist extension"],1,"Extension synergy: scapular protraction, shoulder add/IR, elbow extension, pronation, wrist and finger flexion."),
 (4,"The LE extension synergy includes:",["Hip abduction and ER","Hip extension/adduction/IR, knee extension, ankle PF/inversion","Ankle DF","Knee flexion"],1,"Strongest: hip adduction, knee extension, plantarflexion."),
 (4,"If a muscle group shows patterned movement, you should NOT:",["Document it","Perform MMT","Use the UMCT","Use the Fugl-Meyer"],1,"MMT is not appropriate for patterned movement."),
 (4,"The FMA UE total MDC is:",["1.7 points","3.2 points","5 points","10 points"],1,"Total 3.2; proximal UE 1.7; hand/wrist 1.7."),
 (4,"The UMCT flexion control test reflects which phase of gait?",["Stance","Swing","Double support","Terminal stance"],1,"Flexion = nonweight-bearing limb advancement (swing); extension = single-limb stance."),
 (4,"UMCT hip flexion 'Moderate' is:",["< 30°","30–60° three times within 10 s","> 60° three times within 10 s","Any range in > 10 s"],1,"Weak < 30° or > 10 s; Moderate 30–60°; Strong > 60°."),
 (4,"Which UMCT part has no Moderate grade?",["Hip flexion","Knee flexion","Ankle dorsiflexion","Hip extension"],2,"Ankle DF is graded only Weak or Strong."),
 (4,"During the UMCT knee extension test, the patient continues to collapse into flexion. Grade:",["Weak","Moderate","Strong","Excessive"],0,"Weak = unable to maintain body weight on the flexed knee."),
 (4,"A knee flexion contracture on the knee extension test means the grade can never exceed:",["Weak","Moderate","Strong","Unable to test"],1,"The grade can never exceed Moderate."),
 (4,"How many graded trials per segment does the UMCT allow?",["One","Two","Three","Unlimited"],0,"Up to two practice trials, then one graded trial."),
 (4,"Inability to perform rapid alternating movements is:",["Dysmetria","Dysdiadochokinesia","Rebound","Ataxia"],1,"RAMs: finger-thumb tap, pronation/supination, toe and heel taps."),
 (4,"Coordination grade 3 means:",["Normal","Minimal impairment","Moderate impairment: slow, awkward, unsteady; moderate contact guarding","Activity impossible"],2,"5 normal; 4 minimal; 3 moderate; 2 severe; 1 impossible."),
 (4,"For a patient with peripheral neuropathy, begin sensory testing:",["On the intact side","At the suspected impaired area (toes) and move proximally","At the face","Anywhere"],1,"Bilateral deficits: start at suspected impairment and move toward intact."),
 (4,"Accurate (> 80%) but delayed responses are graded:",["Intact","Impaired","Absent","NT"],1,"Impaired: accurate but delayed, duller, or hypersensitive."),
 (4,"Which tool is correct for vibration sense?",["256 Hz fork","128 Hz fork","Pinwheel","Cotton ball"],1,"128 Hz on bony prominences. 256/512 Hz forks are for Weber and Rinne."),
 (4,"Sharp/dull testing should use:",["A pinwheel","A safety pin opened wide","A needle","A tuning fork"],1,"Not a pinwheel. Precautions: diabetes, poor arterial circulation, lymphedema."),
 (5,"Which is an SLP 'Big 9' area?",["Gait","Aural rehabilitation","Balance","Orthotics"],1,"Cognitive-communication, social communication, motor speech, language, AAC, swallowing, voice, fluency, aural rehab."),
 (5,"Post-stroke cognitive impairment in the first year affects about:",["10%","30%","60%","90%"],2,"About 60% (El Husseini 2023)."),
 (5,"Focusing on a conversation in a noisy coffee shop is:",["Sustained attention","Selective attention","Alternating attention","Divided attention"],1,"Focused/selective attention prioritizes features despite competing stimuli."),
 (5,"Working memory differs from short-term memory because it:",["Holds more items","Also manipulates information","Is non-declarative","Is in the cerebellum"],1,"Temporary storage plus processing; prefrontal cortex."),
 (5,"Riding a bike relies on which memory?",["Semantic","Episodic","Procedural","Prospective"],2,"Procedural memory is non-declarative."),
 (5,"Which is NOT one of the 3 core EF skills?",["Inhibitory control","Working memory","Cognitive flexibility","Sustained attention"],3,"Attention is the foundation of the building, not a core EF skill."),
 (5,"Confabulation is:",["Deliberate lying","Fabricated information, not on purpose, from memory breakdown","Word-finding difficulty","Stuttering"],1,"A pragmatic issue tied to memory breakdown."),
 (5,"Inconsistent speech errors with groping and high awareness suggest:",["Dysarthria","Apraxia of speech","Fluent aphasia","Dysphonia"],1,"Apraxia = planning deficit; dysarthria errors are consistent."),
 (5,"Short, effortful, telegraphic speech with frustration is typical of:",["Fluent aphasia","Non-fluent aphasia","Global aphasia only","Confabulation"],1,"Non-fluent aphasia, often with apraxia/dysarthria."),
 (5,"Saying 'wishdasher' for 'dishwasher' is a:",["Semantic paraphasia","Phonemic paraphasia","Neologism","Telegraphic error"],1,"Phonemic = sound substitution."),
 (5,"The most common type of aphasia among acute stroke patients is:",["Fluent","Non-fluent","Global","Anomic"],2,"Global aphasia, from larger lesions in anterior and posterior language areas."),
 (5,"The most common cause of neurogenic dysphagia is:",["PD","MS","Stroke","Dementia"],2,"~65% of acute stroke patients."),
 (5,"About what share of people with dysphagia aspirate silently?",["10%","25%","50%","90%"],2,"~50%."),
 (5,"Which is a dysphagia warning sign?",["Improved appetite","Wet voice after swallowing","Weight gain","Short meals"],1,"Also coughing, fevers after eating, recurrent pneumonia."),
 (5,"The 4th stage of swallowing is:",["Oral preparatory","Oral transit","Pharyngeal","Esophageal"],3,"Oral preparatory → oral transit → pharyngeal → esophageal."),
 (6,"'High intensity' after stroke is generally:",["20–40% max","40–60% max","60–80% max strength or HR max","100% max"],2,"60–80% of max strength or HR max."),
 (6,"HIIT session length after stroke is typically:",["10 min","25–30 min","45–60 min","90 min"],1,"25–30 minutes, 2–5 days/week for 2–4 weeks."),
 (6,"For HIIT on a recumbent stepper, monitor carefully for:",["Hypertension only","Hypotensive responses","Hypoglycemia","Spasticity"],1,"Careful monitoring to mitigate potential hypotensive responses."),
 (6,"PD aerobic intensity should be:",["< 40% HR max","Moderate to high, > 60% HR max","Maximal only","Avoided"],1,"Plus large-amplitude, rotational and reciprocal movements."),
 (6,"In MS, the best response to fatigue during training is to:",["Stop exercising","Shorten bouts but keep the challenge","Only stretch","Exercise in the heat"],1,"Fatigue changes how you dose intensity, not whether you use it."),
 (6,"Which PNF technique starts with PROM and progresses to independent movement?",["Rhythmic stabilization","Rhythmic initiation","Replication","Combination of isotonics"],1,"PROM → AAROM → AROM → resisted → independent."),
 (6,"Alternating isometric contractions with no motion allowed describes:",["Dynamic reversals","Rhythmic stabilization","Repeated stretch","Rhythmic initiation"],1,"Goal: stability and co-contraction. VC: 'Don't let me move you.'"),
 (6,"Concentric, isometric and eccentric contractions of the same agonists without relaxation is:",["Combination of isotonics","Dynamic reversals","Replication","Rhythmic initiation"],0,"Goal: controlled mobility and eccentric control."),
 (6,"Starting at the end position of a movement and working backward is:",["Replication","Repeated stretch","Rhythmic initiation","Hold-relax"],0,"Teaches the final position; facilitates motor learning of a task."),
 (6,"How many repeated stretches per pattern are recommended?",["1","3–4","8–10","As many as tolerated"],1,"Only 3–4 repeated stretches per pattern."),
 (6,"Which technique is used for STABILITY?",["Rhythmic initiation","Replication","Dynamic reversals with a hold","Repeated stretch"],2,"Stability: rhythmic stabilization and dynamic reversals with a hold."),
 (7,"Which muscle is NOT listed as a key rolling muscle?",["SCM","Ipsilateral pectoralis major","Contralateral external oblique","Ipsilateral gluteus medius"],3,"SCM, ipsilateral pec major, contralateral external oblique, contralateral rectus femoris."),
 (7,"Compared with healthy controls, people post-stroke took about how long to roll?",["The same","1.5×","3×","10×"],2,"3× longer (Żukowska 2025)."),
 (7,"The most common healthy adult rolling pattern uses:",["UE push, LE lift","UE lift and reach above shoulder, LE unilateral push","Log roll","Head-first flexion only"],1,"From 32 combinations (Richter 1989)."),
 (7,"The Trunk Control Test items are scored:",["0–3","0, 12 or 25","0–4","Pass/fail"],1,"4 items: rolling both ways, supine to sit, sitting balance."),
 (7,"'Where the eyes, head and neck go, the trunk will follow' is an example of:",["Approximation","Irradiation","Error augmentation","Forced use"],1,"Hoogenboom 2009."),
 (7,"A manual cue applied opposite the direction of movement is:",["Directional","Resistance","Loading","Alignment"],1,"Directional = with movement; approximation = compress joint; loading = long axis."),
 (7,"To reduce hamstring cramping during a bridge:",["Move the feet farther from the pelvis","Move the feet closer to the pelvis","Lift the heels","Do a single-leg bridge"],1,"Feet closer decreases hamstring activation."),
 (7,"Adding a heel lift to a bridge:",["Increases hamstring, decreases glute max","Decreases hamstring, increases glute max","Has no effect","Increases calf only"],1,"Ankle DF also increases glute max activation."),
 (7,"Resisting pelvic elevation, then a hold, then slow lowering against pressure is:",["Rhythmic stabilization","Combination of isotonics","Replication","Rhythmic initiation"],1,"Concentric, isometric, eccentric; hands stay in the same place."),
 (7,"Highest ground reaction force in sit to stand occurs at:",["Initiation","Buttocks lift-off","Max hip extension","Stabilization"],1,"Momentum-transfer phase begins at lift-off."),
 (7,"In phase I of sit to stand, the erector spinae contract:",["Concentrically","Eccentrically","Isometrically","Not at all"],1,"Iliopsoas, abs, tibialis anterior concentric; erector spinae eccentric."),
 (7,"In stand to sit, maximum dorsiflexion occurs:",["At initiation","Just before the buttocks touch","After sitting","Never"],1,"Max trunk flexion occurs at initial contact."),
 (7,"Chair height and armrests are which category of STS determinant?",["Person-related","Chair-related (environment)","Strategy-related","Cognitive"],1,"Janssen 2002."),
 (7,"During lateral seated scooting with more assist, the head moves:",["With the hips","Opposite the hips","Straight up","Backward"],1,"Raise the bottom about an inch; head goes opposite the hips."),
 (7,"For a segmental forward scoot, place manual cues at the:",["Anterior pelvis","Posterior hip","Anterior knee","Shoulders"],1,"Posterior hip for forward; anterior pelvis for backward."),
 (7,"Which is a floor-transfer level?",["Independent with a walker","Modified assisted using a chair, ottoman or couch","Max assist of 2","Mechanical lift"],1,"1) independent; 2) modified assisted; 3) unable."),
 (8,"Up to what share of people post-stroke have persistent shoulder pain?",["10%","25%","40%","70%"],2,"More than 70% have some UE dysfunction."),
 (8,"Early hand work helps the shoulder because it:",["Immobilizes the shoulder","Creates purposeful demand on proximal motion","Reduces sensation","Replaces the need for PROM"],1,"Reduced hand movement reduces proximal demand and causes complications."),
 (8,"Which is a 'more active' way to minimize UE complications?",["Sling","Taping","Mirror therapy","PROM"],2,"Graded motor imagery (mirror therapy, mental imagery) is active."),
 (8,"EMG-triggered NMES requires the patient to:",["Rest passively","Actively reach a threshold to trigger stimulation","Walk","Stand"],1,"Cyclic NMES needs no active participation."),
 (8,"FES for shoulder subluxation targets:",["Biceps and triceps","Supraspinatus and posterior deltoid","Pec major and lats","Upper trap"],1,"10–50 Hz, 2.5 s on/2.5 s off."),
 (8,"The evidence on slings for the hemiplegic shoulder suggests they are:",["Essential","Likely not beneficial","Harmful in all cases","Only for pain"],1,"Insufficient evidence they prevent subluxation or reduce pain."),
 (8,"McConnell taping is used:",["To hold the humerus in the socket","As a reminder for posture and alignment","For dynamic alignment","For lymphedema"],1,"Kinesio tape is for more dynamic alignment."),
 (8,"Without facilitating scapulohumeral rhythm, avoid shoulder ROM above:",["60°","90°","120°","140°"],1,"With facilitation, stop at 140° max."),
 (8,"When opening a hypertonic hand, which do you open first?",["Extend the wrist","Open the thumb with pressure on the thenar eminence","Press into the palm","Extend all fingers at once"],1,"Open fingers before extending the wrist; stay out of the palm."),
 (8,"Strengthening progression for a hypotonic UE starts with:",["The involved UE unilaterally","The less-involved UE, then bilateral, then the involved UE","Bilateral only","Weights on the involved hand"],1,"Less involved → bilateral → unilateral skilled involved."),
 (8,"Which is a temporary inhibition technique for hypertonicity?",["Quick stretch","Deep non-noxious pressure on the tendon","Ice massage","Vibration"],1,"Also rhythmic rotation, sustained stretch, warmth, weight bearing."),
 (8,"Resistance training in people with spasticity:",["Worsens spasticity","Improves strength and function without exacerbating spasticity","Should be avoided","Only works in children"],1,"Pak & Patten 2008; Chacón-Barba 2024."),
 (8,"The goal of treatment for hypertonia should be:",["Decrease spasticity","Patient-centered and functional","Normalize MAS","Increase ROM only"],1,"Goals should never be directed at decreasing spasticity."),
 (8,"In NHPT, the stopwatch starts when the patient:",["Hears 'go'","Touches the first peg","Places the first peg","Picks up the container"],1,"Stops when the last peg hits the container."),
 (8,"In the Box and Block Test, two blocks carried at once:",["Count as two","Count as one","Don't count","Void the trial"],1,"Blocks that bounce out after crossing still count."),
 (9,"The O section of a treatment note is written:",["By importance","In chronological order of the session","Alphabetically","Only at discharge"],1,"Chronological order, showing skilled PT and progress."),
 (9,"Which belongs in A, not O?",["Reps and sets","Assist level","The PT's judgment of progress and factors affecting goals","Vital signs"],2,"A is professional judgment, not a summary of O."),
 (9,"Forced use and error augmentation are documented under:",["Therapeutic exercise","Neuromuscular re-education","Education","Plan"],1,"State body part, how and how long, and the functional reason."),
 (9,"In acute care, the most important reason to ask about home setup is:",["Billing","Discharge planning","Pain","Medication reconciliation"],1,"Home setup matters for discharge planning in acute care."),
 (9,"The first EGRESS step is:",["Stand and march","Move to the edge of the surface","Step forward and back","Walk"],1,"Edge → seated march → stand and march → step forward/back."),
 (9,"Rehab potential in an acute care assessment is rated:",["1–10","Good, fair or poor","MMT grades","Independent/dependent"],1,"Good, fair or poor."),
 (1,"In the common hypothesis (Ho) process, what comes right after the initial observation?",["Task/movement analysis","A first hypothesis, then the subjective exam","Testing potential impairments","Outcome measures"],1,"Initial observation → Ho → subjective exam → Ho → task/movement analysis → Ho of potential impairments → test them."),
 (2,"On the PSFS, how is the total score calculated?",["Sum of all activity scores","Sum of activity scores ÷ number of activities","Lowest activity score","Highest activity score"],1,"Each activity is rated 0 (unable) to 10 (pre-injury level); the total is the mean."),
 (2,"In the movement analysis glossary, which two constructs fall under postural control?",["Alignment and symmetry","Verticality and stability","Smoothness and timing","Speed and amplitude"],1,"Postural control = verticality and stability; coordination = smoothness, sequencing, timing, accuracy."),
 (3,"Weber test: sound lateralizes to the right ear. This is consistent with:",["Right sensorineural loss","Right conductive loss or left sensorineural loss","Normal hearing","Left conductive loss"],1,"A positive Weber lateralizes toward an ipsilateral conductive loss or away from a sensorineural loss."),
 (5,"Where are executive function processes performed?",["Occipital lobe","Frontal lobe","Cerebellum","Brainstem"],1,"Executive function is a frontal lobe process."),
 (5,"In the memory model, information that is never attended to is lost from:",["Long-term memory","Short-term memory","Sensory memory","Working memory only"],2,"Unattended → lost from sensory memory; unrehearsed → lost from STM; some LTM fades over time."),
 (5,"Which aphasia types come from lesions in the border zone (watershed) around the central speech areas?",["Broca's, Wernicke's, conduction","Transcortical motor, transcortical sensory, anomic","Global only","Conduction and global"],1,"Central: Broca's, Wernicke's, conduction, global. Border zone: transcortical motor, transcortical sensory, anomic."),
 (5,"Which word-retrieval stage is the motor plan for the word's sounds?",["Semantic concept","Lemma","Phonological word","Articulatory score"],2,"Concept → lemma → phonological code → phonological word (motor plan) → articulatory score (spoken)."),
 (7,"On the PASS, a score of 2 on an item means:",["Cannot perform","Performs with much help","Performs with little help","Performs without help"],2,"0 cannot, 1 much help, 2 little help, 3 without help."),
 (7,"In Janssen's determinants of sit to stand, a rigid AFO is a:",["Chair-related factor","Person-related factor","Strategy-related factor","Not a determinant"],2,"A fixed joint, light conditions, attention and training are strategy (task) factors."),
 (7,"Getting up from the floor using a chair, which comes right after quadruped near the chair?",["Tall kneel","Hands on the chair seat","Half-kneel","Push up to sit"],1,"Quadruped → hands on the seat → tall kneel → half-kneel → push up → sit."),
 (8,"Box and Block Test: a block tossed over without the fingertips crossing the partition is:",["Counted","Not counted","Counted as two","Counted only on the dominant side"],1,"Fingertips must cross; bounced blocks that did cross still count; two carried together count as one."),
 (9,"Which goal is written correctly as a patient-centered functional goal?",["Pt will decrease spasticity in L elbow flexors in 4 weeks","Pt will be able to walk better","Mr. R will walk 150 ft on tile with a quad cane and stand-by assist for balance within 3 weeks","Pt will increase L hip flexion strength to 4/5"],2,"It names who, an observable activity, conditions, how well and by when. Goals target function, never an impairment like spasticity on its own."),
 (9,"In the five-part goal format, \"with contact guard at the trunk and one verbal cue for hand placement\" is the:",["Who","What","Conditions","How well"],3,"How well = the help or accuracy needed, described concretely."),
]

F = [
 (1,"EDGE","Evaluation Database to Guide Effectiveness; ANPT documents for PD, MS, TBI, SCI, stroke, vestibular."),
 (1,"Ortho vs neuro exam (4 swaps)","Pain → social support/environment; dermatomes → areas; MMT/myotomes → patterned/selective + UMCT; normal tone → hyper/hypo."),
 (1,"Streamlined cycle","Initial impression → interview/history → exam → evaluation → POC → reassessment → outcome; reflection between steps; shared decision-making."),
 (1,"PIP / N-PIP / AP","Reported by patient / by therapist, team or family / may occur in future (prevention, education)."),
 (1,"Co-manage, consult, manage, refer","Coordinate with others / give or receive expert opinion / stay accountable using assistive personnel / send out for out-of-scope care or testing."),
 (1,"Reflection in vs on action","During the event (think aloud) vs after it (e.g., journal)."),
 (1,"Outcome measure purposes","Discriminate, predict, evaluate."),
 (1,"MDC vs MCID","Smallest true change beyond error vs smallest meaningful change."),
 (2,"Respect + 3 P's of the subjective","Respect (intro, name, family), privacy, position (supported pt; PT in line of vision, same level), pace."),
 (2,"PSFS MDC/MCID","Stroke 1.94 / 1.58; MS 2.1 / 2.5."),
 (2,"Gentile's 4 conditions","Stationary/moving individual × stationary/moving environment."),
 (2,"Discrete / continuous / serial","Clear start and end / no start or end / discrete movements in sequence."),
 (2,"Movement continuum phases","Initial conditions, preparation, initiation, execution, termination."),
 (2,"Task regression order","Verbal cue → tactile cue → physical assistance."),
 (2,"6 ANPT core tasks","Sitting, sit to stand, standing, walking with a turn, step up/down, reach/grasp/manipulate."),
 (2,"13 observable constructs","Symmetry, speed, amplitude, alignment, verticality, stability, smoothness, sequencing, timing, accuracy, force production, force sustainability, symptom provocation."),
 (3,"Levels of consciousness","Coma (GCS < 8), stupor, obtunded, lethargic, alert."),
 (3,"Closure / figure-ground / neglect","Partially hidden objects / busy background / not attending to part of space."),
 (3,"Ideational vs ideomotor apraxia","Can't sequence or use a tool vs can't perform on command (may do it spontaneously)."),
 (3,"MoCA key numbers","< 26 positive; sens 51%, spec 96%, LR 13.5; meaningful change 1.7; +1 if < 12 y education; Blind /22."),
 (3,"Visual field normals","Superior 60°, inferior 75°, nasal 60°, temporal 100°."),
 (3,"Convergence and saccades","Convergence intact to 4\"; saccade targets ≤ 40° apart, on target in 1–2 reps."),
 (3,"Weber vs Rinne","Vertex, lateralization = ipsi conductive or contra sensorineural / mastoid then ear; bone > air = conductive loss."),
 (3,"Gaze holding positive","> 3 beats at end range, any nystagmus at 25–30°, diplopia, can't reach ranges (no upgaze = central)."),
 (3,"DVA","Head flexed 30°, 2 Hz, 10–20° each way; ≥ 3-line drop = VOR impairment."),
 (3,"Head impulse test","Head 30° flexed; quick 5–10° turn; corrective saccade = loss on side of turn."),
 (3,"Tongue deviation","Toward a CN XII lesion; away from a cortical/corticobulbar lesion."),
 (3,"Left homonymous hemianopia","Right optic tract or right occipital lobe lesion."),
 (4,"Spasticity vs rigidity","Velocity-dependent, clasp-knife, pyramidal vs constant, lead pipe/cogwheel, basal ganglia."),
 (4,"MAS 0–4","0 none; 1 catch/end-range; 1+ catch + resistance < half; 2 most of ROM, moves easily; 3 difficult; 4 rigid."),
 (4,"Tone documentation","Muscle group, not motion: 'hypertonicity in L elbow flexors'."),
 (4,"UE flexion synergy","Scap elevation/retraction, shoulder abd/ER, ELBOW FLEXION (strongest), supination, wrist and finger flexion."),
 (4,"UE extension synergy","Scap protraction, SHOULDER ADDUCTION, IR, elbow extension, PRONATION, wrist and finger flexion."),
 (4,"LE flexion synergy","HIP FLEXION, abd, ER; knee flexion; ankle DF (inversion); toe DF/extension."),
 (4,"LE extension synergy","Hip ext, ADDUCTION, IR; KNEE EXTENSION; ANKLE PF (inversion); toe flexion."),
 (4,"FMA UE MDC","3.2 total; 1.7 proximal; 1.7 hand/wrist."),
 (4,"UMCT flexion grades (hip/knee)","W < 30° or > 10 s; M 30–60° ×3 in 10 s; S > 60° ×3 in 10 s."),
 (4,"UMCT knee extension grades","W collapses; M holds flexed knee; S holds then straightens; E extensor thrust; UT no plantigrade."),
 (4,"UMCT ankle PF grades","W knee collapses/wobbles; M knee 0°, ankle 90°, vertical tibia; S heel rise with knee at 0°; E equinus/varus; UT knee contracture."),
 (4,"Coordination grades","5 normal; 4 minimal; 3 moderate; 2 severe (initiate only); 1 impossible."),
 (4,"Sensation grades","Intact > 80% prompt; impaired > 80% delayed/duller/hypersensitive; absent < 80%; NT."),
 (4,"Which side to test first","Unilateral: intact side first. Bilateral: suspected impaired area, move toward intact. CNS: distal to proximal."),
 (5,"Big 9 of SLP","Cognitive-comm, social comm, motor speech, language, AAC, swallowing, voice, fluency, aural rehab."),
 (5,"4 attention types","Sustained, focused/selective, switching, divided."),
 (5,"Declarative vs non-declarative","Semantic, episodic, prospective vs procedural, priming, classical conditioning."),
 (5,"3 core EF skills","Inhibitory control, working memory, cognitive flexibility."),
 (5,"Apraxia of speech vs dysarthria","Planning, inconsistent, groping vs execution, consistent, slurred."),
 (5,"Fluent vs non-fluent aphasia","Effortless, empty, poor insight vs effortful, telegraphic, aware."),
 (5,"Aphasia error terms","Anomia, jargon/word salad, neologism, phonemic and semantic paraphasia, telegraphic speech; agraphia, alexia."),
 (5,"Dysphagia stats","Stroke ~65%, PD ~50%, MS ~31.3%, dementia 13–57%, MND 30–100%; ~50% aspirate silently."),
 (5,"4 swallow stages","Oral preparatory, oral transit, pharyngeal, esophageal."),
 (5,"When to refer to SLP","Known neuro dx, signs of aspiration, excessive throat clearing, unexpected cognitive or communication behaviors."),
 (6,"HIIT after stroke","2–5 d/wk × 2–4 wk; fastest safe speed or 85–95% HRR; 25–30 min; 30 s:30–60 s to 3:4 min; treadmill or stepper."),
 (6,"PD exercise","Moderate strength ≥ 2–3×/wk; aerobic > 60% HR max; big amplitude, rotation, reciprocal."),
 (6,"MS dosing rules","Shorten bouts (keep the task); plan rest; let symptoms guide progression."),
 (6,"PNF mobility techniques","Rhythmic initiation, dynamic reversals, repeated stretch, combination of isotonics, replication."),
 (6,"PNF stability techniques","Rhythmic stabilization; dynamic reversals with a hold."),
 (6,"Rhythmic initiation cue","'Relax and let me move you, now move with me, now help a little more, now I'll resist you.'"),
 (7,"Rolling muscles","SCM, ipsilateral pec major, contralateral external oblique, contralateral rectus femoris."),
 (7,"Rolling OMs","PASS (12 items, 0–3), Trunk Control Test (4 items, 0/12/25), 30-s roll to quadruped."),
 (7,"6 manual cue types","Muscle-specific, directional, approximation, loading, resistance, alignment."),
 (7,"Bridge tweaks","Feet closer = less HS; heel lift/DF = more glute max; single leg = more trunk co-activation."),
 (7,"STS phases","Flexion-momentum, momentum-transfer (lift-off), extension (from max DF), stabilization."),
 (7,"STS determinants","Chair (height, armrests), person (age, force, cognition), strategy (speed, foot/trunk position, UE use)."),
 (7,"Lateral scoot (more assist)","PT lateral; lift ~1 inch; trunk forward; head opposite hips; UE toward side abducted."),
 (7,"Floor transfer levels","Independent; modified assisted with furniture; unable."),
 (8,"UE stats post-stroke","Shoulder pain up to 40%; UE dysfunction > 70%; hand lags proximal recovery."),
 (8,"NMES types","Cyclic (preset), EMG-triggered (patient reaches threshold), FES (during function)."),
 (8,"FES for subluxation","Supraspinatus + posterior deltoid; 10–50 Hz; 2.5 s on/off; 3–5 d/wk ≥ 4 wk (inpatient rehab); ~4.9 mm less subluxation."),
 (8,"Slings","Insufficient evidence; likely not beneficial."),
 (8,"Shoulder ROM rule","No ROM above 90° unless facilitating upward rotation + ER; stop at 140°."),
 (8,"Hand-opening order","Gravity and trunk flexion → wrist flexion → thumb first (thenar) → spread metacarpal heads from thumb side → fingers before wrist → heel of hand on surface."),
 (8,"Hypertonia inhibition","Deep tendon pressure, rhythmic rotation, sustained stretch, warmth, weight bearing."),
 (8,"NHPT vs BBT","Timed pegs in and out (s) vs blocks moved in 1 min; dominant hand first; practice first."),
 (9,"O-section essentials","Task, MC, VC, direction of force, reps, assist, setup, equipment, outcome; quantify cues."),
 (9,"A-section language","Increase safety, reduce fall risk, reduce caregiver burden; not a summary of O."),
 (9,"EGRESS steps","Edge of surface → seated march → stand and march → step forward and back."),
 (1,"Ho process order","Initial observation → Ho → subjective exam → Ho → task/movement analysis → Ho of potential impairments → test them."),
 (2,"SDOH 5 domains","Economic stability · education · health care · neighborhood/built environment · social and community context."),
 (5,"EF wheel (5)","Planning and organizing · flexible thinking · problem solving · inhibition and self-regulation · insight and awareness."),
 (5,"Aphasia: central vs border zone","Central: Broca's, Wernicke's, conduction, global. Border zone: TC motor, TC sensory, anomic."),
 (5,"Word retrieval (5 stages)","Semantic concept → lemma → phonological code → phonological word (motor plan) → articulatory score."),
 (7,"Floor transfer down / up","Down: edge of mat → half-kneel → kneel, hands to floor (quadruped) → side sit. Up: quadruped → hands on chair → tall kneel → half-kneel → sit."),
 (9,"Functional goal: 5 parts","Who · does what (observable activity) · under what conditions · how well (specific help or accuracy) · by when. Never target an impairment such as spasticity."),
 (9,"SMART","Specific · Measurable · Achievable · Realistic/Relevant · Timed; set with the patient."),
]

# Short answer: (topic, question, answer_html, keyterms, need)
SA = [
 (1,"Describe the streamlined clinical reasoning and decision-making cycle, and where hypotheses fit.","Initial impression → interview/history (focused questions, review of systems, <b>formulate Ho</b>) → exam (systems review, task and movement analysis, outcome measures, impairment testing) → evaluation (diagnosis, prognosis, goals, PIP/N-PIP/AP, POC) → POC/interventions → reassessment → outcome. <b>Reflection</b> between steps; <b>shared decision-making</b> at the center. {{roth03,schenk06,deutsch22}}",
  [["interview/history",["interview","history"]],["exam",["exam"]],["evaluation",["evaluation"]],["plan of care / interventions",["plan of care","poc","intervention"]],["reassessment / outcome",["reassess","outcome"]],["reflection",["reflect"]],["hypothesis formed early",["hypothes","ho "]],["shared decision-making",["shared"]]],6),
 (1,"Compare PIP, N-PIP and AP, and how each is managed.","<b>PIP:</b> reported by the patient; current or anticipated; the therapist hypothesizes causes and sets testing criteria. <b>N-PIP:</b> identified by the therapist, team or family, not the patient. <b>AP:</b> may occur in the future; require prevention and education. Existing problems → <b>remediation</b>; future → <b>prevention</b>. {{roth03}}",
  [["PIP = patient reports",["patient-identified","reported by the patient","patient report"]],["N-PIP = therapist/team/family",["therapist","team","family","caregiver"]],["AP = future",["future","anticipat"]],["remediation",["remediat"]],["prevention / education",["prevent","educat"]]],4),
 (1,"Name the factors to consider when selecting an outcome measure, and define MDC and MCID.","What to measure (ICF level); purpose (discriminative, predictive, evaluative); type (disease-specific vs generic, performance vs self-report); patient and clinic factors; psychometrics (reliability, validity, diagnostic accuracy, responsiveness); feasibility (time, space, equipment, training, cost, language). <b>MDC</b> = smallest change beyond error; <b>MCID</b> = smallest meaningful change. {{potter11}}",
  [["ICF level",["icf","body function","activity","participation"]],["purpose",["discrimin","predict","evaluat"]],["type: performance vs self-report",["performance","self-report","self report","generic","disease-specific"]],["psychometrics",["reliab","valid","sensitiv","responsiv"]],["feasibility",["feasib","time","cost","equipment"]],["MDC = beyond error",["error","true change","detectable"]],["MCID = meaningful",["meaningful","important","worthwhile"]]],5),
 (2,"Contrast task analysis and movement analysis, and list the movement continuum phases.","<b>Task analysis:</b> how the person did the task: steps and order, devices, effectiveness, efficiency, safety. <b>Movement analysis:</b> quality during observation, using observable constructs (symmetry, speed, alignment, stability, timing…). Phases: <b>initial conditions, preparation, initiation, execution, termination</b>. {{quinn21,u_exam}}",
  [["task = steps / devices / safety",["step","device","safe","efficien","effective"]],["movement = quality / constructs",["quality","construct","symmetry","observ"]],["initial conditions",["initial"]],["preparation",["preparation"]],["initiation",["initiation"]],["execution",["execution"]],["termination",["termination"]]],5),
 (2,"How do you regress a task during analysis, and what does failure to respond to cueing tell you?","Regress in order: <b>verbal cue → tactile cue → physical assistance</b>, noting how much, how and where assistance is applied. If the person can't modify the movement pattern with cueing or instruction, they are likely <b>unable to fractionate</b> and are <b>synergistically bound</b>. {{quinn21,u_exam}}",
  [["verbal first",["verbal"]],["tactile second",["tactile"]],["physical assistance last",["physical","assist"]],["note how much / where",["where","how much","amount"]],["synergistically bound / can't fractionate",["synerg","fractionat","pattern"]]],4),
 (3,"How do you administer and document the MoCA?","Screens for MCI across 7 domains (short-term memory, visuospatial, executive, attention/working memory, language, orientation); does not diagnose. <b>&lt; 26</b> = positive screen (sens 51%, spec 96%, LR 13.5). Add 1 point if &lt; 12 years of education; MoCA Blind is out of 22. Document “positive (or negative) screen for mild cognitive impairment”, never “has MCI”. {{krish17,u_exam}}",
  [["screen, not diagnosis",["screen","not diagnos","doesn't diagnose","does not diagnose"]],["cut-off < 26",["26"]],["+1 if < 12 y education",["12","education"]],["MoCA Blind /22",["blind","22"]],["document 'positive screen'",["positive screen","negative screen"]],["domains",["memory","visuospatial","executive","attention","language","orientation"]]],4),
 (3,"Describe the head impulse test and dynamic visual acuity test and how to interpret each.","<b>HIT:</b> sit lower than the patient; head flexed 30°; eyes on your nose; after slow movements, a quick, small (5–10°) unexpected rotation. A corrective saccade back to target = likely peripheral vestibular loss on the side of the head turn (head R, eyes correct L → +R HIT). <b>DVA:</b> static acuity first; flex 30° and oscillate at 2 Hz, 10–20° each way; a drop of ≥ 3 lines = VOR impairment. {{u_cn}}",
  [["30° flexion",["30"]],["quick 5–10° rotation",["5-10","5–10","quick","small"]],["corrective saccade",["saccade"]],["side of head turn",["side of","direction of","toward the turn","turned"]],["2 Hz oscillation",["2 hz","2hz"]],["≥ 3 lines = VOR impairment",["3 line","three line","3 or more","vor"]]],5),
 (3,"Explain Weber and Rinne testing and interpretation.","<b>Weber:</b> 256/512 Hz fork on the vertex; normal = midline; lateralization = ipsilateral conductive or contralateral sensorineural loss. <b>Rinne:</b> fork on the mastoid, then 2.5 cm from the ear; normal = air louder than bone; bone louder/longer = conductive hearing loss. {{u_cn}}",
  [["Weber on vertex",["vertex","top of"]],["midline = normal",["midline"]],["ipsilateral conductive / contralateral sensorineural",["conductive","sensorineural"]],["Rinne mastoid then ear",["mastoid"]],["air > bone normal",["air"]],["bone > air = conductive",["bone"]]],5),
 (4,"Compare spasticity and rigidity, and describe how to test and document tone.","<b>Spasticity:</b> velocity/amplitude-dependent, catch or clasp-knife, often unequal in agonist/antagonist, pyramidal (corticoreticulospinal). <b>Rigidity:</b> constant through ROM, equal in both (lead pipe, cogwheel), extrapyramidal/basal ganglia. Test supported supine; slow stretch for tone, quick stretch from the shortened range for spasticity; less-affected side first; grade with MAS; document the <b>muscle group</b>. {{u_exam,bohan87}}",
  [["velocity-dependent",["velocity"]],["clasp-knife / catch",["clasp","catch"]],["pyramidal / corticospinal",["pyramidal","cortico"]],["rigidity constant / lead pipe / cogwheel",["constant","lead pipe","cogwheel"]],["basal ganglia / extrapyramidal",["basal","extrapyramidal"]],["quick stretch from shortened range",["quick","fast","short"]],["MAS",["ashworth","mas"]],["muscle group, not motion",["muscle group","flexors","extensors"]]],6),
 (4,"Describe the UMCT: purpose, test parts and how flexion is graded.","Tests voluntary control of the hemiparetic LE in upright; indicated for CNS lesions with patterned movement or spasticity. <b>Flexion control</b> (hip, knee, ankle DF) reflects swing; <b>extension control</b> (hip, knee, ankle PF) reflects stance. Two practice trials, one graded trial. Hip/knee flexion: <b>Weak</b> &lt; 30° or &gt; 10 s for 3 reps; <b>Moderate</b> 30–60° ×3 in 10 s; <b>Strong</b> &gt; 60° ×3 in 10 s. DF has no Moderate grade. {{hislop95,u_exam}}",
  [["upright / hemiparetic LE",["upright","hemipar","standing"]],["flexion = swing",["swing"]],["extension = stance",["stance"]],["one graded trial",["one graded","1 graded","single trial","one trial"]],["weak < 30°",["30"]],["strong > 60°",["60"]],["within 10 s",["10 s","10 sec","ten sec","10s"]]],5),
 (4,"List the UE flexion and extension synergy components and their strongest parts.","<b>Flexion:</b> scapular elevation/retraction, shoulder abduction/ER, <b>elbow flexion</b> (strongest), forearm supination, wrist and finger flexion. <b>Extension:</b> scapular protraction, <b>shoulder adduction</b> and IR, elbow extension, <b>forearm pronation</b> (adduction and pronation strongest), wrist and finger flexion. {{u_exam,sathian11}}",
  [["scap elevation/retraction",["elevation","retraction"]],["shoulder abd/ER",["abduction","external rot","er"]],["elbow flexion strongest",["elbow flex"]],["supination",["supination"]],["protraction",["protraction"]],["shoulder add/IR",["adduction","internal rot","ir"]],["pronation",["pronation"]],["wrist/finger flexion in both",["wrist","finger"]]],6),
 (5,"Differentiate aphasia, apraxia of speech and dysarthria.","<b>Aphasia:</b> acquired disruption of language (reading, writing, listening, speaking), typically left hemisphere; fluent or non-fluent. <b>Apraxia of speech:</b> motor planning deficit; inconsistent errors, groping, high awareness; not from weakness. <b>Dysarthria:</b> motor execution deficit from weakness, tone or incoordination; slurred; consistent errors; affects respiration, phonation, articulation, prosody, resonance. {{u_slp}}",
  [["aphasia = language",["language"]],["left hemisphere",["left"]],["apraxia = planning",["plan","programm"]],["inconsistent / groping",["inconsisten","grop"]],["dysarthria = execution",["execution","weakness","muscle"]],["consistent / slurred",["consistent","slur"]]],5),
 (5,"List dysphagia warning signs and when you would refer to SLP.","Warning signs: coughing/throat clearing, <b>wet voice</b> after swallowing, fevers after eating/drinking, congestion or wheezing after intake, drooling, unintentional weight loss, long meals, recurrent pneumonia, regurgitation, food sticking, fear of eating or pills. Remember ~50% aspirate silently. Refer with a known neuro diagnosis, signs of aspiration, excessive throat clearing, or unexpected cognitive-communication behavior. {{u_slp}}",
  [["coughing / throat clearing",["cough","throat clear"]],["wet voice",["wet"]],["fever",["fever"]],["recurrent pneumonia / infections",["pneumonia","infection"]],["weight loss",["weight"]],["silent aspiration",["silent"]],["refer with known dx or signs",["refer","slp","speech"]]],5),
 (6,"Describe four PNF techniques with their goal and verbal cue.","<b>Rhythmic initiation</b> (PROM → AAROM → AROM → resisted → I; initiation, teach the pattern; 'relax and let me move you… now move with me'). <b>Dynamic reversals</b> (alternating concentric, no relaxation; mobility, strength; 'push against me'). <b>Rhythmic stabilization</b> (alternating isometrics; stability; 'don't let me move you'). <b>Combination of isotonics</b> (concentric-isometric-eccentric; controlled mobility; 'push, hold, let me move you slowly'). <b>Replication</b> (start at the end; teach the final position). <b>Repeated stretch</b> (3–4 per pattern). {{u_ther}}",
  [["rhythmic initiation",["rhythmic initiation"]],["dynamic reversals",["reversal"]],["rhythmic stabilization",["stabiliz"]],["combination of isotonics",["isotonic"]],["replication",["replicat"]],["repeated stretch",["repeated"]],["goals: mobility vs stability",["mobility","stability"]]],5),
 (6,"Give HIIT dosing after stroke using FITT.","<b>F:</b> 2–5 days/week for 2–4 weeks. <b>I:</b> fastest safe walking speed, or 85–95% HRR, or power at 90–100% VO<sub>2</sub>peak. <b>T:</b> 25–30 min; burst:recovery 30 s:30–60 s up to 3 min:4 min. <b>T:</b> treadmill if safe or recumbent stepper, monitoring for hypotension. {{crozier18}}",
  [["2–5 days/week",["2-5","2–5"]],["2–4 weeks",["2-4","2–4"]],["85–95% HRR / fastest safe speed",["85","95","fastest"]],["25–30 min",["25","30 min"]],["burst:recovery",["30 s","burst","recovery","interval"]],["treadmill / stepper",["treadmill","stepper"]],["hypotension",["hypotens"]]],5),
 (7,"Describe the four phases of sit to stand with the key muscle activity.","<b>I Flexion-momentum</b> (initiation to just before lift-off): iliopsoas, abs, tibialis anterior concentric; erector spinae eccentric. <b>II Momentum-transfer</b> (lift-off to max DF): hip and knee extensors; highest GRF at lift-off. <b>III Extension</b> (max DF until hips stop extending): co-activation of hip/knee extensors, abdominals. <b>IV Stabilization:</b> co-contraction for upright. {{schenk90,fell18}}",
  [["flexion-momentum",["flexion-momentum","flexion momentum","flexion"]],["momentum-transfer / lift-off",["transfer","lift"]],["extension",["extension"]],["stabilization",["stabiliz"]],["tibialis anterior / iliopsoas",["tibialis","iliopsoas","psoas"]],["erector spinae eccentric",["erector","eccentric"]],["highest GRF at lift-off",["ground reaction","grf","highest"]]],5),
 (7,"How would you use bridging for both function and strengthening? Include at least two parameter changes.","Bridging feeds tasks like pulling up pants and scooting. Strengthen with combination of isotonics (resist the lift, hold, lower slowly against your push) or rhythmic stabilization in the hold. Parameters: feet closer to the pelvis reduces hamstring activity (and cramps); heel lift or ankle DF increases glute max; single-leg bridge increases trunk co-activation, more with hip abduction; unstable surfaces or vibration add challenge. {{colonna25,yoon18,u_roll}}",
  [["functional use (pants, scooting)",["pants","scoot","function"]],["combination of isotonics",["isotonic","concentric","eccentric"]],["rhythmic stabilization",["stabiliz"]],["feet closer = less HS",["closer","hamstring"]],["heel lift / DF = glute max",["heel","glute","dorsiflex"]],["single leg = trunk",["single","one leg","trunk"]]],4),
 (8,"Outline your approach to a hypotonic hemiplegic UE in the first week after stroke.","Early mobility in the neuroplasticity window; prevent shoulder complications, contractures and learned non-use. Positioning and handling (support the shoulder in bed and chair), ROM respecting scapulohumeral rhythm (no ROM &gt; 90° unless facilitating upward rotation and ER; max 140°), weight bearing with facilitation, strengthening from the less-involved UE → bilateral → involved. Work the hand early. Consider FES for subluxation; slings are likely not beneficial. {{u_ue1,u_ue2,ada05}}",
  [["early mobility",["early"]],["prevent learned non-use",["non-use","nonuse"]],["positioning / handling",["position","handling"]],["90° / scapulohumeral rhythm",["90","scapulohumeral","rhythm"]],["weight bearing",["weight bear","weight-bear"]],["less-involved → bilateral → involved",["bilateral","less involved","less-involved"]],["FES / slings",["fes","sling"]]],5),
 (8,"What does the evidence say about strengthening a spastic limb, and what are appropriate goals?","Weakness affects function more than spasticity; resistance training improves strength, gait speed, function and QOL <b>without exacerbating spasticity</b>, and may benefit spasticity. Goals must be patient-centered and functional, never “decrease spasticity”. Treat spasticity when it interferes with function, is painful, or causes contracture or skin breakdown. {{ross07,pak08,chacon24,gelber99}}",
  [["no exacerbation of spasticity",["without","not exacerbat","doesn't worsen","does not worsen","no increase"]],["improves strength / function",["strength","function"]],["weakness matters more",["weakness"]],["goals functional / patient-centered",["functional","patient-centered","patient centered"]],["treat when it interferes / pain / contracture",["interfere","pain","contracture","skin"]]],4),
 (9,"What belongs in each part of a neuro treatment SOAP note?","<b>S:</b> what the patient says at the start. <b>O:</b> chronological; vitals with reasons; movement analysis; task, MC, VC, direction of force, reps, assist, setup, equipment, outcome; show skilled PT and progress. <b>A:</b> professional judgment of progress, factors helping or interfering, not a summary of O (safety, fall risk, caregiver burden). <b>P:</b> what you'll do next visit. {{u_soap}}",
  [["S = patient's words",["patient says","report","consent"]],["O chronological",["chronolog"]],["MC / VC / assist / reps",["cue","assist","reps","vc","mc"]],["A = judgment, not summary",["judgment","judgement","not a summary","progress"]],["safety / fall risk / caregiver",["safety","fall","caregiver"]],["P = next visit",["next"]]],5),
]

MTF = [
 ("EDGE documents are produced by the ANPT.",1,1),
 ("The MCID is the smallest change that exceeds measurement error.",0,1),
 ("Anticipated problems require prevention and education.",1,1),
 ("The systems review includes communication, affect, cognition and learning style.",1,1),
 ("PSFS MCID in stroke is 2.5 points.",0,2),
 ("Walking is a continuous task.",1,2),
 ("When regressing a task, add physical assistance before a tactile cue.",0,2),
 ("Rolling is one of the 6 ANPT core tasks for movement analysis.",0,2),
 ("A lethargic patient falls back asleep easily but shows awareness.",1,3),
 ("A MoCA score below 26 means the patient has mild cognitive impairment.",0,3),
 ("On the head impulse test, a corrective saccade indicates likely vestibular loss on the side of the head turn.",1,3),
 ("With a CN XII lesion, the tongue deviates away from the lesion.",0,3),
 ("Rigidity is velocity-dependent.",0,4),
 ("MMT is not appropriate for a muscle that moves in a pattern.",1,4),
 ("Ankle dorsiflexion on the UMCT has a Moderate grade.",0,4),
 ("For a unilateral sensory deficit, test the intact side first.",1,4),
 ("Apraxia of speech errors are consistent across contexts.",0,5),
 ("About half of people with dysphagia may aspirate silently.",1,5),
 ("Stroke is the most common cause of neurogenic dysphagia.",1,5),
 ("In MS, fatigue is a reason to avoid exercise intensity.",0,6),
 ("Rhythmic stabilization allows motion between contractions.",0,6),
 ("Moving the feet closer to the pelvis increases hamstring activation in a bridge.",0,7),
 ("Maximum dorsiflexion in stand to sit occurs just before the buttocks touch the surface.",1,7),
 ("Slings are likely not beneficial for the hemiplegic shoulder.",1,8),
 ("Resistance training worsens spasticity.",0,8),
 ("The assessment section should summarize the objective section.",0,9),
]
MBL = [
 ("EDGE stands for Evaluation Database to Guide ___.",["effectiveness"],1),
 ("MCID = minimal clinically important ___.",["difference"],1),
 ("PSFS MDC in stroke is ___ points.",["1.94"],2),
 ("The first movement continuum phase is initial ___.",["conditions","condition"],2),
 ("The MoCA cut-off: a score below ___ is a positive screen.",["26"],3),
 ("Coma corresponds to a GCS below ___.",["8"],3),
 ("Intact convergence: focus up to ___ inches from the nose.",["4"],3),
 ("DVA: a drop of ___ or more lines indicates VOR impairment.",["3","three"],3),
 ("Rigidity described as 'lead pipe' or '___'.",["cogwheel","cog wheel"],4),
 ("The strongest component of the UE flexion synergy is elbow ___.",["flexion"],4),
 ("FMA UE total MDC = ___ points.",["3.2"],4),
 ("Vibration is tested with a ___ Hz tuning fork.",["128"],4),
 ("Short-term memory holds 7 ± ___ items.",["2","two"],5),
 ("Swapping 'table' for 'bed' is a ___ paraphasia.",["semantic"],5),
 ("HIIT sessions after stroke last about 25–___ minutes.",["30"],6),
 ("Limit repeated stretch to 3–___ per pattern.",["4","four"],6),
 ("People post-stroke took about ___ times longer to roll.",["3","three"],7),
 ("FES for subluxation uses 2.5 s on and ___ s off.",["2.5"],8),
 ("Without facilitating rhythm, avoid shoulder ROM above ___ degrees.",["90"],8),
]
MM = [
 (3,'Cranial nerve tests',[('CN I','Identify a smell, one nostril at a time'),('CN II','Snellen acuity and confrontation fields'),('CN VIII','Weber, Rinne and head impulse test'),('CN XI','Shoulder shrug and resisted head rotation')]),
 (4,'Motor exam tools',[('Modified Ashworth Scale','Tone and spasticity'),('UMCT','Upright LE control in hemiparesis'),('Fugl-Meyer','Patterned vs selective movement'),('Rebound test','Resisted elbow flexion, sudden release')]),
 (5,'Communication terms',[('Anomia','Difficulty retrieving words'),('Neologism','Novel, unrecognizable words'),('Telegraphic speech','Omits function words'),('Confabulation','Unintentional fabricated information')]),
 (6,'PNF techniques',[('Rhythmic initiation','PROM → AAROM → AROM → resisted'),('Rhythmic stabilization','Alternating isometrics, no motion'),('Combination of isotonics','Concentric, hold, eccentric'),('Replication','Start at the end position')]),
 (8,'UE interventions',[('Cyclic NMES','Preset schedule, no active effort'),('McConnell tape','Alignment reminder'),('Resting hand splint','Night use in a functional position'),('Mental practice','Rehearse the task mentally')]),
]
SAPOOL = list(range(len(SA)))

GAPS = [
 ('Studies named without a full reference', 'The bridging study on a mat, air cushion and whole-body vibration is cited only as "Yang &amp; Uhm 2020", and the sling evidence also names "Iruthayarajah et al., 2019" without a full citation. Neither is in the reference list; confirm them before citing.'),
 ('MoCA score of exactly 26', 'The cut-off is given as &lt; 26 positive and &gt; 26 negative. By the &lt; 26 rule, 26 is a negative screen, but the wording leaves it unstated.'),
 ('Visual field figure labels', 'The chiasmal defect is labeled "bipolar hemianopia" in the source figure, and the optic radiation lesions are paired with quadrant cuts as labeled there. Check these pairings against a neuroanatomy text.'),
 ('Synergy tables vs bullet lists', 'The LE flexion synergy lists "toe extension" in one place and toe dorsiflexion in the table; ankle inversion appears in the bullet lists but not the table. They describe the same pattern; use one wording consistently.'),
 ('Fell et al. publisher', 'Lifespan Neurorehabilitation (Fell, Lunnen, Rauk; 2018) is cited with two different publishers in the source material. The reference list uses the verified publisher.'),
 ('Unfilled prompts', 'Several prompts are posed as open problem-solving questions without answers: variations for supine to sit and sit to stand that add assistance or challenge, the benefits of transferring toward the more involved side, and how to train floor transfers for the case with L hemiplegia.'),
]
