import type { MovementExercise } from "@/lib/movement-lab/types";

/** Ankle and foot. Carries the full calf-loading ladder (double-leg raise → single-leg →
 *  eccentric heel drop) that the Achilles tendinopathy protocol is built on, plus the
 *  four-direction band series that every ankle sprain program uses. */
export const ANKLE_FOOT_EXERCISES: MovementExercise[] = [
  {
    id: "ankle-pumps",
    name: "Ankle Pumps",
    aka: ["Foot pumps", "Ankle dorsiflexion and plantarflexion"],
    region: "Ankle & Foot",
    category: "Mobility",
    positions: ["Supine", "Seated"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected"],
    targets: ["Calf muscles", "Tibialis anterior", "Ankle joint"],
    indications: ["Post-operative circulation", "Ankle swelling", "Immobilisation or reduced walking", "Early ankle sprain management"],
    setup: "Lie or sit with the leg supported and, where swelling is present, elevated above heart height.",
    steps: [
      "Point the toes away from the body as far as is comfortable.",
      "Then pull the toes back toward the shin as far as is comfortable.",
      "Move through the full comfortable range each way.",
      "Keep the movement at the ankle, not the whole leg.",
    ],
    dosage: { sets: "1", reps: "20–30", frequency: "Every hour while awake early on, then several times a day" },
    cue: "“Point and flex your foot like you're pressing and releasing a pedal — big, slow movements.”",
    patientInstructions:
      "Lie or sit with your leg supported, raised on pillows if it is swollen. Point your toes away from you, then pull them back toward your shin. Twenty to thirty times, every hour while you are awake in the first days, then a few times a day after that.",
    commonErrors: [
      "Tiny movements that don't reach the end of the range",
      "Moving the whole leg rather than the ankle",
      "Forgetting to elevate when swelling is the problem",
    ],
    regression: "Smaller range, fewer repetitions, done more often.",
    progression: "Ankle Alphabet, then resisted band work.",
    precautions: [
      "Follow post-operative weight-bearing and movement restrictions.",
      "New calf pain, swelling, warmth or redness needs medical assessment, not more exercise.",
    ],
  },
  {
    id: "ankle-alphabet",
    name: "Ankle Alphabet",
    aka: ["Foot alphabet", "Ankle circles"],
    region: "Ankle & Foot",
    category: "Mobility",
    positions: ["Seated", "Supine"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Ankle joint", "Subtalar joint", "Ankle musculature"],
    indications: ["Ankle sprain", "Post-immobilisation stiffness", "General ankle mobility"],
    setup: "Sit with the leg supported and the foot free to move — off the edge of a bed or with the ankle resting on a rolled towel.",
    steps: [
      "Imagine drawing the letters of the alphabet in the air with the big toe.",
      "Move only at the ankle — the knee and hip stay still.",
      "Work through the letters at a steady, comfortable pace.",
      "Stop before the ankle becomes painful rather than completing the alphabet at all costs.",
    ],
    dosage: { sets: "1–2", reps: "One full alphabet", frequency: "2–3x/day" },
    cue: "“Write the alphabet in the air with your big toe — the letters have to come from your ankle, not your knee.”",
    patientInstructions:
      "Sit with your foot hanging free. Using your big toe as a pen, draw the letters of the alphabet in the air, moving only your ankle. Work through the whole alphabet, two or three times a day.",
    commonErrors: [
      "Moving the whole leg rather than the ankle",
      "Making the letters tiny",
      "Pushing through sharp pain to finish the alphabet",
    ],
    regression: "Do half the alphabet, or ankle circles only.",
    progression: "Add band resistance in the four cardinal directions.",
    precautions: [
      "Follow post-operative movement restrictions.",
      "Stop for sharp pain rather than completing the set.",
    ],
  },
  {
    id: "band-dorsiflexion",
    name: "Band Ankle Dorsiflexion",
    region: "Ankle & Foot",
    category: "Strength",
    positions: ["Seated", "Supine"],
    equipment: ["Resistance band"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Tibialis anterior", "Ankle dorsiflexors"],
    indications: ["Foot drop", "Ankle sprain rehabilitation", "Shin pain", "Post-immobilisation weakness"],
    setup: "Sit with the leg straight out. Anchor a band around a fixed object in front and loop the other end over the top of the foot.",
    steps: [
      "Start with the toes pointed away and the band under light tension.",
      "Pull the foot back toward the shin against the band.",
      "Hold briefly at the end of the range.",
      "Return slowly against the band rather than letting it pull the foot back.",
    ],
    dosage: { sets: "2–3", reps: "12–15", hold: "2 s", frequency: "Once daily", loadOrTempo: "2 s in, 3 s out" },
    cue: "“Pull your toes up toward your nose against the band, then let it back down slowly.”",
    patientInstructions:
      "Sit with your leg straight out. Loop a band over the top of your foot and anchor the other end to something solid in front of you. Pull your foot back toward your shin against the band, hold a moment, then let it out slowly. Twelve to fifteen repetitions.",
    commonErrors: [
      "Bending the knee to help",
      "Curling the toes rather than lifting the whole foot",
      "Letting the band snap the foot back down",
    ],
    regression: "Lighter band, or no band at all.",
    progression: "Heavier band, or progress to heel walking.",
    precautions: [
      "Follow post-operative restrictions.",
      "Anchor the band securely — a band that releases under tension can strike the face.",
    ],
  },
  {
    id: "band-plantarflexion",
    name: "Band Ankle Plantarflexion",
    region: "Ankle & Foot",
    category: "Strength",
    positions: ["Seated", "Supine"],
    equipment: ["Resistance band"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Gastrocnemius", "Soleus"],
    indications: ["Calf weakness", "Post-immobilisation", "Early Achilles loading (per protocol)", "Ankle sprain rehabilitation"],
    setup: "Sit with the leg straight out, a band looped around the ball of the foot and both ends held in the hands.",
    steps: [
      "Start with the foot pulled back toward the shin.",
      "Push the ball of the foot away against the band, pointing the toes.",
      "Hold briefly at the end of the range.",
      "Return slowly against the band.",
    ],
    dosage: { sets: "2–3", reps: "12–15", hold: "2 s", frequency: "Once daily", loadOrTempo: "2 s out, 3 s back" },
    cue: "“Push the band away like pressing a pedal, then let it come back slowly.”",
    patientInstructions:
      "Sit with your leg straight out and a band looped around the ball of your foot, holding both ends. Push your foot away from you against the band, hold a moment, then let it come back slowly. Twelve to fifteen repetitions.",
    commonErrors: [
      "Bending the knee to push harder",
      "Cramping in the calf from too much band tension",
      "Letting the band snap the foot back",
    ],
    regression: "Lighter band and fewer repetitions.",
    progression: "Double-leg heel raise, then single-leg.",
    precautions: [
      "Follow the surgeon's protocol after Achilles repair — calf loading is staged carefully.",
      "Stop for calf cramping and reduce the tension.",
    ],
  },
  {
    id: "band-inversion",
    name: "Band Ankle Inversion",
    region: "Ankle & Foot",
    category: "Strength",
    positions: ["Seated"],
    equipment: ["Resistance band"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Tibialis posterior", "Tibialis anterior"],
    indications: ["Posterior tibial tendon dysfunction", "Flat foot posture", "Ankle sprain rehabilitation"],
    setup: "Sit with the legs out and cross the involved foot over the other. Loop a band around the inside of the forefoot, anchored out to the involved side.",
    steps: [
      "Start with the foot turned slightly outward under band tension.",
      "Turn the sole of the foot inward against the band, as if trying to look at it.",
      "Keep the knee and hip still — the movement belongs to the ankle.",
      "Return slowly.",
    ],
    dosage: { sets: "2–3", reps: "12–15", frequency: "Once daily", loadOrTempo: "2 s in, 3 s out" },
    cue: "“Turn the sole of your foot inward like you're showing me the bottom of it — keep your knee still.”",
    patientInstructions:
      "Sit with your legs out in front and cross the sore foot over the other. Loop a band around the inside of your foot, anchored to the side. Turn the sole of your foot inwards against the band, keeping your knee still, then let it back slowly. Twelve to fifteen repetitions.",
    commonErrors: [
      "Rotating the whole leg at the hip instead of moving the ankle",
      "Using a band that is too heavy so the hip takes over",
      "Letting the band snap the foot back",
    ],
    regression: "Lighter band, smaller range.",
    progression: "Heavier band, or progress to single-leg heel raise with the heel guided inward.",
    precautions: [
      "Follow post-operative restrictions.",
      "Take care after a medial ankle injury — inversion loading may be limited early.",
    ],
  },
  {
    id: "band-eversion",
    name: "Band Ankle Eversion",
    region: "Ankle & Foot",
    category: "Strength",
    positions: ["Seated"],
    equipment: ["Resistance band"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Peroneus longus", "Peroneus brevis"],
    indications: ["Lateral ankle sprain", "Chronic ankle instability", "Peroneal weakness"],
    setup: "Sit with the legs out. Loop a band around the outside of the forefoot, anchored across to the opposite side.",
    steps: [
      "Start with the foot turned slightly inward under band tension.",
      "Turn the sole of the foot outward against the band.",
      "Keep the knee and hip still.",
      "Return slowly against the band.",
    ],
    dosage: { sets: "2–3", reps: "12–15", frequency: "Once daily", loadOrTempo: "2 s out, 3 s back" },
    cue: "“Turn the outside edge of your foot up toward the ceiling — knee stays completely still.”",
    patientInstructions:
      "Sit with your legs out in front. Loop a band around the outside of your foot, anchored across to the other side. Turn the sole of your foot outwards against the band, keeping your knee still, then let it back slowly. Twelve to fifteen repetitions.",
    commonErrors: [
      "Turning the whole leg out at the hip",
      "Lifting the toes instead of turning the foot",
      "Letting the band snap the foot back",
    ],
    regression: "Lighter band, smaller range.",
    progression: "Heavier band, then progress to single-leg balance and hop control work.",
    precautions: [
      "The key strengthening direction after a lateral ankle sprain — but follow the acute-phase timeline before loading it.",
      "Stop for sharp pain over the outside of the ankle.",
    ],
  },
  {
    id: "double-leg-heel-raise",
    name: "Double-Leg Heel Raise",
    aka: ["Calf raise", "Two-leg heel raise"],
    region: "Ankle & Foot",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Table or counter"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Gastrocnemius", "Soleus"],
    indications: ["Calf weakness", "Achilles tendinopathy", "Post-immobilisation", "Return to walking"],
    setup: "Stand with the feet hip-width apart, holding a counter lightly for balance.",
    steps: [
      "Rise up onto the balls of both feet as high as possible.",
      "Keep the weight even across the front of both feet, not rolled to the outside.",
      "Hold briefly at the top.",
      "Lower slowly all the way down.",
    ],
    dosage: { sets: "3", reps: "12–15", hold: "1–2 s", frequency: "Once daily", loadOrTempo: "2 s up, 3 s down" },
    cue: "“All the way up onto your toes, then lower slowly — don't let your ankles roll outward.”",
    patientInstructions:
      "Stand with your feet hip-width apart, holding a counter lightly. Rise up onto the balls of your feet as high as you can, hold a second, then lower slowly all the way down. Twelve to fifteen repetitions.",
    commonErrors: [
      "Rolling the weight onto the outside edges of the feet",
      "Dropping down rather than lowering slowly",
      "Leaning heavily on the counter",
      "Not going all the way up",
    ],
    regression: "Seated heel raise, or do it with more weight through the hands.",
    progression: "Single-Leg Heel Raise, then add load, then heel raises off a step for greater range.",
    precautions: [
      "Follow post-operative loading timelines after Achilles repair.",
      "Stop for sharp pain in the Achilles or the back of the heel.",
    ],
  },
  {
    id: "single-leg-heel-raise",
    name: "Single-Leg Heel Raise",
    region: "Ankle & Foot",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Table or counter", "Step or stairs"],
    difficulty: 4,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Gastrocnemius", "Soleus", "Ankle stabilisers"],
    indications: ["Achilles tendinopathy", "Calf strength deficit", "Return to running", "Late-stage ankle rehabilitation"],
    setup: "Stand on one foot, holding a counter lightly for balance. Later, stand with the forefoot on the edge of a step.",
    steps: [
      "Rise up onto the ball of the standing foot as high as possible.",
      "Keep the ankle from rolling outward — the heel should lift straight up.",
      "Hold briefly at the top.",
      "Lower slowly and fully.",
    ],
    dosage: { sets: "3", reps: "10–15 each side", frequency: "Once daily", loadOrTempo: "2 s up, 3 s down" },
    cue: "“Straight up, no rolling out to the little toe — and lower all the way down under control.”",
    patientInstructions:
      "Stand on one foot, holding a counter lightly for balance. Rise up onto the ball of that foot as high as you can, then lower slowly all the way down. Ten to fifteen repetitions on each leg.",
    commonErrors: [
      "Rolling out onto the outside of the foot",
      "Pushing through the hand on the counter",
      "Not reaching full height",
      "Dropping down quickly",
    ],
    regression: "Double-leg heel raise, or single-leg with more weight through the hands.",
    progression: "Off a step for greater range, then holding a weight, then eccentric heel drops.",
    precautions: [
      "Follow post-operative loading timelines.",
      "Needs adequate balance — use a stable support.",
      "Stop for sharp Achilles pain.",
    ],
  },
  {
    id: "seated-heel-raise",
    name: "Seated Heel Raise",
    aka: ["Soleus raise", "Bent-knee calf raise"],
    region: "Ankle & Foot",
    category: "Strength",
    positions: ["Seated"],
    equipment: ["Chair", "Weight"],
    difficulty: 2,
    phases: ["Acute / Protected", "Subacute / Restore", "Strengthening"],
    targets: ["Soleus"],
    indications: ["Achilles tendinopathy", "Calf weakness", "Early loading where standing raises are too much", "Post-immobilisation"],
    setup: "Sit on a firm chair with the feet flat and the knees bent to about 90 degrees. A weight can rest on the thighs later.",
    steps: [
      "Lift both heels off the floor, rising onto the balls of the feet.",
      "Keep the knees bent throughout — that is what biases the soleus.",
      "Hold at the top.",
      "Lower slowly.",
    ],
    dosage: { sets: "3", reps: "15–20", hold: "1–2 s", frequency: "Once daily", loadOrTempo: "Add weight on the thighs as it becomes easy" },
    cue: "“Knees stay bent — that's what makes this hit the deeper calf muscle rather than the one you can see.”",
    patientInstructions:
      "Sit on a firm chair with your feet flat and knees bent. Lift both heels off the floor onto the balls of your feet, hold a second, then lower slowly. Fifteen to twenty repetitions. Once it feels easy, rest a weight on your thighs.",
    commonErrors: [
      "Straightening the knees, which shifts the work to the calf muscle above",
      "A small range that never reaches full height",
      "Dropping the heels down",
    ],
    regression: "Fewer repetitions with no added weight.",
    progression: "Add weight on the thighs, then move to standing double-leg then single-leg raises.",
    precautions: [
      "Follow post-operative loading timelines.",
      "Stop for sharp Achilles pain.",
    ],
  },
  {
    id: "eccentric-heel-drop",
    name: "Eccentric Heel Drop",
    aka: ["Alfredson heel drop", "Eccentric calf lowering"],
    region: "Ankle & Foot",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Step or stairs", "Table or counter"],
    difficulty: 4,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Achilles tendon", "Gastrocnemius", "Soleus"],
    indications: ["Mid-portion Achilles tendinopathy", "Calf strength deficit", "Return to running"],
    setup: "Stand with the forefeet on the edge of a step and the heels hanging off, holding a rail.",
    steps: [
      "Rise up onto both toes, or step up using the uninvolved leg.",
      "Shift the weight onto the involved leg alone.",
      "Lower that heel slowly below the level of the step, as far as is comfortable.",
      "Use the other leg to come back up — the lowering is the exercise, the raising is not.",
      "Do one set with the knee straight and one with the knee slightly bent.",
    ],
    dosage: { sets: "3", reps: "15", frequency: "2x/day", loadOrTempo: "3–4 s lowering; raise with the other leg" },
    cue: "“Go up on both, come down slowly on the sore one — the slow lowering is the whole exercise.”",
    patientInstructions:
      "Stand with the front of your feet on the edge of a step, heels hanging off, holding a rail. Go up onto your toes using both legs, then shift your weight onto the sore leg and lower that heel slowly below the step. Use your other leg to come back up. Fifteen repetitions with the knee straight and fifteen with the knee slightly bent, three sets, twice a day. Some discomfort in the tendon during this is expected — it should settle within twenty-four hours. If it is getting worse day to day, tell your therapist.",
    commonErrors: [
      "Raising up on the involved leg, which is not part of the exercise",
      "Lowering quickly instead of over three or four seconds",
      "Skipping the bent-knee set, which targets a different part of the calf",
      "Stopping at the first sign of tendon discomfort — some is expected here",
    ],
    regression: "Do it on flat ground rather than a step, or double-leg lowering.",
    progression: "Add a weighted backpack, in small increments.",
    precautions: [
      "Not appropriate for insertional Achilles pain in the same full-range form — the below-step position often aggravates it, so the range is kept above neutral.",
      "Not appropriate after Achilles rupture or repair until the surgeon permits it.",
      "Expect some tendon discomfort; symptoms should settle within a day. Worsening day to day means reduce the load.",
      "Needs a secure step and handrail.",
    ],
    note: "The eccentric heel-drop programme (three sets of fifteen, twice daily, knee straight and knee bent) described by Alfredson for mid-portion Achilles tendinopathy.",
  },
  {
    id: "gastrocnemius-stretch",
    name: "Gastrocnemius Stretch",
    aka: ["Straight-knee calf stretch", "Wall calf stretch", "Runner's stretch"],
    region: "Ankle & Foot",
    category: "Flexibility",
    positions: ["Standing"],
    equipment: ["Wall"],
    difficulty: 1,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Gastrocnemius", "Achilles tendon"],
    indications: ["Calf tightness", "Limited ankle dorsiflexion", "Plantar heel pain", "Achilles tendinopathy"],
    setup: "Stand facing a wall with both hands on it. Step the leg to be stretched back, keeping that heel down and the toes pointing straight at the wall.",
    steps: [
      "Keep the back knee completely straight.",
      "Bend the front knee and lean toward the wall until a stretch is felt in the upper calf.",
      "Keep the back heel flat on the floor and the foot pointing forward, not turned out.",
      "Hold, breathing normally.",
    ],
    dosage: { sets: "3", reps: "1 each side", hold: "30 s", frequency: "1–2x/day" },
    cue: "“Back knee locked straight, back heel glued to the floor, and lean in from the ankle — toes point at the wall.”",
    patientInstructions:
      "Stand facing a wall with your hands on it. Step one leg back, keeping that knee straight, that heel on the floor, and your toes pointing at the wall. Bend your front knee and lean towards the wall until you feel a stretch in your upper calf. Hold thirty seconds. Three times on each side.",
    commonErrors: [
      "Letting the back heel lift off the floor",
      "Bending the back knee, which turns it into the soleus stretch",
      "Turning the back foot outward, which reduces the stretch and stresses the arch",
    ],
    regression: "Reduce the lean, or do it seated with a strap around the foot.",
    progression: "Hold longer, step further back, or do it with the forefoot on a wedge.",
    precautions: [
      "Follow post-operative restrictions after Achilles surgery.",
      "Stop for sharp pain in the tendon or the back of the heel.",
    ],
  },
  {
    id: "soleus-stretch",
    name: "Soleus Stretch",
    aka: ["Bent-knee calf stretch"],
    region: "Ankle & Foot",
    category: "Flexibility",
    positions: ["Standing"],
    equipment: ["Wall"],
    difficulty: 1,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Soleus", "Achilles tendon"],
    indications: ["Limited ankle dorsiflexion", "Difficulty squatting or descending stairs", "Plantar heel pain", "Achilles tendinopathy"],
    setup: "Set up exactly as for the gastrocnemius stretch, standing facing a wall with one leg back.",
    steps: [
      "Bend the back knee while keeping that heel firmly on the floor.",
      "Sink the hips down and slightly forward until a stretch is felt low in the calf, near the ankle.",
      "Keep the back foot pointing straight forward.",
      "Hold, breathing normally.",
    ],
    dosage: { sets: "3", reps: "1 each side", hold: "30 s", frequency: "1–2x/day" },
    cue: "“Same position, but bend the back knee and sink down — you'll feel it much lower, close to your heel.”",
    patientInstructions:
      "Stand facing a wall with one leg stepped back. This time bend the back knee while keeping that heel firmly on the floor, and sink your weight down. You should feel a stretch low in your calf near your ankle. Hold thirty seconds. Three times on each side.",
    commonErrors: [
      "Letting the heel lift as the knee bends",
      "Not bending the knee enough to change where the stretch is felt",
      "Turning the foot outward",
    ],
    regression: "Do it in a half-kneeling position with the front foot flat and drive the knee forward over the toes.",
    progression: "Knee-to-Wall Ankle Mobilisation, which loads the same range in a weight-bearing position.",
    precautions: [
      "Follow post-operative restrictions.",
      "Stop for sharp pain at the back of the heel.",
    ],
  },
  {
    id: "knee-to-wall",
    name: "Knee-to-Wall Ankle Mobilisation",
    aka: ["Weight-bearing dorsiflexion", "Wall ankle mobilisation", "Lunge test drill"],
    region: "Ankle & Foot",
    category: "Mobility",
    positions: ["Half-kneeling", "Standing"],
    equipment: ["Wall"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Talocrural joint", "Posterior ankle capsule", "Soleus"],
    indications: ["Limited ankle dorsiflexion", "Post-ankle-sprain stiffness", "Squat depth restriction", "Post-immobilisation"],
    setup: "Stand facing a wall with the toes of the front foot a few centimetres from it, in a half-kneeling or split stance.",
    steps: [
      "Drive the front knee forward toward the wall, aiming to touch it with the kneecap.",
      "Keep the heel flat on the floor throughout — the heel lifting ends the range.",
      "Keep the knee tracking over the second toe, not falling inward.",
      "Return, then move the foot back a centimetre and repeat as range improves.",
    ],
    dosage: { sets: "2–3", reps: "10", hold: "2–3 s", frequency: "1–2x/day" },
    cue: "“Drive your knee at the wall over your second toe, and the second your heel lifts, that's your range.”",
    patientInstructions:
      "Stand facing a wall with the toes of one foot a few centimetres from it. Drive that knee forward toward the wall, trying to touch it, while keeping your heel flat on the floor. If the heel lifts, you have gone too far. Ten repetitions. As it improves, move your foot slightly further from the wall.",
    commonErrors: [
      "Letting the heel lift to reach the wall",
      "Letting the knee fall inward",
      "Rolling the arch flat to gain range",
    ],
    regression: "Start with the toes touching the wall and work outward from there.",
    progression: "Move the foot further from the wall; add a band mobilisation around the ankle if the therapist has prescribed one.",
    precautions: [
      "Follow post-operative weight-bearing restrictions.",
      "Stop for pinching at the front of the ankle, which is a joint response rather than a stretch.",
    ],
  },
  {
    id: "plantar-fascia-stretch",
    name: "Plantar Fascia Stretch",
    aka: ["Toe extension stretch", "Seated plantar fascia stretch"],
    region: "Ankle & Foot",
    category: "Flexibility",
    positions: ["Seated"],
    equipment: ["None", "Chair"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore", "Strengthening"],
    targets: ["Plantar fascia", "Intrinsic foot muscles"],
    indications: ["Plantar heel pain", "Plantar fasciopathy", "Morning first-step pain", "Foot stiffness"],
    setup: "Sit and cross the involved foot over the opposite knee so the sole is accessible.",
    steps: [
      "Hold the base of the toes and pull them back toward the shin until the arch tightens.",
      "Feel along the arch with the other thumb — the band should be firm and palpable.",
      "Hold, breathing normally.",
      "Release slowly.",
    ],
    dosage: { sets: "3", reps: "1", hold: "30 s", frequency: "3x/day, including before the first steps in the morning" },
    cue: "“Pull your toes back until you can feel the band in your arch go tight — and do this one before you get out of bed.”",
    patientInstructions:
      "Sit and cross the sore foot over your other knee. Hold the base of your toes and pull them back toward your shin until you feel the arch of your foot tighten. Hold thirty seconds, three times. Do this three times a day — and importantly, before you take your first steps in the morning.",
    commonErrors: [
      "Pulling on the ends of the toes rather than at their base",
      "Not pulling far enough to feel the arch band tighten",
      "Skipping the morning repetition, which is the one that matters most for first-step pain",
    ],
    regression: "A gentler pull with a shorter hold.",
    progression: "Add a rolling massage under the arch with a ball or frozen bottle after the stretch.",
    precautions: [
      "Stop for sharp pain rather than a stretch.",
      "New numbness or tingling in the foot needs assessment rather than more stretching.",
    ],
  },
  {
    id: "towel-scrunch",
    name: "Towel Scrunch",
    aka: ["Toe curls", "Towel curls"],
    region: "Ankle & Foot",
    category: "Strength",
    positions: ["Seated"],
    equipment: ["Towel or strap", "Chair"],
    difficulty: 1,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Toe flexors", "Intrinsic foot muscles"],
    indications: ["Foot intrinsic weakness", "Plantar heel pain", "Flat foot posture", "Post-immobilisation foot weakness"],
    setup: "Sit on a chair with a towel spread flat on the floor under the bare foot.",
    steps: [
      "Keep the heel planted on the floor.",
      "Scrunch the toes to draw the towel toward the foot.",
      "Release and reach the toes forward to grab the next section.",
      "Continue until the whole towel has been drawn in.",
    ],
    dosage: { sets: "2–3", reps: "1 full towel each side", frequency: "Once daily" },
    cue: "“Heel stays down and let your toes do the pulling — like your foot is grabbing the towel.”",
    patientInstructions:
      "Sit on a chair with a towel spread flat on the floor under your bare foot. Keeping your heel down, scrunch your toes to pull the towel toward you a little at a time until the whole towel is bunched up. Repeat two or three times on each foot.",
    commonErrors: [
      "Lifting the heel and dragging the towel with the whole foot",
      "Clawing so hard the toes cramp",
      "Doing it with shoes or socks on",
    ],
    regression: "Fewer repetitions and a smaller towel; add a light weight on the far end later.",
    progression: "Put a small weight on the far end of the towel, or progress to the Short Foot exercise.",
    precautions: [
      "Stop for toe cramping and rest.",
      "Not appropriate where a toe deformity makes clawing painful.",
    ],
  },
  {
    id: "short-foot",
    name: "Short Foot Exercise",
    aka: ["Arch doming", "Foot core activation"],
    region: "Ankle & Foot",
    category: "Motor Control",
    positions: ["Seated", "Standing"],
    equipment: ["None"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Intrinsic foot muscles", "Abductor hallucis", "Medial arch"],
    indications: ["Flat foot posture", "Plantar heel pain", "Chronic ankle instability", "Foot intrinsic weakness"],
    setup: "Sit with the bare foot flat on the floor, knee over the ankle. Progress to standing once it can be done seated.",
    steps: [
      "Keep the toes long and relaxed on the floor — they must not curl.",
      "Draw the ball of the foot gently toward the heel so the arch lifts and the foot 'shortens'.",
      "Hold the doming without clawing the toes or rolling the ankle.",
      "Relax fully.",
    ],
    dosage: { sets: "2–3", reps: "10", hold: "5–10 s", frequency: "Once daily" },
    cue: "“Keep your toes long and flat — pull the ball of your foot toward your heel so your arch lifts. Toes must not curl.”",
    patientInstructions:
      "Sit with your bare foot flat on the floor. Without curling your toes, draw the ball of your foot gently toward your heel so the arch of your foot lifts up. Hold five to ten seconds and relax. Ten repetitions. This one is hard to learn — expect it to take a few sessions.",
    commonErrors: [
      "Curling the toes, which is a different exercise entirely",
      "Rolling the ankle outward to lift the arch",
      "Pressing hard through the big toe",
      "Giving up in the first session — it usually takes practice to find",
    ],
    regression: "Do it seated with no weight through the foot, and use a hand under the arch for feedback.",
    progression: "Progress to standing, then single-leg standing, then during a step or a heel raise.",
    precautions: [
      "Stop for foot cramping and rest.",
      "Progress slowly where there is a rigid foot deformity.",
    ],
  },
];
