import type { MovementExercise } from "@/lib/movement-lab/types";

/** Back. The pulling musculature trained as muscle — lats, traps, rhomboids and the spinal
 *  extensors — rather than the spine itself, which the cervical, thoracic and lumbar files
 *  cover (see the note on MOVEMENT_REGIONS in types.ts for where the line sits). Ordered the
 *  way a back programme actually builds: unloaded extension and light rows first, then the
 *  bent-over and loaded pulling, then the hinge that loads the whole chain at once. */
export const BACK_EXERCISES: MovementExercise[] = [
  {
    id: "prone-back-extension",
    name: "Prone Back Extension",
    aka: ["Superman", "Floor back extension", "Prone extension hold"],
    region: "Back",
    category: "Strength",
    positions: ["Prone"],
    equipment: ["None"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Lumbar extensors", "Erector spinae", "Gluteus maximus", "Lower trapezius"],
    indications: ["Back extensor endurance deficit", "Postural fatigue", "Return to lifting and carrying", "General back conditioning"],
    setup: "Lie face down on a mat with the arms by the sides or reaching overhead, and a small pillow under the abdomen if that is more comfortable.",
    steps: [
      "Tuck the chin slightly so the neck stays in line with the spine.",
      "Lift the chest a few centimetres off the floor by squeezing the back and buttocks — this is a small movement, not a backbend.",
      "Hold, breathing normally.",
      "Lower under control and rest briefly between repetitions.",
      "Keep the legs down unless the exercise is specifically progressed to include them.",
    ],
    dosage: { sets: "2–3", reps: "8–10", hold: "5–10 s", frequency: "Daily or every other day", loadOrTempo: "Small range held well, rather than a large range" },
    cue: "“Lift your chest just a few centimetres and hold — this is a squeeze, not an arch.”",
    patientInstructions:
      "Lie face down with your arms by your sides and your chin tucked in. Lift your chest a small way off the floor by squeezing your back and bottom muscles, hold for five to ten seconds, then lower. Eight to ten repetitions. This should be a small movement — lifting higher does not make it better, and usually just makes your back ache.",
    commonErrors: [
      "Lifting far too high and arching the low back",
      "Tipping the head back rather than keeping the neck in line",
      "Holding the breath",
      "Adding the legs before the upper-body version is comfortable",
    ],
    regression: "Lift only the arms, or only the chest, through a smaller range; or hold the position for less time.",
    progression: "Reach the arms overhead, lift the legs as well, or move to the 45-Degree Back Extension.",
    precautions: [
      "Range is small on purpose: this is an endurance hold, and the extra range that feels like progress is where it starts provoking the low back.",
      "Not appropriate where lumbar extension is provocative, including many acute low back presentations and lumbar spinal stenosis.",
      "Stop for leg symptoms rather than continuing.",
      "Use a pillow under the abdomen if lying flat is uncomfortable, and skip it in later pregnancy.",
    ],
  },
  {
    id: "seated-row",
    name: "Seated Row",
    aka: ["Cable row", "Band seated row", "Horizontal row"],
    region: "Back",
    category: "Strength",
    positions: ["Seated"],
    equipment: ["Resistance band", "Weight", "Chair"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Latissimus dorsi", "Rhomboids", "Middle trapezius", "Posterior deltoid", "Biceps brachii"],
    indications: ["Back and scapular strength deficit", "Postural fatigue", "Return to pulling work", "General back conditioning"],
    setup: "Sit on a chair or the floor with the legs out in front, a resistance band looped around the feet or anchored in front at chest height, holding an end in each hand with the arms extended.",
    steps: [
      "Sit tall with the chest up and the low back in its natural curve.",
      "Begin the pull by drawing the shoulder blades back and together, before the elbows bend.",
      "Pull the hands toward the lower ribs, keeping the elbows close to the body.",
      "Pause briefly with the shoulder blades squeezed together.",
      "Return slowly, letting the shoulder blades travel forward again at the end without the trunk rounding.",
    ],
    dosage: { sets: "3", reps: "10–15", hold: "1–2 s", frequency: "2–3x/week", loadOrTempo: "2–3 s return; resistance light enough that the trunk stays still" },
    cue: "“Shoulder blades back first, then pull to your ribs — chest up, don't rock backwards.”",
    patientInstructions:
      "Sit tall with a band looped around your feet or anchored in front of you at chest height, holding an end in each hand with your arms straight. Pull your shoulder blades back, then pull your hands in toward your lower ribs, keeping your elbows close to your body. Squeeze for a second, then return slowly. Ten to fifteen repetitions, three sets. Keep your body still — if you have to rock backwards to pull, the band is too strong.",
    commonErrors: [
      "Rocking the trunk backwards to move the resistance",
      "Pulling with the arms before the shoulder blades engage",
      "Shrugging the shoulders toward the ears",
      "Rounding the low back on the return",
      "Letting the band snap the arms forward",
    ],
    regression: "A lighter band, sitting with the back supported, or rowing one arm at a time.",
    progression: "Heavier resistance, a longer squeeze at the end, or the Bent-Over Dumbbell Row for a gravity-loaded version.",
    precautions: [
      "Keep the trunk still: rocking turns a back exercise into a low back one.",
      "Check the anchor before pulling — a band that comes loose recoils toward the face.",
      "Follow the surgeon's protocol after shoulder or elbow surgery.",
      "Sit with back support where prolonged unsupported sitting is provocative.",
    ],
  },
  {
    id: "face-pull",
    name: "Face Pull",
    aka: ["Band face pull", "High row to face", "Rope face pull"],
    region: "Back",
    category: "Strength",
    positions: ["Standing", "Half-kneeling"],
    equipment: ["Resistance band"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Lower trapezius", "Middle trapezius", "Rhomboids", "Posterior deltoid", "Rotator cuff"],
    indications: ["Postural and scapular control", "Subacromial pain", "Rounded-shoulder posture with desk work", "Return to overhead work or sport"],
    setup: "Anchor a resistance band at about head height. Stand facing the anchor a step back, holding an end in each hand with the arms extended forward at shoulder height, palms facing in.",
    steps: [
      "Stand tall with the ribs down and a slight forward lean from the ankles.",
      "Pull the band toward the face, leading with the elbows and letting them travel out to the sides at about shoulder height.",
      "As the hands arrive either side of the face, rotate the forearms up so the knuckles finish pointing at the ceiling.",
      "Squeeze the shoulder blades back and down at the end position.",
      "Return slowly to the start with the arms extended.",
    ],
    dosage: { sets: "3", reps: "12–15", hold: "1–2 s", frequency: "Daily or every other day", loadOrTempo: "Light band, slow return; the external rotation at the end is the point" },
    cue: "“Pull to your face with your elbows high, then rotate your hands up like a goalpost.”",
    patientInstructions:
      "Anchor a band at about head height and stand facing it, holding an end in each hand with your arms out in front at shoulder height. Pull the band toward your face, letting your elbows go out to the sides, and finish by rotating your hands up so your knuckles point at the ceiling. Squeeze your shoulder blades, then return slowly. Twelve to fifteen repetitions. Use a light band — the rotation at the end is what makes this worth doing, and a heavy band makes it impossible.",
    commonErrors: [
      "A band so heavy the finishing rotation disappears",
      "Elbows dropping so it becomes an ordinary row",
      "Shrugging the shoulders up",
      "Leaning back rather than pulling with the arms and shoulder blades",
      "Rushing the return",
    ],
    regression: "A lighter band, pulling to chest height rather than face height, or the Band Pull-Apart.",
    progression: "A heavier band, a longer hold at the end, or half-kneeling to remove any help from the legs.",
    precautions: [
      "Reduce range or hold off with anterior shoulder instability, since the end position is external rotation near shoulder height.",
      "Follow the surgeon's protocol after rotator cuff repair or shoulder stabilisation.",
      "Check the anchor before pulling — a band released at head height recoils toward the eyes.",
      "Stop for pinching in the shoulder rather than working through it.",
    ],
  },
  {
    id: "shrug",
    name: "Shrug",
    aka: ["Shoulder shrug", "Trap shrug", "Dumbbell shrug"],
    region: "Back",
    category: "Strength",
    positions: ["Standing", "Seated"],
    equipment: ["Weight", "Resistance band"],
    difficulty: 2,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Upper trapezius", "Levator scapulae"],
    indications: ["Upper trapezius strength deficit", "Return to carrying and lifting", "Scapular elevation weakness", "Load tolerance after neck or shoulder injury"],
    setup: "Stand tall with a dumbbell in each hand at the sides, arms straight, or stand on a resistance band holding an end in each hand.",
    steps: [
      "Stand tall with the chin gently tucked and the arms hanging straight.",
      "Lift the shoulders straight up toward the ears.",
      "Pause briefly at the top.",
      "Lower slowly and fully, letting the shoulders settle all the way down before the next repetition.",
      "Keep the elbows straight and the head still — do not roll the shoulders.",
    ],
    dosage: { sets: "3", reps: "10–15", hold: "1–2 s", frequency: "2x/week", loadOrTempo: "2–3 s lowering; load that allows a full range without the neck bracing" },
    cue: "“Straight up toward your ears and slowly back down — no rolling, and keep your neck long.”",
    patientInstructions:
      "Stand tall holding a weight in each hand by your sides, or standing on a band. Lift your shoulders straight up toward your ears, pause, then lower them slowly all the way down. Ten to fifteen repetitions, three sets. Do not roll your shoulders round in circles, and keep your neck relaxed and long rather than poking your chin forward.",
    commonErrors: [
      "Rolling the shoulders in circles instead of lifting straight up",
      "Poking the chin forward or bracing the neck",
      "Bending the elbows, which turns it into a partial upright row",
      "A short range that never lets the shoulders settle fully down",
      "Loading heavily before the neck tolerates it",
    ],
    regression: "A lighter load, seated with the back supported, or shrugging with no weight at all.",
    progression: "Add load gradually, hold longer at the top, or move to loaded carries such as the Suitcase Carry.",
    precautions: [
      "Build load gradually where there is neck pain or a history of neck injury — the upper trapezius is often already overworked and irritable in those presentations.",
      "Stop for neck pain, headache or arm symptoms rather than working through them.",
      "Do not roll the shoulders under load.",
      "Follow the surgeon's protocol after neck or shoulder surgery.",
    ],
  },
  {
    id: "reverse-fly",
    name: "Reverse Fly",
    aka: ["Bent-over reverse fly", "Rear delt fly", "Reverse pec fly"],
    region: "Back",
    category: "Strength",
    positions: ["Standing", "Seated"],
    equipment: ["Weight", "Resistance band", "Chair"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Posterior deltoid", "Rhomboids", "Middle trapezius", "Infraspinatus"],
    indications: ["Scapular and posterior shoulder strength deficit", "Rounded-shoulder posture", "Return to overhead or pulling work", "Late-stage rotator cuff rehabilitation"],
    setup: "Hinge forward at the hips with a flat back until the trunk is at about 45 degrees, knees softly bent, a light dumbbell in each hand hanging beneath the shoulders. Sitting on a chair and leaning forward over the thighs is an easier alternative.",
    steps: [
      "Set the back flat and the ribs down before lifting — the hinge holds still throughout.",
      "With a slight bend in the elbows, lift both arms out to the sides.",
      "Lead with the elbows and squeeze the shoulder blades together at the top.",
      "Stop when the arms are level with the trunk rather than travelling above it.",
      "Lower slowly under control.",
    ],
    dosage: { sets: "3", reps: "12–15", hold: "1–2 s", frequency: "2–3x/week", loadOrTempo: "Light load, slow lowering; the squeeze matters more than the weight" },
    cue: "“Flat back, lead with your elbows, and squeeze your shoulder blades together at the top.”",
    patientInstructions:
      "Hinge forward from your hips with a flat back until your body is at about forty-five degrees, holding a light weight in each hand. With a slight bend in your elbows, lift your arms out to the sides, squeezing your shoulder blades together, then lower slowly. Twelve to fifteen repetitions, three sets. Use light weights — this is a small muscle group and heavy weights just turn it into a rowing motion.",
    commonErrors: [
      "Too heavy a load, which turns it into a row",
      "The low back rounding as the arms lift",
      "Standing up out of the hinge during the set",
      "Shrugging the shoulders toward the ears",
      "Swinging the weights up rather than lifting them",
    ],
    regression: "Sit and lean forward over the thighs, use a band instead of weights, or reduce the range.",
    progression: "Add load slowly, hold longer at the top, or move toward a horizontal trunk position.",
    precautions: [
      "Hold off or use the seated version with symptomatic low back pain — holding the bent-over position is often harder on the back than the arms.",
      "Stop for pinching at the top of the lift rather than working through it.",
      "Follow the surgeon's protocol after shoulder surgery.",
      "Keep the load light: heavy reverse flies are almost always rows in disguise.",
    ],
  },
  {
    id: "straight-arm-pulldown",
    name: "Straight-Arm Pulldown",
    aka: ["Straight-arm pullover", "Band lat pulldown", "Lat pushdown"],
    region: "Back",
    category: "Strength",
    positions: ["Standing", "Half-kneeling"],
    equipment: ["Resistance band", "Weight"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Latissimus dorsi", "Teres major", "Lower trapezius", "Triceps"],
    indications: ["Latissimus strength deficit", "Return to pulling and overhead work", "Scapular control in elevation", "Late-stage shoulder and back rehabilitation"],
    setup: "Anchor a resistance band above head height. Stand facing the anchor a step back, holding an end in each hand with the arms straight and raised in front at about head height.",
    steps: [
      "Stand tall with the ribs down and a slight hinge at the hips.",
      "Keeping the elbows straight or very slightly bent, sweep the arms down in an arc toward the thighs.",
      "Feel the pull along the side of the back rather than in the arms.",
      "Finish with the hands at the thighs and the shoulder blades drawn down.",
      "Return slowly along the same arc, letting the arms rise fully overhead again.",
    ],
    dosage: { sets: "3", reps: "12–15", frequency: "2–3x/week", loadOrTempo: "2–3 s return; light enough that the elbows do not start bending" },
    cue: "“Keep your arms straight and sweep them down in an arc — you should feel it along the side of your back, not in your arms.”",
    patientInstructions:
      "Anchor a band above head height and stand facing it a step back, holding an end in each hand with your arms straight out in front at about head height. Keeping your arms straight, sweep them down in an arc until your hands reach your thighs, then let them rise slowly back up. Twelve to fifteen repetitions, three sets. You should feel this down the sides of your back. If your elbows start bending, use a lighter band.",
    commonErrors: [
      "Bending the elbows, which turns it into a triceps pushdown",
      "Leaning the trunk forward to drive the arms down",
      "Shrugging the shoulders during the return",
      "Stopping the return short so the lats never lengthen",
      "A band heavy enough to make the straight-arm position impossible",
    ],
    regression: "A lighter band, a shorter range, or one arm at a time.",
    progression: "A heavier band, a longer pause at the bottom, or half-kneeling to remove help from the legs.",
    precautions: [
      "Needs comfortable overhead reach — the start position is full elevation, so reduce the range where that is painful or restricted.",
      "Follow the surgeon's protocol after shoulder surgery, particularly where overhead positions are staged.",
      "Check the overhead anchor before loading it.",
      "Stop for shoulder pinching at the top of the arc.",
    ],
  },
  {
    id: "bent-over-dumbbell-row",
    name: "Bent-Over Dumbbell Row",
    aka: ["Single-arm dumbbell row", "Supported row", "Bench row"],
    region: "Back",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Weight", "Chair", "Table or counter"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Latissimus dorsi", "Rhomboids", "Middle trapezius", "Posterior deltoid", "Biceps brachii"],
    indications: ["Back strength deficit", "Return to lifting and carrying", "Pulling strength asymmetry", "General back conditioning"],
    setup: "Place one hand and the same-side knee on a bench, chair seat or sturdy counter so the trunk is roughly horizontal with a flat back. Hold a dumbbell in the free hand, arm hanging straight down.",
    steps: [
      "Set the back flat and the hips square before the first repetition.",
      "Begin the pull by drawing the shoulder blade back, then bend the elbow.",
      "Pull the dumbbell up toward the hip, keeping the elbow close to the body.",
      "Keep the trunk still — the shoulders should not rotate open toward the working side.",
      "Lower slowly to full arm extension, letting the shoulder blade travel forward at the bottom.",
    ],
    dosage: { sets: "3", reps: "8–12 each side", frequency: "2–3x/week", loadOrTempo: "2–3 s lowering; load leaving 2–3 reps in reserve" },
    cue: "“Flat back, pull the weight to your hip — and don't let your shoulders twist open.”",
    patientInstructions:
      "Put one hand and the same-side knee on a bench or sturdy chair so your back is flat and roughly horizontal. Hold a weight in your other hand with your arm hanging straight down. Pull it up toward your hip, keeping your elbow close to your body, then lower it slowly. Eight to twelve repetitions each side, three sets. Keep your shoulders level — twisting your body to lift the weight means it is too heavy.",
    commonErrors: [
      "Rotating the trunk open to help the weight up",
      "Rounding the low back",
      "Pulling with the arm before the shoulder blade engages",
      "Shrugging the shoulder toward the ear",
      "Dropping the weight rather than lowering it",
    ],
    regression: "A lighter weight, the Seated Row, or a shorter range.",
    progression: "Add load, slow the lowering, or move to the Bent-Over Barbell Row for a two-armed unsupported version.",
    precautions: [
      "The support is what protects the low back here — set it up properly rather than hinging unsupported with a heavy weight.",
      "Reduce load or hold off with symptomatic low back pain.",
      "Use a bench or chair that cannot slide.",
      "Follow the surgeon's protocol after shoulder, elbow or spinal surgery.",
    ],
  },
  {
    id: "back-extension-45",
    name: "45-Degree Back Extension",
    aka: ["Roman chair back extension", "Hyperextension", "Bench back extension"],
    region: "Back",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Weight", "Chair"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Erector spinae", "Lumbar extensors", "Gluteus maximus", "Hamstrings"],
    indications: ["Back extensor endurance deficit", "Return to lifting and manual work", "Posterior chain conditioning", "Late-stage low back rehabilitation"],
    setup: "Set up in a back-extension bench with the pads just below the hip bones and the ankles secured, arms folded across the chest.",
    steps: [
      "Start with the body in a straight line from head to heels.",
      "Hinge forward at the hips, keeping the back flat rather than letting it round.",
      "Lower until a stretch is felt in the hamstrings, and no further than the point where the back would round.",
      "Squeeze the glutes to return to the straight-line position.",
      "Stop at straight — do not extend past it into an arch.",
    ],
    dosage: { sets: "3", reps: "10–15", frequency: "2x/week", loadOrTempo: "3 s lowering; bodyweight first, then a light weight held at the chest" },
    cue: "“Hinge from your hips with a flat back, and come up to straight — not past it.”",
    patientInstructions:
      "Set the pads just below your hip bones with your ankles secured, arms folded across your chest. Bend forward from your hips, keeping your back flat, until you feel a stretch in the back of your thighs. Squeeze your bottom to come back up until your body is straight. Stop at straight — do not arch backwards past it. Ten to fifteen repetitions, three sets.",
    commonErrors: [
      "Extending past straight into an arch at the top, which is where this exercise causes problems",
      "Rounding the low back on the way down",
      "Bouncing at the bottom of the movement",
      "Pads set too high, above the hip bones, which blocks the hinge",
      "Adding weight before the bodyweight version is controlled",
    ],
    regression: "Prone Back Extension on the floor, or a shorter range.",
    progression: "Hold a light weight at the chest, slow the lowering, or pause at the top.",
    precautions: [
      "Stop at straight: the extra range past neutral is where this loads the low back joints, and it adds nothing.",
      "Not appropriate where lumbar extension is provocative, including lumbar spinal stenosis and many acute presentations.",
      "Reduce range or hold off with symptomatic low back pain.",
      "Follow the surgeon's protocol after spinal surgery.",
    ],
  },
  {
    id: "bent-over-barbell-row",
    name: "Bent-Over Barbell Row",
    aka: ["Barbell row", "Pendlay row", "Bent-over row"],
    region: "Back",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Weight"],
    difficulty: 4,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Latissimus dorsi", "Rhomboids", "Middle trapezius", "Erector spinae", "Posterior deltoid", "Biceps brachii"],
    indications: ["Back strength deficit", "Return to heavy lifting and manual work", "Return to sport requiring pulling strength", "Late-stage back conditioning"],
    setup: "Stand with the feet hip-width apart, holding a barbell with an overhand grip a little wider than shoulder-width. Hinge at the hips with a flat back until the trunk is at about 45 degrees, knees softly bent, bar hanging at arm's length.",
    steps: [
      "Set the back flat and brace the trunk before the first repetition — this position must hold for the whole set.",
      "Begin the pull by drawing the shoulder blades back, then bend the elbows.",
      "Pull the bar toward the lower ribs or upper abdomen, keeping the elbows in.",
      "Keep the trunk angle fixed — the chest should not rise as the bar comes up.",
      "Lower under control to full arm extension without letting the back round.",
    ],
    dosage: { sets: "3", reps: "6–10", frequency: "2x/week", loadOrTempo: "2–3 s lowering; load leaving 2–3 reps in reserve, and well under what a supported row allows" },
    cue: "“Flat back locked in place — pull the bar to your stomach without letting your chest rise.”",
    patientInstructions:
      "Stand holding a barbell with your hands a little wider than your shoulders. Bend forward from your hips with a flat back until your body is at about forty-five degrees, with the bar hanging at arm's length. Pull it up to your stomach, keeping your elbows close, then lower it slowly. Six to ten repetitions, three sets. Your body should stay in the same bent-over position throughout — if you find yourself standing up to lift the bar, it is too heavy.",
    commonErrors: [
      "The trunk rising through the set so the last repetitions are nearly upright",
      "The low back rounding, especially on the last few repetitions",
      "Jerking the bar up with a leg drive",
      "Pulling to the chest rather than the abdomen, which flares the elbows",
      "Going heavier than the hinge position can be held for",
    ],
    regression: "Bent-Over Dumbbell Row with the trunk supported, or the Seated Row.",
    progression: "Add load in small increments, pause at the top, or slow the lowering further.",
    precautions: [
      "The unsupported hinge, not the pull, is the limiting factor — the set ends when the back stops staying flat, not when the arms tire.",
      "Reduce load or hold off with symptomatic low back pain, and where spinal loading is restricted.",
      "Earn it from the supported dumbbell row first.",
      "Follow the surgeon's protocol after spinal or shoulder surgery.",
    ],
  },
  {
    id: "conventional-deadlift",
    name: "Conventional Deadlift",
    aka: ["Deadlift", "Barbell deadlift", "Floor pull"],
    region: "Back",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Weight"],
    difficulty: 4,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Erector spinae", "Latissimus dorsi", "Gluteus maximus", "Hamstrings", "Quadriceps", "Trapezius", "Grip"],
    indications: ["Return to heavy lifting and manual work", "Posterior chain strength deficit", "Building load tolerance for the low back", "Late-stage back and hip rehabilitation"],
    setup: "Stand with the feet hip-width apart and the barbell over the middle of the feet, close to the shins. Hinge the hips back and bend the knees to grip the bar just outside the legs, back flat, chest up, shoulders slightly ahead of the bar.",
    steps: [
      "Set the back flat and take the slack out of the bar before anything lifts — the bar should be pulled tight against the plates.",
      "Drive through the whole foot, pushing the floor away, and let the bar travel straight up the shins.",
      "Keep the bar in contact with, or very close to, the legs the whole way.",
      "Stand tall at the top by squeezing the glutes — do not lean back or shrug.",
      "Return the bar to the floor by hinging the hips back first, keeping the back flat, then bending the knees.",
    ],
    dosage: { sets: "3–4", reps: "5–8", frequency: "1–2x/week", loadOrTempo: "Controlled lowering; load leaving 2–3 reps in reserve, and never to failure" },
    cue: "“Flat back, bar against your shins — push the floor away and stand tall. Don't lean back at the top.”",
    patientInstructions:
      "Stand with your feet hip-width apart and the bar over the middle of your feet. Push your hips back and bend your knees to grip the bar, keeping your back flat and your chest up. Stand up by driving through your feet, keeping the bar close to your legs the whole way. Stand tall — do not lean back. Lower it by pushing your hips back first, then bending your knees. Five to eight repetitions, three or four sets, once or twice a week. Start much lighter than you think and add weight slowly.",
    commonErrors: [
      "The hips rising before the bar, which leaves the back to do the lifting",
      "Rounding the low back, most often on the last repetitions or on the way down",
      "The bar drifting away from the legs",
      "Leaning back or shrugging at the top",
      "Adding weight faster than technique holds",
    ],
    regression: "Dumbbell Romanian Deadlift, a trap-bar or rack pull from blocks to shorten the range, or a lighter load.",
    progression: "Add load in small increments, pause just off the floor, or slow the lowering.",
    precautions: [
      "Technique first, load second: the deadlift is well tolerated by most backs when the position holds and is unforgiving when it does not — end the set the moment the back stops staying flat.",
      "Reduce load or hold off with symptomatic low back pain, and where spinal loading is restricted.",
      "Never take a set to failure, and build up over weeks rather than sessions.",
      "Follow the surgeon's protocol after spinal, hip or abdominal surgery, and take care with hernia history or uncontrolled hypertension, where heavy straining against a held breath matters.",
    ],
  },
];
