import type { MovementExercise } from "@/lib/movement-lab/types";

/** Cervical spine. Weighted toward the deep neck flexor / retraction family and the three
 *  stretches that actually get prescribed, because that is what a neck program is mostly
 *  made of — and toward low-difficulty entries, because an irritable neck tolerates very
 *  little early on. */
export const CERVICAL_EXERCISES: MovementExercise[] = [
  {
    id: "chin-tuck-supine",
    name: "Chin Tuck (Supine)",
    aka: ["Cranio-cervical flexion", "Deep neck flexor activation", "Nod"],
    region: "Cervical",
    category: "Activation",
    positions: ["Supine"],
    equipment: ["None", "Towel or strap"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore", "Strengthening"],
    targets: ["Longus colli", "Longus capitis", "Deep cervical flexors"],
    indications: ["Neck pain", "Cervicogenic headache", "Forward head posture", "Post-whiplash (once cleared)"],
    setup: "Lie on your back, knees bent, head resting flat or on a thin folded towel so the face is level with the ceiling.",
    steps: [
      "Nod gently, as if saying a small “yes” — the movement is at the base of the skull, not the whole neck.",
      "Feel a light stretch at the back of the upper neck and the chin drop slightly toward the throat.",
      "Hold the nod without letting the big superficial muscles at the front of the neck stand out.",
      "Relax fully between repetitions.",
    ],
    dosage: { sets: "2–3", reps: "10", hold: "5–10 s", frequency: "1–2x/day" },
    cue: "“Make a tiny double chin — nod like you're saying yes to something very small, and keep the back of your head on the surface.”",
    patientInstructions:
      "Lie on your back with your knees bent. Make a small nodding movement, like a gentle 'yes', so your chin tucks slightly toward your throat. Keep the back of your head resting down — you are not lifting your head off the surface. Hold for about five to ten seconds, then relax completely. Repeat ten times, once or twice a day.",
    commonErrors: [
      "Lifting the head off the surface instead of nodding at the base of the skull",
      "Jamming the chin hard into the chest — the movement should be small and gentle",
      "Visible bulging of the front-of-neck muscles, which means the superficial muscles are doing the work",
      "Holding the breath through the contraction",
    ],
    regression: "Shorten the hold to 2–3 seconds and reduce to 5 repetitions.",
    progression: "Chin Tuck with Head Lift (see chin-tuck-head-lift) once a 10-second hold is easy and symptom-free.",
    precautions: [
      "Stop if the exercise reproduces dizziness, arm symptoms, or a headache that keeps building.",
      "After cervical surgery or a fracture, follow the surgeon's protocol for when active neck motion is allowed.",
    ],
    note: "The cranio-cervical flexion pattern that deep neck flexor retraining programmes are built around.",
  },
  {
    id: "chin-tuck-head-lift",
    name: "Chin Tuck with Head Lift",
    aka: ["Deep neck flexor endurance", "Nod and lift"],
    region: "Cervical",
    category: "Strength",
    positions: ["Supine"],
    equipment: ["None"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Deep cervical flexors", "Sternocleidomastoid", "Scalenes"],
    indications: ["Chronic neck pain", "Cervicogenic headache", "Deep neck flexor endurance deficit"],
    setup: "Lie on your back, knees bent, head resting flat on the surface.",
    steps: [
      "Perform a gentle chin tuck first and hold it.",
      "Keeping the tuck, lift the head about an inch off the surface — no more.",
      "Hold, keeping the chin tucked the whole time; the moment the chin pokes forward, the set is over.",
      "Lower the head, release the tuck, and rest before the next repetition.",
    ],
    dosage: { sets: "2–3", reps: "8–10", hold: "5–10 s", frequency: "Once daily" },
    cue: "“Tuck first, then lift — and if your chin pokes out, put your head down. Quality ends the set, not fatigue.”",
    patientInstructions:
      "Lie on your back with knees bent. First make a small nod, tucking your chin. Keeping that tuck, lift your head about an inch off the surface and hold for five to ten seconds. Lower down and rest. If your chin starts poking forward, stop that set — doing it well matters more than doing more.",
    commonErrors: [
      "Losing the tuck as the head comes up, so the chin leads the lift",
      "Lifting too high, which turns it into a superficial-muscle exercise",
      "Pushing through shaking and neck pain instead of stopping the set",
    ],
    regression: "Chin Tuck (Supine) with no head lift.",
    progression: "Add repetitions, then lengthen the hold, before considering any added load.",
    precautions: [
      "Not appropriate while neck pain is highly irritable — the supine chin tuck comes first.",
      "Stop for dizziness, visual change, or symptoms travelling into the arm.",
    ],
  },
  {
    id: "cervical-retraction-seated",
    name: "Cervical Retraction (Seated)",
    aka: ["Chin retraction", "Head glide back", "Bracing the neck"],
    region: "Cervical",
    category: "Mobility",
    positions: ["Seated", "Standing"],
    equipment: ["None", "Chair"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore", "Strengthening"],
    targets: ["Upper cervical extensors", "Lower cervical segments", "Deep cervical flexors"],
    indications: ["Neck pain", "Forward head posture", "Desk-related neck stiffness", "Cervical radiculopathy with a retraction preference"],
    setup: "Sit tall in a supportive chair, feet flat, eyes level and looking straight ahead.",
    steps: [
      "Glide the whole head straight backward over the shoulders, keeping the eyes level.",
      "Go to the end of the comfortable range and hold briefly.",
      "Return to the starting position without letting the head drift further forward than where it started.",
    ],
    dosage: { sets: "1–2", reps: "10", hold: "2–3 s", frequency: "Several times a day" },
    cue: "“Slide your head straight back over your shoulders like a drawer closing — don't tip your nose up or down.”",
    patientInstructions:
      "Sit up tall and look straight ahead. Slide your whole head straight backwards over your shoulders, keeping your eyes level — do not tip your head up or down. Hold a couple of seconds, then let it come back. Ten repetitions, spread through the day, works better than one long session.",
    commonErrors: [
      "Nodding down instead of gliding straight back",
      "Shrugging the shoulders up during the glide",
      "Slumping the mid-back, which makes true retraction impossible",
    ],
    regression: "Do it lying on the back, where gravity doesn't fight the movement.",
    progression: "Retraction with over-pressure from two fingers on the chin, or progress to Retraction with Extension.",
    precautions: [
      "Stop if arm symptoms increase or travel further down the arm during or after the set.",
      "Increased dizziness is a reason to stop and be reassessed rather than push on.",
    ],
    note: "The retraction movement used as the first-line directional test-and-treat in McKenzie-style cervical assessment.",
  },
  {
    id: "cervical-retraction-extension",
    name: "Cervical Retraction with Extension",
    aka: ["Retraction–extension", "Chin tuck and look up"],
    region: "Cervical",
    category: "Mobility",
    positions: ["Seated", "Standing"],
    equipment: ["Chair"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Cervical extensors", "Anterior cervical structures", "Facet joints"],
    indications: ["Neck pain with a clear extension preference", "Loss of cervical extension range", "Postural neck pain"],
    setup: "Sit tall, supported, eyes forward.",
    steps: [
      "Retract the head fully — glide straight back and hold that position.",
      "Keeping the retraction, tip the head back to look up toward the ceiling.",
      "Rotate the head a few degrees each way at end range if that is comfortable, which usually lets it go a little further.",
      "Return to retraction first, then to neutral — never come up out of extension with the head poking forward.",
    ],
    dosage: { sets: "1", reps: "8–10", hold: "1–2 s", frequency: "Several times a day during a flare" },
    cue: "“Chin back first, then look up over your forehead — and come back to chin-back before you sit up straight.”",
    patientInstructions:
      "Sit tall. First slide your head straight back, then keeping it there, tip your head back to look at the ceiling. Come back to the head-back position before returning to normal. Do eight to ten, several times through the day. Symptoms moving out of your arm and closer to your neck is a good sign; symptoms travelling further down the arm is not — stop and tell your therapist.",
    commonErrors: [
      "Letting the head slide forward before extending, which loads the segments the exercise is meant to unload",
      "Going straight to end-range extension on the first repetition instead of building into it",
      "Doing it fast enough to provoke dizziness",
    ],
    regression: "Cervical Retraction (Seated) alone, no extension component.",
    progression: "Add gentle over-pressure at end range, or perform it lying supine off the edge of a bed under supervision.",
    precautions: [
      "Stop immediately for dizziness, nausea, visual disturbance, or a change in speech or swallowing.",
      "Not a self-directed exercise for someone with untested end-range extension symptoms, known cervical instability, inflammatory arthropathy, or after recent cervical surgery.",
      "Peripheralising symptoms (pain moving further down the arm) mean stop, not push harder.",
    ],
  },
  {
    id: "cervical-rotation-arom",
    name: "Cervical Rotation (Active Range)",
    region: "Cervical",
    category: "Mobility",
    positions: ["Seated", "Supine"],
    equipment: ["None", "Chair"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Cervical rotators", "Facet joints", "Upper cervical segments"],
    indications: ["Acute neck stiffness", "Post-whiplash (once cleared)", "Torticollis", "Reduced driving head-check range"],
    setup: "Sit tall with the shoulders relaxed and the head level.",
    steps: [
      "Turn the head slowly to look over one shoulder, staying inside the comfortable range.",
      "Pause briefly at the end of comfortable movement.",
      "Return slowly through the middle and turn to the other side.",
      "Keep the chin level throughout — the nose stays on the same horizontal line.",
    ],
    dosage: { sets: "1–2", reps: "10 each side", frequency: "2–3x/day" },
    cue: "“Turn to look over your shoulder like you're checking a blind spot — slow, and only as far as comfortable.”",
    patientInstructions:
      "Sit up tall. Slowly turn your head to look over one shoulder, only as far as is comfortable, then slowly turn to the other side. Keep your chin level — do not let your nose drop or lift. Ten each way, two or three times a day.",
    commonErrors: [
      "Turning the shoulders and trunk instead of the head",
      "Dropping or lifting the chin as the head turns",
      "Forcing past the point where symptoms sharpen",
    ],
    regression: "Perform lying on the back where the head is supported by the surface.",
    progression: "Add a light end-range hold, or progress to rotation in a flexed position for the upper cervical segments.",
    precautions: [
      "Stop for dizziness, and report it — end-range rotation symptoms need assessment before continuing.",
      "Stay well inside range in the first days after a whiplash injury.",
    ],
  },
  {
    id: "cervical-rotation-in-flexion",
    name: "Cervical Rotation in Flexion",
    aka: ["Upper cervical rotation", "C1–C2 rotation"],
    region: "Cervical",
    category: "Mobility",
    positions: ["Seated"],
    equipment: ["Chair"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Atlanto-axial joint", "Upper cervical rotators"],
    indications: ["Cervicogenic headache", "Restricted upper cervical rotation"],
    setup: "Sit tall in a chair with the back supported.",
    steps: [
      "Drop the chin toward the chest into comfortable flexion and hold it there — this locks out most of the lower neck.",
      "Keeping the chin down, rotate the head to look toward one armpit.",
      "Return to the middle, then rotate the other way.",
      "Come back to neutral flexion before lifting the head.",
    ],
    dosage: { sets: "1–2", reps: "8–10 each side", hold: "2–3 s", frequency: "Once or twice daily" },
    cue: "“Chin to chest first and keep it there — now turn and look toward your armpit.”",
    patientInstructions:
      "Sit tall and drop your chin toward your chest. Keeping your chin down, turn your head to look toward your armpit, then to the other side. Hold a couple of seconds each way. Eight to ten each side, once or twice a day.",
    commonErrors: [
      "Letting the chin lift during the turn, which shifts the movement back to the lower neck",
      "Rotating with the trunk rather than the head",
      "Pushing into a headache that is building rather than easing",
    ],
    regression: "Plain Cervical Rotation with the head neutral.",
    progression: "Hold longer at end range, then add gentle self over-pressure with one hand.",
    precautions: [
      "Stop for dizziness, visual change, or new arm symptoms.",
      "Avoid entirely where upper cervical instability is suspected or in inflammatory arthropathy affecting the cervical spine, until cleared.",
    ],
  },
  {
    id: "cervical-sidebend-arom",
    name: "Cervical Side Bend (Active Range)",
    region: "Cervical",
    category: "Mobility",
    positions: ["Seated", "Standing"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Lateral cervical musculature", "Facet joints"],
    indications: ["Neck stiffness", "Acute wry neck (once settling)", "General cervical mobility"],
    setup: "Sit or stand tall with the shoulders level and relaxed.",
    steps: [
      "Tip one ear toward the shoulder on the same side without lifting that shoulder to meet it.",
      "Stop at the first firm resistance, not at the point of pain.",
      "Return to level, then tip the other way.",
    ],
    dosage: { sets: "1–2", reps: "10 each side", frequency: "2–3x/day" },
    cue: "“Ear toward your shoulder — and keep the shoulder where it is, don't shrug up to meet it.”",
    patientInstructions:
      "Sitting or standing tall, tip one ear toward your shoulder without shrugging that shoulder up. Go only as far as comfortable, come back to level, and repeat to the other side. Ten each way, a couple of times a day.",
    commonErrors: [
      "Shrugging the shoulder up to the ear instead of bringing the ear to the shoulder",
      "Rotating the head as it tips, so the nose turns",
      "Bouncing at end range",
    ],
    regression: "Reduce the range; do it supine with the head supported.",
    progression: "Add a light hand over-pressure at end range, held 20–30 seconds, which turns it into a stretch.",
    precautions: [
      "Stop if symptoms move down the arm.",
      "Keep the range small and gentle in the acute stage of a wry neck.",
    ],
  },
  {
    id: "cervical-isometrics",
    name: "Cervical Isometrics (Multi-direction)",
    aka: ["Neck isometrics", "Hand-resisted neck holds"],
    region: "Cervical",
    category: "Strength",
    positions: ["Seated", "Standing"],
    equipment: ["None", "Wall"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Cervical flexors", "Cervical extensors", "Lateral flexors", "Rotators"],
    indications: ["Neck pain with strength deficits", "Post-whiplash reconditioning", "Contact-sport neck conditioning"],
    setup: "Sit or stand tall with the head in neutral. Place one hand against the forehead, the back of the head, or the side of the head depending on the direction being worked.",
    steps: [
      "Press the head gently into the hand without any movement happening — the head stays still.",
      "Build the pressure to roughly half effort over a second or two, hold, then release gradually.",
      "Work forward, backward, and each side in turn, resting between directions.",
    ],
    dosage: { sets: "1–2", reps: "5–8 per direction", hold: "5 s", frequency: "Once daily", loadOrTempo: "About 50% effort, built up and released gradually" },
    cue: "“Push into your hand just hard enough to feel the muscle work — nothing should actually move.”",
    patientInstructions:
      "Sit tall. Put your hand on your forehead and press your head gently into it — hard enough to feel the muscles working, but not hard enough for your head to move. Hold five seconds, then ease off slowly. Repeat with your hand behind your head, and then on each side. Five to eight holds in each direction, once a day.",
    commonErrors: [
      "Pushing maximally instead of at a moderate, controlled effort",
      "Letting the head actually move, which makes it a resisted exercise rather than an isometric",
      "Snapping the pressure on and off instead of building and releasing",
      "Holding the breath",
    ],
    regression: "Use a lighter effort and 3-second holds, and work only the directions that are comfortable.",
    progression: "Longer holds, then progress toward the endurance work of Chin Tuck with Head Lift and Prone Head Lift.",
    precautions: [
      "Keep the effort submaximal — this is not a strength test.",
      "Stop for dizziness, headache that keeps building, or arm symptoms.",
    ],
  },
  {
    id: "upper-trapezius-stretch",
    name: "Upper Trapezius Stretch",
    region: "Cervical",
    category: "Flexibility",
    positions: ["Seated"],
    equipment: ["Chair"],
    difficulty: 1,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Upper trapezius"],
    indications: ["Neck and shoulder tension", "Cervicogenic headache", "Desk-related neck pain"],
    setup: "Sit tall in a chair and hold the seat edge with the hand on the side being stretched, which anchors that shoulder down.",
    steps: [
      "Tip the opposite ear toward the opposite shoulder.",
      "Turn the nose slightly away from the stretched side, up toward the ceiling.",
      "Use the free hand on top of the head for gentle guidance only, not to pull hard.",
      "Hold, breathing normally, then release slowly.",
    ],
    dosage: { sets: "2–3", reps: "1 each side", hold: "30 s", frequency: "1–2x/day" },
    cue: "“Sit on the hand of the tight side, then take your other ear away from it — you should feel a long, tolerable pull, not a sharp one.”",
    patientInstructions:
      "Sit tall and hold onto the chair seat with the hand on the tight side. Tip your other ear toward the other shoulder and turn your nose slightly upward, away from the tight side. You should feel a comfortable stretch along the side of your neck onto the top of the shoulder. Hold thirty seconds, two or three times per side.",
    commonErrors: [
      "Pulling hard on the head with the free hand",
      "Letting the anchored shoulder rise, which removes the stretch",
      "Holding the breath or bracing through the jaw",
    ],
    regression: "Drop the hand assistance entirely and use head position alone.",
    progression: "Anchor the shoulder more firmly and hold up to 45 seconds.",
    precautions: [
      "A stretch should feel like a pull, never a sharp or electric sensation — stop if it does.",
      "Avoid strong over-pressure on a neck that is still highly irritable.",
    ],
  },
  {
    id: "levator-scapulae-stretch",
    name: "Levator Scapulae Stretch",
    region: "Cervical",
    category: "Flexibility",
    positions: ["Seated"],
    equipment: ["Chair"],
    difficulty: 1,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Levator scapulae"],
    indications: ["Neck and upper-back tension", "Reduced cervical rotation", "Cervicogenic headache"],
    setup: "Sit tall and anchor the shoulder on the tight side by holding the chair seat or reaching that hand behind the low back.",
    steps: [
      "Turn the head about 45 degrees away from the tight side.",
      "Drop the nose down toward the armpit on that opposite side.",
      "Rest the free hand lightly on the back of the head for gentle guidance only.",
      "Hold, breathing normally.",
    ],
    dosage: { sets: "2–3", reps: "1 each side", hold: "30 s", frequency: "1–2x/day" },
    cue: "“Turn your nose away from the sore side, then look down into your armpit — you'll feel it from the base of your neck to the top of your shoulder blade.”",
    patientInstructions:
      "Sit tall and hold the chair seat with the hand on the tight side. Turn your head about halfway toward the other side, then drop your nose down toward that armpit. Rest your other hand gently on the back of your head. Hold thirty seconds, two or three times per side.",
    commonErrors: [
      "Confusing it with the upper trapezius stretch — the nose turns away here, rather than up",
      "Pulling forcefully with the guiding hand",
      "Letting the anchored shoulder lift",
    ],
    regression: "Use position alone with no hand on the head.",
    progression: "Hold longer, or add a gentle scapular depression on the anchored side.",
    precautions: [
      "Stop for any sharp, shooting, or electric sensation.",
      "Keep it gentle where the neck is still irritable.",
    ],
  },
  {
    id: "scalene-stretch",
    name: "Scalene Stretch",
    region: "Cervical",
    category: "Flexibility",
    positions: ["Seated"],
    equipment: ["Chair"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Anterior scalene", "Middle scalene", "Accessory breathing muscles"],
    indications: ["Anterior neck tightness", "Upper chest breathing pattern", "Neck pain with shoulder-girdle tension"],
    setup: "Sit tall and anchor the shoulder on the side being stretched by holding the chair seat.",
    steps: [
      "Tip the ear away from the anchored side.",
      "Turn the nose slightly toward the anchored side and lift the chin a little.",
      "Hold gently and breathe out slowly through the stretch.",
    ],
    dosage: { sets: "2", reps: "1 each side", hold: "20–30 s", frequency: "Once daily" },
    cue: "“Ear away, nose toward, chin slightly up — and breathe out into it rather than pulling harder.”",
    patientInstructions:
      "Sit tall and hold the chair seat on the side you want to stretch. Tip your head away from that side, then turn your nose slightly toward it and lift your chin a little. You should feel a gentle stretch at the front and side of your neck. Hold twenty to thirty seconds, twice per side.",
    commonErrors: [
      "Over-extending the neck to chase the stretch",
      "Shrugging the anchored shoulder",
      "Pulling with a hand on the head, which is unnecessary here and easy to overdo",
    ],
    regression: "Keep the chin level rather than lifted and reduce the hold to 15 seconds.",
    progression: "Extend the hold, or pair it with a diaphragmatic breathing drill.",
    precautions: [
      "Stop immediately for tingling, numbness, or a change in the hand — the neurovascular structures of the thoracic outlet run right here.",
      "Avoid this one where thoracic outlet symptoms or vascular concerns are being investigated, until cleared.",
    ],
  },
  {
    id: "suboccipital-release",
    name: "Suboccipital Release (Supine)",
    aka: ["Occipital release", "Ball release at the base of the skull"],
    region: "Cervical",
    category: "Mobility",
    positions: ["Supine"],
    equipment: ["Ball", "Towel or strap"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Suboccipital muscles"],
    indications: ["Cervicogenic headache", "Tension at the base of the skull", "Upper cervical stiffness"],
    setup: "Lie on the back with knees bent. Place two tennis balls in a sock (or a rolled towel) just below the base of the skull, one on each side of the midline — never directly on the spine.",
    steps: [
      "Let the weight of the head rest onto the balls or towel.",
      "Stay still and breathe slowly for the first half of the hold.",
      "Add a very small nod, as if saying yes, a few times.",
      "Come off slowly, rolling the head to one side first.",
    ],
    dosage: { sets: "1", reps: "1", hold: "60–120 s", frequency: "Once daily" },
    cue: "“Let your head get heavy on the balls — you're not pushing into them, you're letting go onto them.”",
    patientInstructions:
      "Lie on your back with your knees bent. Put two tennis balls in a sock and place them just under the base of your skull, one either side of the middle — never on the bones of your spine itself. Let your head rest there and breathe slowly for one to two minutes, adding a few small nods toward the end. Come off slowly.",
    commonErrors: [
      "Putting the pressure on the spine itself rather than either side of it",
      "Pressing too hard, which guards the muscles rather than settling them",
      "Sitting straight up afterwards instead of rolling to one side first",
    ],
    regression: "Use a folded towel instead of balls for a broader, gentler pressure.",
    progression: "Add the small nods for the full duration, or hold up to two minutes.",
    precautions: [
      "Stop for dizziness, nausea, or visual change.",
      "Avoid direct pressure on bone, and avoid entirely after recent head or neck trauma until cleared.",
    ],
  },
  {
    id: "prone-head-lift",
    name: "Prone Cervical Extensor Hold",
    aka: ["Prone head lift", "Neck extensor endurance"],
    region: "Cervical",
    category: "Strength",
    positions: ["Prone"],
    equipment: ["None"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Deep cervical extensors", "Semispinalis cervicis", "Upper thoracic extensors"],
    indications: ["Chronic neck pain", "Neck extensor endurance deficit", "Postural neck fatigue"],
    setup: "Lie face down with the forehead resting on a folded towel and the arms by the sides.",
    steps: [
      "Tuck the chin gently.",
      "Keeping the tuck, lift the head just off the towel until it is in line with the spine — not higher.",
      "Hold, keeping the eyes looking down at the floor.",
      "Lower under control and rest.",
    ],
    dosage: { sets: "2–3", reps: "8–10", hold: "5–10 s", frequency: "Once daily" },
    cue: "“Chin tucked, then lift your head just level with your spine — eyes stay on the floor, don't look forward.”",
    patientInstructions:
      "Lie face down with your forehead on a folded towel. Tuck your chin slightly, then lift your head just enough to clear the towel, so it lines up with your back. Keep looking at the floor. Hold five to ten seconds, lower, and rest. Eight to ten repetitions, once a day.",
    commonErrors: [
      "Lifting the head high and looking forward, which cranks the upper neck into extension",
      "Losing the chin tuck",
      "Holding to exhaustion instead of stopping while the position is still clean",
    ],
    regression: "Do it in four-point kneeling with the head held level, which is far less demanding.",
    progression: "Longer holds, then more repetitions, then add prone scapular work (see prone-y-raise).",
    precautions: [
      "Not for someone who cannot lie face down comfortably, or in early post-operative cervical care.",
      "Stop for headache or arm symptoms.",
    ],
  },
  {
    id: "median-nerve-glide",
    name: "Median Nerve Glide",
    aka: ["Median nerve floss", "Nerve gliding for the arm"],
    region: "Cervical",
    category: "Neurodynamic",
    positions: ["Seated", "Standing"],
    equipment: ["None"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Median nerve", "Cervical nerve roots", "Neural interface tissue"],
    indications: ["Cervical radiculopathy", "Carpal tunnel symptoms", "Arm tingling with a neural component"],
    setup: "Sit or stand tall with the arm out to the side at about shoulder height, elbow bent, palm facing up.",
    steps: [
      "Straighten the elbow and extend the wrist and fingers back, while tipping the head *toward* the working arm.",
      "Then bend the elbow and relax the wrist while tipping the head *away* from the arm.",
      "Move slowly and rhythmically between the two positions — this is a slide, not a stretch held at end range.",
      "Stay short of reproducing strong symptoms at every point.",
    ],
    dosage: { sets: "1–2", reps: "8–10", frequency: "1–2x/day", loadOrTempo: "Slow and rhythmic, no end-range hold" },
    cue: "“As your arm straightens, your head comes toward it; as your arm bends, your head goes away. Slide through it — never hang out at the end.”",
    patientInstructions:
      "Sit tall with your arm out to the side, elbow bent and palm up. As you straighten your elbow and bend your wrist back, tip your head toward that arm. Then bend the elbow, relax the wrist, and tip your head away. Move smoothly back and forth eight to ten times. You may feel a light pulling — you should not be provoking strong tingling or pain.",
    commonErrors: [
      "Holding the end position like a stretch, which usually flares neural symptoms",
      "Moving fast and losing the head–arm coordination",
      "Chasing a strong pull rather than staying under symptom threshold",
    ],
    regression: "Move only the wrist and elbow, keeping the head neutral.",
    progression: "Add shoulder depression or take the arm further into abduction — increase one variable at a time.",
    precautions: [
      "Symptoms that increase for hours afterward mean the dose was too much — reduce range and repetitions.",
      "Not a self-directed exercise while there is progressive weakness, numbness in a saddle or bilateral distribution, or any red-flag neurological change: that needs assessment first.",
    ],
    note: "A gliding (rather than tensioning) neurodynamic technique — the two ends of the nerve are loaded alternately, not at once.",
  },
];
