import type { MovementExercise } from "@/lib/movement-lab/types";

/**
 * General conditioning. These entries are *programs* rather than single movements, which is
 * why their `steps` read as rules and their `dosage` is written in minutes rather than reps —
 * but they use the same record shape as everything else so they can be filtered, searched and
 * dropped into a HEP alongside the specific exercises. Almost every HEP in the bank should
 * carry one of these: the local exercises fix the local problem, and the conditioning entry is
 * what actually returns the person to their life.
 */
export const CONDITIONING_EXERCISES: MovementExercise[] = [
  {
    id: "walking-program",
    name: "Walking Program",
    aka: ["Graded walking", "Daily walking prescription"],
    region: "General Conditioning",
    category: "Endurance",
    positions: ["Standing"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Cardiovascular system", "Lower limb endurance", "General conditioning"],
    indications: ["Deconditioning", "Persistent low back pain", "Post-operative recovery", "Osteoarthritis", "General health"],
    setup: "Comfortable, supportive footwear and a route that allows turning back at any point rather than committing to a long loop.",
    steps: [
      "Start from a baseline that can be done comfortably on a bad day, not a good one.",
      "Walk at a pace where talking is possible but singing is not.",
      "Increase the duration by roughly ten percent per week, and only change one thing at a time — duration or pace, never both.",
      "Hold the current level for an extra week rather than progressing after any flare.",
    ],
    dosage: { sets: "1", reps: "", frequency: "Most days of the week", loadOrTempo: "Start at a duration that is comfortable on a bad day; build ~10% per week toward 20–30 minutes" },
    cue: "“Set your starting point by what you could manage on a bad day — that's the number that keeps you consistent instead of boom-and-bust.”",
    patientInstructions:
      "Walk at a pace where you could hold a conversation but not sing. Start with a length of time you could manage even on a bad day — that might be five minutes, and that is fine. Add about ten percent each week, aiming to build toward twenty to thirty minutes on most days. If you have a flare, stay at your current level for an extra week rather than dropping the walking altogether.",
    commonErrors: [
      "Setting the starting point by the best day, which produces a boom-and-bust cycle",
      "Increasing pace and duration in the same week",
      "Stopping walking entirely after a flare instead of holding at the current level",
      "Only walking at weekends",
    ],
    regression: "Split the total into two or three shorter walks across the day.",
    progression: "Add duration first, then pace, then hills or uneven ground.",
    precautions: [
      "Chest pain, unusual breathlessness, dizziness or palpitations mean stop and seek medical advice, not push on.",
      "Follow post-operative weight-bearing restrictions.",
      "Use appropriate footwear and a walking aid if one has been prescribed.",
    ],
  },
  {
    id: "interval-walking",
    name: "Interval Walking",
    aka: ["Walk–rest intervals", "Paced walking intervals"],
    region: "General Conditioning",
    category: "Endurance",
    positions: ["Standing"],
    equipment: ["None", "Chair"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Cardiovascular system", "Walking tolerance"],
    indications: ["Lumbar spinal stenosis", "Intermittent claudication-type symptoms", "Low walking tolerance", "Post-operative endurance building"],
    setup: "Plan a route with places to sit or lean at intervals, so a rest is always available before it is needed.",
    steps: [
      "Walk for a set time that stays *below* the point where symptoms build — if symptoms start at four minutes, walk three.",
      "Rest in the position that settles symptoms most quickly, which for spinal stenosis is usually sitting or leaning forward.",
      "Repeat the walk–rest cycle several times.",
      "Increase the walking interval before increasing the number of cycles.",
    ],
    dosage: { sets: "4–6 cycles", reps: "", frequency: "Most days", loadOrTempo: "Walk interval set just under the symptom threshold; rest 1–2 minutes" },
    cue: "“Sit down before you have to, not after — resting early is what lets you cover more ground in total.”",
    patientInstructions:
      "Work out roughly how long you can walk before your symptoms start building, and walk for slightly less than that. Then rest — sitting down, or leaning forward on a counter or trolley, whichever settles things fastest. Repeat four to six times. As it gets easier, make each walking stretch slightly longer before adding more repeats.",
    commonErrors: [
      "Walking until symptoms force a stop, which sets the whole session back",
      "Adding more cycles before lengthening the walking interval",
      "Resting standing up when sitting or leaning is what actually settles the symptoms",
    ],
    regression: "Shorter walking intervals and longer rests; use a supported walking aid.",
    progression: "Lengthen the walking interval, then reduce the rest, then increase the number of cycles.",
    precautions: [
      "New or worsening leg weakness, numbness in the saddle area, or bladder or bowel change needs urgent medical assessment.",
      "Calf pain that comes on reliably with walking and settles with rest should be medically assessed rather than simply trained through.",
    ],
  },
  {
    id: "return-to-running-progression",
    name: "Return-to-Running Progression",
    aka: ["Walk–run program", "Graded running return"],
    region: "General Conditioning",
    category: "Endurance",
    positions: ["Standing"],
    equipment: ["None"],
    difficulty: 4,
    phases: ["Return to Activity"],
    targets: ["Cardiovascular system", "Lower limb load tolerance", "Tendon and bone loading capacity"],
    indications: ["Return to running after injury", "Post-operative return to sport", "Running-related overuse injury"],
    setup: "Flat, even ground in supportive running shoes. Entry criteria should be met before starting — typically pain-free walking for thirty minutes, symmetrical single-leg heel raises and single-leg squats, and no pain on hopping.",
    steps: [
      "Alternate short running intervals with walking intervals — for example one minute of running to two minutes of walking.",
      "Keep total running time low at first and increase the running interval before reducing the walking.",
      "Run on alternate days only, never on consecutive days, in the early weeks.",
      "Judge each session by how the area feels the next morning, not by how it feels during the run.",
    ],
    dosage: { sets: "6–10 intervals", reps: "", frequency: "Every other day, 3x/week", loadOrTempo: "Start ~1 min run / 2 min walk; progress the run interval by ~10% per week" },
    cue: "“The test isn't how it feels while you're running — it's how it feels when you get out of bed tomorrow.”",
    patientInstructions:
      "Alternate one minute of easy running with two minutes of walking, repeating six to ten times. Run every other day, never two days in a row. Each week, make the running intervals slightly longer before shortening the walking. The most important test is how the area feels the next morning — if it is stiffer or more sore than before, repeat the previous week rather than progressing.",
    commonErrors: [
      "Starting before the entry criteria are met",
      "Running on consecutive days early in the progression",
      "Judging the session by how it felt during the run rather than the next morning",
      "Increasing distance, pace and frequency in the same week",
    ],
    regression: "Shorter running intervals, more walking, or return to fast walking and hopping drills for another week.",
    progression: "Longer running intervals, then continuous running, then pace, then hills and uneven terrain — one variable at a time.",
    precautions: [
      "Not appropriate until the entry criteria are met — the criteria, not the calendar, decide when running starts.",
      "Pain that increases week to week, or a localised bony tenderness, means stop and be reassessed rather than pushing through.",
      "Follow the surgeon's timeline after lower limb surgery.",
    ],
  },
  {
    id: "stair-climbing",
    name: "Stair Climbing Practice",
    aka: ["Graded stair practice"],
    region: "General Conditioning",
    category: "Endurance",
    positions: ["Standing"],
    equipment: ["Step or stairs"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Quadriceps", "Gluteals", "Cardiovascular system"],
    indications: ["Difficulty with stairs at home", "Post-operative lower limb rehabilitation", "Lower limb endurance deficit", "Deconditioning"],
    setup: "A staircase with a secure handrail. Practise where there is somewhere to sit at the top or bottom.",
    steps: [
      "Going up, lead with the stronger leg; going down, lead with the weaker one.",
      "Use the handrail, and place the whole foot on each step where the step depth allows.",
      "Climb a set number of steps, rest, and repeat.",
      "Build the number of flights before increasing the pace.",
    ],
    dosage: { sets: "3–5", reps: "1 flight", frequency: "Daily", loadOrTempo: "Rest fully between flights; add flights before adding pace" },
    cue: "“Up with the good leg, down with the bad — and use the rail, that's what it's there for.”",
    patientInstructions:
      "Using the handrail, go up the stairs leading with your stronger leg and come down leading with your weaker leg. Rest at the bottom, then repeat. Three to five flights with rests, once a day. Build up the number of flights before you try to go faster.",
    commonErrors: [
      "Leading with the wrong leg in each direction",
      "Not using the handrail",
      "Rushing the descent, which is the higher-risk direction",
      "Building pace before building volume",
    ],
    regression: "Practise on a single step, stepping up and down, holding the rail.",
    progression: "More flights, then step over step rather than one step at a time, then reduce rail use if safe.",
    precautions: [
      "Always use the handrail, and never practise alone if unsteady.",
      "Follow post-operative weight-bearing restrictions.",
      "Stop for chest pain, unusual breathlessness or dizziness and seek medical advice.",
    ],
  },
  {
    id: "stationary-cycling",
    name: "Stationary Cycling",
    aka: ["Exercise bike", "Static cycling"],
    region: "General Conditioning",
    category: "Endurance",
    positions: ["Seated"],
    equipment: ["None"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Cardiovascular system", "Quadriceps", "Knee and hip range of motion"],
    indications: ["Post total knee replacement", "Post ACL reconstruction", "Knee and hip osteoarthritis", "Lumbar spinal stenosis", "Low-impact conditioning"],
    setup: "Set the saddle height so the knee has a slight bend at the bottom of the pedal stroke. Raise the saddle if knee flexion range is limited; lower it slightly as range improves.",
    steps: [
      "Start by rocking the pedals back and forth if a full revolution is not yet possible.",
      "Progress to full revolutions once the range allows, with no resistance at first.",
      "Build the duration before adding any resistance.",
      "Keep the pace comfortable — a conversation should be possible.",
    ],
    dosage: { sets: "1", reps: "", frequency: "Most days", loadOrTempo: "Start 5–10 minutes with no resistance; build duration first, then resistance" },
    cue: "“Raise the seat until you can get the pedal all the way round comfortably — then lower it a little each week as your knee bends further.”",
    patientInstructions:
      "Set the saddle high enough that your knee is only slightly bent at the bottom of the pedal stroke. If you cannot get the pedal all the way round yet, rock it back and forth instead. Start with five to ten minutes with no resistance and build up the time before adding any. Keep the pace easy enough to talk.",
    commonErrors: [
      "A saddle set too low, which forces more knee bend than is available and causes pain",
      "Adding resistance before building duration",
      "Pedalling hard enough that a conversation is impossible in the early stages",
    ],
    regression: "Pedal rocking through a partial arc; shorter sessions split across the day.",
    progression: "Longer duration, then resistance, then a lower saddle as knee flexion improves.",
    precautions: [
      "Follow the surgeon's protocol on when cycling may start and at what resistance.",
      "Stop for chest pain, unusual breathlessness or dizziness.",
      "Reduce the saddle height only as knee range genuinely allows.",
    ],
  },
  {
    id: "aquatic-walking",
    name: "Aquatic Walking",
    aka: ["Pool walking", "Water walking"],
    region: "General Conditioning",
    category: "Endurance",
    positions: ["Standing"],
    equipment: ["None"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Cardiovascular system", "Lower limb endurance", "Balance"],
    indications: ["Osteoarthritis", "High pain sensitivity with land-based loading", "Post-operative reduced weight-bearing", "Obesity-related joint loading", "Deconditioning"],
    setup: "A pool where the water reaches chest or waist height, with easy access via steps or a ramp.",
    steps: [
      "Walk forward the length of the pool with an upright posture and a normal heel-to-toe pattern.",
      "Walk backward and sideways for a set distance each.",
      "Deeper water reduces the load on the joints; shallower water increases it.",
      "Use the pool edge for support when turning.",
    ],
    dosage: { sets: "1", reps: "", frequency: "2–3x/week", loadOrTempo: "Start 10 minutes; build to 20–30. Deeper water = less load" },
    cue: "“Walk normally, heel to toe, rather than shuffling — and remember deeper water means less weight through your joints.”",
    patientInstructions:
      "In water at about waist or chest height, walk the length of the pool forwards, then backwards, then sideways. Walk with a normal heel-to-toe step rather than shuffling. Start with about ten minutes and build to twenty or thirty, two or three times a week. Deeper water takes more weight off your joints.",
    commonErrors: [
      "Shuffling rather than walking with a normal step pattern",
      "Choosing water so shallow that the joint-unloading benefit is lost",
      "Overdoing it because it feels easy in the water and paying for it afterward",
    ],
    regression: "Deeper water, shorter duration, hold the pool edge.",
    progression: "Shallower water, longer duration, add resistance from a paddle or faster walking.",
    precautions: [
      "Not appropriate with an open or unhealed wound, an active infection, or uncontrolled incontinence.",
      "Confirm with the surgical team that a wound is fully healed before pool immersion after surgery.",
      "Take care getting in and out — the poolside is where most incidents happen.",
      "Not appropriate for someone who is not comfortable in water without supervision.",
    ],
  },
  {
    id: "alternating-battle-ropes",
    name: "Alternating Battle Ropes",
    aka: ["Battle rope waves", "Alternating waves", "Rope slams (alternating)", "Heavy rope training"],
    region: "General Conditioning",
    category: "Endurance",
    positions: ["Standing"],
    equipment: ["Weight"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Cardiovascular system", "Shoulder girdle endurance", "Latissimus dorsi", "Grip and forearms", "Trunk", "Lower limb isometric endurance"],
    indications: ["Conditioning when running and impact are not yet permitted", "Late-stage return to work or sport conditioning", "Deconditioning with a painful or load-restricted lower limb", "Upper limb and grip endurance", "Interval conditioning for someone who tolerates load but not impact"],
    setup: "Anchor a heavy rope at its midpoint around a fixed post or rack base and take one end in each hand. Stand facing the anchor a little inside the point where the rope goes taut, feet about hip to shoulder width, knees softly bent and hips hinged back into an athletic stance.",
    steps: [
      "Set the stance first — soft knees, hips back, chest up, ribs down, weight through the middle of the feet.",
      "Drive one arm down and up to send a wave along the rope while the other arm travels the opposite way.",
      "Alternate continuously, keeping the waves even in size and reaching the anchor.",
      "Drive the movement from the shoulder and trunk rather than squeezing the grip and flicking the wrists.",
      "Keep breathing throughout the work interval — do not hold the breath.",
      "Rest fully between intervals so the wave quality holds up on the next one.",
    ],
    dosage: { sets: "4–6", reps: "", frequency: "2–3x/week", loadOrTempo: "20–30 s of continuous waves, then 40–60 s rest; start at 10–15 s if new to it" },
    cue: "“Soft knees, hips back — drive the waves from your shoulders and keep breathing. When the waves stop reaching the anchor, the set is over.”",
    patientInstructions:
      "With a heavy rope anchored at its middle, hold one end in each hand and stand facing the anchor with your feet about hip width apart, knees slightly bent and hips pushed back. Drive one arm down while the other comes up, alternating quickly so a wave travels along each rope. Work for twenty to thirty seconds, then rest for forty to sixty seconds, and repeat four to six times. Keep breathing the whole time. Stop the set when the waves get small and ragged — that means you are tired, and tired repetitions are where technique goes.",
    commonErrors: [
      "Standing tall with straight legs so the whole effort lands on the shoulders",
      "Gripping hard and flicking the wrists instead of driving from the shoulder and trunk",
      "Holding the breath through the interval",
      "Rounding the low back as fatigue sets in",
      "Working on past the point where the waves stop reaching the anchor",
      "Cutting the rest short, which turns an interval session into a grinding one",
    ],
    regression: "Shorten the work interval to 10–15 seconds and lengthen the rest; use a lighter or shorter rope; stand closer to the anchor so there is less rope to move; make the waves smaller.",
    progression: "Lengthen the work interval or shorten the rest; step further back for more rope; move to double-arm waves or rope slams; add a stance change such as a half-squat hold or alternating step.",
    precautions: [
      "A conditioning stressor as much as an arm exercise — screen exercise tolerance first, and stop for chest pain, unusual breathlessness or dizziness.",
      "Avoid straining against a held breath, which matters most with hypertension or known cardiovascular disease.",
      "Not appropriate with acute shoulder pain, and only after clearance following rotator cuff repair, labral repair or shoulder stabilisation.",
      "Grip-intensive — reduce or hold off with lateral epicondylalgia, wrist or hand pain, or carpal tunnel symptoms.",
      "Check the rope is properly anchored and the area is clear before starting.",
      "Ease off with any low back pain, which usually means the stance has collapsed rather than the rope being too heavy.",
    ],
  },
  {
    id: "seated-aerobic-circuit",
    name: "Seated Aerobic Circuit",
    aka: ["Chair cardio", "Seated conditioning"],
    region: "General Conditioning",
    category: "Endurance",
    positions: ["Seated"],
    equipment: ["Chair"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Cardiovascular system", "Upper and lower limb endurance"],
    indications: ["Non-weight-bearing status", "Severe deconditioning", "Balance too limited for standing exercise", "Falls risk"],
    setup: "Sit tall and well back in a firm chair with arms, feet flat on the floor.",
    steps: [
      "March the legs alternately for a set time.",
      "Then punch the arms forward alternately.",
      "Then alternate heel taps and toe taps on the floor.",
      "Then reach both arms overhead and back down repeatedly.",
      "Move continuously through the circuit at a pace that raises the breathing rate but still allows talking.",
    ],
    dosage: { sets: "2–3 rounds", reps: "30–60 s per movement", frequency: "Most days" },
    cue: "“Keep it continuous — the aim is to get your breathing up a little, so move from one straight into the next.”",
    patientInstructions:
      "Sitting tall in a firm chair, march your legs for a minute, then punch your arms forwards for a minute, then tap your heels and toes on the floor, then reach both arms overhead and back down. Move straight from one to the next. Repeat the whole round two or three times. You should feel your breathing pick up but still be able to talk.",
    commonErrors: [
      "Long rests between movements, which loses the aerobic effect",
      "Slumping back in the chair",
      "Using a chair with wheels",
    ],
    regression: "One round, 20–30 seconds per movement, with rests as needed.",
    progression: "More rounds, longer intervals, light hand weights, or progress to standing.",
    precautions: [
      "Use a stable, non-rolling chair.",
      "Stop for chest pain, unusual breathlessness, dizziness or palpitations and seek medical advice.",
    ],
  },
  {
    id: "chair-based-strength-circuit",
    name: "Chair-Based Strength Circuit",
    aka: ["Seated strengthening circuit"],
    region: "General Conditioning",
    category: "Strength",
    positions: ["Seated"],
    equipment: ["Chair", "Resistance band"],
    difficulty: 2,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Quadriceps", "Shoulder girdle", "Trunk", "Grip"],
    indications: ["Severe deconditioning", "Falls risk", "Non-weight-bearing status", "Older adult strength maintenance"],
    setup: "A firm, stable chair with the feet flat. A light resistance band available.",
    steps: [
      "Long arc quads — straighten one knee at a time and lower slowly.",
      "Seated band row — anchor a band in front and pull the elbows back.",
      "Seated heel raises and toe raises.",
      "Seated marching with the trunk held tall.",
      "Rest thirty to sixty seconds between exercises.",
    ],
    dosage: { sets: "2", reps: "10–12 per exercise", frequency: "2–3x/week", loadOrTempo: "Controlled; 2 s effort, 3 s return" },
    cue: "“Everything slow on the way back — the lowering is where most of the strength is built.”",
    patientInstructions:
      "Sitting tall in a firm chair, do ten to twelve of each: straighten one knee at a time and lower it slowly; pull a band back with your elbows; lift your heels then your toes off the floor; and march your legs. Rest between each. Go through the whole circuit twice, two or three times a week.",
    commonErrors: [
      "Rushing the lowering phase",
      "Slumping back in the chair",
      "Doing it every day without recovery days",
    ],
    regression: "One round, fewer repetitions, no band.",
    progression: "Add ankle weights and a heavier band, then progress to standing exercises.",
    precautions: [
      "Use a stable, non-rolling chair.",
      "Follow any post-operative loading restrictions.",
      "Leave at least one recovery day between sessions.",
    ],
  },
  {
    id: "full-body-resistance-circuit",
    name: "Full-Body Resistance Circuit",
    aka: ["Home strength circuit", "General strengthening circuit"],
    region: "General Conditioning",
    category: "Strength",
    positions: ["Standing", "Supine"],
    equipment: ["Resistance band", "Chair", "Weight"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Quadriceps", "Gluteals", "Back", "Shoulder girdle", "Trunk"],
    indications: ["General deconditioning", "Return to work or sport", "Osteoporosis-related strength maintenance", "Maintenance after discharge"],
    setup: "Enough space to stand and lie down, with a chair, a resistance band, and any available weights.",
    steps: [
      "Sit to stand from a chair — a squat pattern.",
      "Band row — a horizontal pull.",
      "Wall or counter push-up — a horizontal push.",
      "Glute bridge — a hip hinge and extension pattern.",
      "A carry or a plank hold — a trunk and grip challenge.",
      "Rest sixty seconds between exercises and complete the whole circuit twice or three times.",
    ],
    dosage: { sets: "2–3 rounds", reps: "8–12 per exercise", frequency: "2–3x/week", loadOrTempo: "A load where the last 2 repetitions are genuinely hard but form holds" },
    cue: "“Pick a load where the last two reps are hard but still look the same as the first two — that's the whole art of it.”",
    patientInstructions:
      "Go through these five, eight to twelve repetitions each, resting a minute between: stand up and sit down from a chair; pull a resistance band back toward you; push away from a wall or counter; lift your hips into a bridge lying down; and either carry a weight for twenty metres or hold a plank. Repeat the whole circuit two or three times, two or three times a week.",
    commonErrors: [
      "Choosing loads so light the last repetitions are easy",
      "Choosing loads so heavy the form breaks down",
      "Training on consecutive days without recovery",
      "Dropping the circuit as soon as symptoms settle — this is the maintenance work",
    ],
    regression: "One round, easier variations of each pattern, longer rests.",
    progression: "Heavier loads, more rounds, shorter rests, then single-limb variations.",
    precautions: [
      "Not appropriate while symptoms are highly irritable — build up through the specific exercises first.",
      "Follow post-operative loading restrictions.",
      "Take care with loaded spinal flexion where osteoporosis is significant.",
      "Leave at least one recovery day between sessions.",
    ],
  },
  {
    id: "morning-mobility-flow",
    name: "Morning Mobility Flow",
    aka: ["Wake-up mobility routine", "Morning stiffness routine"],
    region: "General Conditioning",
    category: "Mobility",
    positions: ["Supine", "Quadruped", "Standing"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Spine", "Hips", "Shoulders", "General mobility"],
    indications: ["Morning stiffness", "Inflammatory arthritis", "Osteoarthritis", "Persistent back or neck pain"],
    setup: "Do it in bed or on the floor beside the bed, before getting up and starting the day.",
    steps: [
      "In bed: ankle pumps, then knees rocking gently side to side, then single knee to chest each side.",
      "Sitting on the edge of the bed: shoulder rolls, then gentle neck turns each way.",
      "Standing: a few gentle back bends with hands on the low back, then a slow march on the spot.",
      "Move gently and stay well within comfort — this is a wake-up, not a workout.",
    ],
    dosage: { sets: "1", reps: "8–10 of each movement", frequency: "Every morning" },
    cue: "“Do this before your feet hit the floor — the point is to move before you have to, not after you've seized up.”",
    patientInstructions:
      "Before you get out of bed, pump your ankles, rock your knees gently side to side, and bring each knee toward your chest in turn. Sitting on the edge of the bed, roll your shoulders and turn your head gently each way. Standing, do a few gentle backwards leans with your hands on your lower back and march on the spot. Eight to ten of each, every morning.",
    commonErrors: [
      "Skipping it on stiff mornings, which are exactly the mornings it helps most",
      "Turning it into a stretching session and pushing into range",
      "Getting up quickly afterward when prone to dizziness",
    ],
    regression: "Do the in-bed movements only.",
    progression: "Add the specific exercises from the rest of the program after the flow.",
    precautions: [
      "Get up slowly if prone to dizziness on standing.",
      "Keep the range gentle — morning is often when tissues are least tolerant.",
      "Adjust the movements to fit any post-operative precautions.",
    ],
  },
  {
    id: "desk-movement-break",
    name: "Desk Movement Break",
    aka: ["Postural break", "Sitting break routine"],
    region: "General Conditioning",
    category: "Mobility",
    positions: ["Seated", "Standing"],
    equipment: ["Chair"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Cervical spine", "Thoracic spine", "Lumbar spine", "Hip flexors"],
    indications: ["Desk-related neck and back pain", "Prolonged sitting", "Return to office work", "Postural fatigue"],
    setup: "No equipment beyond the chair already being sat in. Set a reminder — the reminder is the intervention.",
    steps: [
      "Stand up.",
      "Do a few standing back bends with the hands on the low back.",
      "Do a few chin tucks and shoulder rolls.",
      "Take twenty steps or walk to fill a glass of water.",
      "Sit back down and reset the reminder.",
    ],
    dosage: { sets: "1", reps: "5–8 of each movement", frequency: "Every 30–60 minutes of sitting" },
    cue: "“The best posture is the next one — the frequency matters far more than what you actually do in the break.”",
    patientInstructions:
      "Every half hour to an hour of sitting, stand up. Do five to eight gentle backwards leans with your hands on your lower back, a few chin tucks and shoulder rolls, then take twenty steps or walk to get a drink. Sit back down. Setting a reminder on your phone is the part that actually makes this work.",
    commonErrors: [
      "Skipping breaks on busy days, which are the days sitting is longest",
      "Making the break long and elaborate, which makes it easy to skip",
      "Focusing on finding a perfect sitting posture rather than on changing position regularly",
    ],
    regression: "Do the movements seated without standing up.",
    progression: "Add a longer walk, or a set of sit-to-stands each break.",
    precautions: [
      "Adapt the movements to any directional preference — someone whose symptoms worsen with back bending should use a different movement in the break.",
      "Stand up slowly if prone to dizziness.",
    ],
  },
  {
    id: "graded-activity-pacing",
    name: "Graded Activity and Pacing",
    aka: ["Activity pacing", "Quota-based activity", "Baseline and build"],
    region: "General Conditioning",
    category: "Endurance",
    positions: ["Standing", "Seated"],
    equipment: ["None"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Activity tolerance", "Load management"],
    indications: ["Persistent pain", "Boom-and-bust activity pattern", "Return to work", "Fatigue-limited conditions", "Post-operative return to daily activity"],
    setup: "Pick one specific activity that currently triggers a flare — standing at the sink, gardening, sitting at a desk, walking the dog.",
    steps: [
      "Find the baseline: the amount that can be done on a *bad* day without a flare afterward. Often this is about half of what feels possible on a good day.",
      "Do that amount every day, regardless of how good or bad the day is — including on good days, when the temptation is to do more.",
      "After a week without flares, increase by about ten percent.",
      "After a flare, return to the last level that was tolerated and hold there for an extra week.",
    ],
    dosage: { sets: "1", reps: "", frequency: "Daily", loadOrTempo: "Baseline set by a bad day; increase ~10% per symptom-free week" },
    cue: "“The hardest part is doing less on your good days — that's what stops the crash that follows.”",
    patientInstructions:
      "Pick one activity that tends to set you back. Work out how much of it you could do on a bad day without paying for it afterwards — that is your starting amount. Do that same amount every day, including on good days, even though you will feel able to do more. After a week with no flares, increase it by about ten percent. If you do have a flare, go back to the last amount that was fine and stay there an extra week.",
    commonErrors: [
      "Setting the baseline from a good day",
      "Doing more on good days, which produces the crash that follows",
      "Stopping the activity entirely after a flare rather than returning to the last tolerated level",
      "Trying to pace several activities at once instead of starting with one",
    ],
    regression: "Halve the baseline, or split it into two shorter blocks in the day.",
    progression: "Increase by roughly ten percent per symptom-free week, then add a second activity to the plan.",
    precautions: [
      "New symptoms — rather than the familiar ones — need assessment rather than pacing.",
      "This is a strategy, not a stand-alone treatment: it works alongside the specific exercises, not instead of them.",
    ],
  },
];
