import type { MovementExercise } from "@/lib/movement-lab/types";

/** Hip and pelvis. Carries the gluteal progression that shows up in almost every lower-limb
 *  and low back program in the bank, which is why the bridge and abduction families each get
 *  several graded entries rather than one. */
export const HIP_EXERCISES: MovementExercise[] = [
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    aka: ["Bridging", "Double-leg bridge", "Hip lift"],
    region: "Hip & Pelvis",
    category: "Strength",
    positions: ["Supine"],
    equipment: ["None"],
    difficulty: 2,
    phases: ["Acute / Protected", "Subacute / Restore", "Strengthening"],
    targets: ["Gluteus maximus", "Hamstrings", "Lumbar extensors"],
    indications: ["Low back pain", "Gluteal weakness", "Post-operative hip and knee rehabilitation", "Sit-to-stand difficulty"],
    setup: "Lie on the back with the knees bent, feet flat and hip-width apart, heels about a hand's length from the buttocks.",
    steps: [
      "Squeeze the buttocks first, before anything moves.",
      "Lift the hips until the body forms a straight line from the shoulders to the knees.",
      "Hold at the top without arching the low back past that line.",
      "Lower slowly, one vertebra at a time, and rest briefly.",
    ],
    dosage: { sets: "2–3", reps: "10–15", hold: "3–5 s", frequency: "Once daily", loadOrTempo: "Squeeze first, lift in 2 s, lower in 3 s" },
    cue: "“Squeeze your buttocks first, then lift — stop when your body is a straight ramp, not an arch.”",
    patientInstructions:
      "Lie on your back with your knees bent and feet flat, hip-width apart. Squeeze your buttocks, then lift your hips until your body makes a straight line from your shoulders to your knees. Hold three to five seconds, then lower slowly. Ten to fifteen repetitions.",
    commonErrors: [
      "Lifting so high the low back arches",
      "Pushing through the toes instead of the whole foot",
      "Letting the knees fall apart or drift together",
      "Feeling it mainly in the hamstrings, which usually means the feet are too far away",
    ],
    regression: "Lift a smaller distance, or do a posterior pelvic tilt only.",
    progression: "Bridge with March, then Single-Leg Bridge, then add weight across the hips.",
    precautions: [
      "Respect hip precautions after hip replacement.",
      "Hamstring cramping usually means the feet need to come closer to the buttocks.",
    ],
  },
  {
    id: "bridge-march",
    name: "Bridge with March",
    aka: ["Marching bridge", "Bridge with alternating leg lift"],
    region: "Hip & Pelvis",
    category: "Motor Control",
    positions: ["Supine"],
    equipment: ["None"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Gluteus maximus", "Gluteus medius", "Hamstrings", "Trunk stabilisers"],
    indications: ["Gluteal weakness", "Pelvic control deficit", "Progression from a double-leg bridge"],
    setup: "Set up and hold a standard glute bridge with the hips lifted.",
    steps: [
      "Hold the bridge position throughout — the hips do not lower between repetitions.",
      "Lift one foot a few inches off the floor, keeping the knee bent.",
      "Keep the pelvis completely level — no dipping on the lifted side.",
      "Replace the foot and repeat on the other side.",
    ],
    dosage: { sets: "2–3", reps: "6–10 each side", frequency: "Every other day", loadOrTempo: "Slow — a dropped hip ends the set" },
    cue: "“Keep your hips level as you lift each foot — if one side drops, that's the end of the set.”",
    patientInstructions:
      "Lift your hips into a bridge and hold it there. Lift one foot a few inches off the floor without letting your hips drop or twist, then put it down and lift the other. Six to ten each side, keeping the bridge up the whole time.",
    commonErrors: [
      "Letting the pelvis drop or rotate as the foot lifts",
      "Lowering the hips between repetitions",
      "Lifting the foot too high",
      "Holding the breath",
    ],
    regression: "Plain glute bridge, or lift only the heel a couple of inches.",
    progression: "Single-Leg Bridge.",
    precautions: [
      "Respect hip precautions after hip replacement.",
      "Stop for cramping or low back pain rather than pushing to the rep count.",
    ],
  },
  {
    id: "single-leg-bridge",
    name: "Single-Leg Bridge",
    region: "Hip & Pelvis",
    category: "Strength",
    positions: ["Supine"],
    equipment: ["None"],
    difficulty: 4,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Gluteus maximus", "Hamstrings", "Gluteus medius"],
    indications: ["Gluteal strength deficit", "Return to running", "Late-stage hip and knee rehabilitation"],
    setup: "Lie on the back with one knee bent and that foot flat. Extend the other leg straight, or hold that knee toward the chest.",
    steps: [
      "Squeeze the buttock of the working side.",
      "Lift the hips using only the planted leg until the body forms a straight line.",
      "Keep the pelvis level throughout — both hip bones stay at the same height.",
      "Lower slowly under control.",
    ],
    dosage: { sets: "2–3", reps: "8–12 each side", hold: "2–3 s", frequency: "Every other day", loadOrTempo: "2 s up, 3 s down" },
    cue: "“One leg does all the work — keep both hip bones level the whole way up and down.”",
    patientInstructions:
      "Lie on your back with one knee bent and that foot flat. Straighten your other leg or hold that knee toward your chest. Push through the planted foot to lift your hips into a straight line, keeping your hips level. Lower slowly. Eight to twelve repetitions on each side.",
    commonErrors: [
      "The pelvis dropping on the non-weight-bearing side",
      "Arching the low back to gain height",
      "Pushing through the toes rather than the whole foot",
      "Hamstring cramping from having the foot too far from the buttock",
    ],
    regression: "Bridge with March, or a double-leg bridge with more weight on one side.",
    progression: "Elevate the planted foot on a step, add a weight across the hips, or hold longer at the top.",
    precautions: [
      "Respect hip precautions after hip replacement.",
      "Not appropriate while a hamstring strain is still symptomatic under load.",
    ],
  },
  {
    id: "clamshell",
    name: "Clamshell",
    aka: ["Sidelying hip external rotation", "Clam"],
    region: "Hip & Pelvis",
    category: "Activation",
    positions: ["Sidelying"],
    equipment: ["None", "Resistance band"],
    difficulty: 2,
    phases: ["Acute / Protected", "Subacute / Restore", "Strengthening"],
    targets: ["Gluteus medius", "Gluteus minimus", "Hip external rotators"],
    indications: ["Gluteal weakness", "Patellofemoral pain", "Iliotibial band related lateral knee pain", "Hip and low back pain"],
    setup: "Lie on one side with the hips and knees bent to about 45 and 90 degrees, feet together, hips stacked directly over each other and the back against a wall if available.",
    steps: [
      "Keep the feet touching throughout.",
      "Lift the top knee upward, opening the knees like a clam.",
      "Stop the moment the pelvis starts to roll backward — that is the end of the range.",
      "Lower slowly with control.",
    ],
    dosage: { sets: "2–3", reps: "10–15 each side", hold: "2 s at the top", frequency: "Once daily" },
    cue: "“Keep your feet together and your hips stacked — if your top hip rolls back, you've gone too far.”",
    patientInstructions:
      "Lie on your side with your knees bent and feet together, hips stacked one over the other. Keeping your feet touching, lift your top knee upward like a clam opening. Stop before your hips start to roll backwards. Lower slowly. Ten to fifteen repetitions each side.",
    commonErrors: [
      "Rolling the pelvis backward to open the knee further",
      "Letting the feet separate",
      "Lying with the hips rolled rather than stacked",
      "Going fast enough that the movement becomes a swing",
    ],
    regression: "Reduce the range and hold the position without the band.",
    progression: "Add a band above the knees, then progress to sidelying hip abduction with a straight leg.",
    precautions: [
      "Respect hip precautions after hip replacement — this position may not be permitted early.",
      "Stop if it reproduces pinching at the front of the hip.",
    ],
  },
  {
    id: "sidelying-hip-abduction",
    name: "Sidelying Hip Abduction",
    aka: ["Straight leg raise to the side", "Side-lying leg lift"],
    region: "Hip & Pelvis",
    category: "Strength",
    positions: ["Sidelying"],
    equipment: ["None", "Weight"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Gluteus medius", "Gluteus minimus", "Tensor fascia latae"],
    indications: ["Hip abductor weakness", "Trendelenburg gait", "Lateral hip pain", "Patellofemoral pain"],
    setup: "Lie on one side with the bottom knee bent for stability and the top leg straight, in line with the trunk. Stack the hips.",
    steps: [
      "Turn the top hip so the toes point slightly downward, not up at the ceiling.",
      "Lift the top leg upward, taking it slightly behind the line of the body.",
      "Stop at about 30–45 degrees or when the pelvis starts to tilt.",
      "Lower slowly without letting the leg drop.",
    ],
    dosage: { sets: "2–3", reps: "10–15 each side", frequency: "Every other day", loadOrTempo: "2 s up, 3 s down; add a 1–3 lb ankle weight later" },
    cue: "“Lead with your heel, toes pointing slightly down, and take the leg a little behind you — not up in front.”",
    patientInstructions:
      "Lie on your side with the bottom knee bent and the top leg straight. Point your top toes slightly down toward the floor, then lift that leg up and very slightly backwards. Lower it slowly without letting it drop. Ten to fifteen repetitions each side.",
    commonErrors: [
      "Letting the leg drift forward, which uses the hip flexor instead of the gluteals",
      "Rolling the pelvis backward",
      "Turning the toes up to the ceiling",
      "Lifting too high, which tilts the pelvis",
    ],
    regression: "Clamshell, or a smaller lift with the leg supported on a pillow.",
    progression: "Add an ankle weight, add a hold at the top, or progress to standing band abduction.",
    precautions: [
      "Respect hip precautions after hip replacement.",
      "Reduce range if it reproduces lateral hip pain over the greater trochanter — gluteal tendinopathy often does not tolerate end-range abduction early.",
    ],
  },
  {
    id: "standing-band-hip-abduction",
    name: "Standing Band Hip Abduction",
    region: "Hip & Pelvis",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Resistance band", "Chair"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Gluteus medius", "Gluteus minimus", "Stance-leg stabilisers"],
    indications: ["Hip abductor weakness", "Single-leg stance control", "Return to walking or running"],
    setup: "Loop a band around both ankles. Stand tall holding a chair or counter for light balance support.",
    steps: [
      "Set the standing hip and keep the trunk upright.",
      "Take the working leg out to the side, keeping the knee straight and the toes forward.",
      "Stop before the trunk leans away — the movement belongs to the hip.",
      "Return slowly against the band.",
      "The standing leg is working just as hard as the moving one.",
    ],
    dosage: { sets: "2–3", reps: "10–15 each side", frequency: "Every other day", loadOrTempo: "Controlled; band tension where form holds for all reps" },
    cue: "“Stand tall and take the leg out sideways — don't lean away from it, and keep your toes pointing forward.”",
    patientInstructions:
      "Loop a band around both ankles and hold a counter for balance. Standing tall, take one leg out to the side with the knee straight and toes pointing forward. Bring it back slowly. Keep your body upright rather than leaning. Ten to fifteen repetitions each side.",
    commonErrors: [
      "Leaning the trunk away from the moving leg",
      "Turning the toes out, which recruits the hip flexor",
      "Letting the band snap the leg back",
      "Leaning heavily on the support hand",
    ],
    regression: "No band, or hold the support with both hands.",
    progression: "Heavier band, band at the knees for greater demand, or remove the hand support.",
    precautions: [
      "Needs adequate standing balance — use a stable support, not a rolling chair.",
      "Respect hip precautions after hip replacement.",
    ],
  },
  {
    id: "lateral-band-walk",
    name: "Lateral Band Walk",
    aka: ["Monster walk", "Side-stepping with a band"],
    region: "Hip & Pelvis",
    category: "Endurance",
    positions: ["Standing"],
    equipment: ["Resistance band"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Gluteus medius", "Gluteus minimus", "Gluteus maximus"],
    indications: ["Hip abductor endurance deficit", "Patellofemoral pain", "Return to running", "Knee valgus control"],
    setup: "Loop a band around both legs just above the knees or around the ankles. Stand in a quarter-squat with the feet hip-width apart and the toes forward.",
    steps: [
      "Hold the quarter-squat throughout — do not stand up between steps.",
      "Step sideways with the leading leg, keeping tension on the band.",
      "Bring the trailing leg across slowly, never letting it snap in.",
      "Keep the knees tracking over the toes and the trunk upright.",
    ],
    dosage: { sets: "2–3", reps: "10–12 steps each direction", frequency: "Every other day", loadOrTempo: "Slow and controlled, band tension maintained throughout" },
    cue: "“Stay low, toes forward, and don't let the trailing leg snap in — control it across.”",
    patientInstructions:
      "Put a band around your legs just above your knees. Stand with your feet hip-width apart and squat down slightly. Staying low, step sideways ten to twelve steps in one direction, then back. Keep tension on the band and don't let your trailing leg snap in.",
    commonErrors: [
      "Standing up out of the squat between steps",
      "Letting the knees collapse inward",
      "Letting the trailing leg snap across",
      "Leaning the trunk side to side",
    ],
    regression: "Lighter band, band above the knees rather than at the ankles, and fewer steps.",
    progression: "Heavier band, band moved to the ankles, or a deeper squat position.",
    precautions: [
      "Stop for lateral hip pain over the bony point of the hip.",
      "Reduce the squat depth if it aggravates the knee.",
    ],
  },
  {
    id: "prone-hip-extension",
    name: "Prone Hip Extension",
    aka: ["Prone leg lift", "Gluteus maximus lift"],
    region: "Hip & Pelvis",
    category: "Strength",
    positions: ["Prone"],
    equipment: ["None", "Weight"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Gluteus maximus", "Hamstrings"],
    indications: ["Gluteal weakness", "Low back pain with poor hip extension", "Post-operative hip rehabilitation"],
    setup: "Lie face down with a pillow under the pelvis and the arms folded under the forehead.",
    steps: [
      "Squeeze the buttock on the working side.",
      "Lift the straight leg a few inches off the surface — the movement is small.",
      "Keep the pelvis pressed into the pillow so the low back does not arch.",
      "Lower slowly.",
    ],
    dosage: { sets: "2–3", reps: "10–12 each side", hold: "2–3 s", frequency: "Once daily", loadOrTempo: "Small range; add a 1–3 lb ankle weight later" },
    cue: "“Squeeze the buttock first and lift the leg only a few inches — your low back should stay completely still.”",
    patientInstructions:
      "Lie face down with a pillow under your hips. Squeeze your buttock, then lift one straight leg a few inches off the surface. Keep your back still. Hold a couple of seconds and lower slowly. Ten to twelve repetitions each side.",
    commonErrors: [
      "Lifting the leg high, which arches the low back",
      "Bending the knee, which shifts the work to the hamstring",
      "Rotating the pelvis to gain height",
    ],
    regression: "Squeeze the buttock with no leg lift at all — a gluteal isometric.",
    progression: "Add an ankle weight, or progress to quadruped hip extension.",
    precautions: [
      "Respect hip precautions after hip replacement.",
      "Stop if it increases low back pain — the range is likely too large.",
    ],
  },
  {
    id: "quadruped-hip-extension",
    name: "Quadruped Hip Extension",
    aka: ["Donkey kick", "Four-point hip extension"],
    region: "Hip & Pelvis",
    category: "Strength",
    positions: ["Quadruped"],
    equipment: ["None"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Gluteus maximus", "Hamstrings", "Trunk stabilisers"],
    indications: ["Gluteal weakness", "Hip extension deficit", "Low back pain with poor hip control"],
    setup: "Start on hands and knees with the spine neutral and a light abdominal contraction set.",
    steps: [
      "Keeping the knee bent to 90 degrees, lift one leg by pressing the sole of the foot toward the ceiling.",
      "Stop when the thigh is level with the trunk — no higher.",
      "Keep the pelvis level and the low back still.",
      "Lower under control.",
    ],
    dosage: { sets: "2–3", reps: "10–12 each side", hold: "2 s", frequency: "Every other day" },
    cue: "“Press your heel at the ceiling and stop when your thigh is level with your back — the low back does nothing.”",
    patientInstructions:
      "On your hands and knees, keep your tummy gently tight. Keeping one knee bent, press that foot up toward the ceiling until your thigh is level with your body. Keep your back still. Lower it slowly. Ten to twelve repetitions each side.",
    commonErrors: [
      "Lifting the leg high so the low back arches",
      "Rotating the pelvis toward the lifting side",
      "Straightening the knee, which changes the exercise",
    ],
    regression: "Prone hip extension, which removes the balance and trunk demand.",
    progression: "Add an ankle weight, or combine with a bird dog.",
    precautions: [
      "Needs comfortable weight-bearing through the wrists and knees.",
      "Respect hip precautions after hip replacement.",
    ],
  },
  {
    id: "hip-adduction-squeeze",
    name: "Hip Adduction Squeeze",
    aka: ["Ball squeeze", "Adductor isometric"],
    region: "Hip & Pelvis",
    category: "Activation",
    positions: ["Supine", "Seated"],
    equipment: ["Ball"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Adductor group", "Pelvic floor", "Lower abdominals"],
    indications: ["Groin strain (once settling)", "Adductor-related groin pain", "Pelvic girdle pain", "Post-partum pelvic support"],
    setup: "Lie on the back with the knees bent and feet flat. Place a ball or folded pillow between the knees.",
    steps: [
      "Squeeze the ball with the inner thighs, building the effort over a second or two.",
      "Hold at a comfortable, submaximal effort while breathing normally.",
      "Release gradually rather than letting go suddenly.",
    ],
    dosage: { sets: "2–3", reps: "10", hold: "5–10 s", frequency: "Once daily", loadOrTempo: "Start at about 30–50% effort and build over weeks" },
    cue: "“Squeeze the ball to about half effort — build it up and let it go slowly, don't snap it on.”",
    patientInstructions:
      "Lie on your back with your knees bent and a ball or folded pillow between your knees. Squeeze the ball with your inner thighs at about half effort, hold five to ten seconds, then let go slowly. Ten repetitions.",
    commonErrors: [
      "Going straight to maximum effort, which often flares an irritable groin",
      "Holding the breath",
      "Snapping the contraction on and off",
      "Bracing hard through the low back",
    ],
    regression: "Lower effort and shorter hold; use a softer ball.",
    progression: "Increase the effort gradually, extend the hold, then progress to a modified Copenhagen adduction hold.",
    precautions: [
      "Build effort gradually where there is an acute groin strain — a maximal squeeze early is a common way to set it back.",
      "Stop for sharp groin pain rather than working through it.",
    ],
  },
  {
    id: "copenhagen-adduction-modified",
    name: "Copenhagen Adduction (Short Lever)",
    aka: ["Sidelying adductor plank", "Short-lever Copenhagen"],
    region: "Hip & Pelvis",
    category: "Strength",
    positions: ["Sidelying"],
    equipment: ["Chair", "Step or stairs"],
    difficulty: 4,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Adductor group", "Obliques", "Gluteus medius"],
    indications: ["Adductor-related groin pain", "Return to kicking or change-of-direction sport", "Adductor strength deficit"],
    setup: "Lie on one side propped on the forearm, with the inside of the top knee resting on a bench, chair seat, or low step. The bottom leg rests on the floor.",
    steps: [
      "Press the inside of the top knee down into the bench.",
      "Lift the hips and the bottom leg off the floor so the body forms a straight line.",
      "Hold, keeping the trunk from rotating.",
      "Lower under control.",
    ],
    dosage: { sets: "2–3", reps: "6–10 each side", hold: "3–5 s", frequency: "2x/week", loadOrTempo: "Slow lowering; short lever first" },
    cue: "“Drive your top knee into the bench and lift everything else off the floor — one straight line, no twisting.”",
    patientInstructions:
      "Lie on your side propped on your forearm with the inside of your top knee resting on a chair seat or low bench. Push that knee down into the bench and lift your hips and bottom leg off the floor into a straight line. Hold a few seconds, then lower. Six to ten repetitions each side, twice a week.",
    commonErrors: [
      "Progressing to the long-lever version (foot on the bench) before the short lever is comfortable",
      "Letting the hips sag or the trunk rotate",
      "Doing it too often — the adductors need recovery between sessions",
    ],
    regression: "Hip Adduction Squeeze isometrics, or hold the position without lifting the bottom leg.",
    progression: "Copenhagen Plank (Long Lever), with the ankle rather than the knee on the bench.",
    precautions: [
      "A late-stage exercise — not appropriate while a groin strain is still acutely painful.",
      "Needs the shoulder to tolerate side-support loading.",
      "Expect delayed soreness; twice a week is usually enough.",
    ],
  },
  {
    id: "copenhagen-plank-long-lever",
    name: "Copenhagen Plank (Long Lever)",
    aka: ["Copenhagen plank", "Long-lever Copenhagen", "Copenhagen adduction", "Adductor side plank"],
    region: "Hip & Pelvis",
    category: "Strength",
    positions: ["Sidelying"],
    equipment: ["Chair", "Step or stairs"],
    difficulty: 5,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Adductor group", "Obliques", "Gluteus medius", "Shoulder girdle stabilisers"],
    indications: ["Adductor-related groin pain", "Groin injury prevention in kicking and change-of-direction sport", "Adductor strength deficit at the end of rehabilitation", "Return to sport after adductor strain"],
    setup: "Lie on one side propped on the forearm, shoulder stacked over the elbow, with the ankle or lower shin of the top leg resting on a bench, chair seat or low step at roughly hip height. The bottom leg rests on the floor beneath it.",
    steps: [
      "Press the top ankle down into the bench and set the shoulder before anything lifts.",
      "Lift the hips and the bottom leg clear of the floor so head, hips and feet form one straight line.",
      "Bring the bottom leg up to meet the top leg and hold briefly.",
      "Keep the hips stacked — the trunk should not roll forward or back.",
      "Lower under control to the floor rather than dropping, and reset before the next repetition.",
    ],
    dosage: { sets: "3", reps: "6–12 each side", hold: "2–3 s", frequency: "2x/week", loadOrTempo: "Slow lowering; build repetitions over several weeks before adding sessions" },
    cue: "“Drive the top ankle into the bench and lift everything else into one straight line — hips stacked, no rolling.”",
    patientInstructions:
      "Lie on your side propped on your forearm with the ankle of your top leg resting on a bench or chair seat at about hip height. Press that ankle down and lift your hips and bottom leg off the floor so your body makes one straight line, bringing your bottom leg up to meet the top one. Hold for a couple of seconds, then lower slowly. Six to twelve repetitions on each side, twice a week. Expect this to make you sore for a day or two at first, so build the repetitions up gradually rather than doing as many as you can straight away.",
    commonErrors: [
      "Moving up from the short-lever version before it is genuinely comfortable, which is where most of the soreness and failed sets come from",
      "Letting the hips sag or the trunk rotate so the line is lost",
      "Dropping to the floor instead of lowering under control — the lowering phase is most of the exercise",
      "Doing it more than twice a week; the adductors need the recovery",
      "A support surface well above or below hip height, which changes the exercise rather than scaling it",
      "Loading the shoulder past what it will tolerate in side support",
    ],
    regression: "Copenhagen Adduction (Short Lever), with the knee rather than the ankle on the bench; or hold the top position without lifting the bottom leg.",
    progression: "More repetitions, then a longer hold, then a higher support surface; add a weight vest once bodyweight repetitions are easy and unhurried.",
    precautions: [
      "Expect marked delayed-onset soreness for the first few weeks — this is the exercise's known signature, and the reason volume is built gradually rather than maximised on day one.",
      "A late-stage exercise: not appropriate while a groin strain is still acutely painful.",
      "Needs the shoulder to tolerate side-support loading — stop for shoulder rather than adductor symptoms.",
      "Twice a week is usually enough; stacking sessions is the common way this one causes a problem.",
      "Earn it from the short lever first rather than starting here.",
    ],
    note: "The adductor exercise that widely-published groin injury-prevention programmes in football are built around; the short-lever version is the same exercise at a shorter lever, not a different one.",
  },
  {
    id: "half-kneeling-hip-flexor-stretch",
    name: "Half-Kneeling Hip Flexor Stretch",
    aka: ["Lunge stretch", "Kneeling psoas stretch"],
    region: "Hip & Pelvis",
    category: "Flexibility",
    positions: ["Half-kneeling"],
    equipment: ["None", "Chair"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Iliopsoas", "Rectus femoris", "Anterior hip"],
    indications: ["Hip flexor tightness", "Loss of hip extension", "Low back pain with an anterior pelvic tilt", "Post-operative hip stiffness"],
    setup: "Kneel on one knee with the other foot flat in front, both knees at about 90 degrees. A cushion under the down knee helps.",
    steps: [
      "Tuck the tailbone under — a posterior pelvic tilt — before moving forward at all.",
      "Squeeze the buttock on the kneeling side.",
      "Shift the body weight gently forward until a stretch is felt at the front of the kneeling hip.",
      "Hold, breathing normally, keeping the tailbone tucked.",
    ],
    dosage: { sets: "2–3", reps: "1 each side", hold: "30 s", frequency: "Once daily" },
    cue: "“Tuck your tailbone under and squeeze that buttock first — then just lean forward an inch. Most people don't need to go far.”",
    patientInstructions:
      "Kneel on one knee with your other foot flat in front of you, using a cushion under your knee. Tuck your tailbone under and squeeze the buttock on the kneeling side. Now shift your weight gently forwards until you feel a stretch at the front of the kneeling hip. Hold thirty seconds. Two or three times each side.",
    commonErrors: [
      "Lunging far forward without the pelvic tuck, which arches the low back instead of stretching the hip",
      "Letting the front knee travel far past the toes",
      "Losing the tailbone tuck as the lean increases",
    ],
    regression: "Do it standing in a split stance, or lying on the back at the edge of a bed with the leg hanging off.",
    progression: "Add an overhead reach on the kneeling side, or add a gentle side bend away.",
    precautions: [
      "Not appropriate where kneeling is painful or after knee replacement until cleared.",
      "Respect hip precautions after hip replacement.",
      "Stop for pinching at the front of the hip, which is not the intended stretch.",
    ],
  },
  {
    id: "supine-figure-4-stretch",
    name: "Supine Figure-4 Stretch",
    aka: ["Piriformis stretch", "Thread-the-needle hip stretch"],
    region: "Hip & Pelvis",
    category: "Flexibility",
    positions: ["Supine"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Piriformis", "Deep hip external rotators", "Gluteus maximus"],
    indications: ["Buttock pain", "Deep hip rotator tightness", "Low back pain with hip restriction"],
    setup: "Lie on the back with the knees bent and feet flat.",
    steps: [
      "Cross one ankle over the opposite thigh just above the knee, making a figure four.",
      "Reach through the gap and hold behind the supporting thigh.",
      "Draw the supporting thigh toward the chest until a stretch is felt deep in the buttock of the crossed leg.",
      "Keep the head and shoulders relaxed on the floor.",
    ],
    dosage: { sets: "2–3", reps: "1 each side", hold: "30 s", frequency: "1–2x/day" },
    cue: "“Make a figure four, then pull the bottom thigh toward you — the stretch belongs deep in the buttock, not in the knee.”",
    patientInstructions:
      "Lie on your back with your knees bent. Cross one ankle over your opposite thigh, just above the knee. Reach through the gap, hold behind the lower thigh, and draw it toward your chest until you feel a stretch deep in your buttock. Hold thirty seconds. Two or three times each side.",
    commonErrors: [
      "Pushing down on the crossed knee, which stresses the knee rather than the hip",
      "Lifting the head and shoulders off the floor",
      "Holding the breath",
    ],
    regression: "Do it seated in a chair, crossing the ankle over the knee and leaning forward gently.",
    progression: "Hold longer, or add a gentle push on the crossed thigh — never on the knee itself.",
    precautions: [
      "Respect hip precautions after hip replacement — this position combines flexion, adduction and rotation.",
      "Stop for knee pain, which means the force is going through the wrong joint.",
      "Reduce the range if it reproduces leg symptoms.",
    ],
  },
  {
    id: "supine-hamstring-stretch",
    name: "Supine Hamstring Stretch",
    aka: ["Strap hamstring stretch", "Doorway hamstring stretch"],
    region: "Hip & Pelvis",
    category: "Flexibility",
    positions: ["Supine"],
    equipment: ["Towel or strap"],
    difficulty: 1,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Hamstrings"],
    indications: ["Hamstring tightness", "Low back pain with hamstring restriction", "Post-hamstring-strain flexibility"],
    setup: "Lie on the back with both knees bent. Loop a strap or towel around the arch of one foot.",
    steps: [
      "Straighten that leg upward, holding the strap, keeping the other knee bent with the foot flat.",
      "Raise the leg until a comfortable stretch is felt behind the thigh.",
      "Keep the knee straight but not locked hard, and the low back relaxed.",
      "Hold, then lower slowly.",
    ],
    dosage: { sets: "2–3", reps: "1 each side", hold: "30 s", frequency: "1–2x/day" },
    cue: "“Use the strap so your shoulders and neck stay relaxed — you should feel a long pull behind your thigh, not a sharp one.”",
    patientInstructions:
      "Lie on your back with both knees bent. Loop a towel around one foot, straighten that leg and raise it until you feel a stretch behind your thigh. Keep your other knee bent with the foot flat. Hold thirty seconds, then lower slowly. Two or three times each side.",
    commonErrors: [
      "Straightening the other leg flat on the floor, which tips the pelvis and usually aggravates the back",
      "Pulling hard enough to feel a sharp or electric sensation, which is a nerve response rather than a stretch",
      "Lifting the head and shoulders off the floor",
    ],
    regression: "Keep the raised knee slightly bent, or do it in a doorway with the leg resting on the frame.",
    progression: "Hold longer, or add a gentle ankle pull toward the shin once the pure stretch is comfortable.",
    precautions: [
      "Sharp, electric, or tingling sensations mean this has become a neural stretch — back off and tell the therapist.",
      "Stay gentle in the early weeks after a hamstring strain.",
    ],
  },
  {
    id: "seated-hip-rotation-90-90",
    name: "Seated 90/90 Hip Rotation",
    aka: ["90/90 hip switch", "Seated hip internal and external rotation"],
    region: "Hip & Pelvis",
    category: "Mobility",
    positions: ["Seated"],
    equipment: ["None"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Hip internal rotators", "Hip external rotators", "Hip capsule"],
    indications: ["Hip rotation restriction", "Femoroacetabular impingement", "Return to rotational sport", "Hip stiffness with low back pain"],
    setup: "Sit on the floor with one leg in front bent to 90 degrees and the other out to the side bent to 90 degrees, forming the 90/90 position. Hands on the floor behind for support.",
    steps: [
      "Sit as tall as the position allows.",
      "Rotate both legs across to the other side, letting the knees lift and turn together.",
      "Land in the mirror-image 90/90 position on the other side.",
      "Move slowly and stay within the range where the trunk can stay upright.",
    ],
    dosage: { sets: "2", reps: "8–10 switches", hold: "3–5 s each side", frequency: "Once daily" },
    cue: "“Turn both legs together like a windscreen wiper and try to stay tall — control it rather than dropping into it.”",
    patientInstructions:
      "Sit on the floor with one leg bent in front of you and the other bent out to the side, both at about right angles. Sit as tall as you can, using your hands behind you for support. Rotate both legs across to the other side and settle into the mirror image position. Move slowly. Eight to ten switches.",
    commonErrors: [
      "Collapsing the trunk backward to gain hip range",
      "Forcing past pinching at the front of the hip",
      "Dropping into the position rather than controlling the switch",
    ],
    regression: "Do it seated in a chair, letting one knee drop in and out, or lying on the back with the feet wide and knees dropping in.",
    progression: "Lift the hands off the floor, add a lift of the back knee, or hold each end position longer.",
    precautions: [
      "Pinching at the front of the hip means reduce the range — that is a joint response, not a stretch.",
      "Not appropriate after hip replacement until cleared, and respect hip precautions.",
      "Needs the ability to get to and up from the floor safely.",
    ],
  },
  {
    id: "sit-to-stand",
    name: "Sit to Stand",
    aka: ["Chair rise", "Sit-to-stand practice"],
    region: "Hip & Pelvis",
    category: "Strength",
    positions: ["Seated", "Standing"],
    equipment: ["Chair"],
    difficulty: 2,
    phases: ["Acute / Protected", "Subacute / Restore", "Strengthening"],
    targets: ["Quadriceps", "Gluteus maximus", "Hamstrings", "Trunk"],
    indications: ["Lower limb weakness", "Post-operative hip and knee rehabilitation", "Falls risk", "Deconditioning", "Older adult functional strength"],
    setup: "Sit on the front half of a firm chair with the feet flat, hip-width apart and slightly behind the knees. Arms crossed on the chest if safe, or on the armrests if support is needed.",
    steps: [
      "Lean the chest forward over the knees — nose over toes.",
      "Push evenly through both feet and stand all the way up tall.",
      "Reach back for the chair with the hips and lower slowly and quietly.",
      "Control the sit — do not drop onto the seat.",
    ],
    dosage: { sets: "2–3", reps: "8–12", frequency: "Once daily", loadOrTempo: "Stand in 2 s, sit in 3–4 s" },
    cue: "“Nose over toes to stand up, and sit down so quietly nobody hears the chair.”",
    patientInstructions:
      "Sit on the front half of a firm chair with your feet flat and slightly back. Lean your chest forwards over your knees, then push through both feet and stand up tall. Sit back down slowly and quietly. Eight to twelve repetitions. Use the armrests if you need to at first.",
    commonErrors: [
      "Pushing up mainly through the stronger leg",
      "Dropping down onto the seat rather than lowering",
      "Using a chair that is too low or too soft",
      "Pulling up on a walking frame instead of pushing through the legs",
    ],
    regression: "Use a higher seat or add a cushion, and push off the armrests.",
    progression: "Lower the seat, cross the arms, slow the lowering phase, or progress to single-leg emphasis.",
    precautions: [
      "Use a stable, non-rolling chair against a wall.",
      "Respect hip precautions after hip replacement — seat height matters.",
      "Stand up slowly if prone to dizziness on standing.",
    ],
  },
  {
    id: "step-up",
    name: "Step-Up",
    aka: ["Forward step-up", "Stair step-up"],
    region: "Hip & Pelvis",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Step or stairs", "Table or counter"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Gluteus maximus", "Quadriceps", "Gluteus medius"],
    indications: ["Stair difficulty", "Single-leg strength deficit", "Post-operative knee and hip rehabilitation", "Return to walking on hills or stairs"],
    setup: "Stand facing a step, holding a rail or counter for balance. Start with a low step and increase the height over time.",
    steps: [
      "Place one whole foot on the step.",
      "Push through that heel to stand up on the step — do not push off the back foot.",
      "Keep the knee tracking over the middle of the foot, not falling inward.",
      "Step back down slowly, touching down softly with the trailing foot.",
    ],
    dosage: { sets: "2–3", reps: "8–12 each side", frequency: "Every other day", loadOrTempo: "Up in 2 s, down in 3 s" },
    cue: "“Push through the heel of the foot that's on the step — the back leg is just along for the ride. Come down quietly.”",
    patientInstructions:
      "Stand facing a step, holding a rail for balance. Put one foot fully on the step and push through that heel to stand up, without pushing off your back foot. Step down slowly and quietly. Eight to twelve repetitions on each leg.",
    commonErrors: [
      "Pushing off the trailing foot to get up",
      "Letting the knee collapse inward",
      "Dropping down rather than lowering with control",
      "Starting with a step that is too high",
    ],
    regression: "Use a lower step, or hold the rail with both hands.",
    progression: "Higher step, hold weights, remove the hand support, or add a lateral step-up.",
    precautions: [
      "Use a stable step and a secure handrail.",
      "Reduce the step height if the knee is painful or the knee is falling inward.",
    ],
  },
  {
    id: "split-squat",
    name: "Split Squat",
    aka: ["Static lunge", "Stationary lunge"],
    region: "Hip & Pelvis",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["None", "Weight", "Chair"],
    difficulty: 4,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Quadriceps", "Gluteus maximus", "Adductors", "Hip stabilisers"],
    indications: ["Single-leg strength deficit", "Return to sport", "Late-stage hip and knee rehabilitation"],
    setup: "Stand in a split stance, one foot forward and one back, feet about hip-width apart side to side. Hold a chair or counter lightly at first.",
    steps: [
      "Lower straight down, bending both knees, until the back knee is close to the floor.",
      "Keep the trunk upright and the weight even between both feet.",
      "Keep the front knee tracking over the middle of the foot.",
      "Push back up through the front foot.",
    ],
    dosage: { sets: "2–3", reps: "8–12 each side", frequency: "Every other day", loadOrTempo: "Down in 3 s, up in 2 s" },
    cue: "“Drop straight down like a lift, not forward like a lunge — and keep your front knee over your foot.”",
    patientInstructions:
      "Stand with one foot forward and one back, about hip-width apart side to side. Lower straight down by bending both knees until your back knee is close to the floor. Keep your body upright. Push back up through the front foot. Eight to twelve repetitions each side. Hold a counter for balance to begin with.",
    commonErrors: [
      "Travelling forward instead of down",
      "Letting the front knee collapse inward",
      "Standing with the feet on a tightrope line, which removes all balance width",
      "Leaning heavily on the support hand rather than using it for light balance",
    ],
    regression: "Reduce the depth, hold the counter with both hands, or use a step-up instead.",
    progression: "Full depth, then add weights, then the Bulgarian Split Squat once the front leg carries the work on its own.",
    precautions: [
      "Reduce depth for anterior knee pain.",
      "Needs adequate balance — use a stable support.",
      "Respect hip precautions after hip replacement.",
    ],
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    aka: ["Rear-foot-elevated split squat", "RFE split squat", "Bulgarian lunge"],
    region: "Hip & Pelvis",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Chair", "Step or stairs", "Weight"],
    difficulty: 4,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Quadriceps", "Gluteus maximus", "Gluteus medius", "Adductors", "Hip flexors of the trailing leg"],
    indications: ["Single-leg strength deficit", "Limb symmetry deficit after ACL reconstruction", "Return to sport", "Late-stage hip and knee rehabilitation", "Patellofemoral pain once loading is tolerated"],
    setup: "Stand a stride's length in front of a chair, bench or step no higher than the knee. Rest the top of the back foot on it and keep the feet about hip-width apart side to side, not on a single line. Hold a counter or wall lightly at first.",
    steps: [
      "Check the stance length first — at the bottom the front shin should be close to vertical and the back knee should travel toward the floor rather than jamming forward.",
      "Lower straight down by bending the front knee, letting the back knee drop toward the floor.",
      "Keep the weight through the front foot; the back leg is a kickstand for balance, not a working leg.",
      "Keep the front knee tracking over the middle of the foot and the hips level.",
      "Drive back up through the front foot to standing.",
      "Complete the set on one side, then swap.",
    ],
    dosage: { sets: "2–3", reps: "6–10 each side", frequency: "Every other day", loadOrTempo: "Down in 3 s, up in 2 s; bodyweight first, then a weight in each hand" },
    cue: "“Your front leg does the work — the back foot is only a kickstand. Drop straight down and keep your hips square.”",
    patientInstructions:
      "Stand about a stride in front of a chair or low bench and rest the top of one foot behind you on it, with your feet about hip-width apart rather than in a line. Holding a counter for balance at first, bend your front knee and lower straight down until your back knee is close to the floor, then push back up through your front foot. Six to ten repetitions on each leg, every other day. Nearly all your weight stays on the front foot — the back leg is only there for balance. If your front knee ends up well past your toes, step further forward and try again.",
    commonErrors: [
      "Standing too close to the bench, which drives the front knee forward and loads the kneecap",
      "Using a bench above knee height, which arches the low back and strains the trailing hip flexor",
      "Pushing off the back foot instead of loading the front leg",
      "Letting the front knee collapse inward",
      "Putting the feet on a single line, which removes the side-to-side balance width",
      "Chasing depth before the balance and control are there",
    ],
    regression: "Split Squat with the back foot on the floor, a lower rear-foot surface, less depth, or both hands on a counter.",
    progression: "Add a weight in each hand, then a front-rack or single-side load; slow the lowering phase further, or pause at the bottom.",
    precautions: [
      "Needs reliable single-leg balance — elevating the back foot removes the balance strategy the split squat still allows, so keep a counter within reach.",
      "Reduce depth for anterior knee pain, and follow the surgeon's protocol on depth and load after knee or hip surgery.",
      "Respect hip precautions after hip replacement — the front hip reaches deep flexion at the bottom.",
      "Cramping in the trailing thigh usually means the stance is too short or the bench too high, not that the exercise is being done badly.",
      "Not a starting exercise — the split squat should be comfortable and controlled at full depth first.",
    ],
  },
  {
    id: "split-stance-back-squat-knee-drive",
    name: "Split-Stance Back Squat with Knee Drive",
    aka: ["Barbell split squat to knee drive", "Loaded split squat with knee drive", "Back-loaded split squat to knee lift"],
    region: "Hip & Pelvis",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Weight"],
    difficulty: 5,
    phases: ["Return to Activity"],
    targets: ["Quadriceps", "Gluteus maximus", "Gluteus medius", "Hip flexors", "Trunk and spinal extensors", "Single-leg balance"],
    indications: ["Late-stage return to sport", "Single-leg strength and drive-phase deficit in running or jumping athletes", "Limb symmetry deficit at the end of a lower-limb rehabilitation programme"],
    setup: "Set a barbell in a rack at upper-chest height with the safety pins in place. Unrack the bar across the upper back with the feet parallel and level, then step back into a split stance — front foot flat, rear foot on the ball of the foot, feet about hip-width apart side to side rather than on a single line.",
    steps: [
      "Brace the trunk and set the ribs down before the first repetition.",
      "Lower straight down, bending both knees, until the back knee is close to the floor and the front shin is near vertical.",
      "Drive up through the front foot to standing, keeping the trunk tall.",
      "As the hips finish extending, drive the trailing knee up and forward to about hip height and balance on the front leg.",
      "Hold the knee-drive position briefly under control — do not swing into it or bounce out of it.",
      "Step the trailing foot back to the same start position and reset before the next repetition.",
      "Complete the set on one side, then rerack the bar and swap.",
    ],
    dosage: { sets: "3–4", reps: "5–8 each side", frequency: "2x/week", loadOrTempo: "Far lighter than a bilateral back squat — an empty bar first, adding load only once the knee drive is balanced and unhurried" },
    cue: "“Stand up through your front foot, then drive the back knee to hip height and hold it a beat before you step back down.”",
    patientInstructions:
      "With a bar resting across your upper back, taken from a rack with your feet level, step back into a staggered stance with your feet about hip-width apart. Lower straight down until your back knee is close to the floor, then push up through your front foot to stand tall. As you finish standing, lift your back knee up in front of you to about hip height and balance there for a moment before stepping it back down. Five to eight repetitions on each leg, twice a week. Use much less weight than you would for a normal squat — the difficulty here is balancing, not lifting. Work inside a rack with the safety bars set, and stop the set while every repetition still looks the same.",
    commonErrors: [
      "Unracking the bar already in a split stance instead of stepping back into it",
      "Loading it like a bilateral back squat, so balance fails before the legs do",
      "Swinging the trailing knee up on momentum rather than driving and holding it",
      "Letting the trunk fold forward as the knee drives up",
      "Standing with the feet on a single line, which removes the side-to-side balance width",
      "Not resetting the rear foot to the same spot between repetitions",
      "Front knee collapsing inward under load",
    ],
    regression: "Drop the bar entirely and do the same movement as a bodyweight or dumbbell split squat with knee drive; or the Bulgarian Split Squat with no knee drive at all.",
    progression: "Add load in small increments, pause longer at the top of the knee drive, or progress toward a loaded step-up with knee drive for the same pattern at greater range.",
    precautions: [
      "Work inside a rack with the safety pins set, and never take a set to failure — a failed repetition in a split stance cannot be dumped the way a bilateral squat can.",
      "Late-stage only: not appropriate in any protected or restoring phase, and only after clearance following knee, hip or spinal surgery.",
      "Earn it first — the split squat and Bulgarian Split Squat should both be comfortable and controlled, and the knee drive should be reliable unloaded, before a bar is added.",
      "The limiter is balance, not leg strength, so the load stays well below a bilateral squat; a wobbling repetition means the set is over.",
      "A bar on the back loads the spine — hold off with symptomatic low back pain, or where spinal loading is restricted.",
      "Respect hip precautions after hip replacement: the front hip reaches deep flexion at the bottom and the trailing hip does the same at the top of the knee drive.",
      "Not appropriate with balance, vestibular or proprioceptive impairment.",
    ],
  },
  {
    id: "dumbbell-romanian-deadlift",
    name: "Dumbbell Romanian Deadlift",
    aka: ["Romanian deadlift with dumbbells", "RDL", "Dumbbell RDL", "Loaded hip hinge"],
    region: "Hip & Pelvis",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Weight"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Hamstrings", "Gluteus maximus", "Lumbar extensors", "Trunk", "Grip and forearms"],
    indications: ["Hamstring strain rehabilitation", "Posterior chain strength deficit", "Return to lifting with better mechanics", "Hip hinge pattern training under load", "Return to running or sport"],
    setup: "Stand with the feet about hip-width apart, a dumbbell in each hand resting in front of the thighs, knees softly bent rather than locked.",
    steps: [
      "Set the ribs down and draw the shoulder blades gently back before the first repetition.",
      "Push the hips straight back, letting the trunk lower and the dumbbells travel down the front of the thighs.",
      "Keep the dumbbells in contact with, or very close to, the legs the whole way down.",
      "Keep the back flat and the knees softly bent and roughly still — the movement happens at the hip, not the spine or the knee.",
      "Lower until a stretch is felt in the back of the thighs, and stop at the point where the back would start to round.",
      "Drive the hips forward to stand tall, finishing upright without leaning back.",
    ],
    dosage: { sets: "3", reps: "8–12", frequency: "2x/week", loadOrTempo: "3 s lowering phase; light enough that the back stays flat on every repetition" },
    cue: "“Push your hips back toward the wall behind you and let the weights slide down your legs — back stays flat the whole way.”",
    patientInstructions:
      "Stand with your feet about hip-width apart, holding a dumbbell in each hand in front of your thighs with your knees slightly bent. Push your hips backwards and let your body tip forwards, keeping the weights sliding close down the front of your legs and your back flat. Go down until you feel a stretch in the back of your thighs, then push your hips forwards to stand back up. Eight to twelve repetitions, three sets, twice a week. How far down you go depends on your own flexibility — stop at the point where your back would start to round, not at any set height, and use a light enough weight that every repetition looks the same.",
    commonErrors: [
      "Squatting instead of hinging — the knees bend and the hips drop rather than travelling backwards",
      "Rounding the low back at the bottom to reach further down",
      "Letting the dumbbells drift away from the legs, which loads the back instead of the hamstrings",
      "Leaning back at the top rather than simply finishing upright",
      "Chasing depth instead of stopping where the back would round",
      "Adding load before the hinge pattern is reliable",
    ],
    regression: "Hip Hinge with a Dowel to groove the pattern with no load, or the same lift through a shorter range stopping at the knees.",
    progression: "Add load in small increments, slow the lowering further, then the Single-Leg Romanian Deadlift for the same pattern on one leg.",
    precautions: [
      "Depth is set by hamstring length, not by reaching the floor — the stopping point is where the back would begin to round, and that differs between people.",
      "Reduce load or hold off with symptomatic low back pain, and where spinal loading is restricted: a loaded forward hinge is the position that tends to provoke a disc-related presentation.",
      "Not appropriate while a hamstring strain is still symptomatic under load.",
      "Grip often gives out before the hamstrings do — that is a reason to end the set, not to round the back to finish it.",
      "Follow the surgeon's protocol after spinal or hip surgery.",
    ],
  },
  {
    id: "single-leg-rdl",
    name: "Single-Leg Romanian Deadlift",
    aka: ["Single-leg deadlift", "SLRDL", "Single-leg hinge"],
    region: "Hip & Pelvis",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["None", "Weight", "Chair"],
    difficulty: 4,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Hamstrings", "Gluteus maximus", "Gluteus medius", "Lumbar extensors", "Ankle stabilisers"],
    indications: ["Hamstring strain rehabilitation", "Single-leg control deficit", "Return to running or sport", "Balance and posterior chain conditioning"],
    setup: "Stand on one leg with a soft bend in that knee. Touch a counter for light balance support at first.",
    steps: [
      "Hinge at the hip, letting the trunk lower and the free leg extend straight behind.",
      "Keep the back flat and the hips level — the free-leg hip should not roll open toward the ceiling.",
      "Lower until a stretch is felt in the hamstring of the standing leg.",
      "Drive the hips forward to return upright.",
    ],
    dosage: { sets: "2–3", reps: "8–10 each side", frequency: "Every other day", loadOrTempo: "Down in 3 s, up in 2 s; add load only when balance is stable" },
    cue: "“Push your hips straight back and keep them square to the floor — imagine headlights on your hip bones pointing at the ground.”",
    patientInstructions:
      "Stand on one leg with a slight bend in that knee, touching a counter for balance. Push your hips backwards, letting your body lower and your other leg reach straight out behind you. Keep your back flat and your hips level. Come back up by pushing your hips forwards. Eight to ten repetitions on each leg.",
    commonErrors: [
      "Letting the hips rotate open instead of staying square",
      "Rounding the low back rather than hinging from the hip",
      "Locking the standing knee straight",
      "Adding weight before the balance is reliable",
    ],
    regression: "Keep the toe of the free leg lightly touching the floor behind, which restores balance support; or the Dumbbell Romanian Deadlift on two legs if it is the hinge rather than the balance that is failing.",
    progression: "Remove the hand support, then add a weight in one or both hands, then increase the range.",
    precautions: [
      "Not appropriate while a hamstring strain is still symptomatic under load.",
      "Needs adequate single-leg balance — use support until it is reliable.",
    ],
  },
  {
    id: "standing-hip-march",
    name: "Standing Hip March",
    aka: ["Marching in place", "Standing knee raise"],
    region: "Hip & Pelvis",
    category: "Motor Control",
    positions: ["Standing"],
    equipment: ["Chair", "Table or counter"],
    difficulty: 2,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Hip flexors", "Gluteus medius", "Balance system"],
    indications: ["Gait retraining", "Post-operative hip rehabilitation", "Falls risk", "Single-leg stance deficit"],
    setup: "Stand tall next to a counter, holding it lightly with one or both hands.",
    steps: [
      "Shift the weight fully onto one leg without letting the hip drop on the other side.",
      "Lift the other knee toward hip height, keeping the trunk upright.",
      "Hold briefly, then lower with control.",
      "Alternate sides at a steady rhythm.",
    ],
    dosage: { sets: "2–3", reps: "10 each side", hold: "2–3 s", frequency: "Once daily" },
    cue: "“Stand tall and lift your knee without leaning — the leg you're standing on is doing most of the work.”",
    patientInstructions:
      "Stand tall next to a counter, holding it lightly. Lift one knee up toward hip height without leaning to the side. Hold a couple of seconds, then lower it. Alternate legs, ten each side.",
    commonErrors: [
      "Leaning the trunk sideways to lift the knee",
      "Letting the pelvis drop on the lifted side",
      "Gripping the counter hard rather than using it for light balance",
      "Lifting the knee by rounding the low back",
    ],
    regression: "Lift the foot only a few inches, and hold the counter with both hands.",
    progression: "Reduce hand support to fingertips, then none; add a hold at the top; then add a band around the thighs.",
    precautions: [
      "Respect hip precautions after hip replacement — hip flexion may be limited.",
      "Use a stable support and stand where there is something safe to grab.",
    ],
  },
];
