import type { MovementExercise } from "@/lib/movement-lab/types";

/** Knee. Ordered as a post-operative or post-injury knee program actually runs: quadriceps
 *  activation and range first, then open-chain strength, then closed-chain loading, then the
 *  late-stage eccentric work. */
export const KNEE_EXERCISES: MovementExercise[] = [
  {
    id: "quad-set",
    name: "Quad Set",
    aka: ["Quadriceps setting", "Static quads", "Isometric quad contraction"],
    region: "Knee",
    category: "Activation",
    positions: ["Supine", "Seated"],
    equipment: ["None", "Towel or strap"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Quadriceps", "Vastus medialis"],
    indications: ["Post ACL reconstruction", "Post total knee replacement", "Knee effusion with quadriceps inhibition", "Any acutely painful or swollen knee"],
    setup: "Lie on the back or sit with the leg straight out in front. A small rolled towel under the ankle helps the knee reach full extension.",
    steps: [
      "Tighten the thigh muscle so the kneecap is pulled upward toward the hip.",
      "Push the back of the knee gently down toward the surface.",
      "Hold, keeping the contraction strong and visible — the thigh should firm up under the hand.",
      "Relax fully between repetitions.",
    ],
    dosage: { sets: "3", reps: "10", hold: "5–10 s", frequency: "Several times a day", loadOrTempo: "Strong, visible contraction" },
    cue: "“Tighten your thigh and pull your kneecap up toward your hip — I should see the muscle move, not just feel your knee press down.”",
    patientInstructions:
      "Lie or sit with your leg straight. Tighten the muscle on the front of your thigh so your kneecap pulls upward and the back of your knee presses down. Hold five to ten seconds, then relax completely. Ten repetitions, several times a day. Put your hand on your thigh so you can feel the muscle tighten.",
    commonErrors: [
      "Pressing the knee down without actually contracting the quadriceps",
      "Holding the breath",
      "Lifting the heel off the surface, which turns it into a straight leg raise",
      "Settling for a weak contraction — the quality of the contraction is the whole exercise",
    ],
    regression: "Shorten the hold to 3 seconds; contract the good leg first to feel what it should be like.",
    progression: "Straight Leg Raise, once the quad set is strong enough to hold the knee straight with no lag.",
    precautions: [
      "One of the very first exercises after knee surgery — usually permitted from day one, but confirm against the surgeon's protocol.",
      "Stop for sharp pain, which is not expected here.",
    ],
  },
  {
    id: "short-arc-quad",
    name: "Short Arc Quad",
    aka: ["SAQ", "Towel roll knee extension"],
    region: "Knee",
    category: "Strength",
    positions: ["Supine"],
    equipment: ["Towel or strap", "Weight"],
    difficulty: 2,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Quadriceps"],
    indications: ["Post ACL reconstruction", "Post total knee replacement", "Extensor lag", "Quadriceps weakness"],
    setup: "Lie on the back with a firm rolled towel or foam roller under the knee so the knee rests bent to about 30 degrees.",
    steps: [
      "Keeping the back of the thigh on the roll, straighten the knee by lifting only the lower leg.",
      "Straighten fully so the knee is completely locked out.",
      "Hold at the top with the quadriceps tight.",
      "Lower slowly back onto the roll.",
    ],
    dosage: { sets: "3", reps: "10–15", hold: "3–5 s", frequency: "1–2x/day", loadOrTempo: "Bodyweight first; add a 1–3 lb ankle weight later" },
    cue: "“Keep your thigh on the roll and just straighten your lower leg — lock the knee out fully at the top.”",
    patientInstructions:
      "Lie on your back with a rolled towel under your knee. Keeping the back of your thigh on the towel, straighten your knee by lifting only your lower leg. Hold a few seconds with your thigh muscle tight, then lower slowly. Ten to fifteen repetitions, once or twice a day.",
    commonErrors: [
      "Lifting the whole leg off the roll",
      "Not fully straightening the knee at the top, which is where the exercise counts",
      "Dropping the leg down rather than lowering it",
    ],
    regression: "Quad Set with no lifting at all.",
    progression: "Add an ankle weight, then progress to a Long Arc Quad or Straight Leg Raise.",
    precautions: [
      "Follow the surgeon's protocol on when open-chain knee extension is permitted.",
      "Reduce range for anterior knee pain.",
    ],
  },
  {
    id: "straight-leg-raise",
    name: "Straight Leg Raise",
    aka: ["SLR", "Quad-set leg lift"],
    region: "Knee",
    category: "Strength",
    positions: ["Supine"],
    equipment: ["None", "Weight"],
    difficulty: 2,
    phases: ["Acute / Protected", "Subacute / Restore", "Strengthening"],
    targets: ["Quadriceps", "Hip flexors"],
    indications: ["Post ACL reconstruction", "Post total knee replacement", "Quadriceps weakness", "Extensor lag"],
    setup: "Lie on the back with the involved leg straight and the other knee bent with the foot flat.",
    steps: [
      "Set a strong quad set first — the knee must be completely straight before the leg moves.",
      "Lift the straight leg to about the height of the opposite knee.",
      "Hold briefly at the top, keeping the knee locked.",
      "Lower slowly. If the knee bends on the way up, the set is over.",
    ],
    dosage: { sets: "2–3", reps: "10", hold: "2–3 s", frequency: "1–2x/day", loadOrTempo: "Bodyweight first; add a 1–3 lb ankle weight later" },
    cue: "“Lock the knee first, then lift the whole leg as one piece — if the knee bends at all, put it down.”",
    patientInstructions:
      "Lie on your back with the sore leg straight and the other knee bent. Tighten your thigh so your knee is completely straight, then lift the straight leg to about the height of your other knee. Hold a couple of seconds and lower slowly. Ten repetitions. If your knee bends as you lift, stop and rest — a fully straight knee matters more than the number of repetitions.",
    commonErrors: [
      "An extensor lag — the knee sagging into a slight bend during the lift",
      "Lifting the leg too high",
      "Arching the low back",
      "Dropping the leg down at the end",
    ],
    regression: "Quad Set and Short Arc Quad until the knee can be held fully straight.",
    progression: "Add an ankle weight, or add the other three directions (abduction, adduction, extension) as a four-way series.",
    precautions: [
      "Do not start until the quad set can hold the knee straight — an extensor lag means the exercise is being done wrong.",
      "Follow the surgeon's protocol after knee or hip surgery.",
      "Stop for low back pain, which usually means the back is arching.",
    ],
  },
  {
    id: "heel-slide",
    name: "Heel Slide",
    aka: ["Knee flexion slide", "Wall slide for knee flexion"],
    region: "Knee",
    category: "Mobility",
    positions: ["Supine", "Seated"],
    equipment: ["Towel or strap"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Knee joint", "Quadriceps", "Hamstrings"],
    indications: ["Post total knee replacement", "Post ACL reconstruction", "Loss of knee flexion", "Post-operative knee stiffness"],
    setup: "Lie on the back with both legs straight. A plastic bag, sock, or towel under the heel makes it slide.",
    steps: [
      "Slide the heel toward the buttock, bending the knee as far as is comfortable.",
      "Use a strap around the foot to assist if the knee will not bend actively.",
      "Hold briefly at the end of the comfortable range.",
      "Slide the heel back out until the knee is fully straight.",
    ],
    dosage: { sets: "2–3", reps: "10–15", hold: "5 s", frequency: "3–4x/day early on, then 1–2x/day" },
    cue: "“Slide your heel up toward your bottom as far as it will go, hold, and then slide it all the way back to straight.”",
    patientInstructions:
      "Lie on your back with your legs straight. Put a plastic bag or towel under your heel so it slides easily. Slide the heel toward your bottom, bending your knee as far as is comfortable, hold five seconds, then slide it back out until the knee is completely straight. Ten to fifteen repetitions. Do this several times a day early after surgery.",
    commonErrors: [
      "Only working the bending direction and neglecting full straightening, which is often the harder goal",
      "Rushing so the end range is never reached",
      "Forcing past sharp pain rather than working to a firm stretch",
    ],
    regression: "Do it seated with the foot on the floor, sliding the foot back under the chair.",
    progression: "Add a strap for over-pressure, or progress to seated knee flexion hangs.",
    precautions: [
      "Follow the surgeon's range-of-motion targets and timeline.",
      "Expect a stretch, not sharp pain — sharp pain means back off and report it.",
    ],
  },
  {
    id: "prone-knee-hang",
    name: "Prone Knee Hang",
    aka: ["Prone hang", "Terminal extension stretch"],
    region: "Knee",
    category: "Mobility",
    positions: ["Prone"],
    equipment: ["Table or counter", "Weight"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Posterior knee capsule", "Hamstrings", "Knee joint"],
    indications: ["Loss of terminal knee extension", "Post ACL reconstruction", "Post total knee replacement", "Flexion contracture"],
    setup: "Lie face down on a bed with both legs off the edge from the knees down. A small weight can rest on the ankle later.",
    steps: [
      "Let the involved leg hang with the muscles completely relaxed.",
      "Gravity slowly pulls the knee toward full straightening — do nothing to help it.",
      "Hold for the full time, breathing normally.",
      "Come off slowly, supporting the leg.",
    ],
    dosage: { sets: "1–2", reps: "1", hold: "5–10 min", frequency: "2–3x/day" },
    cue: "“Just let the leg hang and relax completely — the whole point is that you're not doing anything.”",
    patientInstructions:
      "Lie face down on a bed with your legs hanging off the edge from the knees down. Let the leg relax completely and let gravity slowly straighten your knee. Hold for five to ten minutes, two or three times a day. Your therapist may ask you to add a small weight around your ankle later.",
    commonErrors: [
      "Tensing the leg instead of relaxing it",
      "Adding a weight too early, which usually causes guarding rather than lengthening",
      "Not staying long enough — this one works through duration, not intensity",
    ],
    regression: "Sit with the heel propped on a stool and let the knee straighten under gravity.",
    progression: "Add a light weight or ankle cuff, or extend the hold time.",
    precautions: [
      "Full knee extension is a priority goal after ACL reconstruction — follow the surgeon's protocol on how aggressively to pursue it.",
      "Stop for numbness or pins and needles in the foot.",
      "Not appropriate for someone who cannot lie prone or get on and off a bed safely.",
    ],
  },
  {
    id: "patellar-mobilization",
    name: "Patellar Mobilisation",
    aka: ["Kneecap glides", "Patellar mobility"],
    region: "Knee",
    category: "Mobility",
    positions: ["Seated", "Supine"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Patellofemoral joint", "Peripatellar soft tissue"],
    indications: ["Post-operative knee stiffness", "Reduced patellar mobility", "Post total knee replacement", "Post ACL reconstruction"],
    setup: "Sit with the leg straight out in front and the quadriceps completely relaxed — the kneecap will not move if the thigh is tight.",
    steps: [
      "Place the thumb and fingers on either side of the kneecap.",
      "Glide it gently side to side, holding at each end.",
      "Then glide it up toward the hip and down toward the foot.",
      "Keep the movements slow and small.",
    ],
    dosage: { sets: "1–2", reps: "10 in each direction", hold: "5–10 s at each end", frequency: "2–3x/day" },
    cue: "“Let your thigh go completely soft first — if the muscle is tight, the kneecap won't move at all.”",
    patientInstructions:
      "Sit with your leg straight and your thigh completely relaxed. Put your fingers and thumb either side of your kneecap and move it gently from side to side, holding a few seconds at each end. Then move it gently up and down. Ten in each direction, two or three times a day.",
    commonErrors: [
      "Doing it with the quadriceps switched on, which locks the kneecap in place",
      "Pushing hard rather than gliding gently",
      "Pressing directly onto a fresh surgical incision",
    ],
    regression: "Side-to-side glides only, with lighter pressure.",
    progression: "Hold longer at the end of each glide as tolerance improves.",
    precautions: [
      "Avoid pressure directly over a healing incision.",
      "Confirm it is permitted where the extensor mechanism has been repaired.",
      "Stop for sharp pain.",
    ],
  },
  {
    id: "terminal-knee-extension",
    name: "Terminal Knee Extension (Band)",
    aka: ["TKE", "Band knee extension"],
    region: "Knee",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Resistance band"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Quadriceps", "Vastus medialis"],
    indications: ["Quadriceps weakness in the last part of the range", "Post ACL reconstruction", "Knee buckling in gait", "Patellofemoral pain"],
    setup: "Anchor a band at knee height. Step into it so it sits across the back of the involved knee, then step back until there is tension pulling the knee forward into a slight bend.",
    steps: [
      "Stand with the foot flat and the knee slightly bent by the band's pull.",
      "Straighten the knee fully against the band, locking it out.",
      "Hold at full extension with the quadriceps tight.",
      "Let the band bend the knee slowly again.",
    ],
    dosage: { sets: "2–3", reps: "12–15", hold: "2–3 s", frequency: "Every other day", loadOrTempo: "1 s to straighten, 3 s to return" },
    cue: "“Push your knee back to completely straight and squeeze your thigh — then let the band bend it slowly, don't let it snap.”",
    patientInstructions:
      "Loop a resistance band around the back of your knee, anchored in front of you at knee height. Step back until the band pulls your knee into a slight bend. Straighten your knee fully against the band, hold a couple of seconds, then let it bend slowly. Twelve to fifteen repetitions.",
    commonErrors: [
      "Hyperextending or snapping the knee back into lock",
      "Lifting the heel off the floor",
      "Bending at the hip instead of moving at the knee",
      "Letting the band pull the knee back quickly",
    ],
    regression: "Do it seated or supine as a short arc quad.",
    progression: "Heavier band, single-leg stance, or add a mini-squat at the start of each repetition.",
    precautions: [
      "Follow post-operative loading restrictions.",
      "Do not force the knee into hyperextension.",
    ],
  },
  {
    id: "long-arc-quad",
    name: "Long Arc Quad",
    aka: ["Seated knee extension", "LAQ"],
    region: "Knee",
    category: "Strength",
    positions: ["Seated"],
    equipment: ["Chair", "Weight"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Quadriceps"],
    indications: ["Quadriceps weakness", "Post total knee replacement", "Sit-to-stand difficulty", "General knee conditioning"],
    setup: "Sit tall on a firm chair with both feet flat, thighs fully supported.",
    steps: [
      "Straighten one knee until the leg is level with the thigh.",
      "Hold at the top with the thigh muscle tight and the knee fully locked.",
      "Lower slowly, taking longer down than up.",
      "Keep the thigh on the chair throughout.",
    ],
    dosage: { sets: "2–3", reps: "10–15", hold: "3–5 s", frequency: "Once daily", loadOrTempo: "2 s up, 3–4 s down; add a 1–5 lb ankle weight later" },
    cue: "“Straighten it all the way out and hold — then lower slowly rather than letting it drop.”",
    patientInstructions:
      "Sit tall on a firm chair with both feet flat. Straighten one knee until your leg is level, hold three to five seconds with your thigh tight, then lower it slowly. Ten to fifteen repetitions on each leg.",
    commonErrors: [
      "Leaning back and swinging the leg up",
      "Not fully straightening at the top",
      "Letting the leg drop quickly",
      "Lifting the thigh off the chair",
    ],
    regression: "Short Arc Quad, which uses a smaller range under less load.",
    progression: "Add an ankle weight, hold longer at the top, or slow the lowering phase further.",
    precautions: [
      "Open-chain knee extension is restricted at certain points after ACL reconstruction — follow the surgeon's protocol on range and timing.",
      "Reduce the range for anterior knee pain; the last part of the range is usually best tolerated.",
    ],
  },
  {
    id: "prone-hamstring-curl",
    name: "Prone Hamstring Curl",
    aka: ["Prone knee flexion", "Hamstring curl"],
    region: "Knee",
    category: "Strength",
    positions: ["Prone"],
    equipment: ["None", "Weight", "Resistance band"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Hamstrings"],
    indications: ["Hamstring weakness", "Post ACL reconstruction with a hamstring graft", "Knee flexion strength deficit"],
    setup: "Lie face down with the legs straight and a pillow under the hips.",
    steps: [
      "Bend one knee, bringing the heel toward the buttock.",
      "Keep the hip flat on the surface — the thigh should not lift.",
      "Hold briefly at the top.",
      "Lower slowly with control.",
    ],
    dosage: { sets: "2–3", reps: "10–15", hold: "2–3 s", frequency: "Every other day", loadOrTempo: "Bodyweight, then a 1–5 lb ankle weight" },
    cue: "“Heel toward your bottom and keep your hip pressed down — the thigh stays on the bed.”",
    patientInstructions:
      "Lie face down with a pillow under your hips. Bend one knee, bringing your heel toward your bottom, keeping your hip flat on the bed. Hold a couple of seconds, then lower slowly. Ten to fifteen repetitions each side.",
    commonErrors: [
      "Lifting the hip and thigh off the surface",
      "Swinging the leg up rather than lifting with the hamstring",
      "Dropping the leg down at the end",
      "Cramping from going too heavy too soon",
    ],
    regression: "Do it standing, holding a counter, with no added weight.",
    progression: "Add an ankle weight or a band, then progress to a bridge with heel slides and eventually the Nordic curl.",
    precautions: [
      "Follow the surgeon's timeline where a hamstring graft was harvested — resisted hamstring work is delayed in that case.",
      "Stop for cramping and reduce the load.",
    ],
  },
  {
    id: "mini-squat",
    name: "Mini Squat",
    aka: ["Quarter squat", "Partial squat"],
    region: "Knee",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Table or counter"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Quadriceps", "Gluteus maximus", "Hamstrings"],
    indications: ["Early closed-chain knee loading", "Post-operative knee rehabilitation", "Patellofemoral pain", "Sit-to-stand difficulty"],
    setup: "Stand with the feet hip-width apart, holding a counter lightly for balance.",
    steps: [
      "Bend the knees and hips to lower about a quarter of the way down — roughly 30 to 45 degrees of knee bend.",
      "Keep the weight through the middle of the feet and the heels down.",
      "Keep the knees tracking over the second toe, not falling inward.",
      "Push back up to standing through both feet evenly.",
    ],
    dosage: { sets: "2–3", reps: "10–15", frequency: "Once daily", loadOrTempo: "Down in 3 s, up in 2 s" },
    cue: "“Only a quarter of the way down — keep your heels down and your knees pointing over your toes.”",
    patientInstructions:
      "Stand with your feet hip-width apart, holding a counter lightly. Bend your knees and hips to lower about a quarter of the way down, keeping your heels on the floor and your knees pointing over your toes. Push back up. Ten to fifteen repetitions.",
    commonErrors: [
      "Letting the knees fall inward",
      "Coming up onto the toes",
      "Putting most of the weight on the stronger leg",
      "Going deeper than the knee currently tolerates",
    ],
    regression: "Reduce the depth, or use a wall for back support.",
    progression: "Deeper squat, then a box squat, then single-leg work.",
    precautions: [
      "Follow post-operative weight-bearing restrictions.",
      "Reduce depth for anterior knee pain — depth is usually the variable that provokes it.",
    ],
  },
  {
    id: "wall-sit",
    name: "Wall Sit",
    aka: ["Wall squat hold", "Isometric wall squat"],
    region: "Knee",
    category: "Endurance",
    positions: ["Standing"],
    equipment: ["Wall"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Quadriceps", "Gluteals"],
    indications: ["Quadriceps endurance deficit", "Patellofemoral pain", "Patellar tendinopathy", "General knee conditioning"],
    setup: "Stand with the back flat against a wall and the feet about two foot-lengths out from it, hip-width apart.",
    steps: [
      "Slide down the wall until the knees are bent to a comfortable angle — start shallow.",
      "Keep the knees over the middle of the feet, and the shins roughly vertical.",
      "Hold, breathing normally.",
      "Slide back up the wall to stand.",
    ],
    dosage: { sets: "3–5", reps: "1", hold: "20–45 s", frequency: "Every other day", loadOrTempo: "Choose an angle that can be held for the full time" },
    cue: "“Pick a depth you can hold for the whole time without your knees screaming — shallow and steady beats deep and shaking.”",
    patientInstructions:
      "Stand with your back against a wall and your feet about two foot-lengths away. Slide down the wall until your knees are bent to a comfortable angle. Hold for twenty to forty-five seconds, breathing normally, then slide back up. Three to five holds.",
    commonErrors: [
      "Going too deep too soon",
      "Letting the knees travel past the toes because the feet are too close to the wall",
      "Holding the breath",
      "Letting the knees drift inward",
    ],
    regression: "Shallower angle and shorter holds.",
    progression: "Deeper angle, longer holds, or shift toward single-leg emphasis.",
    precautions: [
      "Follow post-operative range and loading restrictions.",
      "Reduce the depth if it reproduces anterior knee pain during or after the hold.",
      "Not appropriate for someone who cannot get back up from the position safely.",
    ],
  },
  {
    id: "spanish-squat",
    name: "Spanish Squat",
    aka: ["Band-supported squat hold", "Knee-loading isometric"],
    region: "Knee",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Resistance band"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Quadriceps", "Patellar tendon"],
    indications: ["Patellar tendinopathy", "Anterior knee pain", "Quadriceps loading with reduced patellofemoral compression"],
    setup: "Loop a heavy band around a fixed anchor at knee height and around the back of both knees. Step back until the band is taut, feet hip-width apart.",
    steps: [
      "Let the band hold the knees back as you sit down and back into a squat.",
      "Keep the shins close to vertical and the trunk upright — the band makes this possible.",
      "Hold at the bottom of the squat.",
      "Stand back up against the band.",
    ],
    dosage: { sets: "4–5", reps: "1", hold: "30–45 s", frequency: "Once daily during a symptomatic phase", loadOrTempo: "A depth and hold that keeps pain low and settles it afterward" },
    cue: "“Let the band take your knees back and just sit down into it — shins stay upright and your chest stays tall.”",
    patientInstructions:
      "Loop a strong band around a fixed anchor at knee height and around the back of both knees. Step back until it is tight. Sit down and back into a squat, letting the band hold your knees back so your shins stay upright. Hold thirty to forty-five seconds, then stand up. Four or five holds.",
    commonErrors: [
      "Letting the knees travel forward over the toes, which loses the point of the band",
      "Using a band that is too light to hold the position",
      "Going so deep that the pain rises rather than settles",
    ],
    regression: "Shallower depth, shorter holds, or a wall sit instead.",
    progression: "Deeper hold, longer duration, or a single-leg version.",
    precautions: [
      "Needs a genuinely secure anchor — a band under load that comes free is a real hazard.",
      "Adjust the depth so symptoms stay low during and after; increasing pain afterward means the dose was too high.",
    ],
  },
  {
    id: "box-squat",
    name: "Box Squat",
    aka: ["Squat to a chair", "Depth-controlled squat"],
    region: "Knee",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Chair", "Step or stairs", "Weight"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Quadriceps", "Gluteus maximus", "Hamstrings"],
    indications: ["Lower limb strength deficit", "Return to lifting", "Post-operative knee and hip progression", "Sit-to-stand strength"],
    setup: "Stand in front of a firm chair or box with the feet shoulder-width apart, toes slightly turned out.",
    steps: [
      "Push the hips back and lower under control until the buttocks touch the box lightly.",
      "Do not sit down heavily — touch and go.",
      "Keep the chest up, heels down, and the knees tracking over the toes.",
      "Drive through both feet to stand.",
    ],
    dosage: { sets: "3", reps: "8–12", frequency: "Every other day", loadOrTempo: "Down in 3 s, brief touch, up in 2 s" },
    cue: "“Reach your hips back and just kiss the box — don't flop onto it, and don't let your knees dive inward on the way up.”",
    patientInstructions:
      "Stand in front of a firm chair with your feet shoulder-width apart. Push your hips backwards and lower until your bottom lightly touches the chair, then stand back up. Do not sit down heavily. Keep your heels down and your knees over your toes. Eight to twelve repetitions.",
    commonErrors: [
      "Dropping onto the box",
      "Knees collapsing inward on the way up",
      "Heels lifting",
      "Rounding the low back at the bottom",
    ],
    regression: "Use a higher box, or hold a counter for support.",
    progression: "Lower the box, then hold weights, then progress to a split squat or single-leg squat.",
    precautions: [
      "Use a box or chair that will not slide or tip.",
      "Follow post-operative depth and loading limits.",
      "Reduce depth for anterior knee pain.",
    ],
  },
  {
    id: "lateral-step-down",
    name: "Lateral Step-Down",
    aka: ["Side step-down", "Eccentric step-down"],
    region: "Knee",
    category: "Motor Control",
    positions: ["Standing"],
    equipment: ["Step or stairs", "Table or counter"],
    difficulty: 4,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Quadriceps", "Gluteus medius", "Hip stabilisers"],
    indications: ["Patellofemoral pain", "Knee valgus in single-leg loading", "Return to running", "Late-stage knee rehabilitation"],
    setup: "Stand sideways on a low step with the involved leg on the step and the other leg hanging off the side. Touch a rail for light balance.",
    steps: [
      "Slowly bend the standing knee to lower the free heel toward the floor.",
      "Keep the pelvis level and the knee tracking over the middle of the foot.",
      "Touch the heel down lightly — do not transfer weight onto it.",
      "Push back up through the standing leg.",
    ],
    dosage: { sets: "2–3", reps: "8–12 each side", frequency: "Every other day", loadOrTempo: "Down in 3 s, up in 2 s" },
    cue: "“Lower slowly and tap the floor with your heel — keep your kneecap pointing straight ahead the whole way down.”",
    patientInstructions:
      "Stand sideways on a low step with one foot on the step and the other hanging off. Holding a rail lightly, slowly bend the standing knee to lower your other heel toward the floor. Tap it lightly and push back up. Keep your hips level and your knee pointing forwards. Eight to twelve repetitions each side.",
    commonErrors: [
      "The knee collapsing inward on the way down",
      "The pelvis dropping on the hanging-leg side",
      "Dropping down quickly instead of lowering",
      "Pushing off the lowered foot to come back up",
    ],
    regression: "Use a lower step, hold the rail with both hands, or do a forward step-down.",
    progression: "Higher step, remove the hand support, hold a weight, or slow the lowering phase.",
    precautions: [
      "Use a stable step and a secure handrail.",
      "Reduce the step height if the knee falls inward or the exercise reproduces knee pain.",
    ],
  },
  {
    id: "forward-step-down",
    name: "Forward Step-Down",
    region: "Knee",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Step or stairs", "Table or counter"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Quadriceps", "Gluteus maximus"],
    indications: ["Difficulty descending stairs", "Quadriceps eccentric weakness", "Post-operative knee rehabilitation"],
    setup: "Stand on a low step facing forward, holding a rail. The involved leg stays on the step.",
    steps: [
      "Slowly lower the other foot toward the floor in front of the step.",
      "The standing knee bends under control — this is the working leg.",
      "Touch the heel lightly and push back up without transferring weight down.",
      "Keep the trunk upright.",
    ],
    dosage: { sets: "2–3", reps: "8–12 each side", frequency: "Every other day", loadOrTempo: "Down in 3 s, up in 2 s" },
    cue: "“Lower yourself with the leg on the step — the leg going down is only tapping, not landing.”",
    patientInstructions:
      "Stand on a low step holding a rail. Slowly lower your other foot toward the floor in front of you by bending the knee of the leg on the step. Touch the floor lightly and push back up. Eight to twelve repetitions each side.",
    commonErrors: [
      "Dropping down instead of lowering with control",
      "The knee falling inward",
      "Taking weight through the lowered foot to help",
      "Using a step that is too high to control",
    ],
    regression: "Lower step, both hands on the rail, or a partial-range lower.",
    progression: "Higher step, less hand support, or add weight.",
    precautions: [
      "Use a stable step and a secure handrail.",
      "Stop if the knee is painful during the lowering phase rather than pushing through.",
    ],
  },
  {
    id: "nordic-hamstring-curl",
    name: "Nordic Hamstring Curl",
    aka: ["Nordic curl", "Eccentric hamstring lower"],
    region: "Knee",
    category: "Strength",
    positions: ["Kneeling"],
    equipment: ["None", "Chair"],
    difficulty: 5,
    phases: ["Return to Activity"],
    targets: ["Hamstrings", "Gluteals"],
    indications: ["Hamstring strain prevention", "Return to sprinting", "Late-stage hamstring rehabilitation"],
    setup: "Kneel on a padded surface with the ankles held down firmly by a partner or anchored under a solid immovable edge. Trunk and hips in one straight line.",
    steps: [
      "Keep the hips extended so the body stays in a straight line from knees to head — no hinging at the hip.",
      "Lower the whole body forward as slowly as possible, resisting with the hamstrings.",
      "Catch the fall with the hands when control is lost.",
      "Push back up with the hands and use the hamstrings only as much as possible.",
    ],
    dosage: { sets: "2–3", reps: "5–8", frequency: "1–2x/week", loadOrTempo: "As slow as possible on the lowering phase" },
    cue: "“Stay in one straight line from your knees to your head and lower as slowly as you can — catch yourself with your hands when you run out.”",
    patientInstructions:
      "Kneel on something padded with your ankles held down securely. Keeping your body in a straight line from knees to head, lower yourself forward as slowly as you possibly can, resisting with the back of your thighs. Catch yourself with your hands, then push back up. Five to eight repetitions, once or twice a week. Expect to be sore for a day or two after the first few sessions.",
    commonErrors: [
      "Bending at the hips instead of staying in a straight line",
      "Dropping quickly instead of resisting the whole way",
      "Doing it too often — the hamstrings need recovery days between sessions",
      "Starting it too early in a hamstring rehabilitation programme",
    ],
    regression: "Do it with hands on a raised surface, or a partial-range lower, or use a band around the chest for assistance.",
    progression: "Increase the range before adding repetitions; then reduce the assistance.",
    precautions: [
      "A late-stage exercise — not appropriate while a hamstring strain is still symptomatic.",
      "Needs a genuinely secure ankle anchor.",
      "Expect significant delayed soreness after the first sessions; build volume slowly.",
      "Requires the knees to tolerate kneeling.",
    ],
    note: "The eccentric hamstring exercise used in widely-published hamstring injury prevention programmes.",
  },
  {
    id: "prone-quad-stretch",
    name: "Prone Quadriceps Stretch",
    aka: ["Prone heel to buttock", "Strap quad stretch"],
    region: "Knee",
    category: "Flexibility",
    positions: ["Prone", "Standing", "Sidelying"],
    equipment: ["Towel or strap"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Quadriceps", "Rectus femoris", "Hip flexors"],
    indications: ["Quadriceps tightness", "Anterior knee pain", "Loss of knee flexion", "Anterior hip tightness"],
    setup: "Lie face down with a pillow under the hips. Loop a strap or towel around the ankle of the leg being stretched.",
    steps: [
      "Draw the heel gently toward the buttock using the strap.",
      "Keep the hips pressed down into the pillow — the low back must not arch.",
      "Keep the knees close together.",
      "Hold, then release slowly.",
    ],
    dosage: { sets: "2–3", reps: "1 each side", hold: "30 s", frequency: "Once daily" },
    cue: "“Keep your hips pressed down — if your back arches, ease off. Knees stay together.”",
    patientInstructions:
      "Lie face down with a pillow under your hips. Loop a towel around one ankle and gently pull the heel toward your bottom until you feel a stretch at the front of your thigh. Keep your hips pressed down and your knees together. Hold thirty seconds. Two or three times each side.",
    commonErrors: [
      "Arching the low back to gain range",
      "Letting the knee drift out to the side",
      "Pulling hard enough to cause knee pain rather than a thigh stretch",
    ],
    regression: "Do it sidelying, or standing holding a counter, with a smaller range.",
    progression: "Hold longer, or add a posterior pelvic tilt to bias the hip flexor component.",
    precautions: [
      "Stop for knee pain — the stretch belongs in the thigh, not the knee joint.",
      "Not appropriate where knee flexion is restricted after surgery until the surgeon permits it.",
      "Take care with any history of patellar instability.",
    ],
  },
  {
    id: "lateral-thigh-foam-roll",
    name: "Lateral Thigh Foam Roll",
    aka: ["ITB foam rolling", "Lateral quadriceps release"],
    region: "Knee",
    category: "Mobility",
    positions: ["Sidelying"],
    equipment: ["Foam roller"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Vastus lateralis", "Tensor fascia latae", "Lateral thigh soft tissue"],
    indications: ["Lateral knee pain", "Lateral thigh tightness", "Patellofemoral pain with lateral tracking"],
    setup: "Lie on one side with a foam roller under the outside of the thigh, supported on the forearm, with the top leg crossed in front for weight control.",
    steps: [
      "Use the top foot and the supporting arm to control how much weight goes through the roller.",
      "Roll slowly from just below the hip to just above the knee.",
      "Pause on tender areas and breathe rather than gritting through them.",
      "Never roll directly over the bony point of the hip or the outside of the knee.",
    ],
    dosage: { sets: "1–2", reps: "1", hold: "60–90 s per side", frequency: "Once daily" },
    cue: "“Use your top foot to take weight off — this should be a firm pressure you can breathe through, not something you brace against.”",
    patientInstructions:
      "Lie on your side with a foam roller under the outside of your thigh, propped on your forearm with your top foot on the floor in front to take some of your weight. Roll slowly between your hip and your knee for a minute or so. Stay off the bony points at your hip and knee. If it is too intense, put more weight on your top foot.",
    commonErrors: [
      "Rolling directly over the bony point of the hip or the outside of the knee",
      "Using so much pressure that the muscles guard the whole time",
      "Rolling fast rather than slowly",
      "Holding the breath",
    ],
    regression: "Take more weight through the top foot and arm, or use a softer roller.",
    progression: "Take more weight through the roller, or pause longer on tender areas.",
    precautions: [
      "Avoid over bony points, varicose veins, or areas of numbness.",
      "Avoid where there is a bleeding disorder, on anticoagulants, or over recent injury or surgery, unless specifically cleared.",
    ],
  },
];
