import type { MovementExercise } from "@/lib/movement-lab/types";

/** Knee. Ordered as a post-operative or post-injury knee program actually runs: quadriceps
 *  activation and range first, then open-chain strength, then closed-chain loading, then the
 *  late-stage eccentric work. */
export const KNEE_EXERCISES: MovementExercise[] = [
  {
    id: "quad-set",
    name: "Quad Set",
    aka: ["Quadriceps setting", "Static quads", "Isometric quad contraction"],
    region: "Knee",
    category: "Activation",
    positions: ["Supine", "Seated"],
    equipment: ["None", "Towel or strap"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Quadriceps", "Vastus medialis"],
    indications: ["Post ACL reconstruction", "Post total knee replacement", "Knee effusion with quadriceps inhibition", "Any acutely painful or swollen knee"],
    setup: "Lie on the back or sit with the leg straight out in front. A small rolled towel under the ankle helps the knee reach full extension.",
    steps: [
      "Tighten the thigh muscle so the kneecap is pulled upward toward the hip.",
      "Push the back of the knee gently down toward the surface.",
      "Hold, keeping the contraction strong and visible — the thigh should firm up under the hand.",
      "Relax fully between repetitions.",
    ],
    dosage: { sets: "3", reps: "10", hold: "5–10 s", frequency: "Several times a day", loadOrTempo: "Strong, visible contraction" },
    cue: "“Tighten your thigh and pull your kneecap up toward your hip — I should see the muscle move, not just feel your knee press down.”",
    patientInstructions:
      "Lie or sit with your leg straight. Tighten the muscle on the front of your thigh so your kneecap pulls upward and the back of your knee presses down. Hold five to ten seconds, then relax completely. Ten repetitions, several times a day. Put your hand on your thigh so you can feel the muscle tighten.",
    commonErrors: [
      "Pressing the knee down without actually contracting the quadriceps",
      "Holding the breath",
      "Lifting the heel off the surface, which turns it into a straight leg raise",
      "Settling for a weak contraction — the quality of the contraction is the whole exercise",
    ],
    regression: "Shorten the hold to 3 seconds; contract the good leg first to feel what it should be like.",
    progression: "Straight Leg Raise, once the quad set is strong enough to hold the knee straight with no lag.",
    precautions: [
      "One of the very first exercises after knee surgery — usually permitted from day one, but confirm against the surgeon's protocol.",
      "Stop for sharp pain, which is not expected here.",
    ],
  },
  {
    id: "short-arc-quad",
    name: "Short Arc Quad",
    aka: ["SAQ", "Towel roll knee extension"],
    region: "Knee",
    category: "Strength",
    positions: ["Supine"],
    equipment: ["Towel or strap", "Weight"],
    difficulty: 2,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Quadriceps"],
    indications: ["Post ACL reconstruction", "Post total knee replacement", "Extensor lag", "Quadriceps weakness"],
    setup: "Lie on the back with a firm rolled towel or foam roller under the knee so the knee rests bent to about 30 degrees.",
    steps: [
      "Keeping the back of the thigh on the roll, straighten the knee by lifting only the lower leg.",
      "Straighten fully so the knee is completely locked out.",
      "Hold at the top with the quadriceps tight.",
      "Lower slowly back onto the roll.",
    ],
    dosage: { sets: "3", reps: "10–15", hold: "3–5 s", frequency: "1–2x/day", loadOrTempo: "Bodyweight first; add a 1–3 lb ankle weight later" },
    cue: "“Keep your thigh on the roll and just straighten your lower leg — lock the knee out fully at the top.”",
    patientInstructions:
      "Lie on your back with a rolled towel under your knee. Keeping the back of your thigh on the towel, straighten your knee by lifting only your lower leg. Hold a few seconds with your thigh muscle tight, then lower slowly. Ten to fifteen repetitions, once or twice a day.",
    commonErrors: [
      "Lifting the whole leg off the roll",
      "Not fully straightening the knee at the top, which is where the exercise counts",
      "Dropping the leg down rather than lowering it",
    ],
    regression: "Quad Set with no lifting at all.",
    progression: "Add an ankle weight, then progress to a Long Arc Quad or Straight Leg Raise.",
    precautions: [
      "Follow the surgeon's protocol on when open-chain knee extension is permitted.",
      "Reduce range for anterior knee pain.",
    ],
  },
  {
    id: "straight-leg-raise",
    name: "Straight Leg Raise",
    aka: ["SLR", "Quad-set leg lift"],
    region: "Knee",
    category: "Strength",
    positions: ["Supine"],
    equipment: ["None", "Weight"],
    difficulty: 2,
    phases: ["Acute / Protected", "Subacute / Restore", "Strengthening"],
    targets: ["Quadriceps", "Hip flexors"],
    indications: ["Post ACL reconstruction", "Post total knee replacement", "Quadriceps weakness", "Extensor lag"],
    setup: "Lie on the back with the involved leg straight and the other knee bent with the foot flat.",
    steps: [
      "Set a strong quad set first — the knee must be completely straight before the leg moves.",
      "Lift the straight leg to about the height of the opposite knee.",
      "Hold briefly at the top, keeping the knee locked.",
      "Lower slowly. If the knee bends on the way up, the set is over.",
    ],
    dosage: { sets: "2–3", reps: "10", hold: "2–3 s", frequency: "1–2x/day", loadOrTempo: "Bodyweight first; add a 1–3 lb ankle weight later" },
    cue: "“Lock the knee first, then lift the whole leg as one piece — if the knee bends at all, put it down.”",
    patientInstructions:
      "Lie on your back with the sore leg straight and the other knee bent. Tighten your thigh so your knee is completely straight, then lift the straight leg to about the height of your other knee. Hold a couple of seconds and lower slowly. Ten repetitions. If your knee bends as you lift, stop and rest — a fully straight knee matters more than the number of repetitions.",
    commonErrors: [
      "An extensor lag — the knee sagging into a slight bend during the lift",
      "Lifting the leg too high",
      "Arching the low back",
      "Dropping the leg down at the end",
    ],
    regression: "Quad Set and Short Arc Quad until the knee can be held fully straight.",
    progression: "Add an ankle weight, or add the other three directions (abduction, adduction, extension) as a four-way series.",
    precautions: [
      "Do not start until the quad set can hold the knee straight — an extensor lag means the exercise is being done wrong.",
      "Follow the surgeon's protocol after knee or hip surgery.",
      "Stop for low back pain, which usually means the back is arching.",
    ],
  },
  {
    id: "heel-slide",
    name: "Heel Slide",
    aka: ["Knee flexion slide", "Wall slide for knee flexion"],
    region: "Knee",
    category: "Mobility",
    positions: ["Supine", "Seated"],
    equipment: ["Towel or strap"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Knee joint", "Quadriceps", "Hamstrings"],
    indications: ["Post total knee replacement", "Post ACL reconstruction", "Loss of knee flexion", "Post-operative knee stiffness"],
    setup: "Lie on the back with both legs straight. A plastic bag, sock, or towel under the heel makes it slide.",
    steps: [
      "Slide the heel toward the buttock, bending the knee as far as is comfortable.",
      "Use a strap around the foot to assist if the knee will not bend actively.",
      "Hold briefly at the end of the comfortable range.",
      "Slide the heel back out until the knee is fully straight.",
    ],
    dosage: { sets: "2–3", reps: "10–15", hold: "5 s", frequency: "3–4x/day early on, then 1–2x/day" },
    cue: "“Slide your heel up toward your bottom as far as it will go, hold, and then slide it all the way back to straight.”",
    patientInstructions:
      "Lie on your back with your legs straight. Put a plastic bag or towel under your heel so it slides easily. Slide the heel toward your bottom, bending your knee as far as is comfortable, hold five seconds, then slide it back out until the knee is completely straight. Ten to fifteen repetitions. Do this several times a day early after surgery.",
    commonErrors: [
      "Only working the bending direction and neglecting full straightening, which is often the harder goal",
      "Rushing so the end range is never reached",
      "Forcing past sharp pain rather than working to a firm stretch",
    ],
    regression: "Do it seated with the foot on the floor, sliding the foot back under the chair.",
    progression: "Add a strap for over-pressure, or progress to seated knee flexion hangs.",
    precautions: [
      "Follow the surgeon's range-of-motion targets and timeline.",
      "Expect a stretch, not sharp pain — sharp pain means back off and report it.",
    ],
  },
  {
    id: "prone-knee-hang",
    name: "Prone Knee Hang",
    aka: ["Prone hang", "Terminal extension stretch"],
    region: "Knee",
    category: "Mobility",
    positions: ["Prone"],
    equipment: ["Table or counter", "Weight"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Posterior knee capsule", "Hamstrings", "Knee joint"],
    indications: ["Loss of terminal knee extension", "Post ACL reconstruction", "Post total knee replacement", "Flexion contracture"],
    setup: "Lie face down on a bed with both legs off the edge from the knees down. A small weight can rest on the ankle later.",
    steps: [
      "Let the involved leg hang with the muscles completely relaxed.",
      "Gravity slowly pulls the knee toward full straightening — do nothing to help it.",
      "Hold for the full time, breathing normally.",
      "Come off slowly, supporting the leg.",
    ],
    dosage: { sets: "1–2", reps: "1", hold: "5–10 min", frequency: "2–3x/day" },
    cue: "“Just let the leg hang and relax completely — the whole point is that you're not doing anything.”",
    patientInstructions:
      "Lie face down on a bed with your legs hanging off the edge from the knees down. Let the leg relax completely and let gravity slowly straighten your knee. Hold for five to ten minutes, two or three times a day. Your therapist may ask you to add a small weight around your ankle later.",
    commonErrors: [
      "Tensing the leg instead of relaxing it",
      "Adding a weight too early, which usually causes guarding rather than lengthening",
      "Not staying long enough — this one works through duration, not intensity",
    ],
    regression: "Sit with the heel propped on a stool and let the knee straighten under gravity.",
    progression: "Add a light weight or ankle cuff, or extend the hold time.",
    precautions: [
      "Full knee extension is a priority goal after ACL reconstruction — follow the surgeon's protocol on how aggressively to pursue it.",
      "Stop for numbness or pins and needles in the foot.",
      "Not appropriate for someone who cannot lie prone or get on and off a bed safely.",
    ],
  },
  {
    id: "patellar-mobilization",
    name: "Patellar Mobilisation",
    aka: ["Kneecap glides", "Patellar mobility"],
    region: "Knee",
    category: "Mobility",
    positions: ["Seated", "Supine"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Patellofemoral joint", "Peripatellar soft tissue"],
    indications: ["Post-operative knee stiffness", "Reduced patellar mobility", "Post total knee replacement", "Post ACL reconstruction"],
    setup: "Sit with the leg straight out in front and the quadriceps completely relaxed — the kneecap will not move if the thigh is tight.",
    steps: [
      "Place the thumb and fingers on either side of the kneecap.",
      "Glide it gently side to side, holding at each end.",
      "Then glide it up toward the hip and down toward the foot.",
      "Keep the movements slow and small.",
    ],
    dosage: { sets: "1–2", reps: "10 in each direction", hold: "5–10 s at each end", frequency: "2–3x/day" },
    cue: "“Let your thigh go completely soft first — if the muscle is tight, the kneecap won't move at all.”",
    patientInstructions:
      "Sit with your leg straight and your thigh completely relaxed. Put your fingers and thumb either side of your kneecap and move it gently from side to side, holding a few seconds at each end. Then move it gently up and down. Ten in each direction, two or three times a day.",
    commonErrors: [
      "Doing it with the quadriceps switched on, which locks the kneecap in place",
      "Pushing hard rather than gliding gently",
      "Pressing directly onto a fresh surgical incision",
    ],
    regression: "Side-to-side glides only, with lighter pressure.",
    progression: "Hold longer at the end of each glide as tolerance improves.",
    precautions: [
      "Avoid pressure directly over a healing incision.",
      "Confirm it is permitted where the extensor mechanism has been repaired.",
      "Stop for sharp pain.",
    ],
  },
  {
    id: "terminal-knee-extension",
    name: "Terminal Knee Extension (Band)",
    aka: ["TKE", "Band knee extension"],
    region: "Knee",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Resistance band"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Quadriceps", "Vastus medialis"],
    indications: ["Quadriceps weakness in the last part of the range", "Post ACL reconstruction", "Knee buckling in gait", "Patellofemoral pain"],
    setup: "Anchor a band at knee height. Step into it so it sits across the back of the involved knee, then step back until there is tension pulling the knee forward into a slight bend.",
    steps: [
      "Stand with the foot flat and the knee slightly bent by the band's pull.",
      "Straighten the knee fully against the band, locking it out.",
      "Hold at full extension with the quadriceps tight.",
      "Let the band bend the knee slowly again.",
    ],
    dosage: { sets: "2–3", reps: "12–15", hold: "2–3 s", frequency: "Every other day", loadOrTempo: "1 s to straighten, 3 s to return" },
    cue: "“Push your knee back to completely straight and squeeze your thigh — then let the band bend it slowly, don't let it snap.”",
    patientInstructions:
      "Loop a resistance band around the back of your knee, anchored in front of you at knee height. Step back until the band pulls your knee into a slight bend. Straighten your knee fully against the band, hold a couple of seconds, then let it bend slowly. Twelve to fifteen repetitions.",
    commonErrors: [
      "Hyperextending or snapping the knee back into lock",
      "Lifting the heel off the floor",
      "Bending at the hip instead of moving at the knee",
      "Letting the band pull the knee back quickly",
    ],
    regression: "Do it seated or supine as a short arc quad.",
    progression: "Heavier band, single-leg stance, or add a mini-squat at the start of each repetition.",
    precautions: [
      "Follow post-operative loading restrictions.",
      "Do not force the knee into hyperextension.",
    ],
  },
  {
    id: "long-arc-quad",
    name: "Long Arc Quad",
    aka: ["Seated knee extension", "LAQ"],
    region: "Knee",
    category: "Strength",
    positions: ["Seated"],
    equipment: ["Chair", "Weight"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Quadriceps"],
    indications: ["Quadriceps weakness", "Post total knee replacement", "Sit-to-stand difficulty", "General knee conditioning"],
    setup: "Sit tall on a firm chair with both feet flat, thighs fully supported.",
    steps: [
      "Straighten one knee until the leg is level with the thigh.",
      "Hold at the top with the thigh muscle tight and the knee fully locked.",
      "Lower slowly, taking longer down than up.",
      "Keep the thigh on the chair throughout.",
    ],
    dosage: { sets: "2–3", reps: "10–15", hold: "3–5 s", frequency: "Once daily", loadOrTempo: "2 s up, 3–4 s down; add a 1–5 lb ankle weight later" },
    cue: "“Straighten it all the way out and hold — then lower slowly rather than letting it drop.”",
    patientInstructions:
      "Sit tall on a firm chair with both feet flat. Straighten one knee until your leg is level, hold three to five seconds with your thigh tight, then lower it slowly. Ten to fifteen repetitions on each leg.",
    commonErrors: [
      "Leaning back and swinging the leg up",
      "Not fully straightening at the top",
      "Letting the leg drop quickly",
      "Lifting the thigh off the chair",
    ],
    regression: "Short Arc Quad, which uses a smaller range under less load.",
    progression: "Add an ankle weight, hold longer at the top, or slow the lowering phase further.",
    precautions: [
      "Open-chain knee extension is restricted at certain points after ACL reconstruction — follow the surgeon's protocol on range and timing.",
      "Reduce the range for anterior knee pain; the last part of the range is usually best tolerated.",
    ],
  },
  {
    id: "prone-hamstring-curl",
    name: "Prone Hamstring Curl",
    aka: ["Prone knee flexion", "Hamstring curl"],
    region: "Knee",
    category: "Strength",
    positions: ["Prone"],
    equipment: ["None", "Weight", "Resistance band"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Hamstrings"],
    indications: ["Hamstring weakness", "Post ACL reconstruction with a hamstring graft", "Knee flexion strength deficit"],
    setup: "Lie face down with the legs straight and a pillow under the hips.",
    steps: [
      "Bend one knee, bringing the heel toward the buttock.",
      "Keep the hip flat on the surface — the thigh should not lift.",
      "Hold briefly at the top.",
      "Lower slowly with control.",
    ],
    dosage: { sets: "2–3", reps: "10–15", hold: "2–3 s", frequency: "Every other day", loadOrTempo: "Bodyweight, then a 1–5 lb ankle weight" },
    cue: "“Heel toward your bottom and keep your hip pressed down — the thigh stays on the bed.”",
    patientInstructions:
      "Lie face down with a pillow under your hips. Bend one knee, bringing your heel toward your bottom, keeping your hip flat on the bed. Hold a couple of seconds, then lower slowly. Ten to fifteen repetitions each side.",
    commonErrors: [
      "Lifting the hip and thigh off the surface",
      "Swinging the leg up rather than lifting with the hamstring",
      "Dropping the leg down at the end",
      "Cramping from going too heavy too soon",
    ],
    regression: "Do it standing, holding a counter, with no added weight.",
    progression: "Add an ankle weight or a band, then the Swiss Ball Hamstring Curl, and eventually the Nordic Hamstring Curl.",
    precautions: [
      "Follow the surgeon's timeline where a hamstring graft was harvested — resisted hamstring work is delayed in that case.",
      "Stop for cramping and reduce the load.",
    ],
  },
  {
    id: "mini-squat",
    name: "Mini Squat",
    aka: ["Quarter squat", "Partial squat"],
    region: "Knee",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Table or counter"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Quadriceps", "Gluteus maximus", "Hamstrings"],
    indications: ["Early closed-chain knee loading", "Post-operative knee rehabilitation", "Patellofemoral pain", "Sit-to-stand difficulty"],
    setup: "Stand with the feet hip-width apart, holding a counter lightly for balance.",
    steps: [
      "Bend the knees and hips to lower about a quarter of the way down — roughly 30 to 45 degrees of knee bend.",
      "Keep the weight through the middle of the feet and the heels down.",
      "Keep the knees tracking over the second toe, not falling inward.",
      "Push back up to standing through both feet evenly.",
    ],
    dosage: { sets: "2–3", reps: "10–15", frequency: "Once daily", loadOrTempo: "Down in 3 s, up in 2 s" },
    cue: "“Only a quarter of the way down — keep your heels down and your knees pointing over your toes.”",
    patientInstructions:
      "Stand with your feet hip-width apart, holding a counter lightly. Bend your knees and hips to lower about a quarter of the way down, keeping your heels on the floor and your knees pointing over your toes. Push back up. Ten to fifteen repetitions.",
    commonErrors: [
      "Letting the knees fall inward",
      "Coming up onto the toes",
      "Putting most of the weight on the stronger leg",
      "Going deeper than the knee currently tolerates",
    ],
    regression: "Reduce the depth, or use a wall for back support.",
    progression: "Deeper squat, then the Box Squat, then the Forward Step-Down and the Single-Leg Squat to a Box.",
    precautions: [
      "Follow post-operative weight-bearing restrictions.",
      "Reduce depth for anterior knee pain — depth is usually the variable that provokes it.",
    ],
  },
  {
    id: "wall-sit",
    name: "Wall Sit",
    aka: ["Wall squat hold", "Isometric wall squat"],
    region: "Knee",
    category: "Endurance",
    positions: ["Standing"],
    equipment: ["Wall"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Quadriceps", "Gluteals"],
    indications: ["Quadriceps endurance deficit", "Patellofemoral pain", "Patellar tendinopathy", "General knee conditioning"],
    setup: "Stand with the back flat against a wall and the feet about two foot-lengths out from it, hip-width apart.",
    steps: [
      "Slide down the wall until the knees are bent to a comfortable angle — start shallow.",
      "Keep the knees over the middle of the feet, and the shins roughly vertical.",
      "Hold, breathing normally.",
      "Slide back up the wall to stand.",
    ],
    dosage: { sets: "3–5", reps: "1", hold: "20–45 s", frequency: "Every other day", loadOrTempo: "Choose an angle that can be held for the full time" },
    cue: "“Pick a depth you can hold for the whole time without your knees screaming — shallow and steady beats deep and shaking.”",
    patientInstructions:
      "Stand with your back against a wall and your feet about two foot-lengths away. Slide down the wall until your knees are bent to a comfortable angle. Hold for twenty to forty-five seconds, breathing normally, then slide back up. Three to five holds.",
    commonErrors: [
      "Going too deep too soon",
      "Letting the knees travel past the toes because the feet are too close to the wall",
      "Holding the breath",
      "Letting the knees drift inward",
    ],
    regression: "Shallower angle and shorter holds.",
    progression: "Deeper angle or longer holds; for single-leg loading move to the Forward Step-Down or the Single-Leg Squat to a Box rather than trying to hold this one on one leg.",
    precautions: [
      "Follow post-operative range and loading restrictions.",
      "Reduce the depth if it reproduces anterior knee pain during or after the hold.",
      "Not appropriate for someone who cannot get back up from the position safely.",
    ],
  },
  {
    id: "spanish-squat",
    name: "Spanish Squat",
    aka: ["Band-supported squat hold", "Knee-loading isometric"],
    region: "Knee",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Resistance band"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Quadriceps", "Patellar tendon"],
    indications: ["Patellar tendinopathy", "Anterior knee pain", "Quadriceps loading with reduced patellofemoral compression"],
    setup: "Loop a heavy band around a fixed anchor at knee height and around the back of both knees. Step back until the band is taut, feet hip-width apart.",
    steps: [
      "Let the band hold the knees back as you sit down and back into a squat.",
      "Keep the shins close to vertical and the trunk upright — the band makes this possible.",
      "Hold at the bottom of the squat.",
      "Stand back up against the band.",
    ],
    dosage: { sets: "4–5", reps: "1", hold: "30–45 s", frequency: "Once daily during a symptomatic phase", loadOrTempo: "A depth and hold that keeps pain low and settles it afterward" },
    cue: "“Let the band take your knees back and just sit down into it — shins stay upright and your chest stays tall.”",
    patientInstructions:
      "Loop a strong band around a fixed anchor at knee height and around the back of both knees. Step back until it is tight. Sit down and back into a squat, letting the band hold your knees back so your shins stay upright. Hold thirty to forty-five seconds, then stand up. Four or five holds.",
    commonErrors: [
      "Letting the knees travel forward over the toes, which loses the point of the band",
      "Using a band that is too light to hold the position",
      "Going so deep that the pain rises rather than settles",
    ],
    regression: "Shallower depth, shorter holds, or a wall sit instead.",
    progression: "Deeper hold or longer duration; for single-leg loading move to the Forward Step-Down or the Single-Leg Squat to a Box.",
    precautions: [
      "Needs a genuinely secure anchor — a band under load that comes free is a real hazard.",
      "Adjust the depth so symptoms stay low during and after; increasing pain afterward means the dose was too high.",
    ],
  },
  {
    id: "box-squat",
    name: "Box Squat",
    aka: ["Squat to a chair", "Depth-controlled squat"],
    region: "Knee",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Chair", "Step or stairs", "Weight"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Quadriceps", "Gluteus maximus", "Hamstrings"],
    indications: ["Lower limb strength deficit", "Return to lifting", "Post-operative knee and hip progression", "Sit-to-stand strength"],
    setup: "Stand in front of a firm chair or box with the feet shoulder-width apart, toes slightly turned out.",
    steps: [
      "Push the hips back and lower under control until the buttocks touch the box lightly.",
      "Do not sit down heavily — touch and go.",
      "Keep the chest up, heels down, and the knees tracking over the toes.",
      "Drive through both feet to stand.",
    ],
    dosage: { sets: "3", reps: "8–12", frequency: "Every other day", loadOrTempo: "Down in 3 s, brief touch, up in 2 s" },
    cue: "“Reach your hips back and just kiss the box — don't flop onto it, and don't let your knees dive inward on the way up.”",
    patientInstructions:
      "Stand in front of a firm chair with your feet shoulder-width apart. Push your hips backwards and lower until your bottom lightly touches the chair, then stand back up. Do not sit down heavily. Keep your heels down and your knees over your toes. Eight to twelve repetitions.",
    commonErrors: [
      "Dropping onto the box",
      "Knees collapsing inward on the way up",
      "Heels lifting",
      "Rounding the low back at the bottom",
    ],
    regression: "Use a higher box, or hold a counter for support.",
    progression: "Lower the box, then hold weights, then the Split Squat or the Single-Leg Squat to a Box.",
    precautions: [
      "Use a box or chair that will not slide or tip.",
      "Follow post-operative depth and loading limits.",
      "Reduce depth for anterior knee pain.",
    ],
  },
  {
    id: "lateral-step-down",
    name: "Lateral Step-Down",
    aka: ["Side step-down", "Eccentric step-down"],
    region: "Knee",
    category: "Motor Control",
    positions: ["Standing"],
    equipment: ["Step or stairs", "Table or counter"],
    difficulty: 4,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Quadriceps", "Gluteus medius", "Hip stabilisers"],
    indications: ["Patellofemoral pain", "Knee valgus in single-leg loading", "Return to running", "Late-stage knee rehabilitation"],
    setup: "Stand sideways on a low step with the involved leg on the step and the other leg hanging off the side. Touch a rail for light balance.",
    steps: [
      "Slowly bend the standing knee to lower the free heel toward the floor.",
      "Keep the pelvis level and the knee tracking over the middle of the foot.",
      "Touch the heel down lightly — do not transfer weight onto it.",
      "Push back up through the standing leg.",
    ],
    dosage: { sets: "2–3", reps: "8–12 each side", frequency: "Every other day", loadOrTempo: "Down in 3 s, up in 2 s" },
    cue: "“Lower slowly and tap the floor with your heel — keep your kneecap pointing straight ahead the whole way down.”",
    patientInstructions:
      "Stand sideways on a low step with one foot on the step and the other hanging off. Holding a rail lightly, slowly bend the standing knee to lower your other heel toward the floor. Tap it lightly and push back up. Keep your hips level and your knee pointing forwards. Eight to twelve repetitions each side.",
    commonErrors: [
      "The knee collapsing inward on the way down",
      "The pelvis dropping on the hanging-leg side",
      "Dropping down quickly instead of lowering",
      "Pushing off the lowered foot to come back up",
    ],
    regression: "Use a lower step, hold the rail with both hands, or do a forward step-down.",
    progression: "Higher step, remove the hand support, hold a weight, or slow the lowering phase.",
    precautions: [
      "Use a stable step and a secure handrail.",
      "Reduce the step height if the knee falls inward or the exercise reproduces knee pain.",
    ],
  },
  {
    id: "forward-step-down",
    name: "Forward Step-Down",
    region: "Knee",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Step or stairs", "Table or counter"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Quadriceps", "Gluteus maximus"],
    indications: ["Difficulty descending stairs", "Quadriceps eccentric weakness", "Post-operative knee rehabilitation"],
    setup: "Stand on a low step facing forward, holding a rail. The involved leg stays on the step.",
    steps: [
      "Slowly lower the other foot toward the floor in front of the step.",
      "The standing knee bends under control — this is the working leg.",
      "Touch the heel lightly and push back up without transferring weight down.",
      "Keep the trunk upright.",
    ],
    dosage: { sets: "2–3", reps: "8–12 each side", frequency: "Every other day", loadOrTempo: "Down in 3 s, up in 2 s" },
    cue: "“Lower yourself with the leg on the step — the leg going down is only tapping, not landing.”",
    patientInstructions:
      "Stand on a low step holding a rail. Slowly lower your other foot toward the floor in front of you by bending the knee of the leg on the step. Touch the floor lightly and push back up. Eight to twelve repetitions each side.",
    commonErrors: [
      "Dropping down instead of lowering with control",
      "The knee falling inward",
      "Taking weight through the lowered foot to help",
      "Using a step that is too high to control",
    ],
    regression: "Lower step, both hands on the rail, or a partial-range lower.",
    progression: "Higher step, less hand support, or add weight.",
    precautions: [
      "Use a stable step and a secure handrail.",
      "Stop if the knee is painful during the lowering phase rather than pushing through.",
    ],
  },
  {
    id: "swiss-ball-hamstring-curl",
    name: "Swiss Ball Hamstring Curl",
    aka: ["Stability ball hamstring curl", "Exercise ball leg curl", "Physioball curl", "Ball bridge curl"],
    region: "Knee",
    category: "Strength",
    positions: ["Supine"],
    equipment: ["Ball"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Hamstrings", "Gluteus maximus", "Gastrocnemius", "Trunk"],
    indications: ["Hamstring strain rehabilitation", "Hamstring strength deficit", "Return to running and sprinting", "Posterior chain strengthening without added load", "After ACL reconstruction with a hamstring graft"],
    setup: "Lie on the back with the heels and lower calves resting on a large exercise ball, roughly 55–75 cm depending on height. Arms rest at the sides, palms down, on a non-slip floor with clear space around.",
    steps: [
      "Press the heels down into the ball and lift the hips into a bridge, so the body is straight from shoulders to heels.",
      "Keeping the hips lifted, bend the knees and draw the heels toward the buttocks, rolling the ball in.",
      "Hold the hips up as the ball arrives — they will want to sag, and holding them up is the exercise.",
      "Straighten the knees slowly, rolling the ball back out under control.",
      "Lower the hips to the floor only once the set is finished, not between repetitions.",
    ],
    dosage: { sets: "3", reps: "8–12", frequency: "2–3x/week", loadOrTempo: "3 s to roll the ball out; hips level throughout" },
    cue: "“Keep your hips up the whole time — the ball comes to you, your hips don't drop to meet it.”",
    patientInstructions:
      "Lie on your back with your heels on a large exercise ball and your arms by your sides. Push through your heels to lift your hips so your body is in a straight line, then bend your knees to roll the ball in toward you, keeping your hips up. Slowly straighten your legs to roll it back out. Eight to twelve repetitions, three sets. Only put your hips down at the end of the set. If your hamstrings cramp, do fewer repetitions through a smaller range rather than pushing on — that is common with this one at first.",
    commonErrors: [
      "Letting the hips sag as the ball rolls in, which takes the hamstrings out of it entirely",
      "Rolling the ball out fast rather than controlling the return, which is the part that builds strength",
      "Pushing hard through the arms to hold the position",
      "Letting the ball drift sideways instead of tracking straight",
      "Working through cramp rather than reducing the range",
    ],
    regression: "Bridge on the ball and hold without curling, or Glute Bridge with the heels on the floor.",
    progression: "A slower roll-out or eccentric-only repetitions, then the Single-Leg Swiss Ball Hamstring Curl, then the Nordic Hamstring Curl.",
    precautions: [
      "Hamstring cramping is common in the first few sessions and is not a sign of injury — reduce range and volume rather than working through it.",
      "Not appropriate while a hamstring strain is still painful under load; this is a mid-stage strengthening exercise, not an early one.",
      "Follow the surgeon's protocol after ACL reconstruction with a hamstring graft, where hamstring loading is usually staged.",
      "Use a properly inflated ball on a non-slip floor with clear space — a ball that shoots out from under the heels is the usual mishap.",
      "Keep the weight through the shoulders and upper back rather than the neck.",
    ],
  },
  {
    id: "nordic-hamstring-curl",
    name: "Nordic Hamstring Curl",
    aka: ["Nordic curl", "Eccentric hamstring lower"],
    region: "Knee",
    category: "Strength",
    positions: ["Kneeling"],
    equipment: ["None", "Chair"],
    difficulty: 5,
    phases: ["Return to Activity"],
    targets: ["Hamstrings", "Gluteals"],
    indications: ["Hamstring strain prevention", "Return to sprinting", "Late-stage hamstring rehabilitation"],
    setup: "Kneel on a padded surface with the ankles held down firmly by a partner or anchored under a solid immovable edge. Trunk and hips in one straight line.",
    steps: [
      "Keep the hips extended so the body stays in a straight line from knees to head — no hinging at the hip.",
      "Lower the whole body forward as slowly as possible, resisting with the hamstrings.",
      "Catch the fall with the hands when control is lost.",
      "Push back up with the hands and use the hamstrings only as much as possible.",
    ],
    dosage: { sets: "2–3", reps: "5–8", frequency: "1–2x/week", loadOrTempo: "As slow as possible on the lowering phase" },
    cue: "“Stay in one straight line from your knees to your head and lower as slowly as you can — catch yourself with your hands when you run out.”",
    patientInstructions:
      "Kneel on something padded with your ankles held down securely. Keeping your body in a straight line from knees to head, lower yourself forward as slowly as you possibly can, resisting with the back of your thighs. Catch yourself with your hands, then push back up. Five to eight repetitions, once or twice a week. Expect to be sore for a day or two after the first few sessions.",
    commonErrors: [
      "Bending at the hips instead of staying in a straight line",
      "Dropping quickly instead of resisting the whole way",
      "Doing it too often — the hamstrings need recovery days between sessions",
      "Starting it too early in a hamstring rehabilitation programme",
    ],
    regression: "Do it with hands on a raised surface, or a partial-range lower, or use a band around the chest for assistance; the Swiss Ball Hamstring Curl is the lower-load alternative if the Nordic is too much even assisted.",
    progression: "Increase the range before adding repetitions; then reduce the assistance.",
    precautions: [
      "A late-stage exercise — not appropriate while a hamstring strain is still symptomatic.",
      "Needs a genuinely secure ankle anchor.",
      "Expect significant delayed soreness after the first sessions; build volume slowly.",
      "Requires the knees to tolerate kneeling.",
    ],
    note: "The eccentric hamstring exercise used in widely-published hamstring injury prevention programmes.",
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    aka: ["Front-loaded squat", "Dumbbell goblet squat", "Kettlebell goblet squat"],
    region: "Knee",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Weight"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Quadriceps", "Gluteus maximus", "Adductors", "Trunk"],
    indications: ["Lower limb strength deficit", "Return to lifting and carrying", "Knee osteoarthritis once loading is tolerated", "Late-stage knee and hip rehabilitation"],
    setup: "Stand with the feet a little wider than hip-width, toes turned slightly out. Hold a single dumbbell or kettlebell vertically against the chest with both hands, elbows tucked in.",
    steps: [
      "Brace the trunk and keep the weight held against the chest throughout.",
      "Sit down between the hips, letting the knees travel forward over the feet and the elbows pass inside the knees.",
      "Go as deep as can be reached with the heels down and the low back neutral.",
      "Keep the knees tracking over the middle of the feet rather than falling inward.",
      "Drive up through the whole foot to stand tall.",
    ],
    dosage: { sets: "3", reps: "8–12", frequency: "2–3x/week", loadOrTempo: "2–3 s lowering; load leaving 2–3 reps in reserve" },
    cue: "“Hold the weight tight to your chest and sit straight down between your hips — chest stays up.”",
    patientInstructions:
      "Stand a little wider than your hips with your toes turned slightly out, holding one weight upright against your chest with both hands. Sit straight down as far as you comfortably can, keeping your heels on the floor and your chest up, then drive back up. Eight to twelve repetitions, three sets. The weight held in front acts as a counterbalance and usually makes squatting easier, not harder.",
    commonErrors: [
      "Letting the weight drift away from the chest, which pulls the trunk forward",
      "Heels lifting, which usually means the ankles rather than the knees are the limit",
      "Knees falling inward on the way up",
      "Chasing depth at the cost of the low back rounding under at the bottom",
    ],
    regression: "Box Squat to a chair for a controlled depth, or Mini Squat with no weight.",
    progression: "Add load, slow the lowering, or pause at the bottom; then the Bulgarian Split Squat and the Single-Leg Squat to a Box.",
    precautions: [
      "Reduce depth for anterior knee pain — the deepest part of the range loads the kneecap most.",
      "Respect hip precautions after hip replacement, which limit how deep the hip may flex.",
      "Heels lifting is an ankle restriction: address that rather than forcing more depth.",
      "Follow the surgeon's protocol on loaded squatting after knee or hip surgery.",
    ],
  },
  {
    id: "drop-landing",
    name: "Drop Landing",
    aka: ["Landing mechanics drill", "Drop-to-land", "Stick the landing"],
    region: "Knee",
    category: "Power & Plyometric",
    positions: ["Standing"],
    equipment: ["Step or stairs"],
    difficulty: 3,
    phases: ["Return to Activity"],
    targets: ["Quadriceps", "Gluteus maximus", "Gluteus medius", "Calf complex", "Landing control"],
    indications: ["Return to sport after ACL reconstruction", "Dynamic knee valgus on landing", "Preparation for jumping and hopping", "Jump-landing injury prevention"],
    setup: "Stand on a low step or box, around 15–30 cm to begin with, with the feet hip-width apart and a clear landing area in front.",
    steps: [
      "Step — do not jump — off the box, dropping straight down onto both feet.",
      "Land on the balls of the feet first and let the heels settle, absorbing through the ankles, knees and hips together.",
      "Land softly and quietly: noise is the drill telling you the landing was stiff.",
      "Hold the landing position still for a count of two, knees bent and tracking over the feet.",
      "Check the knees did not fall inward, then step back up and reset.",
    ],
    dosage: { sets: "3", reps: "5–8", frequency: "2x/week", loadOrTempo: "Full reset between repetitions — this is a quality drill, not a conditioning one" },
    cue: "“Land quiet and soft, then freeze — knees over your toes, and hold it for two seconds before you move.”",
    patientInstructions:
      "Stand on a low step. Step off it — do not jump — and land on both feet, letting your ankles, knees and hips bend to absorb the landing. Land as quietly as you can, then hold still for two seconds before stepping back up. Five to eight repetitions, three sets, twice a week. A loud landing means you landed stiffly. If your knees dip inward as you land, use a lower step until they do not.",
    commonErrors: [
      "Jumping off the box rather than stepping off, which changes the height and the task",
      "Landing stiff-legged, which is what the noise is telling you",
      "Knees falling inward on contact — the single most important thing this drill exists to catch",
      "Landing on the heels rather than the balls of the feet",
      "Moving straight into the next repetition without holding and checking the landing",
    ],
    regression: "Lower the step, or drop it entirely and practise a squat-and-hold to groove the landing shape.",
    progression: "Raise the step gradually, then the Single-Leg Drop Landing, then the Countermovement Jump and hopping drills.",
    precautions: [
      "Late-stage only, and after clearance following knee or ankle surgery — landing load is far higher than anything in the strength work that precedes it.",
      "Stop the set the moment the knees start falling inward: quality is the whole point, and a fatigued landing teaches the wrong pattern.",
      "Not appropriate with an effusion, an unstable knee, or pain on impact.",
      "Needs a non-slip surface and a clear landing area.",
    ],
  },
  {
    id: "countermovement-jump",
    name: "Countermovement Jump",
    aka: ["Vertical jump", "CMJ", "Squat jump"],
    region: "Knee",
    category: "Power & Plyometric",
    positions: ["Standing"],
    equipment: ["None"],
    difficulty: 3,
    phases: ["Return to Activity"],
    targets: ["Quadriceps", "Gluteus maximus", "Calf complex", "Lower limb power"],
    indications: ["Return to sport", "Lower limb power deficit", "Limb symmetry testing after knee injury", "Preparation for running and jumping sport"],
    setup: "Stand with the feet hip-width apart on a firm, non-slip surface with room overhead.",
    steps: [
      "Dip quickly into a quarter squat, swinging the arms back.",
      "Reverse immediately and drive up through both feet, swinging the arms up — the dip and the jump are one continuous movement.",
      "Extend fully through the hips, knees and ankles at take-off.",
      "Land on the balls of the feet and absorb through the ankles, knees and hips, exactly as in the Drop Landing.",
      "Reset fully before the next repetition.",
    ],
    dosage: { sets: "3", reps: "5–8", frequency: "2x/week", loadOrTempo: "Maximal effort each repetition, with full recovery between sets" },
    cue: "“Dip and go in one movement — then land the way you practised, soft and quiet.”",
    patientInstructions:
      "Stand with your feet hip-width apart. Dip down quickly into a shallow squat, swinging your arms back, then immediately jump straight up as high as you can, swinging your arms up. Land softly on the balls of your feet and let your knees and hips bend to absorb it. Five to eight jumps, three sets, twice a week. Each jump should be a full effort, so rest between sets rather than rushing.",
    commonErrors: [
      "Pausing at the bottom of the dip, which loses the stretch and turns it into a slow squat jump",
      "Dipping far too deep",
      "Landing stiffly or noisily after a good jump — the landing matters as much as the height",
      "Knees falling inward on landing",
      "Doing so many repetitions that fatigue degrades the landing",
    ],
    regression: "Drop Landing to build the landing first, then small submaximal jumps landing in place.",
    progression: "Box Jump, Broad Jump, and then the Single-Leg Hop in Place and Single-Leg Hop for Distance.",
    precautions: [
      "Master the Drop Landing first: the take-off is rarely the problem, the landing is.",
      "Late-stage only, and after clearance following lower limb surgery.",
      "Not appropriate with an effusion, pain on impact, or an unstable knee.",
      "Stop for fatigue rather than working through it — power work loses its point once the quality drops.",
    ],
  },
  {
    id: "box-jump",
    name: "Box Jump",
    aka: ["Jump to box", "Box jump with step-down"],
    region: "Knee",
    category: "Power & Plyometric",
    positions: ["Standing"],
    equipment: ["Step or stairs"],
    difficulty: 4,
    phases: ["Return to Activity"],
    targets: ["Quadriceps", "Gluteus maximus", "Calf complex", "Lower limb power"],
    indications: ["Return to sport", "Lower limb power deficit", "Late-stage knee and ankle rehabilitation"],
    setup: "Stand a short step in front of a stable box or step at a height that can be cleared comfortably — start well below the maximum. The box must not slide or tip.",
    steps: [
      "Dip into a quarter squat and swing the arms back.",
      "Drive up and forward, landing softly on top of the box with both feet flat and the knees bent.",
      "Land in the same absorbed position practised in the Drop Landing, not upright and stiff.",
      "Stand up on the box, then step down one foot at a time.",
      "Reset on the floor before the next repetition.",
    ],
    dosage: { sets: "3", reps: "5–8", frequency: "2x/week", loadOrTempo: "Box height that allows a soft landing every time, not the highest that can be cleared" },
    cue: "“Jump up, land soft in a quarter squat on top — then step down, never jump down.”",
    patientInstructions:
      "Stand in front of a solid box or step. Dip down, swing your arms and jump up onto it, landing on both feet with your knees bent to absorb the landing. Stand up, then step down one foot at a time — do not jump down. Five to eight repetitions, three sets. Pick a height you can land on softly every time rather than the highest you can reach.",
    commonErrors: [
      "Jumping down from the box, which is a much harder landing than jumping up",
      "Choosing a height that forces a deep, scrambling landing",
      "Landing on the edge of the box",
      "Landing stiff and upright rather than absorbing",
      "Using a box that can slide or tip",
    ],
    regression: "Lower the box, or use the Countermovement Jump landing on the floor.",
    progression: "Raise the box gradually, then the Broad Jump and the Single-Leg Hop for Distance.",
    precautions: [
      "Always step down, never jump down: landing from a height is the highest-load part of the exercise and it is not what this drill is for.",
      "Use a stable, non-slip box that cannot tip, and keep the area clear.",
      "Late-stage only, after clearance following lower limb surgery, and not with an effusion or pain on impact.",
      "A missed box hits the shin — reduce the height rather than risking it when tired.",
    ],
  },
  {
    id: "broad-jump",
    name: "Broad Jump",
    aka: ["Standing long jump", "Horizontal jump"],
    region: "Knee",
    category: "Power & Plyometric",
    positions: ["Standing"],
    equipment: ["None"],
    difficulty: 4,
    phases: ["Return to Activity"],
    targets: ["Gluteus maximus", "Hamstrings", "Quadriceps", "Calf complex", "Horizontal power"],
    indications: ["Return to sport", "Horizontal power deficit", "Return to running and accelerating", "Late-stage knee rehabilitation"],
    setup: "Stand with the feet hip-width apart on a firm, non-slip surface with a clear run of floor ahead.",
    steps: [
      "Dip into a quarter squat, hinging the hips back and swinging the arms behind.",
      "Drive forward and up, extending fully through the hips and swinging the arms forward.",
      "Land on both feet with the hips back and the knees bent, absorbing the landing.",
      "Stick the landing and hold it still for two seconds before stepping out of it.",
      "Reset fully before the next repetition.",
    ],
    dosage: { sets: "3", reps: "4–6", frequency: "2x/week", loadOrTempo: "Maximal effort, full recovery between repetitions" },
    cue: "“Hips back, then drive forward — and stick the landing so it holds still for two seconds.”",
    patientInstructions:
      "Stand with your feet hip-width apart and clear floor in front. Push your hips back, swing your arms behind you, then jump forwards as far as you can. Land on both feet with your hips back and knees bent, and hold that landing still for two seconds. Four to six jumps, three sets. If you cannot hold the landing without stumbling, jump a little less far.",
    commonErrors: [
      "Jumping further than the landing can be controlled — distance is not the goal if the landing collapses",
      "Landing with straight legs, which is a very high-load landing",
      "Knees falling inward on landing",
      "Stepping or stumbling out of the landing rather than sticking it",
      "Going straight into the next jump without a reset",
    ],
    regression: "Shorten the jump deliberately, or return to the Countermovement Jump landing in place.",
    progression: "Repeated broad jumps, then a single-leg hop for distance.",
    precautions: [
      "The landing, not the jump, is the risk — if it cannot be held still for two seconds, the jump was too far.",
      "Late-stage only, after clearance following lower limb surgery.",
      "Not appropriate with an effusion, an unstable knee, or pain on impact.",
      "Needs a non-slip surface and clear space.",
    ],
  },
  {
    id: "single-leg-hop-for-distance",
    name: "Single-Leg Hop for Distance",
    aka: ["Single hop test", "One-leg hop", "Hop test"],
    region: "Knee",
    category: "Power & Plyometric",
    positions: ["Standing"],
    equipment: ["None"],
    difficulty: 4,
    phases: ["Return to Activity"],
    targets: ["Quadriceps", "Gluteus maximus", "Calf complex", "Single-leg power and control"],
    indications: ["Return to sport after ACL reconstruction", "Limb symmetry assessment", "Single-leg power deficit", "Late-stage knee and ankle rehabilitation"],
    setup: "Stand on one leg with the hands free, on a firm non-slip surface with clear floor ahead. Have a support within reach for the first attempts.",
    steps: [
      "Dip on the standing leg, hinging the hip back and swinging the arms behind.",
      "Hop forward as far as can be controlled and land on the same leg.",
      "Land on the ball of the foot with the knee bent and the hip back, absorbing the landing.",
      "Stick the landing and hold it still for two seconds — a hop that cannot be held does not count.",
      "Rest fully, then repeat; compare the two sides.",
    ],
    dosage: { sets: "2–3", reps: "3–5 each side", frequency: "2x/week", loadOrTempo: "Full recovery between hops; distance only counts when the landing holds" },
    cue: "“Hop only as far as you can land and hold — a wobble means that one did not count.”",
    patientInstructions:
      "Stand on one leg with clear floor ahead and something to steady yourself nearby. Swing your arms and hop forwards, landing on the same leg with your knee bent. Hold the landing still for two seconds. Three to five hops on each leg, two or three sets. Only hop as far as you can land and hold steady — a hop you stumble out of does not count, and comparing your two legs is the point of this one.",
    commonErrors: [
      "Hopping for maximum distance rather than maximum controlled distance",
      "Landing with the knee falling inward",
      "Touching down with the other foot to save the landing",
      "Landing with a straight knee",
      "Testing the injured side without comparing it against the other",
    ],
    regression: "Single-leg hop in place, or a double-leg Broad Jump until single-leg landing is controlled.",
    progression: "Triple hop, crossover hop, and timed hop variations; then change of direction work.",
    precautions: [
      "Requires solid single-leg strength and control first — this is near the end of a return-to-sport progression, not a way to test whether someone is ready to start one.",
      "Follow the surgeon's protocol: hop testing is usually gated to a specific point after ACL reconstruction.",
      "Not appropriate with an effusion, pain on impact, or an unstable knee.",
      "Any comparison between sides is a rough guide for the clinician, not a discharge decision on its own.",
    ],
  },
  {
    id: "deceleration-cutting-drill",
    name: "Deceleration and Cutting Drill",
    aka: ["Change of direction drill", "Cut and plant drill", "Decel drill"],
    region: "Knee",
    category: "Power & Plyometric",
    positions: ["Standing"],
    equipment: ["None"],
    difficulty: 4,
    phases: ["Return to Activity"],
    targets: ["Quadriceps", "Gluteus maximus", "Gluteus medius", "Hamstrings", "Change-of-direction control"],
    indications: ["Return to change-of-direction sport", "Late-stage ACL rehabilitation", "Dynamic knee valgus on cutting", "Return to field and court sport"],
    setup: "Mark a run of about 5 metres with a turning point at the end. Firm, non-slip surface, in trainers rather than bare feet.",
    steps: [
      "Jog, then run, to the marker.",
      "Decelerate over the last two or three steps by sinking the hips and shortening the stride — do not stop in one step.",
      "Plant the outside foot with the knee bent and tracking over the foot, then push off in the new direction.",
      "Start by turning 45 degrees, and progress toward 90 degrees only once the knee stays stable.",
      "Build from a jog to a run to a sprint across sessions, not within one.",
    ],
    dosage: { sets: "3–4", reps: "4–6 turns each direction", frequency: "2x/week", loadOrTempo: "Start at jogging pace and planned turns; add speed before adding unpredictability" },
    cue: "“Sink your hips and take small steps to slow down — then push off. Don't stop dead on one leg.”",
    patientInstructions:
      "Mark out about five metres. Jog to the marker, slow down over the last few steps by sinking your hips and taking smaller steps, plant your outside foot with your knee bent, and push off in a new direction. Start with gentle turns at jogging pace and only get faster once your knee feels steady and stays pointing over your foot. Four to six turns each way, three or four sets, twice a week.",
    commonErrors: [
      "Stopping dead in a single step instead of decelerating over several",
      "The planting knee falling inward — the position most associated with knee injury in sport",
      "Going straight to sharp, fast turns rather than building from shallow and slow",
      "Turning on a slippery surface or in unsuitable footwear",
      "Adding unpredictable, reactive turns before planned ones are controlled",
    ],
    regression: "Planned turns at walking or jogging pace with a shallower angle, or forward-and-backward deceleration with no turn at all.",
    progression: "Increase speed, then sharpen the angle, then make the turn reactive to a call or a signal rather than planned.",
    precautions: [
      "The last stage of a return-to-sport progression: hopping and landing should already be controlled and symmetrical.",
      "Follow the surgeon's and the treating clinician's protocol on when cutting is permitted after ACL reconstruction — this is usually one of the last things cleared.",
      "Not appropriate with an effusion, pain on impact, or any sense of the knee giving way.",
      "Stop for fatigue: cutting mechanics degrade quickly, and a tired turn is the risky one.",
    ],
  },
  {
    id: "single-leg-squat-to-box",
    name: "Single-Leg Squat to a Box",
    aka: ["Single-leg squat", "Pistol squat to box", "One-leg sit-down"],
    region: "Knee",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Chair", "Step or stairs"],
    difficulty: 4,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Quadriceps", "Gluteus maximus", "Gluteus medius", "Single-leg control"],
    indications: ["Single-leg strength deficit", "Limb symmetry deficit after ACL reconstruction", "Return to sport", "Patellofemoral pain once loading is tolerated"],
    setup: "Stand on one leg in front of a box, bench or chair set at about knee height, with the other leg held out in front. Keep a counter or wall within reach.",
    steps: [
      "Stand a short step in front of the box with the free leg extended forward, clear of the seat.",
      "Push the hips back and lower under control until the buttocks touch the box lightly.",
      "Touch — do not sit down and rest — then drive back up through the standing leg.",
      "Keep the knee tracking over the middle of the foot and the pelvis level throughout.",
      "Complete the set on one side, then compare against the other.",
    ],
    dosage: { sets: "3", reps: "6–10 each side", frequency: "2–3x/week", loadOrTempo: "3 s lowering; raise the box until every repetition is controlled" },
    cue: "“Hips back and lower slowly until you just kiss the box — knee over your foot, hips level.”",
    patientInstructions:
      "Stand on one leg in front of a box or chair at about knee height, with your other leg held out in front of you. Push your hips back and lower yourself slowly until you just touch the box, then stand back up without resting. Six to ten repetitions on each leg. Use a higher box if you cannot control the way down — the slow lowering is the point, not how low you go.",
    commonErrors: [
      "Dropping onto the box rather than controlling the descent",
      "Sitting down and resting between repetitions, which removes the hardest part",
      "The knee falling inward on the way up",
      "The pelvis dropping on the free-leg side",
      "Starting with a box so low that the lowering cannot be controlled",
    ],
    regression: "Raise the box, hold a counter with one hand, or use the Forward Step-Down for a shallower single-leg load.",
    progression: "Lower the box gradually, add a weight held at the chest, or slow the lowering further.",
    precautions: [
      "Box height is the dosage — a box too low turns a controlled lower into a drop, which is where knees are provoked.",
      "Reduce range for anterior knee pain, which this loads heavily at the bottom.",
      "Needs adequate single-leg balance; keep a support within reach.",
      "Follow the surgeon's protocol on single-leg loading after knee or hip surgery.",
    ],
  },
  {
    id: "single-leg-drop-landing",
    name: "Single-Leg Drop Landing",
    aka: ["One-leg drop landing", "Single-leg stick landing"],
    region: "Knee",
    category: "Power & Plyometric",
    positions: ["Standing"],
    equipment: ["Step or stairs"],
    difficulty: 4,
    phases: ["Return to Activity"],
    targets: ["Quadriceps", "Gluteus maximus", "Gluteus medius", "Calf complex", "Single-leg landing control"],
    indications: ["Return to sport after ACL reconstruction", "Dynamic knee valgus on single-leg landing", "Preparation for hopping and cutting", "Limb symmetry deficit in landing control"],
    setup: "Stand on one leg on a low step, 15–20 cm to begin with, with a clear landing area and a support within reach.",
    steps: [
      "Drop straight off the step — do not hop — and land on the same single leg.",
      "Land on the ball of the foot and absorb through the ankle, knee and hip together.",
      "Land quietly; noise means the landing was stiff.",
      "Hold the landing still for two seconds, knee tracking over the foot and pelvis level.",
      "Step back up and reset, then compare the two sides.",
    ],
    dosage: { sets: "3", reps: "4–6 each side", frequency: "2x/week", loadOrTempo: "Full reset between repetitions; a landing that cannot be held does not count" },
    cue: "“Land quiet on one leg and freeze — knee over your toes, hips level, hold it for two.”",
    patientInstructions:
      "Stand on one leg on a low step. Drop off it — do not hop — and land on that same leg, letting your ankle, knee and hip bend to absorb it. Land as quietly as you can and hold still for two seconds. Four to six on each leg, three sets. If your knee dips inward or you cannot hold the landing, use a lower step. Compare your two legs — the difference is what you are working on.",
    commonErrors: [
      "The knee falling inward on contact, which is exactly what this drill exists to catch",
      "Touching down with the other foot to save the landing",
      "Landing stiff-legged or on the heel",
      "Using a step too high for a controlled single-leg landing",
      "Continuing once fatigue starts degrading the landings",
    ],
    regression: "Drop Landing on both legs, or step down onto one leg from a lower step with no drop at all.",
    progression: "Raise the step gradually, then move to hopping drills and the Single-Leg Hop for Distance.",
    precautions: [
      "Single-leg landing roughly doubles the load of the double-leg version — progress from the Drop Landing rather than starting here.",
      "Late-stage only, and after clearance following knee or ankle surgery.",
      "Stop the set the moment the knee falls inward: a fatigued landing teaches the pattern this drill is meant to remove.",
      "Not appropriate with an effusion, pain on impact, or a knee that feels like it gives way.",
    ],
  },
  {
    id: "single-leg-swiss-ball-hamstring-curl",
    name: "Single-Leg Swiss Ball Hamstring Curl",
    aka: ["One-leg ball curl", "Single-leg stability ball curl"],
    region: "Knee",
    category: "Strength",
    positions: ["Supine"],
    equipment: ["Ball"],
    difficulty: 4,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Hamstrings", "Gluteus maximus", "Gastrocnemius", "Trunk"],
    indications: ["Hamstring strain rehabilitation", "Hamstring strength asymmetry", "Return to running and sprinting", "After ACL reconstruction with a hamstring graft"],
    setup: "Lie on the back with one heel on a large exercise ball and the other leg lifted clear of it, arms at the sides on a non-slip floor.",
    steps: [
      "Press the working heel into the ball and lift the hips into a bridge, keeping the free leg raised.",
      "Keeping the hips up and level, bend the working knee to roll the ball in.",
      "Hold the hips up as the ball arrives — the pelvis will want to drop on the free-leg side.",
      "Straighten the knee slowly to roll the ball back out.",
      "Complete the set on one side, then compare against the other.",
    ],
    dosage: { sets: "3", reps: "6–10 each side", frequency: "2x/week", loadOrTempo: "3 s to roll out; hips level, not just up" },
    cue: "“Hips up and square — don't let the side with the lifted leg drop as the ball comes in.”",
    patientInstructions:
      "Lie on your back with one heel on an exercise ball and your other leg lifted off it. Push through the heel on the ball to lift your hips, then bend that knee to roll the ball toward you, keeping your hips up and level. Straighten slowly to roll it back out. Six to ten repetitions on each leg. Expect the injured side to tire much sooner — that difference is what you are training.",
    commonErrors: [
      "The pelvis dropping on the free-leg side, which is the whole added difficulty of the single-leg version",
      "Letting the hips sag as the ball rolls in",
      "Rolling out fast instead of controlling the return",
      "Resting the free leg back on the ball partway through the set",
      "Working through cramp rather than reducing the range",
    ],
    regression: "Swiss Ball Hamstring Curl on both legs, or a single-leg bridge hold on the ball with no curl.",
    progression: "Slow the roll-out further, add repetitions, or move to eccentric-only work and the Nordic Hamstring Curl.",
    precautions: [
      "Hamstring cramping is common and is not a sign of injury — reduce range and volume rather than pushing through.",
      "Not appropriate while a hamstring strain is still painful under load.",
      "Follow the surgeon's protocol after ACL reconstruction with a hamstring graft, where hamstring loading is usually staged.",
      "Use a properly inflated ball on a non-slip floor — single-leg contact makes it easier for the ball to slide away.",
    ],
  },
  {
    id: "prone-quad-stretch",
    name: "Prone Quadriceps Stretch",
    aka: ["Prone heel to buttock", "Strap quad stretch"],
    region: "Knee",
    category: "Flexibility",
    positions: ["Prone", "Standing", "Sidelying"],
    equipment: ["Towel or strap"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Quadriceps", "Rectus femoris", "Hip flexors"],
    indications: ["Quadriceps tightness", "Anterior knee pain", "Loss of knee flexion", "Anterior hip tightness"],
    setup: "Lie face down with a pillow under the hips. Loop a strap or towel around the ankle of the leg being stretched.",
    steps: [
      "Draw the heel gently toward the buttock using the strap.",
      "Keep the hips pressed down into the pillow — the low back must not arch.",
      "Keep the knees close together.",
      "Hold, then release slowly.",
    ],
    dosage: { sets: "2–3", reps: "1 each side", hold: "30 s", frequency: "Once daily" },
    cue: "“Keep your hips pressed down — if your back arches, ease off. Knees stay together.”",
    patientInstructions:
      "Lie face down with a pillow under your hips. Loop a towel around one ankle and gently pull the heel toward your bottom until you feel a stretch at the front of your thigh. Keep your hips pressed down and your knees together. Hold thirty seconds. Two or three times each side.",
    commonErrors: [
      "Arching the low back to gain range",
      "Letting the knee drift out to the side",
      "Pulling hard enough to cause knee pain rather than a thigh stretch",
    ],
    regression: "Do it sidelying, or standing holding a counter, with a smaller range.",
    progression: "Hold longer, or add a posterior pelvic tilt to bias the hip flexor component.",
    precautions: [
      "Stop for knee pain — the stretch belongs in the thigh, not the knee joint.",
      "Not appropriate where knee flexion is restricted after surgery until the surgeon permits it.",
      "Take care with any history of patellar instability.",
    ],
  },
  {
    id: "lateral-thigh-foam-roll",
    name: "Lateral Thigh Foam Roll",
    aka: ["ITB foam rolling", "Lateral quadriceps release"],
    region: "Knee",
    category: "Mobility",
    positions: ["Sidelying"],
    equipment: ["Foam roller"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Vastus lateralis", "Tensor fascia latae", "Lateral thigh soft tissue"],
    indications: ["Lateral knee pain", "Lateral thigh tightness", "Patellofemoral pain with lateral tracking"],
    setup: "Lie on one side with a foam roller under the outside of the thigh, supported on the forearm, with the top leg crossed in front for weight control.",
    steps: [
      "Use the top foot and the supporting arm to control how much weight goes through the roller.",
      "Roll slowly from just below the hip to just above the knee.",
      "Pause on tender areas and breathe rather than gritting through them.",
      "Never roll directly over the bony point of the hip or the outside of the knee.",
    ],
    dosage: { sets: "1–2", reps: "1", hold: "60–90 s per side", frequency: "Once daily" },
    cue: "“Use your top foot to take weight off — this should be a firm pressure you can breathe through, not something you brace against.”",
    patientInstructions:
      "Lie on your side with a foam roller under the outside of your thigh, propped on your forearm with your top foot on the floor in front to take some of your weight. Roll slowly between your hip and your knee for a minute or so. Stay off the bony points at your hip and knee. If it is too intense, put more weight on your top foot.",
    commonErrors: [
      "Rolling directly over the bony point of the hip or the outside of the knee",
      "Using so much pressure that the muscles guard the whole time",
      "Rolling fast rather than slowly",
      "Holding the breath",
    ],
    regression: "Take more weight through the top foot and arm, or use a softer roller.",
    progression: "Take more weight through the roller, or pause longer on tender areas.",
    precautions: [
      "Avoid over bony points, varicose veins, or areas of numbness.",
      "Avoid where there is a bleeding disorder, on anticoagulants, or over recent injury or surgery, unless specifically cleared.",
    ],
  },
];
