import type { MovementExercise } from "@/lib/movement-lab/types";

/** Lumbar spine and trunk. The largest region in the bank, because low back pain is the
 *  most-prescribed HEP there is and because the entries here have to cover two clinically
 *  opposite groups — the extension-preference presentation and the flexion-preference
 *  presentation — without implying either one is the default. */
export const LUMBAR_CORE_EXERCISES: MovementExercise[] = [
  {
    id: "posterior-pelvic-tilt",
    name: "Posterior Pelvic Tilt",
    aka: ["Pelvic tilt", "Flat back press"],
    region: "Lumbar & Core",
    category: "Motor Control",
    positions: ["Supine"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Lower abdominals", "Gluteals", "Lumbar multifidus"],
    indications: ["Acute low back pain", "Poor lumbopelvic awareness", "Pre-requisite for core motor control work"],
    setup: "Lie on the back with knees bent and feet flat, arms relaxed at the sides.",
    steps: [
      "Flatten the low back gently toward the floor by rolling the pelvis backward — the tailbone tips slightly up.",
      "Hold without pushing through the feet or holding the breath.",
      "Release and let the natural small arch return.",
    ],
    dosage: { sets: "2", reps: "10", hold: "5 s", frequency: "1–2x/day" },
    cue: "“Roll your pelvis so your belt buckle tips toward your chin and your low back flattens gently — no pushing with your feet.”",
    patientInstructions:
      "Lie on your back with your knees bent and feet flat. Gently flatten your lower back toward the floor by tipping your pelvis backwards. Hold five seconds, then relax. Ten repetitions, once or twice a day.",
    commonErrors: [
      "Pushing through the heels to lever the pelvis rather than using the abdominals",
      "Lifting the hips off the floor, which makes it a bridge",
      "Holding the breath",
    ],
    regression: "Reduce the hold to 2–3 seconds and use a smaller range.",
    progression: "Hold the tilt while adding a single heel slide or a supine march.",
    precautions: [
      "Not the right first exercise if lumbar flexion clearly worsens symptoms — an extension-preference presentation starts elsewhere.",
      "Stop if it increases leg symptoms.",
    ],
  },
  {
    id: "abdominal-draw-in",
    name: "Abdominal Draw-In",
    aka: ["Transversus abdominis activation", "Drawing-in manoeuvre", "Core setting"],
    region: "Lumbar & Core",
    category: "Activation",
    positions: ["Supine", "Quadruped", "Seated"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Transversus abdominis", "Lumbar multifidus", "Pelvic floor"],
    indications: ["Low back pain", "Poor deep abdominal recruitment", "Post-partum core retraining", "Pre-requisite for progressive core loading"],
    setup: "Lie on the back with knees bent. Place the fingertips just inside the front of the pelvic bones.",
    steps: [
      "Breathe out normally.",
      "Draw the lower belly gently inward and upward — a light tightening under the fingertips, roughly a quarter of maximum effort.",
      "Keep breathing normally through the hold; the ribs should not clamp down and the pelvis should not tilt.",
      "Release fully between repetitions.",
    ],
    dosage: { sets: "2–3", reps: "10", hold: "10 s", frequency: "1–2x/day", loadOrTempo: "About 25% effort — gentle, not a maximal brace" },
    cue: "“Draw your lower belly in gently, like doing up a tight pair of trousers — and keep talking to me while you do it.”",
    patientInstructions:
      "Lie on your back with your knees bent. Put your fingertips just inside your hip bones. Breathe out, then gently draw your lower tummy in and up — you should feel a light tightening under your fingers. Keep breathing normally and hold for ten seconds. Repeat ten times.",
    commonErrors: [
      "Bracing hard and bearing down instead of a light draw-in",
      "Holding the breath",
      "Tilting the pelvis or squeezing the buttocks to make it happen",
      "Sucking the whole belly in with the diaphragm",
    ],
    regression: "Shorten the hold to 5 seconds; do it in four-point kneeling, where gravity gives feedback.",
    progression: "Maintain the contraction through a heel slide, a supine march, then a dead bug.",
    precautions: [
      "Stop if it causes downward pressure on the pelvic floor — that is bearing down, not a draw-in.",
      "Follow specific guidance where there is a known abdominal wall separation, hernia, or recent abdominal surgery.",
    ],
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    aka: ["Supine alternating arm and leg", "Core stability with limb loading"],
    region: "Lumbar & Core",
    category: "Motor Control",
    positions: ["Supine"],
    equipment: ["None"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Transversus abdominis", "Rectus abdominis", "Obliques", "Hip flexors"],
    indications: ["Low back pain", "Trunk stability deficits", "Return to lifting or sport", "Post-partum core progression"],
    setup: "Lie on the back with the hips and knees bent to 90 degrees and the arms reaching straight up toward the ceiling.",
    steps: [
      "Set a gentle abdominal draw-in and flatten the low back lightly toward the floor.",
      "Slowly lower one arm overhead and the opposite leg toward the floor.",
      "Go only as far as the low back stays put — the moment it arches, that is the end of the range.",
      "Return to the start and repeat on the other side. Breathe out as the limbs move away.",
    ],
    dosage: { sets: "2–3", reps: "6–10 each side", frequency: "Every other day", loadOrTempo: "Slow — about 3 s out and 3 s back" },
    cue: "“Keep your low back quiet — as soon as it starts to arch, that's your range, come back.”",
    patientInstructions:
      "Lie on your back with your knees bent up over your hips and your arms reaching to the ceiling. Gently tighten your tummy. Slowly lower one arm back overhead and the opposite leg down toward the floor, only as far as you can go without your back arching off the floor. Bring them back and swap sides. Six to ten each side.",
    commonErrors: [
      "Letting the low back arch away from the floor as the leg lowers",
      "Moving fast, which hides the loss of control",
      "Holding the breath instead of breathing out on the effort",
      "Reaching for full range before the control is there",
    ],
    regression: "Move one limb at a time — arms only, or legs only — with a smaller range.",
    progression: "Increase the range toward the floor, slow the tempo further, or add a light weight in the hands.",
    precautions: [
      "Stop if leg symptoms increase.",
      "Reduce the range where an abdominal wall separation is present and the midline domes during the movement.",
    ],
  },
  {
    id: "bird-dog",
    name: "Bird Dog",
    aka: ["Quadruped alternating arm and leg", "Opposite arm and leg raise"],
    region: "Lumbar & Core",
    category: "Motor Control",
    positions: ["Quadruped"],
    equipment: ["None"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Lumbar multifidus", "Gluteus maximus", "Erector spinae", "Obliques"],
    indications: ["Low back pain", "Trunk endurance deficits", "Return to lifting", "General spine conditioning"],
    setup: "Hands and knees, hands under shoulders and knees under hips, spine in a neutral position.",
    steps: [
      "Set a light abdominal contraction and keep the spine still.",
      "Reach one arm forward and the opposite leg straight back, no higher than the level of the trunk.",
      "Keep the hips level — a glass of water on the low back should not spill.",
      "Hold, then return under control and switch sides.",
    ],
    dosage: { sets: "2–3", reps: "8–10 each side", hold: "5–8 s", frequency: "Every other day" },
    cue: "“Reach long, not high — imagine balancing a glass of water on your low back the whole time.”",
    patientInstructions:
      "On your hands and knees, tighten your tummy gently. Reach one arm forwards and the opposite leg backwards, no higher than your body. Keep your hips level and your back still. Hold five to eight seconds, come back, and swap sides. Eight to ten each side.",
    commonErrors: [
      "Lifting the arm and leg too high, which arches the low back",
      "Rotating the hips as the leg goes back",
      "Letting the head drop or crane up instead of staying in line",
      "Rushing the switch between sides",
    ],
    regression: "Arm only, then leg only, before combining them.",
    progression: "Longer holds, add a small draw-in of the elbow to the knee between repetitions, or perform from a plank position.",
    precautions: [
      "Needs comfortable weight-bearing through the wrists and knees.",
      "Stop if it reproduces leg symptoms.",
    ],
    note: "One of the three trunk-endurance exercises commonly taught together with the curl-up and side plank.",
  },
  {
    id: "mcgill-curl-up",
    name: "Curl-Up (One Knee Bent)",
    aka: ["McGill curl-up", "Modified curl-up"],
    region: "Lumbar & Core",
    category: "Strength",
    positions: ["Supine"],
    equipment: ["None"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Rectus abdominis", "Obliques"],
    indications: ["Low back pain", "Abdominal endurance deficit", "General trunk conditioning"],
    setup: "Lie on the back with one knee bent and foot flat, the other leg straight. Slide both hands under the low back to keep it in its natural small arch.",
    steps: [
      "Keep the low back in neutral — do not flatten it against the hands.",
      "Lift the head, neck and shoulders as one unit just off the floor, only a few centimetres.",
      "Hold, breathing normally.",
      "Lower under control. Swap which leg is bent halfway through the set.",
    ],
    dosage: { sets: "2–3", reps: "6–8", hold: "8–10 s", frequency: "Every other day" },
    cue: "“Head, neck and chest come up as one block — don't curl your spine, and don't press your back into your hands.”",
    patientInstructions:
      "Lie on your back with one knee bent and the other leg straight. Put your hands under your lower back to keep its natural curve. Lift your head, neck and shoulders together just a few centimetres off the floor and hold for eight to ten seconds, breathing normally. Lower down. Six to eight repetitions, swapping which knee is bent halfway through.",
    commonErrors: [
      "Doing a full sit-up, which loads the spine into repeated flexion",
      "Flattening the low back into the hands",
      "Pulling on the neck or tucking the chin hard",
      "Holding the breath",
    ],
    regression: "Shorten the hold to 3–5 seconds and lift a smaller distance.",
    progression: "Longer holds and more repetitions, rather than a larger range.",
    precautions: [
      "Not appropriate where lumbar flexion clearly worsens symptoms.",
      "Reduce or avoid where an abdominal wall separation domes on lifting.",
    ],
    note: "Deliberately a small-range hold rather than a sit-up — the flexion range is kept minimal on purpose.",
  },
  {
    id: "side-plank-modified",
    name: "Side Plank (Knees Bent)",
    aka: ["Modified side bridge", "Short-lever side plank"],
    region: "Lumbar & Core",
    category: "Strength",
    positions: ["Sidelying"],
    equipment: ["None"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Quadratus lumborum", "Obliques", "Gluteus medius"],
    indications: ["Low back pain", "Lateral trunk endurance deficit", "Hip abductor weakness"],
    setup: "Lie on one side propped on the forearm, elbow directly under the shoulder, knees bent to about 90 degrees and stacked.",
    steps: [
      "Stack the shoulders and hips so the body is in one plane.",
      "Lift the hips off the floor so the body forms a straight line from head to knees.",
      "Hold, breathing normally, without letting the hips sag or rotate.",
      "Lower under control and rest before the next repetition.",
    ],
    dosage: { sets: "2–3", reps: "5–8 each side", hold: "10–20 s", frequency: "Every other day" },
    cue: "“Push the floor away with your elbow and lift your hips into one straight line — don't let your top hip roll backwards.”",
    patientInstructions:
      "Lie on your side propped up on your forearm, with your elbow under your shoulder and your knees bent. Lift your hips off the floor so your body is in a straight line from your head to your knees. Hold ten to twenty seconds, then lower. Five to eight holds on each side.",
    commonErrors: [
      "Letting the top shoulder and hip roll forward or back",
      "Letting the hips sag toward the floor during the hold",
      "Placing the elbow too far forward or behind the shoulder",
      "Holding to failure rather than stopping while the line is clean",
    ],
    regression: "Do it against a wall standing, or simply hold the sidelying position without lifting the hips.",
    progression: "Straighten the legs for a full-length side plank, then add a top-leg lift or a hip dip.",
    precautions: [
      "Not appropriate where the shoulder cannot bear weight comfortably.",
      "Stop for sharp low back or shoulder pain rather than pushing through.",
    ],
  },
  {
    id: "front-plank",
    name: "Front Plank",
    aka: ["Prone plank", "Forearm plank"],
    region: "Lumbar & Core",
    category: "Strength",
    positions: ["Prone"],
    equipment: ["None"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Rectus abdominis", "Transversus abdominis", "Obliques", "Gluteals", "Shoulder girdle"],
    indications: ["Trunk endurance deficit", "Return to lifting or sport", "General conditioning"],
    setup: "Lie face down and prop on the forearms with elbows under the shoulders. Legs straight, toes tucked.",
    steps: [
      "Lift the hips so the body forms a straight line from head to heels.",
      "Squeeze the glutes lightly and tuck the tailbone slightly so the low back does not sag.",
      "Push the floor away through the forearms so the shoulder blades stay spread rather than collapsed.",
      "Hold, breathing normally, and come down before the line breaks.",
    ],
    dosage: { sets: "2–3", reps: "3–5", hold: "20–30 s", frequency: "Every other day" },
    cue: "“Straight line from your ears to your heels — squeeze your glutes and stop the moment your hips start to drop.”",
    patientInstructions:
      "Lie face down and prop yourself on your forearms with your elbows under your shoulders. Lift your hips so your body makes a straight line from head to heels. Squeeze your buttocks and keep breathing. Hold twenty to thirty seconds, then rest. Three to five holds.",
    commonErrors: [
      "Letting the hips sag, which loads the low back",
      "Piking the hips up to make it easier",
      "Holding the breath",
      "Holding to failure instead of stopping while the position is good",
    ],
    regression: "Plank from the knees, or from the forearms against a wall or a countertop.",
    progression: "Longer holds, then add an alternating arm or leg lift, or a plank with a shoulder tap.",
    precautions: [
      "Not appropriate where the shoulders or wrists cannot tolerate loading.",
      "Reduce or avoid where an abdominal wall separation domes visibly during the hold.",
      "Stop for low back pain during the hold rather than pushing to time.",
    ],
  },
  {
    id: "prone-press-up",
    name: "Prone Press-Up",
    aka: ["Press-up in lying", "Cobra", "Extension in lying"],
    region: "Lumbar & Core",
    category: "Mobility",
    positions: ["Prone"],
    equipment: ["None"],
    difficulty: 2,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Lumbar spine", "Anterior disc structures", "Lumbar extensors"],
    indications: ["Low back pain with an extension preference", "Disc-related leg pain that centralises with extension", "Loss of lumbar extension"],
    setup: "Lie face down with the hands flat under the shoulders, as if about to push up. Let the whole body relax first for a minute.",
    steps: [
      "Push the upper body up on the arms while the hips and legs stay completely relaxed on the floor.",
      "Go up only as far as is comfortable — the hips stay down.",
      "Hold for a second or two at the top, breathing out.",
      "Lower all the way down and let everything relax before the next repetition.",
    ],
    dosage: { sets: "1", reps: "10", hold: "1–2 s", frequency: "Every 2–3 hours during a flare" },
    cue: "“Push your chest up and let your hips stay heavy on the floor — your low back does nothing, your arms do the work.”",
    patientInstructions:
      "Lie face down with your hands flat under your shoulders. Relax completely for a minute. Then push your upper body up with your arms, letting your hips and legs stay relaxed on the floor. Go up only as far as is comfortable, hold a second, and lower all the way down. Ten repetitions, every couple of hours while your back is sore. If pain moves out of your leg and closer to your back, that is a good sign. If it travels further down your leg, stop and tell your therapist.",
    commonErrors: [
      "Tensing the buttocks and low back to lift, instead of letting the arms do it",
      "Lifting the hips off the floor",
      "Going straight to full range on the first repetition instead of building up",
      "Continuing when leg symptoms are travelling further down the leg",
    ],
    regression: "Prone lying propped on the elbows, held for a few minutes, before adding the press-up.",
    progression: "Increase the height reached, hold longer at the top, or add gentle over-pressure by exhaling at end range.",
    precautions: [
      "Peripheralising symptoms — pain moving further down the leg — mean stop, not push on.",
      "Not appropriate where extension clearly worsens symptoms, including many cases of lumbar spinal stenosis.",
      "Avoid or modify with spondylolisthesis, and after recent lumbar surgery until cleared.",
    ],
    note: "The extension-in-lying progression used in McKenzie-style directional-preference management.",
  },
  {
    id: "standing-lumbar-extension",
    name: "Standing Lumbar Extension",
    aka: ["Standing back bend", "Extension in standing"],
    region: "Lumbar & Core",
    category: "Mobility",
    positions: ["Standing"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore", "Return to Activity"],
    targets: ["Lumbar spine", "Lumbar extensors"],
    indications: ["Low back pain with an extension preference", "Prolonged sitting or driving", "Occupational flexion loading"],
    setup: "Stand with the feet shoulder-width apart and both hands on the low back, fingers pointing down.",
    steps: [
      "Use the hands as a fulcrum and lean the trunk backward.",
      "Keep the knees straight and the eyes forward rather than looking up.",
      "Hold briefly at end range, then return to upright.",
    ],
    dosage: { sets: "1", reps: "8–10", hold: "1–2 s", frequency: "Every 1–2 hours of sitting" },
    cue: "“Hands on your belt line, lean back over them — small and often beats one big stretch.”",
    patientInstructions:
      "Stand with your feet apart and both hands on your lower back. Lean backwards over your hands as far as is comfortable, hold a second, and come back up. Eight to ten repetitions, every hour or two if you are sitting a lot.",
    commonErrors: [
      "Bending the knees and pushing the hips forward instead of extending the back",
      "Throwing the head back",
      "Doing one hard repetition rather than a set of moderate ones",
    ],
    regression: "Reduce the range, or use the prone press-up instead where lying down is available.",
    progression: "Increase the range gradually, or hold at end range for a few seconds.",
    precautions: [
      "Stop if symptoms travel further down the leg.",
      "Not appropriate where extension worsens symptoms, as in many cases of spinal stenosis.",
      "Take care with balance — stand near a wall if unsteady.",
    ],
  },
  {
    id: "single-knee-to-chest",
    name: "Single Knee to Chest",
    region: "Lumbar & Core",
    category: "Flexibility",
    positions: ["Supine"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Lumbar extensors", "Gluteus maximus", "Posterior hip"],
    indications: ["Low back stiffness", "Lumbar spinal stenosis", "Morning back stiffness", "Post-exercise back tightness"],
    setup: "Lie on the back with both knees bent and feet flat.",
    steps: [
      "Bring one knee up and hold behind the thigh or over the top of the shin.",
      "Draw the knee gently toward the chest until a comfortable stretch is felt in the buttock or low back.",
      "Keep the other foot flat on the floor and the low back relaxed.",
      "Hold, then lower slowly and swap sides.",
    ],
    dosage: { sets: "2–3", reps: "1 each side", hold: "20–30 s", frequency: "1–2x/day" },
    cue: "“Pull the knee toward your chest until you feel a comfortable pull in your buttock — keep your other foot planted.”",
    patientInstructions:
      "Lie on your back with your knees bent. Bring one knee up toward your chest and hold behind your thigh. Pull gently until you feel a comfortable stretch in your buttock or lower back. Hold twenty to thirty seconds, then lower it. Repeat on the other side, two or three times each.",
    commonErrors: [
      "Pulling over the front of the knee where the knee is painful — hold behind the thigh instead",
      "Lifting the head and neck to meet the knee",
      "Pulling hard enough to lift the pelvis off the floor",
    ],
    regression: "Reduce the range and hold 10–15 seconds.",
    progression: "Double Knee to Chest, or hold longer.",
    precautions: [
      "Hold behind the thigh after a hip or knee replacement, and follow the surgeon's hip precautions on how far the hip may bend.",
      "Stop if it increases leg symptoms.",
    ],
  },
  {
    id: "double-knee-to-chest",
    name: "Double Knee to Chest",
    region: "Lumbar & Core",
    category: "Flexibility",
    positions: ["Supine"],
    equipment: ["None"],
    difficulty: 2,
    phases: ["Subacute / Restore"],
    targets: ["Lumbar extensors", "Gluteus maximus"],
    indications: ["Lumbar spinal stenosis", "Low back stiffness with a flexion preference", "Facet-related back pain"],
    setup: "Lie on the back with both knees bent and feet flat.",
    steps: [
      "Bring one knee up at a time and hold behind both thighs.",
      "Draw both knees gently toward the chest until a comfortable stretch is felt across the low back.",
      "Hold, breathing normally.",
      "Lower one leg at a time back to the floor.",
    ],
    dosage: { sets: "2–3", reps: "1", hold: "20–30 s", frequency: "1–2x/day" },
    cue: "“Bring your knees up one at a time, hold behind your thighs, and let your low back round comfortably.”",
    patientInstructions:
      "Lie on your back with your knees bent. Bring one knee up at a time and hold behind both thighs. Draw both knees gently toward your chest until you feel a comfortable stretch across your lower back. Hold twenty to thirty seconds, then put your feet down one at a time.",
    commonErrors: [
      "Lifting both legs up together, which loads the back at the start",
      "Rocking hard into the stretch",
      "Dropping both feet back down at once",
    ],
    regression: "Single Knee to Chest.",
    progression: "Add a gentle rock side to side, or hold longer.",
    precautions: [
      "Not appropriate where flexion clearly worsens symptoms, including many disc-related presentations.",
      "Follow hip precautions after hip replacement.",
      "Avoid where osteoporosis makes loaded spinal flexion inadvisable.",
    ],
  },
  {
    id: "lower-trunk-rotation",
    name: "Lower Trunk Rotation",
    aka: ["Windshield wipers", "Supine knee rolls"],
    region: "Lumbar & Core",
    category: "Mobility",
    positions: ["Supine"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Lumbar rotators", "Obliques", "Quadratus lumborum"],
    indications: ["Low back stiffness", "Muscle guarding after a back flare", "General lumbar mobility"],
    setup: "Lie on the back with knees bent and feet flat, knees and feet together, arms out to the sides.",
    steps: [
      "Keeping the knees together, let both knees fall slowly to one side.",
      "Go only as far as is comfortable, letting the opposite shoulder stay down.",
      "Hold briefly, then bring the knees back through the middle to the other side.",
    ],
    dosage: { sets: "1–2", reps: "8–10 each side", hold: "2–3 s", frequency: "1–2x/day" },
    cue: "“Let your knees roll like a windscreen wiper — keep both shoulders on the floor.”",
    patientInstructions:
      "Lie on your back with your knees bent, feet together and arms out to the sides. Let both knees roll slowly to one side as far as is comfortable, keeping both shoulders on the floor. Come back through the middle and roll to the other side. Eight to ten each way.",
    commonErrors: [
      "Letting the opposite shoulder lift off the floor",
      "Dropping the knees fast and bouncing at end range",
      "Separating the knees during the roll",
    ],
    regression: "Reduce the range, or put a pillow on the floor for the knees to land on.",
    progression: "Straighten the legs a little to lengthen the lever, or hold at end range for a stretch.",
    precautions: [
      "Keep the range small during an acute flare.",
      "Stop if it increases leg symptoms.",
    ],
  },
  {
    id: "child-pose",
    name: "Child's Pose",
    aka: ["Prayer stretch", "Quadruped rock back"],
    region: "Lumbar & Core",
    category: "Flexibility",
    positions: ["Kneeling", "Quadruped"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Lumbar extensors", "Latissimus dorsi", "Gluteus maximus"],
    indications: ["Low back stiffness with a flexion preference", "Lumbar spinal stenosis", "General spinal decompression"],
    setup: "Start on hands and knees with the knees about hip-width apart.",
    steps: [
      "Sit the hips back toward the heels.",
      "Let the arms stay reaching forward and the chest sink toward the floor.",
      "Rest the forehead on the floor or a cushion if it reaches comfortably.",
      "Hold, breathing into the back of the ribs.",
    ],
    dosage: { sets: "2–3", reps: "1", hold: "30 s", frequency: "1–2x/day" },
    cue: "“Sit your hips back toward your heels and breathe into your back — let the whole spine lengthen.”",
    patientInstructions:
      "Start on your hands and knees. Sit your hips back toward your heels, keeping your arms reaching forward. Rest your forehead on the floor or a cushion. Breathe slowly and hold for thirty seconds. Repeat two or three times.",
    commonErrors: [
      "Forcing the hips all the way back when the knees or hips won't allow it",
      "Holding the breath",
      "Letting the shoulders shrug up around the ears",
    ],
    regression: "Do it seated in a chair, folding the trunk forward over the thighs.",
    progression: "Reach the hands off to one side to bias the stretch down that side of the back.",
    precautions: [
      "Not appropriate where the knees will not bend fully or comfortably, or after knee replacement until cleared.",
      "Not appropriate where flexion worsens symptoms.",
      "Avoid loaded spinal flexion where osteoporosis is significant.",
    ],
  },
  {
    id: "seated-lumbar-flexion",
    name: "Seated Lumbar Flexion",
    aka: ["Seated forward bend", "Flexion in sitting"],
    region: "Lumbar & Core",
    category: "Mobility",
    positions: ["Seated"],
    equipment: ["Chair"],
    difficulty: 1,
    phases: ["Subacute / Restore", "Return to Activity"],
    targets: ["Lumbar spine", "Lumbar extensors"],
    indications: ["Lumbar spinal stenosis", "Neurogenic claudication", "Low back pain with a flexion preference"],
    setup: "Sit on the front half of a firm chair with the feet flat and the knees apart.",
    steps: [
      "Let the trunk fold forward between the knees, reaching the hands toward the floor.",
      "Go only as far as is comfortable and let the low back round.",
      "Hold briefly, then use the hands on the thighs to push back up to sitting.",
    ],
    dosage: { sets: "1–2", reps: "8–10", hold: "2–3 s", frequency: "2–3x/day, or when symptoms build with walking" },
    cue: "“Fold forward between your knees and let your back round — this is the position that usually settles the leg symptoms.”",
    patientInstructions:
      "Sit forward on a firm chair with your knees apart. Bend forward between your knees, reaching your hands toward the floor, letting your lower back round. Hold a couple of seconds, then push up with your hands on your thighs. Eight to ten repetitions, a few times a day or whenever your leg symptoms build up.",
    commonErrors: [
      "Coming back up without using the hands, which loads the back unnecessarily",
      "Bouncing at end range",
      "Doing it on a low, soft seat that makes standing back up hard",
    ],
    regression: "Reduce the range, or use single knee to chest lying down instead.",
    progression: "Progress toward a supported standing forward bend, or hold at end range for a stretch.",
    precautions: [
      "Not appropriate where flexion worsens symptoms, as in many disc-related presentations.",
      "Avoid repeated loaded flexion where osteoporosis is significant.",
      "Come up slowly if prone to dizziness on changing position.",
    ],
  },
  {
    id: "hip-hinge-dowel",
    name: "Hip Hinge with a Dowel",
    aka: ["Dowel hinge", "Broomstick hinge", "Hip hinge pattern training"],
    region: "Lumbar & Core",
    category: "Motor Control",
    positions: ["Standing"],
    equipment: ["Cane or dowel"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Gluteus maximus", "Hamstrings", "Lumbar extensors"],
    indications: ["Low back pain with lifting", "Return to work with manual handling", "Deadlift or lifting technique retraining"],
    setup: "Stand with the feet hip-width apart. Hold a dowel vertically along the spine, touching the back of the head, the mid-back, and the tailbone — one hand at the neck, one at the low back.",
    steps: [
      "Push the hips straight backward, letting the knees bend slightly.",
      "Keep all three contact points on the dowel throughout — that is what proves the spine stayed neutral.",
      "Lower until a stretch is felt in the hamstrings, then drive the hips forward to stand up.",
    ],
    dosage: { sets: "2–3", reps: "8–12", frequency: "Every other day", loadOrTempo: "Controlled — about 2 s down, 1 s up" },
    cue: "“Push your hips back toward the wall behind you and keep all three points on the stick — the bend comes from your hips, not your back.”",
    patientInstructions:
      "Stand holding a broomstick vertically against your back so it touches the back of your head, your mid back, and your tailbone. Push your hips backwards, letting your knees bend a little, until you feel a stretch in the back of your thighs. Keep all three contact points on the stick. Stand back up by pushing your hips forward. Eight to twelve repetitions.",
    commonErrors: [
      "Losing contact at the low back, which means the spine rounded",
      "Squatting down rather than hinging back",
      "Looking up hard, which arches the neck off the dowel",
      "Going deeper than the hamstrings allow",
    ],
    regression: "Hinge with the hips a few inches from a wall, tapping the wall with the hips as the target.",
    progression: "Remove the dowel, then add load — a kettlebell or dumbbells — once the pattern is reliable.",
    precautions: [
      "Reduce depth if it reproduces back pain.",
      "Add load only once the unloaded pattern is consistent.",
    ],
  },
  {
    id: "supine-marching",
    name: "Supine Marching",
    aka: ["Heel taps", "Alternating leg lifts with core hold"],
    region: "Lumbar & Core",
    category: "Motor Control",
    positions: ["Supine"],
    equipment: ["None"],
    difficulty: 2,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Transversus abdominis", "Hip flexors", "Obliques"],
    indications: ["Low back pain", "Early core progression", "Post-partum core retraining"],
    setup: "Lie on the back with the knees bent and feet flat, arms at the sides.",
    steps: [
      "Set a gentle abdominal draw-in and keep the pelvis still.",
      "Lift one foot a few inches off the floor, keeping the knee bent.",
      "Lower it under control without letting the pelvis rock or the back arch.",
      "Alternate sides, breathing normally.",
    ],
    dosage: { sets: "2–3", reps: "10 each side", frequency: "Once daily", loadOrTempo: "Slow — the pelvis must not move" },
    cue: "“Lift your foot like you're stepping over a low kerb — and keep your hips completely still while you do it.”",
    patientInstructions:
      "Lie on your back with your knees bent. Gently tighten your tummy. Lift one foot a few inches off the floor, keeping your knee bent, then lower it slowly. Keep your hips and back completely still. Alternate legs, ten each side.",
    commonErrors: [
      "Letting the pelvis rock side to side as the leg lifts",
      "Arching the low back",
      "Lifting the foot high, which is the hip flexor taking over",
      "Holding the breath",
    ],
    regression: "Lift only the heel a couple of inches, or slide the heel along the floor instead.",
    progression: "Lift both feet to a tabletop position one at a time, then progress to the dead bug.",
    precautions: [
      "Stop if it increases back or leg symptoms.",
      "Reduce range where an abdominal wall separation domes on effort.",
    ],
  },
  {
    id: "pallof-press",
    name: "Pallof Press",
    aka: ["Anti-rotation press", "Band anti-rotation hold"],
    region: "Lumbar & Core",
    category: "Strength",
    positions: ["Standing", "Half-kneeling", "Kneeling"],
    equipment: ["Resistance band"],
    difficulty: 4,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Obliques", "Transversus abdominis", "Gluteals", "Shoulder girdle"],
    indications: ["Return to sport", "Return to manual work", "Trunk anti-rotation strength deficit", "Late-stage low back rehabilitation"],
    setup: "Anchor a resistance band at roughly chest height. Stand side-on to the anchor, feet shoulder-width apart, holding the band at the chest with both hands.",
    steps: [
      "Step away from the anchor until the band is taut.",
      "Brace the trunk lightly, then press both hands straight out from the chest.",
      "Resist the band's pull toward the anchor — the trunk must not rotate at all.",
      "Hold at full extension, then bring the hands back to the chest under control.",
    ],
    dosage: { sets: "2–3", reps: "8–10 each side", hold: "3–5 s at full extension", frequency: "Every other day", loadOrTempo: "Band tension that makes the last repetitions hard to hold square" },
    cue: "“The band wants to twist you — don't let it. Press straight out and stay square to the front.”",
    patientInstructions:
      "Anchor a resistance band at chest height and stand side-on to it, holding the band with both hands at your chest. Step away until the band is tight. Press your hands straight out in front of you and hold for a few seconds, keeping your body facing forwards and not letting the band twist you. Bring your hands back in. Eight to ten repetitions on each side.",
    commonErrors: [
      "Letting the trunk rotate toward the anchor",
      "Shrugging or leaning away from the band instead of bracing against it",
      "Using so much tension that form is lost immediately",
      "Holding the breath",
    ],
    regression: "Perform in half-kneeling or tall kneeling, which removes the balance demand, and use lighter tension.",
    progression: "Add a slow overhead press path, step further from the anchor, or perform in a split stance.",
    precautions: [
      "A late-stage exercise — the trunk needs to tolerate loaded holds before this one.",
      "Stop for sharp back pain rather than reducing tension mid-repetition.",
    ],
  },
  {
    id: "suitcase-carry",
    name: "Suitcase Carry",
    aka: ["Single-arm farmer carry", "Anti-lateral-flexion carry"],
    region: "Lumbar & Core",
    category: "Endurance",
    positions: ["Standing"],
    equipment: ["Weight"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Quadratus lumborum", "Obliques", "Gluteus medius", "Grip"],
    indications: ["Return to manual work", "Lateral trunk endurance deficit", "Functional carrying capacity"],
    setup: "Stand tall holding a single weight in one hand at the side — a dumbbell, kettlebell, or a loaded bag.",
    steps: [
      "Set the shoulders level and the ribs down before taking a step.",
      "Walk a set distance at a normal pace, keeping the trunk upright and level.",
      "Do not let the weighted side pull the trunk sideways.",
      "Set the weight down under control and repeat on the other side.",
    ],
    dosage: { sets: "3–4", reps: "20–30 m each side", frequency: "2–3x/week", loadOrTempo: "A weight that can be carried the full distance with a level trunk" },
    cue: "“Walk like there's no weight in your hand — shoulders level, ribs down, no leaning.”",
    patientInstructions:
      "Hold a weight in one hand at your side. Stand tall with your shoulders level, then walk twenty to thirty metres, keeping your body upright and not leaning to either side. Put the weight down carefully and repeat with the other hand. Three or four trips each side, two or three times a week.",
    commonErrors: [
      "Leaning away from the weight, or letting the trunk collapse toward it",
      "Shrugging the loaded shoulder",
      "Choosing a weight that forces a limp or a lean",
      "Setting the weight down by bending at the back rather than hinging at the hips",
    ],
    regression: "Carry a lighter weight for a shorter distance, or hold a weight in each hand, which balances the load.",
    progression: "Increase the weight, then the distance, then add uneven ground or stairs.",
    precautions: [
      "Not appropriate while a back is highly irritable.",
      "Pick the weight up and set it down with a hip hinge, not a rounded back.",
      "Take care on turns and with balance where there is any unsteadiness.",
    ],
  },
  {
    id: "sciatic-nerve-glide",
    name: "Sciatic Nerve Glide",
    aka: ["Sciatic nerve floss", "Slump slider", "Seated nerve glide"],
    region: "Lumbar & Core",
    category: "Neurodynamic",
    positions: ["Seated"],
    equipment: ["Chair"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Sciatic nerve", "Lumbar nerve roots", "Neural interface tissue"],
    indications: ["Sciatica", "Lumbar radiculopathy", "Hamstring tightness with a neural component", "Post-discectomy mobility (once cleared)"],
    setup: "Sit on a firm chair with the thighs supported and the feet on the floor.",
    steps: [
      "As you straighten one knee and pull the toes up, tip the head backward to look up.",
      "As you bend the knee and point the toes down, drop the chin to the chest.",
      "Move rhythmically between the two — the nerve slides rather than being stretched at both ends at once.",
      "Stay short of reproducing strong leg symptoms throughout.",
    ],
    dosage: { sets: "1–2", reps: "10", frequency: "1–2x/day", loadOrTempo: "Slow and rhythmic, with no end-range hold" },
    cue: "“Knee straight, head up. Knee bent, chin down. Keep it moving — never hold at the end.”",
    patientInstructions:
      "Sit on a firm chair. As you straighten one knee and pull your toes toward you, tip your head back to look up. Then bend that knee, point your toes down, and drop your chin to your chest. Move smoothly between the two positions ten times. You may feel a light pulling down the back of your leg — you should not be provoking strong pain or tingling.",
    commonErrors: [
      "Holding the end position like a hamstring stretch, which usually flares the symptoms",
      "Moving the leg and head in the same direction rather than opposite",
      "Doing too many repetitions on the first day",
    ],
    regression: "Move the knee only, keeping the head still and the toes relaxed.",
    progression: "Add ankle dorsiflexion, then progress to a slump-position variant — one variable at a time.",
    precautions: [
      "Symptoms that increase for hours afterward mean the dose was too high — reduce the range and repetitions.",
      "Not a self-directed exercise where there is progressive leg weakness, saddle numbness, or bladder or bowel change: those need urgent assessment.",
    ],
    note: "A sliding (rather than tensioning) neurodynamic technique — the two ends of the nerve are loaded alternately.",
  },
  {
    id: "femoral-nerve-glide",
    name: "Femoral Nerve Glide",
    aka: ["Femoral nerve slider", "Anterior thigh nerve glide", "Prone knee bend slider"],
    region: "Lumbar & Core",
    category: "Neurodynamic",
    positions: ["Sidelying", "Prone", "Half-kneeling"],
    equipment: ["Towel or strap"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Femoral nerve", "Anterior thigh neural tissue"],
    indications: ["Anterior thigh pain of neural origin", "Upper lumbar nerve root irritation", "Meralgia paraesthetica", "Anterior thigh symptoms after hip or groin injury"],
    setup: "Lie on the unaffected side with the bottom leg curled up, or lie prone with a strap looped around the ankle. Half-kneeling can be used for a standing alternative.",
    steps: [
      "Bend the top knee, drawing the heel toward the buttock while keeping the hip in line with the body.",
      "As the knee bends, tuck the chin toward the chest.",
      "As the knee straightens again, lift the chin away.",
      "Move slowly and rhythmically — the two ends of the nerve are loaded alternately, never both at once.",
      "Stay within a gentle pulling sensation and stop short of reproducing the symptoms.",
    ],
    dosage: { sets: "2–3", reps: "10", frequency: "1–2x/day", loadOrTempo: "Slow and rhythmic; no sustained hold at the end of range" },
    cue: "“Chin down as the heel comes up, chin up as it goes back down — keep it gentle and moving.”",
    patientInstructions:
      "Lie on your good side with your bottom leg curled up. Bend your top knee to bring your heel toward your bottom, tucking your chin toward your chest at the same time. As you straighten the knee again, lift your chin. Repeat ten times, slowly and smoothly, two or three times a day. You should feel a gentle pull down the front of your thigh — if it reproduces your usual pain, do less range, not more.",
    commonErrors: [
      "Letting the hip drift forward into extension, which turns a glide into a stretch",
      "Holding at the end of range instead of moving continuously",
      "Arching the low back to gain more range",
      "Pushing into the symptoms rather than staying just short of them",
    ],
    regression: "Reduce the knee bend, keep the head still, or perform it in half-kneeling with less range.",
    progression: "Increase the range gradually, or add gentle hip extension once the glide is comfortable.",
    precautions: [
      "A glide, not a stretch: aggressive end-range holds tend to worsen an irritable nerve rather than settle it.",
      "Stop if it reproduces or increases the usual symptoms, or if numbness or pins and needles spread further down the leg.",
      "Not appropriate as self-treatment where there is progressive weakness, saddle numbness or bladder or bowel change — those need urgent review.",
      "Reduce range in the acute stage; irritable nerves respond badly to being pushed.",
    ],
    note: "A sliding (rather than tensioning) neurodynamic technique — the two ends of the nerve are loaded alternately.",
  },
  {
    id: "quadruped-rock-back",
    name: "Quadruped Rock Back",
    aka: ["Rock backs", "Four-point rocking"],
    region: "Lumbar & Core",
    category: "Motor Control",
    positions: ["Quadruped"],
    equipment: ["None"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Hip joint", "Lumbar spine", "Deep abdominal wall"],
    indications: ["Hip and lumbar dissociation deficit", "Femoroacetabular impingement", "Low back pain with poor hip mobility"],
    setup: "Start on hands and knees with the spine in neutral. Set a light abdominal contraction.",
    steps: [
      "Rock the hips back toward the heels while keeping the low back exactly where it started.",
      "Stop at the point where the low back begins to round — that point is the end of usable hip range.",
      "Return forward to the start under control.",
      "Over sessions, the rocking distance should increase before the back gives way.",
    ],
    dosage: { sets: "2", reps: "10", frequency: "Once daily", loadOrTempo: "Slow, stopping at the point of spinal movement" },
    cue: "“Rock back only as far as your back can stay still — the moment it rounds, come forward again.”",
    patientInstructions:
      "On your hands and knees, gently tighten your tummy and keep your back still. Rock your hips backwards toward your heels, stopping as soon as your lower back starts to round. Come forward again. Ten repetitions.",
    commonErrors: [
      "Rocking all the way back into a child's pose, which defeats the point",
      "Letting the low back round early without noticing",
      "Holding the breath",
    ],
    regression: "Reduce the distance and use a mirror or a hand on the low back for feedback.",
    progression: "Increase the distance as hip range allows, or add a bird dog from the same starting position.",
    precautions: [
      "Needs comfortable weight-bearing through the wrists and knees.",
      "Respect hip precautions after hip surgery.",
    ],
  },
];
