import type { MovementExercise } from "@/lib/movement-lab/types";

/** Balance, gait and vestibular work. Graded deliberately as a ladder — Romberg through
 *  semi-tandem, tandem and single-leg, then the same positions on a compliant surface, then
 *  moving and dual-task versions — so a falls-prevention program can be built by picking the
 *  rung that is currently challenging rather than guessing. Every entry assumes a stable
 *  support within reach. */
export const NEURO_BALANCE_EXERCISES: MovementExercise[] = [
  {
    id: "romberg-stance",
    name: "Feet-Together Stance",
    aka: ["Romberg stance", "Narrow stance balance"],
    region: "Neuro & Balance",
    category: "Balance",
    positions: ["Standing"],
    equipment: ["Table or counter"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Balance system", "Ankle strategy", "Postural control"],
    indications: ["Falls risk", "Post-operative balance retraining", "Deconditioning", "Early vestibular rehabilitation"],
    setup: "Stand next to a kitchen counter or in a doorway, with something solid to grab within reach at all times.",
    steps: [
      "Stand with the feet together, touching side by side.",
      "Hold the position, looking straight ahead.",
      "Use fingertips on the counter only as much as needed — the goal is to need less over time.",
      "Progress by taking the fingers off, then closing the eyes only if it is safe and someone is nearby.",
    ],
    dosage: { sets: "3–5", reps: "1", hold: "30 s", frequency: "Daily" },
    cue: "“Feet touching, eyes forward, fingertips on the counter — the aim is to need them less each week, not to prove you can do it today.”",
    patientInstructions:
      "Stand next to a kitchen counter with your feet together, touching. Hold for thirty seconds, using your fingertips on the counter for as much support as you need. Repeat three to five times, every day. Always have something solid to grab within reach.",
    commonErrors: [
      "Practising away from a support surface",
      "Gripping the counter tightly rather than using fingertips",
      "Closing the eyes before the position is steady with them open",
      "Looking down at the feet instead of straight ahead",
    ],
    regression: "Stand with the feet slightly apart, with both hands on the counter.",
    progression: "Fingertips only, then hands off, then eyes closed, then Semi-Tandem Stance.",
    precautions: [
      "Always practise where there is a solid support within reach — never in open space.",
      "Have someone nearby when first attempting an eyes-closed version.",
      "Stop for dizziness and report it.",
    ],
  },
  {
    id: "semi-tandem-stance",
    name: "Semi-Tandem Stance",
    aka: ["Staggered stance balance"],
    region: "Neuro & Balance",
    category: "Balance",
    positions: ["Standing"],
    equipment: ["Table or counter"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Balance system", "Hip and ankle strategies", "Postural control"],
    indications: ["Falls risk", "Balance retraining", "Progression from feet-together stance"],
    setup: "Stand beside a counter with something solid within reach.",
    steps: [
      "Place one foot half a step ahead of the other, with the heel of the front foot alongside the big toe of the back foot.",
      "Hold, looking straight ahead.",
      "Use as little hand support as is safe.",
      "Swap which foot is in front halfway through the practice.",
    ],
    dosage: { sets: "3–5", reps: "1 each foot forward", hold: "30 s", frequency: "Daily" },
    cue: "“Front heel beside your back big toe — eyes forward, and only as much hand support as you actually need.”",
    patientInstructions:
      "Stand beside a counter. Put one foot half a step in front of the other, so the heel of the front foot is next to the big toe of the back foot. Hold for thirty seconds. Swap feet and repeat. Three to five times each way, daily.",
    commonErrors: [
      "Standing in full tandem before semi-tandem is steady",
      "Practising away from support",
      "Looking down at the feet",
      "Only ever practising with the same foot in front",
    ],
    regression: "Feet-Together Stance.",
    progression: "Tandem Stance, or the same position with the eyes closed.",
    precautions: [
      "Always have a solid support within reach.",
      "Progress one variable at a time — narrower base, or less hand support, or eyes closed, never two at once.",
    ],
  },
  {
    id: "tandem-stance",
    name: "Tandem Stance",
    aka: ["Heel-to-toe stance", "Sharpened Romberg"],
    region: "Neuro & Balance",
    category: "Balance",
    positions: ["Standing"],
    equipment: ["Table or counter"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Balance system", "Hip strategy", "Postural control"],
    indications: ["Falls risk", "Balance retraining", "Vestibular rehabilitation", "Return to uneven walking surfaces"],
    setup: "Stand beside a counter, with a wall on the other side if possible.",
    steps: [
      "Place one foot directly in front of the other so the heel touches the toes.",
      "Hold, looking straight ahead.",
      "Use as little hand support as is safe.",
      "Swap which foot is in front.",
    ],
    dosage: { sets: "3–5", reps: "1 each foot forward", hold: "30 s", frequency: "Daily" },
    cue: "“Heel right against the toes of the other foot, like standing on a line — eyes up, not down.”",
    patientInstructions:
      "Stand beside a counter and put one foot directly in front of the other so your heel touches your toes. Hold for thirty seconds, then swap feet. Three to five times each way, daily. Keep a hand near the counter.",
    commonErrors: [
      "Standing in a wide stance and calling it tandem",
      "Practising without a support within reach",
      "Holding the breath",
      "Progressing to eyes closed before the eyes-open version is steady",
    ],
    regression: "Semi-Tandem Stance.",
    progression: "Eyes closed, then on a compliant surface, then with head turns.",
    precautions: [
      "This is a genuinely challenging position — always practise with support within reach, and ideally with someone nearby.",
      "Stop for dizziness and report it.",
    ],
  },
  {
    id: "single-leg-stance",
    name: "Single-Leg Stance",
    aka: ["One-leg balance", "Stork stand"],
    region: "Neuro & Balance",
    category: "Balance",
    positions: ["Standing"],
    equipment: ["Table or counter"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Balance system", "Gluteus medius", "Ankle stabilisers"],
    indications: ["Falls risk", "Chronic ankle instability", "Post-operative lower limb rehabilitation", "Return to running", "Hip abductor control"],
    setup: "Stand beside a counter with something solid within reach.",
    steps: [
      "Shift the weight onto one leg and lift the other foot just off the floor.",
      "Keep the hips level and the standing knee soft, not locked.",
      "Hold, looking straight ahead.",
      "Lower the foot and swap sides.",
    ],
    dosage: { sets: "3–5", reps: "1 each side", hold: "10–30 s", frequency: "Daily" },
    cue: "“Lift the foot just off the floor and keep your hips level — you're not trying to lift the knee high, you're trying to stay still.”",
    patientInstructions:
      "Stand beside a counter. Shift your weight onto one leg and lift the other foot just off the floor. Keep your hips level and hold for ten to thirty seconds. Swap legs. Three to five times each side, every day.",
    commonErrors: [
      "Letting the pelvis drop on the lifted side",
      "Locking the standing knee",
      "Holding the counter in a tight grip",
      "Looking down at the floor",
    ],
    regression: "Keep the toe of the lifted foot lightly touching the floor, or use both hands on the counter.",
    progression: "Fingertips only, then hands off, then eyes closed, then on a compliant surface, then add head turns or a reach.",
    precautions: [
      "Always have a solid support within reach.",
      "Follow post-operative weight-bearing restrictions.",
      "Stop for dizziness.",
    ],
  },
  {
    id: "foam-surface-stance",
    name: "Balance on a Compliant Surface",
    aka: ["Foam pad balance", "Pillow stance", "Cushion balance"],
    region: "Neuro & Balance",
    category: "Balance",
    positions: ["Standing"],
    equipment: ["Table or counter"],
    difficulty: 4,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Balance system", "Ankle strategy", "Proprioception"],
    indications: ["Chronic ankle instability", "Falls risk", "Vestibular rehabilitation", "Return to uneven terrain"],
    setup: "Place a firm cushion, folded towel, or balance pad beside a counter so a support is within reach.",
    steps: [
      "Step onto the cushion with both feet, using the counter for support.",
      "Find a steady stance and let go of the counter when it is safe.",
      "Hold, looking straight ahead.",
      "Progress the base of support — feet apart, then together, then semi-tandem, then single-leg.",
    ],
    dosage: { sets: "3–5", reps: "1", hold: "30 s", frequency: "Daily" },
    cue: "“The surface is meant to move — let your ankles work rather than locking up against it.”",
    patientInstructions:
      "Put a firm cushion or folded towel on the floor beside a counter. Step onto it with both feet, holding the counter. Once you feel steady, let go and hold for thirty seconds. Three to five times a day. Use a narrower foot position as it gets easier.",
    commonErrors: [
      "Using a surface so soft it is unsafe rather than challenging",
      "Practising away from a support",
      "Locking the knees and ankles rigid instead of allowing small corrections",
    ],
    regression: "Stand on the cushion with the feet wide and both hands on the counter.",
    progression: "Narrow the base, then close the eyes, then add head turns or a reach.",
    precautions: [
      "Use a stable cushion on a non-slip floor, and always beside a solid support.",
      "Not appropriate for someone who is not yet steady on firm ground.",
      "Have someone nearby the first few sessions.",
    ],
  },
  {
    id: "standing-weight-shift",
    name: "Standing Weight Shifts",
    aka: ["Lateral and anterior-posterior weight shifting"],
    region: "Neuro & Balance",
    category: "Motor Control",
    positions: ["Standing"],
    equipment: ["Table or counter"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Balance system", "Hip and ankle strategies", "Weight-bearing tolerance"],
    indications: ["Post-operative weight-bearing progression", "Falls risk", "Gait asymmetry", "Neurological rehabilitation"],
    setup: "Stand with the feet hip-width apart beside a counter.",
    steps: [
      "Shift the weight slowly onto one foot, then the other, without lifting either foot.",
      "Then shift the weight forward toward the toes and back toward the heels.",
      "Keep the movement coming from the ankles and hips, with the body staying tall.",
      "Move to the edge of comfortable control, not beyond it.",
    ],
    dosage: { sets: "2–3", reps: "10 each direction", frequency: "Daily", loadOrTempo: "Slow and controlled" },
    cue: "“Move your weight over one foot and then the other without lifting either — sway from your ankles, stay tall.”",
    patientInstructions:
      "Stand beside a counter with your feet hip-width apart. Slowly shift your weight onto one foot, then the other, without lifting either foot. Then shift your weight forward onto your toes and back onto your heels. Ten in each direction.",
    commonErrors: [
      "Bending at the waist rather than shifting the whole body",
      "Moving so fast that control is lost",
      "Never shifting far enough to actually challenge balance",
    ],
    regression: "Smaller shifts with both hands on the counter.",
    progression: "Larger shifts, hands off, then the Single-Leg Stance.",
    precautions: [
      "Follow post-operative weight-bearing restrictions.",
      "Always have a support within reach.",
    ],
  },
  {
    id: "tandem-walk",
    name: "Tandem Walking",
    aka: ["Heel-to-toe walking", "Line walking"],
    region: "Neuro & Balance",
    category: "Balance",
    positions: ["Standing"],
    equipment: ["Wall"],
    difficulty: 4,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Dynamic balance", "Gait control", "Hip strategy"],
    indications: ["Falls risk", "Vestibular rehabilitation", "Gait instability", "Return to uneven walking"],
    setup: "Walk along a hallway with a wall within arm's reach on one side.",
    steps: [
      "Walk forward placing the heel of each step directly against the toes of the other foot.",
      "Look ahead rather than down at the feet.",
      "Use a fingertip on the wall for support as needed.",
      "Turn around carefully at the end of the run.",
    ],
    dosage: { sets: "3–5", reps: "10 steps", frequency: "Daily" },
    cue: "“Heel against toe every step, like walking a tightrope — and look where you're going, not at your feet.”",
    patientInstructions:
      "Walk down a hallway placing the heel of each step directly in front of the toes of your other foot, like walking on a line. Keep a fingertip on the wall for safety. Look ahead, not down. Ten steps, three to five times, daily.",
    commonErrors: [
      "Widening the steps so the feet are no longer in line",
      "Looking down at the feet",
      "Practising in open space away from a wall",
      "Turning around quickly at the end",
    ],
    regression: "Semi-tandem walking with a slightly wider base, or tandem *standing* rather than walking.",
    progression: "Hands off the wall, then with head turns, then backwards.",
    precautions: [
      "Practise in a hallway with a wall within reach — never in open space.",
      "Have someone nearby if unsteady.",
      "Stop for dizziness.",
    ],
    note: "One of the walking tasks in the widely-published Otago home exercise programme for falls prevention.",
  },
  {
    id: "backward-walk",
    name: "Backward Walking",
    region: "Neuro & Balance",
    category: "Balance",
    positions: ["Standing"],
    equipment: ["Wall"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Dynamic balance", "Hip extensors", "Gait control"],
    indications: ["Falls risk", "Gait retraining", "Balance progression"],
    setup: "Stand at one end of a clear hallway with a wall within arm's reach and nothing on the floor behind.",
    steps: [
      "Check the path behind is completely clear before starting.",
      "Walk backward with slow, deliberate steps, reaching back with the toes first.",
      "Keep the trunk upright rather than leaning forward.",
      "Keep a fingertip on the wall for reference.",
    ],
    dosage: { sets: "3–4", reps: "10 steps", frequency: "Daily" },
    cue: "“Reach back with your toes and stand tall — small steps, and check the floor behind you first.”",
    patientInstructions:
      "Check the floor behind you is completely clear. Walk backwards slowly down a hallway, keeping a fingertip on the wall. Ten steps, three or four times, every day.",
    commonErrors: [
      "Not checking the path is clear first",
      "Taking large, quick steps",
      "Leaning the trunk forward",
      "Practising alone when unsteady",
    ],
    regression: "Take fewer steps, keep the whole hand on the wall, or do it holding a counter.",
    progression: "More steps, hands off, or add a narrower step width.",
    precautions: [
      "A clear, uncluttered path is essential — this is one of the higher-risk balance drills.",
      "Have someone nearby if unsteady.",
    ],
    note: "One of the walking tasks in the Otago home exercise programme.",
  },
  {
    id: "sidestep-walk",
    name: "Side-Stepping",
    aka: ["Lateral walking", "Sidestepping along a counter"],
    region: "Neuro & Balance",
    category: "Balance",
    positions: ["Standing"],
    equipment: ["Table or counter"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Hip abductors", "Dynamic balance", "Lateral weight transfer"],
    indications: ["Falls risk", "Hip abductor weakness", "Gait retraining", "Post-operative walking progression"],
    setup: "Stand facing a kitchen counter with both hands resting on it.",
    steps: [
      "Step sideways with one foot, then bring the other foot to meet it.",
      "Keep the toes pointing forward and the trunk upright.",
      "Travel the length of the counter, then return the other way.",
      "Reduce the hand support as the movement becomes steady.",
    ],
    dosage: { sets: "3–4", reps: "10 steps each direction", frequency: "Daily" },
    cue: "“Toes forward, stay tall, and step sideways along the counter — don't let your body sway ahead of your feet.”",
    patientInstructions:
      "Stand facing a kitchen counter with your hands on it. Step sideways along the counter, bringing your feet together after each step, then come back the other way. Ten steps each direction, three or four times a day.",
    commonErrors: [
      "Turning the feet outward and walking diagonally",
      "Leaning heavily on the counter",
      "Crossing the feet over instead of stepping and closing",
    ],
    regression: "Fewer steps with both hands firmly on the counter.",
    progression: "Fingertips only, then hands off, then add a resistance band around the thighs.",
    precautions: [
      "Follow post-operative weight-bearing and hip precautions.",
      "Keep the floor clear of rugs and obstacles.",
    ],
    note: "One of the walking tasks in the Otago home exercise programme.",
  },
  {
    id: "heel-toe-walks",
    name: "Heel Walks and Toe Walks",
    region: "Neuro & Balance",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Wall"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Tibialis anterior", "Calf muscles", "Dynamic balance"],
    indications: ["Ankle weakness", "Falls risk", "Foot drop", "Return to walking on varied terrain"],
    setup: "Stand at one end of a hallway with a wall within reach.",
    steps: [
      "Walk forward on the heels with the toes lifted clear of the floor.",
      "Turn around, then walk back up on the toes with the heels off the floor.",
      "Keep the trunk upright and the steps small.",
      "Use fingertips on the wall for support.",
    ],
    dosage: { sets: "2–3", reps: "10 steps of each", frequency: "Daily" },
    cue: "“Toes up for the heel walk, heels up for the toe walk — small steps and stay tall.”",
    patientInstructions:
      "Walk ten steps forward on your heels with your toes lifted off the floor. Then walk ten steps on your toes with your heels lifted. Keep a fingertip on the wall. Repeat two or three times.",
    commonErrors: [
      "Letting the toes or heels touch down each step",
      "Taking large steps",
      "Leaning forward or backward to compensate",
      "Practising away from a wall",
    ],
    regression: "Do heel raises and toe lifts standing still, holding a counter.",
    progression: "More steps, hands off, or add a light backpack.",
    precautions: [
      "Follow post-operative loading restrictions at the ankle.",
      "Practise beside a wall, and have someone nearby if unsteady.",
    ],
  },
  {
    id: "obstacle-step-over",
    name: "Stepping Over an Obstacle",
    aka: ["Obstacle clearance practice", "Step over a line"],
    region: "Neuro & Balance",
    category: "Motor Control",
    positions: ["Standing"],
    equipment: ["Table or counter"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Dynamic balance", "Hip flexors", "Single-leg stance control"],
    indications: ["Falls risk", "Tripping", "Gait retraining", "Return to outdoor walking"],
    setup: "Place a low, soft obstacle — a rolled towel or a foam noodle, never anything rigid — on the floor beside a counter.",
    steps: [
      "Step forward over the obstacle with one foot, then bring the other foot over.",
      "Lift the knee enough to clear it well rather than shuffling across.",
      "Pause in single-leg stance briefly as each foot passes over.",
      "Turn around and repeat, leading with the other foot.",
    ],
    dosage: { sets: "2–3", reps: "8–10 crossings each leading foot", frequency: "Daily" },
    cue: "“Lift the knee and clear it properly — a shuffle over is exactly the pattern that catches a toe on a kerb.”",
    patientInstructions:
      "Put a rolled towel on the floor beside a counter. Step over it with one foot and then the other, lifting your knees enough to clear it well. Turn around and repeat, leading with your other foot. Eight to ten crossings, holding the counter as needed.",
    commonErrors: [
      "Using a rigid obstacle that will not give way if caught",
      "Shuffling across rather than lifting the knee",
      "Looking down the whole time rather than glancing and then looking ahead",
      "Practising without a support within reach",
    ],
    regression: "Step over a line on the floor with no obstacle at all.",
    progression: "Slightly higher soft obstacle, less hand support, or add a turn afterwards.",
    precautions: [
      "Use only a soft, low obstacle — never a box, step, or anything that will not move if kicked.",
      "Always have a support within reach and someone nearby if unsteady.",
    ],
  },
  {
    id: "four-square-step",
    name: "Four Square Stepping",
    aka: ["Multi-directional stepping practice"],
    region: "Neuro & Balance",
    category: "Motor Control",
    positions: ["Standing"],
    equipment: ["Table or counter"],
    difficulty: 4,
    phases: ["Return to Activity"],
    targets: ["Dynamic balance", "Multi-directional stepping", "Reaction and sequencing"],
    indications: ["Falls risk", "Return to community walking", "Multi-directional gait deficits"],
    setup: "Mark four squares on the floor with tape or two crossed towels, forming a plus shape. Stand in one square with a counter within reach.",
    steps: [
      "Step forward into the next square, then sideways, then backward, then sideways, returning to the start.",
      "Then reverse the sequence.",
      "Keep facing the same direction throughout — the body does not turn.",
      "Move at a comfortable pace and stay steady in each square before the next step.",
    ],
    dosage: { sets: "2–4", reps: "1 full circuit each direction", frequency: "Daily" },
    cue: "“Keep facing forward the whole time and step around the squares — forward, sideways, back, sideways.”",
    patientInstructions:
      "Lay two towels on the floor in a cross shape to make four squares. Stand in one square, and step into each of the others in turn — forward, sideways, backwards, sideways — without turning your body. Then go around the other way. Two to four circuits, with a counter within reach.",
    commonErrors: [
      "Turning the body instead of stepping in each direction",
      "Rushing between squares before balance is settled",
      "Using tape or objects that can slip underfoot",
      "Practising away from a support",
    ],
    regression: "Step forward and back only, or use two squares instead of four.",
    progression: "Increase the pace, add a second circuit without pausing, or add a dual task.",
    precautions: [
      "Use non-slip markers on a non-slip floor.",
      "A high-level drill — only appropriate once single-leg and tandem work is steady.",
      "Have someone nearby.",
    ],
  },
  {
    id: "gaze-stabilization-x1",
    name: "Gaze Stabilisation (VOR ×1)",
    aka: ["VOR x1", "Vestibulo-ocular reflex exercise", "Eyes on target head turns"],
    region: "Neuro & Balance",
    category: "Motor Control",
    positions: ["Seated", "Standing"],
    equipment: ["Wall", "Chair"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Vestibulo-ocular reflex", "Gaze stability"],
    indications: ["Vestibular hypofunction", "Dizziness with head movement", "Post-concussion visual and vestibular symptoms", "Blurred vision when moving"],
    setup: "Sit facing a wall about arm's length away, with a small target — a letter or a coin — fixed on the wall at eye level.",
    steps: [
      "Keep the eyes fixed on the target the whole time.",
      "Turn the head slowly side to side while the target stays perfectly clear.",
      "If the target blurs, slow down — speed is limited by clarity, not by comfort.",
      "Do a separate set moving the head up and down.",
    ],
    dosage: { sets: "1", reps: "1 per direction", hold: "60 s of continuous movement", frequency: "3–5x/day", loadOrTempo: "As fast as the target stays clear, no faster" },
    cue: "“Your eyes stay locked on the letter — turn your head only as fast as you can keep it perfectly clear.”",
    patientInstructions:
      "Stick a small letter on a wall at eye level and sit an arm's length away. Keeping your eyes fixed on the letter, turn your head slowly side to side for about a minute, going only as fast as you can keep the letter clear. Rest, then repeat moving your head up and down. Do this three to five times a day. Mild dizziness during this is expected and should settle within a few minutes.",
    commonErrors: [
      "Moving the eyes with the head instead of keeping them fixed",
      "Moving too fast so the target blurs",
      "Stopping at the first hint of dizziness — some is expected and is part of how this works",
      "Continuing when dizziness is severe or lasts well beyond the session",
    ],
    regression: "Shorter duration (20–30 seconds), slower head movement, seated with the back supported.",
    progression: "Longer duration, faster head movement, then standing, then on a compliant surface, then with a busy background.",
    precautions: [
      "This exercise is expected to provoke mild symptoms that settle within a few minutes — that is how it works. Symptoms that are severe, or last well beyond the session, mean the dose is too high.",
      "Sit down for the first sessions in case of unsteadiness.",
      "Should be prescribed after a proper vestibular assessment — the right exercise depends on the diagnosis, and positional vertigo needs a different treatment entirely.",
    ],
  },
  {
    id: "head-turns-walking",
    name: "Walking with Head Turns",
    aka: ["Gait with head movement", "Dynamic gaze during gait"],
    region: "Neuro & Balance",
    category: "Balance",
    positions: ["Standing"],
    equipment: ["Wall"],
    difficulty: 4,
    phases: ["Return to Activity"],
    targets: ["Dynamic balance", "Vestibular system", "Gait stability"],
    indications: ["Vestibular rehabilitation", "Falls risk", "Difficulty walking in busy environments", "Return to community walking"],
    setup: "Walk along a clear hallway with a wall within arm's reach.",
    steps: [
      "Walk at a comfortable pace.",
      "Turn the head slowly left and right while continuing to walk in a straight line.",
      "Then repeat, nodding the head up and down while walking.",
      "Trail a hand near the wall throughout.",
    ],
    dosage: { sets: "2–3", reps: "10–20 m each direction of head movement", frequency: "Once daily" },
    cue: "“Keep walking in a straight line while your head turns — the line is the test, not the head movement.”",
    patientInstructions:
      "Walk down a hallway at a comfortable pace, keeping a hand near the wall. As you walk, slowly turn your head left and right, then walk back nodding your head up and down. Try to keep walking in a straight line. Ten to twenty metres each way, once a day.",
    commonErrors: [
      "Veering off line without noticing",
      "Turning the head fast enough to provoke strong symptoms",
      "Practising in open space or in a busy area before it is steady in a hallway",
    ],
    regression: "Stand still and turn the head, or walk without head turns first.",
    progression: "Faster head turns, a narrower walking line, or a busier visual environment.",
    precautions: [
      "A high-level vestibular and balance task — build up from the static versions first.",
      "Practise beside a wall with someone nearby.",
      "Stop for strong dizziness or unsteadiness.",
    ],
  },
  {
    id: "reach-outside-base",
    name: "Reaching Outside the Base of Support",
    aka: ["Functional reach practice", "Multi-directional reaching"],
    region: "Neuro & Balance",
    category: "Balance",
    positions: ["Standing"],
    equipment: ["Table or counter"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Dynamic balance", "Hip strategy", "Postural control"],
    indications: ["Falls risk", "Difficulty reaching in the kitchen or bathroom", "Balance confidence", "Return to daily activities"],
    setup: "Stand with the feet hip-width apart beside a counter, with a target object placed just beyond comfortable reach.",
    steps: [
      "Reach forward for the target without moving the feet, letting the hips travel backward as a counterbalance.",
      "Return to upright under control.",
      "Repeat reaching out to the side, and then diagonally down toward the floor.",
      "Keep the feet planted throughout, and stop before a step is needed.",
    ],
    dosage: { sets: "2–3", reps: "8–10 in each direction", frequency: "Daily" },
    cue: "“Reach as far as you can without moving your feet — and come back before you need to take a step.”",
    patientInstructions:
      "Stand beside a counter with your feet hip-width apart. Reach forwards for an object just beyond easy reach, without moving your feet, then come back upright. Repeat reaching out to the side and down toward the floor. Eight to ten in each direction.",
    commonErrors: [
      "Taking a step, which means the reach went too far",
      "Bending only at the waist rather than shifting the whole body",
      "Reaching so far that balance is genuinely lost",
    ],
    regression: "Reach a shorter distance, keeping one hand on the counter.",
    progression: "Reach further, add a light object to carry, or reach on a compliant surface.",
    precautions: [
      "Always have a support within reach, and stop short of the point where a step is needed.",
      "Reaching down toward the floor is the highest-risk direction — build up to it last.",
      "Have someone nearby if unsteady.",
    ],
  },
  {
    id: "dual-task-balance",
    name: "Dual-Task Balance",
    aka: ["Balance with a cognitive task", "Talking while balancing"],
    region: "Neuro & Balance",
    category: "Balance",
    positions: ["Standing"],
    equipment: ["Table or counter"],
    difficulty: 4,
    phases: ["Return to Activity"],
    targets: ["Dynamic balance", "Attention and balance integration"],
    indications: ["Falls risk", "Post-concussion rehabilitation", "Return to community mobility", "Balance that fails when distracted"],
    setup: "Choose a balance position that is currently challenging but safe — semi-tandem, tandem, or single-leg — beside a counter.",
    steps: [
      "Hold the balance position.",
      "Add a mental task at the same time: count backward from a hundred by threes, name animals beginning with a letter, or recite the months backward.",
      "Keep both going for the full hold.",
      "Stop the moment balance genuinely degrades — losing the balance is the signal to make it easier.",
    ],
    dosage: { sets: "3–4", reps: "1", hold: "30 s", frequency: "Daily" },
    cue: "“Keep the counting going the whole time — going quiet is the giveaway that all your attention has gone to your feet.”",
    patientInstructions:
      "Stand in a balance position that is a little challenging for you, beside a counter. While you hold it, count backwards from a hundred in threes, or name as many animals as you can. Keep both going for thirty seconds. Three or four times a day.",
    commonErrors: [
      "Going quiet and abandoning the mental task, which removes the whole point",
      "Choosing a balance position that is too hard to hold safely with a distraction",
      "Practising without a support within reach",
    ],
    regression: "Use an easier balance position, or a simpler mental task such as counting up in ones.",
    progression: "Harder balance position, harder mental task, or add a physical second task like passing a ball hand to hand.",
    precautions: [
      "The distraction is exactly what makes this risky — always practise with a support within reach and someone nearby.",
      "Step down a level rather than persisting if balance is repeatedly lost.",
    ],
  },
  {
    id: "y-balance-reach",
    name: "Single-Leg Reach in Three Directions",
    aka: ["Y-balance reach", "Star excursion reach", "Multidirectional reach"],
    region: "Neuro & Balance",
    category: "Balance",
    positions: ["Standing"],
    equipment: ["None"],
    difficulty: 4,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Gluteus medius", "Quadriceps", "Ankle stabilisers", "Dynamic single-leg control"],
    indications: ["Chronic ankle instability", "Return to sport after knee or ankle injury", "Dynamic balance deficit", "Limb symmetry assessment"],
    setup: "Stand on one leg in the centre of a clear space, hands on the hips or free for balance. Mark three lines if available: one straight ahead and two behind at an angle.",
    steps: [
      "Balance on one leg with a soft bend in that knee.",
      "Reach the free foot as far forward as possible, touch the floor lightly, and return to standing without putting weight on it.",
      "Repeat the reach diagonally back and to one side, then diagonally back and to the other.",
      "Keep the heel of the standing foot down throughout — a lifting heel means the reach went too far.",
      "Complete all three directions, then swap legs and compare.",
    ],
    dosage: { sets: "2–3", reps: "3–5 reaches in each direction, each side", frequency: "3x/week", loadOrTempo: "Slow and controlled; touch lightly rather than transferring weight" },
    cue: "“Reach as far as you can and come back without putting weight on that foot — and keep your standing heel down.”",
    patientInstructions:
      "Stand on one leg with clear space around you. Reach your other foot as far forward as you can, touch the floor lightly with your toes, and bring it back without leaning on it. Then reach diagonally back to one side, then diagonally back to the other. Three to five reaches in each direction, then swap legs. Keep your standing heel on the floor — if it lifts, you are reaching too far.",
    commonErrors: [
      "Putting weight on the reaching foot instead of touching lightly",
      "The standing heel lifting as the reach gets longer",
      "The standing knee falling inward",
      "Bending at the waist rather than at the hip and knee of the standing leg",
      "Reaching further on the good side and calling the sides equal",
    ],
    regression: "Reach in one direction only, shorten the reach, or rest a fingertip on a counter.",
    progression: "Reach further, add all three directions in sequence without resetting, or stand on a compliant surface.",
    precautions: [
      "Needs steady Single-Leg Stance first — this is that exercise made dynamic.",
      "Have a support within reach: the backward diagonal reaches are where people lose balance.",
      "Not appropriate where a fall risk cannot be safely managed without hands-on supervision.",
      "Any left-to-right comparison is a rough guide for the clinician, not a discharge decision on its own.",
    ],
  },
  {
    id: "perturbation-training",
    name: "Perturbation Training",
    aka: ["Balance perturbations", "Nudge training", "Reactive balance training"],
    region: "Neuro & Balance",
    category: "Balance",
    positions: ["Standing"],
    equipment: ["None"],
    difficulty: 4,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Reactive postural control", "Hip and ankle strategies", "Stepping responses"],
    indications: ["Falls prevention", "Reactive balance deficit", "Return to sport or work on uneven ground", "Balance retraining after stroke or neurological injury"],
    setup: "Stand in a stable position with a clear space all round and a helper standing close by. A wall or counter should be within reach behind or beside.",
    steps: [
      "Start in a comfortable stance — feet apart at first, narrowing as control improves.",
      "The helper applies a light, unpredictable nudge at the shoulder, hip or pelvis.",
      "Recover balance without stepping if the nudge is small, using the ankles and hips.",
      "Allow a step when the nudge is larger — a fast, well-placed step is a correct response, not a failure.",
      "Vary the direction and timing so the response cannot be anticipated.",
    ],
    dosage: { sets: "2–3", reps: "8–10 nudges", frequency: "2–3x/week", loadOrTempo: "Unpredictable direction and timing; force light enough that recovery is possible" },
    cue: "“I'm going to nudge you and I won't say when — just get your balance back however you need to.”",
    patientInstructions:
      "This one needs a helper. Stand with clear space around you and something solid within reach. Your helper gives you small, unexpected nudges at the shoulder or hip, and you recover your balance — either by swaying back to centre or by taking a quick step. Eight to ten nudges, two or three sets. Taking a step is a correct answer, not a mistake: quick, well-placed steps are what stop falls.",
    commonErrors: [
      "The helper warning before every nudge, which removes the reactive element entirely",
      "Nudging hard enough that recovery is impossible",
      "Treating a step as failure — the stepping response is the point",
      "Always pushing from the same direction",
      "Working without a clear space or a spotter",
    ],
    regression: "A wider stance, lighter and slower nudges, or self-generated perturbations such as reaching and turning.",
    progression: "Narrow the stance, increase the force, add a compliant surface, or add a distraction task.",
    precautions: [
      "Requires a competent helper and a clear space — this exercise deliberately provokes loss of balance, so it is not a solo home exercise.",
      "Not appropriate for someone at high falls risk without hands-on supervision, or where a fall would be unsafe because of fracture risk or anticoagulation.",
      "Keep the force well within what can be recovered from; the aim is to challenge the response, not to knock someone over.",
      "Stop for dizziness, and screen for it beforehand where a vestibular cause is possible.",
    ],
  },
  {
    id: "fast-feet-drill",
    name: "Fast Feet Drill",
    aka: ["Agility ladder drill", "Quick feet", "Foot speed drill"],
    region: "Neuro & Balance",
    category: "Motor Control",
    positions: ["Standing"],
    equipment: ["None"],
    difficulty: 3,
    phases: ["Return to Activity"],
    targets: ["Calf complex", "Hip flexors", "Foot and ankle coordination", "Foot speed"],
    indications: ["Return to running and field sport", "Coordination and foot speed deficit", "Late-stage ankle rehabilitation", "Reintroducing quick footwork before agility work"],
    setup: "Use an agility ladder, or mark out a line of squares on the floor with tape or markers, on a firm non-slip surface. Wear trainers.",
    steps: [
      "Start with one foot in each square, running through the length with short, quick steps.",
      "Stay tall on the balls of the feet with the arms driving naturally.",
      "Keep the ground contacts light and quick rather than reaching for distance.",
      "Progress the pattern once the rhythm is clean: two feet in each square, then lateral in-and-out, then a forward-and-back pattern.",
      "Walk back to the start between runs rather than turning straight round.",
    ],
    dosage: { sets: "4–6", reps: "1 pass of the ladder per set", frequency: "2–3x/week", loadOrTempo: "Speed only once the pattern is accurate; walk back between passes" },
    cue: "“Quick and light on the balls of your feet — accuracy first, speed after.”",
    patientInstructions:
      "Lay out an agility ladder, or mark squares on the floor with tape. Run through with short quick steps, one foot in each square, staying up on the balls of your feet. Walk back and repeat, four to six times. Get the pattern right before you try to go fast, and change to a harder pattern only once the easy one is smooth.",
    commonErrors: [
      "Going fast before the pattern is accurate",
      "Landing flat-footed or heavy",
      "Looking down at the feet the whole way rather than glancing up",
      "Turning straight round at the end instead of walking back and resetting",
      "Using a ladder that slides on the surface",
    ],
    regression: "Walk the pattern, or use fewer squares and a simpler stepping sequence.",
    progression: "Increase speed, use more complex lateral patterns, then add a ball or a call to react to.",
    precautions: [
      "A stepping option before true agility work: it should follow, not replace, the strength and hopping stages.",
      "Not appropriate with pain on impact or an unstable ankle.",
      "Use a non-slip surface and secure the ladder — catching a foot on a rucked ladder is the usual mishap.",
      "Stop for fatigue: the pattern degrades before the legs feel tired.",
    ],
  },
];
