import type { MovementExercise } from "@/lib/movement-lab/types";

/** Shoulder complex, including the scapula. Ordered roughly the way a shoulder program
 *  actually progresses — passive and assisted range first, then isometrics, then open-chain
 *  cuff and scapular strength, then the stretches and the late-stage closed-chain work. */
export const SHOULDER_EXERCISES: MovementExercise[] = [
  {
    id: "pendulum",
    name: "Pendulum Swings",
    aka: ["Codman's exercise", "Pendular exercise"],
    region: "Shoulder",
    category: "Mobility",
    positions: ["Standing"],
    equipment: ["Table or counter"],
    difficulty: 1,
    phases: ["Acute / Protected"],
    targets: ["Glenohumeral joint", "Shoulder capsule"],
    indications: ["Post rotator cuff repair (per protocol)", "Adhesive capsulitis", "Acute shoulder pain", "Proximal humerus fracture (once cleared)"],
    setup: "Stand beside a table and lean forward, supporting the body weight through the uninvolved hand on the table. Let the involved arm hang straight down, completely relaxed.",
    steps: [
      "Let the arm hang heavy — the shoulder muscles do nothing.",
      "Shift weight through the legs and trunk so the arm swings as a passive pendulum.",
      "Swing forward and back, then side to side, then in small circles each way.",
      "Keep every swing small; the arm should feel loose, not driven.",
    ],
    dosage: { sets: "1–2", reps: "10–15 in each direction", frequency: "2–3x/day", loadOrTempo: "Passive only — no shoulder muscle effort" },
    cue: "“Let your arm hang like a rope and move your body, not your shoulder — the arm is just along for the ride.”",
    patientInstructions:
      "Lean forward with your good hand on a table for support and let your sore arm hang straight down, completely relaxed. Move your body gently so the arm swings by itself — forwards and back, side to side, and in small circles. Do not use your shoulder muscles to move the arm. Ten to fifteen swings in each direction, two or three times a day.",
    commonErrors: [
      "Actively swinging the arm with the shoulder muscles, which defeats the purpose entirely",
      "Making the circles too large",
      "Rounding the low back instead of supporting the trunk on the table",
    ],
    regression: "Smaller swings, fewer repetitions, and support the trunk more fully.",
    progression: "Assisted range of motion with a cane, once the protocol allows active-assisted movement.",
    precautions: [
      "Follow the surgeon's protocol exactly after a repair — pendulums are often the only shoulder movement permitted early on.",
      "Stop if it provokes sharp pain rather than the expected stiffness.",
      "Needs a stable support surface and safe trunk position — not appropriate for someone who cannot lean safely.",
    ],
    note: "The classic Codman pendular exercise — passive by definition, which is exactly why it is permitted so early.",
  },
  {
    id: "supine-cane-flexion",
    name: "Supine Shoulder Flexion with a Cane",
    aka: ["Active-assisted flexion", "Wand flexion", "Cane elevation"],
    region: "Shoulder",
    category: "Mobility",
    positions: ["Supine"],
    equipment: ["Cane or dowel"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Glenohumeral joint", "Shoulder capsule", "Scapulothoracic joint"],
    indications: ["Adhesive capsulitis", "Post-operative shoulder stiffness", "Loss of shoulder elevation"],
    setup: "Lie on the back with the knees bent, holding a cane or broomstick across the body with both hands, palms up, hands about shoulder-width apart.",
    steps: [
      "Use the uninvolved arm to do the work of lifting.",
      "Raise the cane up and overhead as far as is comfortable, keeping both elbows straight.",
      "Hold briefly at the end of the comfortable range.",
      "Lower slowly with control, still letting the good arm do most of the work.",
    ],
    dosage: { sets: "2–3", reps: "10", hold: "3–5 s", frequency: "2–3x/day" },
    cue: "“Let your good arm do the lifting — the sore arm is a passenger.”",
    patientInstructions:
      "Lie on your back with your knees bent, holding a broomstick with both hands, palms facing up. Use your good arm to lift the stick up and over your head as far as is comfortable. Hold a few seconds, then lower it slowly. Ten repetitions, two or three times a day.",
    commonErrors: [
      "Letting the involved arm do the lifting instead of being assisted",
      "Arching the low back to gain apparent range",
      "Shrugging the sore shoulder up toward the ear",
      "Pushing into sharp pain instead of stopping at a stretch",
    ],
    regression: "Reduce the range, or use table slides where the arm is supported the whole way.",
    progression: "Move to a seated then standing version, then to active flexion with no cane.",
    precautions: [
      "Follow the surgeon's range-of-motion limits after shoulder surgery — this exercise is often capped at a specific angle early on.",
      "Stop for sharp pain, and expect a stretch rather than a pinch.",
    ],
  },
  {
    id: "supine-cane-external-rotation",
    name: "Supine External Rotation with a Cane",
    aka: ["Wand external rotation", "Assisted external rotation"],
    region: "Shoulder",
    category: "Mobility",
    positions: ["Supine"],
    equipment: ["Cane or dowel", "Towel or strap"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Glenohumeral joint", "Anterior capsule", "Subscapularis"],
    indications: ["Adhesive capsulitis", "Post-operative shoulder stiffness", "Loss of external rotation"],
    setup: "Lie on the back with the elbow of the involved arm at the side, bent to 90 degrees, with a folded towel between the elbow and the ribs. Hold a cane across the body with both hands.",
    steps: [
      "Keep the involved elbow pinned to the side against the towel.",
      "Use the good arm to push the cane so the involved forearm rotates outward.",
      "Stop at a comfortable stretch, not at pain.",
      "Hold, then return slowly to the start.",
    ],
    dosage: { sets: "2–3", reps: "10", hold: "5–10 s", frequency: "2–3x/day" },
    cue: "“Keep your elbow glued to your side and let your good hand push your forearm out like a gate opening.”",
    patientInstructions:
      "Lie on your back with a folded towel between your sore elbow and your side, elbow bent to a right angle. Hold a broomstick with both hands. Use your good hand to push the stick so your sore forearm rotates outwards, away from your body. Stop at a comfortable stretch, hold five to ten seconds, and return. Ten repetitions, two or three times a day.",
    commonErrors: [
      "Letting the elbow drift away from the side, which turns it into a different movement",
      "Pushing into sharp pain",
      "Letting the whole trunk roll to gain range",
    ],
    regression: "Reduce the range and hold shorter.",
    progression: "Progress to the same movement seated or standing, then to active external rotation against a band.",
    precautions: [
      "External rotation is frequently the most restricted direction after a rotator cuff or capsular repair — follow the surgeon's limit exactly.",
      "Take care after anterior shoulder stabilisation surgery, where external rotation is deliberately limited early.",
    ],
  },
  {
    id: "table-slide",
    name: "Table Slide",
    aka: ["Towel slide", "Assisted flexion on a table"],
    region: "Shoulder",
    category: "Mobility",
    positions: ["Seated"],
    equipment: ["Table or counter", "Towel or strap"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Glenohumeral joint", "Shoulder capsule"],
    indications: ["Adhesive capsulitis", "Early post-operative shoulder", "Painful shoulder elevation"],
    setup: "Sit at a table with the forearm resting on a towel on the table surface.",
    steps: [
      "Slide the hand and forearm forward along the table, letting the table carry the weight of the arm.",
      "Let the trunk lean forward as the arm slides, which adds range without any shoulder effort.",
      "Hold at the end of the comfortable range.",
      "Slide back to the start.",
    ],
    dosage: { sets: "2–3", reps: "10", hold: "5 s", frequency: "2–3x/day" },
    cue: "“Let the table hold your arm — slide forward and lean your chest after it.”",
    patientInstructions:
      "Sit at a table with your forearm resting on a towel. Slide your arm forwards along the table, leaning your body forwards as it goes, so the table takes the weight of your arm. Hold five seconds at the furthest comfortable point, then slide back. Ten repetitions, two or three times a day.",
    commonErrors: [
      "Lifting the arm off the table, which removes the support the exercise depends on",
      "Shrugging the shoulder",
      "Rounding the low back instead of hinging forward at the hips",
    ],
    regression: "Slide a shorter distance and skip the trunk lean.",
    progression: "Supine cane flexion, then active elevation.",
    precautions: [
      "Follow post-operative range limits.",
      "Needs a chair and table height that let the shoulder stay relaxed.",
    ],
  },
  {
    id: "scapular-setting",
    name: "Scapular Setting",
    aka: ["Scapular squeeze", "Shoulder blade pinch", "Scapular retraction isometric"],
    region: "Shoulder",
    category: "Activation",
    positions: ["Seated", "Standing", "Prone"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Middle trapezius", "Lower trapezius", "Rhomboids"],
    indications: ["Post-operative shoulder (sling phase, per protocol)", "Scapular control deficit", "Neck and shoulder postural pain"],
    setup: "Sit or stand tall with the arms relaxed at the sides — this can be done with a sling still on.",
    steps: [
      "Draw the shoulder blades gently back and down toward the opposite back pocket.",
      "Hold without shrugging up or pushing the chest forward.",
      "Keep breathing normally.",
      "Release completely between repetitions.",
    ],
    dosage: { sets: "2–3", reps: "10", hold: "5 s", frequency: "1–2x/day", loadOrTempo: "Gentle — about half effort" },
    cue: "“Slide your shoulder blades down and back into your back pockets — no shrugging, and don't puff your chest out.”",
    patientInstructions:
      "Sit or stand tall with your arms relaxed. Gently draw your shoulder blades back and down, as if sliding them toward your back pockets. Hold five seconds and relax. Ten repetitions, once or twice a day. You can do this with your sling on.",
    commonErrors: [
      "Shrugging the shoulders up toward the ears",
      "Squeezing so hard the neck tenses",
      "Pushing the chest forward and arching the low back",
      "Holding the breath",
    ],
    regression: "Do it lying on the back where the floor supports the shoulder blades.",
    progression: "Band pull-apart or band row, which add load to the same pattern.",
    precautions: [
      "Confirm it is permitted in the current post-operative phase — most protocols allow it in the sling phase, but not all.",
      "Keep the effort gentle if the neck flares easily.",
    ],
  },
  {
    id: "isometric-shoulder-er",
    name: "Isometric Shoulder External Rotation",
    aka: ["Wall isometric external rotation", "Submaximal ER hold"],
    region: "Shoulder",
    category: "Activation",
    positions: ["Standing"],
    equipment: ["Wall", "Towel or strap"],
    difficulty: 2,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Infraspinatus", "Teres minor", "Posterior deltoid"],
    indications: ["Rotator cuff related shoulder pain", "Early cuff loading", "Pain-limited shoulder"],
    setup: "Stand side-on to a wall with the involved arm nearest it, elbow at the side and bent to 90 degrees, with a folded towel between the elbow and the ribs. Place the back of the hand against the wall.",
    steps: [
      "Press the back of the hand into the wall as if rotating the forearm outward.",
      "Nothing should move — the wall doesn't give and the arm stays put.",
      "Build to a moderate effort over a second or two, hold, then ease off gradually.",
      "Rest between repetitions.",
    ],
    dosage: { sets: "2–3", reps: "8–10", hold: "5–10 s", frequency: "Once daily", loadOrTempo: "About 50% effort, built up and released gradually" },
    cue: "“Press the back of your hand into the wall like you're opening a door with it — hard enough to feel it, but nothing moves.”",
    patientInstructions:
      "Stand with your sore arm next to a wall, elbow bent to a right angle and a folded towel between your elbow and your side. Put the back of your hand against the wall and press into it, as if turning your forearm outwards. Nothing should actually move. Hold five to ten seconds, then ease off. Eight to ten repetitions.",
    commonErrors: [
      "Letting the elbow drift away from the side",
      "Pressing at maximum effort",
      "Snapping the effort on and off",
      "Shrugging the shoulder during the hold",
    ],
    regression: "Lower the effort and shorten the hold; press into a hand rather than a wall so the effort can be graded more finely.",
    progression: "Band external rotation with the elbow at the side.",
    precautions: [
      "Keep the effort submaximal, especially where the tendon is irritable.",
      "Stop if it reproduces sharp pain rather than a working ache.",
    ],
  },
  {
    id: "isometric-shoulder-ir",
    name: "Isometric Shoulder Internal Rotation",
    region: "Shoulder",
    category: "Activation",
    positions: ["Standing"],
    equipment: ["Wall", "Towel or strap"],
    difficulty: 2,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Subscapularis", "Pectoralis major", "Latissimus dorsi"],
    indications: ["Rotator cuff related shoulder pain", "Post subscapularis repair (per protocol)", "Pain-limited shoulder"],
    setup: "Stand facing a door frame or corner with the involved elbow at the side, bent to 90 degrees, a folded towel between the elbow and the ribs, and the palm against the wall.",
    steps: [
      "Press the palm into the wall as if rotating the forearm inward across the body.",
      "Keep the elbow at the side and nothing moving.",
      "Build the effort, hold, and release gradually.",
    ],
    dosage: { sets: "2–3", reps: "8–10", hold: "5–10 s", frequency: "Once daily", loadOrTempo: "About 50% effort" },
    cue: "“Press your palm into the wall like you're pushing a door shut across your body — elbow stays pinned to your side.”",
    patientInstructions:
      "Stand facing a wall with your sore elbow bent at your side and a folded towel between your elbow and your ribs. Press your palm into the wall as if turning your forearm inwards. Nothing should move. Hold five to ten seconds, then ease off. Eight to ten repetitions.",
    commonErrors: [
      "Leaning the whole body into the wall instead of using the shoulder",
      "Maximal effort rather than a controlled submaximal hold",
      "Letting the elbow slide away from the side",
    ],
    regression: "Lower effort, shorter hold, pressing into the other hand rather than a wall.",
    progression: "Band internal rotation with the elbow at the side.",
    precautions: [
      "Internal rotation loading is specifically restricted after subscapularis repair — follow the surgeon's protocol.",
      "Keep the effort submaximal while the shoulder is irritable.",
    ],
  },
  {
    id: "sidelying-external-rotation",
    name: "Sidelying External Rotation",
    aka: ["Sidelying ER", "Dumbbell external rotation"],
    region: "Shoulder",
    category: "Strength",
    positions: ["Sidelying"],
    equipment: ["Weight", "Towel or strap"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Infraspinatus", "Teres minor"],
    indications: ["Rotator cuff related shoulder pain", "Post-operative cuff strengthening phase", "Overhead athlete cuff conditioning"],
    setup: "Lie on the uninvolved side. The top arm rests along the body with the elbow bent to 90 degrees and a folded towel between the elbow and the ribs. Hold a light weight.",
    steps: [
      "Keeping the elbow pinned against the towel, rotate the forearm upward toward the ceiling.",
      "Stop at the point where the elbow starts to lift or the trunk starts to roll back.",
      "Lower slowly — take about twice as long coming down as going up.",
    ],
    dosage: { sets: "2–3", reps: "10–15", frequency: "Every other day", loadOrTempo: "Start with no weight or 1–2 lb; 1 s up, 2–3 s down" },
    cue: "“Elbow stays glued to the towel — only your forearm moves, like a gate on a hinge.”",
    patientInstructions:
      "Lie on your good side with a folded towel between your top elbow and your ribs, elbow bent to a right angle, holding a light weight. Keeping your elbow against the towel, rotate your forearm up toward the ceiling, then lower it slowly. Ten to fifteen repetitions, every other day. Start with no weight at all.",
    commonErrors: [
      "Letting the elbow lift off the towel to gain range",
      "Rolling the trunk backward to help the arm up",
      "Using too much weight — this is a small muscle group and 1–3 lb is often plenty",
      "Dropping the weight down rather than lowering it slowly",
    ],
    regression: "No weight at all, or band external rotation standing, which loads less at end range.",
    progression: "Add weight in 1 lb steps, or move to 90/90 prone external rotation for the overhead athlete.",
    precautions: [
      "Follow post-operative loading timelines — active cuff strengthening usually starts later than range of motion.",
      "Sharp pain in the front or top of the shoulder means reduce the load or range.",
    ],
  },
  {
    id: "band-external-rotation",
    name: "Band External Rotation (Elbow at Side)",
    aka: ["Standing ER with band", "Resisted external rotation"],
    region: "Shoulder",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Resistance band", "Towel or strap"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Infraspinatus", "Teres minor", "Posterior cuff"],
    indications: ["Rotator cuff related shoulder pain", "Shoulder instability", "Overhead sport conditioning", "Post-operative strengthening phase"],
    setup: "Anchor a band at elbow height. Stand side-on with the involved arm furthest from the anchor, elbow at the side and bent to 90 degrees, folded towel between elbow and ribs.",
    steps: [
      "Hold the band across the body and step out until there is light tension at the start.",
      "Rotate the forearm outward, away from the body, keeping the elbow at the side.",
      "Stop before the trunk starts rotating to help.",
      "Return slowly against the band rather than letting it snap back.",
    ],
    dosage: { sets: "2–3", reps: "10–15", frequency: "Every other day", loadOrTempo: "Band tension where the last 2–3 repetitions are hard but clean" },
    cue: "“Keep the towel squeezed under your elbow and open the gate — and control it all the way back in.”",
    patientInstructions:
      "Anchor a resistance band at elbow height and stand side-on to it, with the sore arm furthest away. Tuck a folded towel between that elbow and your side, and bend the elbow to a right angle. Holding the band, rotate your forearm outwards away from your body, then slowly let it come back. Ten to fifteen repetitions, every other day.",
    commonErrors: [
      "Letting the elbow drift away from the side",
      "Turning the trunk to gain range",
      "Using a band so heavy the movement becomes a whole-body effort",
      "Letting the band pull the arm back fast",
    ],
    regression: "Lighter band, smaller range, or an isometric hold instead.",
    progression: "Heavier band, then the same movement with the arm at 90 degrees of abduction for overhead athletes.",
    precautions: [
      "Follow post-operative loading restrictions.",
      "Reduce load if it reproduces sharp pain rather than a working effort.",
    ],
  },
  {
    id: "band-internal-rotation",
    name: "Band Internal Rotation (Elbow at Side)",
    region: "Shoulder",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Resistance band", "Towel or strap"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Subscapularis", "Pectoralis major", "Latissimus dorsi"],
    indications: ["Rotator cuff related shoulder pain", "Shoulder instability", "Post-operative strengthening phase"],
    setup: "Anchor a band at elbow height. Stand side-on with the involved arm nearest the anchor, elbow at the side bent to 90 degrees, folded towel between elbow and ribs.",
    steps: [
      "Hold the band with the forearm rotated outward at the start.",
      "Pull the forearm inward across the body, keeping the elbow pinned at the side.",
      "Stop at the midline rather than continuing across the body.",
      "Return slowly against the band.",
    ],
    dosage: { sets: "2–3", reps: "10–15", frequency: "Every other day", loadOrTempo: "Band tension where the last 2–3 repetitions are hard but clean" },
    cue: "“Bring your forearm across to your belly button and stop — elbow never leaves your side.”",
    patientInstructions:
      "Anchor a band at elbow height and stand side-on with your sore arm nearest it. Tuck a folded towel between that elbow and your side. With your elbow bent, pull your forearm across toward your stomach, then let it slowly return. Ten to fifteen repetitions, every other day.",
    commonErrors: [
      "Letting the elbow travel forward or away from the side",
      "Rotating the trunk to help",
      "Snapping back at the end of each repetition",
    ],
    regression: "Lighter band, or an isometric internal rotation hold.",
    progression: "Heavier band, or add a step away from the anchor for greater range under tension.",
    precautions: [
      "Specifically restricted after subscapularis repair — follow the surgeon's protocol on when resisted internal rotation may start.",
      "Reduce load for sharp pain.",
    ],
  },
  {
    id: "band-row",
    name: "Band Row",
    aka: ["Seated row with band", "Resisted scapular retraction"],
    region: "Shoulder",
    category: "Strength",
    positions: ["Standing", "Seated"],
    equipment: ["Resistance band"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Middle trapezius", "Rhomboids", "Latissimus dorsi", "Posterior deltoid"],
    indications: ["Scapular weakness", "Rounded shoulder posture", "Rotator cuff related shoulder pain", "General upper body conditioning"],
    setup: "Anchor a band at chest height. Stand or sit facing the anchor holding one end in each hand, arms extended, with light tension at the start.",
    steps: [
      "Set the shoulder blades down and back before the arms move.",
      "Pull the elbows straight back past the ribs, keeping them close to the body.",
      "Squeeze the shoulder blades together at the end without shrugging.",
      "Return slowly with control.",
    ],
    dosage: { sets: "2–3", reps: "10–15", frequency: "Every other day", loadOrTempo: "2 s pull, 3 s return" },
    cue: "“Lead with your elbows, not your hands — and finish by pinching your shoulder blades, not by shrugging.”",
    patientInstructions:
      "Anchor a band at chest height and face it, holding one end in each hand with your arms out in front. Pull your elbows straight back past your ribs, squeezing your shoulder blades together. Return slowly. Ten to fifteen repetitions, every other day.",
    commonErrors: [
      "Shrugging the shoulders up during the pull",
      "Leaning the trunk backward to move more band tension",
      "Flaring the elbows out wide",
      "Letting the band snap the arms forward on the return",
    ],
    regression: "Lighter band, seated with the back supported, and a smaller range.",
    progression: "Heavier band, single-arm rows, or a bent-over dumbbell row.",
    precautions: [
      "Follow post-operative loading timelines.",
      "Stop for sharp neck or shoulder pain rather than pushing through.",
    ],
  },
  {
    id: "scaption-raise",
    name: "Scaption Raise",
    aka: ["Full can raise", "Raise in the plane of the scapula"],
    region: "Shoulder",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["None", "Weight"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Supraspinatus", "Deltoid", "Serratus anterior", "Trapezius"],
    indications: ["Rotator cuff related shoulder pain", "Post-operative strengthening phase", "Overhead reaching weakness"],
    setup: "Stand tall with the arms at the sides. The working arm moves in a plane about 30–45 degrees forward of straight out to the side — the plane the shoulder blade sits in.",
    steps: [
      "Turn the thumb up so the palm faces slightly upward — a 'full can' rather than an emptied one.",
      "Raise the arm in that forward-of-sideways plane, no higher than shoulder height at first.",
      "Stop before the shoulder shrugs or the trunk leans.",
      "Lower slowly, taking longer down than up.",
    ],
    dosage: { sets: "2–3", reps: "10–12", frequency: "Every other day", loadOrTempo: "Bodyweight first, then 1–3 lb; 2 s up, 3 s down" },
    cue: "“Thumb up, and raise it halfway between straight ahead and straight out to the side — stop at shoulder height and lower it slowly.”",
    patientInstructions:
      "Stand tall with your arms by your sides and your thumb pointing up. Raise your arm halfway between straight in front and straight out to the side, up to about shoulder height. Lower it slowly. Ten to twelve repetitions, every other day. Start with no weight.",
    commonErrors: [
      "Raising the arm straight out to the side rather than in the scapular plane",
      "Turning the thumb down, which narrows the space at the top of the shoulder",
      "Shrugging or leaning away to get the arm higher",
      "Adding weight before the unweighted version is clean and pain-free",
    ],
    regression: "Raise only to 45 degrees, or perform lying on the side where gravity's demand changes.",
    progression: "Increase height toward overhead, then add weight, then add a hold at the top.",
    precautions: [
      "Follow post-operative range and loading limits.",
      "A painful arc means reduce the height rather than push through it.",
    ],
  },
  {
    id: "serratus-punch",
    name: "Supine Serratus Punch",
    aka: ["Scapular protraction", "Supine punch", "Serratus anterior activation"],
    region: "Shoulder",
    category: "Activation",
    positions: ["Supine"],
    equipment: ["None", "Weight"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Serratus anterior"],
    indications: ["Scapular winging", "Shoulder impingement", "Poor overhead scapular upward rotation"],
    setup: "Lie on the back with the knees bent. Reach the involved arm straight up toward the ceiling, elbow locked.",
    steps: [
      "Keeping the elbow straight, push the whole arm up toward the ceiling so the shoulder blade lifts off the floor.",
      "The movement is small — a couple of inches at most.",
      "Hold at the top, then let the shoulder blade settle back down.",
      "Do not let the elbow bend and re-straighten.",
    ],
    dosage: { sets: "2–3", reps: "10–12", hold: "2–3 s", frequency: "Every other day", loadOrTempo: "Bodyweight first, then 1–3 lb" },
    cue: "“Punch your hand at the ceiling without bending your elbow — your shoulder blade should come off the floor.”",
    patientInstructions:
      "Lie on your back with your knees bent and reach one arm straight up to the ceiling. Keeping your elbow completely straight, push your hand a couple of inches higher so your shoulder blade lifts off the floor. Hold a couple of seconds, then let it settle. Ten to twelve repetitions.",
    commonErrors: [
      "Bending and straightening the elbow instead of moving the shoulder blade",
      "Making the movement too large",
      "Shrugging the shoulder toward the ear",
    ],
    regression: "Do it with no weight and a smaller range.",
    progression: "Add a light weight, then progress to a Wall Push-Up Plus and then a plank position.",
    precautions: [
      "Follow post-operative restrictions on shoulder flexion and loading.",
      "Not appropriate where the shoulder cannot be comfortably positioned at 90 degrees of flexion.",
    ],
  },
  {
    id: "wall-push-up-plus",
    name: "Wall Push-Up Plus",
    aka: ["Push-up plus at the wall", "Scapular push-up"],
    region: "Shoulder",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Wall"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Serratus anterior", "Pectoralis major", "Triceps"],
    indications: ["Scapular winging", "Scapular control deficit", "Early closed-chain shoulder loading"],
    setup: "Stand facing a wall with the hands flat on it at shoulder height and width, feet a comfortable distance back.",
    steps: [
      "Bend the elbows and let the chest come toward the wall.",
      "Push back to straight arms.",
      "At the top, push a little further so the shoulder blades spread apart around the ribs — that extra push is the 'plus'.",
      "Let the shoulder blades come back together to start the next repetition.",
    ],
    dosage: { sets: "2–3", reps: "10–15", frequency: "Every other day", loadOrTempo: "Controlled, with a 2 s hold on the 'plus'" },
    cue: "“Push all the way through at the top and let your shoulder blades spread apart — that last inch is the whole exercise.”",
    patientInstructions:
      "Stand facing a wall with your hands flat on it at shoulder height. Bend your elbows to bring your chest toward the wall, then push back. At the very top, push a little further so your shoulder blades spread apart. Ten to fifteen repetitions, every other day.",
    commonErrors: [
      "Skipping the 'plus' at the top, which is the part that trains the serratus",
      "Shrugging at the top",
      "Letting the low back sag",
    ],
    regression: "Stand closer to the wall, which reduces the load.",
    progression: "Step further from the wall, then progress to a countertop, then to the floor from the knees.",
    precautions: [
      "Follow post-operative restrictions on weight-bearing through the arm.",
      "Not appropriate where the wrist will not tolerate extension — use fists or push-up handles instead.",
    ],
  },
  {
    id: "sleeper-stretch",
    name: "Sleeper Stretch",
    aka: ["Posterior capsule stretch", "Sidelying internal rotation stretch"],
    region: "Shoulder",
    category: "Flexibility",
    positions: ["Sidelying"],
    equipment: ["None"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Posterior shoulder capsule", "Posterior rotator cuff"],
    indications: ["Loss of shoulder internal rotation", "Overhead athlete with an internal rotation deficit", "Posterior shoulder tightness"],
    setup: "Lie on the involved side with that shoulder positioned forward under the body so it is not pinched. Bring the arm to 90 degrees of shoulder flexion with the elbow bent to 90 degrees.",
    steps: [
      "Roll slightly backward so the body weight pins the shoulder blade, not the shoulder joint.",
      "Use the other hand to press the forearm down toward the floor, rotating the shoulder inward.",
      "Stop at a stretch in the back of the shoulder — never a pinch at the front.",
      "Hold, then release slowly.",
    ],
    dosage: { sets: "3", reps: "1", hold: "30 s", frequency: "Once daily" },
    cue: "“You should feel this in the back of your shoulder — if you feel a pinch in the front, back off and roll a little further onto your shoulder blade.”",
    patientInstructions:
      "Lie on the side you want to stretch, with that shoulder tucked slightly forward under you. Bend that elbow to a right angle with your arm out in front of you at shoulder height. Use your other hand to press that forearm down toward the floor. You should feel a stretch at the back of your shoulder, not a pinch at the front. Hold thirty seconds, three times.",
    commonErrors: [
      "Lying directly on the shoulder joint, which compresses it",
      "Pushing hard enough to feel pinching at the front of the shoulder",
      "Letting the trunk roll forward, which removes the stretch",
    ],
    regression: "Cross-Body Stretch, which is easier to grade and better tolerated by an irritable shoulder.",
    progression: "Hold longer, or add a gentle contract–relax at end range.",
    precautions: [
      "Stop for any front-of-shoulder pinching — that means the position is wrong, not that more force is needed.",
      "Not appropriate with shoulder instability, recent dislocation, or in early post-operative care.",
    ],
  },
  {
    id: "cross-body-stretch",
    name: "Cross-Body Shoulder Stretch",
    aka: ["Horizontal adduction stretch", "Posterior shoulder stretch"],
    region: "Shoulder",
    category: "Flexibility",
    positions: ["Standing", "Seated", "Supine"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Posterior shoulder capsule", "Posterior deltoid"],
    indications: ["Posterior shoulder tightness", "Loss of horizontal adduction", "Overhead athlete maintenance"],
    setup: "Stand or sit tall. Bring the involved arm across the front of the chest at about shoulder height.",
    steps: [
      "Use the other hand to hold just above the elbow — not on the elbow joint itself.",
      "Draw the arm gently across the body until a stretch is felt at the back of the shoulder.",
      "Keep the shoulder down rather than letting it ride up.",
      "Hold, breathing normally.",
    ],
    dosage: { sets: "2–3", reps: "1", hold: "30 s", frequency: "1–2x/day" },
    cue: "“Hold above your elbow, not on it, and keep that shoulder down as you draw the arm across.”",
    patientInstructions:
      "Bring one arm across the front of your chest at shoulder height. Use your other hand to hold just above that elbow and draw the arm gently across your body until you feel a stretch at the back of the shoulder. Keep the shoulder down. Hold thirty seconds, two or three times.",
    commonErrors: [
      "Pulling on the elbow joint itself",
      "Letting the shoulder shrug up toward the ear",
      "Turning the trunk away instead of moving the arm across",
    ],
    regression: "Reduce the pull and hold for 15 seconds.",
    progression: "Sleeper Stretch, which reaches the posterior capsule more specifically.",
    precautions: [
      "Stop for pinching at the front or top of the shoulder.",
      "Follow post-operative restrictions on horizontal adduction, which is often limited early.",
    ],
  },
  {
    id: "doorway-pec-stretch",
    name: "Doorway Pectoral Stretch",
    aka: ["Corner stretch", "Chest stretch"],
    region: "Shoulder",
    category: "Flexibility",
    positions: ["Standing"],
    equipment: ["Wall"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Pectoralis major", "Pectoralis minor", "Anterior shoulder"],
    indications: ["Rounded shoulder posture", "Chest tightness", "Shoulder impingement with anterior tightness"],
    setup: "Stand in a doorway with the forearms on the frame, elbows at about shoulder height, one foot slightly forward.",
    steps: [
      "Keep the ribs down and the low back neutral — do not arch to increase the stretch.",
      "Step or lean gently forward until a stretch is felt across the front of the chest.",
      "Hold, breathing normally.",
      "Repeat with the elbows a little lower and a little higher to reach different fibres.",
    ],
    dosage: { sets: "2–3", reps: "1 per arm height", hold: "30 s", frequency: "Once daily" },
    cue: "“Keep your ribs down and step through the doorway — the stretch is across your chest, not in the front of your shoulder joint.”",
    patientInstructions:
      "Stand in a doorway with your forearms on the frame and your elbows at about shoulder height. Step one foot forward and lean gently through until you feel a stretch across the front of your chest. Keep your ribs down and do not arch your back. Hold thirty seconds. Repeat with your elbows slightly higher and slightly lower.",
    commonErrors: [
      "Arching the low back to create the sensation of a stretch",
      "Leaning so far that the front of the shoulder joint is stressed rather than the chest muscle",
      "Holding the breath",
    ],
    regression: "Use one arm at a time against a wall, with a smaller lean.",
    progression: "Add the higher and lower elbow positions, and hold for up to 45 seconds.",
    precautions: [
      "Not appropriate with anterior shoulder instability or after anterior stabilisation surgery until cleared.",
      "Stop for pain at the front of the shoulder joint — this should be felt in the chest.",
    ],
  },
  {
    id: "wall-walk-flexion",
    name: "Wall Walk (Shoulder Flexion)",
    aka: ["Finger ladder", "Wall climbing"],
    region: "Shoulder",
    category: "Mobility",
    positions: ["Standing"],
    equipment: ["Wall"],
    difficulty: 2,
    phases: ["Subacute / Restore"],
    targets: ["Glenohumeral joint", "Shoulder capsule", "Scapulothoracic joint"],
    indications: ["Adhesive capsulitis", "Loss of shoulder elevation", "Post-operative stiffness"],
    setup: "Stand facing a wall, about an arm's length away, with the fingertips of the involved hand resting on it.",
    steps: [
      "Walk the fingers up the wall, stepping closer to the wall as the arm rises.",
      "Stop at the highest comfortable point, not at pain.",
      "Hold briefly, then walk the fingers back down.",
      "Mark the highest point reached so progress is visible session to session.",
    ],
    dosage: { sets: "2–3", reps: "5–8", hold: "5–10 s at the top", frequency: "2–3x/day" },
    cue: "“Let your fingers do the climbing and step in as you go — mark where you get to so you can see it improve.”",
    patientInstructions:
      "Stand facing a wall with your fingertips on it. Walk your fingers up the wall as high as is comfortable, stepping closer to the wall as your arm goes up. Hold at the top for five to ten seconds, then walk your fingers back down. Five to eight times, two or three times a day. Mark where you reach so you can see your progress.",
    commonErrors: [
      "Shrugging the shoulder to gain height",
      "Leaning the trunk sideways instead of raising the arm",
      "Pushing into sharp pain",
    ],
    regression: "Do it side-on for abduction, or use table slides, which support the arm's weight.",
    progression: "Active shoulder flexion without the wall, then add light weight.",
    precautions: [
      "Follow post-operative range limits.",
      "Height gained by shrugging or leaning is not real range — reduce and rebuild.",
    ],
  },
  {
    id: "band-pull-apart",
    name: "Band Pull-Apart",
    region: "Shoulder",
    category: "Strength",
    positions: ["Standing"],
    equipment: ["Resistance band"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Middle trapezius", "Rhomboids", "Posterior deltoid", "External rotators"],
    indications: ["Scapular retractor weakness", "Rounded shoulder posture", "Upper back conditioning"],
    setup: "Stand tall holding a light resistance band with both hands, arms straight out in front at about shoulder height, hands shoulder-width apart.",
    steps: [
      "Keep the elbows straight throughout.",
      "Pull the band apart by taking the hands out to the sides, squeezing the shoulder blades together.",
      "Stop when the band reaches the chest or when the shoulders start to shrug.",
      "Return slowly under control.",
    ],
    dosage: { sets: "2–3", reps: "12–15", frequency: "Every other day", loadOrTempo: "Light band, 2 s out and 2 s back" },
    cue: "“Straight arms, and pull the band apart by squeezing your shoulder blades — the hands are just holding on.”",
    patientInstructions:
      "Stand tall holding a light resistance band with both hands, arms straight out in front at shoulder height. Keeping your elbows straight, pull the band apart out to your sides, squeezing your shoulder blades together. Return slowly. Twelve to fifteen repetitions, every other day.",
    commonErrors: [
      "Bending the elbows to make it easier",
      "Shrugging the shoulders",
      "Using a band that is far too heavy, so the arms and trunk take over",
      "Letting the band snap back",
    ],
    regression: "Wider hand position on the band, or a lighter band.",
    progression: "Narrower hand position, heavier band, or perform at a slight incline overhead.",
    precautions: [
      "Follow post-operative restrictions.",
      "Reduce the range if the front of the shoulder pinches at end range.",
    ],
  },
  {
    id: "towel-internal-rotation-stretch",
    name: "Towel Internal Rotation Stretch",
    aka: ["Behind-the-back towel stretch"],
    region: "Shoulder",
    category: "Flexibility",
    positions: ["Standing"],
    equipment: ["Towel or strap"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Anterior shoulder", "Posterior cuff", "Shoulder capsule"],
    indications: ["Adhesive capsulitis", "Difficulty reaching behind the back", "Loss of internal rotation and extension"],
    setup: "Stand and drape a towel over one shoulder so one end hangs down the back and one down the front. Reach the involved hand behind the back to grip the lower end.",
    steps: [
      "Use the top hand to pull the towel gently upward.",
      "Let the involved hand ride up the back until a comfortable stretch is felt.",
      "Hold, breathing normally.",
      "Lower slowly rather than letting the arm drop.",
    ],
    dosage: { sets: "2–3", reps: "1", hold: "20–30 s", frequency: "1–2x/day" },
    cue: "“Let the towel do the lifting — go to a stretch, not a strain, and lower it slowly.”",
    patientInstructions:
      "Drape a towel over one shoulder so one end hangs down your back. Reach your other hand behind your back and take hold of the lower end. Use your top hand to pull the towel gently upward, sliding your lower hand up your back until you feel a stretch. Hold twenty to thirty seconds, then lower slowly. Two or three times.",
    commonErrors: [
      "Yanking the towel, which forces the shoulder into a vulnerable position",
      "Bending the trunk sideways instead of moving the shoulder",
      "Letting the lower arm drop suddenly at the end",
    ],
    regression: "Simply reach the hand behind the back without the towel and slide it up the back as far as is comfortable.",
    progression: "Hold longer, or add a gentle contract–relax.",
    precautions: [
      "Not appropriate in early post-operative care, or after anterior stabilisation surgery until cleared — this position combines extension and internal rotation.",
      "Stop for sharp pain at the front of the shoulder.",
    ],
  },
  {
    id: "prone-external-rotation-90-90",
    name: "Prone External Rotation at 90/90",
    aka: ["Prone ER", "90/90 external rotation"],
    region: "Shoulder",
    category: "Strength",
    positions: ["Prone"],
    equipment: ["Weight", "Table or counter"],
    difficulty: 4,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Infraspinatus", "Teres minor", "Posterior deltoid", "Scapular stabilisers"],
    indications: ["Overhead athlete conditioning", "Late-stage rotator cuff strengthening", "Throwing shoulder preparation"],
    setup: "Lie face down on a table or bed with the involved arm hanging off the side, shoulder abducted to 90 degrees and the upper arm supported on the table edge, elbow bent to 90 degrees.",
    steps: [
      "Set the shoulder blade back and down first.",
      "Rotate the forearm upward until it is level with the table, no higher at first.",
      "Hold briefly at the top.",
      "Lower slowly, taking longer down than up.",
    ],
    dosage: { sets: "2–3", reps: "10–12", frequency: "Every other day", loadOrTempo: "Start with no weight, then 1–3 lb; 1 s up, 3 s down" },
    cue: "“Set your shoulder blade first, then rotate your forearm up to level — and lower it under full control.”",
    patientInstructions:
      "Lie face down on a bed with your arm hanging over the edge, your upper arm supported on the edge and out to the side at shoulder height, elbow bent to a right angle. Rotate your forearm up until it is level with the bed, then lower it slowly. Ten to twelve repetitions, every other day. Start with no weight.",
    commonErrors: [
      "Letting the shoulder blade roll forward during the lift",
      "Rotating past level too early in the progression",
      "Using too much weight, so the movement becomes a swing",
      "Shrugging",
    ],
    regression: "Sidelying external rotation with the elbow at the side, which is far less provocative.",
    progression: "Increase weight, then add the same movement standing with a band at 90 degrees of abduction.",
    precautions: [
      "A late-stage exercise — the 90/90 position loads the anterior shoulder and is not appropriate early after injury or surgery.",
      "Not appropriate with anterior instability until cleared.",
    ],
  },
  {
    id: "closed-chain-wall-stabilization",
    name: "Closed-Chain Wall Stabilisation",
    aka: ["Ball on wall circles", "Rhythmic stabilisation at the wall"],
    region: "Shoulder",
    category: "Motor Control",
    positions: ["Standing"],
    equipment: ["Ball", "Wall"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Rotator cuff", "Serratus anterior", "Scapular stabilisers"],
    indications: ["Shoulder instability", "Proprioceptive deficit after shoulder injury", "Late-stage rotator cuff rehabilitation"],
    setup: "Stand facing a wall, holding a small ball against it with the palm of the involved hand at about shoulder height. The elbow stays slightly bent.",
    steps: [
      "Press lightly into the ball so it stays put.",
      "Draw slow, small circles with the ball — clockwise, then anticlockwise.",
      "Then trace the letters of the alphabet, or move up and down and side to side.",
      "Keep the shoulder blade set and the trunk still.",
    ],
    dosage: { sets: "2–3", reps: "20–30 s of continuous movement each direction", frequency: "Every other day" },
    cue: "“Keep light pressure on the ball and let your shoulder blade stay set — small, smooth circles, no shrugging.”",
    patientInstructions:
      "Stand facing a wall and hold a small ball against it with your palm at about shoulder height, elbow slightly bent. Press lightly and draw slow circles with the ball, one way then the other, for twenty to thirty seconds each. Keep your body still and your shoulder down.",
    commonErrors: [
      "Pressing so hard the shoulder fatigues before the control work happens",
      "Moving the trunk instead of the arm",
      "Shrugging the shoulder",
      "Rushing the circles",
    ],
    regression: "Perform with the hand lower, or use the wall directly without a ball.",
    progression: "Raise the hand height, move to an unstable surface, or progress to quadruped and plank-position weight shifts.",
    precautions: [
      "Follow post-operative weight-bearing restrictions for the arm.",
      "Stop for sharp pain rather than continuing for the full time.",
    ],
  },
];
