import type { MovementExercise } from "@/lib/movement-lab/types";

/** Thoracic spine and rib cage. The region a stiff neck and a painful shoulder both end up
 *  blaming, so these entries get referenced from the cervical and shoulder protocols as
 *  often as they get prescribed on their own. */
export const THORACIC_EXERCISES: MovementExercise[] = [
  {
    id: "thoracic-extension-chair",
    name: "Thoracic Extension over a Chair",
    aka: ["Seated thoracic extension", "Chair-back extension"],
    region: "Thoracic & Rib",
    category: "Mobility",
    positions: ["Seated"],
    equipment: ["Chair"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore", "Strengthening"],
    targets: ["Thoracic extensors", "Costovertebral joints", "Anterior chest wall"],
    indications: ["Thoracic kyphosis", "Desk-related upper back stiffness", "Shoulder impingement with thoracic restriction", "Neck pain with thoracic restriction"],
    setup: "Sit upright in a firm chair with a back that reaches roughly the bottom of the shoulder blades. Feet flat, hands behind the head with elbows out.",
    steps: [
      "Draw the shoulder blades gently back and down.",
      "Extend the upper back over the chair back — the chair edge acts as the pivot point.",
      "Stop before the movement runs into the low back; the ribs should not flare forward.",
      "Hold, then return to neutral.",
    ],
    dosage: { sets: "2–3", reps: "10", hold: "3–5 s", frequency: "1–2x/day" },
    cue: "“Lift your breastbone toward the ceiling while keeping your ribs controlled — don't arch from your low back.”",
    patientInstructions:
      "Sit in a firm chair with your hands behind your head and elbows out to the sides. Bend backwards over the back of the chair, arching your upper back only — your lower back should stay still. Hold three to five seconds, then sit back up. Ten repetitions, once or twice a day.",
    commonErrors: [
      "Arching from the lower back instead of the upper back",
      "Letting the ribs flare forward, which is the low back taking over",
      "Pulling the head forward with the hands",
      "Using a chair whose back is too high, which blocks the movement entirely",
    ],
    regression: "Hands crossed on the chest instead of behind the head, with a smaller range.",
    progression: "Foam Roller Thoracic Extension, which gives a more segmental stretch.",
    precautions: [
      "Reduce range or avoid where osteoporosis, vertebral fracture history, or significant spinal instability is known.",
      "Stop for any sharp or radiating pain rather than working through it.",
    ],
  },
  {
    id: "foam-roller-thoracic-extension",
    name: "Foam Roller Thoracic Extension",
    aka: ["Roller extensions", "Segmental thoracic extension"],
    region: "Thoracic & Rib",
    category: "Mobility",
    positions: ["Supine"],
    equipment: ["Foam roller"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Thoracic spine segments", "Thoracic extensors", "Anterior chest wall"],
    indications: ["Thoracic hypomobility", "Kyphotic posture", "Overhead reaching restriction"],
    setup: "Lie on the back with a foam roller across the upper back, perpendicular to the spine. Knees bent, feet flat, hands supporting the head.",
    steps: [
      "Support the head fully with the hands so the neck never hangs.",
      "Lift the hips slightly and extend the upper back over the roller.",
      "Hold at that level for a few breaths.",
      "Move the roller one hand-width along the spine and repeat, covering the mid and upper back — never the low back or the neck.",
    ],
    dosage: { sets: "1–2", reps: "3–5 per segment", hold: "3–5 breaths", frequency: "Once daily" },
    cue: "“Hold your own head the whole time, and let the roller be the hinge — small arch, breathe, then move up a level.”",
    patientInstructions:
      "Lie on your back with a foam roller across your upper back and your hands behind your head to support it. Gently arch backwards over the roller and hold for a few breaths. Move the roller a hand-width up or down your upper back and repeat. Keep the roller on your upper and mid back only — never on your lower back or neck.",
    commonErrors: [
      "Letting the head fall back unsupported",
      "Rolling down into the lumbar spine, which extends a region that usually doesn't need it",
      "Forcing a large arch instead of a controlled one at each level",
    ],
    regression: "Thoracic Extension over a Chair, or use a rolled towel instead of a firm roller.",
    progression: "Add an overhead arm reach at end range, or hold a light weight overhead.",
    precautions: [
      "Avoid with osteoporosis, known vertebral fracture, or recent thoracic or rib injury.",
      "Not appropriate for someone who cannot get down to and up from the floor safely.",
    ],
  },
  {
    id: "open-book-rotation",
    name: "Open Book Rotation",
    aka: ["Sidelying thoracic rotation", "Book openers"],
    region: "Thoracic & Rib",
    category: "Mobility",
    positions: ["Sidelying"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore", "Strengthening"],
    targets: ["Thoracic rotators", "Anterior chest wall", "Rib cage"],
    indications: ["Thoracic rotation restriction", "Golf or throwing rotation loss", "Upper back stiffness", "Neck pain with rotation loss"],
    setup: "Lie on one side with hips and knees bent to about 90 degrees, knees stacked, arms straight out in front at shoulder height with palms together.",
    steps: [
      "Keep the knees together and down — they should not move at all during the exercise.",
      "Slide the top hand along the bottom arm, then open it up and across toward the floor behind, turning the chest and following the hand with the eyes.",
      "Let the ribs and chest do the turning, not the pelvis.",
      "Hold at end range, then close slowly back to the start.",
    ],
    dosage: { sets: "1–2", reps: "8–10 each side", hold: "3–5 s", frequency: "Once or twice daily" },
    cue: "“Glue your knees together and open your chest to the ceiling — follow your hand with your eyes and let your breath take you a little further.”",
    patientInstructions:
      "Lie on your side with your knees bent and stacked, and both arms straight out in front of you. Keeping your knees together and still, open your top arm across your body toward the floor behind you, turning your chest and following your hand with your eyes. Hold a few seconds, then bring it back. Eight to ten each side.",
    commonErrors: [
      "Letting the top knee lift, which turns it into a hip and low back movement",
      "Reaching with the arm alone while the chest stays facing forward",
      "Holding the breath instead of exhaling into the rotation",
    ],
    regression: "Reduce the range — stop as soon as the knees want to separate.",
    progression: "Place a ball or block between the knees to enforce the lock, or add a breathing hold at end range.",
    precautions: [
      "Stay within a comfortable range where there is a recent rib injury or costochondral pain.",
      "Stop for sharp mid-back or chest pain rather than pushing through it.",
    ],
  },
  {
    id: "thread-the-needle",
    name: "Thread the Needle",
    region: "Thoracic & Rib",
    category: "Mobility",
    positions: ["Quadruped"],
    equipment: ["None"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Thoracic rotators", "Posterior shoulder", "Rhomboids"],
    indications: ["Thoracic rotation restriction", "Posterior shoulder tightness", "Upper back stiffness"],
    setup: "Start on hands and knees, hands under shoulders, knees under hips.",
    steps: [
      "Reach one arm underneath the body and across toward the opposite side, palm up.",
      "Let the shoulder and side of the head lower toward the floor as the chest turns.",
      "Hold, breathing into the stretch.",
      "Unwind and reach the same arm up toward the ceiling, opening the chest the other way.",
    ],
    dosage: { sets: "1–2", reps: "6–8 each side", hold: "3–5 s", frequency: "Once daily" },
    cue: "“Thread your arm under and let your shoulder melt toward the floor — then reverse it and reach for the ceiling.”",
    patientInstructions:
      "Start on your hands and knees. Slide one arm underneath your body and across to the other side, letting that shoulder and the side of your head lower toward the floor. Hold a few seconds, then unwind and reach the same arm up to the ceiling. Six to eight times each side.",
    commonErrors: [
      "Letting the hips drift sideways instead of staying over the knees",
      "Collapsing the neck rather than lowering the shoulder",
      "Rushing so the rotation never actually reaches the mid-back",
    ],
    regression: "Open Book Rotation in sidelying, which takes weight off the shoulders and wrists.",
    progression: "Perform from a child's-pose position with the hips back on the heels, which localises it further to the thoracic spine.",
    precautions: [
      "Not appropriate where the wrists, knees, or shoulders won't tolerate weight-bearing.",
      "Avoid where a shoulder is post-operative or unstable until cleared.",
    ],
  },
  {
    id: "cat-cow",
    name: "Cat–Cow",
    aka: ["Cat–camel", "Spinal flexion–extension mobility"],
    region: "Thoracic & Rib",
    category: "Mobility",
    positions: ["Quadruped"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Thoracic spine", "Lumbar spine", "Cervical spine", "Spinal extensors"],
    indications: ["General spinal stiffness", "Morning back stiffness", "Warm-up before a spine program"],
    setup: "Hands and knees, hands under shoulders, knees under hips, spine in neutral.",
    steps: [
      "Breathe out and round the whole spine upward, tucking the tailbone and letting the head drop.",
      "Breathe in and reverse it — drop the belly, lift the tailbone and chest, and look slightly forward.",
      "Move slowly and continuously between the two, taking the whole spine through the range.",
    ],
    dosage: { sets: "1–2", reps: "10", frequency: "1–2x/day", loadOrTempo: "Slow, matched to the breath" },
    cue: "“Breathe out and round like an angry cat, breathe in and let your belly sink — move through the whole spine, not just the low back.”",
    patientInstructions:
      "On your hands and knees, breathe out and round your back up toward the ceiling, dropping your head. Then breathe in and let your belly sink down as you lift your chest and tailbone. Move slowly and let your breathing set the pace. Ten repetitions, once or twice a day.",
    commonErrors: [
      "Moving only through the low back while the mid-back stays flat",
      "Rushing so the movement never reaches end range in either direction",
      "Cranking the neck at the top and bottom",
    ],
    regression: "Do a seated version in a chair, moving between slumped and tall.",
    progression: "Add a hold at each end, or move into segmental control — rounding and extending one region at a time.",
    precautions: [
      "Reduce the flexion component in the first days after a disc-related flare if flexion clearly worsens symptoms.",
      "Needs comfortable weight-bearing through the wrists and knees.",
    ],
  },
  {
    id: "seated-thoracic-rotation",
    name: "Seated Thoracic Rotation",
    region: "Thoracic & Rib",
    category: "Mobility",
    positions: ["Seated"],
    equipment: ["Chair", "Cane or dowel"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore", "Strengthening"],
    targets: ["Thoracic rotators", "Obliques"],
    indications: ["Rotation restriction", "Difficulty with driving head checks", "Desk-based stiffness"],
    setup: "Sit tall on a firm chair, feet flat and knees together. Cross the arms on the chest, or hold a dowel across the shoulders.",
    steps: [
      "Keep the knees and pelvis facing straight forward — a pillow squeezed between the knees helps.",
      "Turn the chest and shoulders to one side as far as is comfortable.",
      "Hold briefly, return to centre, then rotate the other way.",
    ],
    dosage: { sets: "1–2", reps: "8–10 each side", hold: "2–3 s", frequency: "1–2x/day" },
    cue: "“Knees stay pointing forward — turn your ribcage, not your hips.”",
    patientInstructions:
      "Sit tall on a firm chair with your knees together and pointing forward. Cross your arms over your chest and turn your upper body to one side as far as is comfortable. Hold a couple of seconds, come back to the middle, then turn the other way. Eight to ten each side.",
    commonErrors: [
      "Letting the pelvis and knees rotate with the trunk",
      "Slumping, which locks out thoracic rotation before it starts",
      "Yanking into range instead of turning smoothly",
    ],
    regression: "Reduce range and drop the dowel; arms crossed only.",
    progression: "Open Book Rotation or Thread the Needle for a larger range in an unloaded position.",
    precautions: [
      "Keep it gentle after a recent rib injury.",
      "Stop for sharp chest wall pain.",
    ],
  },
  {
    id: "wall-angel",
    name: "Wall Angel",
    aka: ["Wall slide", "Wall shoulder flexion slide"],
    region: "Thoracic & Rib",
    category: "Motor Control",
    positions: ["Standing"],
    equipment: ["Wall"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Lower trapezius", "Serratus anterior", "Thoracic extensors", "Rotator cuff"],
    indications: ["Kyphotic posture", "Shoulder impingement", "Overhead reaching restriction", "Scapular control deficit"],
    setup: "Stand with the back against a wall, feet a few inches out from it, knees slightly bent. Flatten the low back gently toward the wall. Place the backs of the arms against the wall in a goalpost position.",
    steps: [
      "Keep the back of the head, upper back, elbows and wrists in contact with the wall.",
      "Slide the arms slowly up the wall as far as contact can be maintained.",
      "Stop at the point where any contact is lost — that is the working range, not a failure.",
      "Slide back down under control, drawing the elbows toward the ribs at the bottom.",
    ],
    dosage: { sets: "2–3", reps: "8–10", frequency: "Once daily", loadOrTempo: "Slow, about 3 s up and 3 s down" },
    cue: "“Keep every contact point on the wall — go only as high as you can without your ribs flaring or your wrists lifting off.”",
    patientInstructions:
      "Stand with your back against a wall, feet a few inches away, knees soft. Put your arms up against the wall in a goalpost shape. Slide your arms up the wall, keeping your head, upper back, elbows and wrists touching it the whole time. Stop as soon as anything lifts away, then slide back down slowly. Eight to ten repetitions.",
    commonErrors: [
      "Arching the low back off the wall to gain range",
      "Letting the wrists or elbows peel off the wall",
      "Shrugging the shoulders up toward the ears at the top",
      "Chasing full overhead range instead of working the range that can be controlled",
    ],
    regression: "Do it lying on the back on the floor, where the floor gives the same feedback with less demand.",
    progression: "Move the feet closer to the wall, or hold a light band between the hands for extra external rotation demand.",
    precautions: [
      "Painful arc or pinching means reduce the range rather than push through it.",
      "Follow the surgeon's range limits after shoulder surgery.",
    ],
  },
  {
    id: "prone-y-raise",
    name: "Prone Y Raise",
    aka: ["Prone Y", "Lower trapezius raise"],
    region: "Thoracic & Rib",
    category: "Strength",
    positions: ["Prone"],
    equipment: ["None", "Weight"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Lower trapezius", "Middle trapezius", "Thoracic extensors", "Posterior deltoid"],
    indications: ["Scapular downward rotation weakness", "Shoulder impingement", "Postural upper back weakness"],
    setup: "Lie face down with the forehead on a towel, arms out overhead at roughly 45 degrees from the body so the body forms a Y. Thumbs point up.",
    steps: [
      "Set the shoulder blades down toward the back pockets before the arms move at all.",
      "Lift both arms a few inches off the floor, keeping the elbows straight and thumbs up.",
      "Hold briefly at the top without shrugging.",
      "Lower slowly and reset.",
    ],
    dosage: { sets: "2–3", reps: "8–12", hold: "2–3 s", frequency: "Every other day", loadOrTempo: "Bodyweight first; add 1–2 lb only once form holds" },
    cue: "“Slide your shoulder blades toward your back pockets first, then lift — thumbs to the ceiling and no shrugging.”",
    patientInstructions:
      "Lie face down with your forehead on a towel and your arms out overhead in a Y shape, thumbs pointing up. Slide your shoulder blades down toward your back pockets, then lift both arms a few inches off the floor. Hold a couple of seconds and lower slowly. Eight to twelve repetitions, every other day.",
    commonErrors: [
      "Shrugging, so the upper trapezius does the lifting",
      "Lifting the arms high by arching the low back",
      "Adding weight before the unweighted version is clean",
    ],
    regression: "Lift one arm at a time, or do it standing leaning on a table.",
    progression: "Add a small hand weight, lengthen the hold, or progress to a Prone T Raise and then an incline bench version.",
    precautions: [
      "Follow post-operative shoulder restrictions on overhead positions.",
      "Not suitable for someone who cannot lie prone comfortably.",
    ],
  },
  {
    id: "prone-t-raise",
    name: "Prone T Raise",
    aka: ["Prone horizontal abduction", "Prone T"],
    region: "Thoracic & Rib",
    category: "Strength",
    positions: ["Prone"],
    equipment: ["None", "Weight"],
    difficulty: 3,
    phases: ["Strengthening", "Return to Activity"],
    targets: ["Middle trapezius", "Rhomboids", "Posterior deltoid"],
    indications: ["Scapular retractor weakness", "Rounded shoulder posture", "Shoulder rehabilitation"],
    setup: "Lie face down with the forehead on a towel and the arms straight out to the sides at shoulder height, forming a T. Thumbs up.",
    steps: [
      "Squeeze the shoulder blades together and down.",
      "Lift both arms off the floor without shrugging, keeping the elbows straight.",
      "Hold at the top.",
      "Lower slowly.",
    ],
    dosage: { sets: "2–3", reps: "8–12", hold: "2–3 s", frequency: "Every other day", loadOrTempo: "Bodyweight, progressing to 1–3 lb" },
    cue: "“Pinch your shoulder blades together first — the arms only come up because your blades did.”",
    patientInstructions:
      "Lie face down with your forehead on a towel and your arms straight out to the sides like a T, thumbs pointing up. Squeeze your shoulder blades together and lift your arms off the floor. Hold a couple of seconds, then lower slowly. Eight to twelve repetitions, every other day.",
    commonErrors: [
      "Shrugging the shoulders toward the ears",
      "Bending the elbows to make the lift easier",
      "Extending the low back to get the arms higher",
    ],
    regression: "One arm at a time, or a smaller lift height.",
    progression: "Add light hand weights, or move to a bent-over or incline-bench version.",
    precautions: [
      "Follow post-operative shoulder restrictions.",
      "Reduce range if it reproduces pinching at the front of the shoulder.",
    ],
  },
  {
    id: "diaphragmatic-breathing",
    name: "Diaphragmatic Breathing",
    aka: ["Belly breathing", "Abdominal breathing"],
    region: "Thoracic & Rib",
    category: "Motor Control",
    positions: ["Supine", "Seated"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Diaphragm", "Deep abdominal wall", "Pelvic floor"],
    indications: ["Upper-chest breathing pattern", "Persistent pain", "Anxiety-related muscle guarding", "Pre-requisite for core motor control work", "Post-operative respiratory care"],
    setup: "Lie on the back with knees bent, one hand on the chest and one on the belly. It can also be done seated once the pattern is learned.",
    steps: [
      "Breathe in slowly through the nose so the hand on the belly rises and the hand on the chest stays relatively quiet.",
      "Feel the lower ribs widen sideways as well as the belly rising.",
      "Breathe out slowly and fully through the mouth, letting the ribs settle down.",
      "Keep the shoulders and jaw relaxed throughout.",
    ],
    dosage: { sets: "1–2", reps: "8–10 breaths", frequency: "1–3x/day", loadOrTempo: "Aim for the out-breath to be longer than the in-breath" },
    cue: "“Breathe in so the hand on your belly moves and the hand on your chest doesn't — then let the breath out slowly, longer than it went in.”",
    patientInstructions:
      "Lie on your back with your knees bent. Put one hand on your chest and one on your belly. Breathe in slowly through your nose so the hand on your belly rises while the hand on your chest stays fairly still. Breathe out slowly through your mouth, taking longer to breathe out than in. Eight to ten breaths, a few times a day.",
    commonErrors: [
      "Pushing the belly out with the abdominal muscles instead of letting the breath do it",
      "Lifting the shoulders and chest on the in-breath",
      "Breathing so deeply it becomes light-headed — the point is slow and easy, not maximal",
    ],
    regression: "Reduce to 4–5 breaths, or do it sidelying where the pattern is often easier to feel.",
    progression: "Move to seated, then standing, then combine with a core motor-control drill such as the dead bug.",
    precautions: [
      "Stop if it causes light-headedness or tingling around the mouth or hands.",
      "Follow specific respiratory instructions where a lung condition or recent chest surgery is involved.",
    ],
  },
  {
    id: "lateral-costal-expansion",
    name: "Lateral Costal Expansion",
    aka: ["Rib expansion breathing", "Lateral basal breathing"],
    region: "Thoracic & Rib",
    category: "Mobility",
    positions: ["Seated", "Supine"],
    equipment: ["Towel or strap"],
    difficulty: 2,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Intercostals", "Costovertebral joints", "Diaphragm"],
    indications: ["Rib cage stiffness", "Post-thoracic surgery mobility", "Rib fracture recovery (once cleared)", "Restricted chest expansion"],
    setup: "Sit tall or lie on the back. Wrap a towel around the lower ribs and hold the ends crossed in front, or place both hands on the sides of the lower ribs.",
    steps: [
      "Apply light tension on the towel as you breathe out.",
      "Breathe in and push the lower ribs out sideways against the towel or hands.",
      "Hold the fullest comfortable breath for a moment.",
      "Breathe out slowly, letting the towel take up the slack again.",
    ],
    dosage: { sets: "1–2", reps: "6–10 breaths", frequency: "2–3x/day" },
    cue: "“Breathe sideways into my hands — widen your ribs rather than lifting your chest.”",
    patientInstructions:
      "Wrap a towel around your lower ribs and hold the ends crossed in front of you. As you breathe out, pull the towel gently snug. As you breathe in, push your lower ribs out sideways against the towel. Breathe out slowly again. Six to ten breaths, two or three times a day.",
    commonErrors: [
      "Lifting the chest and shoulders instead of expanding sideways",
      "Pulling the towel too tight, which restricts rather than cues",
      "Breathing fast enough to become light-headed",
    ],
    regression: "Use hands only rather than a towel, with a smaller breath.",
    progression: "Combine with a trunk side-bend or an open book rotation to bias one side of the rib cage.",
    precautions: [
      "Keep it comfortable after rib fracture or chest surgery, and follow the treating team's guidance.",
      "Stop for chest pain, breathlessness beyond the expected effort, or light-headedness.",
    ],
  },
  {
    id: "quadruped-thoracic-rotation",
    name: "Quadruped Thoracic Rotation",
    aka: ["Hand behind head rotation", "Quadruped rotation"],
    region: "Thoracic & Rib",
    category: "Mobility",
    positions: ["Quadruped"],
    equipment: ["None"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Thoracic rotators", "Obliques"],
    indications: ["Thoracic rotation restriction", "Rotational sport preparation", "Upper back stiffness"],
    setup: "Kneel on hands and knees. Sit the hips back slightly toward the heels to reduce lumbar contribution. Place one hand behind the head, elbow out.",
    steps: [
      "Rotate the elbow down toward the opposite hand, rounding gently.",
      "Reverse it and rotate the elbow up toward the ceiling, turning the chest to follow.",
      "Keep the hips still and level — the movement belongs to the ribs.",
      "Move slowly through the full available range each way.",
    ],
    dosage: { sets: "1–2", reps: "8–10 each side", hold: "2 s at the top", frequency: "Once daily" },
    cue: "“Point your elbow at the ceiling and let your chest follow it — hips stay square to the floor.”",
    patientInstructions:
      "On hands and knees, sit your hips back a little toward your heels. Put one hand behind your head. Bring that elbow down toward your other hand, then rotate it up toward the ceiling, turning your chest to follow. Keep your hips still. Eight to ten each side.",
    commonErrors: [
      "Letting the hips rotate with the trunk",
      "Rotating from the neck rather than the mid-back",
      "Losing the hips-back position, which lets the low back do the work",
    ],
    regression: "Open Book Rotation in sidelying.",
    progression: "Hold the top position for a full breath, or add a light band resistance.",
    precautions: [
      "Needs comfortable weight-bearing through the wrist and shoulder of the supporting arm.",
      "Stay within a comfortable range with recent rib or chest wall pain.",
    ],
  },
];
