import type { MovementExercise } from "@/lib/movement-lab/types";

/** Elbow, wrist and hand. Built around the two things this region is actually referred for —
 *  tendinopathy at the elbow (which needs graded eccentric loading, not rest) and post-cast
 *  or post-operative hand stiffness (which needs range, tendon glides and grip). */
export const UPPER_LIMB_EXERCISES: MovementExercise[] = [
  {
    id: "elbow-arom",
    name: "Elbow Flexion and Extension (Active Range)",
    region: "Elbow, Wrist & Hand",
    category: "Mobility",
    positions: ["Seated", "Standing"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Elbow joint", "Biceps", "Triceps"],
    indications: ["Post-immobilisation elbow stiffness", "Post-fracture elbow rehabilitation", "Sling phase after shoulder surgery", "Elbow contracture"],
    setup: "Sit with the upper arm supported on a table or against the side of the body.",
    steps: [
      "Bend the elbow, bringing the hand toward the shoulder as far as is comfortable.",
      "Hold briefly at the end of the range.",
      "Straighten the elbow as far as it will go.",
      "Hold at full extension — this is usually the harder direction to regain.",
    ],
    dosage: { sets: "2–3", reps: "10–15", hold: "5 s at each end", frequency: "3–4x/day early on, then 1–2x/day" },
    cue: "“All the way bent, then all the way straight — and hold a few seconds at each end, especially straight.”",
    patientInstructions:
      "Sit with your upper arm resting on a table. Bend your elbow to bring your hand toward your shoulder as far as is comfortable, hold five seconds, then straighten it as far as it will go and hold five seconds. Ten to fifteen repetitions, several times a day.",
    commonErrors: [
      "Working only the bending direction and neglecting full straightening",
      "Moving the shoulder to make the range look bigger",
      "Rushing so neither end range is reached",
    ],
    regression: "Use the other hand to assist the movement, or do it lying with the arm supported.",
    progression: "Add a light weight, or add a gentle end-range hold with over-pressure.",
    precautions: [
      "Follow the surgeon's protocol after elbow fracture or surgery — aggressive stretching of a stiff elbow can worsen it.",
      "Stop for sharp pain or a hard block at end range, and report it.",
      "Report new swelling, warmth, or a rapidly worsening range.",
    ],
  },
  {
    id: "forearm-rotation",
    name: "Forearm Pronation and Supination",
    aka: ["Palm up, palm down", "Forearm rotation"],
    region: "Elbow, Wrist & Hand",
    category: "Mobility",
    positions: ["Seated"],
    equipment: ["None", "Weight", "Cane or dowel"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore", "Strengthening"],
    targets: ["Radioulnar joints", "Pronator teres", "Supinator", "Biceps"],
    indications: ["Post-fracture forearm stiffness", "Post-immobilisation", "Difficulty turning a key or a door handle", "Elbow tendinopathy"],
    setup: "Sit with the elbow tucked at the side and bent to 90 degrees, forearm resting on a table with the hand off the edge.",
    steps: [
      "Turn the palm to face upward as far as is comfortable.",
      "Hold at the end of the range.",
      "Turn the palm to face downward as far as is comfortable.",
      "Keep the elbow pinned at the side — the shoulder must not rotate to help.",
    ],
    dosage: { sets: "2–3", reps: "10–15", hold: "3–5 s each way", frequency: "2–3x/day" },
    cue: "“Elbow stays glued to your side — turn your palm up like you're holding a bowl of soup, then turn it over to pour it out.”",
    patientInstructions:
      "Sit with your elbow tucked at your side and bent to a right angle, forearm resting on a table. Turn your palm up as far as it will go, hold a few seconds, then turn it down and hold. Keep your elbow at your side. Ten to fifteen repetitions each way.",
    commonErrors: [
      "Letting the elbow move away from the side, so the shoulder does the rotating",
      "A small range that never reaches the end of the available movement",
      "Rushing",
    ],
    regression: "Use the other hand to assist the rotation.",
    progression: "Hold a light hammer or a weighted dowel at one end, which adds a rotational load.",
    precautions: [
      "Follow post-fracture and post-operative protocols.",
      "Stop for sharp pain at the wrist or elbow.",
    ],
  },
  {
    id: "wrist-arom",
    name: "Wrist Flexion and Extension (Active Range)",
    region: "Elbow, Wrist & Hand",
    category: "Mobility",
    positions: ["Seated"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Wrist joint", "Wrist flexors", "Wrist extensors"],
    indications: ["Post-cast wrist stiffness", "Post distal radius fracture", "Carpal tunnel symptoms", "General wrist mobility"],
    setup: "Sit with the forearm resting on a table and the hand hanging off the edge, palm down.",
    steps: [
      "Lift the hand upward as far as is comfortable, bending the wrist back.",
      "Hold briefly at the end of the range.",
      "Lower the hand downward as far as is comfortable.",
      "Keep the forearm flat on the table throughout.",
    ],
    dosage: { sets: "2–3", reps: "10–15", hold: "3–5 s", frequency: "3–4x/day early on, then 1–2x/day" },
    cue: "“Forearm stays on the table — only your hand moves, up as far as it goes and then down.”",
    patientInstructions:
      "Sit with your forearm on a table and your hand hanging over the edge, palm down. Lift your hand up as far as is comfortable, hold a few seconds, then lower it down as far as is comfortable. Keep your forearm on the table. Ten to fifteen repetitions.",
    commonErrors: [
      "Lifting the forearm off the table",
      "A small, tentative range",
      "Making a fist, which changes the movement",
    ],
    regression: "Use the other hand to assist through the range.",
    progression: "Add a light weight, or add end-range over-pressure with the other hand.",
    precautions: [
      "Follow the protocol after a distal radius fracture or wrist surgery.",
      "Stop for sharp pain, and report new numbness or tingling in the hand.",
    ],
  },
  {
    id: "wrist-deviation",
    name: "Wrist Radial and Ulnar Deviation",
    aka: ["Side-to-side wrist movement"],
    region: "Elbow, Wrist & Hand",
    category: "Mobility",
    positions: ["Seated"],
    equipment: ["None", "Weight"],
    difficulty: 1,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Wrist joint", "Radial deviators", "Ulnar deviators"],
    indications: ["Post-cast wrist stiffness", "De Quervain's-related restriction (once settling)", "Grip and tool use difficulty"],
    setup: "Sit with the forearm on a table, thumb up and the hand off the edge.",
    steps: [
      "Move the hand upward toward the thumb side.",
      "Hold briefly, then move downward toward the little-finger side.",
      "Keep the forearm still on the table.",
    ],
    dosage: { sets: "2", reps: "10–15 each direction", hold: "2–3 s", frequency: "1–2x/day" },
    cue: "“Thumb up — now move your hand side to side like waving a small hammer, keeping your forearm still.”",
    patientInstructions:
      "Rest your forearm on a table with your thumb pointing up and your hand off the edge. Move your hand up toward your thumb side, then down toward your little finger side. Keep your forearm still. Ten to fifteen each way.",
    commonErrors: [
      "Rotating the forearm rather than deviating the wrist",
      "Lifting the forearm off the table",
      "Working through sharp thumb-side pain, which often means the wrong exercise for the problem",
    ],
    regression: "Assist with the other hand, smaller range.",
    progression: "Hold a light hammer or a small weight at the far end for a leverage challenge.",
    precautions: [
      "Stop for sharp thumb-side wrist pain — that pattern needs assessment rather than more range work.",
      "Follow post-fracture protocols.",
    ],
  },
  {
    id: "eccentric-wrist-extension",
    name: "Eccentric Wrist Extension",
    aka: ["Tennis elbow eccentrics", "Slow wrist extensor lowering"],
    region: "Elbow, Wrist & Hand",
    category: "Strength",
    positions: ["Seated"],
    equipment: ["Weight", "Table or counter"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Wrist extensors", "Extensor carpi radialis brevis", "Common extensor tendon"],
    indications: ["Lateral elbow tendinopathy", "Tennis elbow", "Grip pain with wrist extensor weakness"],
    setup: "Sit with the forearm resting on a table, palm down and the hand off the edge, holding a light weight.",
    steps: [
      "Use the other hand to lift the weighted hand up into wrist extension.",
      "Let go, and lower the weight slowly over three to four seconds until the wrist is fully bent down.",
      "Use the other hand to raise it again — the lowering is the exercise.",
      "Keep the elbow straight or slightly bent, and keep it in the same position throughout.",
    ],
    dosage: { sets: "3", reps: "15", frequency: "Once daily", loadOrTempo: "3–4 s lowering; start at 1–2 lb and build slowly" },
    cue: "“Help it up with your other hand and lower it as slowly as you possibly can — the slow lowering is the whole exercise.”",
    patientInstructions:
      "Sit with your forearm on a table, palm down, hand off the edge, holding a light weight. Use your other hand to lift the weighted hand up. Let go and lower the weight slowly over three or four seconds until your wrist is fully bent down. Use your other hand to lift it back up. Fifteen repetitions, three sets, once a day. Some ache in the elbow during this is expected — it should settle within a day.",
    commonErrors: [
      "Lifting the weight with the working wrist instead of the other hand",
      "Lowering too quickly",
      "Starting with too much weight",
      "Expecting it to be pain-free — some discomfort is part of loading a tendon",
    ],
    regression: "No weight at all, or use a lighter object; reduce to two sets.",
    progression: "Add weight in small increments — often as little as half a pound at a time.",
    precautions: [
      "Expect some discomfort during and after; symptoms should settle within twenty-four hours. Worsening day to day means the load is too high.",
      "This is a graded loading programme, not a quick fix — expect it to take weeks to months.",
      "Stop for pins and needles in the hand, which points to a different problem.",
    ],
  },
  {
    id: "eccentric-wrist-flexion",
    name: "Eccentric Wrist Flexion",
    aka: ["Golfer's elbow eccentrics", "Slow wrist flexor lowering"],
    region: "Elbow, Wrist & Hand",
    category: "Strength",
    positions: ["Seated"],
    equipment: ["Weight", "Table or counter"],
    difficulty: 3,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Wrist flexors", "Common flexor tendon", "Pronator teres"],
    indications: ["Medial elbow tendinopathy", "Golfer's elbow", "Grip pain with wrist flexor involvement"],
    setup: "Sit with the forearm resting on a table, palm up and the hand off the edge, holding a light weight.",
    steps: [
      "Use the other hand to lift the weighted hand up into wrist flexion.",
      "Let go, and lower the weight slowly over three to four seconds until the wrist is fully extended back.",
      "Use the other hand to raise it again.",
      "Keep the forearm still on the table throughout.",
    ],
    dosage: { sets: "3", reps: "15", frequency: "Once daily", loadOrTempo: "3–4 s lowering; start at 1–2 lb" },
    cue: "“Palm up this time — help it up, then lower it as slowly as you can.”",
    patientInstructions:
      "Sit with your forearm on a table, palm up, hand off the edge, holding a light weight. Use your other hand to lift the weighted hand up. Let go and lower the weight slowly over three or four seconds. Lift it back up with your other hand. Fifteen repetitions, three sets, once a day.",
    commonErrors: [
      "Lifting with the working wrist rather than the other hand",
      "Lowering too fast",
      "Starting with too much weight",
    ],
    regression: "No weight, or fewer sets.",
    progression: "Add weight in small increments.",
    precautions: [
      "Expect some discomfort that settles within a day; worsening day to day means reduce the load.",
      "Stop for pins and needles in the ring and little fingers, which points to nerve involvement at the elbow.",
    ],
  },
  {
    id: "wrist-extensor-stretch",
    name: "Wrist Extensor Stretch",
    aka: ["Tennis elbow stretch"],
    region: "Elbow, Wrist & Hand",
    category: "Flexibility",
    positions: ["Standing", "Seated"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Wrist extensors", "Common extensor tendon"],
    indications: ["Lateral elbow tendinopathy", "Forearm tightness", "Desk and tool-use related forearm pain"],
    setup: "Stand or sit with the involved arm out in front, elbow straight and the palm facing down.",
    steps: [
      "Let the wrist drop so the fingers point toward the floor.",
      "Use the other hand to gently draw the hand further down and slightly toward the little-finger side.",
      "Keep the elbow completely straight — bending it removes most of the stretch.",
      "Hold, breathing normally.",
    ],
    dosage: { sets: "3", reps: "1 each side", hold: "30 s", frequency: "2–3x/day" },
    cue: "“Elbow completely straight, fingers pointing down, and draw the hand gently toward you — you'll feel it in the top of your forearm.”",
    patientInstructions:
      "Hold your arm straight out in front of you, palm down. Let your wrist drop so your fingers point at the floor, then use your other hand to gently pull it further. Keep your elbow straight. Hold thirty seconds. Three times, a few times a day.",
    commonErrors: [
      "Bending the elbow, which loses the stretch",
      "Pulling hard enough to cause sharp pain at the elbow",
      "Holding the breath",
    ],
    regression: "Reduce the pull; hold for 15 seconds.",
    progression: "Add the slight ulnar deviation, and hold longer.",
    precautions: [
      "Stop for sharp pain at the elbow rather than a forearm stretch.",
      "Stop for pins and needles in the hand.",
    ],
  },
  {
    id: "wrist-flexor-stretch",
    name: "Wrist Flexor Stretch",
    aka: ["Golfer's elbow stretch"],
    region: "Elbow, Wrist & Hand",
    category: "Flexibility",
    positions: ["Standing", "Seated"],
    equipment: ["None", "Wall"],
    difficulty: 1,
    phases: ["Subacute / Restore", "Strengthening", "Return to Activity"],
    targets: ["Wrist flexors", "Common flexor tendon"],
    indications: ["Medial elbow tendinopathy", "Forearm tightness", "Grip-heavy work or sport"],
    setup: "Hold the involved arm out in front with the elbow straight and the palm facing up.",
    steps: [
      "Use the other hand to draw the fingers and palm back toward the floor.",
      "Keep the elbow completely straight.",
      "Hold, breathing normally.",
      "Release slowly.",
    ],
    dosage: { sets: "3", reps: "1 each side", hold: "30 s", frequency: "2–3x/day" },
    cue: "“Palm up, elbow locked straight, and draw your fingers back toward the floor — you'll feel it along the underside of your forearm.”",
    patientInstructions:
      "Hold your arm straight out in front with your palm facing up. Use your other hand to gently pull your fingers and palm back toward the floor. Keep your elbow straight. Hold thirty seconds, three times.",
    commonErrors: [
      "Bending the elbow",
      "Pulling only the fingers rather than the whole hand",
      "Pulling into sharp pain",
    ],
    regression: "Do it with the elbow slightly bent, then straighten it as tolerance improves.",
    progression: "Hold longer, or add a slight forearm rotation.",
    precautions: [
      "Stop for sharp elbow pain.",
      "Stop for tingling in the ring and little fingers.",
    ],
  },
  {
    id: "grip-squeeze",
    name: "Grip Strengthening",
    aka: ["Ball squeeze", "Putty squeeze", "Grip exercise"],
    region: "Elbow, Wrist & Hand",
    category: "Strength",
    positions: ["Seated", "Standing"],
    equipment: ["Ball"],
    difficulty: 1,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Finger flexors", "Intrinsic hand muscles", "Forearm flexors"],
    indications: ["Grip weakness", "Post-cast hand weakness", "Post-fracture rehabilitation", "General hand conditioning"],
    setup: "Sit or stand holding a soft ball, rolled towel, or therapy putty in the hand.",
    steps: [
      "Squeeze the ball, building the effort over a second or two.",
      "Hold at a comfortable, submaximal effort.",
      "Release gradually and open the hand fully.",
      "Keep the wrist in a neutral, straight position throughout.",
    ],
    dosage: { sets: "2–3", reps: "10–15", hold: "5 s", frequency: "1–2x/day", loadOrTempo: "Start submaximal and build over weeks" },
    cue: "“Squeeze to about three-quarters effort, hold, then open your hand all the way — the opening matters as much as the squeezing.”",
    patientInstructions:
      "Hold a soft ball or rolled towel in your hand. Squeeze it, hold for five seconds, then release and open your hand fully. Ten to fifteen repetitions, once or twice a day.",
    commonErrors: [
      "Squeezing maximally from the first session",
      "Never fully opening the hand between repetitions",
      "Letting the wrist bend during the squeeze",
      "Holding the breath",
    ],
    regression: "Use a softer ball and a shorter hold.",
    progression: "Firmer ball or putty, longer holds, then add pinch grip work between thumb and each finger.",
    precautions: [
      "Follow post-fracture and post-tendon-repair protocols — grip loading is staged carefully after a flexor tendon repair.",
      "Stop for sharp pain or increasing numbness.",
    ],
  },
  {
    id: "finger-extension-band",
    name: "Finger Extension with a Band",
    aka: ["Rubber band finger extension", "Extensor strengthening"],
    region: "Elbow, Wrist & Hand",
    category: "Strength",
    positions: ["Seated"],
    equipment: ["Resistance band"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Finger extensors", "Intrinsic hand muscles"],
    indications: ["Lateral elbow tendinopathy", "Grip and release imbalance", "Hand conditioning after immobilisation"],
    setup: "Loop a rubber band or small resistance loop around all five fingers and the thumb, with the hand resting on a table.",
    steps: [
      "Start with the fingers and thumb together inside the band.",
      "Spread the fingers and thumb apart against the band's resistance.",
      "Hold briefly at the end of the range.",
      "Close slowly against the band rather than letting it snap the fingers together.",
    ],
    dosage: { sets: "2–3", reps: "15–20", hold: "2 s", frequency: "Once daily" },
    cue: "“Open your hand against the band, hold, then close it slowly — don't let it snap shut.”",
    patientInstructions:
      "Put a rubber band around all your fingers and thumb. Spread your fingers and thumb apart against the band, hold a couple of seconds, then close them slowly. Fifteen to twenty repetitions.",
    commonErrors: [
      "Letting the band snap the fingers closed",
      "Using a band so tight the fingers barely move",
      "Bending the wrist to help",
    ],
    regression: "Use a lighter band or fewer fingers.",
    progression: "Heavier band, more repetitions, or add sustained holds.",
    precautions: [
      "Follow post-operative hand protocols.",
      "Stop for joint pain in the fingers rather than muscle effort.",
    ],
  },
  {
    id: "tendon-glides",
    name: "Finger Tendon Glides",
    aka: ["Flexor tendon glides", "Hand tendon gliding series"],
    region: "Elbow, Wrist & Hand",
    category: "Mobility",
    positions: ["Seated"],
    equipment: ["None"],
    difficulty: 2,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Flexor tendons", "Finger joints", "Hand soft tissue"],
    indications: ["Post-cast hand stiffness", "Carpal tunnel syndrome", "Hand oedema", "Post-fracture hand rehabilitation"],
    setup: "Sit with the forearm supported and the hand free, fingers straight.",
    steps: [
      "Start with all fingers straight, hand flat.",
      "Make a hook fist — bend the two end joints of each finger while keeping the knuckles straight.",
      "Return to straight, then make a full fist with the fingers curled all the way in.",
      "Return to straight, then make a tabletop position — knuckles bent, other joints straight.",
      "Move through the whole series slowly, returning to straight between each position.",
    ],
    dosage: { sets: "1–2", reps: "5–10 full series", hold: "3 s in each position", frequency: "3–5x/day" },
    cue: "“Straight, hook, full fist, tabletop — back to straight between each one. Slow and deliberate.”",
    patientInstructions:
      "Start with your fingers straight. Bend just the ends of your fingers into a hook shape and hold three seconds, then straighten. Make a full fist and hold, then straighten. Bend just your knuckles so your fingers stay straight, hold, then straighten. Repeat the whole series five to ten times, several times a day.",
    commonErrors: [
      "Skipping positions and just making a fist",
      "Moving quickly so the tendons don't actually glide through the range",
      "Forcing stiff joints rather than working to a firm stretch",
    ],
    regression: "Use the other hand to assist each position gently.",
    progression: "Hold each position longer, or add gentle over-pressure with the other hand.",
    precautions: [
      "Follow the hand therapist's or surgeon's protocol exactly after a tendon repair — the permitted positions are specific.",
      "Stop for sharp pain or a sudden loss of the ability to bend a finger, and report it immediately.",
    ],
  },
  {
    id: "thumb-opposition",
    name: "Thumb Opposition",
    aka: ["Thumb to fingertips", "Opposition series"],
    region: "Elbow, Wrist & Hand",
    category: "Mobility",
    positions: ["Seated"],
    equipment: ["None"],
    difficulty: 1,
    phases: ["Acute / Protected", "Subacute / Restore"],
    targets: ["Thenar muscles", "Thumb joints", "Median nerve distribution"],
    indications: ["Carpal tunnel syndrome", "Thumb stiffness", "Post-immobilisation hand", "Fine motor difficulty"],
    setup: "Sit with the forearm supported and the hand free, palm up.",
    steps: [
      "Touch the tip of the thumb to the tip of the index finger, making a circle.",
      "Return the thumb to the starting position.",
      "Repeat with the middle, ring and little fingers in turn.",
      "Reach the thumb across the palm to the base of the little finger as the final position.",
    ],
    dosage: { sets: "2", reps: "5 full series", hold: "3 s at each contact", frequency: "2–3x/day" },
    cue: "“Make a round O with your thumb and each fingertip in turn — hold each one for a moment.”",
    patientInstructions:
      "With your palm up, touch the tip of your thumb to the tip of your index finger, making a round circle, and hold three seconds. Then do the same with your middle, ring and little fingers. Finish by reaching your thumb across your palm to the base of your little finger. Repeat the whole series five times.",
    commonErrors: [
      "Bringing the fingers to the thumb rather than the thumb to the fingers",
      "Making a flat pinch rather than a round circle",
      "Rushing through without holding each contact",
    ],
    regression: "Work only with the index and middle fingers to start.",
    progression: "Add resistance by holding against the thumb, or add small-object manipulation.",
    precautions: [
      "Follow post-operative hand protocols.",
      "Report progressive thumb weakness or wasting at the base of the thumb rather than treating it with exercise alone.",
    ],
  },
  {
    id: "radial-nerve-glide",
    name: "Radial Nerve Glide",
    aka: ["Radial nerve floss"],
    region: "Elbow, Wrist & Hand",
    category: "Neurodynamic",
    positions: ["Standing", "Seated"],
    equipment: ["None"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Radial nerve", "Neural interface tissue"],
    indications: ["Radial nerve irritation", "Lateral elbow pain with a neural component", "Forearm and hand symptoms after immobilisation"],
    setup: "Stand tall with the arm down at the side, palm facing backward.",
    steps: [
      "Take the arm slightly behind the body, turn the palm outward and bend the wrist and fingers down, while tipping the head *toward* that arm.",
      "Then bring the arm forward, relax the wrist, and tip the head *away* from the arm.",
      "Move rhythmically between the two positions.",
      "Stay short of reproducing strong symptoms throughout.",
    ],
    dosage: { sets: "1–2", reps: "8–10", frequency: "1–2x/day", loadOrTempo: "Slow and rhythmic; no end-range hold" },
    cue: "“Arm back and wrist down with your head coming toward it; arm forward and wrist relaxed with your head going away. Keep it moving.”",
    patientInstructions:
      "Stand tall with your arm by your side, palm facing backwards. Take the arm slightly behind you, bend your wrist and fingers down, and tip your head toward that arm. Then bring the arm forward, relax your wrist, and tip your head away. Move smoothly back and forth eight to ten times. You may feel a light pulling — you should not be provoking strong symptoms.",
    commonErrors: [
      "Holding the end position like a stretch",
      "Moving the head and arm in the same direction",
      "Doing too many repetitions on the first day",
    ],
    regression: "Move the wrist and elbow only, keeping the head and shoulder still.",
    progression: "Add shoulder depression, or increase the range — one variable at a time.",
    precautions: [
      "Symptoms increasing for hours afterward mean the dose was too high.",
      "Progressive weakness or numbness needs assessment rather than more nerve gliding.",
    ],
  },
  {
    id: "ulnar-nerve-glide",
    name: "Ulnar Nerve Glide",
    aka: ["Ulnar nerve floss", "Cubital tunnel glide"],
    region: "Elbow, Wrist & Hand",
    category: "Neurodynamic",
    positions: ["Standing", "Seated"],
    equipment: ["None"],
    difficulty: 2,
    phases: ["Subacute / Restore", "Strengthening"],
    targets: ["Ulnar nerve", "Cubital tunnel", "Neural interface tissue"],
    indications: ["Cubital tunnel syndrome", "Tingling in the ring and little fingers", "Ulnar-sided forearm symptoms"],
    setup: "Stand tall with the arm out to the side at about shoulder height.",
    steps: [
      "Bend the elbow and bring the hand toward the face, making a circle with the thumb and index finger, while tipping the head *away* from the arm.",
      "Then straighten the elbow, take the hand away, and tip the head *toward* the arm.",
      "Move rhythmically between the two — do not hold the end position.",
      "Keep well short of reproducing strong tingling.",
    ],
    dosage: { sets: "1", reps: "6–10", frequency: "Once daily", loadOrTempo: "Slow and rhythmic; no end-range hold" },
    cue: "“Hand comes to your face as your head goes away; hand goes away as your head comes toward it. Small, smooth, and never held.”",
    patientInstructions:
      "Stand tall with your arm out to the side at shoulder height. Bend your elbow to bring your hand toward your face, making a circle with your thumb and index finger, while tipping your head away from that arm. Then straighten your elbow and tip your head toward the arm. Move smoothly back and forth six to ten times, once a day. Stop if you get strong tingling.",
    commonErrors: [
      "Holding the elbow fully bent, which is the position that most provokes the ulnar nerve",
      "Doing too many repetitions — this nerve is easily irritated",
      "Moving into strong tingling rather than staying under it",
    ],
    regression: "Move the wrist and hand only, keeping the elbow and head still.",
    progression: "Increase the range slowly, one variable at a time.",
    precautions: [
      "The ulnar nerve is easily over-dosed — start with very few repetitions and stop if symptoms increase afterward.",
      "Avoid sustained full elbow flexion, including sleeping with the elbow bent, while symptoms are active.",
      "Progressive weakness, clumsiness, or muscle wasting in the hand needs prompt assessment.",
    ],
  },
];
